// viewers/pptx/packages/angular/src/viewer/options-quick-access-pane.component.ts
/**
 * options-quick-access-pane.component.ts: Options > Quick Access Toolbar pane
 * (Angular port of React's `settings/OptionsQuickAccessPane.tsx`).
 *
 * PowerPoint's dual-list command chooser over the shared
 * {@link QUICK_ACCESS_COMMAND_CATALOG}: available commands on the left, the
 * current toolbar on the right, Add/Remove between them, reorder arrows, and a
 * Reset back to {@link DEFAULT_QUICK_ACCESS_COMMAND_IDS}.
 */
import { ChangeDetectionStrategy, Component, computed, input, output, signal } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import {
	addQuickAccessCommand,
	availableQuickAccessCommands,
	DEFAULT_QUICK_ACCESS_COMMAND_IDS,
	getQuickAccessCommand,
	moveQuickAccessCommand,
	removeQuickAccessCommand,
} from 'ooxml-ui/pptx';
import type { ViewerOptions } from 'ooxml-ui/pptx';

@Component({
	selector: 'pptx-options-quick-access-pane',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<div class="pptx-ng-options-qat">
			<div class="pptx-ng-options-qat-lists">
				<div class="pptx-ng-options-qat-col">
					<p>{{ 'pptx.options.quickAccess.chooseCommands' | translate }}</p>
					<div
						role="listbox"
						[attr.aria-label]="'pptx.options.quickAccess.chooseCommands' | translate"
					>
						@for (id of available(); track id) {
							<button
								type="button"
								role="option"
								[attr.aria-selected]="selectedAvailable() === id"
								[class.is-selected]="selectedAvailable() === id"
								(click)="selectedAvailable.set(id)"
							>
								{{ labelKey(id) | translate }}
							</button>
						}
					</div>
				</div>
				<div class="pptx-ng-options-qat-actions">
					<button
						type="button"
						class="pptx-ng-options-btn"
						[disabled]="!selectedAvailable()"
						(click)="add()"
					>
						{{ 'pptx.options.quickAccess.add' | translate }} &raquo;
					</button>
					<button
						type="button"
						class="pptx-ng-options-btn"
						[disabled]="!selectedCurrent()"
						(click)="remove()"
					>
						&laquo; {{ 'pptx.options.quickAccess.remove' | translate }}
					</button>
				</div>
				<div class="pptx-ng-options-qat-col">
					<p>{{ 'pptx.options.quickAccess.currentCommands' | translate }}</p>
					<div
						role="listbox"
						[attr.aria-label]="'pptx.options.quickAccess.currentCommands' | translate"
					>
						@for (id of current(); track id) {
							<button
								type="button"
								role="option"
								[attr.aria-selected]="selectedCurrent() === id"
								[class.is-selected]="selectedCurrent() === id"
								(click)="selectedCurrent.set(id)"
							>
								{{ labelKey(id) | translate }}
							</button>
						}
					</div>
				</div>
				<div class="pptx-ng-options-qat-actions">
					<button
						type="button"
						class="pptx-ng-options-btn"
						[disabled]="!selectedCurrent()"
						[attr.aria-label]="'pptx.options.quickAccess.moveUp' | translate"
						(click)="move('up')"
					>
						&#9650;
					</button>
					<button
						type="button"
						class="pptx-ng-options-btn"
						[disabled]="!selectedCurrent()"
						[attr.aria-label]="'pptx.options.quickAccess.moveDown' | translate"
						(click)="move('down')"
					>
						&#9660;
					</button>
				</div>
			</div>
			<button type="button" class="pptx-ng-options-btn" (click)="reset()">
				{{ 'pptx.options.quickAccess.reset' | translate }}
			</button>
		</div>
	`,
	styles: [
		`
			.pptx-ng-options-qat {
				display: flex;
				flex-direction: column;
				gap: 10px;
			}
			.pptx-ng-options-qat-lists {
				display: flex;
				align-items: stretch;
				gap: 10px;
			}
			.pptx-ng-options-qat-col {
				flex: 1;
				min-width: 0;
			}
			.pptx-ng-options-qat-col p {
				margin: 0 0 4px;
				color: var(--pptx-muted-foreground);
				font-size: 11px;
				font-weight: 600;
			}
			.pptx-ng-options-qat-col [role='listbox'] {
				height: 190px;
				overflow-y: auto;
				padding: 4px;
				border: 1px solid var(--pptx-border);
				border-radius: 6px;
			}
			.pptx-ng-options-qat-col [role='option'] {
				display: block;
				width: 100%;
				padding: 5px 8px;
				border: 0;
				border-radius: 4px;
				background: transparent;
				color: var(--pptx-foreground);
				font-size: 13px;
				text-align: left;
				cursor: pointer;
			}
			.pptx-ng-options-qat-col [role='option']:hover {
				background: var(--pptx-accent);
			}
			.pptx-ng-options-qat-col [role='option'].is-selected {
				background: color-mix(in srgb, var(--pptx-primary) 15%, transparent);
				color: var(--pptx-primary);
			}
			.pptx-ng-options-qat-actions {
				display: flex;
				flex-direction: column;
				justify-content: center;
				gap: 8px;
			}
			.pptx-ng-options-btn {
				padding: 5px 10px;
				border: 1px solid var(--pptx-border);
				border-radius: 4px;
				background: transparent;
				color: var(--pptx-foreground);
				font-size: 12px;
				white-space: nowrap;
				cursor: pointer;
			}
			.pptx-ng-options-btn:hover:not(:disabled) {
				background: var(--pptx-accent);
			}
			.pptx-ng-options-btn:disabled {
				opacity: 0.5;
				cursor: not-allowed;
			}
			.pptx-ng-options-qat > .pptx-ng-options-btn {
				align-self: flex-start;
			}
		`,
	],
})
export class OptionsQuickAccessPaneComponent {
	readonly options = input.required<ViewerOptions>();
	/** The full replacement command-id list (applied live by the host). */
	readonly commandsChange = output<string[]>();

	protected readonly selectedAvailable = signal<string | null>(null);
	protected readonly selectedCurrent = signal<string | null>(null);

	protected readonly current = computed(() => this.options().quickAccess.commandIds);
	protected readonly available = computed(() =>
		availableQuickAccessCommands(this.current()).map((entry) => entry.id),
	);

	protected labelKey(id: string): string {
		return getQuickAccessCommand(id)?.labelKey ?? id;
	}

	protected add(): void {
		const id = this.selectedAvailable();
		if (id) {
			this.commandsChange.emit(addQuickAccessCommand(this.current(), id));
			this.selectedAvailable.set(null);
		}
	}

	protected remove(): void {
		const id = this.selectedCurrent();
		if (id) {
			this.commandsChange.emit(removeQuickAccessCommand(this.current(), id));
			this.selectedCurrent.set(null);
		}
	}

	protected move(direction: 'up' | 'down'): void {
		const id = this.selectedCurrent();
		if (id) {
			this.commandsChange.emit(moveQuickAccessCommand(this.current(), id, direction));
		}
	}

	protected reset(): void {
		this.commandsChange.emit([...DEFAULT_QUICK_ACCESS_COMMAND_IDS]);
	}
}

// viewers/pptx/packages/svelte/src/viewer/components/settings/OptionsQuickAccessPane.svelte
<script lang="ts">
	/**
	 * Options > Quick Access Toolbar: PowerPoint's dual-list command chooser
	 * with Add/Remove, reorder arrows, and Reset over the shared catalog.
	 */
	import ChevronDown from '@lucide/svelte/icons/chevron-down';
	import ChevronUp from '@lucide/svelte/icons/chevron-up';
	import type { ViewerOptions } from 'ooxml-ui/pptx';
	import {
		QUICK_ACCESS_COMMAND_CATALOG,
		addQuickAccessCommand,
		availableQuickAccessCommands,
		moveQuickAccessCommand,
		removeQuickAccessCommand,
	} from 'ooxml-ui/pptx';
	import { useTranslator } from '../../../i18n/context';

	const {
		options,
		oncommandschange,
		onreset,
	}: {
		options: ViewerOptions;
		oncommandschange: (commandIds: string[]) => void;
		onreset: () => void;
	} = $props();
	const t = useTranslator();
	let selectedAvailable = $state<string | null>(null);
	let selectedCurrent = $state<string | null>(null);
	const current = $derived(options.quickAccess.commandIds);
	const available = $derived(availableQuickAccessCommands(current).map((entry) => entry.id));

	function label(id: string): string {
		const command = QUICK_ACCESS_COMMAND_CATALOG.find((entry) => entry.id === id);
		return command ? t(command.labelKey) : id;
	}

	function add(): void {
		if (selectedAvailable) {
			oncommandschange(addQuickAccessCommand(current, selectedAvailable));
			selectedAvailable = null;
		}
	}

	function remove(): void {
		if (selectedCurrent) {
			oncommandschange(removeQuickAccessCommand(current, selectedCurrent));
			selectedCurrent = null;
		}
	}

	function move(direction: 'up' | 'down'): void {
		if (selectedCurrent) {
			oncommandschange(moveQuickAccessCommand(current, selectedCurrent, direction));
		}
	}
</script>

{#snippet commandList(title: string, ids: readonly string[], selectedId: string | null, onselect: (id: string) => void)}
	<div class="list">
		<p>{title}</p>
		<div role="listbox" aria-label={title}>
			{#each ids as id (id)}
				<button type="button" role="option" aria-selected={selectedId === id} class:selected={selectedId === id} onclick={() => onselect(id)}>{label(id)}</button>
			{/each}
		</div>
	</div>
{/snippet}

<div class="qat-pane">
	<div class="columns">
		{@render commandList(t('pptx.options.quickAccess.chooseCommands'), available, selectedAvailable, (id) => (selectedAvailable = id))}
		<div class="middle">
			<button type="button" disabled={!selectedAvailable} onclick={add}>{t('pptx.options.quickAccess.add')} &gt;&gt;</button>
			<button type="button" disabled={!selectedCurrent} onclick={remove}>&lt;&lt; {t('pptx.options.quickAccess.remove')}</button>
		</div>
		{@render commandList(t('pptx.options.quickAccess.currentCommands'), current, selectedCurrent, (id) => (selectedCurrent = id))}
		<div class="middle">
			<button type="button" aria-label={t('pptx.options.quickAccess.moveUp')} disabled={!selectedCurrent} onclick={() => move('up')}><ChevronUp size={16} aria-hidden="true" /></button>
			<button type="button" aria-label={t('pptx.options.quickAccess.moveDown')} disabled={!selectedCurrent} onclick={() => move('down')}><ChevronDown size={16} aria-hidden="true" /></button>
		</div>
	</div>
	<button type="button" class="reset" onclick={onreset}>{t('pptx.options.quickAccess.reset')}</button>
</div>

<style>
	.qat-pane { display: flex; flex-direction: column; gap: 10px; }
	.columns { display: flex; align-items: stretch; gap: 10px; }
	.list { display: flex; flex: 1; min-width: 0; flex-direction: column; }
	.list p { margin: 0 0 4px; color: var(--pptx-muted-foreground, #94a3b8); font-size: 11px; font-weight: 600; }
	.list [role='listbox'] { display: flex; height: 176px; flex-direction: column; gap: 2px; overflow-y: auto; border: 1px solid color-mix(in srgb, var(--pptx-border, #3f3f52) 60%, transparent); border-radius: 6px; padding: 4px; }
	.list [role='option'] { border: 0; border-radius: 4px; padding: 5px 8px; background: transparent; color: var(--pptx-foreground, #e2e8f0); font-size: 12px; text-align: left; cursor: pointer; }
	.list [role='option']:hover { background: var(--pptx-accent, #33334d); }
	.list [role='option'].selected { background: color-mix(in srgb, var(--pptx-primary, #6366f1) 15%, transparent); color: var(--pptx-primary, #6366f1); }
	.middle { display: flex; flex-direction: column; justify-content: center; gap: 6px; }
	.middle button, .reset { display: inline-flex; align-items: center; justify-content: center; border: 1px solid var(--pptx-border, #3f3f52); border-radius: 5px; padding: 6px 10px; background: transparent; color: var(--pptx-foreground, #e2e8f0); font-size: 11px; white-space: nowrap; cursor: pointer; }
	.middle button:hover:not(:disabled), .reset:hover { background: var(--pptx-accent, #33334d); }
	.middle button:disabled { opacity: 0.5; cursor: not-allowed; }
	.reset { align-self: flex-start; }
	@media (max-width: 600px) { .columns { flex-wrap: wrap; } }
</style>
