// viewers/pptx/packages/vue/src/viewer/components/settings/OptionsControlRow.vue
<script setup lang="ts">
/**
 * OptionsControlRow - one schema-driven File > Options control (toggle /
 * select / number / text), rendered from a shared `ViewerOptionsControl`
 * descriptor. Vue counterpart of the `ControlRow` helper inside React's
 * `OptionsPane.tsx`, split into its own SFC to keep `OptionsPane.vue` small.
 */
import { Info } from 'lucide-vue-next';
import { clampOptionNumber, getDensePanelTouchTargetPx } from 'ooxml-ui/pptx';
import type { ViewerOptions, ViewerOptionsControl, ViewerOptionsGroupId } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { useIsMobile } from '../../composables/useIsMobile';

const props = defineProps<{
	control: ViewerOptionsControl;
	options: ViewerOptions;
	onOptionChange: (
		group: ViewerOptionsGroupId,
		key: string,
		value: boolean | number | string,
	) => void;
}>();

// oxlint-disable-next-line eslint/one-var -- distinct concern from `defineProps` above, forcing one statement hurts readability
const { t } = useI18n();

// oxlint-disable-next-line eslint/one-var -- distinct concern from `t` above, forcing one statement hurts readability
const value = computed<boolean | number | string | undefined>(() => {
	const group = props.options[props.control.group] as unknown as Record<string, unknown>;
	// oxlint-disable-next-line eslint/one-var -- distinct concern from the lookup above, forcing one statement hurts readability
	const raw = group[props.control.key];
	return typeof raw === 'boolean' || typeof raw === 'number' || typeof raw === 'string'
		? raw
		: undefined;
});

// oxlint-disable-next-line eslint/one-var -- distinct concern from `value` above, forcing one statement hurts readability
const label = computed(() => t(props.control.labelKey));
// oxlint-disable-next-line eslint/one-var -- distinct concern from `label` above, forcing one statement hurts readability
const infoText = computed(() => (props.control.infoKey ? t(props.control.infoKey) : undefined));

// A host-locked setting (`customizeOptionsTabs` marks it `readOnly`) renders
// disabled with an explanatory tooltip, and never emits a change.
const locked = computed(() => props.control.readOnly === true);
// oxlint-disable-next-line eslint/one-var -- distinct concern from `locked` above, forcing one statement hurts readability
const lockedTitle = computed(() => (locked.value ? t('pptx.options.lockedByHost') : undefined));

function emitChange(next: boolean | number | string): void {
	if (locked.value) {
		return;
	}
	props.onOptionChange(props.control.group, props.control.key, next);
}

// One-per-row fields (not a dense repeating grid), so every field/toggle in
// every Options tab gets the WCAG touch target below the mobile breakpoint
// from this single shared control-row renderer, per CLAUDE.md Rule 2 - never
// re-derive this per tab.
const { viewportWidth } = useIsMobile();
const fieldMinHeight = computed(() => `${getDensePanelTouchTargetPx(viewportWidth.value)}px`);
const rowStyle = computed(() => ({ minHeight: fieldMinHeight.value }));
const fieldStyle = computed(() => ({ minHeight: fieldMinHeight.value }));

function onNumberInput(event: Event): void {
	if (props.control.kind !== 'number') {
		return;
	}
	const clamped = clampOptionNumber(
		(event.target as HTMLInputElement).value,
		props.control.min,
		props.control.max,
	);
	if (clamped !== undefined) {
		emitChange(clamped);
	}
}
</script>

<template>
	<label
		v-if="control.kind === 'toggle'"
		class="pptx-vue-options-row flex cursor-pointer select-none items-center justify-between gap-3 py-1.5"
		:class="{ 'pl-6': control.indent, 'cursor-not-allowed opacity-60': locked }"
		:style="rowStyle"
		:title="lockedTitle"
	>
		<span class="text-sm text-foreground">
			{{ label }}
			<span v-if="infoText" :title="infoText" class="inline-flex cursor-help align-middle">
				<Info class="ml-1 h-3.5 w-3.5 text-primary/70" :aria-label="infoText" />
			</span>
		</span>
		<pptx-ui-checkbox
			:checked="value === true"
			:disabled="locked"
			:title="lockedTitle"
			:aria-label="label"
			@change="emitChange(($event.target as HTMLElement & { checked: boolean }).checked)"
		/>
	</label>

	<div
		v-else
		class="pptx-vue-options-row flex items-center justify-between gap-3 py-1.5"
		:class="{ 'pl-6': control.indent, 'opacity-60': locked }"
		:style="rowStyle"
		:title="lockedTitle"
	>
		<span class="text-sm text-foreground">
			{{ label }}
			<span v-if="infoText" :title="infoText" class="inline-flex cursor-help align-middle">
				<Info class="ml-1 h-3.5 w-3.5 text-primary/70" :aria-label="infoText" />
			</span>
		</span>

		<pptx-ui-select
			v-if="control.kind === 'select'"
			:aria-label="label"
			:style="fieldStyle"
			:disabled="locked"
			:title="lockedTitle"
			:value="typeof value === 'string' ? value : ''"
			@change="emitChange(($event.target as HTMLElement & { value: string }).value)"
		>
			<option v-for="choice in control.choices" :key="choice.value" :value="choice.value">
				{{ t(choice.labelKey) }}
			</option>
		</pptx-ui-select>

		<span v-else-if="control.kind === 'number'" class="flex items-center gap-1.5">
			<input
				type="number"
				:aria-label="label"
				:style="fieldStyle"
				:disabled="locked"
				:title="lockedTitle"
				class="w-20 rounded border border-border bg-background px-2 py-1 text-right text-xs text-foreground"
				:min="control.min"
				:max="control.max"
				:step="control.step ?? 1"
				:value="typeof value === 'number' ? value : control.min"
				@change="onNumberInput"
			/>
			<span v-if="control.unitKey" class="text-xs text-muted-foreground">
				{{ t(control.unitKey) }}
			</span>
		</span>

		<input
			v-else
			type="text"
			:aria-label="label"
			:style="fieldStyle"
			:disabled="locked"
			:title="lockedTitle"
			class="w-48 max-w-[55%] rounded border border-border bg-background px-2 py-1 text-xs text-foreground"
			:maxlength="control.kind === 'text' ? control.maxLength : undefined"
			:value="typeof value === 'string' ? value : ''"
			@input="emitChange(($event.target as HTMLInputElement).value)"
		/>
	</div>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/settings/OptionsControlRow.svelte
<script lang="ts">
	/**
	 * One schema-driven File > Options control row: toggle, select, number, or
	 * text, with the optional "(i)" info tooltip (a `title` attribute, matching
	 * React's `InfoTip`). Values are read from / written to the flat options
	 * model via the control's `group` + `key`.
	 */
	import Info from '@lucide/svelte/icons/info';
	import { clampOptionNumber, getDensePanelTouchTargetPx } from 'ooxml-ui/pptx';
	import type { ViewerOptions, ViewerOptionsControl, ViewerOptionsGroupId } from 'ooxml-ui/pptx';
	import { useTranslator } from '../../../i18n/context';
	import { useWindowViewport } from '../../state/window-viewport.svelte';

	const {
		control,
		options,
		onchange,
	}: {
		control: ViewerOptionsControl;
		options: ViewerOptions;
		onchange: (group: ViewerOptionsGroupId, key: string, value: boolean | number | string) => void;
	} = $props();
	// oxlint-disable-next-line eslint/one-var -- distinct concern from the `$props()` destructure above, forcing one statement hurts readability
	const t = useTranslator();
	const viewport = useWindowViewport();
	// A host-locked setting (`control.readOnly`, set by the shared
	// `customizeOptionsTabs`) renders disabled and never emits a change.
	const locked = $derived(control.readOnly === true);
	const lockTitle = $derived(locked ? t('pptx.options.lockedByHost') : undefined);
	function emit(group: ViewerOptionsGroupId, key: string, next: boolean | number | string): void {
		if (!locked) {
			onchange(group, key, next);
		}
	}
	// One-per-row fields (not a dense repeating grid), so every field/toggle in
	// every Options tab gets the WCAG touch target below the mobile breakpoint
	// from this single shared control-row renderer, per CLAUDE.md Rule 2 -
	// never re-derive this per tab.
	const touchStyle = $derived(`min-height: ${getDensePanelTouchTargetPx(viewport.width)}px`);

	// oxlint-disable-next-line eslint/one-var -- distinct concern from `t` above, forcing one statement hurts readability
	const value = $derived.by((): boolean | number | string | undefined => {
		const group = options[control.group] as unknown as Record<string, unknown>;
		// oxlint-disable-next-line eslint/one-var -- distinct concern from the lookup above, forcing one statement hurts readability
		const raw = group[control.key];
		return typeof raw === 'boolean' || typeof raw === 'number' || typeof raw === 'string' ? raw : undefined;
	});

	function commitNumber(event: Event): void {
		if (control.kind !== 'number') {
			return;
		}
		const clamped = clampOptionNumber(
			(event.currentTarget as HTMLInputElement).value,
			control.min,
			control.max,
		);
		if (clamped !== undefined) {
			emit(control.group, control.key, clamped);
		}
	}
</script>

<div class="row" style={touchStyle} class:indent={control.indent} class:locked title={lockTitle}>
	{#if control.kind === 'toggle'}
		<label class="toggle" style={touchStyle}>
			<span class="label">{t(control.labelKey)}{#if control.infoKey}<i title={t(control.infoKey)} aria-label={t(control.infoKey)}><Info size={14} aria-hidden="true" /></i>{/if}</span>
			<pptx-ui-checkbox checked={value === true} aria-label={t(control.labelKey)} disabled={locked} title={lockTitle} onchange={(event: Event) => emit(control.group, control.key, (event.currentTarget as HTMLElement & { checked: boolean }).checked)}></pptx-ui-checkbox>
		</label>
	{:else}
		<span class="label">{t(control.labelKey)}{#if control.infoKey}<i title={t(control.infoKey)} aria-label={t(control.infoKey)}><Info size={14} aria-hidden="true" /></i>{/if}</span>
		{#if control.kind === 'select'}
			<pptx-ui-select style={touchStyle} aria-label={t(control.labelKey)} disabled={locked} title={lockTitle} value={typeof value === 'string' ? value : ''} onchange={(event: Event) => emit(control.group, control.key, (event.currentTarget as HTMLElement & { value: string }).value)}>
				{#each control.choices as choice (choice.value)}<option value={choice.value}>{t(choice.labelKey)}</option>{/each}
			</pptx-ui-select>
		{:else if control.kind === 'number'}
			<span class="number">
				<input type="number" style={touchStyle} aria-label={t(control.labelKey)} disabled={locked} title={lockTitle} min={control.min} max={control.max} step={control.step ?? 1} value={typeof value === 'number' ? value : control.min} onchange={commitNumber} />
				{#if control.unitKey}<small>{t(control.unitKey)}</small>{/if}
			</span>
		{:else}
			<input class="text" type="text" style={touchStyle} aria-label={t(control.labelKey)} disabled={locked} title={lockTitle} maxlength={control.maxLength} value={typeof value === 'string' ? value : ''} onchange={(event) => emit(control.group, control.key, event.currentTarget.value)} />
		{/if}
	{/if}
</div>

<style>
	.row { display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 5px 0; font-size: 12px; }
	.indent { padding-left: 22px; }
	.locked { opacity: 0.6; }
	.locked .toggle { cursor: not-allowed; }
	.toggle { display: flex; flex: 1; align-items: center; justify-content: space-between; gap: 12px; cursor: pointer; user-select: none; }
	.label { display: inline-flex; align-items: center; color: var(--pptx-foreground, #e2e8f0); }
	.label i { display: inline-flex; margin-left: 5px; color: color-mix(in srgb, var(--pptx-primary, #6366f1) 70%, transparent); font-style: normal; cursor: help; }
	.number input, .text { border: 1px solid var(--pptx-border, #3f3f52); border-radius: 5px; padding: 4px 7px; background: var(--pptx-background, #11111b); color: var(--pptx-foreground, #e2e8f0); font: inherit; font-size: 11px; }
	.number { display: flex; align-items: center; gap: 6px; }
	.number input { width: 74px; text-align: right; }
	.number small { color: var(--pptx-muted-foreground, #94a3b8); font-size: 11px; }
	.text { width: 12rem; max-width: 55%; }
</style>
