// viewers/pptx/packages/react/src/viewer/components/CanvasContextMenu.tsx
import {
	buildCanvasContextMenuEntries,
	contextMenuViewItems,
	customizeCanvasContextMenuEntries,
} from 'ooxml-ui/pptx';
import type React from 'react';
import { useTranslation } from 'react-i18next';

import {
	canvasContextMenuContext,
	canvasContextMenuHandlers,
} from './canvas-context-menu-dispatch';
import type { CanvasContextMenuProps } from './canvas-context-menu-types';
import { ContextMenuSurface } from './ContextMenuSurface';
import { useViewerCustomizationContext } from './viewer-customization-context';

/**
 * The right-click menu for the empty slide canvas (no element under the
 * cursor). Sibling of `ContextMenu` (the per-element menu): the command list
 * comes from `pptx-viewer-shared`'s `canvas-context-menu-commands` and the rows
 * are drawn by the shared `pptx-ui-context-menu`; this file keeps the gating
 * and the handlers.
 */
export function CanvasContextMenu(props: CanvasContextMenuProps): React.ReactElement | null {
	const { canvasContextMenuState, mode, onClose } = props;
	const { t } = useTranslation();
	const customization = useViewerCustomizationContext();
	const open = Boolean(canvasContextMenuState) && mode === 'edit';
	const handlers = canvasContextMenuHandlers(props);
	// Host customisation drops hidden commands; a menu left empty (or one the
	// host disabled outright) renders nothing at all.
	const entries = customizeCanvasContextMenuEntries(
		buildCanvasContextMenuEntries(canvasContextMenuContext(props)),
		customization,
		{ slideIndex: props.slideIndex ?? 0 },
	);
	if (!open || entries.length === 0) {
		return null;
	}
	const request = (id: string): void => {
		const entry = entries.find((candidate) => candidate.id === id);
		if (entry && 'host' in entry) {
			onClose();
			entry.onSelect();
		} else if (entry) {
			handlers[entry.id]?.();
		}
	};
	return (
		<ContextMenuSurface
			x={canvasContextMenuState?.x ?? 0}
			y={canvasContextMenuState?.y ?? 0}
			label={t('pptx.canvasContextMenu.ariaLabel')}
			markers={['data-pptx-context-menu', 'data-pptx-canvas-context-menu']}
			items={contextMenuViewItems(
				entries,
				t,
				(id) => id.startsWith('host:') || Boolean(handlers[id as keyof typeof handlers]),
			)}
			onRequest={request}
			onClose={onClose}
		/>
	);
}

// viewers/pptx/packages/svelte/src/viewer/components/CanvasContextMenu.svelte
<script lang="ts">
	/**
	 * Empty-canvas (no element under the cursor) context menu.
	 *
	 * Sibling of `ElementContextMenu.svelte`: the item list comes from
	 * `pptx-viewer-shared`'s `canvas-context-menu-commands` (via
	 * `buildCanvasMenuEntries`); the rows are drawn by the shared
	 * `pptx-ui-context-menu`.
	 */
	import { contextMenuViewItems, customizeCanvasContextMenuEntries } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import {
		buildCanvasMenuEntries,
		runCanvasContextMenuCommand,
	} from '../editor/canvas-context-menu-dispatch';
	import { useViewerCustomization } from '../state/viewer-customization.svelte';
	import ContextMenuSurface from './ContextMenuSurface.svelte';
	import type { CanvasContextMenuProps } from './props';

	const {
		x,
		y,
		editor,
		showGrid,
		showRulers,
		onopenlayoutgallery,
		onresetslide,
		onopenformatbackground,
		ontogglegrid,
		ontogglerulers,
		onclose,
	}: CanvasContextMenuProps = $props();
	const t = useTranslator();

	const dispatch = $derived({
		editor,
		showGrid,
		showRulers,
		onOpenLayoutGallery: onopenlayoutgallery,
		onResetSlide: onresetslide,
		onOpenFormatBackground: onopenformatbackground,
		onToggleGrid: ontogglegrid,
		onToggleRulers: ontogglerulers,
	});
	const customization = useViewerCustomization();
	// Filtered through the host's customisation; empty means no menu, so close.
	const entries = $derived(
		customizeCanvasContextMenuEntries(buildCanvasMenuEntries(dispatch), customization.resolved, { slideIndex: editor.currentSlideIndex }),
	);
	$effect(() => {
		if (entries.length === 0) {
			onclose();
		}
	});

	function run(id: string): void {
		const entry = entries.find((candidate) => candidate.id === id);
		if (!entry) {
			return;
		}
		if ('host' in entry) {
			onclose();
			entry.onSelect();
			return;
		}
		runCanvasContextMenuCommand(entry.id, dispatch);
		onclose();
	}
</script>

{#if entries.length > 0}
	<ContextMenuSurface
		{x}
		{y}
		label={t('pptx.canvasContextMenu.ariaLabel')}
		markers={['data-pptx-context-menu', 'data-pptx-canvas-context-menu']}
		items={contextMenuViewItems(entries, t)}
		onrequest={run}
		{onclose}
	/>
{/if}
