// viewers/pptx/packages/vue/src/viewer/components/CommentBody.vue
<script setup lang="ts">
/**
 * CommentBody: renders a comment's text with its `@`-mentions highlighted.
 *
 * The split into text/mention runs is the shared decision function
 * `commentTextSegments`, so all five bindings produce identical runs. This SFC
 * only maps the resulting descriptor onto spans.
 */
import type { PptxComment } from 'pptx-viewer-core';
import {
	COMMENT_MENTION_ATTRIBUTE,
	COMMENT_MENTION_CLASS,
	commentTextSegments,
} from 'ooxml-ui/pptx';
import { computed } from 'vue';

const props = defineProps<{
	text: string;
	mentions?: PptxComment['mentions'];
}>();

const segments = computed(() => commentTextSegments(props.text, props.mentions));
</script>

<template>
	<span>
		<template v-for="(segment, index) in segments" :key="index">
			<span
				v-if="segment.kind === 'mention'"
				:class="[COMMENT_MENTION_CLASS, 'rounded bg-primary/15 px-0.5 font-semibold text-primary']"
				v-bind="{ [COMMENT_MENTION_ATTRIBUTE]: segment.personId || '' }"
				:title="segment.authorName"
				>{{ segment.text }}</span
			>
			<template v-else>{{ segment.text }}</template>
		</template>
	</span>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/CommentBody.svelte
<script lang="ts">
	/**
	 * CommentBody: a comment's text with its `@`-mentions highlighted.
	 *
	 * The split into text/mention runs is the shared decision function
	 * `commentTextSegments`, so all five bindings produce identical runs. This
	 * component only maps the resulting descriptor onto spans.
	 */
	import type { PptxComment } from 'pptx-viewer-core';
	import { commentTextSegments } from 'ooxml-ui/pptx';

	const { text, mentions }: { text: string; mentions?: PptxComment['mentions'] } = $props();

	const segments = $derived(commentTextSegments(text, mentions));
</script>

<!-- prettier-ignore -->
{#each segments as segment, index (index)}{#if segment.kind === 'mention'}<span
			class="pptx-comment-mention"
			data-pptx-comment-mention={segment.personId || ''}
			title={segment.authorName}>{segment.text}</span
		>{:else}{segment.text}{/if}{/each}

<style>
	.pptx-comment-mention {
		border-radius: 3px;
		background: color-mix(in srgb, var(--pptx-primary, #6366f1) 15%, transparent);
		color: var(--pptx-primary, #6366f1);
		font-weight: 600;
		padding: 0 2px;
	}
</style>
