// viewers/pptx/packages/react/src/viewer/components/DialogFooter.tsx
import type {
	DialogFooterAction,
	DialogFooterIntent,
	PptxUiDialogFooterElement,
} from 'ooxml-ui/pptx';
import React from 'react';

import { useWebControl } from '../hooks/useWebControl';

export interface DialogFooterProps {
	actions: readonly DialogFooterAction[];
	/** Called with the id of the activated action. Hosts keep every effect. */
	onAction: (id: string) => void;
}

/**
 * Thin adapter around the shared `pptx-ui-dialog-footer`: the Cancel / OK /
 * primary row at the bottom of a dialog. The dialog shell, its backdrop and
 * dismissal stay in the dialog component.
 */
export function DialogFooter({ actions, onAction }: DialogFooterProps): React.ReactElement {
	const ref = useWebControl<PptxUiDialogFooterElement>(
		{ actions },
		{
			'dialog-footer-request': (event) => onAction((event.detail as DialogFooterIntent).id),
		},
	);
	return <pptx-ui-dialog-footer ref={ref} />;
}

// viewers/pptx/packages/svelte/src/viewer/components/DialogFooter.svelte
<script lang="ts">
	/**
	 * DialogFooter: thin adapter around the shared `pptx-ui-dialog-footer`, the
	 * Cancel / OK / primary row at the bottom of a dialog. The dialog shell, its
	 * backdrop and dismissal stay in the dialog component; this routes the
	 * activated action id.
	 */
	import type { DialogFooterAction, DialogFooterRequestEvent } from 'ooxml-ui/pptx';

	const { actions, onaction }: {
		actions: readonly DialogFooterAction[];
		onaction: (id: string) => void;
	} = $props();
</script>

<pptx-ui-dialog-footer
	state={{ actions }}
	ondialog-footer-request={(event: DialogFooterRequestEvent) => onaction(event.detail.id)}
></pptx-ui-dialog-footer>
