// viewers/pptx/packages/vue/src/viewer/components/InlineTextEditor.vue
<script setup lang="ts">
/**
 * InlineTextEditor: a `contentEditable` overlay for editing an element's text
 * in place (Vue port of the React `elements/InlineTextEditor.tsx`).
 *
 * It is mounted inside the scaled slide stage (same coordinate space as
 * {@link SelectionOverlay}), positioned over the element's box, and seeded once
 * from the element's plain text. It does NOT re-bind its value while the user
 * types (the DOM owns the text during an edit) and only reports changes via
 * `change`, committing on blur (`commit`) or cancelling on Escape (`cancel`).
 * The host commits the typed text back onto the element's rich `textSegments`
 * (via `remapTextToSegments`) so per-run styling is preserved.
 */
import type { PptxElement, TextStyle } from 'pptx-viewer-core';
import {
	attachCollaborationInlineEditor,
	attachInlineListController,
	createInlineListSeed,
	initializeInlineListDom,
	inlineListBodyText,
	mapInlineTextFormatKey,
	placeCaretAt,
	readEditableText,
	readListActivationSelection,
	restoreInlineListBodySelection,
	takePendingCaretPoint,
} from 'ooxml-ui/pptx';
import type {
	CollaborationInlineEditor,
	CollaborationLivePatcher,
	InlineListController,
	InlineTextEditSnapshot,
} from 'ooxml-ui/pptx';
import { computed, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, toRaw, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { inlineEditorStyle } from './inline-editor-style';

const { t } = useI18n();

const props = withDefaults(
	defineProps<{
		element: PptxElement;
		livePatcher?: CollaborationLivePatcher;
		slideId?: string;
		/** Draw the browser's native red spell-check squiggles while editing (View ▸ Spell). */
		spellCheck?: boolean;
	}>(),
	{ spellCheck: true },
);

const emit = defineEmits<{
	change: [text: string, snapshot?: InlineTextEditSnapshot];
	commit: [];
	cancel: [];
	/** Ctrl/Cmd+B/I/U formatting toggle while editing (parity with React). */
	format: [updates: Partial<TextStyle>];
	listSession: [event: { controller: InlineListController; active: boolean }];
}>();

const editorRef = ref<HTMLDivElement | null>(null);
const listSeed = shallowRef(createInlineListSeed(toRaw(props.element)));
let listController: InlineListController | undefined;
let connected: CollaborationInlineEditor | undefined;
let disposed = false;
let activatingList = false;
watch(
	() => props.element,
	async (element) => {
		if (connected) {
			connected.checkModel(toRaw(element));
			return;
		}
		if (listSeed.value) {
			return;
		}
		const seed = createInlineListSeed(toRaw(element));
		if (!seed) {
			return;
		}
		const body = inlineListBodyText('textSegments' in element ? element.textSegments : undefined);
		if (editorRef.value && readEditableText(editorRef.value) !== body) {
			disposed = true;
			emit('cancel');
			return;
		}
		const selection = editorRef.value
			? readListActivationSelection(
					editorRef.value,
					inlineListBodyText('textSegments' in element ? element.textSegments : undefined),
				)
			: undefined;
		activatingList = true;
		listSeed.value = seed;
		await nextTick();
		if (!disposed) {
			initializeEditor(selection);
		}
		activatingList = false;
	},
);

/** The element's current plain text (seed value). */
function seedText(): string {
	return (props.element as { text?: string }).text ?? '';
}

/** Read the live text out of the contentEditable node. */
function extractText(): string {
	return editorRef.value?.innerText ?? '';
}

const editorStyle = computed(() =>
	inlineEditorStyle(props.element, Boolean(listSeed.value || props.livePatcher?.isActive())),
);

function initializeEditor(selection?: { start: number; end: number }): void {
	const node = editorRef.value;
	if (!node) {
		return;
	}
	const seed = listSeed.value;
	if (props.livePatcher?.isActive()) {
		connected = attachCollaborationInlineEditor(node, toRaw(props.element), {
			patcher: props.livePatcher,
			slideId: props.slideId,
			onSnapshot: (snapshot) => emit('change', snapshot.text, snapshot),
			onCancel: () => {
				disposed = true;
				emit('cancel');
			},
		});
		if (!connected) {
			disposed = true;
			emit('cancel');
			return;
		}
		listController = connected;
		emit('listSession', { controller: connected, active: true });
	} else if (seed && initializeInlineListDom(node, seed)) {
		listController = attachInlineListController(node, seed, {
			isCurrent: () => !disposed && props.element.id === seed.elementId && editorRef.value === node,
			onRead: (result) =>
				emit(
					'change',
					result.kind === 'supported' ? result.snapshot.text : result.text,
					result.kind === 'supported' ? result.snapshot : undefined,
				),
		});
		emit('listSession', { controller: listController, active: true });
	} else {
		node.innerText = seedText();
	}
	node.focus();
	// The caret goes where the click that opened the editor landed (PowerPoint),
	// else at the end of the seeded text (shared contract helpers).
	placeCaretAt(node, takePendingCaretPoint());
	if (seed && selection) {
		restoreInlineListBodySelection(seed, node, selection);
	}
}
onMounted(() => initializeEditor());
onBeforeUnmount(() => {
	disposed = true;
	listController?.dispose();
	if (listController) {
		emit('listSession', { controller: listController, active: false });
	}
});

function onInput(): void {
	if (!listController) {
		emit('change', extractText());
	}
}

function onBlur(): void {
	if (activatingList) {
		return;
	}
	if (disposed) {
		return;
	}
	if (listController) {
		const result = listController.refresh();
		if (connected && result.kind !== 'supported') {
			return;
		}
	} else {
		emit('change', extractText());
	}
	emit('commit');
}

/** The style the B/I/U toggles read their current state from. */
function currentTextStyle(): TextStyle | undefined {
	const el = props.element as {
		textSegments?: Array<{ style?: TextStyle }>;
		textStyle?: TextStyle;
	};
	if (!listController) {
		return el.textSegments?.[0]?.style ?? el.textStyle;
	}
	const current = listController.readSelection();
	const style =
		current.kind === 'supported'
			? current.snapshot.textSegments?.[current.selection?.startSegIdx ?? 0]?.style
			: el.textSegments?.[0]?.style;
	return {
		...style,
		bold: style?.bold ?? el.textStyle?.bold,
		italic: style?.italic ?? el.textStyle?.italic,
		underline: style?.underline ?? el.textStyle?.underline,
	};
}

/**
 * When the caret sits at a soft word-wrap boundary (no explicit line break,
 * just CSS wrapping), the space separating the two words is still part of the
 * text and lands right before the caret. Pressing Enter there splits the DOM
 * at that exact position, leaving the new paragraph break preceded by a stray
 * space (mirrors the React inline editor's fix). Since a space immediately
 * before a paragraph break is never visually meaningful, drop it before the
 * browser performs its native Enter/paragraph-split.
 */
function trimTrailingSpaceBeforeCaret(): void {
	const selection = window.getSelection();
	if (!selection || !selection.isCollapsed || selection.rangeCount === 0) {
		return;
	}
	const range = selection.getRangeAt(0);
	const { startContainer, startOffset } = range;
	if (startContainer.nodeType !== Node.TEXT_NODE || startOffset === 0) {
		return;
	}
	const text = startContainer.textContent ?? '';
	if (text.charAt(startOffset - 1) !== ' ') {
		return;
	}
	const trimRange = document.createRange();
	trimRange.setStart(startContainer, startOffset - 1);
	trimRange.setEnd(startContainer, startOffset);
	if (connected) {
		connected.mutate(trimRange, () => trimRange.deleteContents());
	} else {
		trimRange.deleteContents();
	}
}

function onKeydown(event: KeyboardEvent): void {
	if (listController && event.isComposing) {
		return;
	}
	// Inline formatting shortcuts (Ctrl/Cmd + B/I/U): resolved by the shared
	// keymap so this three-way switch is not hand-derived a fourth time.
	const property = mapInlineTextFormatKey(event);
	if (property) {
		event.preventDefault();
		event.stopPropagation();
		const ts = currentTextStyle();
		emit('format', { [property]: !ts?.[property] });
		return;
	}
	if (event.key === 'Escape') {
		event.preventDefault();
		if (listController) {
			disposed = true;
			listController.dispose();
		}
		emit('cancel');
		return;
	}
	if (event.key === 'Enter' && (!listController || (connected && !listSeed.value))) {
		trimTrailingSpaceBeforeCaret();
	}
}
</script>

<template>
	<div
		:key="listSeed ? 'list' : 'plain'"
		ref="editorRef"
		class="pptx-vue-inline-editor"
		data-inline-editor
		contenteditable="true"
		:spellcheck="props.spellCheck"
		role="textbox"
		:aria-label="t('pptx.inlineEditor.editText')"
		:style="editorStyle"
		@input="onInput"
		@blur="onBlur"
		@keydown="onKeydown"
		@pointerdown.stop
	/>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/InlineTextEditor.svelte
<script lang="ts">
	/**
	 * InlineTextEditor: a contenteditable surface positioned over a text/shape
	 * element (Svelte port of the vanilla binding's `openInlineEditor`). Opened by
	 * a double-click, it seeds the element's plain text, commits on blur and on
	 * Escape, and keeps every keystroke local so viewer navigation / editor
	 * shortcuts never fire while typing. On commit the plain text is remapped back
	 * onto the original rich segments upstream (see `EditorState.commitInlineText`
	 * / the shared `remapTextToSegments`), so per-run styles and field metadata
	 * survive the round trip.
	 */
 import { attachInlineListController, buildInlineTextCommitPatch, createInlineListSeed, createInlineListModelObserver, initializeInlineListDom, inlineListBodyText, readListActivationSelection, restoreInlineListBodySelection, placeCaretAt, takePendingCaretPoint } from 'ooxml-ui/pptx';
	import type { InlineListController } from 'ooxml-ui/pptx';
	import { attachCollaborationInlineEditor } from 'ooxml-ui/pptx';
	import type { CollaborationInlineEditor } from 'ooxml-ui/pptx';
	import { onDestroy, onMount, untrack } from 'svelte';

	import { readEditableText, resolveInlineSurface } from '../editor/inline-text';
	import { handleInlineFormatShortcut } from './inline-text-editor-shortcuts';
	import type { InlineTextEditorProps } from './props';
	import { getTextBlockStyle, styleToString } from '../style';

	const {
		element,
		box,
		scale,
		spellCheck = false,
		oninput,
		oncommit,
		onclose,
		onregister,
		onretire,
		collaboration,
		onformat,
		oncopyformat,
		onpasteformat,
		onhyperlink,
		onfind,
		onfindreplace,
	}: InlineTextEditorProps = $props();

	const surface = $derived(resolveInlineSurface(element));
	// The surface is remounted per edit session (keyed on the element id), so the
	// element is stable for its lifetime: capture the seed text once.
	const initialText = untrack(() => resolveInlineSurface(element).text);
	const collaborationTarget = untrack(() => ({
		slideId: collaboration?.slideId,
		patcher: collaboration?.patcher,
	}));
	let listSeed = $state.raw(untrack(() => createInlineListSeed($state.snapshot(element))));
	let listController: InlineListController | undefined;
	let connected = $state.raw<CollaborationInlineEditor>();

	// eslint-disable-next-line no-unassigned-vars
	let el: HTMLDivElement | undefined;
	let closed = false;
	let modelObserver = untrack(() => createInlineListModelObserver($state.snapshot(element)));
	$effect(() => {
		JSON.stringify(element);
		const activeSlideId = collaboration?.slideId;
		const activePatcher = collaboration?.patcher;
		untrack(() => {
			if (connected) {
				if (
					activeSlideId !== collaborationTarget.slideId ||
					activePatcher !== collaborationTarget.patcher
				) {
					close(null);
				} else {
					connected.checkModel($state.snapshot(element));
				}
				return;
			}
			if (listController) { listController.read(); return; }
			if (!el || closed || listSeed) {
				return;
			}
			const seed = createInlineListSeed($state.snapshot(element));
			const body = 'textSegments' in element ? inlineListBodyText(element.textSegments) : '';
			if (!seed) {
				return;
			}
			if (readEditableText(el) !== body) { close(null); return; }
			const selection = readListActivationSelection(el, body);
			el.replaceChildren();
			listSeed = seed;
			modelObserver = createInlineListModelObserver($state.snapshot(element));
			mountList();
			if (selection) {
				restoreInlineListBodySelection(seed, el, selection);
			}
		});
	});

	const style = $derived(
		listSeed || connected ? styleToString({ ...getTextBlockStyle(element), textDecoration: 'none', textDecorationLine: 'none', left: `${box.x * scale}px`, top: `${box.y * scale}px`, width: `${box.width}px`, minHeight: `${box.height}px`, transform: `scale(${scale})`, transformOrigin: 'top left' })
		: `left:${box.x * scale}px;top:${box.y * scale}px;width:${box.width * scale}px;min-height:${box.height * scale}px;${typeof surface.fontSize === 'number' ? `font-size:${surface.fontSize * scale}px;` : ''}${surface.fontFamily !== undefined ? `font-family:${surface.fontFamily};` : ''}`,
	);

	function close(commitText: string | null): void {
		if (closed) {
			return;
		}
		const read = commitText === null ? undefined : listController?.read();
		if (connected && read?.kind === 'unsupported' &&
			(read.reason === 'composition-active' || read.reason === 'input-active')) return;
		const snapshot = read?.kind === 'supported' ? read.snapshot : undefined;
		if (connected && !snapshot) commitText = null;
		if (commitText !== null && snapshot) {
			commitText = snapshot.text;
		}
		closed = true;
		if (commitText !== null && (snapshot ? buildInlineTextCommitPatch(element, commitText, snapshot) : commitText !== initialText)) {
			oncommit(commitText, snapshot);
		}
		listController?.dispose();
		onregister?.(undefined);
		onclose();
	}

	// Every keystroke is mirrored out for the collaboration live preview; the
	// editor itself stays uncontrolled and only commits on blur/Escape.
	function onInput(): void {
		if (listController) {
			return;
		}
		if (el) {
			oninput?.(readEditableText(el));
		}
	}

	function onBlur(): void {
		close(el ? readEditableText(el) : null);
	}

	function onKeydown(event: KeyboardEvent): void {
		// Keep every keystroke local so viewer navigation / editor shortcuts
		// (arrows, space, Delete, Ctrl+Z...) never fire while typing. That
		// includes PowerPoint's text-formatting shortcuts (Ctrl+B/I/U,
		// Ctrl+L/E/R/J, the font-size ladder, format painter, hyperlink, clear
		// formatting, find/replace): the root `editor-keyboard.ts` handler never
		// sees a key pressed in here, so `handleInlineFormatShortcut` resolves
		// and dispatches them directly, through the `onformat`/`oncopyformat`/
		// etc. props (this component has no direct access to `EditorState`,
		// only to `EditorController`, via those callbacks).
		event.stopPropagation();
		if (event.key === 'Escape') {
			event.preventDefault();
			close(el ? readEditableText(el) : null);
			return;
		}
		if (
			handleInlineFormatShortcut(event, element, {
				onformat,
				oncopyformat,
				onpasteformat,
				onhyperlink,
				onfind,
				onfindreplace,
			})
		) {
			event.preventDefault();
		}
	}

	function mountList(): void {
			if (el && listSeed && initializeInlineListDom(el, listSeed)) {
			const root = el;
			const native = attachInlineListController(root, listSeed, {
				isCurrent: () => !closed && el === root,
				onRead: (read) => oninput?.(read.kind === 'supported' ? read.snapshot.text : read.text, read.kind === 'supported' ? read.snapshot : undefined),
			});
			listController = {
				...native,
				read() {
					const read = native.read();
					const change = modelObserver.check($state.snapshot(element), read);
					if (change.kind === 'retire') { close(null); return { kind: 'unsupported', reason: 'model-replaced', text: read.kind === 'supported' ? read.snapshot.text : read.text }; }
					if (change.kind === 'format') {
						const formatted = native.format(change.snapshot);
						if (formatted.kind !== 'supported') {
							close(null);
						}
						return formatted;
					}
					return read;
				},
				format(snapshot) {
					const formatted = native.format($state.snapshot(snapshot));
					if (formatted.kind === 'supported') {
						modelObserver.expect(snapshot);
					}
					return formatted;
				},
			};
			onregister?.(listController, () => close(null));
		}
	}

	onMount(() => {
		if (el) {
			if (collaboration?.patcher.isActive()) {
				connected = attachCollaborationInlineEditor(el, $state.snapshot(element), {
					...collaboration,
					onCancel: () => close(null),
				});
				if (!connected) { close(null); return; }
				listController = connected;
				onregister?.(connected, () => close(null));
			} else if (listSeed) {
				mountList();
			} else {
				el.textContent = initialText;
			}
			el.focus();
			// The caret goes where the click that opened the editor landed
			// (PowerPoint), else at the END of the seeded text so typing appends
			// (the shared contract; focus alone leaves the caret at the start).
			placeCaretAt(el, takePendingCaretPoint());
		}
	});

	// Committed on unmount too (e.g. the slide changed out from under the editor),
	// mirroring the vanilla controller's commit-on-close.
	onDestroy(() => {
		if (!closed && el) {
			if (connected) { onretire?.(); close(null); return; }
			close(readEditableText(el));
			if (!closed) close(null);
		}
	});
</script>

<div
	bind:this={el}
	class="pptx-svelte-inline-editor"
	data-inline-editor
	style={style}
	contenteditable="true"
	spellcheck={spellCheck}
	role="textbox"
	tabindex="0"
	aria-multiline="true"
	aria-label="edit text"
	oninput={onInput}
	onblur={onBlur}
	onkeydown={onKeydown}
	onpointerdown={(event) => event.stopPropagation()}
></div>

<style>
	.pptx-svelte-inline-editor {
		position: absolute;
		box-sizing: border-box;
		padding: 2px;
		margin: 0;
		border: 1px solid var(--pptx-ring, #6366f1);
		background: var(--pptx-background, #ffffff);
		color: var(--pptx-foreground, #0f172a);
		outline: none;
		white-space: pre-wrap;
		overflow-wrap: break-word;
		pointer-events: auto;
		z-index: 6;
	}
</style>
