// viewers/pptx/packages/angular/src/viewer/notes-panel.component.ts
/**
 * notes-panel.component.ts: collapsible, editable speaker-notes panel.
 *
 * Ported from: packages/react/src/viewer/components/notes (rich editor) and the
 * earlier Vue/Angular plain-textarea panel.
 *
 * Renders the active slide's speaker notes. The default surface is a
 * contentEditable RICH editor (bold/italic/underline/strikethrough, bullet and
 * numbered lists, indent, hyperlinks, print), mirroring the React viewer. On a
 * mobile viewport it defaults to a plain `<textarea>` so the on-screen keyboard
 * and caret behave (the documented mobile rationale); the toolbar's rich/plain
 * toggle flips between the two on any device. All framework-agnostic logic lives
 * in `pptx-viewer-shared`; this component is the view layer + signal wiring.
 *
 * Framework-neutral e2e contract
 * ------------------------------
 * The body wrapper carries `id="slide-notes-content"` and the plain editor is a
 * `textarea[name="slide-notes"]` (kept in the DOM via `[hidden]`, not `@if`),
 * matching the React/Vue viewers so the shared Playwright specs run unchanged.
 *
 * Touch / focus correctness
 * -------------------------
 * Both surfaces are UNCONTROLLED: content is seeded imperatively (once per
 * slide, keyed by slide id) and never re-bound while the user types. Rich edits
 * are debounced; plain edits commit on `change` / `blur`. This keeps the host's
 * per-keystroke history-aware update from remounting the field mid-typing.
 */

import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	ElementRef,
	inject,
	input,
	output,
	signal,
	viewChild,
} from '@angular/core';
import { LucideChevronDown, LucideChevronRight } from '@lucide/angular';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import type { PptxSlide, PptxTextStyleLevels, TextSegment } from 'pptx-viewer-core';

import type { NotesInlineCommand, NotesParagraphCommand } from 'ooxml-ui/pptx';
import {
	DEBOUNCE_MS,
	applyInlineCommand,
	applyParagraphCommand,
	buildNotesPrintHtml,
	createPlainNotesSegments,
	defaultRichEnabled,
	handleEditorAnchorClick,
	insertHyperlinkAtSelection,
	normalizeNotesLinkUrl,
	readEditorSegments,
	resolveNotesSegments,
	segmentsToEditorHtml,
	segmentsToPlainText,
} from 'ooxml-ui/pptx';
import { NotesToolbarComponent } from './notes-toolbar.component';

@Component({
	selector: 'pptx-notes-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NotesToolbarComponent, TranslatePipe, LucideChevronRight, LucideChevronDown],
	templateUrl: './notes-panel.component.html',
	styleUrl: './notes-panel.component.css',
})
export class NotesPanelComponent {
	private readonly translate = inject(TranslateService);

	/** The active slide whose notes are shown / edited. */
	readonly slide = input<PptxSlide | undefined>(undefined);

	/**
	 * Whether the notes body is expanded. When false the panel collapses to just
	 * its header strip (React parity: the notes footer is always present below
	 * the canvas, the body toggles). Host-controlled so the status-bar Notes
	 * button and the header chevron stay in sync.
	 */
	readonly expanded = input<boolean>(false);

	/**
	 * The deck's notes master `<p:notesStyle>` level defaults (`PptxData.
	 * notesMaster.notesStyle`), when the host has it. Fills in a notes
	 * segment's missing font/colour/indent from the authored defaults instead
	 * of a hardcoded look; see `resolveNotesSegments` / `buildNotesPrintHtml`.
	 */
	readonly notesStyle = input<PptxTextStyleLevels | undefined>(undefined);

	/** Emits the new plain-text notes on commit. */
	readonly update = output<string>();

	/** Emits the plain text together with the rich segments that carry its formatting. */
	readonly notesCommit = output<{ notes: string; segments: TextSegment[] }>();

	/** Emits when the header strip is clicked to expand / collapse the body. */
	readonly notesToggle = output<void>();

	readonly collapsed = computed<boolean>(() => !this.expanded());
	protected readonly isRichEnabled = signal<boolean>(defaultRichEnabled());

	private readonly richEditor = viewChild<ElementRef<HTMLDivElement>>('richEditor');
	private readonly textarea = viewChild<ElementRef<HTMLTextAreaElement>>('textarea');

	/** Show the rich surface only when a slide is selected. */
	protected showRich(): boolean {
		return this.isRichEnabled() && this.slide() !== undefined;
	}

	private draftSegments: TextSegment[] = resolveNotesSegments(undefined, this.notesStyle());
	private draftText = '';
	private seededId: string | null = null;
	private debounceId: ReturnType<typeof setTimeout> | null = null;

	constructor() {
		// Re-seed the uncontrolled surface exactly once per slide (keyed by id), so
		// an in-progress edit is never overwritten on an unrelated change pass.
		effect(() => {
			const slide = this.slide();
			const id = slide?.id ?? null;
			if (id === this.seededId) {
				return;
			}
			this.seededId = id;
			this.draftSegments = resolveNotesSegments(slide, this.notesStyle());
			this.draftText = segmentsToPlainText(this.draftSegments);
			queueMicrotask(() => this.seedActiveSurface());
		});

		afterNextRender(() => this.seedActiveSurface());
	}

	private seedActiveSurface(): void {
		if (this.isRichEnabled()) {
			const el = this.richEditor()?.nativeElement;
			if (el) {
				// Built by the shared sanitising serialiser (text escaped, links/CSS
				// allow-listed), so assigning innerHTML here is safe.
				el.innerHTML = segmentsToEditorHtml(this.draftSegments);
			}
		} else {
			const el = this.textarea()?.nativeElement;
			if (el) {
				el.value = this.draftText;
			}
		}
	}

	private emit(text: string): void {
		this.update.emit(text);
		this.notesCommit.emit({ notes: text, segments: this.draftSegments });
	}

	private emitNow(text: string): void {
		if (this.debounceId) {
			clearTimeout(this.debounceId);
			this.debounceId = null;
		}
		this.emit(text);
	}

	private scheduleSave(text: string): void {
		if (this.debounceId) {
			clearTimeout(this.debounceId);
		}
		this.debounceId = setTimeout(() => {
			this.emit(text);
			this.debounceId = null;
		}, DEBOUNCE_MS);
	}

	toggle(): void {
		this.notesToggle.emit();
	}

	/* --- Rich editor --- */

	onRichInput(): void {
		const el = this.richEditor()?.nativeElement;
		if (!el) {
			return;
		}
		const next = readEditorSegments(el);
		this.draftSegments = next.segments;
		this.draftText = next.text;
		this.scheduleSave(next.text);
	}

	/** Commit now: leaving the editor (for example to another slide) must not wait for the debounce. */
	onRichBlur(): void {
		const el = this.richEditor()?.nativeElement;
		if (!el) {
			return;
		}
		const next = readEditorSegments(el);
		this.draftSegments = next.segments;
		this.draftText = next.text;
		this.emitNow(next.text);
	}

	inlineCommand(command: NotesInlineCommand): void {
		applyInlineCommand(command);
		this.onRichInput();
		this.richEditor()?.nativeElement.focus();
	}

	paragraphCommand(command: NotesParagraphCommand): void {
		const el = this.richEditor()?.nativeElement;
		if (!el) {
			return;
		}
		const next = applyParagraphCommand(el, this.draftSegments, command);
		this.draftSegments = next.segments;
		this.draftText = next.text;
		// List/indent changes block structure, so re-seed the DOM.
		el.innerHTML = segmentsToEditorHtml(next.segments);
		this.scheduleSave(next.text);
		el.focus();
	}

	onRichKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Enter' && (event.metaKey || event.ctrlKey)) {
			this.emitNow(this.draftText);
			this.richEditor()?.nativeElement.blur();
			return;
		}
		if (event.key === 'Tab') {
			event.preventDefault();
			this.paragraphCommand(event.shiftKey ? 'outdent' : 'indent');
		}
	}

	onEditorClick(event: MouseEvent): void {
		if (handleEditorAnchorClick(event.target, event.ctrlKey || event.metaKey)) {
			event.preventDefault();
		}
	}

	/* --- Hyperlink (the shared toolbar owns the popover) --- */

	insertLink(link: { url: string; displayText: string }): void {
		const el = this.richEditor()?.nativeElement;
		if (!el) {
			return;
		}
		el.focus();
		const finalUrl = normalizeNotesLinkUrl(link.url);
		insertHyperlinkAtSelection(finalUrl, link.displayText || finalUrl);
		this.onRichInput();
	}

	/* --- Plain textarea --- */

	onPlainCommit(event: Event): void {
		const value = (event.target as HTMLTextAreaElement).value;
		this.draftText = value;
		this.draftSegments = createPlainNotesSegments(value);
		this.emitNow(value);
	}

	/* --- Toggle + print --- */

	toggleRich(): void {
		const richEl = this.richEditor()?.nativeElement;
		const plainEl = this.textarea()?.nativeElement;
		if (this.isRichEnabled() && richEl) {
			const next = readEditorSegments(richEl);
			this.draftSegments = next.segments;
			this.draftText = next.text;
		} else if (!this.isRichEnabled() && plainEl) {
			this.draftText = plainEl.value;
			this.draftSegments = createPlainNotesSegments(this.draftText);
		}
		this.isRichEnabled.update((v) => !v);
		queueMicrotask(() => this.seedActiveSurface());
	}

	printNotes(): void {
		const slide = this.slide();
		if (!slide || typeof document === 'undefined') {
			return;
		}
		const html = buildNotesPrintHtml(
			[slide],
			(n) => this.translate.instant('pptx.notes.slideN', { n }),
			this.notesStyle(),
		);
		const frame = document.createElement('iframe');
		frame.setAttribute('aria-hidden', 'true');
		frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0';
		document.body.appendChild(frame);
		const doc = frame.contentWindow?.document;
		if (!doc) {
			frame.remove();
			return;
		}
		doc.open();
		doc.write(html);
		doc.close();
		setTimeout(() => {
			frame.contentWindow?.focus();
			frame.contentWindow?.print();
			setTimeout(() => frame.remove(), 1000);
		}, 200);
	}
}

// viewers/pptx/packages/svelte/src/viewer/components/NotesPanel.svelte
<script lang="ts">
	/**
	 * NotesPanel: collapsible speaker-notes panel, docked below the slide
	 * stage. It supports plain text on compact screens plus a desktop-oriented
	 * rich contentEditable surface with a compact formatting toolbar.
	 *
	 * Reads the current slide's notes via the shared `resolveNotesSegments` /
	 * `segmentsToPlainText` helpers (falls back to plain `slide.notes` when the
	 * deck has no rich `notesSegments`). When the host passes `notesStyle` (the
	 * deck's notes master `<p:notesStyle>` defaults), a seeded segment's missing
	 * font/colour/indent fields are filled in from it without overriding any
	 * value the segment already carries explicitly. This binding has no
	 * built-in slide-mutation channel, so writes go through the `onupdate`
	 * callback prop; omitting it renders a read-only textarea.
	 *
	 * Touch / focus correctness
	 * --------------------------
	 * The textarea is UNCONTROLLED while focused: its `value` is seeded from a
	 * local `$state` that is only reassigned inside an `$effect` gated on the
	 * slide id changing, never on every reactive tick. Edits commit on
	 * `change` / `blur` (not `input`), so an in-progress keystroke never gets
	 * fought by a reactive re-seed (mirrors Vue's `useNotesEditor` rationale).
	 */
	import type { TextSegment } from 'pptx-viewer-core';
	import {
		applyInlineCommand,
		applyParagraphCommand,
		buildNotesPrintHtml,
		defaultRichEnabled,
		handleEditorAnchorClick,
		insertHyperlinkAtSelection,
		observeElementHeight,
		readEditorSegments,
		resolveNotesSegments,
		segmentsToEditorHtml,
		segmentsToPlainText,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import type { NotesPanelProps } from './props';
	import { useNotesBarHeightSink } from '../state/notes-bar-height.svelte';
	import NotesFormattingToolbar from './NotesFormattingToolbar.svelte';

	const { slide, expanded = false, onupdate, ontoggle, notesStyle }: NotesPanelProps = $props();

	const t = useTranslator();

	const hasSlide = $derived(slide !== undefined);
	const collapsed = $derived(!expanded);
	/** No `onupdate` handler wired up: render a read-only surface. */
	const readonly = $derived(!onupdate);

	let text = $state('');
	let seededId: string | null = null;
	let rich = $state(defaultRichEnabled());
	// eslint-disable-next-line prefer-const
	let editorEl: HTMLDivElement | undefined = $state();
	// eslint-disable-next-line prefer-const
	let rootEl: HTMLElement | undefined = $state();
	const notesBarSink = useNotesBarHeightSink();

	// Report this strip's live height so the compat-toast stack can clear it;
	// resets to 0 on unmount.
	$effect(() => {
		const el = rootEl;
		if (!el || !notesBarSink) {
			return undefined;
		}
		const stop = observeElementHeight(el, (height) => notesBarSink.report(height));
		return () => {
			stop();
			notesBarSink.report(0);
		};
	});
	let segments: TextSegment[] = [];

	$effect(() => {
		const nextId = slide?.id ?? null;
		if (nextId === seededId) {
			return;
		}
		seededId = nextId;
		segments = resolveNotesSegments(slide, notesStyle);
		text = segmentsToPlainText(segments);
		if (editorEl) {editorEl.innerHTML = segmentsToEditorHtml(segments);}
	});

	function commit(event: Event): void {
		const value = (event.currentTarget as HTMLTextAreaElement).value;
		text = value;
		onupdate?.(value);
	}

	function commitRich(): void {
		if (!editorEl) {return;}
		const next = readEditorSegments(editorEl);
		segments = next.segments;
		text = next.text;
		onupdate?.(next.text, next.segments);
	}

	function inline(command: 'bold' | 'italic' | 'underline' | 'strikeThrough'): void {
		applyInlineCommand(command);
		commitRich();
		editorEl?.focus();
	}

	function paragraph(command: 'bullet' | 'numbered' | 'indent' | 'outdent'): void {
		if (!editorEl) {return;}
		const next = applyParagraphCommand(editorEl, segments, command);
		segments = next.segments;
		text = next.text;
		editorEl.innerHTML = segmentsToEditorHtml(next.segments);
		onupdate?.(next.text, next.segments);
		editorEl.focus();
	}

	function link(url: string, label: string): void {
		if (!editorEl) {return;}
		editorEl.focus();
		insertHyperlinkAtSelection(url, label);
		commitRich();
	}

	function toggleMode(): void {
		rich = !rich;
		if (rich && editorEl) {editorEl.innerHTML = segmentsToEditorHtml(segments);}
	}

	/**
	 * Print the current slide's speaker notes via the browser's native print
	 * dialog. Builds the document with the shared `buildNotesPrintHtml`
	 * (framework-neutral, honours `notesStyle`) and writes it into a hidden
	 * iframe, mirroring the Vue (`useNotesEditor.printNotes`) and Angular
	 * (`NotesPanelComponent.printNotes`) implementations exactly, so all logic
	 * stays in `pptx-viewer-shared` and no binding re-derives the print HTML.
	 */
	function printNotes(): void {
		if (!slide || typeof document === 'undefined') {return;}
		const html = buildNotesPrintHtml([slide], (n) => t('pptx.notes.slideN', { n }), notesStyle);
		const frame = document.createElement('iframe');
		frame.setAttribute('aria-hidden', 'true');
		frame.setAttribute('sandbox', 'allow-same-origin');
		frame.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0';
		document.body.appendChild(frame);
		const doc = frame.contentWindow?.document;
		if (!doc) {
			frame.remove();
			return;
		}
		doc.open();
		doc.write(html);
		doc.close();
		setTimeout(() => {
			frame.contentWindow?.focus();
			frame.contentWindow?.print();
			setTimeout(() => frame.remove(), 1000);
		}, 200);
	}
</script>

<section class="pptx-svelte-notes-panel" data-pptx-chrome="notes" data-collapsed={collapsed} bind:this={rootEl}>
	<button
		type="button"
		class="pptx-svelte-notes-header" data-pptx-chrome="notes-header"
		aria-expanded={!collapsed}
		aria-controls="slide-notes-content"
		onclick={() => ontoggle?.()}
	>
		<span class="pptx-svelte-notes-title">{t('pptx.notes.title')}</span>
	</button>

	<!-- `slide-notes-content` matches the id/aria-controls pair the React/Vue
	     notes panels emit (see e.g. `SlideNotesPanel.tsx`), part of the
	     framework-neutral e2e DOM contract documented in `playwright.config.ts`. -->
	<div id="slide-notes-content" class="pptx-svelte-notes-body" hidden={collapsed}>
		{#if !readonly}
			<NotesFormattingToolbar {rich} disabled={!hasSlide} oninline={inline} onparagraph={paragraph} onlink={link} onprint={printNotes} ontogglemode={toggleMode} />
		{/if}
		{#if rich && !readonly}
			<div class="pptx-svelte-notes-rich" bind:this={editorEl} contenteditable={hasSlide} role="textbox" tabindex="0" aria-multiline="true" aria-label={t('pptx.presenter.speakerNotes')} spellcheck="true" oninput={commitRich} onblur={commitRich} onclick={(event) => handleEditorAnchorClick(event.target, event.ctrlKey || event.metaKey)} onkeydown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') commitRich(); }}></div>
		{:else}
			<textarea class="pptx-svelte-notes-textarea" name="slide-notes" value={text} disabled={!hasSlide} {readonly} placeholder={hasSlide ? t('pptx.notes.addSpeakerNotes') : t('pptx.notes.noSlide')} aria-label={t('pptx.presenter.speakerNotes')} spellcheck="true" onchange={commit} onblur={commit}></textarea>
		{/if}
	</div>
</section>

<style>
	.pptx-svelte-notes-panel {
		display: flex;
		flex-direction: column;
		flex: none;
		border-top: 1px solid var(--pptx-border, #33334d);
		background: var(--pptx-card, #1e1e2e);
		color: var(--pptx-card-foreground, #e2e8f0);
		font-family: system-ui, sans-serif;
	}

	.pptx-svelte-notes-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		width: 100%;
		padding: 6px 10px;
		border: none;
		background: transparent;
		color: var(--pptx-muted-foreground, #94a3b8);
		font: inherit;
		font-size: 13px;
		font-weight: 600;
		text-align: left;
		cursor: pointer;
	}

	.pptx-svelte-notes-header:hover {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-accent-foreground, #f8fafc);
	}

	.pptx-svelte-notes-body {
		padding: 0 10px 10px;
	}

	.pptx-svelte-notes-textarea {
		box-sizing: border-box;
		width: 100%;
		min-height: 80px;
		resize: vertical;
		padding: 8px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b);
		color: var(--pptx-foreground, #e2e8f0);
		font: inherit;
		font-size: 13px;
		line-height: 1.5;
	}

	.pptx-svelte-notes-textarea:focus {
		outline: 2px solid var(--pptx-ring, #6366f1);
		outline-offset: -1px;
	}

	.pptx-svelte-notes-textarea:disabled {
		cursor: not-allowed;
		opacity: 0.6;
	}

	.pptx-svelte-notes-rich {
		box-sizing: border-box; min-height: 80px; max-height: 240px; overflow-y: auto;
		padding: 8px; border: 1px solid var(--pptx-border, #33334d); border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b); color: var(--pptx-foreground, #e2e8f0);
		font: 13px/1.5 system-ui, sans-serif; white-space: pre-wrap;
	}
	.pptx-svelte-notes-rich:focus { outline: 2px solid var(--pptx-ring, #6366f1); outline-offset: -1px; }
	.pptx-svelte-notes-rich :global(a) { color: #4a9eff; text-decoration: underline; cursor: pointer; }
</style>
