// viewers/pptx/packages/vue/src/viewer/components/PresenterView.vue
<script setup lang="ts">
/**
 * PresenterView - PowerPoint's presenter console: the control strip across the
 * top, the current slide (left, 70%), a rail (right, 30%) with clock, timer,
 * navigation, next-slide preview and speaker notes, the "all slides" navigator
 * and the 5-minute timer progress bar.
 *
 * The strip used to render ONLY in the empty-deck branch below, so with a real
 * deck the Vue console had no timer, no zoom, no annotation tools, no blackout,
 * no captions and no End button at all. It is now the first child of both
 * branches, as in React.
 *
 * Rendered as an absolute overlay by the host (`PresentationMode`). Keyboard
 * navigation is owned by the host; this component only emits intents.
 */
import type { PptxSlide } from 'pptx-viewer-core';
import {
	createInitialPresentationSnapshot,
	PRESENTER_CONSOLE_CLASSES,
	PRESENTER_RAIL_LABEL_KEYS,
	presenterPaneAdvancesOnClick,
	stepPresenterZoom,
} from 'ooxml-ui/pptx';
import type {
	AuthoredSlideRange,
	PresentationPointerTool,
	PresentationSnapshot,
} from 'ooxml-ui/pptx';
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { usePresenterClock } from '../composables/usePresenterClock';
import type { CanvasSize } from '../types';
import PresenterControlStrip from './PresenterControlStrip.vue';
import PresenterNotesRail from './PresenterNotesRail.vue';
import PresenterSlideGrid from './PresenterSlideGrid.vue';
import PresenterStagePane from './PresenterStagePane.vue';

const props = withDefaults(
	defineProps<{
		slides: PptxSlide[];
		currentSlideIndex: number;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		/** Timestamp (ms) the presentation started, or `null`. */
		presentationStartTime: number | null;
		audienceOpen?: boolean;
		snapshot?: PresentationSnapshot;
		/** Membership of the running custom show, for the next-slide preview. */
		activeCustomShow?: { slideRIds: string[] } | null;
		/** `p:showPr/p:sldRg`, resolved to deck indexes; `null`/`undefined` for no range. */
		authoredRange?: AuthoredSlideRange | null;
		/**
		 * Bumped by the host to raise the "all slides" grid (PowerPoint's Ctrl+S).
		 * A counter rather than a boolean so the host never has to be told when the
		 * grid is closed again: closing stays entirely local to this component.
		 */
		openSlideGridNonce?: number;
	}>(),
	{
		snapshot: () => createInitialPresentationSnapshot(),
	},
);

const emit = defineEmits<{
	(e: 'move', direction: 1 | -1): void;
	(e: 'exit' | 'open-audience' | 'close-audience' | 'swap-displays'): void;
	(e: 'navigate', index: number): void;
	(e: 'update-snapshot', patch: Partial<PresentationSnapshot>): void;
}>();

const { t } = useI18n();
const classes = PRESENTER_CONSOLE_CLASSES;
const railKeys = PRESENTER_RAIL_LABEL_KEYS;
const showSlides = ref(false);
watch(
	() => props.openSlideGridNonce,
	(nonce) => {
		if (nonce !== undefined && nonce > 0) {
			showSlides.value = true;
		}
	},
	// `immediate`, because Ctrl+S raises the console AND asks for the grid in one
	// press: this component mounts with the nonce ALREADY bumped, and a watcher
	// that only fires on later changes would miss the very press that opened it.
	{ immediate: true },
);

const { clockText, elapsedText, progress } = usePresenterClock(() => props.presentationStartTime);

/**
 * Clicking the current-slide pane advances the show, the way PowerPoint's
 * presenter console does. A drawing tool owns the pointer instead, so clicking
 * then annotates rather than jumping the deck.
 */
const paneAdvancesOnClick = computed(() =>
	presenterPaneAdvancesOnClick(props.snapshot.pointer?.tool),
);

function update(patch: Partial<PresentationSnapshot>): void {
	emit('update-snapshot', patch);
}
function setTool(tool: PresentationPointerTool): void {
	update({
		pointer: { ...(props.snapshot.pointer ?? { x: 0.5, y: 0.5, color: '#ef4444' }), tool },
	});
}
function zoom(direction: -1 | 1): void {
	update({
		zoom: stepPresenterZoom(
			props.snapshot.zoom ?? { scale: 1, originX: 0.5, originY: 0.5 },
			direction,
		),
	});
}
function toggleAudience(): void {
	emit(props.audienceOpen === true ? 'close-audience' : 'open-audience');
}

const currentSlide = computed<PptxSlide | undefined>(() => props.slides[props.currentSlideIndex]);
const timerTitle = computed(() =>
	t('pptx.presenter.timerTitle', {
		elapsed: elapsedText.value,
		segment: progress.value.segment + 1,
	}),
);
</script>

<template>
	<div
		class="pptx-vue-presenter"
		:class="[classes.root, { 'pptx-vue-presenter--empty': !currentSlide }]"
	>
		<PresenterControlStrip
			:snapshot="snapshot"
			:audience-open="Boolean(audienceOpen)"
			@timer="update({ paused: !snapshot.paused })"
			@reset-timer="update({ paused: false, elapsedMs: 0 })"
			@slides="showSlides = true"
			@zoom="zoom"
			@reset-zoom="update({ zoom: { scale: 1, originX: 0.5, originY: 0.5 } })"
			@blackout="(value) => update({ blackout: value })"
			@tool="setTool"
			@subtitles="update({ subtitlesVisible: !snapshot.subtitlesVisible })"
			@audience="toggleAudience"
			@swap-displays="emit('swap-displays')"
			@exit="emit('exit')"
		/>

		<div
			v-if="!currentSlide"
			class="pptx-vue-presenter-empty-body flex flex-1 items-center justify-center bg-card text-muted-foreground"
		>
			{{ t(railKeys.noSlides) }}
		</div>

		<template v-else>
			<div class="pptx-vue-presenter-body" :class="classes.body">
				<PresenterStagePane
					:slide="currentSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:slide-number="currentSlideIndex + 1"
					:slide-count="slides.length"
					:zoom="snapshot.zoom"
					:advances-on-click="paneAdvancesOnClick"
					@advance="emit('move', 1)"
				/>
				<PresenterNotesRail
					:slides="slides"
					:current-slide-index="currentSlideIndex"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:clock-text="clockText"
					:elapsed-text="elapsedText"
					:audience-open="Boolean(audienceOpen)"
					:active-custom-show="activeCustomShow"
					:authored-range="authoredRange"
					@move="(direction) => emit('move', direction)"
					@audience="toggleAudience"
					@exit="emit('exit')"
				/>
			</div>

			<PresenterSlideGrid
				v-if="showSlides"
				:slides="slides"
				:current="currentSlideIndex"
				:canvas-size="canvasSize"
				:media-data-urls="mediaDataUrls"
				@select="
					(index) => {
						emit('navigate', index);
						showSlides = false;
					}
				"
				@close="showSlides = false"
			/>

			<!-- Timer progress bar -->
			<div
				class="pptx-vue-presenter-progress"
				:class="classes.progressTrack"
				role="progressbar"
				:aria-valuenow="Math.round(progress.percent)"
				:aria-valuemin="0"
				:aria-valuemax="100"
				:aria-label="t(railKeys.timerProgress)"
				:title="timerTitle"
			>
				<div
					class="pptx-vue-presenter-progress-fill"
					:class="classes.progressFill"
					:style="{ width: `${progress.percent}%` }"
				/>
			</div>
		</template>
	</div>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/PresenterView.svelte
<script lang="ts">
	/**
	 * PresenterView: PowerPoint's presenter console.
	 *
	 * A thin composition layer over four sub-components (strip, stage, rail,
	 * navigator), which is what keeps this file inside the repo's 300-line
	 * budget; it owns only the console's own state (clock, timer, notes font
	 * size, navigator visibility) and the dispatch from a shared control id onto
	 * the snapshot patch it produces.
	 *
	 * The strip's inventory and the console's measurements come from
	 * `pptx-viewer-shared`. Measurements arrive as CSS custom properties on the
	 * root's inline style attribute, because a Svelte scoped style block is
	 * compiled ahead of time and cannot read a TypeScript value; every descendant
	 * then inherits them. This is the same seam `PresentationToolbar.svelte`
	 * already uses for `presentToolbarStyleAttr()`.
	 *
	 * The timer is driven by the shared `presenter-console` state helpers rather
	 * than by subtracting `startedAt` from the clock, so Pause actually pauses;
	 * each change is mirrored into the snapshot so an audience display agrees.
	 */
	import type { PptxSlide } from 'pptx-viewer-core';
	import {
		clampPresenterZoom,
		createPresenterTimer,
		formatElapsed,
		NOTES_FONT_SIZE_DEFAULT,
		presenterConsoleStyleAttr,
		presenterElapsed,
		presenterPaneAdvancesOnClick,
		PRESENTER_RAIL_LABEL_KEYS,
		presenterTimerProgress,
		resetPresenterTimer,
		stepPresenterZoom,
		togglePresenterTimer,
	} from 'ooxml-ui/pptx';
	import type {
		AuthoredSlideRange,
		CanvasSize,
		PresentationSnapshot,
		ShowOrderCustomShow,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import { isPresenterPointerTool } from './presenter-console-strip';
	import PresenterConsoleStrip from './PresenterConsoleStrip.svelte';
	import PresenterNotesRail from './PresenterNotesRail.svelte';
	import PresenterSlideNavigator from './PresenterSlideNavigator.svelte';
	import PresenterStage from './PresenterStage.svelte';

	const {
		slides,
		current,
		canvasSize,
		mediaDataUrls,
		startedAt,
		audienceOpen,
		activeCustomShow,
		authoredRange,
		onmove,
		onaudience,
		onswap,
		onexit,
		snapshot,
		onupdate,
		onnavigate,
	}: {
		slides: PptxSlide[];
		current: number;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		startedAt: number;
		audienceOpen: boolean;
		/** The custom show playback is restricted to; drives the next-slide preview. */
		activeCustomShow?: ShowOrderCustomShow | null;
		/** `p:showPr/p:sldRg`; drives the next-slide preview alongside `activeCustomShow`. */
		authoredRange?: AuthoredSlideRange | null;
		/** Step the SHOW, so hidden slides are skipped (the host owns show order). */
		onmove: (direction: -1 | 1) => void;
		onaudience: () => void;
		/** Move the console to the audience screen and vice versa. */
		onswap: () => void;
		onexit: () => void;
		snapshot: PresentationSnapshot;
		onupdate: (patch: Partial<PresentationSnapshot>) => void;
		onnavigate: (index: number) => void;
	} = $props();

	const t = useTranslator();
	const metricVars = presenterConsoleStyleAttr();

	let now = $state(Date.now());
	// Seeded once, deliberately: the console is mounted fresh each time presenter
	// view opens (`{#if vm.presenterMode}`), and after that the timer is the
	// presenter's to pause and reset, not something a prop may overwrite.
	// svelte-ignore state_referenced_locally
	let timer = $state(createPresenterTimer(startedAt));
	let notesSize = $state(NOTES_FONT_SIZE_DEFAULT);
	let showSlides = $state(false);

	$effect(() => {
		const tick = setInterval(() => (now = Date.now()), 1000);
		return () => clearInterval(tick);
	});

	const elapsed = $derived(presenterElapsed(timer, now));
	const progress = $derived(presenterTimerProgress(elapsed));

	// An armed drawing tool owns the pointer, so the current-slide pane must stop
	// advancing on click while one is active or it jumps the deck out from under
	// the stroke.
	const paneAdvances = $derived(presenterPaneAdvancesOnClick(snapshot.pointer?.tool));

	function setNotesSize(size: number): void {
		notesSize = size;
	}

	function closeNavigator(): void {
		showSlides = false;
	}

	function setTool(tool: string): void {
		if (!isPresenterPointerTool(tool)) {
			return;
		}
		const pointer = snapshot.pointer ?? { x: 0.5, y: 0.5, color: '#ef4444', tool: 'none' };
		onupdate({ pointer: { ...pointer, tool: pointer.tool === tool ? 'none' : tool } });
	}

	function zoomBy(direction: 1 | -1): void {
		onupdate({
			zoom: stepPresenterZoom(snapshot.zoom ?? clampPresenterZoom({}), direction),
		});
	}

	/** Dispatch a strip control id onto the console's behaviour. */
	function onControl(id: string): void {
		switch (id) {
			case 'timer-toggle': {
				// `Date.now()`, not the once-a-second clock tick: pausing must freeze
				// the timer at the instant of the press, not at the last tick.
				const at = Date.now();
				timer = togglePresenterTimer(timer, at);
				onupdate({ paused: timer.paused, elapsedMs: presenterElapsed(timer, at) });
				break;
			}
			case 'timer-reset':
				timer = resetPresenterTimer(Date.now());
				onupdate({ paused: false, elapsedMs: 0 });
				break;
			case 'all-slides':
				showSlides = true;
				break;
			case 'zoom-in':
				zoomBy(1);
				break;
			case 'zoom-out':
				zoomBy(-1);
				break;
			case 'zoom-reset':
				onupdate({ zoom: clampPresenterZoom({}) });
				break;
			case 'blackout-black':
				onupdate({ blackout: snapshot.blackout === 'black' ? 'none' : 'black' });
				break;
			case 'blackout-white':
				onupdate({ blackout: snapshot.blackout === 'white' ? 'none' : 'white' });
				break;
			case 'captions':
				onupdate({ subtitlesVisible: !snapshot.subtitlesVisible });
				break;
			case 'audience':
				onaudience();
				break;
			case 'swap-displays':
				onswap();
				break;
			case 'end':
				onexit();
				break;
			default:
				setTool(id);
		}
	}
</script>

<div
	class="pptx-svelte-presenter"
	role="dialog"
	aria-label={t('pptx.presenter.presenterView')}
	style={metricVars}
>
	<PresenterConsoleStrip {snapshot} {audienceOpen} onselect={onControl} />

	<div class="pptx-svelte-presenter-body">
		<PresenterStage
			slide={slides[current]}
			{current}
			total={slides.length}
			{canvasSize}
			{mediaDataUrls}
			zoom={snapshot.zoom}
			advances={paneAdvances}
			onadvance={() => onmove(1)}
		/>

		<PresenterNotesRail
			{slides}
			{current}
			{canvasSize}
			{mediaDataUrls}
			{now}
			{elapsed}
			{notesSize}
			{activeCustomShow}
			{authoredRange}
			{onmove}
			onnotessize={setNotesSize}
		/>
	</div>

	<!-- Elapsed-time pacing bar: one fill is `PRESENTER_TIMER_SEGMENT_MS`, the
	     five-minute interval PowerPoint's own console paces a talk in. -->
	<div
		class="pptx-svelte-presenter-progress"
		role="progressbar"
		aria-valuemin={0}
		aria-valuemax={100}
		aria-valuenow={Math.round(progress.percent)}
		aria-label={t(PRESENTER_RAIL_LABEL_KEYS.timerProgress)}
		title={t('pptx.presenter.timerTitle', {
			elapsed: formatElapsed(elapsed),
			segment: progress.segment + 1,
		})}
	>
		<div style={`width:${progress.percent}%`}></div>
	</div>

	{#if showSlides}
		<PresenterSlideNavigator
			{slides}
			{current}
			{canvasSize}
			{mediaDataUrls}
			onselect={(index) => {
				onnavigate(index);
				closeNavigator();
			}}
			onclose={closeNavigator}
		/>
	{/if}
</div>

<style>
	.pptx-svelte-presenter {
		position: absolute;
		z-index: var(--pptx-pv-z);
		inset: 0;
		display: flex;
		flex-direction: column;
		background: var(--pptx-card, #111827);
		color: var(--pptx-foreground, #f8fafc);
	}

	.pptx-svelte-presenter-body {
		display: flex;
		min-height: 0;
		flex: 1;
	}

	.pptx-svelte-presenter-progress {
		flex-shrink: 0;
		width: 100%;
		height: var(--pptx-pv-progress-h);
		background: var(--pptx-muted, #1e293b);
	}

	.pptx-svelte-presenter-progress > div {
		height: 100%;
		background: var(--pptx-primary, #38bdf8);
		transition: width 1s linear;
	}
</style>
