// viewers/pptx/packages/react/src/viewer/components/RibbonCustomizationStyle.tsx
/**
 * Group- and control-level ribbon hiding for one viewer instance.
 *
 * The viewer root carries `data-pptx-ribbon-scope="<token>"` and this
 * component renders the ONE `<style>` element whose rules (built by the
 * shared `ribbonCustomizationCss`) hide every `data-ribbon-group` /
 * `data-ribbon-control` the host named, confined to that root so a second
 * viewer on the page is untouched.
 */
import type { ResolvedCustomization } from 'ooxml-ui/pptx';
import { ribbonCustomizationCss } from 'ooxml-ui/pptx';
import React, { useId, useMemo } from 'react';

/**
 * A per-instance scope token. `useId` output carries punctuation (`:r1:`,
 * `«r1»`) that the shared scope validator rejects, so only the word
 * characters are kept; they are still unique per instance.
 */
export function useRibbonScopeToken(): string {
	const id = useId();
	return `pptx-ribbon-${id.replace(/[^\w-]/gu, '')}`;
}

export interface RibbonCustomizationStyleProps {
	resolved: ResolvedCustomization;
	scope: string;
}

export function RibbonCustomizationStyle({
	resolved,
	scope,
}: RibbonCustomizationStyleProps): React.ReactElement {
	const css = useMemo(() => ribbonCustomizationCss(resolved, scope), [resolved, scope]);
	return <style data-pptx-ribbon-customization=''>{css}</style>;
}

// viewers/pptx/packages/svelte/src/viewer/components/RibbonCustomizationStyle.svelte
<script lang="ts">
	/**
	 * RibbonCustomizationStyle: the viewer's ONE `<style>` element for host
	 * ribbon-group / ribbon-control hiding. The rules come from shared's
	 * `ribbonCustomizationCss` (which validates every id against the catalogue,
	 * so a host string cannot inject CSS), scoped to this viewer's
	 * `data-pptx-ribbon-scope` token so two viewers on a page never hide each
	 * other's controls. Re-renders whenever the resolved customisation changes
	 * (the `customization` prop or an imperative `hideRibbonGroup(...)`).
	 */
	import { ribbonCustomizationCss } from 'ooxml-ui/pptx';

	import { useViewerCustomization } from '../state/viewer-customization.svelte';

	const { scope }: { scope: string } = $props();
	const custom = useViewerCustomization();
	// Split so neither the markup nor the script parser sees a literal closing
	// style tag.
	const CLOSE = ['<', '/style>'].join('');
	const markup = $derived(
		`<style data-pptx-ribbon-customization="">${ribbonCustomizationCss(custom.resolved, scope)}${CLOSE}`,
	);
</script>

{@html markup}
