// viewers/pptx/packages/angular/src/viewer/run-program-notices.component.ts
/**
 * run-program-notices.component.ts: "Run program" notice stack for a running
 * slide show.
 *
 * Selector: `pptx-run-program-notices`
 *
 * PowerPoint's `ppaction://program` action ("Run program") cannot be launched
 * from a browser. Rather than doing nothing (silently) or blocking the show
 * with a modal dialog, `PresentationInputController`'s `runProgram` callback
 * (via {@link RunProgramNoticeStore}) surfaces a small, non-blocking notice
 * naming the exact command PowerPoint would have run, with a Copy button.
 *
 * Purely presentational, mirroring `CompatToastsComponent`'s card markup: the
 * store owns the notice list and this component only renders it and forwards
 * dismiss/copy clicks. See `presentation-overlay-chrome-styles.ts`'s
 * `RUN_PROGRAM_NOTICE_STACK_STYLE` doc comment for why this does not reuse
 * shared's `compatToastStackStyle` for positioning.
 *
 * @module viewer/run-program-notices
 */
import { NgStyle } from '@angular/common';
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { canUseClipboard } from 'ooxml-ui/pptx';
import type { RunProgramNotice } from 'ooxml-ui/pptx';
import { RUN_PROGRAM_NOTICE_STACK_STYLE } from './presentation-overlay-chrome-styles';

@Component({
	selector: 'pptx-run-program-notices',
	standalone: true,
	imports: [NgStyle, TranslatePipe],
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		@if (notices().length > 0) {
			<div
				class="pptx-ng-run-program-notices"
				data-testid="pptx-run-program-notices"
				[ngStyle]="stackStyle"
			>
				@for (notice of notices(); track notice.id) {
					<div
						class="pptx-ng-run-program-notice"
						data-testid="pptx-run-program-notice"
						[attr.data-target]="notice.target"
						role="status"
						style="pointer-events:auto"
					>
						<p class="pptx-ng-run-program-notice__message">
							{{ notice.messageKey | translate: { target: notice.target } }}
						</p>
						<div class="pptx-ng-run-program-notice__actions">
							@if (clipboardAvailable) {
								<button
									type="button"
									data-testid="pptx-run-program-notice-copy"
									class="pptx-ng-run-program-notice__button"
									(click)="copy(notice.target)"
								>
									{{ notice.copyLabelKey | translate }}
								</button>
							}
							<button
								type="button"
								data-testid="pptx-run-program-notice-dismiss"
								class="pptx-ng-run-program-notice__button"
								[attr.aria-label]="'pptx.compatibility.dismiss' | translate"
								(click)="dismiss.emit(notice.id)"
							>
								&times;
							</button>
						</div>
					</div>
				}
			</div>
		}
	`,
	styles: `
		.pptx-ng-run-program-notice {
			border-radius: 4px;
			border: 1px solid rgba(255, 255, 255, 0.2);
			background: rgba(0, 0, 0, 0.75);
			color: #fff;
			padding: 8px 10px;
			font-size: 12px;
			line-height: 1.4;
			box-shadow: 0 2px 10px rgba(0, 0, 0, 0.35);
		}
		.pptx-ng-run-program-notice__message {
			margin: 0 0 6px;
			overflow-wrap: anywhere;
		}
		.pptx-ng-run-program-notice__actions {
			display: flex;
			justify-content: flex-end;
			gap: 8px;
		}
		.pptx-ng-run-program-notice__button {
			background: transparent;
			border: 1px solid rgba(255, 255, 255, 0.35);
			border-radius: 3px;
			color: inherit;
			font-size: 11px;
			padding: 2px 8px;
			cursor: pointer;
		}
		.pptx-ng-run-program-notice__button:hover {
			background: rgba(255, 255, 255, 0.12);
		}
	`,
})
export class RunProgramNoticesComponent {
	/** The notice list ({@link RunProgramNoticeStore.notices}). */
	readonly notices = input.required<readonly RunProgramNotice[]>();
	/** Dismiss one notice by id. */
	readonly dismiss = output<string>();

	/** See {@link RUN_PROGRAM_NOTICE_STACK_STYLE}'s doc comment. */
	protected readonly stackStyle = RUN_PROGRAM_NOTICE_STACK_STYLE;

	/**
	 * Whether an async clipboard write is available, checked once: a runtime's
	 * clipboard support does not change over the component's lifetime. False
	 * hides the Copy button entirely rather than rendering a button that would
	 * no-op on click.
	 */
	protected readonly clipboardAvailable = canUseClipboard(
		typeof navigator === 'undefined' ? undefined : navigator,
	);

	/** Copy a notice's resolved command to the clipboard. No-ops on failure. */
	protected copy(target: string): void {
		if (!this.clipboardAvailable) {
			return;
		}
		navigator.clipboard.writeText(target).catch(() => undefined);
	}
}

// viewers/pptx/packages/svelte/src/viewer/components/RunProgramNotices.svelte
<script lang="ts">
	/**
	 * RunProgramNotices: the notice stack shown during a running show when an
	 * on-slide `ppaction://program` ("Run program") action is clicked. A
	 * browser cannot launch the author's command, so each click raises a
	 * dismissible, non-blocking notice naming the exact resolved command
	 * (`pptx-viewer-shared`'s `buildRunProgramNotice`) instead of silently doing
	 * nothing or blocking the show with a native `alert`/`confirm`.
	 *
	 * Deliberately a sibling of `CompatibilityToasts.svelte` rather than an
	 * extension of it: the two notice kinds carry unrelated data (a load
	 * diagnostic vs. a resolved shell command) and unrelated actions (dismiss
	 * vs. dismiss + copy). They do share the same visual primitive though, the
	 * `pptx-viewer-shared` toast-stack positioning (`compatToastStackStyleAttr`),
	 * reused here for a consistent look; the two stacks never actually overlap
	 * on screen since compat toasts hide in fullscreen and this one only
	 * renders in fullscreen (see `PresentationOverlays.svelte`).
	 */
	import type { RunProgramNotice } from 'ooxml-ui/pptx';
	import { canUseClipboard, compatToastStackStyleAttr } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';

	const {
		notices,
		ondismiss,
	}: {
		notices: readonly RunProgramNotice[];
		ondismiss: (id: string) => void;
	} = $props();

	const t = useTranslator();
	const stackStyle = compatToastStackStyleAttr();
	const clipboardAvailable = canUseClipboard(
		typeof navigator === 'undefined' ? undefined : navigator,
	);

	function copy(target: string): void {
		if (!clipboardAvailable) {
			return;
		}
		void navigator.clipboard.writeText(target);
	}
</script>

{#if notices.length > 0}
	<div class="pptx-svelte-run-program-notices" style={stackStyle}>
		{#each notices as notice (notice.id)}
			<div
				class="pptx-svelte-run-program-notice"
				data-testid="pptx-run-program-notice"
				data-target={notice.target}
			>
				<span class="pptx-svelte-run-program-notice-icon" aria-hidden="true">&#9888;&#65039;</span>
				<p class="pptx-svelte-run-program-notice-message">
					{t(notice.messageKey, { target: notice.target })}
				</p>
				<div class="pptx-svelte-run-program-notice-actions">
					{#if clipboardAvailable}
						<button
							type="button"
							data-testid="pptx-run-program-notice-copy"
							class="pptx-svelte-run-program-notice-copy"
							onclick={() => copy(notice.target)}
						>
							{t(notice.copyLabelKey)}
						</button>
					{/if}
					<button
						type="button"
						aria-label={t('pptx.compatibility.dismiss')}
						class="pptx-svelte-run-program-notice-dismiss"
						onclick={() => ondismiss(notice.id)}
					>
						&#10005;
					</button>
				</div>
			</div>
		{/each}
	</div>
{/if}

<style>
	/* The container's position/size/z-index come from the inline `style`
	   attribute (shared's COMPAT_TOAST_METRICS); this block only styles what a
	   scoped stylesheet can express (colors, borders, per-notice layout). */
	.pptx-svelte-run-program-notice {
		display: flex;
		align-items: flex-start;
		gap: 8px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 6px;
		padding: 10px;
		background: var(--pptx-popover, #1e1e2e);
		box-shadow: 0 8px 24px rgba(0, 0, 0, 0.35);
		font-size: 12px;
		pointer-events: auto;
	}
	.pptx-svelte-run-program-notice-icon {
		flex: none;
		margin-top: 2px;
	}
	.pptx-svelte-run-program-notice-message {
		flex: 1 1 auto;
		margin: 0;
		color: var(--pptx-foreground, #e2e8f0);
		word-break: break-word;
	}
	.pptx-svelte-run-program-notice-actions {
		display: flex;
		flex: none;
		flex-direction: column;
		align-items: stretch;
		gap: 4px;
	}
	.pptx-svelte-run-program-notice-copy {
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 4px;
		padding: 2px 8px;
		background: transparent;
		color: var(--pptx-foreground, #e2e8f0);
		font-size: 11px;
		cursor: pointer;
	}
	.pptx-svelte-run-program-notice-copy:hover {
		background: var(--pptx-accent, #33334d);
	}
	.pptx-svelte-run-program-notice-dismiss {
		border: 0;
		border-radius: 4px;
		padding: 2px;
		background: transparent;
		color: var(--pptx-muted-foreground, #94a3b8);
		cursor: pointer;
	}
	.pptx-svelte-run-program-notice-dismiss:hover {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-foreground, #e2e8f0);
	}
</style>
