// viewers/pptx/packages/angular/src/viewer/settings-appearance-tab.component.ts
/**
 * settings-appearance-tab.component.ts: File > Options > Appearance tab.
 *
 * A theme-preset swatch gallery over `THEME_CATALOG` (or a host-supplied
 * `availableThemes` catalog), extracted out of `SettingsDialogComponent` to
 * keep that file under the repo's ~300-LOC guideline. Mirrors the swatch
 * pattern used by the vanilla/Svelte Design tab theme galleries, adapted to
 * this binding's CSS-variable-driven visual language.
 */
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import type { ThemeCatalogEntry } from 'ooxml-ui/pptx';

@Component({
	selector: 'pptx-settings-appearance-tab',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<div class="pptx-ng-theme-gallery" role="radiogroup">
			@for (entry of themes(); track entry.key) {
				<button
					type="button"
					role="radio"
					class="pptx-ng-theme-swatch"
					[attr.aria-checked]="entry.key === activeKey()"
					[class.is-active]="entry.key === activeKey()"
					(click)="select.emit(entry.key)"
				>
					<span class="pptx-ng-theme-swatch-preview" [style.background]="swatchColor(entry)"></span>
					<span>{{ entry.labelKey | translate }}</span>
				</button>
			}
		</div>
	`,
	styles: [
		`
			.pptx-ng-theme-gallery {
				display: grid;
				grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
				gap: 10px;
				padding-top: 8px;
			}
			.pptx-ng-theme-swatch {
				display: flex;
				flex-direction: column;
				align-items: center;
				gap: 8px;
				padding: 10px 8px;
				border: 1px solid var(--pptx-border);
				border-radius: 6px;
				background: var(--pptx-card);
				color: inherit;
				font-size: 12px;
				cursor: pointer;
			}
			.pptx-ng-theme-swatch.is-active {
				border-color: var(--pptx-primary);
				box-shadow: 0 0 0 1px var(--pptx-primary);
			}
			.pptx-ng-theme-swatch-preview {
				width: 100%;
				height: 32px;
				border-radius: 4px;
			}
		`,
	],
})
export class SettingsAppearanceTabComponent {
	readonly themes = input.required<readonly ThemeCatalogEntry[]>();
	readonly activeKey = input<string>('default');
	readonly select = output<string>();

	protected swatchColor(entry: ThemeCatalogEntry): string {
		return entry.theme?.colors?.primary ?? '#6b7280';
	}
}

// viewers/pptx/packages/svelte/src/viewer/components/SettingsAppearanceTab.svelte
<script lang="ts">
	/**
	 * File > Options > Appearance: swatch gallery over the viewer chrome's
	 * theme catalog, mirroring React's `SettingsAppearanceTab` layout: a
	 * 2-column grid of preview cards (split background/primary swatch + label,
	 * highlighted border when selected). Generalizes the ribbon Design tab's
	 * smaller `THEME_SWATCHES` idiom (see `ribbon/design/theme-swatches.ts`) to
	 * the full `THEME_CATALOG` (or a host-supplied `availableThemes`), and
	 * shares `PowerPointViewer`'s single `themeKey` state with it so both stay
	 * in sync.
	 */
	import type { ThemeCatalogEntry } from 'ooxml-ui/pptx';
	import { useTranslator } from '../../i18n/context';

	const {
		themeKey,
		themeCatalog,
		onselect,
	}: {
		themeKey: string;
		themeCatalog: readonly ThemeCatalogEntry[];
		onselect: (key: string) => void;
	} = $props();
	const t = useTranslator();
</script>

<div class="gallery">
	{#each themeCatalog as entry (entry.key)}
		{@const previewBackground = entry.theme?.colors?.background ?? '#0b0f19'}
		{@const previewPrimary = entry.theme?.colors?.primary ?? '#6366f1'}
		<button
			type="button"
			class:active={entry.key === themeKey}
			aria-pressed={entry.key === themeKey}
			onclick={() => onselect(entry.key)}
		>
			<span
				class="swatch"
				style={`background: linear-gradient(135deg, ${previewBackground} 50%, ${previewPrimary} 50%)`}
			></span>
			<span class="label">{t(entry.labelKey)}</span>
		</button>
	{/each}
</div>

<style>
	.gallery {
		display: grid;
		grid-template-columns: repeat(2, minmax(0, 1fr));
		gap: 12px;
		padding: 4px 0;
	}

	.gallery button {
		display: flex;
		align-items: center;
		gap: 12px;
		padding: 10px 12px;
		border: 1px solid var(--pptx-border, #3f3f52);
		border-radius: 8px;
		background: transparent;
		color: inherit;
		cursor: pointer;
		font: inherit;
		text-align: left;
		transition:
			border-color 0.15s ease,
			background-color 0.15s ease;
	}

	.gallery button:hover {
		border-color: color-mix(in srgb, var(--pptx-primary, #6366f1) 50%, transparent);
		background: var(--pptx-accent, #33334d);
	}

	.gallery button.active {
		border-color: var(--pptx-primary, #6366f1);
		background: color-mix(in srgb, var(--pptx-primary, #6366f1) 10%, transparent);
	}

	.swatch {
		display: inline-block;
		flex: none;
		width: 32px;
		height: 32px;
		border-radius: 50%;
		border: 1px solid var(--pptx-border, #3f3f52);
		box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.25);
	}

	.label {
		font-size: 12px;
		font-weight: 500;
		color: var(--pptx-card-foreground, #e2e8f0);
	}

	.gallery button.active .label {
		color: var(--pptx-primary, #6366f1);
	}
</style>
