// viewers/pptx/packages/react/src/viewer/components/SettingsLanguageTab.tsx
import type { LocaleCatalogEntry } from 'ooxml-ui/pptx/i18n';
import React from 'react';

import { cn } from '../utils';

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export interface SettingsLanguageTabProps {
	activeLocale: string;
	/** Locales resolved from the host's registered i18n resources (falls back to `LOCALE_CATALOG`). */
	locales: readonly LocaleCatalogEntry[];
	onSelectLocale: (code: string) => void;
}

/** File > Options > Language: a simple list over the resolved locale catalog. */
export function SettingsLanguageTab({
	activeLocale,
	locales,
	onSelectLocale,
}: SettingsLanguageTabProps): React.ReactElement {
	return (
		<div className='space-y-0.5'>
			{locales.map((locale) => {
				const isActive = locale.code === activeLocale;
				return (
					<button
						key={locale.code}
						type='button'
						onClick={() => onSelectLocale(locale.code)}
						aria-pressed={isActive}
						className={cn(
							'flex w-full items-center justify-between rounded px-3 py-2.5 text-left transition-colors',
							isActive ? 'bg-primary/10 text-primary' : 'text-foreground hover:bg-accent',
						)}
					>
						<span className='text-sm'>{locale.nativeLabel}</span>
						{locale.nativeLabel !== locale.label && (
							<span className='text-xs text-muted-foreground'>{locale.label}</span>
						)}
					</button>
				);
			})}
		</div>
	);
}

// viewers/pptx/packages/svelte/src/viewer/components/SettingsLanguageTab.svelte
<script lang="ts">
	/**
	 * File > Options > Language: a list of locale choices. Defaults to every
	 * locale actually registered via `pptx-svelte-viewer/i18n`'s
	 * `registerTranslations` (English ships built in), labelled from the
	 * shared `LOCALE_CATALOG`, so this never offers a locale with no
	 * registered dictionary. A host can override the list with
	 * `availableLocales`.
	 */
	import { LOCALE_CATALOG } from 'ooxml-ui/pptx/i18n';
	import type { LocaleCatalogEntry } from 'ooxml-ui/pptx/i18n';
	import { getRegisteredLocales } from '../../i18n/translator';
	import { useTranslator } from '../../i18n/context';

	const {
		locale,
		availableLocales,
		onselect,
	}: {
		locale: string;
		availableLocales?: readonly LocaleCatalogEntry[];
		onselect: (code: string) => void;
	} = $props();
	const t = useTranslator();
	const choices = $derived<readonly LocaleCatalogEntry[]>(
		availableLocales ?? LOCALE_CATALOG.filter((entry) => getRegisteredLocales().includes(entry.code)),
	);
</script>

<div class="list" role="group" aria-label={t('pptx.settings.language')}>
	{#each choices as entry (entry.code)}
		<button
			type="button"
			class:active={entry.code === locale}
			aria-pressed={entry.code === locale}
			onclick={() => onselect(entry.code)}
		>
			<span class="native">{entry.nativeLabel}</span>
			<span class="label">{entry.label}</span>
		</button>
	{/each}
</div>

<style>
	.list {
		display: flex;
		flex-direction: column;
		gap: 4px;
		padding: 4px 0;
	}

	.list button {
		display: flex;
		align-items: baseline;
		gap: 8px;
		padding: 9px 11px;
		border: 0;
		border-radius: 6px;
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		cursor: pointer;
		font: inherit;
		font-size: 12px;
		text-align: left;
	}

	.list button:hover {
		background: var(--pptx-accent, #33334d);
	}

	.list button.active {
		outline: 2px solid var(--pptx-primary, #c43b32);
		outline-offset: -2px;
	}

	.native {
		font-weight: 600;
	}

	.label {
		color: var(--pptx-muted-foreground, #94a3b8);
	}
</style>
