// viewers/pptx/packages/vue/src/viewer/components/SlideStage.vue
<script setup lang="ts">
import {
	actionAffordanceLabels,
	applyElementActionAffordances,
	applyRenderedElementAccessibility,
	deviceStrokeStageStyle,
	getSlideBackgroundStyle,
	visibleTemplateElements,
} from 'ooxml-ui/pptx';
import type { PptxElement, PptxSlide } from 'pptx-viewer-core';
import type { CSSProperties } from 'vue';
import { computed, ref, watchPostEffect } from 'vue';
import { useI18n } from 'vue-i18n';

import { provideSlideFieldContext } from '../composables/field-context';
import { provideSlideElements } from '../composables/slide-elements';
import { stripElementIdMarkers } from '../composables/stage-element-markers';
import type { CanvasSize } from '../types';
import ElementRenderer from './ElementRenderer.vue';

/**
 * SlideStage - the fixed-size slide surface (background + absolutely-positioned
 * elements) rendered at a given `scale`.
 *
 * Extracted so it can be reused at full size by `SlideCanvas` and at tiny scale
 * by the thumbnail rail. It owns no chrome (no centering, margins, or shadow);
 * the host decides layout.
 *
 * Template (master/layout) elements are rendered in a DEDICATED layer behind the
 * slide content (lower z), supplied separately via `templateElements`. They are
 * interactive (and gain the editable affordance) only while `editTemplateMode`
 * is on; otherwise they render but are locked.
 *
 * Accessibility contract: exactly ONE `aria-roledescription="slide"` region
 * exists per surface. On the editable canvas that region is the `SlideCanvas`
 * wrapper (which also paints the resolved background), mirroring React's
 * `SlideCanvas.tsx`, so the interactive stage itself stays unlabelled. Only the
 * standalone live presentation stage (`presenting`, no wrapper) self-labels.
 * Static stages (thumbnails, sorter, previews, export) are `aria-hidden` and
 * additionally have their `data-element-id` markers stripped post-render (see
 * `stripElementIdMarkers`) so element queries always hit the real canvas copy.
 */
const props = withDefaults(
	defineProps<{
		slide: PptxSlide | undefined;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		scale?: number;
		/** Mark elements with the `data-pptx-element` interaction hook (main canvas only). */
		interactive?: boolean;
		/**
		 * Master/layout elements pulled out of the slide at load time, rendered in a
		 * dedicated layer behind the slide content.
		 */
		templateElements?: PptxElement[];
		/**
		 * When on, the template-layer elements become interactive and gain a visual
		 * affordance; when off they render but are locked. Only the main editable
		 * canvas threads this through.
		 */
		editTemplateMode?: boolean;
		/**
		 * True only for the live presentation stage: slide-content media autoplays
		 * (as in a real slideshow). Left false for thumbnails, the sorter, presenter
		 * previews and transition snapshots so their media stays quiet.
		 */
		presenting?: boolean;
		/**
		 * Keep the `data-element-id` markers on an otherwise-static stage.
		 *
		 * Only the Morph transition layers set this: their per-element CSS is
		 * keyed on those markers. It does not create a duplicate marked copy,
		 * because the host hides its own stage while the overlay is mounted.
		 */
		preserveElementIds?: boolean;
		/**
		 * Render the elements with NO slide background at all.
		 *
		 * `getSlideBackgroundStyle` always resolves to an opaque paint (it falls
		 * back to `DEFAULT_SLIDE_BACKGROUND` when the slide declares none), which is
		 * right for a real surface and fatal for a stage stacked over another one.
		 * The morph transition's departing-shape layer is exactly that: it sits on
		 * top of the incoming slide, so its background would hide the whole morph
		 * behind a flat slab for the entire transition.
		 */
		transparentBackground?: boolean;
		/**
		 * The element currently open in the element-level inline text editor
		 * (mounted as a slotted overlay by the host), threaded down so
		 * `ElementRenderer` can suppress its own text render for that one element
		 * instead of duplicating it underneath the editor (issue #182).
		 */
		inlineEditingElementId?: string | null;
	}>(),
	{ scale: 1 },
);
const { t } = useI18n();
const stageRef = ref<HTMLElement | null>(null);

// Re-point the deck-wide field context at THIS stage's slide before the element
// renderers read it: date / header / footer / document-property fields are
// presentation-wide, but the slide number and title are not, so a thumbnail,
// presenter preview or export stage must resolve them from the slide it paints
// rather than from the active one.
provideSlideFieldContext(() => props.slide);

/**
 * Template elements render behind the slide content; default to none, and
 * empty out entirely when the slide has "Hide Background Graphics"
 * (`showMasterShapes === false`) set.
 */
const templateElements = computed<PptxElement[]>(() => [
	...visibleTemplateElements(props.slide, props.templateElements ?? []),
]);

// Publish THIS stage's sibling list so a text box in an `a:linkedTxbx` chain can
// find the rest of its chain and render only its own slice of the overflow.
// Template elements are included because a chain may be authored on a layout.
provideSlideElements(() => [...templateElements.value, ...(props.slide?.elements ?? [])]);

/** Number of template elements, used to offset the main layer's z-index above them. */
const templateCount = computed(() => templateElements.value.length);
const accessibleElements = computed(() => [
	...templateElements.value,
	...(props.slide?.elements ?? []),
]);

/**
 * The template layer is interactive only when the canvas as a whole is
 * interactive AND edit-template mode is on. Computed here (not inline in the
 * template) so the SFC stays presentational. Declared above the post-render
 * effect below, which reads it.
 */
const templateLayerInteractive = computed(
	() => (props.interactive ?? false) && (props.editTemplateMode ?? false),
);

watchPostEffect(() => {
	const stage = stageRef.value;
	// Read the element list in both branches so structural changes re-trigger
	// this effect for static stages too (the strip must re-run after them).
	const elements = accessibleElements.value;
	if (!stage) {
		return;
	}
	if (props.interactive || props.presenting) {
		applyRenderedElementAccessibility(stage, elements, { presenting: props.presenting === true });
		// The on-canvas action affordances (amber badge + hover link tooltip) are
		// painted at the stage boundary rather than inside `ElementRenderer`,
		// because that component dispatches straight to a per-type view whose root
		// IS the element node, leaving no wrapper to hang the chrome off. A
		// template-layer element is only decorated while it is actually editable,
		// mirroring React's `canInteract` gate.
		applyElementActionAffordances(
			stage,
			[
				...(templateLayerInteractive.value ? templateElements.value : []),
				...(props.slide?.elements ?? []),
			],
			{
				canInteract: props.interactive === true,
				presenting: props.presenting === true,
				labels: actionAffordanceLabels((key) => t(key)),
			},
		);
	} else if (props.preserveElementIds) {
		// Morph drives per-element CSS keyed on `data-element-id`, so the two
		// transition layers must keep their markers. Safe because the host hides
		// its own stage while the overlay is mounted, so there is still exactly
		// one marked copy of each element on the page.
	} else {
		// Static surface (thumbnail, sorter, preview, export stage): remove the
		// `data-element-id` markers so only the real canvas / presentation stage
		// exposes them, matching React's marker-free static renderer.
		stripElementIdMarkers(stage);
	}
});

const stageStyle = computed<CSSProperties>(() => ({
	width: `${props.canvasSize.width}px`,
	height: `${props.canvasSize.height}px`,
	transform: `scale(${props.scale})`,
	transformOrigin: 'top left',
	// One device pixel in slide px: thin strokes stay visible on screen.
	...deviceStrokeStageStyle(props.scale),
	position: 'relative',
	overflow: 'hidden',
	// Motion-path keyframes translate by a fraction of the SLIDE, so the stage
	// publishes its own size for those calc() offsets. Set on every stage (edit,
	// presentation, thumbnails) because the path fractions are slide-relative
	// regardless of the scale the stage happens to be drawn at.
	'--pptx-slide-w': `${props.canvasSize.width}px`,
	'--pptx-slide-h': `${props.canvasSize.height}px`,
	// Resolved slide background: image -> gradient -> pattern -> solid colour.
	// A stacked overlay layer opts out entirely and stays see-through.
	...(props.transparentBackground
		? { background: 'none', backgroundColor: 'transparent' }
		: (getSlideBackgroundStyle(props.slide, {
				widthPx: props.canvasSize.width,
				heightPx: props.canvasSize.height,
			}) as CSSProperties)),
}));
</script>

<template>
	<div
		ref="stageRef"
		class="pptx-vue-stage"
		:style="stageStyle"
		:role="presenting ? 'region' : undefined"
		:aria-roledescription="presenting ? 'slide' : undefined"
		:aria-label="presenting ? t('pptx.canvas.slide') : undefined"
		:aria-hidden="!interactive && !presenting ? 'true' : undefined"
	>
		<!-- Template (master/layout) layer: behind the slide content (lower z).
		     `marked` keeps the data-pptx-element contract on these elements even
		     while they are interaction-locked (outside edit-template mode): the
		     marker means "rendered slide element", not "editable right now". -->
		<ElementRenderer
			v-for="(element, index) in templateElements"
			:key="element.id"
			:element="element"
			:media-data-urls="mediaDataUrls"
			:z-index="index"
			:interactive="templateLayerInteractive"
			:marked="interactive ?? false"
			:template-editing="editTemplateMode ?? false"
			:inline-editing-element-id="inlineEditingElementId"
		/>
		<!-- Slide content (template-free after the load-time partition). -->
		<ElementRenderer
			v-for="(element, index) in slide?.elements ?? []"
			:key="element.id"
			:element="element"
			:media-data-urls="mediaDataUrls"
			:z-index="index + templateCount"
			:interactive="interactive ?? false"
			:presenting="presenting ?? false"
			:inline-editing-element-id="inlineEditingElementId"
		/>
		<!-- Optional editing overlay (selection handles, etc.) shares this scaled space -->
		<slot />
	</div>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/SlideStage.svelte
<script lang="ts">
	/**
	 * SlideStage: the fixed-size slide surface (resolved background +
	 * absolutely-positioned elements) rendered at a given `scale` (Svelte port
	 * of Vue's `SlideStage`). Reused at full size by the main canvas and at
	 * tiny scale by the thumbnail rail; it owns no chrome, the host decides
	 * layout.
	 */
	import type { PptxElement } from 'pptx-viewer-core';
	import {
		actionAffordanceLabels,
		applyElementActionAffordances,
		applyRenderedElementAccessibility,
		deriveSlideFieldContext,
		deviceStrokeStageStyle,
		getSlideBackgroundStyle,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import { getFieldContextGetter, provideFieldContext } from '../state/field-context';
	import { provideSlideElements } from '../state/slide-elements';
	import { styleToString } from '../style';
	import ActiveXOverlay from './ActiveXOverlay.svelte';
	import CommentMarkersOverlay from './CommentMarkersOverlay.svelte';
	import ElementRenderer from './ElementRenderer.svelte';
	import type { SlideStageProps } from './props';

	const {
		slide,
		canvasSize,
		mediaDataUrls,
		scale = 1,
		presenting = false,
		interactive = false,
		editTemplateMode = false,
		editingElementId = null,
		editable = false,
		selectedElementIds,
		transparentBackground = false,
		ontablecellcommit,
		onsmartartnodecommit,
		onsmartartnodefill,
		onchartpointcommit,
		ontableresizecolumns,
		ontableresizerow,
		comments = [],
		oncommentmarkerclick,
	}: SlideStageProps = $props();

	const t = useTranslator();

	// Re-point the deck-wide field context at THIS stage's slide before the
	// element renderers read it: the date / header / footer / document-property
	// fields are presentation-wide, but the slide number and title are not, so a
	// thumbnail or presenter preview must resolve them from the slide it paints
	// rather than the active one. Both calls must happen at init (Svelte context
	// is captured once), hence the getter closure over the reactive `slide` prop.
	const getDeckFieldContext = getFieldContextGetter();
	provideFieldContext(() => deriveSlideFieldContext(getDeckFieldContext?.(), slide));

	// Publish THIS stage's sibling list so a text box in an `a:linkedTxbx` chain
	// can find the rest of its chain and render only its own slice of the
	// overflow. Also a getter, for the same init-time capture reason as above.
	provideSlideElements(() => slide?.elements);

	const stageStyle = $derived(
		styleToString({
			width: `${canvasSize.width}px`,
			height: `${canvasSize.height}px`,
			transform: `scale(${scale})`,
			transformOrigin: 'top left',
			// One device pixel in slide px: thin strokes stay visible on screen.
			...deviceStrokeStageStyle(scale),
			position: 'relative',
			overflow: 'hidden',
			// Motion-path keyframes translate by a fraction of the SLIDE, not of
			// the element box, so the stage publishes its own size for those
			// `calc()` offsets. Declared here rather than on each host because
			// this one component IS both the editing stage and the slide-show
			// stage in this binding (plus presenter / reading / thumbnail views).
			'--pptx-slide-w': `${canvasSize.width}px`,
			'--pptx-slide-h': `${canvasSize.height}px`,
			// Resolved slide background: image -> gradient -> pattern -> solid.
			// A stage stacked over another one opts out entirely and stays
			// see-through, so it cannot hide what it is animating over.
			...(transparentBackground
				? { background: 'none', backgroundColor: 'transparent' }
				: getSlideBackgroundStyle(slide, {
						widthPx: canvasSize.width,
						heightPx: canvasSize.height,
					})),
		}),
	);

	/** What the post-render stage passes need; each part must re-trigger them. */
	interface AccessibleStageParams {
		elements: readonly PptxElement[];
		/** True only for a RUNNING slide show, never for a thumbnail or preview. */
		presenting: boolean;
		/** True only for the live editing canvas; gates the action affordances. */
		interactive: boolean;
	}

	// `presenting` travels as an action PARAMETER rather than being closed over:
	// entering the show flips the flag on the SAME component instance, and an
	// action body only re-runs when its parameter changes. Closed over, the stage
	// stayed unmarked, the show's hit-testing rule never applied, and a
	// decorative shape painted over the deck's navigation swallowed every click.
	function accessibleStage(node: HTMLElement, params: AccessibleStageParams) {
		let current = params;
		function apply(): void {
			queueMicrotask(() => {
				applyRenderedElementAccessibility(node, current.elements, {
					presenting: current.presenting,
				});
				// The on-canvas action affordances (amber badge + hover link
				// tooltip) ride the same post-render pass: `ElementRenderer`
				// dispatches every non-shape type straight to a per-type view whose
				// root IS the element node, so there is no wrapper inside the
				// component tree to hang the chrome off.
				applyElementActionAffordances(node, current.elements, {
					canInteract: current.interactive,
					presenting: current.presenting,
					labels: actionAffordanceLabels((key) => t(key)),
				});
			});
		}
		apply();
		return {
			update(next: AccessibleStageParams): void {
				current = next;
				apply();
			},
		};
	}
</script>

<!-- Non-interactive stages (thumbnail rail, presenter previews) get no
     role/label but are NOT aria-hidden: they can contain real interactive
     controls (e.g. the OLE Download/Open action bar), and hiding a subtree
     with focusable controls is an accessibility violation that also removed
     those controls from the accessibility tree. Matches the other bindings,
     which only withhold the region role from thumbnail stages. -->
<div
	class="pptx-svelte-stage"
	use:accessibleStage={{ elements: slide?.elements ?? [], presenting, interactive }}
	style={stageStyle}
	role={interactive ? 'region' : undefined}
	aria-roledescription={interactive ? 'slide' : undefined}
	aria-label={interactive ? t('pptx.canvas.slide') : undefined}
>
	{#each slide?.elements ?? [] as element, index (element.id)}
		<ElementRenderer {element} {mediaDataUrls} zIndex={index} {presenting} {interactive} {editTemplateMode} {editingElementId} {editable} {selectedElementIds} {ontablecellcommit} {onsmartartnodecommit} {onsmartartnodefill} {onchartpointcommit} {ontableresizecolumns} {ontableresizerow} />
	{/each}
	{#if slide?.activeXControls && slide.activeXControls.length > 0}
		<ActiveXOverlay controls={slide.activeXControls} {canvasSize} />
	{/if}
	{#if comments.length > 0}
		<CommentMarkersOverlay {comments} {canvasSize} onmarkerclick={oncommentmarkerclick} />
	{/if}
</div>
