// viewers/pptx/packages/vue/src/viewer/components/WordArtText.vue
<script setup lang="ts">
import type { PptxElement, PptxElementWithText, TextSegment, TextStyle } from 'pptx-viewer-core';
import { getSubstituteFontFamily, hasTextProperties } from 'pptx-viewer-core';
import {
	buildWarpPath,
	DEFAULT_FONT_FAMILY,
	groupIntoParagraphs,
	normalizeHexColor,
	shouldUseSvgWarp,
	substituteFieldText,
} from 'ooxml-ui/pptx';
import type { EnvelopeGlyphPlacement, WarpParagraph } from 'ooxml-ui/pptx';
import { computed } from 'vue';

import { injectFieldContext, resolveFieldContext } from '../composables/field-context';
import { useTextWarpEnvelope } from '../composables/useTextWarpEnvelope';
import WordArtEnvelopeGlyph from './WordArtEnvelopeGlyph.vue';

/**
 * WordArtText - Vue port of the React `WarpedText` SVG renderer.
 *
 * Renders warped (WordArt) text. Every classified preset (`textNoShape` /
 * `textPlain` / unknown excluded) renders along an SVG `<textPath>` baseline
 * built by {@link shouldUseSvgWarp} + `buildWarpPath`: arch/wave/circle/
 * triangle/chevron/ring/curve, and (as of the WordArt envelope fidelity fix)
 * inflate/deflate/can/slant/fade/cascade too, matching React and Vanilla.
 *
 * This used to branch on `classifyTextWarp(preset)` and fall back to a flat
 * `<div>` + CSS `transform` approximation for the `envelope`/`simple`
 * categories; that branch was dead code once `shouldUseSvgWarp` is used
 * directly (it already returns `true` for every classified preset), and
 * because React/Vanilla never had that branch, Vue rendered inflate/deflate/
 * can/slant/fade/cascade as a flat CSS-transform approximation while React
 * and Vanilla already rendered them as true SVG textPath - a cross-binding
 * parity bug this component no longer has.
 *
 * Presets that are not classified (`textNoShape`, `textPlain`, unknown values)
 * cause the component to render nothing; callers fall back to flat text. The
 * overlay is absolutely positioned to fill the host box and is
 * `pointer-events: none` so it overlays without intercepting interaction.
 */
const props = defineProps<{
	element: PptxElement;
	zIndex: number;
}>();

// ── Inlined scalar defaults (kept self-contained; mirrors React constants) ──
// DEFAULT_FONT_FAMILY comes from pptx-viewer-shared so every binding's WordArt
// fallback font is the same string (see the shared `constants.ts` doc comment).
const DEFAULT_TEXT_COLOR = '#111827';
const DEFAULT_TEXT_FONT_SIZE = 24;
const HYPERLINK_COLOR = '#0563C1';

// Paragraph splitting now uses the shared pure helper
// (pptx-viewer-shared render/text-warp `groupIntoParagraphs`), shared with the
// React + Angular warp renderers.

const textEl = computed<PptxElementWithText | null>(() =>
	hasTextProperties(props.element) ? props.element : null,
);

const preset = computed(() => textEl.value?.textStyle?.textWarpPreset);

/**
 * Every classified preset renders along an SVG `<textPath>` baseline; only
 * `textNoShape` / `textPlain` / unknown presets fall through to flat text
 * (handled by the caller, not this component). Matches React and Vanilla.
 */
const usesTextPath = computed(() => Boolean(textEl.value) && shouldUseSvgWarp(preset.value));

const width = computed(() => Math.max(props.element.width, 1));
const height = computed(() => Math.max(props.element.height, 1));

/** OOXML field-substitution context (slide number, date/time, etc.), provided by the viewer root. */
const fieldContextSource = injectFieldContext();

const paragraphs = computed<WarpParagraph[]>(() => {
	const el = textEl.value;
	if (!el) {
		return [];
	}
	// Mirror React's warp-text-renderer: substitute field-run text via a
	// per-segment transform so warped WordArt resolves slide number / date /
	// footer fields identically to flat text.
	const ctx = resolveFieldContext(fieldContextSource);
	return groupIntoParagraphs(el, (seg) => {
		if (seg.fieldType) {
			const substituted = substituteFieldText(seg.text, seg.fieldType, ctx, seg.style?.language);
			if (substituted !== seg.text) {
				return { ...seg, text: substituted };
			}
		}
		return seg;
	});
});

const pathIdPrefix = computed(() => `warp-${props.element.id.replace(/[^a-zA-Z0-9_-]/gu, '_')}`);

const warpAdj = computed(() => textEl.value?.textStyle?.textWarpAdj);
const warpAdj2 = computed(() => textEl.value?.textStyle?.textWarpAdj2);

/** Map paragraph alignment to SVG textPath offset + anchor. */
const alignment = computed<{ startOffset: string; textAnchor: 'start' | 'middle' | 'end' }>(() => {
	switch (textEl.value?.textStyle?.align ?? 'center') {
		case 'center':
			return { startOffset: '50%', textAnchor: 'middle' };
		case 'right':
			return { startOffset: '100%', textAnchor: 'end' };
		default:
			return { startOffset: '0%', textAnchor: 'start' };
	}
});

const baseFontSize = computed(() => textEl.value?.textStyle?.fontSize ?? DEFAULT_TEXT_FONT_SIZE);
const baseFontFamily = computed(() =>
	textEl.value?.textStyle?.fontFamily
		? getSubstituteFontFamily(textEl.value.textStyle.fontFamily)
		: DEFAULT_FONT_FAMILY,
);
const baseFill = computed(() =>
	normalizeHexColor(textEl.value?.textStyle?.color, DEFAULT_TEXT_COLOR),
);
const baseFontWeight = computed(() => (textEl.value?.textStyle?.bold ? 700 : 400));
const baseFontStyle = computed(() => (textEl.value?.textStyle?.italic ? 'italic' : 'normal'));

interface TspanProps {
	fill: string;
	fontSize: number;
	fontWeight: number;
	fontStyle: 'italic' | 'normal';
	fontFamily: string;
	textDecoration?: string;
}

/** Resolve per-segment `<tspan>` attributes from a run's style. */
function tspanProps(segment: TextSegment): TspanProps {
	const s: TextStyle = segment.style ?? {};
	const decos: string[] = [];
	if (s.underline || s.hyperlink) {
		decos.push('underline');
	}
	if (s.strikethrough) {
		decos.push('line-through');
	}
	const elStyle = textEl.value?.textStyle;
	const fill = s.hyperlink
		? normalizeHexColor(s.color ?? elStyle?.color, HYPERLINK_COLOR)
		: normalizeHexColor(s.color ?? elStyle?.color, DEFAULT_TEXT_COLOR);
	const family = s.fontFamily ?? elStyle?.fontFamily;
	return {
		fill,
		fontSize: s.fontSize ?? elStyle?.fontSize ?? DEFAULT_TEXT_FONT_SIZE,
		fontWeight: s.bold ? 700 : 400,
		fontStyle: s.italic ? 'italic' : 'normal',
		fontFamily: family ? getSubstituteFontFamily(family) : DEFAULT_FONT_FAMILY,
		textDecoration: decos.length > 0 ? decos.join(' ') : undefined,
	};
}

/** Path `d` for the baseline of paragraph `i`. */
function pathFor(i: number): string {
	return buildWarpPath(
		preset.value as NonNullable<typeof preset.value>,
		width.value,
		height.value,
		i,
		paragraphs.value.length,
		warpAdj.value,
		warpAdj2.value,
	);
}

const { useGlyphEnvelope, glyphLines } = useTextWarpEnvelope({
	textEl,
	preset,
	paragraphs,
	width,
	height,
	warpAdj,
	warpAdj2,
	defaultFontFamily: DEFAULT_FONT_FAMILY,
	defaultFontSize: DEFAULT_TEXT_FONT_SIZE,
});

/** Per-glyph `<text>` style attributes, from the segment it belongs to. */
function glyphProps(glyph: EnvelopeGlyphPlacement, segments: TextSegment[]): TspanProps {
	return tspanProps(segments[glyph.segmentIndex]);
}

/**
 * Deterministic clip-id prefix for one glyph's slices, unique across every
 * WordArt element on the page: `element.id` + line + glyph index. Sanitised
 * the same way `pathIdPrefix` already is, since an SVG `id` cannot contain
 * arbitrary characters a PPTX shape id might.
 */
function glyphClipIdPrefix(lineIndex: number, glyphIndex: number): string {
	return `${pathIdPrefix.value}-l${lineIndex}-g${glyphIndex}`;
}
</script>

<template>
	<svg
		v-if="useGlyphEnvelope"
		class="pptx-vue-wordart"
		:width="width"
		:height="height"
		:viewBox="`0 0 ${width} ${height}`"
		xmlns="http://www.w3.org/2000/svg"
		aria-hidden="true"
		:style="{ zIndex }"
	>
		<template v-for="line in glyphLines" :key="`line-${line.lineIndex}`">
			<WordArtEnvelopeGlyph
				v-for="(g, gi) in line.glyphs"
				:key="`g-${line.lineIndex}-${gi}`"
				:glyph="g"
				:tspan="glyphProps(g, line.segments)"
				:clip-id-prefix="glyphClipIdPrefix(line.lineIndex, gi)"
			/>
		</template>
	</svg>
	<svg
		v-else-if="usesTextPath && paragraphs.length > 0"
		class="pptx-vue-wordart"
		:width="width"
		:height="height"
		:viewBox="`0 0 ${width} ${height}`"
		xmlns="http://www.w3.org/2000/svg"
		aria-hidden="true"
		:style="{ zIndex }"
	>
		<defs>
			<path
				v-for="(_para, i) in paragraphs"
				:id="`${pathIdPrefix}-${i}`"
				:key="`def-${i}`"
				:d="pathFor(i)"
				fill="none"
			/>
		</defs>
		<text
			v-for="(para, pi) in paragraphs"
			:key="`txt-${pi}`"
			:font-size="baseFontSize"
			:font-family="baseFontFamily"
			:fill="baseFill"
			:font-weight="baseFontWeight"
			:font-style="baseFontStyle"
		>
			<textPath
				:href="`#${pathIdPrefix}-${pi}`"
				:startOffset="alignment.startOffset"
				:text-anchor="alignment.textAnchor"
			>
				<tspan
					v-for="(seg, si) in para.segments"
					:key="`ts-${pi}-${si}`"
					:fill="tspanProps(seg).fill"
					:font-size="tspanProps(seg).fontSize"
					:font-weight="tspanProps(seg).fontWeight"
					:font-style="tspanProps(seg).fontStyle"
					:font-family="tspanProps(seg).fontFamily"
					:text-decoration="tspanProps(seg).textDecoration"
				>
					{{ seg.text }}
				</tspan>
			</textPath>
		</text>
	</svg>
</template>

<style scoped>
.pptx-vue-wordart {
	position: absolute;
	inset: 0;
	overflow: visible;
	pointer-events: none;
}
</style>

// viewers/pptx/packages/svelte/src/viewer/components/WordArtText.svelte
<script lang="ts">
	import type { TextSegment, TextStyle } from 'pptx-viewer-core';
	import { getSubstituteFontFamily, hasTextProperties } from 'pptx-viewer-core';
	import type { EnvelopeGlyphPlacement, EnvelopeSegmentInput } from 'ooxml-ui/pptx';
	import {
		buildGlyphEnvelopeBlock,
		buildWarpPath,
		DEFAULT_FONT_FAMILY,
		groupIntoParagraphs,
		hasGlyphEnvelope,
		normalizeHexColor,
		shouldUseSvgWarp,
		substituteFieldText,
	} from 'ooxml-ui/pptx';

	import { getFieldContextGetter } from '../state/field-context';
	import { getGlyphOutline, glyphOutlineFontsTick } from '../state/glyph-outline-cache.svelte';
	import { styleToString } from '../style';
	import type { ElementRendererProps } from './props';

	const { element, zIndex }: ElementRendererProps = $props();
	// Captured at init: `getContext` only resolves during component
	// initialisation, so the getter is invoked inside the `$derived` below.
	const getFieldContext = getFieldContextGetter();
	const textElement = $derived(hasTextProperties(element) ? element : undefined);
	const preset = $derived(textElement?.textStyle?.textWarpPreset);
	// Every classified preset renders along an SVG `<textPath>` baseline;
	// only `textNoShape` / `textPlain` / unknown presets render nothing here.
	// This used to additionally require `classifyTextWarp(preset) === 'path'`,
	// which routed inflate/deflate/can/slant/fade/cascade to a flat CSS
	// `transform` approximation instead - a cross-binding parity bug, since
	// React and Vanilla never had that extra gate and already rendered those
	// presets as true SVG textPath. See `WordArtText.vue` for the same fix.
	const usesPath = $derived(shouldUseSvgWarp(preset));
	// Warped WordArt bypasses `buildParagraphs`, so it substitutes field runs
	// itself via a per-segment transform; without this a slide-number field
	// inside WordArt would still render its authored "Slide #" placeholder.
	const paragraphs = $derived(
		textElement
			? groupIntoParagraphs(textElement, (segment) => {
					if (!segment.fieldType) {
						return segment;
					}
					const substituted = substituteFieldText(
						segment.text,
						segment.fieldType,
						getFieldContext?.(),
						segment.style?.language,
					);
					return substituted === segment.text ? segment : { ...segment, text: substituted };
				})
			: [],
	);
	const width = $derived(Math.max(element.width, 1));
	const height = $derived(Math.max(element.height, 1));
	const pathPrefix = $derived(`warp-${element.id.replace(/[^a-zA-Z0-9_-]/gu, '_')}`);
	const alignment = $derived.by(() => {
		switch (textElement?.textStyle?.align ?? 'center') {
			case 'center': return { offset: '50%', anchor: 'middle' as const };
			case 'right': return { offset: '100%', anchor: 'end' as const };
			default: return { offset: '0%', anchor: 'start' as const };
		}
	});

	function runStyle(segment: TextSegment): Record<string, string | number> {
		const style: TextStyle = segment.style ?? {};
		const inherited = textElement?.textStyle;
		const decorations = [style.underline || style.hyperlink ? 'underline' : '', style.strikethrough ? 'line-through' : ''].filter(Boolean);
		const family = style.fontFamily ?? inherited?.fontFamily;
		const result: Record<string, string | number> = {
			color: normalizeHexColor(style.color ?? inherited?.color, style.hyperlink ? '#0563C1' : '#111827'),
			fontSize: `${style.fontSize ?? inherited?.fontSize ?? 24}px`,
			fontWeight: style.bold || inherited?.bold ? 700 : 400,
			fontStyle: style.italic || inherited?.italic ? 'italic' : 'normal',
			fontFamily: family ? getSubstituteFontFamily(family) : DEFAULT_FONT_FAMILY,
		};
		if (decorations.length) {
			result.textDecoration = decorations.join(' ');
		}
		return result;
	}

	function pathFor(index: number): string {
		return buildWarpPath(preset!, width, height, index, paragraphs.length, textElement?.textStyle?.textWarpAdj, textElement?.textStyle?.textWarpAdj2);
	}

	// Envelope presets (inflate/deflate/can) are laid out as ONE block and
	// warped by a single PowerPoint-derived mapping (see
	// `buildGlyphEnvelopeBlock` in pptx-viewer-shared), so glyph HEIGHT varies
	// between the preset's top and bottom curves and a multi-paragraph block
	// bends within the same overall envelope with its rows kept in order.
	const useGlyphEnvelope = $derived(paragraphs.length > 0 && hasGlyphEnvelope(preset ?? ''));

	function segmentFont(segment: TextSegment): EnvelopeSegmentInput['font'] {
		const s: TextStyle = segment.style ?? {};
		const inherited = textElement?.textStyle;
		const family = s.fontFamily ?? inherited?.fontFamily;
		return {
			fontFamily: family ? getSubstituteFontFamily(family) : DEFAULT_FONT_FAMILY,
			fontSizePx: s.fontSize ?? inherited?.fontSize ?? 24,
			bold: s.bold ?? inherited?.bold,
			italic: s.italic ?? inherited?.italic,
		};
	}

	/** One glyph plus its already-resolved inline style string (avoids a stale
	 *  cross-paragraph `segmentIndex` lookup at render time), plus the plain
	 *  fill colour string for the outline-`<path>` branch (a `style` attribute
	 *  `color` does not paint an SVG `fill`). */
	type StyledGlyph = EnvelopeGlyphPlacement & { styleStr: string; fillColor: string };

	const glyphs = $derived.by<StyledGlyph[]>(() => {
		if (!useGlyphEnvelope) {
			return [];
		}
		// Read (never write) the tick so this recomputes once a catalogue
		// webfont's outline bytes land (see glyph-outline-cache.svelte.ts).
		void glyphOutlineFontsTick.value;
		const perLine = buildGlyphEnvelopeBlock(
			preset as string,
			paragraphs.map((paragraph) =>
				paragraph.segments.map((seg, i): EnvelopeSegmentInput => ({ text: seg.text, font: segmentFont(seg), segmentIndex: i })),
			),
			width,
			height,
			textElement?.textStyle?.align,
			textElement?.textStyle?.textWarpAdj,
			textElement?.textStyle?.textWarpAdj2,
			getGlyphOutline,
		);
		return paragraphs.flatMap((paragraph, lineIndex) => {
			const placements = perLine[lineIndex] ?? [];
			return placements.map((p) => {
				const s = runStyle(paragraph.segments[p.segmentIndex]);
				return { ...p, styleStr: styleToString(s), fillColor: String(s.color) };
			});
		});
	});
</script>

{#if useGlyphEnvelope}
	<svg class="pptx-svelte-wordart" {width} {height} viewBox={`0 0 ${width} ${height}`} aria-hidden="true" style={`z-index:${zIndex}`}>
		{#each glyphs as g, gi (gi)}
			{#if g.outlinePath}
				<!-- The glyph's real outline, already warped point-by-point (see
				     `buildWarpedGlyphOutlinePathD` in pptx-viewer-shared): exact,
				     so no affine fit or slicing is needed. -->
				<path d={g.outlinePath} fill={g.fillColor} />
			{:else if !g.slices || g.slices.length <= 1}
				<!-- Ordinary glyph (no slices needed): a bare <text>, unchanged
				     from before per-glyph slicing existed. -->
				<text x={g.x} y={g.y} transform={g.transform} style={g.styleStr}>{g.char}</text>
			{:else}
				<!-- A very wide glyph on a strongly-curved envelope: rendered as
				     `slices.length` clipped copies, each with its own affine (see
				     `fitGlyphEnvelopeAffine` in pptx-viewer-shared), so the pieces
				     tile across the glyph. Wrapped in a real <g> so it never
				     matches an "svg > text" selector the single-slice case does. -->
				<g data-glyph-slices={g.slices.length}>
					{#each g.slices as slice, si (si)}
						<clipPath id={`${pathPrefix}-g${gi}-s${si}`} clipPathUnits="userSpaceOnUse">
							<rect x={slice.clipX0} y={-100000} width={slice.clipX1 - slice.clipX0} height={200000} />
						</clipPath>
						<text x={g.x} y={g.y} transform={slice.transform} clip-path={`url(#${pathPrefix}-g${gi}-s${si})`} style={g.styleStr}>{g.char}</text>
					{/each}
				</g>
			{/if}
		{/each}
	</svg>
{:else if usesPath && paragraphs.length > 0}
	<svg class="pptx-svelte-wordart" {width} {height} viewBox={`0 0 ${width} ${height}`} aria-hidden="true" style={`z-index:${zIndex}`}>
		<defs>{#each paragraphs as _, i (i)}<path id={`${pathPrefix}-${i}`} d={pathFor(i)} fill="none" />{/each}</defs>
		{#each paragraphs as paragraph, pi (pi)}
			<text><textPath href={`#${pathPrefix}-${pi}`} startOffset={alignment.offset} text-anchor={alignment.anchor}>
				{#each paragraph.segments as segment, si (si)}<tspan style={styleToString(runStyle(segment))}>{segment.text}</tspan>{/each}
			</textPath></text>
		{/each}
	</svg>
{/if}

<style>
	.pptx-svelte-wordart { position: absolute; inset: 0; overflow: visible; pointer-events: none; }
</style>
