// viewers/pptx/packages/vue/src/viewer/components/ai/AiToolCallCard.vue
<script setup lang="ts">
/**
 * AiToolCallCard: a subtle, non-technical "activity" row describing one thing
 * the assistant did, e.g. "Looked at slide 5" / "Merged two tables", with a
 * friendly icon and a status (working / done / failed). The raw tool name +
 * arguments are hidden behind an optional, collapsed "Details" disclosure for
 * power users. Purely presentational.
 */
import {
	ChartColumn,
	Check,
	Eye,
	Film,
	LayoutTemplate,
	LoaderCircle,
	Move,
	Navigation,
	Palette,
	Search,
	Shapes,
	StickyNote,
	Table,
	Trash2,
	TriangleAlert,
	Type,
	Wrench,
} from 'lucide-vue-next';
import type { RenderableToolPart, ToolActivityIcon } from 'ooxml-ui/pptx/ai';
import { describeToolActivity, summarizeToolArgs, toolLabel } from 'ooxml-ui/pptx/ai';
import type { Component } from 'vue';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';

const props = defineProps<{ part: RenderableToolPart }>();
const { t } = useI18n();

/** Map a shared icon category to a concrete lucide glyph. */
const ICONS: Record<ToolActivityIcon, Component> = {
	view: Eye,
	text: Type,
	shape: Shapes,
	theme: Palette,
	table: Table,
	slide: LayoutTemplate,
	chart: ChartColumn,
	move: Move,
	delete: Trash2,
	search: Search,
	nav: Navigation,
	animation: Film,
	notes: StickyNote,
	tool: Wrench,
};

const failed = computed(() => props.part.state === 'output-error');
const done = computed(() => props.part.state === 'output-available');
const running = computed(() => !failed.value && !done.value);

const activity = computed(() =>
	describeToolActivity(props.part.toolName, props.part.input, running.value ? 'present' : 'past'),
);
const icon = computed<Component>(() => ICONS[activity.value.icon] ?? Wrench);
const rawSummary = computed(() => summarizeToolArgs(props.part.input));
const statusLabel = computed(() =>
	failed.value
		? t('pptx.ai.toolFailed')
		: done.value
			? t('pptx.ai.toolDone')
			: t('pptx.ai.toolRunning'),
);
</script>

<template>
	<div class="text-[12px]">
		<div class="flex items-center gap-1.5">
			<component
				:is="icon"
				:class="cn('w-3.5 h-3.5 shrink-0', failed ? 'text-destructive' : 'text-muted-foreground')"
			/>
			<span :class="cn('truncate', failed ? 'text-destructive' : 'text-foreground')">
				{{ activity.label }}
			</span>
			<span
				:class="
					cn(
						'ml-auto inline-flex items-center gap-1 rounded-sm px-1.5 py-0.5 text-[10px]',
						failed
							? 'bg-destructive/15 text-destructive'
							: done
								? 'bg-primary/10 text-primary'
								: 'bg-muted text-muted-foreground',
					)
				"
			>
				<LoaderCircle v-if="running" class="w-3 h-3 animate-spin" />
				<Check v-else-if="done" class="w-3 h-3" />
				<TriangleAlert v-else class="w-3 h-3" />
				{{ statusLabel }}
			</span>
		</div>
		<div v-if="failed && props.part.errorText" class="mt-1 pl-5 text-[11px] text-destructive">
			{{ props.part.errorText }}
		</div>
		<details v-if="rawSummary" class="group mt-0.5 pl-5">
			<summary
				class="cursor-pointer list-none text-[10px] text-muted-foreground/70 hover:text-muted-foreground"
			>
				{{ t('pptx.ai.toolDetails') }}
			</summary>
			<div class="mt-0.5 break-words font-mono text-[10px] text-muted-foreground/80">
				{{ toolLabel(props.part.toolName) }}: {{ rawSummary }}
			</div>
		</details>
	</div>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/ai/AiToolCallCard.svelte
<script lang="ts">
	/**
	 * AiToolCallCard: a subtle, non-technical "activity" row describing one thing
	 * the assistant did, e.g. "Looked at slide 5" / "Merged two tables", with a
	 * friendly icon and a status (Working / Done / Failed). The raw tool name +
	 * arguments are hidden behind an optional, collapsed "Details" disclosure for
	 * power users; no ids are shown by default. Purely presentational.
	 */
	import ChartColumn from '@lucide/svelte/icons/chart-column';
	import Check from '@lucide/svelte/icons/check';
	import Eye from '@lucide/svelte/icons/eye';
	import Film from '@lucide/svelte/icons/film';
	import LayoutTemplate from '@lucide/svelte/icons/layout-template';
	import LoaderCircle from '@lucide/svelte/icons/loader-circle';
	import Move from '@lucide/svelte/icons/move';
	import Navigation from '@lucide/svelte/icons/navigation';
	import Palette from '@lucide/svelte/icons/palette';
	import Search from '@lucide/svelte/icons/search';
	import Shapes from '@lucide/svelte/icons/shapes';
	import StickyNote from '@lucide/svelte/icons/sticky-note';
	import Table from '@lucide/svelte/icons/table';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import TriangleAlert from '@lucide/svelte/icons/triangle-alert';
	import Type from '@lucide/svelte/icons/type';
	import Wrench from '@lucide/svelte/icons/wrench';
	import { describeToolActivity, summarizeToolArgs, toolLabel } from 'ooxml-ui/pptx/ai';
	import type { RenderableToolPart, ToolActivityIcon } from 'ooxml-ui/pptx/ai';
	import type { Component } from 'svelte';

	import { useTranslator } from '../../../i18n/context';

	const { part }: { part: RenderableToolPart } = $props();

	const t = useTranslator();

	/** Map a shared icon category to a concrete lucide glyph. */
	const ICONS: Record<ToolActivityIcon, Component> = {
		view: Eye,
		text: Type,
		shape: Shapes,
		theme: Palette,
		table: Table,
		slide: LayoutTemplate,
		chart: ChartColumn,
		move: Move,
		delete: Trash2,
		search: Search,
		nav: Navigation,
		animation: Film,
		notes: StickyNote,
		tool: Wrench,
	};

	const failed = $derived(part.state === 'output-error');
	const done = $derived(part.state === 'output-available');
	const running = $derived(!failed && !done);
	const activity = $derived(describeToolActivity(part.toolName, part.input, running ? 'present' : 'past'));
	const Icon = $derived(ICONS[activity.icon] ?? Wrench);
	const rawSummary = $derived(summarizeToolArgs(part.input));
	const statusLabel = $derived(
		failed ? t('pptx.ai.toolFailed') : done ? t('pptx.ai.toolDone') : t('pptx.ai.toolRunning'),
	);
</script>

<div class="pptx-svelte-ai-tool">
	<div class="pptx-svelte-ai-tool-head">
		<Icon size={14} class={failed ? 'pptx-svelte-ai-tool-ic is-error' : 'pptx-svelte-ai-tool-ic'} aria-hidden="true" />
		<span class="pptx-svelte-ai-tool-label" class:is-error={failed}>{activity.label}</span>
		<span class="pptx-svelte-ai-tool-chip" class:is-error={failed} class:is-done={done}>
			{#if running}<LoaderCircle size={11} class="pptx-svelte-ai-spin" aria-hidden="true" />{/if}
			{#if done}<Check size={11} aria-hidden="true" />{/if}
			{#if failed}<TriangleAlert size={11} aria-hidden="true" />{/if}
			{statusLabel}
		</span>
	</div>
	{#if failed && part.errorText}
		<div class="pptx-svelte-ai-tool-error">{part.errorText}</div>
	{/if}
	{#if rawSummary}
		<details class="pptx-svelte-ai-tool-details">
			<summary>{t('pptx.ai.toolDetails')}</summary>
			<div class="pptx-svelte-ai-tool-raw">{toolLabel(part.toolName)}: {rawSummary}</div>
		</details>
	{/if}
</div>

<style>
	.pptx-svelte-ai-tool {
		font-size: 12px;
	}

	.pptx-svelte-ai-tool-head {
		display: flex;
		align-items: center;
		gap: 6px;
	}

	:global(.pptx-svelte-ai-tool-ic) {
		flex-shrink: 0;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	:global(.pptx-svelte-ai-tool-ic.is-error) {
		color: var(--pptx-destructive, #fca5a5);
	}

	.pptx-svelte-ai-tool-label {
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		color: var(--pptx-card-foreground, #e2e8f0);
	}

	.pptx-svelte-ai-tool-label.is-error {
		color: var(--pptx-destructive, #fca5a5);
	}

	.pptx-svelte-ai-tool-chip {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		margin-left: auto;
		padding: 1px 6px;
		border-radius: 3px;
		background: var(--pptx-muted, #2a2a3d);
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 10px;
	}

	.pptx-svelte-ai-tool-chip.is-done {
		background: color-mix(in srgb, var(--pptx-primary, #6366f1) 15%, transparent);
		color: var(--pptx-primary, #a5b4fc);
	}

	.pptx-svelte-ai-tool-chip.is-error {
		background: color-mix(in srgb, var(--pptx-destructive, #ef4444) 15%, transparent);
		color: var(--pptx-destructive, #fca5a5);
	}

	.pptx-svelte-ai-tool-error {
		margin-top: 4px;
		padding-left: 20px;
		font-size: 11px;
		color: var(--pptx-destructive, #fca5a5);
	}

	.pptx-svelte-ai-tool-details {
		margin-top: 2px;
		padding-left: 20px;
	}

	.pptx-svelte-ai-tool-details summary {
		cursor: pointer;
		list-style: none;
		font-size: 10px;
		color: color-mix(in srgb, var(--pptx-muted-foreground, #94a3b8) 70%, transparent);
	}

	.pptx-svelte-ai-tool-details summary:hover {
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-ai-tool-details summary::-webkit-details-marker {
		display: none;
	}

	.pptx-svelte-ai-tool-raw {
		margin-top: 2px;
		font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
		font-size: 10px;
		color: color-mix(in srgb, var(--pptx-muted-foreground, #94a3b8) 80%, transparent);
		word-break: break-word;
	}

	:global(.pptx-svelte-ai-spin) {
		animation: pptx-svelte-ai-spin 0.8s linear infinite;
	}

	@keyframes pptx-svelte-ai-spin {
		to {
			transform: rotate(360deg);
		}
	}
</style>
