// viewers/pptx/packages/react/src/viewer/components/inspector/ArtisticEffectsGallery.tsx
import type { PptxImageLikeElement } from 'pptx-viewer-core';
import { ARTISTIC_EFFECTS } from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { cn } from '../../utils';

// ---------------------------------------------------------------------------
// Artistic effect presets
// ---------------------------------------------------------------------------

export { ARTISTIC_EFFECTS };

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface ArtisticGalleryProps {
	imgSrc: string | undefined;
	fx: PptxImageLikeElement['imageEffects'];
	canEdit: boolean;
	updateEffects: (patch: Record<string, unknown>) => void;
}

// ---------------------------------------------------------------------------
// Gallery grid
// ---------------------------------------------------------------------------

export function ArtisticEffectsGallery({
	imgSrc,
	fx,
	canEdit,
	updateEffects,
}: ArtisticGalleryProps): React.ReactElement {
	const { t } = useTranslation();
	return (
		<div className='space-y-1 text-[11px]'>
			<span className='text-muted-foreground'>{t('pptx.image.artisticEffects')}</span>
			<div className='grid grid-cols-4 gap-1'>
				{ARTISTIC_EFFECTS.map(([effectName, tKey, cssFilter]) => {
					const isActive =
						effectName === 'none' ? !fx?.artisticEffect : fx?.artisticEffect === effectName;
					return (
						<button
							key={effectName}
							type='button'
							disabled={!canEdit}
							className={cn(
								'flex flex-col items-center gap-0.5 rounded border p-0.5 hover:bg-accent/50',
								isActive ? 'border-primary bg-primary/10' : 'border-border',
							)}
							title={t(tKey)}
							onClick={() =>
								updateEffects({
									artisticEffect: effectName === 'none' ? undefined : effectName,
									...(effectName === 'grayscale' ? { grayscale: undefined } : {}),
								})
							}
						>
							<div
								className='w-10 h-7 rounded overflow-hidden bg-muted'
								style={{
									backgroundImage: imgSrc ? `url(${imgSrc})` : undefined,
									backgroundSize: 'cover',
									backgroundPosition: 'center',
									filter: cssFilter || undefined,
								}}
							/>
							<span className='text-[8px] text-muted-foreground truncate w-full text-center'>
								{t(tKey)}
							</span>
						</button>
					);
				})}
			</div>
		</div>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/inspector/ArtisticEffectsGallery.vue
<script setup lang="ts">
import type { PptxElement, PptxImageEffects } from 'pptx-viewer-core';
import { ARTISTIC_EFFECTS } from 'ooxml-ui/pptx';
import { useI18n } from 'vue-i18n';

import { humanizeEffectLabel, mergeEffectsPatch } from '../../composables/useImageEditing';

/**
 * ArtisticEffectsGallery: a 4-column grid over the shared ARTISTIC_EFFECTS
 * catalogue. Each cell previews the effect as a live CSS filter over the image
 * and, on click, sets `imageEffects.artisticEffect` (or clears it for "none").
 * Emits the FULL merged `imageEffects` sub-object like every other sub-panel.
 */
const props = defineProps<{
	imgSrc: string | undefined;
	fx: PptxImageEffects | undefined;
}>();

const emit = defineEmits<{
	update: [patch: Partial<PptxElement>];
}>();

const { t } = useI18n();

const effects = ARTISTIC_EFFECTS;

function isActive(effectName: string): boolean {
	return effectName === 'none'
		? !props.fx?.artisticEffect
		: props.fx?.artisticEffect === effectName;
}

function thumbStyle(cssFilter: string): Record<string, string> {
	const style: Record<string, string> = {
		backgroundSize: 'cover',
		backgroundPosition: 'center',
	};
	if (props.imgSrc) {
		style.backgroundImage = `url(${props.imgSrc})`;
	}
	if (cssFilter) {
		style.filter = cssFilter;
	}
	return style;
}

function onPick(effectName: string): void {
	const patch: Partial<PptxImageEffects> = {
		artisticEffect: effectName === 'none' ? undefined : effectName,
	};
	if (effectName === 'grayscale') {
		patch.grayscale = undefined;
	}
	emit('update', mergeEffectsPatch(props.fx, patch));
}
</script>

<template>
	<div class="pptx-vue-artistic flex flex-col gap-1 text-[11px]">
		<span class="text-muted-foreground">{{ t('pptx.image.artisticEffects') }}</span>
		<div class="pptx-vue-artistic__grid grid grid-cols-4 gap-1">
			<button
				v-for="[effectName, tKey, cssFilter] in effects"
				:key="effectName"
				type="button"
				class="pptx-vue-artistic__cell flex flex-col items-center gap-0.5 rounded border p-0.5 hover:bg-accent/50 transition-colors"
				:class="isActive(effectName) ? 'border-primary bg-primary/10' : 'border-border'"
				:title="humanizeEffectLabel(tKey)"
				@click="onPick(effectName)"
			>
				<div class="w-10 h-7 rounded overflow-hidden bg-muted" :style="thumbStyle(cssFilter)" />
				<span class="text-[8px] text-muted-foreground truncate w-full text-center">
					{{ humanizeEffectLabel(effectName) }}
				</span>
			</button>
		</div>
	</div>
</template>
