// viewers/pptx/packages/angular/src/viewer/chart-axis-options.component.ts
/**
 * chart-axis-options.component.ts: Per-axis scale + label formatting controls.
 *
 * Selector: `pptx-chart-axis-options`
 *
 * Mirrors React's `ChartAxisOptions.tsx`: for each axis present on the chart it
 * exposes min/max/major-unit/minor-unit (scaled axes only), display units, axis
 * title text, number format, tick-label position, and major/minor gridline
 * visibility. Edits route through the headless `setChartAxis` core op (via the
 * `setAxis` immutable wrapper) and emit a new `ChartPptxElement`.
 *
 * @module angular-viewer/chart-axis-options
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	input,
	output,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type {
	ChartAxisEdit,
	ChartPptxElement,
	PptxChartAxisFormatting,
	PptxChartAxisType,
} from 'pptx-viewer-core';

import type { ChartTickLabelPosition } from 'ooxml-ui/pptx';
import { DISPLAY_UNITS_OPTIONS, TICK_LABEL_POSITION_OPTIONS } from 'ooxml-ui/pptx';
import { setAxis } from './chart-advanced-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { boolFromEvent, numFromEvent, selectValue, stringFromEvent } from './chart-event-helpers';

/** Axis kinds the inspector exposes, with their label key and whether they scale. */
interface AxisRow {
	type: PptxChartAxisType;
	labelKey: string;
	hasScale: boolean;
	axis: PptxChartAxisFormatting;
}

const AXIS_DEFS: ReadonlyArray<{ type: PptxChartAxisType; labelKey: string; hasScale: boolean }> = [
	{ type: 'valAx', labelKey: 'pptx.chart.valueAxis', hasScale: true },
	{ type: 'dateAx', labelKey: 'pptx.chart.dateAxis', hasScale: true },
	{ type: 'catAx', labelKey: 'pptx.chart.categoryAxis', hasScale: false },
];

/** Numeric scale fields, paired with their label key, rendered for scaled axes. */
const SCALE_FIELDS: ReadonlyArray<{
	key: 'min' | 'max' | 'majorUnit' | 'minorUnit';
	labelKey: string;
}> = [
	{ key: 'min', labelKey: 'pptx.chart.min' },
	{ key: 'max', labelKey: 'pptx.chart.max' },
	{ key: 'majorUnit', labelKey: 'pptx.chart.majorUnit' },
	{ key: 'minorUnit', labelKey: 'pptx.chart.minorUnit' },
];

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-chart-axis-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (rows().length > 0) {
			<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.axes' | translate">
				<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.axes' | translate }}</h4>
				@for (row of rows(); track row.type) {
					<div class="pptx-chart-card__group">
						<div class="pptx-chart-card__subhead">{{ row.labelKey | translate }}</div>
						<div class="pptx-chart-card__group pptx-chart-card__group--indent">
							@if (row.hasScale) {
								@for (field of scaleFields; track field.key) {
									<label class="pptx-chart-card__row">
										<span class="pptx-chart-card__label">{{ field.labelKey | translate }}</span>
										<input
											type="number"
											class="pptx-chart-card__input"
											[placeholder]="'pptx.chart.auto' | translate"
											[disabled]="!canEdit()"
											[value]="numValue(row.axis, field.key)"
											(change)="onScaleField(row.type, field.key, $event)"
										/>
									</label>
								}
								<label class="pptx-chart-card__row">
									<span class="pptx-chart-card__label">{{
										'pptx.chart.displayUnits' | translate
									}}</span>
									<pptx-ui-select
										[attr.aria-label]="'pptx.chart.displayUnits' | translate"
										class="pptx-chart-card__input"
										[disabled]="!canEdit()"
										[value]="row.axis.displayUnits ?? ''"
										(change)="onDisplayUnits(row.type, $event)"
									>
										@for (opt of displayUnitOptions; track opt.value) {
											<option
												[value]="opt.value"
												[selected]="opt.value === (row.axis.displayUnits ?? '')"
											>
												{{ opt.labelKey | translate }}
											</option>
										}
									</pptx-ui-select>
								</label>
							}

							<label class="pptx-chart-card__row">
								<span class="pptx-chart-card__label">{{ 'pptx.chart.axisTitle' | translate }}</span>
								<input
									type="text"
									class="pptx-chart-card__input"
									[placeholder]="'pptx.chart.axisTitlePlaceholder' | translate"
									[disabled]="!canEdit()"
									[value]="row.axis.titleText ?? ''"
									(change)="onTitleText(row.type, $event)"
								/>
							</label>

							<label class="pptx-chart-card__row">
								<span class="pptx-chart-card__label">{{
									'pptx.chart.numberFormat' | translate
								}}</span>
								<input
									type="text"
									class="pptx-chart-card__input"
									placeholder="General"
									[disabled]="!canEdit()"
									[value]="row.axis.numFmt?.formatCode ?? ''"
									(change)="onNumberFormat(row.type, $event)"
								/>
							</label>

							<label class="pptx-chart-card__row">
								<span class="pptx-chart-card__label">{{
									'pptx.chart.tickLabels' | translate
								}}</span>
								<pptx-ui-select
									[attr.aria-label]="'pptx.chart.tickLabels' | translate"
									class="pptx-chart-card__input"
									[disabled]="!canEdit()"
									[value]="row.axis.tickLblPos ?? 'nextTo'"
									(change)="onTickPosition(row.type, $event)"
								>
									@for (opt of tickPositionOptions; track opt.value) {
										<option
											[value]="opt.value"
											[selected]="opt.value === (row.axis.tickLblPos ?? 'nextTo')"
										>
											{{ opt.labelKey | translate }}
										</option>
									}
								</pptx-ui-select>
							</label>

							<label class="pptx-chart-card__check">
								<pptx-ui-checkbox
									[disabled]="!canEdit()"
									[checked]="row.axis.majorGridlines ?? false"
									(change)="onGridlines(row.type, 'major', $event)"
								></pptx-ui-checkbox>
								<span>{{ 'pptx.chart.majorGridlines' | translate }}</span>
							</label>
							<label class="pptx-chart-card__check">
								<pptx-ui-checkbox
									[disabled]="!canEdit()"
									[checked]="row.axis.minorGridlines ?? false"
									(change)="onGridlines(row.type, 'minor', $event)"
								></pptx-ui-checkbox>
								<span>{{ 'pptx.chart.minorGridlines' | translate }}</span>
							</label>
						</div>
					</div>
				}
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartAxisOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly scaleFields = SCALE_FIELDS;
	protected readonly displayUnitOptions = DISPLAY_UNITS_OPTIONS;
	protected readonly tickPositionOptions = TICK_LABEL_POSITION_OPTIONS;

	/** Only the axes that actually exist on the chart (pie charts have none). */
	protected readonly rows = computed<AxisRow[]>(() => {
		const axes = this.element().chartData?.axes ?? [];
		const result: AxisRow[] = [];
		for (const def of AXIS_DEFS) {
			const axis = axes.find((a) => a.axisType === def.type);
			if (axis) {
				result.push({ ...def, axis });
			}
		}
		return result;
	});

	protected numValue(
		axis: PptxChartAxisFormatting,
		key: 'min' | 'max' | 'majorUnit' | 'minorUnit',
	): string {
		const value = axis[key];
		return value === undefined ? '' : String(value);
	}

	protected onScaleField(
		axisType: PptxChartAxisType,
		key: 'min' | 'max' | 'majorUnit' | 'minorUnit',
		event: Event,
	): void {
		const num = numFromEvent(event);
		if (num === undefined) {
			return;
		}
		this.emit(axisType, { [key]: num });
	}

	protected onDisplayUnits(axisType: PptxChartAxisType, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, {
			displayUnits: (value || null) as ChartAxisEdit['displayUnits'],
		});
	}

	protected onTitleText(axisType: PptxChartAxisType, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, { title: value });
	}

	protected onNumberFormat(axisType: PptxChartAxisType, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, { numberFormat: value });
	}

	protected onTickPosition(axisType: PptxChartAxisType, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.emit(axisType, { tickLabelPosition: value as ChartTickLabelPosition });
	}

	protected onGridlines(axisType: PptxChartAxisType, which: 'major' | 'minor', event: Event): void {
		const checked = boolFromEvent(event);
		this.emit(
			axisType,
			which === 'major' ? { majorGridlines: checked } : { minorGridlines: checked },
		);
	}

	private emit(axisType: PptxChartAxisType, edit: ChartAxisEdit): void {
		this.elementChange.emit(setAxis(this.element(), axisType, edit));
	}
}

// viewers/pptx/packages/vue/src/viewer/components/inspector/ChartAxisOptions.vue
<script setup lang="ts">
import type { PptxChartAxisFormatting } from 'pptx-viewer-core';
import {
	DISPLAY_UNITS_OPTIONS,
	EDITABLE_AXIS_ROWS,
	TICK_LABEL_POSITION_OPTIONS,
} from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartAxisOptions: per-axis scale (min/max/major/minor), display units, axis
 * title text, number format, tick-label position, and major/minor gridline
 * visibility. Mirrors React's `ChartAxisOptions`. Emits `updateAxis(type,patch)`.
 */
const props = defineProps<{
	axes: readonly PptxChartAxisFormatting[] | undefined;
}>();

const emit = defineEmits<{
	updateAxis: [
		axisType: PptxChartAxisFormatting['axisType'],
		patch: Partial<PptxChartAxisFormatting>,
	];
}>();

const { t } = useI18n();

type AxisRow = (typeof EDITABLE_AXIS_ROWS)[number] & { axis: PptxChartAxisFormatting };

const rows = computed<AxisRow[]>(() =>
	EDITABLE_AXIS_ROWS.map((row) => ({
		...row,
		axis: props.axes?.find((a) => a.axisType === row.type),
	})).filter((row): row is AxisRow => Boolean(row.axis)),
);

type ScaleKey = 'min' | 'max' | 'majorUnit' | 'minorUnit';

function onNumber(
	event: Event,
	axisType: PptxChartAxisFormatting['axisType'],
	key: ScaleKey,
): void {
	const raw = (event.target as HTMLInputElement).value;
	if (raw === '') {
		emit('updateAxis', axisType, { [key]: undefined });
		return;
	}
	const num = Number.parseFloat(raw);
	if (Number.isFinite(num)) {
		emit('updateAxis', axisType, { [key]: num });
	}
}

function onDisplayUnits(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	const value = (event.target as HTMLSelectElement).value;
	emit('updateAxis', axisType, {
		displayUnits: (value || undefined) as PptxChartAxisFormatting['displayUnits'],
	});
}

function onTitle(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	emit('updateAxis', axisType, { titleText: (event.target as HTMLInputElement).value });
}

function onNumberFormat(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	const value = (event.target as HTMLInputElement).value;
	emit('updateAxis', axisType, {
		numFmt: value ? { formatCode: value, sourceLinked: false } : undefined,
	});
}

function onTickPos(event: Event, axisType: PptxChartAxisFormatting['axisType']): void {
	emit('updateAxis', axisType, {
		tickLblPos: (event.target as HTMLSelectElement).value as PptxChartAxisFormatting['tickLblPos'],
	});
}

function onGridline(
	event: Event,
	axisType: PptxChartAxisFormatting['axisType'],
	key: 'majorGridlines' | 'minorGridlines',
): void {
	emit('updateAxis', axisType, { [key]: (event.target as HTMLInputElement).checked });
}

const SCALE_FIELDS: ReadonlyArray<{ key: ScaleKey; labelKey: string }> = [
	{ key: 'min', labelKey: 'pptx.chart.min' },
	{ key: 'max', labelKey: 'pptx.chart.max' },
	{ key: 'majorUnit', labelKey: 'pptx.chart.majorUnit' },
	{ key: 'minorUnit', labelKey: 'pptx.chart.minorUnit' },
];

const INPUT = 'flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full';
</script>

<template>
	<div
		v-if="rows.length > 0"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.axes') }}
		</div>
		<div v-for="row in rows" :key="row.type" class="space-y-1.5">
			<div class="text-[11px] font-medium">{{ t(row.labelKey) }}</div>

			<div v-if="row.hasScale" class="space-y-1.5 ml-2">
				<label
					v-for="field in SCALE_FIELDS"
					:key="field.key"
					class="flex items-center gap-2 text-[11px]"
				>
					<span class="w-16 text-muted-foreground shrink-0">{{ t(field.labelKey) }}</span>
					<input
						type="number"
						:class="INPUT"
						data-testid="chart-axis-scale"
						:value="row.axis[field.key] ?? ''"
						:placeholder="t('pptx.chart.auto')"
						@input="onNumber($event, row.type, field.key)"
					/>
				</label>

				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{
						t('pptx.chart.displayUnits')
					}}</span>
					<pptx-ui-select
						:aria-label="t('pptx.chart.displayUnits')"
						:class="INPUT"
						data-testid="chart-axis-display-units"
						:value="row.axis.displayUnits ?? ''"
						@change="onDisplayUnits($event, row.type)"
					>
						<option v-for="opt in DISPLAY_UNITS_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</pptx-ui-select>
				</label>
			</div>

			<div class="space-y-1.5 ml-2">
				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{ t('pptx.chart.axisTitle') }}</span>
					<input
						type="text"
						:class="INPUT"
						data-testid="chart-axis-title"
						:value="row.axis.titleText ?? ''"
						:placeholder="t('pptx.chart.axisTitlePlaceholder')"
						@input="onTitle($event, row.type)"
					/>
				</label>

				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{
						t('pptx.chart.numberFormat')
					}}</span>
					<input
						type="text"
						:class="INPUT"
						data-testid="chart-axis-number-format"
						:value="row.axis.numFmt?.formatCode ?? ''"
						:placeholder="t('pptx.chart.numberFormatPlaceholder')"
						@input="onNumberFormat($event, row.type)"
					/>
				</label>

				<label class="flex items-center gap-2 text-[11px]">
					<span class="w-16 text-muted-foreground shrink-0">{{ t('pptx.chart.tickLabels') }}</span>
					<pptx-ui-select
						:aria-label="t('pptx.chart.tickLabels')"
						:class="INPUT"
						data-testid="chart-axis-tick-pos"
						:value="row.axis.tickLblPos ?? 'nextTo'"
						@change="onTickPos($event, row.type)"
					>
						<option v-for="opt in TICK_LABEL_POSITION_OPTIONS" :key="opt.value" :value="opt.value">
							{{ t(opt.labelKey) }}
						</option>
					</pptx-ui-select>
				</label>

				<label class="flex items-center gap-2 cursor-pointer">
					<pptx-ui-checkbox
						data-testid="chart-axis-major-gridlines"
						:checked="row.axis.majorGridlines ?? false"
						@change="onGridline($event, row.type, 'majorGridlines')"
					/>
					<span class="text-[11px]">{{ t('pptx.chart.majorGridlines') }}</span>
				</label>
				<label class="flex items-center gap-2 cursor-pointer">
					<pptx-ui-checkbox
						data-testid="chart-axis-minor-gridlines"
						:checked="row.axis.minorGridlines ?? false"
						@change="onGridline($event, row.type, 'minorGridlines')"
					/>
					<span class="text-[11px]">{{ t('pptx.chart.minorGridlines') }}</span>
				</label>
			</div>
		</div>
	</div>
</template>
