// viewers/pptx/packages/react/src/viewer/components/inspector/SlideTransitionSection.tsx
/**
 * SlideTransitionSection: the SLIDE TRANSITION card of the no-selection
 * inspector, rendered by `PresentationPropertiesPanel` immediately after SLIDE
 * SIZE so React sits where Angular, Svelte and Vanilla already put it.
 *
 * WHY the conditional controls: OOXML overloads a transition's `dir`
 * attribute. Most types take a compass token, the blinds/checker/comb/randomBar
 * family takes `horz`/`vert`, and `wheel` takes a spoke count instead.
 * `TRANSITION_VALID_DIRECTIONS` (core) and `TRANSITION_ORIENTATION_TYPES`
 * (shared) decide which control applies, so the card never offers a direction
 * PowerPoint would drop on save.
 *
 * WHY the shared clamp: `clampTransitionNumber` rounds every binding's typed
 * duration / spoke count the same way, so the same gesture in React and in
 * Angular stores the same number.
 */
import type { PptxSlideTransition, PptxTransitionType } from 'pptx-viewer-core';
import {
	TRANSITION_PATTERN_OPTIONS,
	TRANSITION_THRUBLK_TYPES,
	TRANSITION_VALID_DIRECTIONS,
} from 'pptx-viewer-core';
import {
	clampTransitionNumber,
	TRANSITION_MORPH_OPTIONS,
	TRANSITION_ORIENTATION_TYPES,
	TRANSITION_SPEED_OPTIONS,
} from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { SLIDE_TRANSITION_OPTIONS } from '../../constants';
import { WebSelect, WebCheckbox } from '../WebControls';
import { DirectionPicker } from './DirectionPicker';
import { TransitionPreview } from './TransitionPreview';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface SlideTransitionSectionProps {
	activeSlide: { transition?: PptxSlideTransition } | null;
	/** Disables every control when the viewer is not in an editable mode. */
	canEdit?: boolean;
	onTransitionChange: (updates: Partial<PptxSlideTransition>) => void;
}

/** Default duration (ms) shown when the slide declares no transition timing. */
const DEFAULT_DURATION_MS = 320;
const MAX_DURATION_MS = 10000;
const MIN_SPOKES = 1;
const MAX_SPOKES = 8;

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function SlideTransitionSection({
	activeSlide,
	canEdit = true,
	onTransitionChange,
}: SlideTransitionSectionProps): React.ReactElement | null {
	const { t } = useTranslation();

	if (!activeSlide) {
		return null;
	}

	const transitionType: PptxTransitionType = activeSlide.transition?.type ?? 'none';
	const validDirections = TRANSITION_VALID_DIRECTIONS[transitionType];
	const hasDirections = validDirections !== undefined && validDirections.length > 0;
	const usesOrientation = TRANSITION_ORIENTATION_TYPES.has(transitionType);
	const isWheel = transitionType === 'wheel';
	const isMorph = transitionType === 'morph';
	const patternOptions = TRANSITION_PATTERN_OPTIONS[transitionType];
	const hasThruBlk = TRANSITION_THRUBLK_TYPES.has(transitionType);

	return (
		<div
			className='mb-3 rounded border border-border bg-card p-2 space-y-2'
			data-pptx-slide-transition
		>
			<div className='text-[11px] uppercase tracking-wide text-muted-foreground'>
				{t('pptx.slideInspector.slideTransition')}
			</div>

			{/* Type */}
			<label className='flex flex-col gap-1'>
				<span className='text-muted-foreground text-xs'>{t('pptx.transition.type')}</span>
				<WebSelect
					value={activeSlide.transition?.type || 'none'}
					disabled={!canEdit}
					aria-label={t('pptx.transition.type')}
					onChange={(e) =>
						onTransitionChange({
							type: e.target.value as NonNullable<PptxSlideTransition['type']>,
						})
					}
					className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
				>
					{SLIDE_TRANSITION_OPTIONS.map((option) => (
						<option key={option.value} value={option.value}>
							{t(option.i18nKey)}
						</option>
					))}
				</WebSelect>
			</label>

			{/* Direction picker */}
			{hasDirections && !usesOrientation && (
				<div className='space-y-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.direction')}</span>
					<DirectionPicker
						directions={validDirections}
						value={activeSlide.transition?.direction}
						disabled={!canEdit}
						onChange={(dir) => onTransitionChange({ direction: dir })}
					/>
				</div>
			)}

			{/* Orientation picker */}
			{usesOrientation && (
				<div className='space-y-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.orientation')}</span>
					<div className='flex gap-1'>
						{(['horz', 'vert'] as const).map((o) => (
							<button
								key={o}
								type='button'
								disabled={!canEdit}
								onClick={() => onTransitionChange({ orient: o })}
								className={`px-2 py-1 rounded text-xs border ${
									(activeSlide.transition?.orient ?? 'horz') === o
										? 'bg-primary text-white border-primary'
										: 'bg-muted border-border hover:bg-accent'
								}`}
							>
								{t(
									o === 'horz' ? 'pptx.slideInspector.horizontal' : 'pptx.slideInspector.vertical',
								)}
							</button>
						))}
					</div>
				</div>
			)}

			{/* Pattern (glitter's diamond/hexagon, shred's strip/rectangle) */}
			{patternOptions && (
				<div className='space-y-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.pattern')}</span>
					<div className='flex gap-1'>
						{patternOptions.map((pattern) => (
							<button
								key={pattern}
								type='button'
								disabled={!canEdit}
								onClick={() => onTransitionChange({ pattern })}
								className={`px-2 py-1 rounded text-xs border ${
									(activeSlide.transition?.pattern ?? patternOptions[0]) === pattern
										? 'bg-primary text-white border-primary'
										: 'bg-muted border-border hover:bg-accent'
								}`}
							>
								{t(`pptx.transition.pattern.${pattern}`)}
							</button>
						))}
					</div>
				</div>
			)}

			{/* Through Black */}
			{hasThruBlk && (
				<label className='inline-flex items-center gap-2 text-foreground text-xs'>
					<WebCheckbox
						disabled={!canEdit}
						checked={activeSlide.transition?.thruBlk === true}
						onChange={(e) => onTransitionChange({ thruBlk: e.target.checked })}
					/>
					{t('pptx.transition.thruBlk')}
				</label>
			)}

			{/* Spokes for wheel */}
			{isWheel && (
				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.spokes')}</span>
					<input
						type='number'
						min={MIN_SPOKES}
						max={MAX_SPOKES}
						disabled={!canEdit}
						value={activeSlide.transition?.spokes ?? 4}
						onChange={(e) => {
							const spokes = clampTransitionNumber(Number(e.target.value), MIN_SPOKES, MAX_SPOKES);
							if (spokes !== null) {
								onTransitionChange({ spokes });
							}
						}}
						className='bg-muted border border-border rounded px-2 py-1 text-xs w-16'
					/>
				</label>
			)}

			{/* Duration */}
			<label className='flex flex-col gap-1'>
				<span className='text-muted-foreground text-xs'>{t('pptx.transition.duration')}</span>
				<input
					type='number'
					min={0}
					max={MAX_DURATION_MS}
					disabled={!canEdit}
					aria-label={t('pptx.transition.duration')}
					value={Math.round(activeSlide.transition?.durationMs || DEFAULT_DURATION_MS)}
					onChange={(e) => {
						const durationMs = clampTransitionNumber(Number(e.target.value), 0, MAX_DURATION_MS);
						if (durationMs !== null) {
							onTransitionChange({ durationMs });
						}
					}}
					className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
				/>
			</label>

			{/* Speed */}
			<label className='flex flex-col gap-1'>
				<span className='text-muted-foreground text-xs'>{t('pptx.transition.speed')}</span>
				<WebSelect
					value={activeSlide.transition?.speed ?? 'fast'}
					disabled={!canEdit}
					aria-label={t('pptx.transition.speed')}
					onChange={(e) =>
						onTransitionChange({
							speed: e.target.value as NonNullable<PptxSlideTransition['speed']>,
						})
					}
					className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
				>
					{TRANSITION_SPEED_OPTIONS.map((option) => (
						<option key={option.value} value={option.value}>
							{t(option.i18nKey)}
						</option>
					))}
				</WebSelect>
			</label>

			{/* Morph granularity */}
			{isMorph && (
				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.morphOption')}</span>
					<WebSelect
						value={activeSlide.transition?.morphOption ?? 'byObject'}
						disabled={!canEdit}
						aria-label={t('pptx.transition.morphOption')}
						onChange={(e) =>
							onTransitionChange({
								morphOption: e.target.value as NonNullable<PptxSlideTransition['morphOption']>,
							})
						}
						className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
					>
						{TRANSITION_MORPH_OPTIONS.map((option) => (
							<option key={option.value} value={option.value}>
								{t(option.i18nKey)}
							</option>
						))}
					</WebSelect>
				</label>
			)}

			{/* Advance on click */}
			<label className='inline-flex items-center gap-2 text-foreground text-xs'>
				<WebCheckbox
					disabled={!canEdit}
					checked={activeSlide.transition?.advanceOnClick !== false}
					onChange={(e) => onTransitionChange({ advanceOnClick: e.target.checked })}
				/>
				{t('pptx.transition.advanceOnClick')}
			</label>

			{/* Sound */}
			{activeSlide.transition?.soundFileName && (
				<div className='flex items-center gap-1 text-xs text-muted-foreground'>
					<span className='text-muted-foreground'>{t('pptx.transition.sound')}:</span>
					<span className='text-foreground truncate' title={activeSlide.transition.soundFileName}>
						{activeSlide.transition.soundFileName}
					</span>
				</div>
			)}

			{/* Preview */}
			{activeSlide.transition && <TransitionPreview transition={activeSlide.transition} />}
		</div>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/inspector/SlideTransitionSection.vue
<script setup lang="ts">
/**
 * SlideTransitionSection: slide transition editing (type / duration / direction
 * / orientation / spokes / advance-on-click), extracted from the old untabbed
 * `SlideInspector`. Mirrors React's `inspector/SlideTransitionSection.tsx`,
 * which `PresentationPropertiesPanel` renders beside SLIDE SIZE; this one is
 * mounted from the Vue panel in the same slot.
 */
import type { PptxSlide, PptxSlideTransition, PptxTransitionType } from 'pptx-viewer-core';
import {
	TRANSITION_PATTERN_OPTIONS,
	TRANSITION_THRUBLK_TYPES,
	TRANSITION_VALID_DIRECTIONS,
} from 'pptx-viewer-core';
import { TRANSITION_MORPH_OPTIONS, TRANSITION_ORIENTATION_TYPES } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import SlideTransitionPanel from '../SlideTransitionPanel.vue';
import DirectionPicker from './DirectionPicker.vue';
import TransitionPreview from './TransitionPreview.vue';

const props = defineProps<{ slide: PptxSlide | undefined }>();

const emit = defineEmits<{
	'transition-update': [transition: PptxSlideTransition | undefined];
}>();

const { t } = useI18n();

/** A real (non-"none") transition is set on this slide. */
const hasTransition = computed(
	() => Boolean(props.slide?.transition) && props.slide?.transition?.type !== 'none',
);
/** PowerPoint default is advance-on-click unless explicitly disabled. */
const advanceOnClick = computed(() => props.slide?.transition?.advanceOnClick !== false);

const transitionType = computed<PptxTransitionType>(
	() => (props.slide?.transition?.type as PptxTransitionType) ?? 'none',
);
const validDirections = computed<readonly string[]>(
	() => TRANSITION_VALID_DIRECTIONS[transitionType.value] ?? [],
);
const usesOrientation = computed(() => TRANSITION_ORIENTATION_TYPES.has(transitionType.value));
const showDirection = computed(
	() => hasTransition.value && validDirections.value.length > 0 && !usesOrientation.value,
);
const isWheel = computed(() => transitionType.value === 'wheel');
const isMorph = computed(() => transitionType.value === 'morph');
const orient = computed(() => props.slide?.transition?.orient ?? 'horz');
const spokes = computed(() => props.slide?.transition?.spokes ?? 4);
const morphOption = computed(() => props.slide?.transition?.morphOption ?? 'byObject');
const patternOptions = computed<readonly string[] | undefined>(
	() => TRANSITION_PATTERN_OPTIONS[transitionType.value],
);
const hasThruBlk = computed(() => TRANSITION_THRUBLK_TYPES.has(transitionType.value));

function onThruBlkChange(e: Event): void {
	patchTransition({ thruBlk: (e.target as HTMLInputElement).checked });
}

function onMorphOptionChange(e: Event): void {
	patchTransition({
		morphOption: (e.target as HTMLSelectElement).value as PptxSlideTransition['morphOption'],
	});
}

/** Merge a partial transition patch into the current transition and commit. */
function patchTransition(updates: Partial<PptxSlideTransition>): void {
	const current = props.slide?.transition;
	if (!current) {
		return;
	}
	emit('transition-update', { ...current, ...updates });
}

function onSpokesInput(e: Event): void {
	const value = Number((e.target as HTMLInputElement).value);
	if (!Number.isFinite(value)) {
		return;
	}
	patchTransition({ spokes: Math.max(1, Math.min(8, Math.round(value))) });
}

function onAdvanceChange(e: Event): void {
	patchTransition({ advanceOnClick: (e.target as HTMLInputElement).checked });
}
</script>

<template>
	<div>
		<h3
			class="pptx-vue-inspector-title mb-2 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground"
		>
			{{ t('pptx.slideInspector.slideTransition') }}
		</h3>
		<SlideTransitionPanel :slide="slide" @update="(next) => emit('transition-update', next)" />

		<div v-if="showDirection" class="mt-2 space-y-1 px-2.5">
			<span class="text-xs text-muted-foreground">{{ t('pptx.transition.direction') }}</span>
			<DirectionPicker
				:directions="validDirections"
				:value="slide?.transition?.direction"
				@change="(dir) => patchTransition({ direction: dir })"
			/>
		</div>

		<div v-if="hasTransition && usesOrientation" class="mt-2 space-y-1 px-2.5">
			<span class="text-xs text-muted-foreground">{{ t('pptx.transition.orientation') }}</span>
			<div class="flex gap-1">
				<button
					v-for="o in ['horz', 'vert'] as const"
					:key="o"
					type="button"
					class="rounded border px-2 py-1 text-xs"
					:class="
						orient === o
							? 'border-primary bg-primary text-white'
							: 'border-border bg-muted hover:bg-accent'
					"
					:aria-pressed="orient === o"
					@click="patchTransition({ orient: o })"
				>
					{{
						o === 'horz' ? t('pptx.slideInspector.horizontal') : t('pptx.slideInspector.vertical')
					}}
				</button>
			</div>
		</div>

		<div v-if="patternOptions" class="mt-2 space-y-1 px-2.5">
			<span class="text-xs text-muted-foreground">{{ t('pptx.transition.pattern') }}</span>
			<div class="flex gap-1">
				<button
					v-for="pattern in patternOptions"
					:key="pattern"
					type="button"
					class="rounded border px-2 py-1 text-xs"
					:class="
						(slide?.transition?.pattern ?? patternOptions[0]) === pattern
							? 'border-primary bg-primary text-white'
							: 'border-border bg-muted hover:bg-accent'
					"
					@click="patchTransition({ pattern })"
				>
					{{ t(`pptx.transition.pattern.${pattern}`) }}
				</button>
			</div>
		</div>

		<label
			v-if="hasThruBlk"
			class="mt-1 inline-flex items-center gap-2 px-2.5 text-xs text-foreground"
		>
			<pptx-ui-checkbox
				data-testid="transition-thru-blk"
				:checked="slide?.transition?.thruBlk === true"
				@change="onThruBlkChange"
			/>
			{{ t('pptx.transition.thruBlk') }}
		</label>

		<label v-if="isWheel" class="mt-2 flex flex-col gap-1 px-2.5">
			<span class="text-xs text-muted-foreground">{{ t('pptx.transition.spokes') }}</span>
			<input
				type="number"
				min="1"
				max="8"
				:value="spokes"
				data-testid="transition-spokes"
				class="w-16 rounded border border-border bg-muted px-2 py-1 text-xs"
				@input="onSpokesInput"
			/>
		</label>

		<div v-if="hasTransition && isMorph" class="mt-2 space-y-1 px-2.5">
			<span class="text-xs text-muted-foreground">{{ t('pptx.transition.morphOption') }}</span>
			<pptx-ui-select
				class="w-full rounded border border-border bg-muted px-2 py-1 text-xs"
				:value="morphOption"
				:aria-label="t('pptx.transition.morphOption')"
				data-testid="transition-morph-option"
				@change="onMorphOptionChange"
			>
				<option
					v-for="option in TRANSITION_MORPH_OPTIONS"
					:key="option.value"
					:value="option.value"
				>
					{{ t(option.i18nKey) }}
				</option>
			</pptx-ui-select>
		</div>

		<label
			v-if="hasTransition"
			class="mt-1 inline-flex items-center gap-2 px-2.5 text-xs text-foreground"
		>
			<pptx-ui-checkbox
				data-testid="transition-advance"
				:checked="advanceOnClick"
				@change="onAdvanceChange"
			/>
			{{ t('pptx.transition.advanceOnClick') }}
		</label>

		<div v-if="slide?.transition" class="mt-2 px-2.5">
			<TransitionPreview :transition="slide.transition" />
		</div>
	</div>
</template>
