// viewers/pptx/packages/react/src/viewer/components/inspector/SlideSizeCard.tsx
/**
 * SlideSizeCard: the Design > Slide Size control, inspector edition.
 *
 * Every decision here (which preset a size matches, what a preset produces in
 * a given orientation, and whether the EMU size or the typed pixels win) comes
 * from `pptx-viewer-shared`'s `slide-size` module, so the other four bindings
 * can render the same descriptor without re-deriving any of it.
 */
import {
	resolveSlideSizeSelection,
	slideSizeFromPreset,
	SLIDE_SIZE_PRESETS,
	withSlideSizeOrientation,
} from 'ooxml-ui/pptx';
import type { SlideSizeEmu, SlideSizeOrientation, SlideSizeRescaleMode } from 'ooxml-ui/pptx';
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

import type { CanvasSize } from '../../types';
import { WebSelect } from '../WebControls';
import { CARD, HEADING, INPUT } from './inspector-pane-constants';
import { SlideSizeRescalePrompt } from './SlideSizeRescalePrompt';

/** Sentinel `<option>` value for a size that matches no preset. */
const CUSTOM_PRESET_VALUE = '';

export interface SlideSizeCardProps {
	canvasSize: CanvasSize;
	/**
	 * The EMU `p:sldSz` the viewer holds. Absent until a deck loads, in which
	 * case the pixel canvas alone decides the selection.
	 */
	slideSizeEmu?: SlideSizeEmu | undefined;
	canEdit: boolean;
	/** Raw W/H pixel edit. */
	onUpdate: (size: CanvasSize) => void;
	/**
	 * A preset or orientation pick, in EMU. Distinct from {@link onUpdate}
	 * because a pixel round-trip is lossy: Ledger is 12179300 EMU = 1278.5px,
	 * and the integer pixel it rounds to would cost the deck its preset.
	 *
	 * `rescaleMode` is set only when the user confirmed the Maximize/Ensure Fit
	 * prompt below for a size change that affects existing content.
	 */
	onUpdateSlideSize?: (size: SlideSizeEmu, rescaleMode?: SlideSizeRescaleMode) => void;
	/** Whether any slide has at least one element; gates the rescale prompt. */
	hasContent: boolean;
}

/** Whether two EMU sizes differ, ignoring `type` (a preset id carries no geometry of its own). */
function sizesDiffer(a: SlideSizeEmu, b: SlideSizeEmu): boolean {
	return a.widthEmu !== b.widthEmu || a.heightEmu !== b.heightEmu;
}

export function SlideSizeCard({
	canvasSize,
	slideSizeEmu,
	canEdit,
	onUpdate,
	onUpdateSlideSize,
	hasContent,
}: SlideSizeCardProps): React.ReactElement {
	const { t } = useTranslation();
	const selection = resolveSlideSizeSelection({ current: slideSizeEmu, canvas: canvasSize });
	const presetDisabled = !canEdit || !onUpdateSlideSize;

	// PowerPoint's Maximize/Ensure Fit prompt: held here rather than applied
	// immediately whenever the picked size differs from the current one AND the
	// deck actually has content to rescale. An empty deck (or a size that
	// happens to match already) applies directly, matching today's behaviour.
	const [pendingSize, setPendingSize] = useState<SlideSizeEmu | null>(null);

	const applyOrPromptSize = (nextSize: SlideSizeEmu): void => {
		if (hasContent && sizesDiffer(selection.size, nextSize)) {
			setPendingSize(nextSize);
			return;
		}
		onUpdateSlideSize?.(nextSize);
	};

	const handlePreset = (labelKey: string): void => {
		const preset = SLIDE_SIZE_PRESETS.find((candidate) => candidate.labelKey === labelKey);
		if (!preset) {
			return;
		}
		applyOrPromptSize(slideSizeFromPreset(preset, selection.orientation));
	};

	const handleOrientation = (orientation: SlideSizeOrientation): void => {
		applyOrPromptSize(withSlideSizeOrientation(selection.size, orientation));
	};

	const handleRescale = (mode: SlideSizeRescaleMode): void => {
		if (!pendingSize) {
			return;
		}
		onUpdateSlideSize?.(pendingSize, mode);
		setPendingSize(null);
	};

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.slideSize.title')}</div>
			<div className='space-y-1.5 text-[11px]'>
				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground'>{t('pptx.slideSize.presets')}</span>
					<WebSelect
						aria-label={t('pptx.slideSize.presets')}
						data-pptx-slide-size-preset
						disabled={presetDisabled}
						className={INPUT}
						value={selection.preset?.labelKey ?? CUSTOM_PRESET_VALUE}
						onChange={(e) => handlePreset(e.target.value)}
					>
						{/* Only offered while the size actually is custom: picking
						    "Custom" is not an instruction PowerPoint can carry out. */}
						{selection.preset === undefined && (
							<option value={CUSTOM_PRESET_VALUE}>{t('pptx.slideSize.customSize')}</option>
						)}
						{SLIDE_SIZE_PRESETS.map((preset) => (
							<option key={preset.labelKey} value={preset.labelKey}>
								{t(`pptx.slideSize.preset.${preset.labelKey}`)}
							</option>
						))}
					</WebSelect>
				</label>

				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground'>{t('pptx.slideSize.orientation')}</span>
					<WebSelect
						aria-label={t('pptx.slideSize.orientation')}
						data-pptx-slide-size-orientation
						disabled={presetDisabled}
						className={INPUT}
						value={selection.orientation}
						onChange={(e) => handleOrientation(e.target.value as SlideSizeOrientation)}
					>
						<option value='landscape'>{t('pptx.slideSize.landscape')}</option>
						<option value='portrait'>{t('pptx.slideSize.portrait')}</option>
					</WebSelect>
				</label>

				<div className='grid grid-cols-2 gap-1.5'>
					{(
						[
							['W', 'width'],
							['H', 'height'],
						] as const
					).map(([label, key]) => (
						<label key={key} className='flex items-center gap-1'>
							<span className='text-muted-foreground'>{label}</span>
							<input
								type='number'
								className={INPUT}
								disabled={!canEdit}
								value={canvasSize[key]}
								onChange={(e) => onUpdate({ ...canvasSize, [key]: Number(e.target.value) })}
							/>
						</label>
					))}
				</div>

				{pendingSize && <SlideSizeRescalePrompt onChoose={handleRescale} />}
			</div>
		</div>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/inspector/SlideSizeCard.vue
<script setup lang="ts">
/**
 * SlideSizeCard: the SLIDE SIZE card, mirroring PowerPoint's Design > Slide
 * Size: a preset dropdown, a Landscape/Portrait toggle, and the raw W/H pixel
 * inputs underneath for a hand-sized deck.
 *
 * Every decision here belongs to `resolveSlideSizeSelection` in
 * `pptx-viewer-shared`; this card only maps the descriptor it returns onto
 * controls. In particular it does NOT derive the EMU size from the pixel
 * inputs: that round-trip is lossy (Ledger is 12179300 EMU = 1278.5px) and
 * would cost a preset deck its identity on save.
 */
import type { SlideSizeEmu, SlideSizeOrientation } from 'ooxml-ui/pptx';
import {
	resolveSlideSizeSelection,
	SLIDE_SIZE_PRESETS,
	slideSizeFromPreset,
	slideSizeToCanvasPx,
	withSlideSizeOrientation,
} from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { CanvasSize } from '../../types';
import { CARD, HEADING, INPUT } from './inspector-cards';

const props = withDefaults(
	defineProps<{
		canvasSize: CanvasSize;
		/** The deck's `p:sldSz`, when one has been loaded or chosen. */
		slideSize?: SlideSizeEmu;
		canEdit?: boolean;
	}>(),
	{ canEdit: true },
);

const emit = defineEmits<{
	/** The raw W/H pixel inputs changed. */
	update: [size: CanvasSize];
	/** A preset or orientation was chosen: both EMU and pixel sizes follow. */
	'update-slide-size': [size: SlideSizeEmu, canvas: CanvasSize];
}>();

const { t } = useI18n();

const FIELDS = [
	['W', 'width'],
	['H', 'height'],
] as const;

const ORIENTATIONS: readonly SlideSizeOrientation[] = ['landscape', 'portrait'];

/** `''` marks the "Custom" entry, which only appears for an unmatched size. */
const CUSTOM_VALUE = '';

const presets = SLIDE_SIZE_PRESETS;

const selection = computed(() =>
	resolveSlideSizeSelection({ current: props.slideSize, canvas: props.canvasSize }),
);

const selectedPresetKey = computed(() => selection.value.preset?.labelKey ?? CUSTOM_VALUE);

function commit(size: SlideSizeEmu): void {
	emit('update-slide-size', size, slideSizeToCanvasPx(size));
}

function onPresetChange(event: Event): void {
	const labelKey = (event.target as HTMLSelectElement).value;
	const preset = presets.find((candidate) => candidate.labelKey === labelKey);
	if (!preset) {
		return;
	}
	commit(slideSizeFromPreset(preset, selection.value.orientation));
}

function onOrientationChange(orientation: SlideSizeOrientation): void {
	commit(withSlideSizeOrientation(selection.value.size, orientation));
}

function onFieldInput(key: 'width' | 'height', event: Event): void {
	const value = Number((event.target as HTMLInputElement).value);
	if (!Number.isFinite(value)) {
		return;
	}
	emit('update', { ...props.canvasSize, [key]: value });
}
</script>

<template>
	<div :class="CARD">
		<div :class="HEADING">{{ t('pptx.slideSize.title') }}</div>

		<label class="mb-1.5 flex flex-col gap-1 text-[11px]">
			<span class="text-muted-foreground">{{ t('pptx.slideSize.presets') }}</span>
			<pptx-ui-select
				:class="INPUT"
				data-pptx-slide-size-preset
				:disabled="!props.canEdit"
				:value="selectedPresetKey"
				:aria-label="t('pptx.slideSize.presets')"
				@change="onPresetChange"
			>
				<option v-if="!selection.preset" :value="CUSTOM_VALUE">
					{{ t('pptx.slideSize.customSize') }}
				</option>
				<option v-for="preset in presets" :key="preset.labelKey" :value="preset.labelKey">
					{{ t(`pptx.slideSize.preset.${preset.labelKey}`) }}
				</option>
			</pptx-ui-select>
		</label>

		<div class="mb-1.5 flex flex-col gap-1 text-[11px]">
			<span class="text-muted-foreground">{{ t('pptx.slideSize.orientation') }}</span>
			<div class="flex gap-1" role="group" :aria-label="t('pptx.slideSize.orientation')">
				<button
					v-for="orientation in ORIENTATIONS"
					:key="orientation"
					type="button"
					class="flex-1 rounded border px-2 py-1 text-[11px] transition-colors disabled:cursor-not-allowed disabled:opacity-50"
					:class="
						selection.orientation === orientation
							? 'border-primary bg-accent text-foreground'
							: 'border-border bg-muted text-muted-foreground hover:bg-accent'
					"
					:data-pptx-slide-size-orientation="orientation"
					:aria-pressed="selection.orientation === orientation"
					:disabled="!props.canEdit"
					@click="onOrientationChange(orientation)"
				>
					{{ t(`pptx.slideSize.${orientation}`) }}
				</button>
			</div>
		</div>

		<div class="grid grid-cols-2 gap-1.5 text-[11px]">
			<label v-for="[label, key] in FIELDS" :key="key" class="flex items-center gap-1">
				<span class="text-muted-foreground">{{ label }}</span>
				<input
					type="number"
					:class="INPUT"
					:disabled="!props.canEdit"
					:value="props.canvasSize[key]"
					@input="(e) => onFieldInput(key, e)"
				/>
			</label>
		</div>
	</div>
</template>
