// viewers/pptx/packages/react/src/viewer/components/inspector/TextWarpGallery.tsx
import type { TextStyle } from 'pptx-viewer-core';
import { TEXT_WARP_PRESETS, warpPreviewPath } from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';

// The warp preset catalogue + preview-path generator now live in
// `pptx-viewer-shared` (consumed identically by Vue and Angular). Re-export them
// here to preserve this module's historical public symbol surface.
export { TEXT_WARP_PRESETS, warpPreviewPath };

// ==========================================================================
// Component
// ==========================================================================

interface TextWarpGalleryProps {
	ts: TextStyle | undefined;
	onUpdateTextStyle: (updates: Partial<TextStyle>) => void;
}

export function TextWarpGallery({
	ts,
	onUpdateTextStyle,
}: TextWarpGalleryProps): React.ReactElement {
	const { t } = useTranslation();
	const [expanded, setExpanded] = React.useState(false);
	const currentPreset = ts?.textWarpPreset || 'textNoShape';

	return (
		<div className='mt-2 rounded border border-border bg-card p-2 space-y-2'>
			<button
				type='button'
				className='flex w-full items-center justify-between text-[11px] uppercase tracking-wide text-muted-foreground max-md:min-h-[44px]!'
				onClick={() => setExpanded(!expanded)}
			>
				<span>{t('pptx.textWarp.title')}</span>
				<span className='text-muted-foreground'>{expanded ? '−' : '+'}</span>
			</button>
			{!expanded && (
				<div className='text-[11px] text-muted-foreground'>
					{TEXT_WARP_PRESETS.find((p) => p.value === currentPreset)?.label || currentPreset}
				</div>
			)}
			{expanded && (
				<div className='grid grid-cols-5 gap-1'>
					{TEXT_WARP_PRESETS.map(({ value, label }) => (
						<button
							key={value}
							type='button'
							title={label}
							aria-label={label}
							className={`flex items-center justify-center rounded p-1 ${currentPreset === value ? 'bg-primary ring-1 ring-primary' : 'bg-muted hover:bg-accent'}`}
							onClick={() =>
								onUpdateTextStyle({
									textWarpPreset: value === 'textNoShape' ? undefined : value,
								})
							}
						>
							<svg width={40} height={20} viewBox='0 0 40 20'>
								<path
									d={warpPreviewPath(value)}
									stroke='currentColor'
									strokeWidth={1.5}
									fill='none'
									className={currentPreset === value ? 'text-white' : 'text-muted-foreground'}
								/>
							</svg>
						</button>
					))}
				</div>
			)}
		</div>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/inspector/TextWarpGallery.vue
<script setup lang="ts">
import type { PptxTextWarpPreset, TextStyle } from 'pptx-viewer-core';
import { TEXT_WARP_PRESETS, warpPreviewPath } from 'ooxml-ui/pptx';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * TextWarpGallery: collapsible gallery of text-warp presets, sourced from the
 * shared `TEXT_WARP_PRESETS` catalogue with miniature SVG previews from
 * `warpPreviewPath`. Selecting a preset emits `select` with the preset value,
 * or `undefined` for the identity `textNoShape` preset. The parent
 * (`TextPanel`) merges it into the full `textStyle` sub-object.
 */
const props = defineProps<{
	ts: TextStyle | undefined;
}>();

const emit = defineEmits<{
	select: [preset: PptxTextWarpPreset | undefined];
}>();

const { t } = useI18n();

const expanded = ref(false);

const currentPreset = computed<PptxTextWarpPreset>(() => props.ts?.textWarpPreset ?? 'textNoShape');

const currentLabel = computed<string>(() => {
	const match = TEXT_WARP_PRESETS.find((p) => p.value === currentPreset.value);
	return match?.label ?? currentPreset.value;
});

function pick(value: PptxTextWarpPreset): void {
	emit('select', value === 'textNoShape' ? undefined : value);
}
</script>

<template>
	<div class="pptx-vue-textwarp mt-2 rounded border border-border bg-card p-2 space-y-2">
		<button
			type="button"
			class="pptx-vue-textwarp-toggle flex w-full items-center justify-between text-[11px] uppercase tracking-wide text-muted-foreground"
			@click="expanded = !expanded"
		>
			<span>{{ t('pptx.textWarp.title') }}</span>
			<span class="text-muted-foreground">{{ expanded ? '-' : '+' }}</span>
		</button>

		<div v-if="!expanded" class="pptx-vue-textwarp-current text-[11px] text-muted-foreground">
			{{ currentLabel }}
		</div>

		<div v-else class="pptx-vue-textwarp-grid grid grid-cols-5 gap-1">
			<button
				v-for="opt in TEXT_WARP_PRESETS"
				:key="opt.value"
				type="button"
				:title="opt.label"
				class="pptx-vue-textwarp-swatch flex items-center justify-center rounded p-1"
				:class="
					currentPreset === opt.value
						? 'bg-primary ring-1 ring-primary'
						: 'bg-muted hover:bg-accent'
				"
				@click="pick(opt.value)"
			>
				<svg width="40" height="20" viewBox="0 0 40 20">
					<path
						:d="warpPreviewPath(opt.value)"
						stroke="currentColor"
						:stroke-width="1.5"
						fill="none"
						:class="currentPreset === opt.value ? 'text-white' : 'text-muted-foreground'"
					/>
				</svg>
			</button>
		</div>
	</div>
</template>
