// viewers/pptx/packages/angular/src/viewer/after-animation-row.component.ts
/**
 * after-animation-row.component.ts: the animation panel's "after animation"
 * row (dim to colour / hide after animation / hide on next click / don't dim).
 *
 * Selector: `pptx-after-animation-row`
 *
 * Its own component for the same reason as {@link MotionPathRowComponent}:
 * keeps {@link AnimationAuthorPanelComponent} under this repo's 300-LOC cap.
 *
 * Reference binding: packages/react/src/viewer/components/inspector/AfterAnimationRow.tsx
 *
 * @module viewer/after-animation-row
 */
import {
	ChangeDetectionStrategy,
	Component,
	input,
	output,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxAfterAnimationAction } from 'pptx-viewer-core';

import { AFTER_ANIMATION_VALUES } from 'ooxml-ui/pptx';
import { isSelectControl } from './control-event-targets';

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-after-animation-row',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<div class="pptx-ng-anim__section pptx-ng-after-animation">
			<label>
				<span class="pptx-ng-anim__label">{{ 'pptx.animation.afterAnimation' | translate }}</span>
				<pptx-ui-select
					[attr.aria-label]="'pptx.animation.afterAnimation' | translate"
					[attr.value]="action()"
					class="pptx-ng-anim__select"
					[disabled]="!canEdit()"
					(change)="onActionChange($event)"
				>
					@for (value of values; track value) {
						<option [value]="value" [selected]="action() === value">
							{{ 'pptx.animation.afterAnimation.' + value | translate }}
						</option>
					}
				</pptx-ui-select>
			</label>
			@if (action() === 'dimToColor') {
				<label class="pptx-ng-after-animation__color">
					<span class="pptx-ng-anim__label">{{
						'pptx.animation.afterAnimation.color' | translate
					}}</span>
					<input
						type="color"
						[attr.aria-label]="'pptx.animation.afterAnimation.color' | translate"
						[disabled]="!canEdit()"
						[value]="color() ?? '#808080'"
						(change)="onColorChange($event)"
					/>
				</label>
			}
		</div>
	`,
	styles: `
		.pptx-ng-after-animation {
			display: grid;
			gap: 6px;
		}
		.pptx-ng-after-animation__color {
			display: flex;
			align-items: center;
			gap: 6px;
		}
		.pptx-ng-after-animation__color input[type='color'] {
			width: 40px;
			height: 24px;
			padding: 0;
		}
	`,
})
export class AfterAnimationRowComponent {
	readonly action = input.required<PptxAfterAnimationAction>();
	readonly color = input<string | undefined>(undefined);
	readonly canEdit = input<boolean>(true);
	readonly actionChange = output<PptxAfterAnimationAction>();
	readonly colorChange = output<string>();

	protected readonly values = AFTER_ANIMATION_VALUES;

	protected onActionChange(event: Event): void {
		const target = event.target;
		if (!isSelectControl(target)) {
			return;
		}
		this.actionChange.emit(target.value as PptxAfterAnimationAction);
	}

	protected onColorChange(event: Event): void {
		const target = event.target;
		if (!(target instanceof HTMLInputElement)) {
			return;
		}
		this.colorChange.emit(target.value);
	}
}

// viewers/pptx/packages/svelte/src/viewer/components/inspector/AfterAnimationRow.svelte
<script lang="ts">
	/**
	 * AfterAnimationRow: the animation panel's "after animation" row (dim to
	 * colour / hide after animation / hide on next click / don't dim), Svelte
	 * port of React's `inspector/AfterAnimationRow.tsx`.
	 */
	import type { PptxAfterAnimationAction } from 'pptx-viewer-core';
	import { AFTER_ANIMATION_VALUES } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';

	const {
		action,
		color,
		canEdit,
		onaction,
		oncolor,
	}: {
		action: PptxAfterAnimationAction;
		color: string | undefined;
		canEdit: boolean;
		onaction: (action: PptxAfterAnimationAction) => void;
		oncolor: (color: string) => void;
	} = $props();

	const t = useTranslator();
</script>

<div class="pptx-svelte-after-animation">
	<label>
		<span>{t('pptx.animation.afterAnimation')}</span>
		<pptx-ui-select
			aria-label={t('pptx.animation.afterAnimation')}
			class="pptx-svelte-animp-after-animation"
			disabled={!canEdit}
			value={action}
			onchange={(event) => onaction(event.currentTarget.value as PptxAfterAnimationAction)}
		>
			{#each AFTER_ANIMATION_VALUES as value (value)}
				<option {value}>{t(`pptx.animation.afterAnimation.${value}`)}</option>
			{/each}
		</pptx-ui-select>
	</label>
	{#if action === 'dimToColor'}
		<label class="pptx-svelte-after-animation-color">
			<span>{t('pptx.animation.afterAnimation.color')}</span>
			<input
				type="color"
				aria-label={t('pptx.animation.afterAnimation.color')}
				disabled={!canEdit}
				value={color ?? '#808080'}
				onchange={(event) => oncolor(event.currentTarget.value)}
			/>
		</label>
	{/if}
</div>

<style>
	.pptx-svelte-after-animation {
		display: flex;
		flex-direction: column;
		gap: 6px;
	}

	.pptx-svelte-after-animation label {
		display: flex;
		flex-direction: column;
		gap: 3px;
	}

	.pptx-svelte-after-animation > label > span {
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-animp-after-animation {
		width: 100%;
		height: 26px;
		box-sizing: border-box;
		padding: 0 6px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		font: inherit;
		font-size: 11px;
	}

	.pptx-svelte-after-animation-color {
		flex-direction: row;
		align-items: center;
		gap: 6px;
	}

	.pptx-svelte-after-animation-color input[type='color'] {
		width: 40px;
		height: 24px;
		padding: 0;
	}
</style>
