// viewers/pptx/packages/vue/src/viewer/components/inspector/AnimationPanel.vue
<script setup lang="ts">
import type {
	AnimationPresetInfo,
	PptxAnimationTimelineAnchor,
	PptxAnimationTrigger,
	PptxElement,
	PptxElementAnimation,
} from 'pptx-viewer-core';
import {
	EMPHASIS_PRESETS,
	ENTRANCE_PRESETS,
	EXIT_PRESETS,
	getAnimationPresetInfo,
} from 'pptx-viewer-core';
import {
	animationCatalogPresetLabelKey,
	applyMotionPathPreset,
	clearMotionPath,
	getDensePanelTouchTargetPx,
	motionPathFor,
	TRIGGER_OPTIONS,
} from 'ooxml-ui/pptx';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { useIsMobile } from '../../composables/useIsMobile';
import type { AnimationCategory } from './animation-panel-model';
import { createElementAnimation, patchElementAnimation } from './animation-panel-model';
import { previewVueAnimation } from './animation-preview-player';
import AnimationEditorControls from './AnimationEditorControls.vue';
import AnimationTimeline from './AnimationTimeline.vue';
import MotionPathRow from './MotionPathRow.vue';

type AnimatableElement = PptxElement & { animations?: PptxElementAnimation[] };
const props = withDefaults(
	defineProps<{
		element: AnimatableElement;
		slideElements?: readonly PptxElement[];
		slideAnimations?: readonly PptxElementAnimation[];
		/** Read-only anchors for the deck's own effect groups; see {@link PptxAnimationTimelineAnchor}. */
		animationTimelineAnchors?: readonly PptxAnimationTimelineAnchor[];
		canEdit?: boolean;
	}>(),
	{
		slideElements: () => [],
		slideAnimations: () => [],
		animationTimelineAnchors: () => [],
		canEdit: true,
	},
);
const emit = defineEmits<{
	update: [patch: Partial<AnimatableElement>];
	updateSlideAnimations: [animations: PptxElementAnimation[]];
}>();
const { t } = useI18n();

// Dense-panel touch-target sizing (shared decision function; see CLAUDE.md
// Rule 2) for this panel's own small buttons, and forwarded to
// `AnimationEditorControls` for its per-row preview/remove buttons.
const { viewportWidth } = useIsMobile();
const touchTargetPx = computed(() => getDensePanelTouchTargetPx(viewportWidth.value));
const touchBtnStyle = computed(() => ({
	minWidth: `${touchTargetPx.value}px`,
	minHeight: `${touchTargetPx.value}px`,
}));

const currentAnimations = computed(() => props.element.animations ?? []);
const category = ref<AnimationCategory>('entrance');
const presetId = ref(ENTRANCE_PRESETS[0]?.presetId ?? '');
const trigger = ref<PptxAnimationTrigger>('onClick');

const categories: readonly { value: AnimationCategory; labelKey: string }[] = [
	{ value: 'entrance', labelKey: 'pptx.animation.entrance' },
	{ value: 'emphasis', labelKey: 'pptx.animation.emphasis' },
	{ value: 'exit', labelKey: 'pptx.animation.exit' },
];
const presets: Readonly<Record<AnimationCategory, AnimationPresetInfo[]>> = {
	entrance: ENTRANCE_PRESETS,
	emphasis: EMPHASIS_PRESETS,
	exit: EXIT_PRESETS,
};
const presetChoices = computed(() => presets[category.value]);

/**
 * The catalogue's own `label` is a hard-coded English constant in a core data
 * table a locale cannot override, so this picker stayed English in every
 * language. Name each preset through the dictionary instead.
 */
function catalogLabel(preset: AnimationPresetInfo): string {
	return t(animationCatalogPresetLabelKey(preset.presetId));
}
const timelineAnimations = computed(() =>
	props.slideAnimations.length ? props.slideAnimations : currentAnimations.value,
);

function changeCategory(): void {
	presetId.value = presetChoices.value[0]?.presetId ?? '';
}
function onCategoryChange(event: Event): void {
	category.value = (event.currentTarget as HTMLElement & { value: AnimationCategory }).value;
	changeCategory();
}
function onPresetChange(event: Event): void {
	presetId.value = (event.currentTarget as HTMLElement & { value: string }).value;
}
function onTriggerChange(event: Event): void {
	trigger.value = (event.currentTarget as HTMLElement & { value: PptxAnimationTrigger }).value;
}
function addAnimation(): void {
	const info = getAnimationPresetInfo(presetId.value);
	if (!info) {
		return;
	}
	const next = createElementAnimation(
		props.element.id,
		category.value,
		info,
		timelineAnimations.value.length,
	);
	emit('update', { animations: [...currentAnimations.value, { ...next, trigger: trigger.value }] });
}
function patchAnimation(index: number, patch: Partial<PptxElementAnimation>): void {
	emit('update', { animations: patchElementAnimation(currentAnimations.value, index, patch) });
}
function removeAnimation(index: number): void {
	emit('update', { animations: currentAnimations.value.filter((_, current) => current !== index) });
}

// A motion path lives on the SLIDE's animation list (keyed by element id), the
// same list the canvas overlay and the ribbon gallery write, so the row reads
// and commits there rather than through the element-scoped `update` patch.
const motionPath = computed(() => motionPathFor(props.slideAnimations, props.element.id));

function changeMotionPath(pathPresetId: string): void {
	if (!props.canEdit) {
		return;
	}
	// `custom` is the read-only marker for a hand-dragged path; selecting it
	// again is a no-op rather than a reset to some catalogue entry.
	if (pathPresetId === 'custom') {
		return;
	}
	emit(
		'updateSlideAnimations',
		pathPresetId === 'none'
			? clearMotionPath(props.slideAnimations, props.element.id)
			: applyMotionPathPreset(props.slideAnimations, props.element.id, pathPresetId),
	);
}
</script>

<template>
	<div class="flex flex-col gap-2 rounded-md border border-border bg-card p-2 text-xs">
		<div class="text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.animation.title') }}
		</div>
		<div v-if="currentAnimations.length" class="space-y-2">
			<AnimationEditorControls
				v-for="(animation, index) in currentAnimations"
				:key="`${animation.elementId}-${index}`"
				:animation="animation"
				:elements="slideElements"
				:touch-target-px="touchTargetPx"
				@patch="patchAnimation(index, $event)"
				@remove="removeAnimation(index)"
				@preview="previewVueAnimation(animation)"
			/>
		</div>
		<p v-else class="text-muted-foreground">{{ t('pptx.animation.noAnimations') }}</p>

		<!-- Motion path: geometry, not a preset, so it gets its own row -->
		<MotionPathRow :motion-path="motionPath" :can-edit="canEdit" @change="changeMotionPath" />

		<AnimationTimeline
			:animations="timelineAnimations"
			:elements="slideElements"
			:animation-timeline-anchors="animationTimelineAnchors"
			:selected-element-id="element.id"
			@reorder="emit('updateSlideAnimations', $event)"
		/>

		<div class="flex flex-col gap-1.5 border-t border-border pt-2">
			<div class="text-[11px] uppercase text-muted-foreground">
				{{ t('pptx.animation.addAnimation') }}
			</div>
			<label
				>{{ t('pptx.animation.category') }}
				<pptx-ui-select
					:value="category"
					:aria-label="t('pptx.animation.categoryAria')"
					@change="onCategoryChange"
				>
					<option v-for="option in categories" :key="option.value" :value="option.value">
						{{ t(option.labelKey) }}
					</option>
				</pptx-ui-select>
			</label>
			<label
				>{{ t('pptx.animation.effect') }}
				<pptx-ui-select
					:value="presetId"
					:aria-label="t('pptx.animation.presetAria')"
					@change="onPresetChange"
				>
					<option v-for="preset in presetChoices" :key="preset.presetId" :value="preset.presetId">
						{{ catalogLabel(preset) }}
					</option>
				</pptx-ui-select>
			</label>
			<label
				>{{ t('pptx.animation.start') }}
				<pptx-ui-select
					:value="trigger"
					:aria-label="t('pptx.animation.triggerAria')"
					@change="onTriggerChange"
				>
					<option v-for="item in TRIGGER_OPTIONS" :key="item.value" :value="item.value">
						{{ t(item.labelKey) }}
					</option>
				</pptx-ui-select>
			</label>
			<button
				type="button"
				class="pptx-vue-anim-add-btn inline-flex items-center justify-center rounded bg-primary px-2 py-1.5 text-white disabled:opacity-50"
				:style="touchBtnStyle"
				:disabled="!presetId"
				@click="addAnimation"
			>
				{{ t('pptx.animation.addAnimation') }}
			</button>
		</div>
	</div>
</template>

<style scoped>
label {
	display: grid;
	gap: 3px;
	color: var(--muted-foreground);
}
select {
	box-sizing: border-box;
	width: 100%;
	border: 1px solid var(--border);
	border-radius: 3px;
	background: var(--muted);
	color: inherit;
	padding: 4px 6px;
}
/* Touch target: matches MIN_TOUCH_TARGET_PX (44) from pptx-viewer-shared's
   render/responsive module, below MOBILE_BREAKPOINT (768). */
@media (max-width: 767px) {
	select {
		min-height: 44px;
	}
}
</style>

// viewers/pptx/packages/svelte/src/viewer/components/inspector/AnimationPanel.svelte
<script lang="ts">
	/**
	 * AnimationPanel: the docked per-element animation editor, port of React's
	 * `inspector/AnimationPanel.tsx`. Docked at the bottom of the inspector
	 * pane whenever an element is selected (any tab), it edits the slide-level
	 * `PptxSlide.animations` entry for the selection: entrance / emphasis /
	 * exit presets, direction (for directional presets), sequence, the TIMING
	 * block ({@link AnimationTimingFields}), and the timeline section
	 * ({@link AnimationTimelineSection}).
	 *
	 * Every mutation goes through the shared `animation-authoring` setters and
	 * commits via `commitSlideAnimations` -> `EditorState.commitSlides`, so each
	 * change is one undoable history step, exactly like React's
	 * `onUpdateSlide({ animations })` path. Self-gating: renders nothing
	 * without a selection, so the host only adds `<AnimationPanel {editor} />`.
	 */
	import Play from '@lucide/svelte/icons/play';
	import type {
		PptxAfterAnimationAction,
		PptxAnimationDirection,
		PptxAnimationPreset,
		PptxAnimationSequence,
		PptxElementAnimation,
	} from 'pptx-viewer-core';
	import {
		animationFor,
		applyMotionPathPreset,
		clearMotionPath,
		getDensePanelTouchTargetPx,
		getEffectSoundState,
		hasAnimation,
		setAfterAnimation,
		setAfterAnimationColor,
		setAnimationEmphasis,
		setAnimationEntrance,
		setAnimationExit,
		directionValuesFor,
		effectiveDirection,
		setDirection,
		setEffectSound,
		setEffectStockSound,
		setSequence,
		showDirectionPicker,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';
	import type { EditorState } from '../../editor/editor-state.svelte';
	import { useWindowViewport } from '../../state/window-viewport.svelte';
	import AfterAnimationRow from './AfterAnimationRow.svelte';
	import { commitSlideAnimations } from './animation-panel-helpers';
	import {
		PANEL_DIRECTION_OPTIONS,
		PANEL_EMPHASIS_PRESETS,
		PANEL_ENTRANCE_PRESETS,
		PANEL_EXIT_PRESETS,
		PANEL_SEQUENCE_OPTIONS,
	} from './animation-panel-options';
	import { startAnimationPreview } from './animation-preview-control';
	import AnimationTimelineSection from './AnimationTimelineSection.svelte';
	import AnimationTimingFields from './AnimationTimingFields.svelte';
	import EffectSoundRow from './EffectSoundRow.svelte';
	import MotionPathRow from './MotionPathRow.svelte';

	const { editor }: { editor: EditorState } = $props();
	const t = useTranslator();
	const viewport = useWindowViewport();
	// The direction-picker icon buttons and the Preview button are 28px by
	// design; below the dense-panel breakpoint they must still clear the 44px
	// touch target, so this only ever grows them, never shrinks below 28.
	const touchPx = $derived(Math.max(28, getDensePanelTouchTargetPx(viewport.width)));
	const touchStyle = $derived(`min-width: ${touchPx}px; min-height: ${touchPx}px;`);

	const slide = $derived(editor.slides[editor.currentSlideIndex]);
	const el = $derived(editor.selectedElement);
	const anims = $derived<PptxElementAnimation[]>(slide?.animations ?? []);
	const anim = $derived(el ? animationFor(anims, el.id) : undefined);
	const hasAnim = $derived(el ? hasAnimation(anims, el.id) : false);
	const showDirection = $derived(el ? showDirectionPicker(anims, el.id) : false);
	// Only the directions PowerPoint has a variant for (shared catalogue).
	const directionValues = $derived(el ? directionValuesFor(anims, el.id) : []);
	const directionOptions = $derived(PANEL_DIRECTION_OPTIONS.filter((option) => directionValues.includes(option.value)));
	const activeDirection = $derived(effectiveDirection(anim, directionValues));
	const canEdit = $derived(editor.editable);
	const soundState = $derived(el ? getEffectSoundState(anims, el.id) : { hasSound: false });

	function commit(next: PptxElementAnimation[]): void {
		if (canEdit) {
			commitSlideAnimations(editor, next);
		}
	}

	function onEffect(group: 'entrance' | 'emphasis' | 'exit', value: string): void {
		if (!el) {
			return;
		}
		const preset = value as PptxAnimationPreset | 'none';
		const apply =
			group === 'entrance'
				? setAnimationEntrance
				: group === 'emphasis'
					? setAnimationEmphasis
					: setAnimationExit;
		commit(apply(anims, el.id, preset));
	}

	function onPreview(): void {
		if (anim) {
			startAnimationPreview(anim);
		}
	}

	/**
	 * Motion path is geometry, not a preset, so it never routes through
	 * `onEffect`. `custom` is the read-only marker for a hand-dragged path:
	 * re-selecting it must not snap the path back to a catalogue entry.
	 */
	function onMotionPath(presetId: string): void {
		if (!el || presetId === 'custom') {
			return;
		}
		commit(
			presetId === 'none'
				? clearMotionPath(anims, el.id)
				: applyMotionPathPreset(anims, el.id, presetId),
		);
	}

	function onEffectSoundPick(pick: { dataUrl: string; fileName?: string } | undefined): void {
		if (!el) {
			return;
		}
		commit(setEffectSound(anims, el.id, pick));
	}

	function onEffectStockSoundPick(catalogueId: string): void {
		if (!el) {
			return;
		}
		commit(setEffectStockSound(anims, el.id, catalogueId));
	}

	function onAfterAnimationChange(action: PptxAfterAnimationAction): void {
		if (!el) {
			return;
		}
		commit(setAfterAnimation(anims, el.id, action));
	}

	function onAfterAnimationColorChange(color: string): void {
		editor.recordRecentColor(color);
		if (!el) {
			return;
		}
		commit(setAfterAnimationColor(anims, el.id, color));
	}
</script>

{#if el && slide}
	<div class="pptx-svelte-animp" data-pptx-animation-panel>
		<div class="pptx-svelte-animp-header">
			<span class="pptx-svelte-animp-title">{t('pptx.animation.title')}</span>
			{#if hasAnim}
				<button
					type="button"
					class="pptx-svelte-animp-preview"
					style={touchStyle}
					title={t('pptx.animation.preview')}
					onclick={onPreview}
				>
					<Play size={12} aria-hidden="true" /> {t('pptx.animation.preview')}
				</button>
			{/if}
		</div>

		<label>
			<span>{t('pptx.animation.entrance')}</span>
			<pptx-ui-select aria-label={t('pptx.animation.entrance')} class="pptx-svelte-animp-entrance" disabled={!canEdit} value={anim?.entrance ?? 'none'} onchange={(e) => onEffect('entrance', e.currentTarget.value)}>
				<option value="none">{t('pptx.animation.none')}</option>
				{#each PANEL_ENTRANCE_PRESETS as preset (preset)}<option value={preset}>{t(`pptx.animation.preset.${preset}`)}</option>{/each}
			</pptx-ui-select>
		</label>

		<label>
			<span>{t('pptx.animation.emphasis')}</span>
			<pptx-ui-select aria-label={t('pptx.animation.emphasis')} class="pptx-svelte-animp-emphasis" disabled={!canEdit} value={anim?.emphasis ?? 'none'} onchange={(e) => onEffect('emphasis', e.currentTarget.value)}>
				<option value="none">{t('pptx.animation.none')}</option>
				{#each PANEL_EMPHASIS_PRESETS as preset (preset)}<option value={preset}>{t(`pptx.animation.preset.${preset}`)}</option>{/each}
			</pptx-ui-select>
		</label>

		<label>
			<span>{t('pptx.animation.exit')}</span>
			<pptx-ui-select aria-label={t('pptx.animation.exit')} class="pptx-svelte-animp-exit" disabled={!canEdit} value={anim?.exit ?? 'none'} onchange={(e) => onEffect('exit', e.currentTarget.value)}>
				<option value="none">{t('pptx.animation.none')}</option>
				{#each PANEL_EXIT_PRESETS as preset (preset)}<option value={preset}>{t(`pptx.animation.preset.${preset}`)}</option>{/each}
			</pptx-ui-select>
		</label>

		<!-- Motion path: geometry, not a preset, so it gets its own row. -->
		<MotionPathRow motionPath={anim?.motionPath} {canEdit} onchange={onMotionPath} />

		{#if hasAnim}
			{#if showDirection}
				<div class="pptx-svelte-animp-direction">
					<span>{t('pptx.animation.direction')}</span>
					<div class="pptx-svelte-animp-direction-row">
						{#each directionOptions as option (option.value)}
							<button
								type="button"
								disabled={!canEdit}
								style={touchStyle}
								class:is-active={activeDirection === option.value}
								title={t(option.labelKey)}
								aria-label={t(option.labelKey)}
								onclick={() => el && commit(setDirection(anims, el.id, option.value as PptxAnimationDirection))}
							>{option.glyph}</button>
						{/each}
					</div>
				</div>
			{/if}

			<label>
				<span>{t('pptx.animation.sequence')}</span>
				<pptx-ui-select aria-label={t('pptx.animation.sequence')} class="pptx-svelte-animp-sequence" disabled={!canEdit} value={anim?.sequence ?? 'asOne'} onchange={(e) => el && commit(setSequence(anims, el.id, e.currentTarget.value as PptxAnimationSequence))}>
					{#each PANEL_SEQUENCE_OPTIONS as option (option.value)}<option value={option.value}>{t(option.labelKey)}</option>{/each}
				</pptx-ui-select>
			</label>

			<EffectSoundRow
			{soundState}
			{canEdit}
			onpick={onEffectSoundPick}
			onpickstock={onEffectStockSoundPick}
		/>
			<AfterAnimationRow
				action={anim?.afterAnimation ?? 'none'}
				color={anim?.afterAnimationColor}
				{canEdit}
				onaction={onAfterAnimationChange}
				oncolor={onAfterAnimationColorChange}
			/>

			<AnimationTimingFields {editor} />
		{/if}

		<AnimationTimelineSection {editor} selectedElementId={el.id} />
	</div>
{/if}

<style>
	.pptx-svelte-animp {
		flex: none;
		max-height: 220px;
		overflow-y: auto;
		padding: 8px 12px 12px;
		border-top: 1px solid var(--pptx-border, #33334d);
		display: flex;
		flex-direction: column;
		gap: 8px;
		font-size: 11px;
	}

	.pptx-svelte-animp-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	.pptx-svelte-animp-title {
		font-size: 11px;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.04em;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-animp-preview {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		border: none;
		background: transparent;
		color: var(--pptx-primary, #6366f1);
		cursor: pointer;
		font: inherit;
		font-size: 10px;
	}

	.pptx-svelte-animp label {
		display: flex;
		flex-direction: column;
		gap: 3px;
	}

	.pptx-svelte-animp label > span,
	.pptx-svelte-animp-direction > span {
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-animp select {
		width: 100%;
		height: 26px;
		box-sizing: border-box;
		padding: 0 6px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		font: inherit;
		font-size: 11px;
	}

	.pptx-svelte-animp-direction {
		display: flex;
		flex-direction: column;
		gap: 4px;
		padding-top: 6px;
		border-top: 1px solid var(--pptx-border, #33334d);
	}

	.pptx-svelte-animp-direction-row {
		display: flex;
		gap: 4px;
	}

	.pptx-svelte-animp-direction-row button {
		display: grid;
		place-items: center;
		width: 28px;
		height: 28px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #2a2a3d);
		color: var(--pptx-muted-foreground, #94a3b8);
		cursor: pointer;
		font: inherit;
	}

	.pptx-svelte-animp-direction-row button.is-active {
		border-color: var(--pptx-primary, #6366f1);
		background: color-mix(in srgb, var(--pptx-primary, #6366f1) 20%, transparent);
		color: var(--pptx-primary, #6366f1);
	}

	.pptx-svelte-animp-direction-row button:disabled {
		opacity: 0.5;
		cursor: default;
	}
</style>
