// viewers/pptx/packages/vue/src/viewer/components/inspector/MediaTrimTimeline.vue
<script setup lang="ts">
/**
 * MediaTrimTimeline: the draggable trim scrubber, ported from React's
 * `TrimTimeline`. Shows the trimmed region, a playhead, two drag handles, and
 * bookmark markers over a clip of `duration` seconds.
 *
 *  - Emits `trim-change` with `{ trimStartMs, trimEndMs }` while a handle drags.
 *  - Emits `seek` with a time in seconds when the bar (or a marker) is clicked.
 *
 * All state is derived from props; the parent owns trim + playhead values.
 */
import type { MediaBookmark } from 'pptx-viewer-core';
import { mediaTrimEndMsFromSeconds, mediaTrimEndSeconds } from 'ooxml-ui/pptx';
import { computed, onBeforeUnmount, ref } from 'vue';

import { clamp } from '../../composables/useMediaEditing';

const props = defineProps<{
	duration: number;
	trimStartMs: number;
	trimEndMs: number;
	currentTime: number;
	bookmarks: MediaBookmark[];
	canEdit: boolean;
}>();

const emit = defineEmits<{
	'trim-change': [payload: { trimStartMs: number; trimEndMs: number }];
	seek: [time: number];
}>();

const barRef = ref<HTMLDivElement | null>(null);
const dragging = ref<'start' | 'end' | null>(null);

const safeDuration = computed(() => (props.duration > 0 ? props.duration : 1));
const trimStartSec = computed(() => props.trimStartMs / 1000);
// `trimEndMs` is p14:trim/@end's distance from the clip's tail.
const trimEndSec = computed(() => mediaTrimEndSeconds(props.duration, props.trimEndMs));

const startPct = computed(() => (trimStartSec.value / safeDuration.value) * 100);
const endPct = computed(() => (trimEndSec.value / safeDuration.value) * 100);
const playheadPct = computed(() => Math.min((props.currentTime / safeDuration.value) * 100, 100));

function timeFromPointer(clientX: number): number {
	const bar = barRef.value;
	if (!bar) {
		return 0;
	}
	const rect = bar.getBoundingClientRect();
	const ratio = clamp((clientX - rect.left) / rect.width, 0, 1);
	return ratio * safeDuration.value;
}

function onPointerMove(event: PointerEvent): void {
	if (!dragging.value) {
		return;
	}
	const t = timeFromPointer(event.clientX);
	if (dragging.value === 'start') {
		const newStart = Math.min(t, trimEndSec.value - 0.1);
		emit('trim-change', {
			trimStartMs: Math.max(0, newStart) * 1000,
			trimEndMs: props.trimEndMs,
		});
	} else {
		const newEnd = Math.max(t, trimStartSec.value + 0.1);
		emit('trim-change', {
			trimStartMs: props.trimStartMs,
			trimEndMs: mediaTrimEndMsFromSeconds(props.duration, newEnd),
		});
	}
}

function stopDragging(): void {
	dragging.value = null;
	window.removeEventListener('pointermove', onPointerMove);
	window.removeEventListener('pointerup', stopDragging);
}

function startDragging(which: 'start' | 'end', event: PointerEvent): void {
	event.stopPropagation();
	if (!props.canEdit) {
		return;
	}
	dragging.value = which;
	window.addEventListener('pointermove', onPointerMove);
	window.addEventListener('pointerup', stopDragging);
}

function onBarClick(event: MouseEvent): void {
	emit('seek', timeFromPointer(event.clientX));
}

function markerPct(bmk: MediaBookmark): number {
	return (bmk.time / safeDuration.value) * 100;
}

function onMarkerClick(bmk: MediaBookmark, event: MouseEvent): void {
	event.stopPropagation();
	emit('seek', bmk.time);
}

onBeforeUnmount(stopDragging);
</script>

<template>
	<div class="pptx-vue-media-timeline space-y-1">
		<div class="flex items-center justify-between text-[10px] text-muted-foreground tabular-nums">
			<span>{{ trimStartSec.toFixed(1) }}s</span>
			<span>{{ trimEndSec.toFixed(1) }}s</span>
		</div>
		<div
			ref="barRef"
			class="pptx-vue-media-timeline__bar relative h-5 rounded bg-muted cursor-pointer select-none"
			@click="onBarClick"
		>
			<div
				class="absolute top-0 bottom-0 bg-primary/30 rounded"
				:style="{ left: `${startPct}%`, width: `${endPct - startPct}%` }"
			/>
			<div
				class="absolute top-0 bottom-0 w-0.5 bg-white z-10"
				:style="{ left: `${playheadPct}%` }"
			/>
			<div
				v-if="canEdit"
				class="absolute top-0 bottom-0 w-2 bg-primary rounded-l cursor-ew-resize z-20 hover:bg-primary/80"
				:style="{ left: `calc(${startPct}% - 4px)` }"
				@pointerdown="startDragging('start', $event)"
			/>
			<div
				v-if="canEdit"
				class="absolute top-0 bottom-0 w-2 bg-primary rounded-r cursor-ew-resize z-20 hover:bg-primary/80"
				:style="{ left: `calc(${endPct}% - 4px)` }"
				@pointerdown="startDragging('end', $event)"
			/>
			<div
				v-for="bmk in bookmarks"
				:key="bmk.id"
				class="absolute top-0 bottom-0 w-1 bg-yellow-400/70 z-10 cursor-pointer"
				:style="{ left: `${markerPct(bmk)}%` }"
				:title="bmk.label"
				@click="onMarkerClick(bmk, $event)"
			/>
		</div>
	</div>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/inspector/MediaTrimTimeline.svelte
<script lang="ts">
	import type { MediaBookmark } from 'pptx-viewer-core';
	import { mediaTimelineGeometry, mediaTrimEndSeconds, mediaTrimRangeForDrag } from 'ooxml-ui/pptx';

	const { duration, startMs, endMs, currentTime, bookmarks, onchange, onseek }: { duration: number; startMs: number; endMs?: number; currentTime: number; bookmarks: MediaBookmark[]; onchange: (startMs: number, endMs: number) => void; onseek: (seconds: number) => void } = $props();
	// eslint-disable-next-line prefer-const
	let bar = $state<HTMLDivElement>();
	// eslint-disable-next-line prefer-const
	let dragging = $state<'start' | 'end' | null>(null);
	const safeDuration = $derived(Math.max(duration, 0.1));
	// `endMs` is p14:trim/@end's distance from the clip's tail; the shared
	// helpers convert to and from the absolute position the scrubber draws.
	const trimEndMs = $derived(endMs ?? 0);
	const effectiveEndSeconds = $derived(mediaTrimEndSeconds(duration, trimEndMs));
	const geometry = $derived(mediaTimelineGeometry(duration, startMs, trimEndMs, currentTime));

	function timeAt(clientX: number): number {
		const rect = bar?.getBoundingClientRect();
		if (!rect) {
			return 0;
		}
		return Math.max(0, Math.min(1, (clientX - rect.left) / rect.width)) * safeDuration;
	}
	function move(event: PointerEvent): void {
		if (!dragging) {
			return;
		}
		const range = mediaTrimRangeForDrag(dragging, timeAt(event.clientX), duration, startMs, trimEndMs);
		onchange(range.trimStartMs, range.trimEndMs);
	}
	function keySeek(event: KeyboardEvent): void {
		if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') {
			return;
		}
		event.preventDefault();
		onseek(Math.max(0, Math.min(duration, currentTime + (event.key === 'ArrowRight' ? 0.5 : -0.5))));
	}
</script>

<svelte:window onpointermove={move} onpointerup={() => (dragging = null)} />
<div class="times"><span>{(startMs / 1000).toFixed(1)}s</span><span>{effectiveEndSeconds.toFixed(1)}s</span></div>
<div class="timeline" bind:this={bar} role="slider" aria-label="Media trim timeline" aria-valuemin="0" aria-valuemax={duration} aria-valuenow={currentTime} tabindex="0" onclick={(event) => onseek(timeAt(event.clientX))} onkeydown={keySeek}>
	<div class="range" style={`left:${geometry.startPercent}%;right:${100 - geometry.endPercent}%`}></div>
	<div class="playhead" style={`left:${geometry.playheadPercent}%`}></div>
	<button type="button" class="handle start" aria-label="Trim start" style={`left:${geometry.startPercent}%`} data-pptx-compact onpointerdown={(event) => { event.stopPropagation(); dragging = 'start'; }}></button>
	<button type="button" class="handle end" aria-label="Trim end" style={`left:${geometry.endPercent}%`} data-pptx-compact onpointerdown={(event) => { event.stopPropagation(); dragging = 'end'; }}></button>
	{#each bookmarks as bookmark}<button type="button" class="bookmark" title={bookmark.label} aria-label={bookmark.label} style={`left:${bookmark.time / safeDuration * 100}%`} data-pptx-compact onclick={(event) => { event.stopPropagation(); onseek(bookmark.time); }}></button>{/each}
</div>

<style>.times{display:flex;justify-content:space-between;color:var(--pptx-muted-foreground);font-size:9px}.timeline{position:relative;height:22px;border-radius:5px;background:var(--pptx-muted);cursor:pointer}.range{position:absolute;inset-block:0;background:color-mix(in srgb,var(--pptx-primary) 30%,transparent)}.playhead{position:absolute;inset-block:0;width:2px;background:white}.handle,.bookmark{position:absolute;top:0;bottom:0;width:7px;transform:translateX(-50%);border:0;background:var(--pptx-primary);cursor:ew-resize}.bookmark{width:3px;background:#facc15;cursor:pointer}</style>
