// viewers/pptx/packages/react/src/viewer/components/inspector/SlideTransitionSection.tsx
/**
 * SlideTransitionSection: the SLIDE TRANSITION card of the no-selection
 * inspector, rendered by `PresentationPropertiesPanel` immediately after SLIDE
 * SIZE so React sits where Angular, Svelte and Vanilla already put it.
 *
 * WHY the conditional controls: OOXML overloads a transition's `dir`
 * attribute. Most types take a compass token, the blinds/checker/comb/randomBar
 * family takes `horz`/`vert`, and `wheel` takes a spoke count instead.
 * `TRANSITION_VALID_DIRECTIONS` (core) and `TRANSITION_ORIENTATION_TYPES`
 * (shared) decide which control applies, so the card never offers a direction
 * PowerPoint would drop on save.
 *
 * WHY the shared clamp: `clampTransitionNumber` rounds every binding's typed
 * duration / spoke count the same way, so the same gesture in React and in
 * Angular stores the same number.
 */
import type { PptxSlideTransition, PptxTransitionType } from 'pptx-viewer-core';
import {
	TRANSITION_PATTERN_OPTIONS,
	TRANSITION_THRUBLK_TYPES,
	TRANSITION_VALID_DIRECTIONS,
} from 'pptx-viewer-core';
import {
	clampTransitionNumber,
	TRANSITION_MORPH_OPTIONS,
	TRANSITION_ORIENTATION_TYPES,
	TRANSITION_SPEED_OPTIONS,
} from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';

import { SLIDE_TRANSITION_OPTIONS } from '../../constants';
import { WebSelect, WebCheckbox } from '../WebControls';
import { DirectionPicker } from './DirectionPicker';
import { TransitionPreview } from './TransitionPreview';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface SlideTransitionSectionProps {
	activeSlide: { transition?: PptxSlideTransition } | null;
	/** Disables every control when the viewer is not in an editable mode. */
	canEdit?: boolean;
	onTransitionChange: (updates: Partial<PptxSlideTransition>) => void;
}

/** Default duration (ms) shown when the slide declares no transition timing. */
const DEFAULT_DURATION_MS = 320;
const MAX_DURATION_MS = 10000;
const MIN_SPOKES = 1;
const MAX_SPOKES = 8;

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function SlideTransitionSection({
	activeSlide,
	canEdit = true,
	onTransitionChange,
}: SlideTransitionSectionProps): React.ReactElement | null {
	const { t } = useTranslation();

	if (!activeSlide) {
		return null;
	}

	const transitionType: PptxTransitionType = activeSlide.transition?.type ?? 'none';
	const validDirections = TRANSITION_VALID_DIRECTIONS[transitionType];
	const hasDirections = validDirections !== undefined && validDirections.length > 0;
	const usesOrientation = TRANSITION_ORIENTATION_TYPES.has(transitionType);
	const isWheel = transitionType === 'wheel';
	const isMorph = transitionType === 'morph';
	const patternOptions = TRANSITION_PATTERN_OPTIONS[transitionType];
	const hasThruBlk = TRANSITION_THRUBLK_TYPES.has(transitionType);

	return (
		<div
			className='mb-3 rounded border border-border bg-card p-2 space-y-2'
			data-pptx-slide-transition
		>
			<div className='text-[11px] uppercase tracking-wide text-muted-foreground'>
				{t('pptx.slideInspector.slideTransition')}
			</div>

			{/* Type */}
			<label className='flex flex-col gap-1'>
				<span className='text-muted-foreground text-xs'>{t('pptx.transition.type')}</span>
				<WebSelect
					value={activeSlide.transition?.type || 'none'}
					disabled={!canEdit}
					aria-label={t('pptx.transition.type')}
					onChange={(e) =>
						onTransitionChange({
							type: e.target.value as NonNullable<PptxSlideTransition['type']>,
						})
					}
					className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
				>
					{SLIDE_TRANSITION_OPTIONS.map((option) => (
						<option key={option.value} value={option.value}>
							{t(option.i18nKey)}
						</option>
					))}
				</WebSelect>
			</label>

			{/* Direction picker */}
			{hasDirections && !usesOrientation && (
				<div className='space-y-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.direction')}</span>
					<DirectionPicker
						directions={validDirections}
						value={activeSlide.transition?.direction}
						disabled={!canEdit}
						onChange={(dir) => onTransitionChange({ direction: dir })}
					/>
				</div>
			)}

			{/* Orientation picker */}
			{usesOrientation && (
				<div className='space-y-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.orientation')}</span>
					<div className='flex gap-1'>
						{(['horz', 'vert'] as const).map((o) => (
							<button
								key={o}
								type='button'
								disabled={!canEdit}
								onClick={() => onTransitionChange({ orient: o })}
								className={`px-2 py-1 rounded text-xs border ${
									(activeSlide.transition?.orient ?? 'horz') === o
										? 'bg-primary text-white border-primary'
										: 'bg-muted border-border hover:bg-accent'
								}`}
							>
								{t(
									o === 'horz' ? 'pptx.slideInspector.horizontal' : 'pptx.slideInspector.vertical',
								)}
							</button>
						))}
					</div>
				</div>
			)}

			{/* Pattern (glitter's diamond/hexagon, shred's strip/rectangle) */}
			{patternOptions && (
				<div className='space-y-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.pattern')}</span>
					<div className='flex gap-1'>
						{patternOptions.map((pattern) => (
							<button
								key={pattern}
								type='button'
								disabled={!canEdit}
								onClick={() => onTransitionChange({ pattern })}
								className={`px-2 py-1 rounded text-xs border ${
									(activeSlide.transition?.pattern ?? patternOptions[0]) === pattern
										? 'bg-primary text-white border-primary'
										: 'bg-muted border-border hover:bg-accent'
								}`}
							>
								{t(`pptx.transition.pattern.${pattern}`)}
							</button>
						))}
					</div>
				</div>
			)}

			{/* Through Black */}
			{hasThruBlk && (
				<label className='inline-flex items-center gap-2 text-foreground text-xs'>
					<WebCheckbox
						disabled={!canEdit}
						checked={activeSlide.transition?.thruBlk === true}
						onChange={(e) => onTransitionChange({ thruBlk: e.target.checked })}
					/>
					{t('pptx.transition.thruBlk')}
				</label>
			)}

			{/* Spokes for wheel */}
			{isWheel && (
				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.spokes')}</span>
					<input
						type='number'
						min={MIN_SPOKES}
						max={MAX_SPOKES}
						disabled={!canEdit}
						value={activeSlide.transition?.spokes ?? 4}
						onChange={(e) => {
							const spokes = clampTransitionNumber(Number(e.target.value), MIN_SPOKES, MAX_SPOKES);
							if (spokes !== null) {
								onTransitionChange({ spokes });
							}
						}}
						className='bg-muted border border-border rounded px-2 py-1 text-xs w-16'
					/>
				</label>
			)}

			{/* Duration */}
			<label className='flex flex-col gap-1'>
				<span className='text-muted-foreground text-xs'>{t('pptx.transition.duration')}</span>
				<input
					type='number'
					min={0}
					max={MAX_DURATION_MS}
					disabled={!canEdit}
					aria-label={t('pptx.transition.duration')}
					value={Math.round(activeSlide.transition?.durationMs || DEFAULT_DURATION_MS)}
					onChange={(e) => {
						const durationMs = clampTransitionNumber(Number(e.target.value), 0, MAX_DURATION_MS);
						if (durationMs !== null) {
							onTransitionChange({ durationMs });
						}
					}}
					className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
				/>
			</label>

			{/* Speed */}
			<label className='flex flex-col gap-1'>
				<span className='text-muted-foreground text-xs'>{t('pptx.transition.speed')}</span>
				<WebSelect
					value={activeSlide.transition?.speed ?? 'fast'}
					disabled={!canEdit}
					aria-label={t('pptx.transition.speed')}
					onChange={(e) =>
						onTransitionChange({
							speed: e.target.value as NonNullable<PptxSlideTransition['speed']>,
						})
					}
					className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
				>
					{TRANSITION_SPEED_OPTIONS.map((option) => (
						<option key={option.value} value={option.value}>
							{t(option.i18nKey)}
						</option>
					))}
				</WebSelect>
			</label>

			{/* Morph granularity */}
			{isMorph && (
				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground text-xs'>{t('pptx.transition.morphOption')}</span>
					<WebSelect
						value={activeSlide.transition?.morphOption ?? 'byObject'}
						disabled={!canEdit}
						aria-label={t('pptx.transition.morphOption')}
						onChange={(e) =>
							onTransitionChange({
								morphOption: e.target.value as NonNullable<PptxSlideTransition['morphOption']>,
							})
						}
						className='bg-muted border border-border rounded px-2 py-1 max-md:min-h-[44px]!'
					>
						{TRANSITION_MORPH_OPTIONS.map((option) => (
							<option key={option.value} value={option.value}>
								{t(option.i18nKey)}
							</option>
						))}
					</WebSelect>
				</label>
			)}

			{/* Advance on click */}
			<label className='inline-flex items-center gap-2 text-foreground text-xs'>
				<WebCheckbox
					disabled={!canEdit}
					checked={activeSlide.transition?.advanceOnClick !== false}
					onChange={(e) => onTransitionChange({ advanceOnClick: e.target.checked })}
				/>
				{t('pptx.transition.advanceOnClick')}
			</label>

			{/* Sound */}
			{activeSlide.transition?.soundFileName && (
				<div className='flex items-center gap-1 text-xs text-muted-foreground'>
					<span className='text-muted-foreground'>{t('pptx.transition.sound')}:</span>
					<span className='text-foreground truncate' title={activeSlide.transition.soundFileName}>
						{activeSlide.transition.soundFileName}
					</span>
				</div>
			)}

			{/* Preview */}
			{activeSlide.transition && <TransitionPreview transition={activeSlide.transition} />}
		</div>
	);
}

// viewers/pptx/packages/svelte/src/viewer/components/inspector/SlideTransitionSection.svelte
<script lang="ts">
	/**
	 * SlideTransitionSection: the active slide's transition settings, mirroring
	 * React's `inspector/SlideTransitionSection.tsx` (reached there through
	 * `SlideProperties`, here through the no-selection Properties tab).
	 *
	 * WHY the conditional controls: OOXML overloads a transition's `dir`
	 * attribute. Most types take a compass token, the blinds/checker/comb/
	 * randomBar family takes `horz`/`vert`, and `wheel` takes a spoke count
	 * instead. `TRANSITION_VALID_DIRECTIONS` (core) and
	 * `TRANSITION_ORIENTATION_TYPES` (shared) decide which control applies, so
	 * the panel never offers a direction PowerPoint would drop on save.
	 *
	 * Every edit is a partial merge onto the slide's existing transition and
	 * goes through `EditorState.commitSlides`, so it is undoable and lands on
	 * the same `PptxSlide.transition` the presentation playback reads.
	 */
	import type { PptxSlideTransition, PptxTransitionType } from 'pptx-viewer-core';
	import {
		TRANSITION_PATTERN_OPTIONS,
		TRANSITION_THRUBLK_TYPES,
		TRANSITION_VALID_DIRECTIONS,
	} from 'pptx-viewer-core';
	import {
		SLIDE_TRANSITION_OPTIONS,
		TRANSITION_MORPH_OPTIONS,
		TRANSITION_ORIENTATION_TYPES,
		TRANSITION_SPEED_OPTIONS,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';
	import type { EditorState } from '../../editor/editor-state.svelte';
	import TransitionDirectionPicker from './TransitionDirectionPicker.svelte';
	import TransitionPreview from './TransitionPreview.svelte';

	const { editor }: { editor: EditorState } = $props();
	const t = useTranslator();

	const activeSlide = $derived(editor.slides[editor.currentSlideIndex]);
	const transition = $derived(activeSlide?.transition);
	const transitionType = $derived<PptxTransitionType>(transition?.type ?? 'none');
	const validDirections = $derived(TRANSITION_VALID_DIRECTIONS[transitionType]);
	const usesOrientation = $derived(TRANSITION_ORIENTATION_TYPES.has(transitionType));
	const hasDirections = $derived(
		!usesOrientation && validDirections !== undefined && validDirections.length > 0,
	);
	const patternOptions = $derived(TRANSITION_PATTERN_OPTIONS[transitionType]);
	const hasThruBlk = $derived(TRANSITION_THRUBLK_TYPES.has(transitionType));
	const isWheel = $derived(transitionType === 'wheel');
	const isMorph = $derived(transitionType === 'morph');
	const canEdit = $derived(editor.editable);

	/** Merge a partial change onto the active slide's transition (undoable). */
	function patch(updates: Partial<PptxSlideTransition>): void {
		const index = editor.currentSlideIndex;
		const slide = editor.slides[index];
		if (!slide) {
			return;
		}
		const next: PptxSlideTransition = { type: 'none', ...slide.transition, ...updates };
		editor.commitSlides(editor.slides.map((s, i) => (i === index ? { ...s, transition: next } : s)));
	}

	function commitNumber(raw: string, min: number, max: number, apply: (value: number) => void): void {
		const value = Number(raw);
		if (Number.isFinite(value)) {
			apply(Math.max(min, Math.min(max, Math.round(value))));
		}
	}
</script>

{#if activeSlide}
	<div class="pptx-svelte-transition-fields">
		<label>
			<span>{t('pptx.transition.type')}</span>
			<pptx-ui-select
				aria-label={t('pptx.transition.type')}
				disabled={!canEdit}
				value={transitionType}
				onchange={(event) =>
					patch({ type: event.currentTarget.value as NonNullable<PptxSlideTransition['type']> })}
			>
				{#each SLIDE_TRANSITION_OPTIONS as option (option.value)}
					<option value={option.value}>{t(option.i18nKey)}</option>
				{/each}
			</pptx-ui-select>
		</label>

		{#if hasDirections && validDirections}
			<div class="pptx-svelte-transition-field">
				<span>{t('pptx.transition.direction')}</span>
				<TransitionDirectionPicker
					directions={validDirections}
					value={transition?.direction}
					onchange={(direction) => patch({ direction })}
				/>
			</div>
		{/if}

		{#if usesOrientation}
			<div class="pptx-svelte-transition-field">
				<span>{t('pptx.transition.orientation')}</span>
				<div class="pptx-svelte-transition-orient">
					{#each ['horz', 'vert'] as const as orient (orient)}
						<button
							type="button"
							disabled={!canEdit}
							aria-pressed={(transition?.orient ?? 'horz') === orient}
							class:pptx-svelte-transition-orient-active={(transition?.orient ?? 'horz') === orient}
							onclick={() => patch({ orient })}
						>
							{t(
								orient === 'horz'
									? 'pptx.slideInspector.horizontal'
									: 'pptx.slideInspector.vertical',
							)}
						</button>
					{/each}
				</div>
			</div>
		{/if}

		{#if patternOptions}
			<div class="pptx-svelte-transition-field">
				<span>{t('pptx.transition.pattern')}</span>
				<div class="pptx-svelte-transition-orient">
					{#each patternOptions as pattern (pattern)}
						<button
							type="button"
							disabled={!canEdit}
							aria-pressed={(transition?.pattern ?? patternOptions[0]) === pattern}
							class:pptx-svelte-transition-orient-active={(transition?.pattern ??
								patternOptions[0]) === pattern}
							onclick={() => patch({ pattern })}
						>
							{t(`pptx.transition.pattern.${pattern}`)}
						</button>
					{/each}
				</div>
			</div>
		{/if}

		{#if hasThruBlk}
			<label class="pptx-svelte-transition-check">
				<pptx-ui-checkbox
					disabled={!canEdit}
					checked={transition?.thruBlk === true}
					onchange={(event) => patch({ thruBlk: event.currentTarget.checked })}
				></pptx-ui-checkbox>
				<span>{t('pptx.transition.thruBlk')}</span>
			</label>
		{/if}

		{#if isWheel}
			<label>
				<span>{t('pptx.transition.spokes')}</span>
				<input
					type="number"
					min="1"
					max="8"
					disabled={!canEdit}
					value={transition?.spokes ?? 4}
					onchange={(event) =>
						commitNumber(event.currentTarget.value, 1, 8, (spokes) => patch({ spokes }))}
				/>
			</label>
		{/if}

		<label>
			<span>{t('pptx.transition.duration')}</span>
			<input
				type="number"
				min="0"
				max="10000"
				disabled={!canEdit}
				value={Math.round(transition?.durationMs || 320)}
				onchange={(event) =>
					commitNumber(event.currentTarget.value, 0, 10000, (durationMs) => patch({ durationMs }))}
			/>
		</label>

		<label>
			<span>{t('pptx.transition.speed')}</span>
			<pptx-ui-select
				aria-label={t('pptx.transition.speed')}
				disabled={!canEdit}
				value={transition?.speed ?? 'fast'}
				onchange={(event) =>
					patch({ speed: event.currentTarget.value as NonNullable<PptxSlideTransition['speed']> })}
			>
				{#each TRANSITION_SPEED_OPTIONS as option (option.value)}
					<option value={option.value}>{t(option.i18nKey)}</option>
				{/each}
			</pptx-ui-select>
		</label>

		{#if isMorph}
			<label>
				<span>{t('pptx.transition.morphOption')}</span>
				<pptx-ui-select
					aria-label={t('pptx.transition.morphOption')}
					disabled={!canEdit}
					value={transition?.morphOption ?? 'byObject'}
					onchange={(event) =>
						patch({
							morphOption: event.currentTarget.value as NonNullable<
								PptxSlideTransition['morphOption']
							>,
						})}
				>
					{#each TRANSITION_MORPH_OPTIONS as option (option.value)}
						<option value={option.value}>{t(option.i18nKey)}</option>
					{/each}
				</pptx-ui-select>
			</label>
		{/if}

		<label class="pptx-svelte-transition-check">
			<pptx-ui-checkbox
				disabled={!canEdit}
				checked={transition?.advanceOnClick !== false}
				onchange={(event) => patch({ advanceOnClick: event.currentTarget.checked })}
			></pptx-ui-checkbox>
			<span>{t('pptx.transition.advanceOnClick')}</span>
		</label>

		{#if transition?.soundFileName}
			<p class="pptx-svelte-transition-sound">
				<span>{t('pptx.transition.sound')}:</span>
				<b title={transition.soundFileName}>{transition.soundFileName}</b>
			</p>
		{/if}

		{#if transition}
			<TransitionPreview {transition} />
		{/if}
	</div>
{/if}

<style>
	.pptx-svelte-transition-fields {
		display: grid;
		gap: 8px;
	}

	label,
	.pptx-svelte-transition-field {
		display: grid;
		gap: 3px;
	}

	label > span,
	.pptx-svelte-transition-field > span {
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	select,
	input[type='number'] {
		width: 100%;
		min-width: 0;
		height: 26px;
		box-sizing: border-box;
		padding: 0 6px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b);
		color: inherit;
		font: inherit;
	}

	.pptx-svelte-transition-orient {
		display: flex;
		gap: 4px;
	}

	.pptx-svelte-transition-orient button {
		padding: 3px 8px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 4px;
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		font: inherit;
		cursor: pointer;
	}

	.pptx-svelte-transition-orient-active {
		background: var(--pptx-primary, #6366f1);
		border-color: var(--pptx-primary, #6366f1);
		color: #fff;
	}

	.pptx-svelte-transition-check {
		display: flex;
		align-items: center;
		gap: 6px;
	}

	.pptx-svelte-transition-check input {
		width: auto;
	}

	.pptx-svelte-transition-sound {
		margin: 0;
		overflow: hidden;
		color: var(--pptx-muted-foreground, #94a3b8);
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.pptx-svelte-transition-sound b {
		color: var(--pptx-card-foreground, #e2e8f0);
		font-weight: 500;
	}
</style>
