// viewers/pptx/packages/react/src/viewer/components/inspector/SlideSizeRescalePrompt.tsx
import type { SlideSizeRescaleMode } from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';

/**
 * SlideSizeRescalePrompt: PowerPoint's Maximize/Ensure Fit choice, shown by
 * `SlideSizeCard` when a picked preset/orientation size differs from the
 * current one and the deck has content to rescale. Confirming either applies
 * the shared `scaleSlidesForSizeChange` transform (via the caller) together
 * with the size change.
 */
export interface SlideSizeRescalePromptProps {
	onChoose: (mode: SlideSizeRescaleMode) => void;
}

export function SlideSizeRescalePrompt({
	onChoose,
}: SlideSizeRescalePromptProps): React.ReactElement {
	const { t } = useTranslation();

	return (
		<div className='space-y-1.5 rounded border border-border bg-muted/40 p-2 text-[11px]'>
			<div className='font-medium'>{t('pptx.slideSize.rescaleTitle')}</div>
			<div className='text-muted-foreground'>{t('pptx.slideSize.rescaleDescription')}</div>
			<div className='grid grid-cols-2 gap-1.5 pt-1'>
				<button
					type='button'
					data-testid='pptx-slide-size-rescale-maximize'
					title={t('pptx.slideSize.rescaleMaximizeHint')}
					className='rounded bg-primary px-2 py-1 text-primary-foreground transition-colors hover:opacity-90'
					onClick={() => onChoose('maximize')}
				>
					{t('pptx.slideSize.rescaleMaximize')}
				</button>
				<button
					type='button'
					data-testid='pptx-slide-size-rescale-ensure-fit'
					title={t('pptx.slideSize.rescaleEnsureFitHint')}
					className='rounded bg-muted px-2 py-1 transition-colors hover:bg-accent'
					onClick={() => onChoose('ensureFit')}
				>
					{t('pptx.slideSize.rescaleEnsureFit')}
				</button>
			</div>
		</div>
	);
}

// viewers/pptx/packages/svelte/src/viewer/components/inspector/SlideSizeRescalePrompt.svelte
<script lang="ts">
	/**
	 * SlideSizeRescalePrompt: PowerPoint's Maximize/Ensure Fit choice, shown by
	 * `SlideSizeSection` when a picked preset/orientation size differs from the
	 * current one and the deck has content to rescale. Svelte port of React's
	 * `SlideSizeRescalePrompt`. Confirming either applies the shared
	 * `scaleSlidesForSizeChange` transform (via the caller) together with the
	 * size change, as one undo step.
	 */
	import type { SlideSizeRescaleMode } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';

	const { onchoose }: { onchoose: (mode: SlideSizeRescaleMode) => void } = $props();
	const t = useTranslator();
</script>

<div class="pptx-svelte-slide-size-rescale" data-testid="pptx-slide-size-rescale-prompt">
	<div class="title">{t('pptx.slideSize.rescaleTitle')}</div>
	<div class="description">{t('pptx.slideSize.rescaleDescription')}</div>
	<div class="choices">
		<button
			type="button"
			data-testid="pptx-slide-size-rescale-maximize"
			title={t('pptx.slideSize.rescaleMaximizeHint')}
			class="maximize"
			onclick={() => onchoose('maximize')}
		>
			{t('pptx.slideSize.rescaleMaximize')}
		</button>
		<button
			type="button"
			data-testid="pptx-slide-size-rescale-ensure-fit"
			title={t('pptx.slideSize.rescaleEnsureFitHint')}
			class="ensure-fit"
			onclick={() => onchoose('ensureFit')}
		>
			{t('pptx.slideSize.rescaleEnsureFit')}
		</button>
	</div>
</div>

<style>
	.pptx-svelte-slide-size-rescale {
		display: grid;
		gap: 4px;
		margin-top: 8px;
		padding: 6px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 6px;
		background: var(--pptx-muted, #2a2a3d);
		font-size: 11px;
	}
	.title {
		font-weight: 600;
	}
	.description {
		color: var(--pptx-muted-foreground, #94a3b8);
	}
	.choices {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 6px;
		padding-top: 4px;
	}
	.choices button {
		height: 25px;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 5px;
		color: inherit;
		font-size: 11px;
	}
	.maximize {
		background: var(--pptx-primary, #c43b32);
		color: #fff;
	}
	.ensure-fit {
		background: var(--pptx-background, #11111b);
	}
</style>
