// viewers/pptx/packages/angular/src/viewer/table-style-editor.component.ts
/**
 * table-style-editor.component.ts: "Edit style..." panel for a table style's
 * own DEFINITION (`a:tblStyleLst` section fill/text/borders/cell3D), distinct
 * from `TablePropertiesComponent`'s "which style does this table use" picker.
 * Angular port of React's `TableStyleEditor.tsx` / Vue's `TableStyleEditor.vue`.
 *
 * @module viewer/table-style-editor
 */
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import type { ParsedTableStyleMap } from 'pptx-viewer-core';
import {
	addTableStyleToMap,
	createTableStyleEntry,
	deleteTableStyleFromMap,
	normalizeTableStyleGuid,
} from 'pptx-viewer-core';

import type { TableStyleEditorFieldEdit, TableStyleEditorPartId } from 'ooxml-ui/pptx';
import {
	applyTableStyleFieldEdit,
	describeTableStyleEditor,
	TABLE_STYLE_EDITOR_PARTS,
} from 'ooxml-ui/pptx';
import { LoadContentService } from './load-content.service';
import { TableStyleEditorFieldsComponent } from './table-style-editor-fields.component';

@Component({
	selector: 'pptx-table-style-editor',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe, TableStyleEditorFieldsComponent],
	template: `
		<div class="pptx-tse" data-testid="table-style-editor">
			<div class="pptx-tse__hdr">
				<div class="pptx-tse__hdg">{{ 'pptx.tableStyleEditor.title' | translate }}</div>
				<button type="button" class="pptx-tse__btn" (click)="close.emit()">
					{{ 'pptx.tableStyleEditor.close' | translate }}
				</button>
			</div>

			@if (!entry()) {
				<div class="pptx-tse__empty">{{ 'pptx.tableStyleEditor.noStyleSelected' | translate }}</div>
			}

			@if (entry()) {
				<div class="pptx-tse__parts">
					@for (part of parts; track part.id) {
						<button
							type="button"
							class="pptx-tse__btn"
							[class.pptx-tse__btn--active]="selectedPart() === part.id"
							[disabled]="!canEdit()"
							(click)="selectedPart.set(part.id)"
						>
							{{ part.labelKey | translate }}
						</button>
					}
				</div>
			}

			@if (descriptor(); as d) {
				<pptx-table-style-editor-fields
					[descriptor]="d"
					[canEdit]="canEdit()"
					(edit)="onFieldEdit($event)"
				/>
			}

			<div class="pptx-tse__actions">
				<button
					type="button"
					class="pptx-tse__btn"
					[disabled]="!canEdit()"
					(click)="createFromCurrent()"
				>
					{{
						(entry() ? 'pptx.tableStyleEditor.newFromCurrent' : 'pptx.tableStyleEditor.newStyle')
							| translate
					}}
				</button>
				@if (entry()) {
					<button
						type="button"
						class="pptx-tse__btn"
						[disabled]="!canEdit()"
						(click)="handleDelete()"
					>
						{{ 'pptx.tableStyleEditor.deleteStyle' | translate }}
					</button>
				}
			</div>
		</div>
	`,
	styles: `
		.pptx-tse {
			display: flex;
			flex-direction: column;
			gap: 0.5rem;
			border: 1px solid var(--pptx-inspector-border, #444);
			border-radius: 4px;
			padding: 0.5rem;
		}
		.pptx-tse__hdr {
			display: flex;
			align-items: center;
			justify-content: space-between;
		}
		.pptx-tse__hdg {
			font-size: 11px;
			text-transform: uppercase;
			letter-spacing: 0.03em;
			color: var(--pptx-inspector-muted, #888);
		}
		.pptx-tse__empty {
			font-size: 11px;
			color: var(--pptx-inspector-muted, #888);
		}
		.pptx-tse__parts {
			display: flex;
			flex-wrap: wrap;
			gap: 0.25rem;
		}
		.pptx-tse__actions {
			display: flex;
			gap: 0.4rem;
			padding-top: 0.25rem;
			border-top: 1px solid var(--pptx-inspector-border, #444);
		}
		.pptx-tse__btn {
			font-size: 11px;
			background: var(--pptx-inspector-input-bg, #2d2d2d);
			border: 1px solid var(--pptx-inspector-border, #444);
			color: inherit;
			border-radius: 3px;
			padding: 2px 6px;
			cursor: pointer;
		}
		.pptx-tse__btn--active {
			background: var(--pptx-inspector-active, #3a3a3a);
		}
		.pptx-tse__btn:disabled {
			opacity: 0.4;
			cursor: not-allowed;
		}
	`,
})
export class TableStyleEditorComponent {
	readonly styleMap = input<ParsedTableStyleMap | undefined>(undefined);
	/** The style currently assigned to the table being edited. */
	readonly styleId = input<string | undefined>(undefined);
	readonly canEdit = input<boolean>(true);
	/** Commit a full replacement style map (section edit, create, or delete already applied). */
	readonly styleMapChange = output<ParsedTableStyleMap>();
	/** Record a styleId for save-time removal from `ppt/tableStyles.xml`. */
	readonly deleteStyle = output<string>();
	/** A newly-created style, for a parent that wants to assign it to the table. */
	readonly assignStyle = output<string>();
	readonly close = output<void>();

	private readonly translate = inject(TranslateService);
	private readonly loader = inject(LoadContentService, { optional: true });

	protected readonly parts = TABLE_STYLE_EDITOR_PARTS;
	protected readonly selectedPart = signal<TableStyleEditorPartId>('wholeTbl');
	private readonly activeStyleId = signal('');

	protected readonly entry = computed(() => {
		const id =
			this.activeStyleId() || (this.styleId() ? normalizeTableStyleGuid(this.styleId()!) : '');
		return id ? this.styleMap()?.[id] : undefined;
	});
	protected readonly descriptor = computed(() =>
		describeTableStyleEditor(this.entry(), this.selectedPart(), this.loader?.themeColorMap?.()),
	);

	protected onFieldEdit(fieldEdit: TableStyleEditorFieldEdit): void {
		const entry = this.entry();
		const map = this.styleMap();
		if (!entry || !map) {
			return;
		}
		const { entry: nextEntry } = applyTableStyleFieldEdit(entry, this.selectedPart(), fieldEdit);
		this.styleMapChange.emit({ ...map, [nextEntry.styleId]: nextEntry });
	}

	protected createFromCurrent(): void {
		const entry = this.entry();
		const name = window.prompt(
			this.translate.instant('pptx.tableStyleEditor.newStyleNamePrompt'),
			entry ? `${entry.styleName ?? ''} Copy`.trim() : '',
		);
		if (!name) {
			return;
		}
		const nextMap: ParsedTableStyleMap = { ...(this.styleMap() ?? {}) };
		const created = createTableStyleEntry(nextMap, { styleName: name, basedOn: entry });
		addTableStyleToMap(nextMap, created);
		this.styleMapChange.emit(nextMap);
		this.activeStyleId.set(created.styleId);
		this.assignStyle.emit(created.styleId);
	}

	protected handleDelete(): void {
		const entry = this.entry();
		const map = this.styleMap();
		if (
			!entry ||
			!map ||
			!window.confirm(this.translate.instant('pptx.tableStyleEditor.deleteConfirm'))
		) {
			return;
		}
		const nextMap: ParsedTableStyleMap = { ...map };
		deleteTableStyleFromMap(nextMap, entry.styleId);
		this.styleMapChange.emit(nextMap);
		this.deleteStyle.emit(entry.styleId);
		this.close.emit();
	}
}

// viewers/pptx/packages/svelte/src/viewer/components/inspector/TableStyleEditor.svelte
<script lang="ts">
	/**
	 * "Edit style..." panel for a table style's own DEFINITION
	 * (`a:tblStyleLst` section fill/text/borders/cell3D), distinct from
	 * `TableSection.svelte`'s "which style does this table use" picker.
	 * Svelte port of React's `TableStyleEditor.tsx` / Vue's
	 * `TableStyleEditor.vue`.
	 */
	import type { ParsedTableStyleMap } from 'pptx-viewer-core';
	import {
		addTableStyleToMap,
		createTableStyleEntry,
		deleteTableStyleFromMap,
		normalizeTableStyleGuid,
	} from 'pptx-viewer-core';
	import type { TableStyleEditorFieldEdit, TableStyleEditorPartId } from 'ooxml-ui/pptx';
	import { applyTableStyleFieldEdit, describeTableStyleEditor, TABLE_STYLE_EDITOR_PARTS } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';
	import TableStyleEditorFields from './TableStyleEditorFields.svelte';

	const {
		styleMap,
		styleId,
		themeColorMap,
		canEdit = true,
		onStyleMapChange,
		onDeleteStyle,
		onAssignStyle,
		onClose,
	}: {
		styleMap: ParsedTableStyleMap | undefined;
		/** The style currently assigned to the table being edited. */
		styleId: string | undefined;
		themeColorMap: Record<string, string> | undefined;
		canEdit?: boolean;
		/** Commit a full replacement style map (section edit, create, or delete already applied). */
		onStyleMapChange: (nextMap: ParsedTableStyleMap) => void;
		/** Record a styleId for save-time removal from `ppt/tableStyles.xml`. */
		onDeleteStyle: (styleId: string) => void;
		/** Optional: assign a newly-created style to the table being edited. */
		onAssignStyle?: (styleId: string) => void;
		onClose: () => void;
	} = $props();

	const t = useTranslator();
	// eslint-disable-next-line prefer-const
	let activeStyleId = $state(styleId ? normalizeTableStyleGuid(styleId) : '');
	// eslint-disable-next-line prefer-const
	let selectedPart = $state<TableStyleEditorPartId>('wholeTbl');

	const entry = $derived(activeStyleId ? styleMap?.[activeStyleId] : undefined);
	const descriptor = $derived(describeTableStyleEditor(entry, selectedPart, themeColorMap));

	function onFieldEdit(fieldEdit: TableStyleEditorFieldEdit): void {
		if (!entry || !styleMap) {
			return;
		}
		const { entry: nextEntry } = applyTableStyleFieldEdit(entry, selectedPart, fieldEdit);
		onStyleMapChange({ ...styleMap, [nextEntry.styleId]: nextEntry });
	}

	function createFromCurrent(): void {
		const name = window.prompt(
			t('pptx.tableStyleEditor.newStyleNamePrompt'),
			entry ? `${entry.styleName ?? ''} Copy`.trim() : '',
		);
		if (!name) {
			return;
		}
		const nextMap: ParsedTableStyleMap = { ...(styleMap ?? {}) };
		const created = createTableStyleEntry(nextMap, { styleName: name, basedOn: entry });
		addTableStyleToMap(nextMap, created);
		onStyleMapChange(nextMap);
		activeStyleId = created.styleId;
		onAssignStyle?.(created.styleId);
	}

	function handleDelete(): void {
		if (!entry || !styleMap || !window.confirm(t('pptx.tableStyleEditor.deleteConfirm'))) {
			return;
		}
		const nextMap: ParsedTableStyleMap = { ...styleMap };
		deleteTableStyleFromMap(nextMap, entry.styleId);
		onStyleMapChange(nextMap);
		onDeleteStyle(entry.styleId);
		onClose();
	}
</script>

<div class="editor" data-testid="table-style-editor">
	<div class="hdr">
		<span class="hdg">{t('pptx.tableStyleEditor.title')}</span>
		<button type="button" onclick={onClose}>{t('pptx.tableStyleEditor.close')}</button>
	</div>

	{#if !entry}
		<div class="empty">{t('pptx.tableStyleEditor.noStyleSelected')}</div>
	{/if}

	{#if entry}
		<div class="parts">
			{#each TABLE_STYLE_EDITOR_PARTS as part (part.id)}
				<button type="button" class:active={selectedPart === part.id} disabled={!canEdit} onclick={() => (selectedPart = part.id)}>{t(part.labelKey)}</button>
			{/each}
		</div>
	{/if}

	{#if descriptor}
		<TableStyleEditorFields {descriptor} {themeColorMap} {canEdit} onedit={onFieldEdit} />
	{/if}

	<div class="actions">
		<button type="button" disabled={!canEdit} onclick={createFromCurrent}>{entry ? t('pptx.tableStyleEditor.newFromCurrent') : t('pptx.tableStyleEditor.newStyle')}</button>
		{#if entry}
			<button type="button" disabled={!canEdit} onclick={handleDelete}>{t('pptx.tableStyleEditor.deleteStyle')}</button>
		{/if}
	</div>
</div>

<style>
	.editor { display: flex; flex-direction: column; gap: 8px; border: 1px solid var(--pptx-border); border-radius: 5px; padding: 8px; }
	.hdr { display: flex; align-items: center; justify-content: space-between; }
	.hdg { font-size: 11px; text-transform: uppercase; letter-spacing: 0.03em; color: var(--pptx-muted-foreground); }
	.empty { font-size: 11px; color: var(--pptx-muted-foreground); }
	.parts { display: flex; flex-wrap: wrap; gap: 4px; }
	.actions { display: flex; gap: 6px; padding-top: 4px; border-top: 1px solid var(--pptx-border); }
	button { font-size: 11px; border: 1px solid var(--pptx-border); border-radius: 4px; padding: 3px 6px; background: var(--pptx-muted); color: inherit; cursor: pointer; }
	button.active { background: var(--pptx-primary, #c43b32); color: #fff; }
	button:disabled { opacity: 0.4; cursor: not-allowed; }
</style>
