// viewers/pptx/packages/svelte/src/viewer/components/inspector/ActionSettingsPanel.svelte
<script lang="ts">
	/**
	 * ActionSettingsPanel: PowerPoint's Insert > Action dialog as an inspector
	 * card, mirroring React's `inspector/ActionSettingsPanel.tsx`.
	 *
	 * An element can carry two independent actions, one per trigger, stored as
	 * `actionClick` / `actionHover` (`PptxAction`). The friendlier
	 * `ElementAction` shape the UI edits is converted both ways by core's
	 * `pptxActionToElementAction` / `elementActionToPptxAction`, so this panel
	 * never hand-rolls the OOXML `ppaction://` string, and the option catalogue
	 * plus the 1-based to 0-based slide-number clamp come from
	 * `pptx-viewer-shared` (`ELEMENT_ACTION_TYPE_OPTIONS` / `toSlideIndex`).
	 *
	 * Both triggers share {@link ActionTriggerFields}, so the extra URL / slide
	 * input only exists for the two types that need it.
	 */
	import type { ElementAction, ElementActionType, PptxElement } from 'pptx-viewer-core';
	import { elementActionToPptxAction, pptxActionToElementAction } from 'pptx-viewer-core';
	import { canCommitActionType } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';
	import type { EditorState } from '../../editor/editor-state.svelte';
	import ActionTriggerFields from './ActionTriggerFields.svelte';

	const { editor, el }: { editor: EditorState; el: PptxElement } = $props();
	const t = useTranslator();

	const canEdit = $derived(editor.editable);
	const slideCount = $derived(editor.slides.length);
	const customShows = $derived(editor.customShows);
	const clickAction = $derived<ElementAction | undefined>(
		el.actionClick ? pptxActionToElementAction(el.actionClick, 'click') : undefined,
	);
	const hoverAction = $derived<ElementAction | undefined>(
		el.actionHover ? pptxActionToElementAction(el.actionHover, 'hover') : undefined,
	);

	/** Write one trigger's FULL action back onto the element (history-integrated). */
	function updateAction(trigger: 'click' | 'hover', action: Omit<ElementAction, 'trigger'>): void {
		const pptxAction = elementActionToPptxAction({ trigger, ...action });
		editor.applyElementPatch(
			el.id,
			(trigger === 'click' ? { actionClick: pptxAction } : { actionHover: pptxAction }) as Partial<
				PptxElement
			>,
		);
	}

	/**
	 * Write a picked type back only once it carries its target.
	 *
	 * A target-less `url` / `slide` / `customShow` action serialises to an
	 * action that parses straight back as `none` (or, for `customShow`, one
	 * naming no show), so committing one would wipe the choice the user is
	 * halfway through making; the fields keep showing the pick until the
	 * target arrives (shared `canCommitActionType`).
	 */
	function chooseType(trigger: 'click' | 'hover', type: ElementActionType): void {
		const current = trigger === 'click' ? clickAction : hoverAction;
		const action = { ...current, type };
		if (canCommitActionType(type, action)) {
			updateAction(trigger, action);
		}
	}

	/**
	 * A target field changed (URL, slide number, custom show, return-after):
	 * `patch` always carries the type the field belongs to (the trigger
	 * fields' own `effectiveType`, which may still be only PENDING), so this
	 * commits under the SAME gate as a fresh type pick rather than the type
	 * last actually written to the element.
	 */
	function changeTarget(trigger: 'click' | 'hover', patch: Partial<ElementAction>): void {
		const current = trigger === 'click' ? clickAction : hoverAction;
		const action = { ...current, ...patch, type: patch.type ?? current?.type ?? 'none' };
		if (canCommitActionType(action.type, action)) {
			updateAction(trigger, action);
		}
	}
</script>

<!-- Keyed on the element so a half-made pick does not follow the inspector to
     the next shape, which never had it. -->
{#key el.id}
	<div class="pptx-svelte-action-settings">
		<ActionTriggerFields
			label={t('pptx.action.onClick')}
			activeType={clickAction?.type ?? 'none'}
			url={clickAction?.url ?? el.actionClick?.url ?? ''}
			slideIndex={clickAction?.slideIndex ?? el.actionClick?.targetSlideIndex ?? 0}
			customShowId={clickAction?.customShowId ?? ''}
			returnAfter={clickAction?.returnAfter ?? false}
			{customShows}
			{canEdit}
			{slideCount}
			onchangetype={(type) => chooseType('click', type)}
			onchangetarget={(patch) => changeTarget('click', patch)}
		/>
		<ActionTriggerFields
			label={t('pptx.action.onHover')}
			activeType={hoverAction?.type ?? 'none'}
			url={hoverAction?.url ?? el.actionHover?.url ?? ''}
			slideIndex={hoverAction?.slideIndex ?? el.actionHover?.targetSlideIndex ?? 0}
			customShowId={hoverAction?.customShowId ?? ''}
			returnAfter={hoverAction?.returnAfter ?? false}
			{customShows}
			{canEdit}
			{slideCount}
			onchangetype={(type) => chooseType('hover', type)}
			onchangetarget={(patch) => changeTarget('hover', patch)}
		/>
	</div>
{/key}

<style>
	.pptx-svelte-action-settings {
		display: grid;
		gap: 10px;
	}
</style>

// viewers/pptx/packages/react/src/viewer/components/inspector/ActionSettingsPanel.tsx
/**
 * ActionSettingsPanel: PowerPoint's Insert > Action dialog as an inspector card.
 *
 * An element carries two independent actions, one per trigger (`actionClick` /
 * `actionHover`), stored as the OOXML-shaped `PptxAction`; core's
 * `pptxActionToElementAction` / `elementActionToPptxAction` convert both ways so
 * this panel never hand-rolls a `ppaction://` URI. The option catalogue, the
 * pending-type rule, the commit gate and the 1-based to 0-based slide-number
 * clamp all come from `pptx-viewer-shared`, so the five bindings cannot drift on
 * behaviour that is not a rendering decision.
 */
import type { PptxElement, PptxSlide, ElementAction, ElementActionType } from 'pptx-viewer-core';
import { pptxActionToElementAction, elementActionToPptxAction } from 'pptx-viewer-core';
import {
	canCommitActionType,
	ELEMENT_ACTION_TYPE_OPTIONS,
	resolveActionType,
} from 'ooxml-ui/pptx';
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { cn } from '../../utils';
import { WebSelect } from '../WebControls';
import { ActionTargetFields } from './ActionTargetFields';
import { CARD, HEADING, INPUT } from './inspector-pane-constants';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface ActionSettingsPanelProps {
	selectedElement: PptxElement;
	slides: PptxSlide[];
	canEdit: boolean;
	/** `data.customShows`, for the `customShow` target picker. */
	customShows: Array<{ id: string; name: string }>;
	onUpdateElement: (updates: Partial<PptxElement>) => void;
}

/** The action target fields, beyond `type`, that `updateAction` can write. */
export interface ActionTargetPatch {
	url?: string;
	slideIndex?: number;
	customShowId?: string;
	returnAfter?: boolean;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function ActionSettingsPanel({
	selectedElement,
	slides,
	canEdit,
	customShows,
	onUpdateElement,
}: ActionSettingsPanelProps): React.ReactElement {
	const { t } = useTranslation();

	const clickAction: ElementAction | undefined = selectedElement.actionClick
		? pptxActionToElementAction(selectedElement.actionClick, 'click')
		: undefined;

	const hoverAction: ElementAction | undefined = selectedElement.actionHover
		? pptxActionToElementAction(selectedElement.actionHover, 'hover')
		: undefined;

	const updateAction = (
		trigger: 'click' | 'hover',
		type: ElementActionType,
		patch: ActionTargetPatch,
	) => {
		const ea: ElementAction = { trigger, type, ...patch };
		const pa = elementActionToPptxAction(ea);
		if (trigger === 'click') {
			onUpdateElement({ actionClick: pa } as Partial<PptxElement>);
		} else {
			onUpdateElement({ actionHover: pa } as Partial<PptxElement>);
		}
	};

	/**
	 * Commit a picked type only once it can carry a target.
	 *
	 * "Go to URL" / "Go to Slide" / "Custom Show" round-trip back to `none`
	 * while their target is missing, so writing one straight away would stamp
	 * an empty action onto the element (and mark the deck dirty) for a choice
	 * the user has not finished making. The pick still shows, because the
	 * section holds it locally.
	 */
	const changeType = (trigger: 'click' | 'hover', type: ElementActionType) => {
		const current = trigger === 'click' ? clickAction : hoverAction;
		const target: ActionTargetPatch = {
			url: current?.url,
			slideIndex: current?.slideIndex,
			customShowId: current?.customShowId,
		};
		if (canCommitActionType(type, target)) {
			updateAction(trigger, type, target);
		}
	};

	return (
		<div className={CARD} data-pptx-action-settings>
			<div className={HEADING}>{t('pptx.action.title', 'Action')}</div>
			<div className='space-y-2 text-[11px]'>
				{/* On Click */}
				<ActionTriggerSection
					// A pending pick belongs to the element it was made on: re-keying on
					// the element id drops it when the inspector moves on, so the next
					// shape cannot inherit a half-made "Go to URL" it never had.
					key={`click-${selectedElement.id}`}
					label={t('pptx.action.onClick', 'On Click')}
					trigger='click'
					activeType={clickAction?.type}
					action={clickAction}
					fallbackUrl={selectedElement.actionClick?.url}
					fallbackSlideIndex={selectedElement.actionClick?.targetSlideIndex}
					canEdit={canEdit}
					slideCount={slides.length}
					customShows={customShows}
					onChangeType={(type) => changeType('click', type)}
					onChangeTarget={(type, patch) => updateAction('click', type, patch)}
				/>

				{/* On Hover */}
				<ActionTriggerSection
					key={`hover-${selectedElement.id}`}
					label={t('pptx.action.onHover', 'On Hover')}
					trigger='hover'
					activeType={hoverAction?.type}
					action={hoverAction}
					fallbackUrl={selectedElement.actionHover?.url}
					fallbackSlideIndex={selectedElement.actionHover?.targetSlideIndex}
					canEdit={canEdit}
					slideCount={slides.length}
					customShows={customShows}
					onChangeType={(type) => changeType('hover', type)}
					onChangeTarget={(type, patch) => updateAction('hover', type, patch)}
				/>
			</div>
		</div>
	);
}

// ---------------------------------------------------------------------------
// Sub-component: a single trigger block (Click or Hover)
// ---------------------------------------------------------------------------

interface ActionTriggerSectionProps {
	label: string;
	trigger: 'click' | 'hover';
	/** The type read back off the element, if it carries an action at all. */
	activeType: ElementActionType | undefined;
	action: ElementAction | undefined;
	fallbackUrl: string | undefined;
	fallbackSlideIndex: number | undefined;
	canEdit: boolean;
	slideCount: number;
	customShows: Array<{ id: string; name: string }>;
	onChangeType: (type: ElementActionType) => void;
	/** Commits a target-field patch against the EFFECTIVE type (pending or active). */
	onChangeTarget: (type: ElementActionType, patch: ActionTargetPatch) => void;
}

function ActionTriggerSection({
	label,
	trigger,
	activeType,
	action,
	fallbackUrl,
	fallbackSlideIndex,
	canEdit,
	slideCount,
	customShows,
	onChangeType,
	onChangeTarget,
}: ActionTriggerSectionProps): React.ReactElement {
	const { t } = useTranslation();
	// `url` / `slide` / `customShow` only become a stored action once they have
	// a target, so deriving the select purely from the element round-tripped
	// "Go to URL" straight back to "None" and its input never appeared. The
	// locally picked type therefore wins until the element really carries an
	// action.
	const [pendingType, setPendingType] = useState<ElementActionType | undefined>(undefined);
	const effectiveType = resolveActionType(pendingType, activeType);
	const changeType = (type: ElementActionType) => {
		setPendingType(type);
		onChangeType(type);
	};
	return (
		<div className='space-y-1.5' data-pptx-action-trigger={trigger}>
			<span className='text-muted-foreground font-medium'>{label}</span>
			<WebSelect
				disabled={!canEdit}
				aria-label={label}
				className={cn(INPUT, 'w-full')}
				value={effectiveType}
				onChange={(e) => changeType(e.target.value as ElementActionType)}
			>
				{ELEMENT_ACTION_TYPE_OPTIONS.map((o) => (
					<option key={o.value} value={o.value}>
						{t(o.labelKey)}
					</option>
				))}
			</WebSelect>

			<ActionTargetFields
				type={effectiveType}
				canEdit={canEdit}
				slideCount={slideCount}
				customShows={customShows}
				url={action?.url ?? fallbackUrl}
				slideIndex={action?.slideIndex ?? fallbackSlideIndex}
				customShowId={action?.customShowId}
				returnAfter={action?.returnAfter}
				onChange={(patch) => onChangeTarget(effectiveType, patch)}
			/>
		</div>
	);
}
