// viewers/pptx/packages/vue/src/viewer/components/MobileSheet.vue
<script setup lang="ts">
/**
 * MobileSheet - reusable slide-up bottom sheet for the Vue `pptx-vue-viewer`.
 *
 * Vue port of `packages/react/src/viewer/components/mobile/MobileSheet.tsx`:
 *   - a tap-to-close backdrop,
 *   - a rounded-top panel that animates up from the bottom,
 *   - a handle + header that form one swipe-to-dismiss grab region
 *     (drag down past the threshold to close),
 *   - Escape closes the sheet.
 *
 * Visibility is owned by the parent (`v-if="isMobile && open"`); the body is
 * scrollable and sized via dvh so it survives the mobile address-bar collapse.
 */
import { activateModalFocus, MIN_TOUCH_TARGET_PX } from 'ooxml-ui/pptx';
import { nextTick, onBeforeUnmount, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { useSheetDismissDrag } from '../composables/useSheetDismissDrag';

const { t } = useI18n();

const props = defineProps<{ open: boolean; title?: string; inspector?: boolean }>();
const emit = defineEmits<{ close: [] }>();

const { dragY, dragging, onPointerDown, onPointerMove, onPointerUp } = useSheetDismissDrag(() =>
	emit('close'),
);

const panelRef = ref<HTMLElement | null>(null);
let releaseFocus: (() => void) | undefined;
watch(
	() => props.open,
	async (open) => {
		releaseFocus?.();
		releaseFocus = undefined;
		if (open) {
			await nextTick();
			if (panelRef.value) {
				releaseFocus = activateModalFocus(panelRef.value, { onEscape: () => emit('close') });
			}
		}
	},
	{ immediate: true },
);
onBeforeUnmount(() => releaseFocus?.());
</script>

<template>
	<div v-if="open" class="pptx-vue-msheet fixed inset-0 z-[60] flex flex-col justify-end">
		<!-- Backdrop -->
		<button
			type="button"
			:aria-label="t('pptx.settings.close')"
			class="absolute inset-0 border-0 bg-black/40 backdrop-blur-[2px]"
			@click="emit('close')"
		/>

		<!-- Panel -->
		<div
			ref="panelRef"
			class="pptx-vue-msheet-panel relative flex max-h-[85dvh] flex-col rounded-t-2xl border-t border-border bg-card text-foreground shadow-2xl"
			role="dialog"
			aria-modal="true"
			:aria-label="title || t('pptx.mobileSheet.ariaLabel')"
			tabindex="-1"
			:data-pptx-inspector="props.inspector ? '' : undefined"
			:style="{
				transform: dragY > 0 ? `translateY(${dragY}px)` : undefined,
				transition: dragging ? 'none' : 'transform 150ms ease-out',
			}"
		>
			<!-- Handle + header = one swipe-to-dismiss grab region -->
			<div
				class="shrink-0 cursor-grab touch-none select-none active:cursor-grabbing"
				@pointerdown="onPointerDown"
				@pointermove="onPointerMove"
				@pointerup="onPointerUp"
				@pointercancel="onPointerUp"
			>
				<div class="flex items-center justify-center pt-2 pb-1">
					<div class="h-1 w-10 rounded-full bg-muted-foreground/40" />
				</div>
				<div
					v-if="title"
					class="flex items-center justify-between gap-2 border-b border-border/60 px-4 pb-2"
				>
					<span class="truncate text-sm font-semibold text-foreground">{{ title }}</span>
					<button
						type="button"
						class="inline-flex items-center justify-center rounded text-xl text-muted-foreground hover:bg-accent hover:text-foreground"
						:style="{ minWidth: `${MIN_TOUCH_TARGET_PX}px`, minHeight: `${MIN_TOUCH_TARGET_PX}px` }"
						:aria-label="t('pptx.settings.close')"
						@pointerdown.stop
						@click="emit('close')"
					>
						&times;
					</button>
				</div>
			</div>

			<!-- Scrollable body -->
			<div
				class="flex-1 overflow-y-auto overscroll-contain pb-[max(env(safe-area-inset-bottom),0px)]"
			>
				<slot />
			</div>
		</div>
	</div>
</template>

// viewers/pptx/packages/react/src/viewer/components/mobile/MobileSheet.tsx
import { MIN_TOUCH_TARGET_PX } from 'ooxml-ui/pptx';
import React, { useRef } from 'react';
import { useTranslation } from 'react-i18next';

import { useModalFocus } from '../../hooks/useModalFocus';
import { useSheetDismissDrag } from '../../hooks/useSheetDismissDrag';
import { cn } from '../../utils';

export interface MobileSheetProps {
	open: boolean;
	onClose: () => void;
	title?: React.ReactNode;
	children: React.ReactNode;
	/** Initial sheet height as a percentage of viewport (0-1). Default 0.6. */
	heightFraction?: number;
	/** When true, sheet covers full viewport. */
	fullScreen?: boolean;
	/**
	 * When true, the sheet sizes to its content (up to 85dvh, then the body
	 * scrolls). Preferred over `fullScreen` for variable-height content so short
	 * sections don't leave a large empty void below the controls.
	 */
	autoHeight?: boolean;
	className?: string;
	/** Extra header content rendered to the right of the title. */
	headerRight?: React.ReactNode;
}

/**
 * Mobile bottom sheet with a drag handle. Tapping the backdrop or dragging
 * past the dismiss threshold closes it. Uses CSS dvh so it survives the
 * mobile address-bar collapse.
 */
export function MobileSheet({
	open,
	onClose,
	title,
	children,
	heightFraction = 0.6,
	fullScreen = false,
	autoHeight = false,
	className,
	headerRight,
}: MobileSheetProps): React.ReactElement | null {
	const sheetRef = useRef<HTMLDivElement>(null);
	const { t } = useTranslation();
	const { dragY, dragging, handlers } = useSheetDismissDrag(onClose);
	useModalFocus(open, sheetRef, onClose);

	if (!open) {
		return null;
	}

	const heightStyle = autoHeight
		? { maxHeight: 'calc(85dvh - env(safe-area-inset-top))' }
		: fullScreen
			? { height: 'calc(100dvh - env(safe-area-inset-top))' }
			: { height: `${Math.round(heightFraction * 100)}dvh` };

	return (
		<div className='fixed inset-0 z-50 flex flex-col justify-end'>
			{/* Backdrop */}
			<button
				type='button'
				aria-label={t('pptx.mobileSheet.close')}
				className='absolute inset-0 bg-black/40 backdrop-blur-[2px] animate-in fade-in duration-150'
				onClick={onClose}
			/>

			{/* Sheet */}
			<div
				ref={sheetRef}
				role='dialog'
				aria-modal='true'
				aria-label={typeof title === 'string' ? title : t('pptx.mobileSheet.ariaLabel')}
				tabIndex={-1}
				className={cn(
					'relative bg-background border-t border-border rounded-t-2xl shadow-2xl flex flex-col overflow-hidden',
					'animate-in slide-in-from-bottom duration-200',
					className,
				)}
				style={{
					...heightStyle,
					transform: dragY > 0 ? `translateY(${dragY}px)` : undefined,
					transition: dragging ? 'none' : 'transform 150ms ease-out',
				}}
			>
				{/* Drag handle + header form a single swipe-to-dismiss grab region so
				    the gesture isn't limited to the thin pill. */}
				<div
					className='cursor-grab active:cursor-grabbing touch-none'
					onPointerDown={handlers.onPointerDown}
					onPointerMove={handlers.onPointerMove}
					onPointerUp={handlers.onPointerUp}
					onPointerCancel={handlers.onPointerCancel}
				>
					<div className='flex items-center justify-center pt-2 pb-1'>
						<div className='h-1 w-10 rounded-full bg-muted-foreground/40' />
					</div>

					{/* Header */}
					{(title || headerRight) && (
						<div className='flex items-center justify-between gap-2 px-4 pb-2 border-b border-border/60'>
							<div className='text-sm font-semibold text-foreground truncate'>{title}</div>
							{headerRight}
							<button
								type='button'
								aria-label={t('pptx.mobileSheet.close')}
								onPointerDown={(event) => event.stopPropagation()}
								onClick={onClose}
								style={{ minWidth: MIN_TOUCH_TARGET_PX, minHeight: MIN_TOUCH_TARGET_PX }}
								className='inline-flex items-center justify-center rounded text-xl text-muted-foreground hover:bg-accent hover:text-foreground'
							>
								&times;
							</button>
						</div>
					)}
				</div>

				{/* Body */}
				<div className='flex-1 overflow-y-auto overscroll-contain'>{children}</div>
			</div>
		</div>
	);
}
