// viewers/pptx/packages/svelte/src/viewer/components/ai/AiChatPanel.svelte
<script lang="ts">
	/**
	 * AiChatPanel: the right-hand AI assistant pane. Reached ONLY through the
	 * dynamic `{#await import('./components/ai/AiChatPanel.svelte')}` boundary in
	 * `PowerPointViewer.svelte`, so `@ai-sdk/svelte` + the optional `ai` SDK load
	 * lazily when the assistant is first opened.
	 *
	 * The panel owns the {@link SvelteAiChat} runes controller: it bootstraps the
	 * session on mount, guards availability, and lays out the transcript, staged
	 * proposals, an error banner, and the composer.
	 */
	import LoaderCircle from '@lucide/svelte/icons/loader-circle';
	import Sparkles from '@lucide/svelte/icons/sparkles';
	import TriangleAlert from '@lucide/svelte/icons/triangle-alert';
	import X from '@lucide/svelte/icons/x';
	import type { PptxAiBridge, PptxAiConfig, ToolCanvasTarget } from 'ooxml-ui/pptx/ai';
	import { onMount, untrack } from 'svelte';

	import { useTranslator } from '../../../i18n/context';
	import { useAiChatHistory } from '../../ai/ai-chat-history.svelte';
	import type { AiPanelController } from '../../ai/ai-panel-controller.svelte';
	import { SvelteAiChat } from '../../ai/chat.svelte';
	import AiComposer from './AiComposer.svelte';
	import AiErrorBanner from './AiErrorBanner.svelte';
	import AiFocusBar from './AiFocusBar.svelte';
	import AiHistoryMenu from './AiHistoryMenu.svelte';
	import AiMessageList from './AiMessageList.svelte';
	import AiPendingChanges from './AiPendingChanges.svelte';

	const {
		bridge,
		config,
		aiPanel,
		onclose,
	}: {
		bridge: PptxAiBridge;
		config: PptxAiConfig;
		/** On-canvas scope controller (focus targets, picks, live-tool highlight). */
		aiPanel: AiPanelController;
		onclose: () => void;
	} = $props();

	const t = useTranslator();
	// Live "AI as a collaborator" focus: as each tool runs, navigate to and
	// highlight the slide / element(s) it touches so the canvas mirrors the
	// assistant in real time (and colour edits tween while it is active).
	function onToolTarget(target: ToolCanvasTarget | null): void {
		if (target && target.slideIndex !== undefined) {
			bridge.goToSlide(target.slideIndex);
		}
		aiPanel.flashToolTarget(target);
	}
	// The session is built once for the panel's lifetime (the bridge reads live
	// viewer state through getters, and `config` is stable), so capturing the
	// initial prop values here is intentional.
	const chat = untrack(() => new SvelteAiChat({ bridge, config, onToolTarget }));

	// Applied-edit animation: once the session is ready, subscribe to its change
	// animator so that when the AI apply path publishes a batch of changed
	// elements we reveal that slide and hand the batch to the canvas overlay (the
	// user watches the edit land: glide old->new, fade/scale in-out, glow). The
	// effect re-runs when `chat.session` becomes available and cleans up on teardown.
	$effect(() => {
		const session = chat.session;
		if (!session) {
			return;
		}
		return session.changeAnimator.subscribe((batch) => {
			if (batch) {
				bridge.goToSlide(batch.slideIndex);
			}
			aiPanel.showChangeBatch(batch);
		});
	});

	// Applying a suggestion briefly enables the canvas colour tween so the edit
	// fades in rather than snapping (proposals apply outside the tool loop).
	function applyProposal(id: string): void {
		aiPanel.flashToolTarget(null);
		chat.applyProposal(id);
	}
	function acceptAllProposals(): void {
		aiPanel.flashToolTarget(null);
		chat.acceptAllProposals();
	}

	// Chat history: debounced per-deck persistence + the "Chats" resume menu
	// (shared controller; the export in File > Options > AI reads the same store).
	// oxlint-disable-next-line react-hooks/rules-of-hooks
	const history = useAiChatHistory({
		// The bridge is created once for the panel's lifetime (it reads live viewer
		// state through getters), so capturing it here is intentional.
		// svelte-ignore state_referenced_locally
		bridge,
		getMessages: () => chat.messages,
		setMessages: (messages) => chat.setMessages(messages),
		getUntitledLabel: () => t('pptx.ai.untitledChat'),
	});

	onMount(() => {
		void chat.init();
	});
</script>

<aside class="pptx-svelte-ai-panel" data-pptx-ai-panel aria-label={t('pptx.ai.title')}>
	<div class="pptx-svelte-ai-header">
		<Sparkles size={16} class="pptx-svelte-ai-header-icon" aria-hidden="true" />
		<span class="pptx-svelte-ai-title">{t('pptx.ai.title')}</span>
		<button
			type="button"
			class="pptx-svelte-ai-close"
			onclick={onclose}
			title={t('pptx.ai.close')}
			aria-label={t('pptx.ai.close')}
		>
			<X size={16} aria-hidden="true" />
		</button>
	</div>

	{#if chat.initState === 'checking'}
		<div class="pptx-svelte-ai-state">
			<LoaderCircle size={20} class="pptx-svelte-ai-spin" aria-hidden="true" />
		</div>
	{:else if chat.initState === 'unavailable' || chat.initState === 'error'}
		<div class="pptx-svelte-ai-state">
			<TriangleAlert size={24} aria-hidden="true" />
			<p class="pptx-svelte-ai-state-title">{t('pptx.ai.unavailableTitle')}</p>
			<p class="pptx-svelte-ai-state-hint">
				{chat.initError?.message ?? t('pptx.ai.unavailableHint')}
			</p>
		</div>
	{:else if chat.initState === 'ready'}
		<div class="pptx-svelte-ai-body">
			<AiHistoryMenu
				chats={history.chats}
				activeChatId={history.activeChatId}
				canClear={chat.messages.length > 0}
				onresume={(id) => void history.resumeChat(id)}
				ondelete={(id) => void history.deleteChat(id)}
				onnewchat={() => history.newChat()}
				onclearchat={() => history.clearCurrent()}
			/>

			<AiFocusBar
				targets={aiPanel.effectiveTargets}
				slides={bridge.getSlides()}
				isPinned={aiPanel.isPinned}
				hasPicks={aiPanel.hasPicks}
				pickMode={aiPanel.pickMode}
				onpin={() => aiPanel.pinFocus()}
				onclearpin={() => aiPanel.clearPinnedFocus()}
				onsenddirective={(text) => chat.send(text)}
				onstartpick={() => aiPanel.startPicking()}
				onstoppick={() => aiPanel.stopPicking()}
				onclearpicks={() => aiPanel.clearPicks()}
			/>

			<AiMessageList messages={chat.messages} isStreaming={chat.isStreaming} />

			{#if chat.error}
				<AiErrorBanner message={chat.error.message} onretry={() => chat.clearError()} />
			{/if}

			{#if chat.proposals.length > 0}
				<AiPendingChanges
					proposals={chat.proposals}
					onaccept={applyProposal}
					onacceptall={acceptAllProposals}
					onreject={(id) => chat.rejectProposal(id)}
				/>
			{/if}

			<AiComposer
				isStreaming={chat.isStreaming}
				onsend={(text) => chat.send(text)}
				onstop={() => chat.stop()}
				prefillText={aiPanel.prefill.text}
				prefillNonce={aiPanel.prefill.nonce}
			/>
		</div>
	{/if}
</aside>

<style>
	.pptx-svelte-ai-panel {
		display: flex;
		flex-direction: column;
		width: 320px;
		max-width: 100%;
		height: 100%;
		min-height: 0;
		border-left: 1px solid var(--pptx-border, #33334d);
		background: var(--pptx-card, #1a1a2e);
		color: var(--pptx-card-foreground, #e2e8f0);
	}

	/*
	 * Mobile (<768px): render as a bottom sheet instead of a full-height side
	 * panel. Use a fixed 75dvh height so it reads as a proper, roomy sheet (not a
	 * squished strip), span the full width, drop the left border for a top border,
	 * and round the top corners so it rises from the bottom edge (the dock is
	 * bottom-anchored in PowerPointViewer). This keeps the canvas above the sheet
	 * visible + tappable. Matches the React fix.
	 */
	@media (max-width: 767px) {
		.pptx-svelte-ai-panel {
			width: 100%;
			height: 75dvh;
			border-left: none;
			border-top: 1px solid var(--pptx-border, #33334d);
			border-top-left-radius: 12px;
			border-top-right-radius: 12px;
		}
		/*
		 * Touch target: matches MIN_TOUCH_TARGET_PX (44) from
		 * pptx-viewer-shared's render/responsive module. `!important` is
		 * load-bearing: ViewerGlobalStyles.svelte's document-level
		 * `:global(.pptx-svelte-viewer :is(button, [role='button']):not(...):not(...))`
		 * baseline reset out-specificities a plain scoped class selector.
		 */
		.pptx-svelte-ai-close {
			min-width: 44px !important;
			min-height: 44px !important;
		}
	}

	.pptx-svelte-ai-header {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 8px 12px;
		border-bottom: 1px solid var(--pptx-border, #33334d);
	}

	:global(.pptx-svelte-ai-header-icon) {
		color: var(--pptx-primary, #a5b4fc);
	}

	.pptx-svelte-ai-title {
		font-size: 13px;
		font-weight: 600;
	}

	.pptx-svelte-ai-close {
		margin-left: auto;
		display: inline-flex;
		padding: 4px;
		border: none;
		border-radius: 3px;
		background: transparent;
		color: var(--pptx-muted-foreground, #94a3b8);
		cursor: pointer;
	}

	.pptx-svelte-ai-close:hover {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-accent-foreground, #f8fafc);
	}

	.pptx-svelte-ai-state {
		flex: 1;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: 8px;
		padding: 0 24px;
		text-align: center;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-ai-state-title {
		margin: 0;
		font-size: 13px;
		font-weight: 500;
		color: var(--pptx-card-foreground, #e2e8f0);
	}

	.pptx-svelte-ai-state-hint {
		margin: 0;
		font-size: 12px;
	}

	.pptx-svelte-ai-body {
		flex: 1;
		display: flex;
		flex-direction: column;
		min-height: 0;
	}

	:global(.pptx-svelte-ai-spin) {
		animation: pptx-svelte-ai-panel-spin 0.8s linear infinite;
	}

	@keyframes pptx-svelte-ai-panel-spin {
		to {
			transform: rotate(360deg);
		}
	}
</style>

// viewers/pptx/packages/angular/src/viewer/ai/ai-chat-panel.component.ts
/**
 * AiChatPanelComponent: the right-hand AI assistant pane. Angular port of
 * React's `AiChatPanel` + `AiConversation`, combined into one thin shell.
 *
 * It provides {@link AiChatService} at its own level (so the lazily loaded `ai`
 * SDK is scoped to the open panel), bootstraps the session from the host bridge
 * + config, and lays out the transcript, the staged-proposal review strip, an
 * error banner, and the composer. Mount it behind a `@defer` block so its (and
 * the SDK's) chunk loads only when the assistant is first opened.
 */
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	effect,
	inject,
	input,
	output,
} from '@angular/core';
import { LucideLoaderCircle, LucideSparkles, LucideTriangleAlert, LucideX } from '@lucide/angular';
import { TranslatePipe } from '@ngx-translate/core';

import type { PptxAiBridge, PptxAiConfig } from 'ooxml-ui/pptx/ai';
import { deckIdFromBridge } from 'ooxml-ui/pptx/ai';
import { AiChatService } from './ai-chat.service';
import { AiComposerComponent } from './ai-composer.component';
import { AiFocusBarComponent } from './ai-focus-bar.component';
import { AiHistoryMenuComponent } from './ai-history-menu.component';
import { AiHistoryService } from './ai-history.service';
import { AiMessageListComponent } from './ai-message-list.component';
import { AiPanelStore } from './ai-panel-store';
import { AiProposalCardComponent } from './ai-proposal-card.component';

@Component({
	selector: 'pptx-ai-chat-panel',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	providers: [AiChatService, AiHistoryService],
	imports: [
		TranslatePipe,
		AiMessageListComponent,
		AiProposalCardComponent,
		AiComposerComponent,
		AiFocusBarComponent,
		AiHistoryMenuComponent,
		LucideSparkles,
		LucideX,
		LucideLoaderCircle,
		LucideTriangleAlert,
	],
	template: `
		<div
			data-pptx-ai-panel
			class="pptx-ng-ai-panel flex h-full w-80 flex-col border-l border-border bg-card shadow-xl"
			[style.width.px]="panelWidth()"
		>
			<div class="flex items-center gap-2 border-b border-border px-3 py-2">
				<svg lucideSparkles class="h-4 w-4 text-primary"></svg>
				<span class="text-sm font-semibold text-foreground">{{ 'pptx.ai.title' | translate }}</span>
				<button
					type="button"
					(click)="closed.emit()"
					[title]="'pptx.ai.close' | translate"
					[attr.aria-label]="'pptx.ai.close' | translate"
					class="pptx-ng-ai-close ml-auto rounded-sm p-1 text-muted-foreground transition-colors hover:bg-accent"
				>
					<svg lucideX class="h-4 w-4"></svg>
				</button>
			</div>

			@switch (chat.state()) {
				@case ('checking') {
					<div
						class="flex flex-1 flex-col items-center justify-center gap-2 text-muted-foreground"
						role="status"
						aria-live="polite"
					>
						<svg lucideLoaderCircle class="h-5 w-5 animate-spin"></svg>
					</div>
				}
				@case ('ready') {
					<div class="relative flex min-h-0 flex-1 flex-col">
						<pptx-ai-history-menu [canClear]="chat.messages().length > 0" />

						<pptx-ai-focus-bar
							[slides]="bridge().getSlides()"
							(sendDirective)="chat.send($event)"
						/>

						<pptx-ai-message-list [messages]="chat.messages()" [isStreaming]="chat.isStreaming()" />

						@if (chat.error(); as err) {
							<div
								class="mx-3 mb-2 flex items-start gap-2 rounded-md border border-destructive/40 bg-destructive/5 px-2.5 py-1.5 text-[12px] text-destructive"
							>
								<svg lucideTriangleAlert class="mt-0.5 h-3.5 w-3.5 shrink-0"></svg>
								<div class="min-w-0 flex-1">
									<div class="font-medium">{{ 'pptx.ai.errorPrefix' | translate }}</div>
									<div class="truncate text-[11px] opacity-80" [title]="err.message">
										{{ err.message }}
									</div>
								</div>
								<button
									type="button"
									(click)="chat.clearError()"
									class="shrink-0 rounded-sm px-1.5 py-0.5 text-[11px] underline-offset-2 hover:underline"
								>
									{{ 'pptx.ai.retry' | translate }}
								</button>
							</div>
						}

						@if (chat.proposals().length > 0) {
							<div
								class="max-h-[38%] space-y-2 overflow-y-auto border-t border-border bg-background px-3 py-2"
							>
								<div class="flex items-center justify-between">
									<span
										class="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground"
									>
										{{ 'pptx.ai.pendingChanges' | translate: { count: chat.proposals().length } }}
									</span>
									@if (chat.proposals().length > 1) {
										<button
											type="button"
											(click)="acceptAllProposals()"
											class="rounded-sm bg-primary/90 px-2 py-0.5 text-[11px] font-medium text-primary-foreground hover:bg-primary"
										>
											{{ 'pptx.ai.acceptAll' | translate }}
										</button>
									}
								</div>
								@for (proposal of chat.proposals(); track proposal.id) {
									<pptx-ai-proposal-card
										[proposal]="proposal"
										(accept)="applyProposal($event)"
										(reject)="chat.rejectProposal($event)"
									/>
								}
							</div>
						}

						<pptx-ai-composer
							[isStreaming]="chat.isStreaming()"
							[prefillText]="store.prefill().text"
							[prefillNonce]="store.prefill().nonce"
							(onSend)="chat.send($event)"
							(onStop)="chat.stop()"
						/>
					</div>
				}
				@default {
					<div class="flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center">
						<svg lucideTriangleAlert class="h-6 w-6 text-muted-foreground"></svg>
						<p class="text-sm font-medium text-foreground">
							{{ 'pptx.ai.unavailableTitle' | translate }}
						</p>
						<p class="text-[12px] text-muted-foreground">
							{{ chat.initError()?.message ?? ('pptx.ai.unavailableHint' | translate) }}
						</p>
					</div>
				}
			}
		</div>
	`,
	styles: [
		`
			/*
			 * Touch target: matches MIN_TOUCH_TARGET_PX (44) from
			 * pptx-viewer-shared's render/responsive module. A component-scoped
			 * rule (not a Tailwind utility) so it is not subject to Tailwind's
			 * \`@layer utilities\` losing to the global, unlayered
			 * \`:where(button)\` base rule in theme.css.
			 */
			@media (pointer: coarse), (max-width: 767px) {
				.pptx-ng-ai-close {
					display: flex;
					align-items: center;
					justify-content: center;
					min-width: 44px;
					min-height: 44px;
				}
			}
		`,
	],
})
export class AiChatPanelComponent {
	readonly bridge = input.required<PptxAiBridge>();
	readonly config = input.required<PptxAiConfig>();
	readonly panelWidth = input<number | undefined>(undefined);
	readonly closed = output<void>();

	protected readonly chat = inject(AiChatService);
	/** Chat-history persistence + the "Chats" resume menu (panel-scoped). */
	protected readonly history = inject(AiHistoryService);
	/** Shared panel scope + on-canvas highlight store (provided by the viewer). */
	protected readonly store = inject(AiPanelStore);

	constructor() {
		// Live "AI as a collaborator" focus: as each tool runs, navigate to and
		// highlight the slide / element(s) it touches so the canvas mirrors the
		// assistant in real time (and colour edits tween while it is active).
		this.chat.setToolTargetHandler((target) => {
			if (target && target.slideIndex !== undefined) {
				this.bridge().goToSlide(target.slideIndex);
			}
			this.store.flashToolTarget(target);
		});

		// Applied-edit animation: when the AI apply path publishes a batch of changed
		// elements, reveal that slide and hand the batch to the canvas overlay so the
		// user watches the edit land (glide old->new, fade/scale in-out, glow). The
		// animator is viewer-scoped (on the store), so unsubscribe with this panel.
		const unsubscribe = this.store.changeAnimator.subscribe((batch) => {
			if (batch) {
				this.bridge().goToSlide(batch.slideIndex);
			}
			this.store.showChangeBatch(batch);
		});
		inject(DestroyRef).onDestroy(unsubscribe);

		// Bootstrap the session once the bridge + config inputs are bound. `init`
		// is idempotent, so re-runs (e.g. from an inline config object identity
		// change) do not tear the live session down.
		effect(() => {
			this.chat.init(this.bridge(), this.config());
		});

		// Chat history: bootstrap the per-deck controller once the session is
		// ready (both inits are idempotent), and debounce-save on every
		// transcript change.
		effect(() => {
			if (this.chat.state() !== 'ready') {
				return;
			}
			this.history.init({
				deckId: deckIdFromBridge(this.bridge()),
				getMessages: () => [...this.chat.messages()],
				setMessages: (messages) => this.chat.setMessages(messages),
			});
		});
		effect(() => {
			this.chat.messages();
			this.history.notifyMessagesChanged();
		});
	}

	/**
	 * Apply a suggestion, first enabling the canvas colour tween so the edit fades
	 * in rather than snapping (proposals apply outside the tool loop).
	 */
	protected applyProposal(id: string): void {
		this.store.flashToolTarget(null);
		this.chat.applyProposal(id);
	}

	protected acceptAllProposals(): void {
		this.store.flashToolTarget(null);
		this.chat.acceptAllProposals();
	}
}
