// viewers/pptx/packages/vue/src/viewer/components/ribbon/SubtitleSettingsControl.vue
<script setup lang="ts">
import {
	createViewerOptionsStore,
	subtitleSettingsFromOptions,
	subtitleSettingsLabels,
	updateSubtitleSettings,
} from 'ooxml-ui/pptx';
import type { SubtitleSettingsChangeEvent } from 'ooxml-ui/pptx';
import { inject, onScopeDispose, shallowRef } from 'vue';
import { useI18n } from 'vue-i18n';

import { ViewerOptionsStoreKey } from '../../composables/useViewerOptionsStore';

const { t } = useI18n();
const store = inject(ViewerOptionsStoreKey, null) ?? createViewerOptionsStore({ persist: false });
const options = shallowRef(store.getOptions());
onScopeDispose(
	store.subscribe((value) => {
		options.value = value;
	}),
);
function commit(event: Event): void {
	updateSubtitleSettings(store, (event as SubtitleSettingsChangeEvent).detail);
}
</script>

<template>
	<pptx-ui-subtitle-settings
		data-ribbon-control="slideShow.captions.subtitleSettings"
		:settings.prop="subtitleSettingsFromOptions(options)"
		:labels.prop="subtitleSettingsLabels(t)"
		:languageDisabled.prop="store.isLocked('accessibility', 'subtitleLanguage')"
		@subtitle-settings-change="commit"
	></pptx-ui-subtitle-settings>
</template>

// viewers/pptx/packages/react/src/viewer/components/toolbar/SubtitleSettingsControl.tsx
import {
	createViewerOptionsStore,
	subtitleSettingsFromOptions,
	subtitleSettingsLabels,
	updateSubtitleSettings,
} from 'ooxml-ui/pptx';
import type {
	PptxUiSubtitleSettingsElement,
	SubtitleSettingsChangeEvent,
} from 'ooxml-ui/pptx';
import React, { useContext, useEffect, useRef, useSyncExternalStore } from 'react';
import { useTranslation } from 'react-i18next';

import { ViewerOptionsStoreContext } from '../viewer-options-context';

/** Native lifecycle and preference ownership only; shared owns trigger and dialog. */
export function SubtitleSettingsControl(): React.ReactElement {
	const { t } = useTranslation();
	const supplied = useContext(ViewerOptionsStoreContext);
	const fallback = useRef<ReturnType<typeof createViewerOptionsStore> | null>(null);
	if (!supplied) {
		fallback.current ??= createViewerOptionsStore({ persist: false });
	}
	const store = supplied ?? fallback.current!;
	const options = useSyncExternalStore(
		(callback) => store.subscribe(callback),
		() => store.getOptions(),
		() => store.getOptions(),
	);
	const ref = useRef<PptxUiSubtitleSettingsElement>(null);
	useEffect(() => {
		const element = ref.current!;
		element.settings = subtitleSettingsFromOptions(options);
		element.labels = subtitleSettingsLabels((key) => t(key));
		element.languageDisabled = store.isLocked('accessibility', 'subtitleLanguage');
	}, [options, store, t]);
	useEffect(() => {
		const element = ref.current!;
		const commit = (event: Event) =>
			updateSubtitleSettings(store, (event as SubtitleSettingsChangeEvent).detail);
		element.addEventListener('subtitle-settings-change', commit);
		return () => element.removeEventListener('subtitle-settings-change', commit);
	}, [store]);
	return (
		<pptx-ui-subtitle-settings
			ref={ref}
			data-ribbon-control='slideShow.captions.subtitleSettings'
		/>
	);
}
