// viewers/pptx/packages/vue/src/viewer/components/ribbon/TransitionsSection.vue
<script setup lang="ts">
import type { PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
import type { RibbonTransitionsRequestEvent } from 'ooxml-ui/pptx';
import {
	playSlideTransitionPreview,
	readRibbonTransitionDraft,
	ribbonTransitionsDraftPatch,
	ribbonTransitionsSoundChange,
	ribbonTransitionStockSoundUrl,
	ribbonTransitionUpdates,
} from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { playAnimationSound } from '../../composables/animation-sound';

/**
 * TransitionsSection: a thin adapter over the shared `pptx-ui-ribbon-transitions`
 * view. Every control reads the ACTIVE SLIDE through `readRibbonTransitionDraft`
 * and commits through `ribbonTransitionUpdates`; Preview replays the transition
 * on the stage without writing, and sound picks are raw transition patches.
 */
interface Props {
	isInspectorPaneOpen: boolean;
	onToggleInspector: () => void;
	canEdit?: boolean;
	/** The slide whose transition the tab reads and writes. */
	activeSlide?: PptxSlide;
	onTransitionChange: (updates: Partial<PptxSlideTransition>) => void;
	onApplyTransitionToAll: () => void;
}

// `withDefaults` is load-bearing: Vue casts an ABSENT boolean prop to `false`,
// so a bare `defineProps` would disable the whole tab whenever a caller omits it.
const props = withDefaults(defineProps<Props>(), { canEdit: true, activeSlide: undefined });
const { t } = useI18n();
const draft = computed(() => readRibbonTransitionDraft(props.activeSlide));
const state = computed(() => ({
	draft: draft.value,
	transition: props.activeSlide?.transition,
	editable: props.canEdit !== false,
	inspectorOpen: props.isInspectorPaneOpen,
	translate: t,
}));

function request(event: RibbonTransitionsRequestEvent): void {
	const intent = event.detail;
	const patch = ribbonTransitionsDraftPatch(intent);
	if (patch) {
		props.onTransitionChange(ribbonTransitionUpdates({ ...draft.value, ...patch }));
		return;
	}
	switch (intent.kind) {
		case 'preview':
			playSlideTransitionPreview(props.activeSlide?.transition, document);
			break;
		case 'applyToAll':
			props.onApplyTransitionToAll();
			break;
		case 'inspector':
			props.onToggleInspector();
			break;
		case 'soundPreview': {
			const url = ribbonTransitionStockSoundUrl(props.activeSlide?.transition);
			if (url) {
				playAnimationSound(url);
			}
			break;
		}
		default:
			void ribbonTransitionsSoundChange(intent).then((change) => {
				if (change) {
					props.onTransitionChange(change);
				}
				return undefined;
			});
	}
}
</script>

<template>
	<pptx-ui-ribbon-transitions :state.prop="state" @transitions-request="request" />
</template>

// viewers/pptx/packages/react/src/viewer/components/toolbar/TransitionsSection.tsx
import type { PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
import type {
	PptxUiRibbonTransitionsElement,
	RibbonTransitionsRequestEvent,
} from 'ooxml-ui/pptx';
import {
	playSlideTransitionPreview,
	readRibbonTransitionDraft,
	ribbonTransitionsDraftPatch,
	ribbonTransitionsSoundChange,
	ribbonTransitionStockSoundUrl,
	ribbonTransitionUpdates,
} from 'ooxml-ui/pptx';
import React, { useEffect, useMemo, useRef } from 'react';
import { useTranslation } from 'react-i18next';

import { playAnimationSound } from '../../utils/animation-sound';

/**
 * The Transitions ribbon tab: a thin adapter over `pptx-ui-ribbon-transitions`.
 *
 * The shared view owns every control, label, pressed state and gating. The
 * tab holds no transition state of its own: `readRibbonTransitionDraft`
 * derives what each control shows from the ACTIVE SLIDE, every change commits
 * `ribbonTransitionUpdates` through `onTransitionChange`, Preview replays the
 * slide's transition on the editing stage (and writes nothing), and sound
 * picks are raw transition patches that bypass the draft.
 */
export interface TransitionsSectionProps {
	isInspectorPaneOpen: boolean;
	onToggleInspector: () => void;
	/** The slide whose transition the tab reads and writes. */
	activeSlide?: PptxSlide;
	onTransitionChange: (updates: Partial<PptxSlideTransition>) => void;
	onApplyTransitionToAll: () => void;
	canEdit?: boolean;
}

export function TransitionsSection(p: TransitionsSectionProps): React.ReactElement {
	const { t } = useTranslation();
	const ref = useRef<PptxUiRibbonTransitionsElement>(null);
	const draft = useMemo(() => readRibbonTransitionDraft(p.activeSlide), [p.activeSlide]);
	const transition = p.activeSlide?.transition;
	const editable = p.canEdit !== false;
	useEffect(() => {
		const host = ref.current;
		if (host) {
			host.state = {
				draft,
				transition,
				editable,
				inspectorOpen: p.isInspectorPaneOpen,
				translate: t,
			};
		}
	}, [draft, transition, editable, p.isInspectorPaneOpen, t]);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		const request = (event: Event) => {
			const intent = (event as RibbonTransitionsRequestEvent).detail;
			const patch = ribbonTransitionsDraftPatch(intent);
			if (patch) {
				p.onTransitionChange(ribbonTransitionUpdates({ ...draft, ...patch }));
				return;
			}
			switch (intent.kind) {
				case 'preview':
					playSlideTransitionPreview(transition, document);
					break;
				case 'applyToAll':
					p.onApplyTransitionToAll();
					break;
				case 'inspector':
					p.onToggleInspector();
					break;
				case 'soundPreview': {
					const url = ribbonTransitionStockSoundUrl(transition);
					if (url) {
						playAnimationSound(url);
					}
					break;
				}
				default:
					void ribbonTransitionsSoundChange(intent).then((change) => {
						if (change) {
							p.onTransitionChange(change);
						}
						return undefined;
					});
			}
		};
		host.addEventListener('transitions-request', request);
		return () => host.removeEventListener('transitions-request', request);
	}, [draft, transition, p]);
	return <pptx-ui-ribbon-transitions ref={ref} />;
}
