// viewers/pptx/packages/vue/src/viewer/components/ChartQuickActionsOverlay.vue
<script setup lang="ts">
import { Filter, Paintbrush, Plus } from 'lucide-vue-next';
/**
 * ChartQuickActionsOverlay: PowerPoint's three floating quick-action icons
 * ("Chart Elements" +, "Chart Styles" paintbrush, "Chart Filters" funnel)
 * shown just outside a selected chart's top-right corner. Mirrors React's
 * `ChartQuickActionsOverlay.tsx`; lives in the SAME scaled-stage coordinate
 * space as `SelectionOverlay` (mounted as its sibling in
 * `ViewerCanvasOverlays.vue`), reusing that overlay's `--pptx-vue-hs`
 * inverse-zoom CSS var so the buttons/popovers stay a constant screen size.
 *
 * All decision-making (which buttons render, checklist/gallery/filter state)
 * comes from the shared `buildChartQuickActionsDescriptor`; this component
 * only renders three buttons plus whichever popover is open, and calls the
 * shared mutation functions the descriptor's state was computed from
 * (`applyChartElementToggle`, `hideChartSeries`/`restoreFilteredSeries`,
 * `applyChartStylePreset`) through the existing `ChartCanvasEditContext`
 * (`updateElement`), the same commit path chart mark-drag and inline title
 * editing already use. See the shared module's header for scope notes
 * (Series-only Chart Filters, no trendline/error-bar/up-down-bars rows).
 */
import type { ChartPptxElement, PptxElement } from 'pptx-viewer-core';
import {
	applyChartElementToggle,
	applyChartStylePreset,
	buildChartQuickActionsDescriptor,
	CHART_QUICK_ACTION_BUTTON_SIZE,
	hideChartSeries,
	restoreFilteredSeries,
} from 'ooxml-ui/pptx';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { injectChartCanvasEdit } from '../composables/chart-part-selection';

const props = defineProps<{
	element: ChartPptxElement;
	canEdit: boolean;
	/** Effective stage zoom, so the buttons/popovers can size to a constant screen px. */
	zoom: number;
}>();

const { t } = useI18n();
const editCtx = injectChartCanvasEdit();

type QuickActionId = 'elements' | 'styles' | 'filters';
const open = ref<QuickActionId | null>(null);
const hostEl = ref<HTMLElement | null>(null);

const ICONS: Record<QuickActionId, typeof Plus> = {
	elements: Plus,
	styles: Paintbrush,
	filters: Filter,
};

// The buttons keep a constant screen size (`--pptx-vue-hs`), so the descriptor
// is built against the on-screen box and each position divided back to stage px
// by `screenPx`. Laying them out in stage px made them overlap when zoomed out.
const scale = computed(() => props.zoom || 1);

function screenPx(value: number): number {
	return value / scale.value;
}

const descriptor = computed(() =>
	buildChartQuickActionsDescriptor({
		isChartSelected: true,
		chartData: props.element.chartData,
		selectionBox: {
			x: props.element.x * scale.value,
			y: props.element.y * scale.value,
			width: props.element.width * scale.value,
			height: props.element.height * scale.value,
		},
	}),
);

function commit(updates: Partial<PptxElement>): void {
	editCtx?.updateElement(props.element.id, updates);
}

function toggle(id: QuickActionId): void {
	open.value = open.value === id ? null : id;
}

function onOutsideClick(e: MouseEvent): void {
	if (open.value && hostEl.value && !hostEl.value.contains(e.target as Node)) {
		open.value = null;
	}
}

onMounted(() => document.addEventListener('mousedown', onOutsideClick));
onBeforeUnmount(() => document.removeEventListener('mousedown', onOutsideClick));

function onElementToggle(
	key: 'title' | 'legend' | 'gridlines' | 'dataLabels' | 'axes' | 'axisTitles',
	checked: boolean,
): void {
	const chartData = props.element.chartData;
	if (!chartData) {
		return;
	}
	commit({ chartData: applyChartElementToggle(chartData, key, checked) });
}

function onStylePreset(presetId: string): void {
	const chartData = props.element.chartData;
	if (!chartData) {
		return;
	}
	const next = applyChartStylePreset(chartData, presetId);
	if (next) {
		commit({ chartData: next });
	}
}

function onFilterToggle(seriesIndex: number | undefined, filteredIndex: number | undefined): void {
	const chartData = props.element.chartData;
	if (!chartData) {
		return;
	}
	const next =
		seriesIndex !== undefined
			? hideChartSeries(chartData, seriesIndex)
			: restoreFilteredSeries(chartData, filteredIndex!);
	if (next) {
		commit({ chartData: next });
	}
}
</script>

<template>
	<div
		v-if="descriptor"
		ref="hostEl"
		data-pptx-chart-quick-actions="true"
		data-export-ignore="true"
		data-testid="chart-quick-actions"
		style="position: absolute; left: 0; top: 0; z-index: 59"
		@pointerdown.stop
		@mousedown.stop
	>
		<template v-for="button in descriptor.buttons" :key="button.id">
			<button
				type="button"
				:disabled="!canEdit"
				:data-testid="`chart-quick-action-${button.id}`"
				:aria-label="t(button.labelKey)"
				:title="t(button.labelKey)"
				class="flex items-center justify-center rounded bg-white border border-gray-300 shadow-sm hover:bg-gray-100 text-gray-700"
				:style="{
					position: 'absolute',
					left: `${screenPx(button.x)}px`,
					top: `${screenPx(button.y)}px`,
					width: `${button.size}px`,
					height: `${button.size}px`,
					scale: 'var(--pptx-vue-hs, 1)',
					transformOrigin: 'top left',
				}"
				@click="toggle(button.id)"
			>
				<component :is="ICONS[button.id]" class="size-3.5" />
			</button>

			<div
				v-if="open === button.id && button.id === 'elements'"
				data-testid="chart-quick-elements-popover"
				class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2 w-44 z-10 shadow-lg"
				:style="{
					position: 'absolute',
					left: `${screenPx(button.x + CHART_QUICK_ACTION_BUTTON_SIZE + 4)}px`,
					top: `${screenPx(button.y)}px`,
					scale: 'var(--pptx-vue-hs, 1)',
					transformOrigin: 'top left',
				}"
			>
				<div
					class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground"
				>
					{{ t('pptx.chart.quickElements') }}
				</div>
				<label
					v-for="item in descriptor.elements"
					:key="item.key"
					class="flex items-center gap-2 cursor-pointer"
				>
					<pptx-ui-checkbox
						:disabled="!canEdit"
						:checked="item.checked"
						:data-testid="`chart-quick-element-${item.key}`"
						@change="onElementToggle(item.key, ($event.target as HTMLInputElement).checked)"
					/>
					<span class="text-[11px]">{{ t(item.labelKey) }}</span>
				</label>
			</div>

			<div
				v-if="open === button.id && button.id === 'styles'"
				data-testid="chart-quick-styles-popover"
				class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2 w-48 z-10 shadow-lg grid grid-cols-3 gap-1.5"
				:style="{
					position: 'absolute',
					left: `${screenPx(button.x + CHART_QUICK_ACTION_BUTTON_SIZE + 4)}px`,
					top: `${screenPx(button.y)}px`,
					scale: 'var(--pptx-vue-hs, 1)',
					transformOrigin: 'top left',
				}"
			>
				<button
					v-for="preset in descriptor.styles.presets"
					:key="preset.id"
					type="button"
					:disabled="!canEdit"
					:data-testid="`chart-quick-style-${preset.id}`"
					:aria-label="t(preset.labelKey)"
					:aria-pressed="preset.applied"
					:title="t(preset.labelKey)"
					class="flex flex-col rounded overflow-hidden border"
					:class="preset.applied ? 'border-primary ring-1 ring-primary' : 'border-border'"
					@click="onStylePreset(preset.id)"
				>
					<span class="flex h-5 w-full">
						<span
							v-for="(c, i) in preset.colors.slice(0, 5)"
							:key="i"
							class="flex-1"
							:style="{ backgroundColor: c }"
						/>
					</span>
				</button>
			</div>

			<div
				v-if="open === button.id && button.id === 'filters'"
				data-testid="chart-quick-filters-popover"
				class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2 w-48 z-10 shadow-lg"
				:style="{
					position: 'absolute',
					left: `${screenPx(button.x + CHART_QUICK_ACTION_BUTTON_SIZE + 4)}px`,
					top: `${screenPx(button.y)}px`,
					scale: 'var(--pptx-vue-hs, 1)',
					transformOrigin: 'top left',
				}"
			>
				<div
					class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground"
				>
					{{ t('pptx.chart.quickFilters') }}
				</div>
				<label
					v-for="row in descriptor.filters.series"
					:key="row.key"
					class="flex items-center gap-2 cursor-pointer"
				>
					<pptx-ui-checkbox
						:disabled="!canEdit"
						:checked="row.visible"
						:data-testid="`chart-quick-filter-${row.key}`"
						@change="onFilterToggle(row.seriesIndex, row.filteredIndex)"
					/>
					<span class="text-[11px] truncate">{{ row.name }}</span>
				</label>
			</div>
		</template>
	</div>
</template>

// viewers/pptx/packages/react/src/viewer/components/canvas/ChartQuickActionsOverlay.tsx
import type { ChartPptxElement, PptxElement } from 'pptx-viewer-core';
import {
	applyChartElementToggle,
	applyChartStylePreset,
	buildChartQuickActionsDescriptor,
	CHART_QUICK_ACTION_BUTTON_SIZE,
	hideChartSeries,
	restoreFilteredSeries,
} from 'ooxml-ui/pptx';
import React, { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuFilter, LuPaintbrush, LuPlus } from 'react-icons/lu';

import { CARD, HEADING } from '../inspector/chart-panel-constants';
import { WebCheckbox } from '../WebControls';

export interface ChartQuickActionsOverlayProps {
	element: ChartPptxElement;
	canEdit: boolean;
	/** Effective stage scale (`zoom.editorScale`), so gaps stay a constant screen size. */
	scale?: number;
	onUpdateElement: (elementId: string, updates: Partial<PptxElement>) => void;
}

const ICONS: Record<
	'elements' | 'styles' | 'filters',
	React.ComponentType<{ className?: string }>
> = {
	elements: LuPlus,
	styles: LuPaintbrush,
	filters: LuFilter,
};

/**
 * PowerPoint's three floating quick-action icons ("Chart Elements" +,
 * "Chart Styles" paintbrush, "Chart Filters" funnel) shown just outside a
 * selected chart's top-right corner. A stage-level sibling of
 * `SelectionHandleOverlay`, for the same reason: it must not be clipped by
 * the chart's own container.
 *
 * All decision-making (which buttons render, checklist/gallery/filter state)
 * comes from the shared `buildChartQuickActionsDescriptor`
 * (`pptx-viewer-shared`); this component only renders three buttons plus
 * whichever popover is open, and calls the shared mutation functions the
 * descriptor's state was computed from (`applyChartElementToggle`,
 * `hideChartSeries`/`restoreFilteredSeries`, `applyChartStylePreset`). See
 * that module's header for scope notes (Series-only Chart Filters, no
 * trendline/error-bar/up-down-bars checklist rows).
 */
export function ChartQuickActionsOverlay({
	element,
	canEdit,
	scale: stageScale = 1,
	onUpdateElement,
}: ChartQuickActionsOverlayProps): React.ReactElement | null {
	const { t } = useTranslation();
	const [open, setOpen] = useState<'elements' | 'styles' | 'filters' | null>(null);
	const hostRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		if (!open) {
			return;
		}
		const handler = (e: MouseEvent) => {
			if (hostRef.current && !hostRef.current.contains(e.target as Node)) {
				setOpen(null);
			}
		};
		document.addEventListener('mousedown', handler);
		return () => document.removeEventListener('mousedown', handler);
	}, [open]);

	// The buttons are a constant screen size (inverse-scaled below), so the
	// descriptor is built against the on-screen box, whose gaps are then screen
	// constants, and each resulting position is divided back to slide px.
	// Laying them out in slide px made them overlap whenever the stage was
	// zoomed out.
	const scale = stageScale || 1;
	const screenPx = (value: number) => value / scale;
	const descriptor = buildChartQuickActionsDescriptor({
		isChartSelected: true,
		chartData: element.chartData,
		selectionBox: {
			x: element.x * scale,
			y: element.y * scale,
			width: element.width * scale,
			height: element.height * scale,
		},
	});
	if (!descriptor || !element.chartData) {
		return null;
	}
	const chartData = element.chartData;

	const commit = (updates: Partial<PptxElement>) => onUpdateElement(element.id, updates);

	return (
		<div
			ref={hostRef}
			data-pptx-chart-quick-actions='true'
			data-export-ignore='true'
			style={{ position: 'absolute', left: 0, top: 0, zIndex: 59 }}
			// The canvas stage deselects on a mousedown that lands outside any
			// `data-pptx-element` node (see `SelectionHandleOverlay`'s own doc
			// comment on the same hazard). This host is deliberately not marked
			// that way, so without stopping propagation here every click on a
			// quick-action button or popover control first deselected the chart
			// (dropping this whole overlay) before its own onClick/onChange ran.
			onMouseDown={(e) => e.stopPropagation()}
		>
			{descriptor.buttons.map((button) => (
				<React.Fragment key={button.id}>
					<button
						type='button'
						disabled={!canEdit}
						data-testid={`chart-quick-action-${button.id}`}
						aria-label={t(button.labelKey)}
						title={t(button.labelKey)}
						onClick={() => setOpen((prev) => (prev === button.id ? null : button.id))}
						style={{
							position: 'absolute',
							left: screenPx(button.x),
							top: screenPx(button.y),
							width: button.size,
							height: button.size,
							scale: 'var(--pptx-handle-inverse-scale, 1)',
							transformOrigin: 'top left',
						}}
						// Fixed, opaque colours rather than the app's semantic theme tokens
						// (bg-popover/hover:bg-accent/text-foreground): those tokens are
						// tuned for panels that sit inside the app's own dark chrome, and
						// `--color-accent` is deliberately a LOW-ALPHA tint for that
						// context. This button floats over the SLIDE CANVAS instead (any
						// colour, often white), so a translucent hover background reads
						// as whatever is behind it, at which point the icon's colour
						// (unchanged on hover) can land on its own near-twin and vanish.
						// Same reasoning as ConnectorEndpointOverlay/ConnectorOverlay,
						// which use fixed colours for the same reason.
						className='flex items-center justify-center rounded bg-white border border-gray-300 shadow-sm hover:bg-gray-100 text-gray-700'
					>
						{React.createElement(ICONS[button.id], { className: 'size-3.5' })}
					</button>

					{open === button.id && button.id === 'elements' && (
						<div
							data-testid='chart-quick-elements-popover'
							style={{
								position: 'absolute',
								left: screenPx(button.x + CHART_QUICK_ACTION_BUTTON_SIZE + 4),
								top: screenPx(button.y),
								scale: 'var(--pptx-handle-inverse-scale, 1)',
								transformOrigin: 'top left',
							}}
							className={`${CARD} w-44 z-10 shadow-lg`}
						>
							<div className={HEADING}>{t('pptx.chart.quickElements')}</div>
							{descriptor.elements.map((item) => (
								<label key={item.key} className='flex items-center gap-2 cursor-pointer'>
									<WebCheckbox
										disabled={!canEdit}
										checked={item.checked}
										data-testid={`chart-quick-element-${item.key}`}
										onChange={(e) =>
											commit({
												chartData: applyChartElementToggle(chartData, item.key, e.target.checked),
											})
										}
									/>
									<span className='text-[11px]'>{t(item.labelKey)}</span>
								</label>
							))}
						</div>
					)}

					{open === button.id && button.id === 'styles' && (
						<div
							data-testid='chart-quick-styles-popover'
							style={{
								position: 'absolute',
								left: screenPx(button.x + CHART_QUICK_ACTION_BUTTON_SIZE + 4),
								top: screenPx(button.y),
								scale: 'var(--pptx-handle-inverse-scale, 1)',
								transformOrigin: 'top left',
							}}
							className={`${CARD} w-48 z-10 shadow-lg grid grid-cols-3 gap-1.5`}
						>
							{descriptor.styles.presets.map((preset) => (
								<button
									key={preset.id}
									type='button'
									disabled={!canEdit}
									data-testid={`chart-quick-style-${preset.id}`}
									aria-label={t(preset.labelKey)}
									aria-pressed={preset.applied}
									title={t(preset.labelKey)}
									onClick={() => {
										const next = applyChartStylePreset(chartData, preset.id);
										if (next) {
											commit({ chartData: next });
										}
									}}
									className={`flex flex-col rounded overflow-hidden border ${
										preset.applied ? 'border-primary ring-1 ring-primary' : 'border-border'
									}`}
								>
									<span className='flex h-5 w-full'>
										{preset.colors.slice(0, 5).map((c, i) => (
											<span key={i} style={{ backgroundColor: c }} className='flex-1' />
										))}
									</span>
								</button>
							))}
						</div>
					)}

					{open === button.id && button.id === 'filters' && (
						<div
							data-testid='chart-quick-filters-popover'
							style={{
								position: 'absolute',
								left: screenPx(button.x + CHART_QUICK_ACTION_BUTTON_SIZE + 4),
								top: screenPx(button.y),
								scale: 'var(--pptx-handle-inverse-scale, 1)',
								transformOrigin: 'top left',
							}}
							className={`${CARD} w-48 z-10 shadow-lg`}
						>
							<div className={HEADING}>{t('pptx.chart.quickFilters')}</div>
							{descriptor.filters.series.map((row) => (
								<label key={row.key} className='flex items-center gap-2 cursor-pointer'>
									<WebCheckbox
										disabled={!canEdit}
										checked={row.visible}
										data-testid={`chart-quick-filter-${row.key}`}
										onChange={() => {
											const next =
												row.seriesIndex !== undefined
													? hideChartSeries(chartData, row.seriesIndex)
													: restoreFilteredSeries(chartData, row.filteredIndex!);
											if (next) {
												commit({ chartData: next });
											}
										}}
									/>
									<span className='text-[11px] truncate'>{row.name}</span>
								</label>
							))}
						</div>
					)}
				</React.Fragment>
			))}
		</div>
	);
}
