// viewers/pptx/packages/vue/src/viewer/components/CommentMarkersOverlay.vue
<script setup lang="ts">
import type { PptxComment } from 'pptx-viewer-core';
import { buildCommentMarkers, COMMENT_MARKER_SIZE } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { CanvasSize } from '../types';

/**
 * CommentMarkersOverlay: numbered comment marker dots drawn over the slide
 * canvas. Vue port of the React `canvas/CommentMarkersOverlay.tsx`. The
 * descriptors (position clamped to the slide or a 4-column grid fallback,
 * 1-based numbering, and the `"<author>: <text>"` tooltip) come from the
 * shared `buildCommentMarkers`, so markers match every other binding.
 */
const props = defineProps<{
	comments: PptxComment[];
	canvasSize: CanvasSize;
}>();

const emit = defineEmits<{
	'marker-click': [commentId: string];
}>();

const { t } = useI18n();

const half = COMMENT_MARKER_SIZE / 2;

const markers = computed(() =>
	buildCommentMarkers(
		props.comments,
		props.canvasSize.width,
		props.canvasSize.height,
		t('pptx.comments.unknownAuthor'),
	),
);
</script>

<template>
	<div class="pointer-events-none absolute inset-0 z-[45]">
		<button
			v-for="marker in markers"
			:key="marker.commentId"
			type="button"
			class="pptx-vue-comment-marker pointer-events-auto absolute flex cursor-pointer items-center justify-center rounded-full border-2 border-white text-[10px] font-bold leading-none text-white shadow"
			:style="{
				left: `${marker.x - half}px`,
				top: `${marker.y - half}px`,
				width: `${COMMENT_MARKER_SIZE}px`,
				height: `${COMMENT_MARKER_SIZE}px`,
				backgroundColor: 'rgba(255, 165, 0, 0.9)',
			}"
			:title="marker.title"
			@click.stop="emit('marker-click', marker.commentId)"
		>
			{{ marker.label }}
		</button>
	</div>
</template>

// viewers/pptx/packages/react/src/viewer/components/canvas/CommentMarkersOverlay.tsx
/**
 * Comment marker dots rendered on top of the slide canvas.
 *
 * The descriptors (position clamped to the slide or a 4-column grid
 * fallback, 1-based numbering, and the `"<author>: <text>"` tooltip) come
 * from the shared `buildCommentMarkers`, so the dots match every other
 * binding (Vue, Angular, Svelte, Vanilla).
 */
import type { PptxComment } from 'pptx-viewer-core';
import { buildCommentMarkers, COMMENT_MARKER_SIZE } from 'ooxml-ui/pptx';
import { useTranslation } from 'react-i18next';

import type { CanvasSize } from '../../types';

/* ------------------------------------------------------------------ */
/*  Props                                                              */
/* ------------------------------------------------------------------ */

interface CommentMarkersOverlayProps {
	comments: PptxComment[];
	canvasSize: CanvasSize;
	onCommentMarkerClick?: (commentId: string) => void;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function CommentMarkersOverlay({
	comments,
	canvasSize,
	onCommentMarkerClick,
}: CommentMarkersOverlayProps) {
	const { t } = useTranslation(),
		half = COMMENT_MARKER_SIZE / 2,
		markers = buildCommentMarkers(
			comments,
			canvasSize.width,
			canvasSize.height,
			t('pptx.comments.unknownAuthor'),
		);
	return (
		<div className='absolute inset-0 pointer-events-none z-[45]'>
			{markers.map((marker) => (
				<div
					key={marker.commentId}
					className='absolute pointer-events-auto cursor-pointer'
					style={{
						left: marker.x - half,
						top: marker.y - half,
						width: COMMENT_MARKER_SIZE,
						height: COMMENT_MARKER_SIZE,
						borderRadius: '50%',
						backgroundColor: 'rgba(255, 165, 0, 0.9)',
						border: '2px solid #fff',
						boxShadow: '0 1px 3px rgba(0,0,0,0.3)',
						display: 'flex',
						alignItems: 'center',
						justifyContent: 'center',
						fontSize: 10,
						fontWeight: 700,
						color: '#fff',
						lineHeight: 1,
					}}
					title={marker.title}
					onClick={(e) => {
						e.stopPropagation();
						onCommentMarkerClick?.(marker.commentId);
					}}
				>
					{marker.label}
				</div>
			))}
		</div>
	);
}
