// viewers/pptx/packages/vue/src/viewer/components/ConnectorEndpointOverlay.vue
<script setup lang="ts">
/**
 * ConnectorEndpointOverlay: the two handles PowerPoint puts on a selected
 * connector, which attach an end to a shape's connection point or detach it.
 *
 * Vue could DRAW a connector but never bind one: nothing in this binding ever
 * wrote `a:stCxn` / `a:endCxn`, so `connector-reroute` (a connector following
 * the shape it is anchored to) only ever fired for connectors that arrived
 * already bound from a `.pptx`.
 *
 * Rendered inside the scaled stage like every other canvas overlay, so all
 * coordinates are RAW SLIDE SPACE; the zoom is used only to convert pointer
 * screen positions back into it, and to keep the handles a constant screen size.
 *
 * Every decision is shared (`render/connector-endpoints`).
 */
import type { PptxElement } from 'pptx-viewer-core';
import {
	collectConnectorSiteCandidates,
	findConnectorSiteNear,
	getConnectorEndpointHandles,
	resolveConnectorEndpointUpdate,
	withConnectorEndpointUpdate,
} from 'ooxml-ui/pptx';
import type { ConnectorEndpointKind } from 'ooxml-ui/pptx';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

const props = defineProps<{
	connector: PptxElement;
	elements: PptxElement[];
	/** `fitScale x userZoom`; used only to un-scale pointer travel. */
	zoom: number;
}>();

const emit = defineEmits<{
	commit: [payload: { id: string; element: PptxElement }];
}>();

const { t } = useI18n();
const rootEl = ref<HTMLElement | null>(null);
const drag = ref<{ kind: ConnectorEndpointKind; x: number; y: number } | null>(null);

const candidates = computed(() =>
	collectConnectorSiteCandidates(props.elements.filter((el) => el.id !== props.connector.id)),
);
const handles = computed(() => getConnectorEndpointHandles(props.connector));
const snap = computed(() =>
	drag.value ? findConnectorSiteNear(candidates.value, drag.value.x, drag.value.y) : null,
);
/** Handles keep a constant SCREEN size, like the resize handles beside them. */
const inverseZoom = computed(() => 1 / (props.zoom || 1));

function toSlidePoint(clientX: number, clientY: number): { x: number; y: number } {
	const rect = rootEl.value?.getBoundingClientRect();
	const scale = props.zoom || 1;
	return { x: (clientX - (rect?.left ?? 0)) / scale, y: (clientY - (rect?.top ?? 0)) / scale };
}

function onPointerMove(event: PointerEvent): void {
	if (!drag.value) {
		return;
	}
	drag.value = { ...drag.value, ...toSlidePoint(event.clientX, event.clientY) };
}

function onPointerUp(event: PointerEvent): void {
	const current = drag.value;
	detach();
	if (!current) {
		return;
	}
	const point = toSlidePoint(event.clientX, event.clientY);
	const target = findConnectorSiteNear(candidates.value, point.x, point.y);
	const update = resolveConnectorEndpointUpdate(
		props.connector,
		props.elements,
		current.kind,
		point,
		target,
	);
	emit('commit', {
		id: props.connector.id,
		element: withConnectorEndpointUpdate(props.connector, update),
	});
}

function detach(): void {
	drag.value = null;
	window.removeEventListener('pointermove', onPointerMove);
	window.removeEventListener('pointerup', onPointerUp);
	window.removeEventListener('pointercancel', onPointerUp);
}

function beginDrag(kind: ConnectorEndpointKind, event: PointerEvent): void {
	event.preventDefault();
	event.stopPropagation();
	drag.value = { kind, ...toSlidePoint(event.clientX, event.clientY) };
	window.addEventListener('pointermove', onPointerMove);
	window.addEventListener('pointerup', onPointerUp);
	window.addEventListener('pointercancel', onPointerUp);
}

function handleStyle(handle: { kind: ConnectorEndpointKind; x: number; y: number }) {
	const live = drag.value?.kind === handle.kind ? drag.value : handle;
	return {
		left: `${live.x}px`,
		top: `${live.y}px`,
		transform: `translate(-50%, -50%) scale(${inverseZoom.value})`,
	};
}
defineExpose({ hasActivePointerInteraction: () => drag.value !== null });
</script>

<template>
	<div ref="rootEl" class="pptx-vue-connector-endpoints" data-pptx-connector-endpoints>
		<!-- Candidate connection points, revealed only while an end is in flight
		     so they never obscure the deck at rest. -->
		<div
			v-for="site in drag ? candidates : []"
			:key="`${site.elementId}-${site.siteIndex}`"
			class="pptx-vue-connection-site"
			:class="{
				'is-snapped': snap?.elementId === site.elementId && snap?.siteIndex === site.siteIndex,
			}"
			data-pptx-connection-site
			aria-hidden="true"
			:style="{
				left: `${site.x}px`,
				top: `${site.y}px`,
				transform: `translate(-50%, -50%) scale(${inverseZoom})`,
			}"
		/>

		<button
			v-for="handle in handles"
			:key="handle.kind"
			type="button"
			class="pptx-vue-connector-endpoint"
			:class="{ 'is-attached': handle.attached }"
			:data-pptx-connector-endpoint="handle.kind"
			:data-pptx-connector-attached="String(handle.attached)"
			:aria-label="
				t(
					handle.kind === 'start'
						? 'pptx.canvas.connectorEndpointStart'
						: 'pptx.canvas.connectorEndpointEnd',
				)
			"
			:style="handleStyle(handle)"
			@pointerdown="(e) => beginDrag(handle.kind, e)"
		/>
	</div>
</template>

<style scoped>
.pptx-vue-connector-endpoints {
	position: absolute;
	inset: 0;
	pointer-events: none;
	z-index: 56;
}

.pptx-vue-connection-site {
	position: absolute;
	width: 8px;
	height: 8px;
	border-radius: 9999px;
	border: 2px solid #3b82f6;
	background: rgb(96 165 250 / 60%);
}

.pptx-vue-connection-site.is-snapped {
	background: #3b82f6;
}

/* A bound end is filled, a loose one hollow, so "is this connector actually
   attached?" is answerable at a glance. */
.pptx-vue-connector-endpoint {
	position: absolute;
	width: 10px;
	height: 10px;
	padding: 0;
	border-radius: 9999px;
	border: 2px solid #fff;
	background: #fff;
	box-shadow: 0 0 0 1px #16a34a;
	cursor: crosshair;
	pointer-events: auto;
	touch-action: none;
}

.pptx-vue-connector-endpoint.is-attached {
	background: #16a34a;
}
</style>

// viewers/pptx/packages/react/src/viewer/components/canvas/ConnectorEndpointOverlay.tsx
/**
 * Connector endpoint authoring: the two handles PowerPoint puts on a selected
 * connector, which attach an end to a shape's connection point or detach it.
 *
 * Until this existed the binding could DRAW a connector but never bind one:
 * `a:stCxn` / `a:endCxn` were written by nothing reachable, so
 * `connector-reroute` (a connector following the shape it is anchored to) only
 * ever fired for connectors that arrived bound from a `.pptx`.
 *
 * Every decision is shared (`render/connector-endpoints`); this component owns
 * only the pointer lifecycle and the SVG.
 */
import type { ConnectorPptxElement, PptxElement } from 'pptx-viewer-core';
import {
	CONNECTOR_SITE_SNAP_PX,
	collectConnectorSiteCandidates,
	findConnectorSiteNear,
	getConnectorEndpointHandles,
	resolveConnectorEndpointUpdate,
	withConnectorEndpointUpdate,
} from 'ooxml-ui/pptx';
import type { ConnectorEndpointKind } from 'ooxml-ui/pptx';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

interface ConnectorEndpointOverlayProps {
	connector: PptxElement;
	elements: PptxElement[];
	/** Screen px per slide px. */
	editorScale: number;
	canvasStageRef: React.RefObject<HTMLDivElement | null>;
	onUpdateElement: (elementId: string, updates: Partial<PptxElement>) => void;
}

interface EndpointDrag {
	kind: ConnectorEndpointKind;
	x: number;
	y: number;
}

export function ConnectorEndpointOverlay({
	connector,
	elements,
	editorScale,
	canvasStageRef,
	onUpdateElement,
}: ConnectorEndpointOverlayProps) {
	const { t } = useTranslation();
	const [drag, setDrag] = useState<EndpointDrag | null>(null);

	// A connector may never bind to itself, and the candidate list is the same
	// one the reroute resolves site indices through.
	const candidates = useMemo(
		() => collectConnectorSiteCandidates(elements.filter((el) => el.id !== connector.id)),
		[elements, connector.id],
	);
	const handles = getConnectorEndpointHandles(connector);
	const snap = drag ? findConnectorSiteNear(candidates, drag.x, drag.y) : null;

	const toSlidePoint = useCallback(
		(clientX: number, clientY: number): { x: number; y: number } => {
			const rect = canvasStageRef.current?.getBoundingClientRect();
			const scale = editorScale || 1;
			return {
				x: (clientX - (rect?.left ?? 0)) / scale,
				y: (clientY - (rect?.top ?? 0)) / scale,
			};
		},
		[canvasStageRef, editorScale],
	);

	useEffect(() => {
		if (!drag) {
			return;
		}
		const onMove = (event: PointerEvent): void => {
			const point = toSlidePoint(event.clientX, event.clientY);
			setDrag((prev) => (prev ? { ...prev, ...point } : prev));
		};
		const onUp = (event: PointerEvent): void => {
			const point = toSlidePoint(event.clientX, event.clientY);
			const target = findConnectorSiteNear(candidates, point.x, point.y, CONNECTOR_SITE_SNAP_PX);
			const update = resolveConnectorEndpointUpdate(connector, elements, drag.kind, point, target);
			const next = withConnectorEndpointUpdate(connector, update) as ConnectorPptxElement;
			onUpdateElement(connector.id, {
				x: next.x,
				y: next.y,
				width: next.width,
				height: next.height,
				flipHorizontal: next.flipHorizontal,
				flipVertical: next.flipVertical,
				// Sent whole: a DETACHED end has had its binding key deleted, so a
				// merge of only the surviving keys would leave the stale one behind.
				shapeStyle: next.shapeStyle,
			} as Partial<PptxElement>);
			setDrag(null);
		};
		window.addEventListener('pointermove', onMove);
		window.addEventListener('pointerup', onUp);
		window.addEventListener('pointercancel', onUp);
		return () => {
			window.removeEventListener('pointermove', onMove);
			window.removeEventListener('pointerup', onUp);
			window.removeEventListener('pointercancel', onUp);
		};
	}, [drag, candidates, connector, elements, onUpdateElement, toSlidePoint]);

	return (
		<div
			className='absolute inset-0 z-[56] pointer-events-none'
			data-pptx-connector-endpoints
			data-export-ignore='true'
		>
			{/* Candidate connection points, revealed only while an end is in flight
			    so they never obscure the deck at rest. */}
			{drag
				? candidates.map((site) => (
						<div
							key={`${site.elementId}-${site.siteIndex}`}
							aria-hidden='true'
							data-pptx-connection-site
							className='absolute rounded-full border-2 border-blue-500'
							style={{
								left: site.x - 4,
								top: site.y - 4,
								width: 8,
								height: 8,
								background:
									snap?.elementId === site.elementId && snap.siteIndex === site.siteIndex
										? '#3b82f6'
										: 'rgba(96,165,250,0.6)',
							}}
						/>
					))
				: null}

			{handles.map((handle) => (
				<button
					key={handle.kind}
					type='button'
					data-pptx-connector-endpoint={handle.kind}
					data-pptx-connector-attached={String(handle.attached)}
					aria-label={t(
						handle.kind === 'start'
							? 'pptx.canvas.connectorEndpointStart'
							: 'pptx.canvas.connectorEndpointEnd',
					)}
					className='absolute rounded-full border-2 border-white shadow'
					style={{
						left: (drag?.kind === handle.kind ? drag.x : handle.x) - 5,
						top: (drag?.kind === handle.kind ? drag.y : handle.y) - 5,
						width: 10,
						height: 10,
						// A bound end is filled, a loose one hollow, so "is this
						// connector actually attached?" is answerable at a glance.
						background: handle.attached ? '#16a34a' : '#ffffff',
						boxShadow: '0 0 0 1px #16a34a',
						cursor: 'crosshair',
						pointerEvents: 'auto',
						touchAction: 'none',
					}}
					onPointerDown={(event) => {
						event.stopPropagation();
						event.preventDefault();
						const point = toSlidePoint(event.clientX, event.clientY);
						setDrag({ kind: handle.kind, ...point });
					}}
				/>
			))}
		</div>
	);
}
