// viewers/pptx/packages/vue/src/viewer/components/OutlineAuthoringLayer.vue
<script setup lang="ts">
/**
 * OutlineAuthoringLayer: stage-level host of the Edit Points overlay and the
 * Freeform: Shape / Curve drawing overlay (Vue port of React's
 * `canvas/OutlineAuthoringLayer.tsx`). Reads the viewer's
 * `OutlineAuthoringStore`, and leaves Edit Points when its shape disappears
 * (deleted, slide changed) or becomes locked.
 */
import type { PptxSlide } from 'pptx-viewer-core';
import { canEditElementPoints } from 'ooxml-ui/pptx';
import { computed, watch } from 'vue';

import { useOutlineAuthoring } from '../composables/useOutlineAuthoring';
import { useResolvedCustomization } from '../composables/useViewerCustomization';
import type { CanvasSize } from '../types';
import EditPointsOverlay from './EditPointsOverlay.vue';
import FreeformToolOverlay from './FreeformToolOverlay.vue';

const props = defineProps<{
	activeSlide: PptxSlide | undefined;
	canvasSize: CanvasSize;
	scale: number;
}>();

const store = useOutlineAuthoring();
const customization = useResolvedCustomization();

const element = computed(() => {
	const id = store?.editPointsElementId.value;
	return id ? props.activeSlide?.elements.find((candidate) => candidate.id === id) : undefined;
});
const editable = computed(() => Boolean(element.value && canEditElementPoints(element.value)));

watch(
	[() => store?.editPointsElementId.value, editable],
	([id, ok]) => {
		if (id && !ok) {
			store?.exitEditPoints();
		}
	},
	{ immediate: true },
);
</script>

<template>
	<template v-if="store">
		<FreeformToolOverlay
			v-if="store.activeFreeformTool.value"
			:tool="store.activeFreeformTool.value"
			:canvas-size="canvasSize"
			:scale="scale"
			:on-commit="store.commitFreeform"
			:on-cancel="() => store?.armFreeformTool(null)"
		/>
		<EditPointsOverlay
			v-else-if="element && editable"
			:element="element"
			:canvas-size="canvasSize"
			:scale="scale"
			:hidden-commands="customization.hiddenEditPointsCommands"
			:on-commit="store.commitEditPoints"
			:on-exit="store.exitEditPoints"
		/>
	</template>
</template>

// viewers/pptx/packages/react/src/viewer/components/canvas/OutlineAuthoringLayer.tsx
import type { PptxSlide, ShapePptxElement } from 'pptx-viewer-core';
import type {
	EditPointsCommandId,
	EditPointsElementPatch,
	FreeformToolKind,
} from 'ooxml-ui/pptx';
import { canEditElementPoints } from 'ooxml-ui/pptx';
import type React from 'react';
import { useEffect } from 'react';

import { EditPointsOverlay } from './EditPointsOverlay';
import { FreeformToolOverlay } from './FreeformToolOverlay';

/** Wiring for Edit Points and the Freeform: Shape / Curve tools. */
export interface OutlineAuthoringProps {
	/** The shape in Edit Points mode, or null. */
	editPointsElementId: string | null;
	/** Edit Points menu commands the host hid. */
	hiddenEditPointsCommands?: ReadonlySet<EditPointsCommandId>;
	/** Apply one Edit Points edit (one undo step). */
	onCommitEditPoints: (elementId: string, patch: EditPointsElementPatch) => void;
	onExitEditPoints: () => void;
	/** The armed drawing tool, or null. */
	freeformTool: FreeformToolKind | null;
	/** Insert a drawn freeform (the tool then disarms). */
	onFreeformCommit: (element: ShapePptxElement) => void;
	onFreeformCancel: () => void;
}

export interface OutlineAuthoringLayerProps extends OutlineAuthoringProps {
	activeSlide: PptxSlide | undefined;
	canvasSize: { width: number; height: number };
	scale: number;
}

/**
 * Stage-level host of the two outline-authoring overlays. Leaves Edit Points
 * when its shape disappears (deleted, slide changed) or becomes locked.
 */
export function OutlineAuthoringLayer({
	activeSlide,
	canvasSize,
	scale,
	editPointsElementId,
	hiddenEditPointsCommands,
	onCommitEditPoints,
	onExitEditPoints,
	freeformTool,
	onFreeformCommit,
	onFreeformCancel,
}: OutlineAuthoringLayerProps): React.ReactElement | null {
	const element = editPointsElementId
		? activeSlide?.elements.find((candidate) => candidate.id === editPointsElementId)
		: undefined;
	const editable = Boolean(element && canEditElementPoints(element));

	useEffect(() => {
		if (editPointsElementId && !editable) {
			onExitEditPoints();
		}
	}, [editPointsElementId, editable, onExitEditPoints]);

	if (freeformTool) {
		return (
			<FreeformToolOverlay
				tool={freeformTool}
				canvasSize={canvasSize}
				scale={scale}
				onCommit={onFreeformCommit}
				onCancel={onFreeformCancel}
			/>
		);
	}
	if (element && editable) {
		return (
			<EditPointsOverlay
				element={element}
				canvasSize={canvasSize}
				scale={scale}
				hiddenCommands={hiddenEditPointsCommands}
				onCommit={onCommitEditPoints}
				onExit={onExitEditPoints}
			/>
		);
	}
	return null;
}
