// viewers/pptx/packages/svelte/src/viewer/components/DialogFooter.svelte
<script lang="ts">
	/**
	 * DialogFooter: thin adapter around the shared `pptx-ui-dialog-footer`, the
	 * Cancel / OK / primary row at the bottom of a dialog. The dialog shell, its
	 * backdrop and dismissal stay in the dialog component; this routes the
	 * activated action id.
	 */
	import type { DialogFooterAction, DialogFooterRequestEvent } from 'ooxml-ui/pptx';

	const { actions, onaction }: {
		actions: readonly DialogFooterAction[];
		onaction: (id: string) => void;
	} = $props();
</script>

<pptx-ui-dialog-footer
	state={{ actions }}
	ondialog-footer-request={(event: DialogFooterRequestEvent) => onaction(event.detail.id)}
></pptx-ui-dialog-footer>

// viewers/pptx/packages/vue/src/viewer/components/DialogFooter.vue
<script setup lang="ts">
/**
 * DialogFooter: thin adapter around the shared `pptx-ui-dialog-footer`, the
 * Cancel / OK / primary row at the bottom of a dialog. The dialog shell
 * (`ModalDialog`) keeps the backdrop, focus trap and dismissal; this re-emits
 * the activated action id.
 */
import type { DialogFooterAction, DialogFooterRequestEvent } from 'ooxml-ui/pptx';
import { computed } from 'vue';

const props = defineProps<{ actions: readonly DialogFooterAction[] }>();
const emit = defineEmits<{ action: [id: string] }>();
const state = computed(() => ({ actions: props.actions }));
</script>

<template>
	<pptx-ui-dialog-footer
		:state.prop="state"
		@dialog-footer-request="emit('action', ($event as DialogFooterRequestEvent).detail.id)"
	/>
</template>
