// viewers/pptx/packages/svelte/src/viewer/components/ElementRenderer.svelte
<script lang="ts">
	/**
	 * ElementRenderer: a thin dispatcher over the `PptxElement` discriminated
	 * union (Svelte port of Vue's `ElementRenderer`). Real renderers: group
	 * (recursive), image/picture, connector, text/shape, table, chart,
	 * smartArt, media, ink, ole, contentPart, zoom, and model3d. Only
	 * `unknown` still falls through to the typed placeholder.
	 */
	import { hasShapeProperties, hasTextProperties } from 'pptx-viewer-core';
	import { build3DExtrusionData, buildParagraphs, buildTextStyleOverrideCss, getGroupChildParentFill, getOverflowSegments, hasTextWarp, inlineElementPointerEvents, isElementHidden, isEquationOnlyText, isTemplateElement, placeholderPromptDescriptor, shouldRenderHitTarget } from 'ooxml-ui/pptx';

	import { getContainerStyle, getElementHitTargetStyle, getShapeBoxStyle, getShapeFillStrokeStyle, getTextBlockStyle, mergeStyles, styleToString } from '../style';
	import { getFieldContextGetter } from '../state/field-context';
	import { getSlideElementsGetter } from '../state/slide-elements';
	import {
		getPresentationElementStatesGetter,
		usePresentationElementState,
	} from '../state/presentation-element-states-context';
	// Self-import: groups recurse into this same component (Svelte 5 pattern).
	// eslint-disable-next-line import/no-self-import
	import ElementRenderer from './ElementRenderer.svelte';
	import ChartView from './ChartView.svelte';
	import ConnectorView from './ConnectorView.svelte';
	import DuotoneFilterDefs from './DuotoneFilterDefs.svelte';
	import ShapeEffectOverlay from './ShapeEffectOverlay.svelte';
	import EquationView from './EquationView.svelte';
	import { useRendering3DFlags } from '../state/rendering-3d-flags-context';
	import Extrusion3D from './Extrusion3D.svelte';
	import ContentPartView from './ContentPartView.svelte';
	import ImageBox from './ImageBox.svelte';
	import InkView from './InkView.svelte';
	import MediaBox from './MediaBox.svelte';
	import Model3dView from './Model3dView.svelte';
	import OleView from './OleView.svelte';
	import PlaceholderElement from './PlaceholderElement.svelte';
	import SmartArt3DView from './SmartArt3DView.svelte';
	import SmartArtView from './SmartArtView.svelte';
	import TableView from './TableView.svelte';
	import TextBlock from './TextBlock.svelte';
	import ZoomView from './ZoomView.svelte';
	import WordArtText from './WordArtText.svelte';
	import type { ElementRendererProps } from './props';

	const { element, mediaDataUrls, zIndex, presenting = false, interactive = false, marked = false, editTemplateMode = false, editingElementId = null, editable = false, selectedElementIds, parentGroupFill, ontablecellcommit, onsmartartnodecommit, onsmartartnodefill, onchartpointcommit, ontableresizecolumns, ontableresizerow }: ElementRendererProps =
		$props();
	/** Whether THIS element is part of the current selection; see `ElementRendererProps.selectedElementIds`. */
	const isSelected = $derived(selectedElementIds?.includes(element.id) ?? false);
	/** This exact element is open in the element-level inline text editor right now. */
	const isBeingInlineEdited = $derived(element.id === editingElementId);
	/**
	 * Whether THIS element takes part in the neutral element contract
	 * (`data-pptx-element="true"`) and in pointer interaction.
	 *
	 * Forwarded to every delegated view, not just the branches that render their
	 * own box here: Svelte has no attribute fallthrough, so a view that is not
	 * handed this flag cannot mark its root, and its element type drops out of
	 * the contract entirely (charts and tables painted correctly while being
	 * invisible to anything that enumerates or hit-tests elements by the marker).
	 */
	const elementInteractive = $derived(interactive && (!isTemplateElement(element) || editTemplateMode));
	/**
	 * The inline pointer-events value for this element's own box, or `undefined`
	 * for "write nothing and let the stylesheet decide".
	 *
	 * Off-stage the inline value is the only thing that tells a locked template
	 * node it is locked. During a show it must stay absent in BOTH directions:
	 * `render/presentation-hit-test` makes the whole stage transparent and then
	 * re-enables only what owns its own click, and an inline value of either
	 * `none` or `auto` outranks that stylesheet. Writing `auto` here (what this
	 * branch used to do, since the show stage renders interactive) left every
	 * piece of scenery clickable, so a shape drawn over an Action Setting could
	 * swallow the click meant for it.
	 */
	const rootPointerEvents = $derived(inlineElementPointerEvents({ interactive: elementInteractive, presenting }));
	/**
	 * The same decision as a style map, so a box can MERGE it instead of spreading
	 * a key over its base map. `getShapeBoxStyle` already writes `none` for an
	 * unfilled, textless FRAME shape (PowerPoint hit-tests one on its outline only,
	 * and `ShapeEffectOverlay` paints the transparent `pointer-events: stroke` band
	 * that opts the outline back in), and `{ ...base, pointerEvents: undefined }`
	 * would drop that declaration rather than leave it alone.
	 */
	const rootPointerEventsStyle = $derived(rootPointerEvents ? { pointerEvents: rootPointerEvents } : undefined);
	/**
	 * Whether THIS element's root carries `data-pptx-element="true"`. Wider than
	 * `elementInteractive`: an interaction-locked template (master/layout)
	 * element on the main canvas keeps the marker (it is still a rendered slide
	 * element carrying the contract), it only loses pointer interactivity.
	 */
	const elementMarked = $derived(interactive || marked);
	/**
	 * The fill handed to this group's `a:grpFill` children (undefined for
	 * non-groups): its own, or the one this group inherited when it has none,
	 * since `a:grpFill` resolves against the nearest ANCESTOR with a fill.
	 */
	const childParentGroupFill = $derived(getGroupChildParentFill(element, parentGroupFill));

	/**
	 * Native-animation playback state for this element (present only during a
	 * running presentation). Drives the staged chart / SmartArt build reveal and
	 * the `p:animClr` fill / stroke relinquish; read from the element-states
	 * context so editor / read-only rendering (context absent) is unaffected.
	 */
	const animationState = $derived(usePresentationElementState(element.id));
	/**
	 * A font-style emphasis effect (Bold Flash, Bold Reveal, Underline, Change
	 * Font Style/Size) overrides the runs' own inline bold/italic/underline/
	 * size, which plain CSS inheritance cannot reach (the runs declare those
	 * unconditionally). See `animation-text-style-css.ts`. NOT gated on
	 * `hasTextProperties`: a table cell, a chart title/label/legend, and a
	 * SmartArt node caption all animate this way too, and shared's selector
	 * already scopes itself to this element's `data-element-id`.
	 */
	const textStyleOverrideCss = $derived(buildTextStyleOverrideCss(element.id, animationState?.textStyle));
	// Captured at init: `getContext` only resolves during component
	// initialisation, so reading it inside the `$derived` below returned nothing
	// and the text-build split never ran.
	const getAllAnimStates = getPresentationElementStatesGetter();
	/** Whole map, so a staged text build can find its `::c` / `::w` sub-states. */
	const allAnimStates = $derived(getAllAnimStates?.());

	/**
	 * The host's resolved 3D flags (provided by PowerPointViewer). Charts
	 * resolve their own `<pptx-three-view>` spec inside `ChartView`; only the
	 * SmartArt branch below is decided here.
	 */
	const getRendering3DFlags = useRendering3DFlags();
	const smartArt3D = $derived(getRendering3DFlags().smartArt3D);

	const isShapeLike = $derived(element.type === 'text' || element.type === 'shape');
	const isImageLike = $derived(element.type === 'picture' || element.type === 'image');

	// Captured at init for the same reason as the animation states above:
	// `getContext` only resolves during component initialisation, so the getter
	// is taken here and invoked inside the `$derived` to stay reactive.
	const getFieldContext = getFieldContextGetter();
	/**
	 * OOXML field-substitution context (slide number, date/time, header/footer,
	 * slide title, document properties), provided by the viewer root and
	 * re-pointed per slide by `SlideStage`. Without it a slide-number run renders
	 * its authored placeholder ("Slide #") instead of the resolved "Slide 1".
	 */
	const fieldContext = $derived(getFieldContext?.());

	// Captured at init for the same reason as the field context above.
	const getSlideElements = getSlideElementsGetter();
	/**
	 * The slice of an `a:linkedTxbx` chain's text this box renders, or
	 * `undefined` when the element is not in a chain (the overwhelmingly common
	 * case, resolved by a single field check inside the shared helper).
	 */
	const linkedSegments = $derived(getOverflowSegments(element, getSlideElements?.()));

	/** Rendered paragraphs (runs + bullet/indent), built by shared logic. */
	const paragraphs = $derived(buildParagraphs(element, fieldContext, linkedSegments));
	const hasText = $derived(
		paragraphs.some((p) => p.runs.length > 0 || p.bulletMarker !== undefined),
	);
	/**
	 * An empty inherited placeholder's greyed-out authoring hint ("Click to add
	 * title"), shown only on the editing canvas (`editable`) and only while the
	 * element carries no real text of its own. `placeholderPromptDescriptor`
	 * (shared) is the one place that decides "edit surface or not" so present
	 * mode, export, and thumbnails never leak the hint (unlike a render surface
	 * that reused the editor's text path unconditionally).
	 */
	const promptDescriptor = $derived(
		editable && !hasText ? placeholderPromptDescriptor(element, 'edit') : null,
	);
	/**
	 * A PURE equation box (OMML and nothing else) delegates wholesale to
	 * `EquationView`, which centres the maths in the shape. A body that mixes
	 * prose with an inline `m:oMath` renders through the paragraph path instead,
	 * where shared emits the equation as a run in its authored position: sending
	 * it here dropped every word around it.
	 */
	const hasEquation = $derived(
		hasTextProperties(element) && isEquationOnlyText(element.textSegments),
	);
	const warpedText = $derived(hasTextWarp(element));
	/** Selection Pane visibility; see the leading branch of the markup below. */
	const isHidden = $derived(isElementHidden(element));
	const extrusion = $derived.by(() => {
		const style = hasShapeProperties(element) ? element.shapeStyle : undefined;
		return build3DExtrusionData(
			style?.shape3d,
			style?.scene3d,
			style?.fillColor,
			element.width,
			element.height,
		);
	});
	/**
	 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE) shape:
	 * a bigger, invisible, centred click/drag target, kept separate from the
	 * painted box (`getShapeBoxStyle`, now always the authored size) so a thin
	 * authored line never paints as a thick bar in read-only rendering (issue
	 * #285). Never rendered while presenting: nothing on the show stage is
	 * draggable or selectable. `undefined` on a read-only surface (`editable`
	 * false) and when the authored box already meets the minimum size.
	 */
	const hitTarget = $derived(
		shouldRenderHitTarget(editable, presenting) ? getElementHitTargetStyle(element) : undefined,
	);
</script>

{#if isHidden}
	<!--
		Hidden via the Selection Pane: draw nothing, exactly as PowerPoint does.
		This leads the chain so one empty branch suppresses every element type at
		once. Rendering nothing (rather than an invisible box) is what keeps the
		element out of hit-testing, the tab order and the export raster; it stays
		listed in and selectable from the Selection Pane, which reads the slide
		model rather than the DOM.
	-->
{:else if element.type === 'group'}
	<!-- Group: recurse into children. -->
	<div
		class="pptx-svelte-element pptx-svelte-group"
		style={styleToString(
				mergeStyles(
					getContainerStyle(element, zIndex),
					getShapeFillStrokeStyle(element),
					rootPointerEventsStyle,
				),
			)}
		data-element-id={element.id}
		data-pptx-element={elementMarked ? 'true' : undefined}
	>
		<!-- A group paints no fill/outline of its own, but `p:grpSpPr/a:effectLst`
		     DOES carry a shadow/glow/soft-edge for the group's own composite
		     raster (the `filter`/`overflow` merged into the style above from
		     `getShapeFillStrokeStyle`) and a reflection (parsed onto
		     `groupEffectStyle`) that mirrors the whole group subtree, so this
		     still needs mounting. -->
		<!-- Interaction-only hit target for a degenerate group; see `hitTarget`. -->
		{#if hitTarget}
			<div aria-hidden="true" data-pptx-hit-target="true" style={styleToString(hitTarget)}></div>
		{/if}
		<ShapeEffectOverlay {element} {mediaDataUrls} {zIndex} />
		{#each element.children ?? [] as child, i (child.id)}
			<ElementRenderer element={child} {mediaDataUrls} zIndex={i} {presenting} {interactive} {marked} {editTemplateMode} {editingElementId} {editable} {selectedElementIds} parentGroupFill={childParentGroupFill} {ontablecellcommit} {onsmartartnodecommit} {onsmartartnodefill} {onchartpointcommit} {ontableresizecolumns} {ontableresizerow} />
		{/each}
	</div>
{:else if isImageLike}
	<ImageBox {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if element.type === 'connector'}
	<ConnectorView {element} {mediaDataUrls} {zIndex} {animationState} interactive={elementInteractive} marked={elementMarked} />
{:else if element.type === 'table'}
	<TableView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {ontablecellcommit} {ontableresizecolumns} {ontableresizerow} {editable} {presenting} />
{:else if element.type === 'chart'}
	<ChartView {element} {mediaDataUrls} {zIndex} {animationState} interactive={elementInteractive} marked={elementMarked} selected={isSelected} {onchartpointcommit} {editable} {presenting} />
{:else if element.type === 'smartArt' && smartArt3D}
	<SmartArt3DView {element} {mediaDataUrls} {zIndex} {animationState} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} {onsmartartnodecommit} {onsmartartnodefill} />
{:else if element.type === 'smartArt'}
	<SmartArtView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {animationState} {onsmartartnodecommit} {onsmartartnodefill} {editable} {presenting} />
{:else if element.type === 'media'}
	<MediaBox {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'ink'}
	<InkView {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'ole'}
	<OleView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if element.type === 'contentPart'}
	<ContentPartView {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'zoom'}
	<ZoomView {element} {mediaDataUrls} {zIndex} {presenting} interactive={elementInteractive} marked={elementMarked} {editable} />
{:else if element.type === 'model3d'}
	<Model3dView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if hasEquation}
	<EquationView {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{:else if isShapeLike}
	<!-- Text / shape: shared fill/stroke/effects/geometry + rich text block. -->
	<div
		class="pptx-svelte-element pptx-svelte-shape"
		style={styleToString(mergeStyles(getShapeBoxStyle(element, zIndex, parentGroupFill, animationState?.animatesFill, animationState?.animatesStroke), rootPointerEventsStyle))}
		data-element-id={element.id}
		data-pptx-element={elementMarked ? 'true' : undefined}
	>
		<DuotoneFilterDefs {element} {mediaDataUrls} {zIndex} />
		<!-- Interaction-only hit target for a degenerate shape; see `hitTarget`. -->
		{#if hitTarget}
			<div aria-hidden="true" data-pptx-hit-target="true" style={styleToString(hitTarget)}></div>
		{/if}
		<!-- A font-style emphasis effect (Bold Flash, Bold Reveal, Underline,
		     Change Font Style/Size) overrides the runs' own inline
		     bold/italic/underline/size, which plain CSS inheritance cannot reach
		     (the runs declare those unconditionally). A literal `<style>` tag's
		     content is not reactive to a mustache expression (see `ContentPartView`'s
		     `INK_REPLAY_KEYFRAMES` precedent), so this uses the `svelte:element`
		     escape hatch instead. -->
		{#if textStyleOverrideCss}<svelte:element this={'style'}>{textStyleOverrideCss}</svelte:element>{/if}
		<ShapeEffectOverlay {element} {mediaDataUrls} {zIndex} />
		{#if extrusion.hasExtrusion}<Extrusion3D data={extrusion} />{/if}
		<!-- While this element is open in the inline text editor, its live text is
		     drawn by that overlay instead; rendering it here too duplicates it
		     underneath (issue #182). -->
		{#if !isBeingInlineEdited}
			{#if warpedText}
				<WordArtText {element} {mediaDataUrls} {zIndex} />
			{:else if hasText}
				<TextBlock
					{paragraphs}
					textStyle={styleToString(getTextBlockStyle(element))}
					elementId={element.id}
					subElementAnimStates={allAnimStates}
				/>
			{:else if promptDescriptor}
				<div
					class="pptx-svelte-placeholder-prompt"
					style={styleToString(mergeStyles(getTextBlockStyle(element), promptDescriptor.style))}
				>{promptDescriptor.text}</div>
			{/if}
		{/if}
	</div>
{:else}
	<PlaceholderElement {element} {mediaDataUrls} {zIndex} interactive={elementInteractive} marked={elementMarked} {editable} {presenting} />
{/if}

<!--
	A font-style emphasis effect (Bold Flash, Bold Reveal, Underline, Change
	Font Style/Size) overrides a table cell / chart title-label-legend /
	SmartArt node caption / connector caption's own inline or SVG-attribute
	styling, which plain CSS inheritance cannot reach. Rendered here, as a
	SIBLING of the branch above rather than nested inside it: the selector
	`buildTextStyleOverrideCss` builds (`[data-element-id="<id>"] ...`)
	matches anywhere in the document, and TableView/ConnectorView/
	SmartArtView/ChartView (the last not owned by this change) do not need
	their own copy of this wiring. The plain shape/text case keeps its own
	nested copy above (inside the `isShapeLike` branch) since that predates
	this change and its test asserts the nested position.
-->
{#if !isHidden && textStyleOverrideCss && (element.type === 'table' || element.type === 'chart' || element.type === 'smartArt' || element.type === 'connector')}
	<svelte:element this={'style'}>{textStyleOverrideCss}</svelte:element>
{/if}

// viewers/pptx/packages/vue/src/viewer/components/ElementRenderer.vue
<script setup lang="ts">
import type { PptxElement, ShapeStyle } from 'pptx-viewer-core';
import { hasShapeProperties, hasTextProperties } from 'pptx-viewer-core';
import {
	buildParagraphs,
	buildTextBody3DSceneStyle,
	buildTextStyleOverrideCss,
	getGroupChildParentFill,
	getOverflowSegments,
	hasTextWarp,
	inlineElementPointerEvents,
	isElementRendered,
	isEquationOnlyText,
	placeholderPromptDescriptor,
} from 'ooxml-ui/pptx';
import type { CSSProperties } from 'vue';
import { computed } from 'vue';

import { useElementHitTargetStyle } from '../composables/element-hit-target';
import {
	getContainerStyle,
	getShapeFillStrokeStyle,
	getTextBlockStyle,
} from '../composables/element-style';
import { injectFieldContext, resolveFieldContext } from '../composables/field-context';
import { injectPresentationElementStates } from '../composables/presentation-element-states';
import { useRendering3DFlags } from '../composables/rendering-3d-flags';
import { injectSlideElements, resolveSlideElements } from '../composables/slide-elements';
import { build3DExtrusionData } from '../composables/visual-3d';
import ActionButtonGlyphOverlay from './ActionButtonGlyphOverlay.vue';
import ChartRenderer from './ChartRenderer.vue';
import ConnectorRenderer from './ConnectorRenderer.vue';
import ContentPartRenderer from './ContentPartRenderer.vue';
import DuotoneFilterDefs from './DuotoneFilterDefs.vue';
import ElementImageBox from './ElementImageBox.vue';
import ElementMediaBox from './ElementMediaBox.vue';
import EquationRenderer from './EquationRenderer.vue';
import Extrusion3DOverlay from './Extrusion3DOverlay.vue';
import InkRenderer from './InkRenderer.vue';
import Model3DRenderer from './Model3DRenderer.vue';
import OleRenderer from './OleRenderer.vue';
import ShapeEffectOverlay from './ShapeEffectOverlay.vue';
import SlideTextBlock from './SlideTextBlock.vue';
import SmartArt3DRenderer from './SmartArt3DRenderer.vue';
import SmartArtRenderer from './SmartArtRenderer.vue';
import TableRenderer from './TableRenderer.vue';
import WordArtText from './WordArtText.vue';
import ZoomRenderer from './ZoomRenderer.vue';

/**
 * ElementRenderer: Vue port of the React `ElementRenderer.tsx`.
 *
 * A thin dispatcher: renders a slide element by its `type` discriminant,
 * delegating each non-trivial type to a dedicated renderer component. The text
 * paragraph/bullet model is built by the shared, framework-agnostic
 * `buildParagraphs`; image/media branches live in their own box components.
 */
const props = defineProps<{
	element: PptxElement;
	mediaDataUrls: Map<string, string>;
	zIndex: number;
	/**
	 * When true, emit the `data-pptx-element` test/interaction hook. Only the
	 * primary editable canvas sets this; thumbnails, the sorter, the export
	 * stage and presentation mode render without it.
	 */
	interactive?: boolean;
	/**
	 * When true, emit the `data-pptx-element` marker even though `interactive` is
	 * off. The main canvas sets this for template (master/layout) elements, which
	 * are interaction-locked outside edit-template mode but are still rendered
	 * slide elements as far as the contract is concerned (mirrors React, which
	 * always tags canvas elements and gates interactivity separately).
	 */
	marked?: boolean;
	/**
	 * When true, this element belongs to the slide layout/master and the viewer is
	 * in edit-template mode: draw a visual affordance so the user can tell apart
	 * the (now editable) shared template shapes from normal slide content.
	 */
	templateEditing?: boolean;
	/** True only on the live presentation stage; enables media autoplay. */
	presenting?: boolean;
	/**
	 * The enclosing group's fill (`GroupPptxElement.groupFill`), passed down by a
	 * group's render branch so a child painted with `a:grpFill` inherits it.
	 */
	parentGroupFill?: ShapeStyle;
	/**
	 * The element currently open in the element-level inline text editor
	 * (`InlineTextEditor.vue`, mounted separately in `ViewerCanvasOverlays.vue`),
	 * or `null`/`undefined` when nothing is being edited.
	 *
	 * Mirrors React's `ElementBody.renderBody`, which swaps its static text
	 * render out for `InlineTextEditor` while `isEditing` is true rather than
	 * layering the two: without this, this renderer kept painting the element's
	 * normal text UNDERNEATH the editor overlay, and the editor's own
	 * translucent background let it show through as a duplicate, offset "text
	 * shadow" (issue #182).
	 */
	inlineEditingElementId?: string | null;
}>();

/** Host opt-in to the Three.js SmartArt renderer (provided by PowerPointViewer). */
const rendering3DFlags = useRendering3DFlags();
const smartArt3D = computed(() => rendering3DFlags.value.smartArt3D);

/** OOXML field-substitution context (slide number, date/time, etc.), provided by the viewer root. */
const fieldContextSource = injectFieldContext();

/** Sibling elements of the slide being painted, used to resolve linked text box chains. */
const slideElementsSource = injectSlideElements();

/**
 * Native-animation playback state for this element (present only during a running
 * presentation). Drives the staged chart / SmartArt build reveal and the
 * `p:animClr` fill / stroke relinquish, mirroring React's per-element
 * `animationState`. Absent (undefined) in editor / read-only rendering.
 */
const presentationStates = injectPresentationElementStates();
const animationState = computed(() => presentationStates.value.get(props.element.id));
/**
 * A font-style emphasis effect (Bold Flash, Bold Reveal, Underline, Change
 * Font Style/Size) overrides the runs' own inline bold/italic/underline/size,
 * which plain CSS inheritance cannot reach (the runs declare those
 * unconditionally). See `animation-text-style-css.ts`. NOT gated on
 * `hasTextProperties`: a table cell, a chart title/label/legend, and a
 * SmartArt node caption all animate this way too, and shared's selector
 * already scopes itself to this element's `data-element-id`, which every
 * delegated renderer's own root already carries (see `elementMarker` above).
 */
const textStyleOverrideCss = computed(() =>
	buildTextStyleOverrideCss(props.element.id, animationState.value?.textStyle),
);

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);
const shapeStyle = computed<CSSProperties>(() =>
	getShapeFillStrokeStyle(
		props.element,
		props.parentGroupFill,
		animationState.value?.animatesFill,
		animationState.value?.animatesStroke,
	),
);
/**
 * The fill handed to this group's `a:grpFill` children (undefined for
 * non-groups): its own, or - when it has none of its own - whatever this group
 * inherited, because `a:grpFill` resolves against the nearest ANCESTOR with a
 * fill rather than the immediate parent.
 */
const childParentGroupFill = computed<ShapeStyle | undefined>(() =>
	getGroupChildParentFill(props.element, props.parentGroupFill),
);
/**
 * Merge container + shape styles for the shape box. The shape style may carry a
 * 3D `transform` (from `visual-3d`); compose it with the container's
 * rotation/flip transform instead of letting the spread clobber it.
 */
const shapeDivStyle = computed<CSSProperties>(() => {
	const c = containerStyle.value;
	const s = shapeStyle.value;
	const merged: CSSProperties = { ...c, ...s };
	if (c.transform && s.transform) {
		merged.transform = `${c.transform} ${s.transform}`;
	}
	return merged;
});
const textStyle = computed<CSSProperties>(() => {
	const base = getTextBlockStyle(props.element);
	// Text body 3D scene (a:bodyPr/a:scene3d -> perspective + rotate transform),
	// mirroring React's ElementBody. Compose its transform with any existing
	// text-block transform rather than clobbering it. No-op when absent.
	const textStyleRaw = hasTextProperties(props.element) ? props.element.textStyle : undefined;
	const scene3d = buildTextBody3DSceneStyle(textStyleRaw, {
		width: props.element.width,
		height: props.element.height,
	}) as CSSProperties | undefined;
	if (!scene3d) {
		return base;
	}
	const merged: CSSProperties = { ...base, ...scene3d };
	if (base.transform && scene3d.transform) {
		merged.transform = `${String(base.transform)} ${String(scene3d.transform)}`;
	}
	return merged;
});

/**
 * CSS 3D extrusion side-panel data for shapes with `a:sp3d` extrusion depth.
 * Mirrors React's `ElementRenderer`: real extruded faces are rendered as
 * `<div>` panels (the box-shadow approximation from `getShapeFillStrokeStyle`
 * is kept underneath, as in React). `hasExtrusion` is false for the common
 * no-3D case, so the overlay renders nothing.
 */
const extrusionData = computed(() => {
	const ss = hasShapeProperties(props.element) ? props.element.shapeStyle : undefined;
	return build3DExtrusionData(
		ss?.shape3d,
		ss?.scene3d,
		ss?.fillColor,
		props.element.width,
		props.element.height,
	);
});

const isShapeLike = computed(() => props.element.type === 'text' || props.element.type === 'shape');
const isImageLike = computed(
	() => props.element.type === 'picture' || props.element.type === 'image',
);

/**
 * Whether this element is a pure equation box (OMML and nothing else). Those
 * delegate wholesale to `EquationRenderer`, which self-positions and centres
 * the maths. A body that MIXES prose with an inline `m:oMath` goes down the
 * ordinary paragraph path instead, where shared emits the equation as a run in
 * its authored position: sending it here dropped every word around it.
 */
const hasEquation = computed(
	() => hasTextProperties(props.element) && isEquationOnlyText(props.element.textSegments),
);

/** Whether this element's text is warped (WordArt / `prstTxWarp`). */
const isWarpedText = computed(() => hasTextWarp(props.element));

/**
 * The slice of an `a:linkedTxbx` chain's text this box renders, or `undefined`
 * when the element is not in a chain (the overwhelmingly common case, resolved
 * by a single field check inside the shared helper).
 */
const linkedSegments = computed(() =>
	getOverflowSegments(props.element, resolveSlideElements(slideElementsSource)),
);

/** Rendered paragraphs (runs + bullet/indent), built by shared logic. */
const paragraphs = computed(() =>
	buildParagraphs(props.element, resolveFieldContext(fieldContextSource), linkedSegments.value),
);
const hasText = computed(() =>
	paragraphs.value.some((p) => p.runs.length > 0 || p.bulletMarker !== undefined),
);
/**
 * An empty inherited placeholder's greyed-out hint ("Click to add title").
 * Shared decides the surface rule: the editing canvas only, never the live
 * stage, a thumbnail or an export.
 */
const placeholderPrompt = computed(() =>
	hasText.value
		? null
		: placeholderPromptDescriptor(
				props.element,
				props.interactive && !props.presenting ? 'edit' : 'present',
			),
);

/** Affordance class toggled on for editable template (master/layout) elements. */
const templateClass = computed(() => (props.templateEditing ? 'pptx-vue-template-editing' : null));

/**
 * The neutral element marker (`data-pptx-element="true"`) every binding
 * advertises for a rendered slide element, or `undefined` on a static surface.
 *
 * Bound on the delegated renderer components (chart, table, connector, ink,
 * ole, model3d, zoom, equation, 3D SmartArt) as well as on the branches that
 * render their own box: each of those components has a single root `<div>` that
 * already carries `data-element-id`, so Vue's attribute fallthrough lands the
 * marker on exactly that node. Without it those types painted correctly but
 * were not elements as far as the contract is concerned, so anything that
 * enumerates or hit-tests slide elements by the marker skipped them silently.
 *
 * `marked` keeps the marker on interaction-locked template-layer elements.
 */
const elementMarker = computed<'true' | undefined>(() =>
	props.interactive || props.marked ? 'true' : undefined,
);

/**
 * `pointer-events: none` on the root while this render is not interactive,
 * mirroring React's `pointer-events-none` Tailwind class and Angular's
 * `rootPointerEvents` computed (see `element-renderer.component.ts`) on the
 * same condition. `elementMarker` keeps the `data-pptx-element` contract
 * attribute on a locked template (master/layout) element so it stays
 * findable as a rendered slide element, but the attribute alone never
 * stopped clicks/drags from reaching it: without this, a layout/master
 * shape stayed fully clickable with `editTemplateMode` off, because nothing
 * on its DOM node reflected the stage's id-based lock.
 *
 * `null` while interactive (rather than clearing `pointerEvents` explicitly)
 * so the style-array merge below leaves an already-set `pointerEvents` (e.g.
 * the hollow-shape outline-only hit-test in `getShapeFillStrokeStyle`)
 * untouched instead of clobbering it.
 *
 * On a RUNNING SHOW the value is `null` too, whatever `interactive` says: the
 * rule there is `PRESENTATION_HIT_TEST_CSS`, which re-enables action shapes
 * nested inside inert ones, and an inline `none` here outranks that stylesheet.
 * Writing it made every on-slide Action Setting unclickable, so the show
 * advanced instead of following the link. `inlineElementPointerEvents` owns the
 * distinction for all five bindings.
 */
const rootPointerEvents = computed<CSSProperties | null>(() => {
	const value = inlineElementPointerEvents({
		interactive: props.interactive === true,
		presenting: props.presenting === true,
	});
	return value ? { pointerEvents: value } : null;
});

/*
 * The on-canvas action affordances (amber "has action" badge + hover link
 * tooltip) used to be rendered here, but only for the text / shape branch: this
 * component dispatches every other type straight to a per-type view whose root
 * IS the element node, so there was nowhere to put them for a picture, chart,
 * table or media element. They are now painted for ALL types at the stage
 * boundary by `applyElementActionAffordances` (see `SlideStage.vue`), from the
 * same shared rule and stylesheet the other four bindings use.
 */

/**
 * Whether this element reaches the canvas at all. The Selection Pane's eye
 * toggle writes `element.hidden` (and `p:cNvPr/@hidden` on save); a hidden
 * element is drawn nowhere, exactly as in PowerPoint. Rendering nothing (rather
 * than painting an invisible box) is what keeps it out of hit-testing, the tab
 * order and the export raster. It stays listed in and selectable from the
 * Selection Pane, which reads the slide model rather than the DOM.
 */
const isRendered = computed(() => isElementRendered(props.element));

/** This exact element is open in the element-level inline text editor right now. */
const isBeingInlineEdited = computed(() => props.element.id === props.inlineEditingElementId);

/**
 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE)
 * text/shape/group: a bigger, invisible, centred click/drag target, kept
 * separate from the painted box (`shapeDivStyle`, now always the authored
 * size) so a thin authored line never paints as a thick bar in read-only
 * rendering (issue #285). Never rendered while presenting: nothing on the
 * show stage is draggable or selectable.
 */
const hitTargetStyle = useElementHitTargetStyle(
	() => props.element,
	() => props.interactive,
	() => props.presenting,
);
</script>

<template>
	<!-- Hidden via the Selection Pane: render nothing at all (see `isRendered`). -->
	<template v-if="!isRendered" />

	<!-- Group: recurse into children. `shapeDivStyle` (not the bare
	     `containerStyle`) so the group's own `p:grpSpPr/a:effectLst` shadow /
	     glow `filter` from `getShapeFillStrokeStyle` reaches the composite. -->
	<div
		v-else-if="element.type === 'group'"
		class="pptx-vue-element pptx-vue-group"
		:class="templateClass"
		:style="[shapeDivStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="elementMarker"
	>
		<!-- Interaction-only hit-target for a degenerate group; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<!-- A group has no fill/outline/soft-edge of its own to paint here (see
		     `ShapeEffectOverlay`'s doc comment), but `p:grpSpPr/a:effectLst/a:reflection`
		     mirrors the whole group subtree, so this still needs mounting. -->
		<ShapeEffectOverlay :element="element" :media-data-urls="mediaDataUrls" />
		<ElementRenderer
			v-for="(child, i) in element.children ?? []"
			:key="child.id"
			:element="child"
			:media-data-urls="mediaDataUrls"
			:z-index="i"
			:interactive="interactive"
			:marked="marked"
			:presenting="presenting"
			:parent-group-fill="childParentGroupFill"
			:inline-editing-element-id="inlineEditingElementId"
		/>
	</div>

	<!-- Image / picture -->
	<ElementImageBox
		v-else-if="isImageLike"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:class="templateClass"
	/>

	<!-- Media (video/audio/poster) -->
	<ElementMediaBox
		v-else-if="element.type === 'media'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:class="templateClass"
	/>

	<!--
		Connector / line.

		This and every delegated renderer below take `data-pptx-element` by
		attribute fallthrough onto their single root box; see `elementMarker`.
	-->
	<ConnectorRenderer
		v-else-if="element.type === 'connector'"
		:element="element"
		:z-index="zIndex"
		:animation-state="animationState"
		:text-style-override-css="textStyleOverrideCss"
		:data-pptx-element="elementMarker"
	/>

	<!-- Delegated element renderers (same prop contract) -->
	<!--
		Table and chart take `interactive` as a real prop (they already gate their
		own editing on it) and mark their own root from it, so no fallthrough
		attribute is bound here: the table's root is a `v-if`, and a fallthrough
		attr on a branch that renders nothing warns at runtime.
	-->
	<TableRenderer
		v-else-if="element.type === 'table'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<ChartRenderer
		v-else-if="element.type === 'chart'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:animation-state="animationState"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<SmartArt3DRenderer
		v-else-if="element.type === 'smartArt' && smartArt3D"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:replay="presenting"
		:text-style="animationState?.textStyle"
		:text-style-override-css="textStyleOverrideCss"
		:data-pptx-element="elementMarker"
	/>
	<SmartArtRenderer
		v-else-if="element.type === 'smartArt'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:animation-state="animationState"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<InkRenderer
		v-else-if="element.type === 'ink'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:replay="presenting"
		:data-pptx-element="elementMarker"
	/>
	<ContentPartRenderer
		v-else-if="element.type === 'contentPart'"
		:element="element"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>
	<OleRenderer
		v-else-if="element.type === 'ole'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>
	<Model3DRenderer
		v-else-if="element.type === 'model3d'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>
	<ZoomRenderer
		v-else-if="element.type === 'zoom'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>

	<!-- Equation (OMML → MathML): equation text boxes delegate wholesale -->
	<EquationRenderer
		v-else-if="hasEquation"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>

	<!-- Text / shape -->
	<div
		v-else-if="isShapeLike"
		class="pptx-vue-element pptx-vue-shape"
		:class="templateClass"
		:style="[shapeDivStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="elementMarker"
	>
		<DuotoneFilterDefs :element="element" />
		<!-- Interaction-only hit-target for a degenerate shape; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<!--
			`<style>` is a forbidden side-effect tag in an SFC template (the compiler
			rejects it even behind `v-if`), so the override is rendered through the
			dynamic `<component :is>` escape hatch instead.
		-->
		<component :is="'style'" v-if="textStyleOverrideCss">{{ textStyleOverrideCss }}</component>
		<!-- Soft-edge <filter> defs + DAG fill-overlay tint layer + reflection. -->
		<ShapeEffectOverlay :element="element" :media-data-urls="mediaDataUrls" />
		<Extrusion3DOverlay v-if="extrusionData.hasExtrusion" :data="extrusionData" />
		<!-- Action-button glyph (home/help/sound/arrows/...); self-hides for non-buttons. -->
		<ActionButtonGlyphOverlay :element="element" />
		<!-- While this element is open in the inline text editor, its live text is
		     drawn by that overlay instead (see `isBeingInlineEdited`); rendering it
		     here too produced a duplicate, offset "text shadow" (issue #182). -->
		<template v-if="!isBeingInlineEdited">
			<WordArtText v-if="isWarpedText" :element="element" :z-index="0" />
			<SlideTextBlock
				v-else-if="hasText"
				:paragraphs="paragraphs"
				:text-style="textStyle"
				:element-id="element.id"
				:sub-element-anim-states="presentationStates"
			/>
			<div
				v-else-if="placeholderPrompt"
				class="pptx-vue-text pptx-vue-placeholder-prompt"
				:style="[textStyle, placeholderPrompt.style]"
			>
				{{ placeholderPrompt.text }}
			</div>
		</template>
	</div>

	<!-- Fallback placeholder for not-yet-ported element types -->
	<div
		v-else
		class="pptx-vue-element pptx-vue-unsupported"
		:class="templateClass"
		:style="[containerStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="elementMarker"
	>
		<div class="pptx-vue-placeholder">{{ element.type }}</div>
	</div>
</template>
