// viewers/pptx/packages/react/src/viewer/components/ElementRenderer.tsx
import { hasShapeProperties, hasTextProperties } from 'pptx-viewer-core';
import {
	buildTextStyleOverrideCss,
	elementHitTargetStyle,
	getGroupChildParentFill,
	isHollowShapeElement,
	isMediaFullscreenActive,
	resolveElementAriaAttributes,
	isElementRendered,
	inlineElementPointerEvents,
	LINK_TOOLTIP_HOST_CLASS,
	resolveElementInteractivity,
	shouldRenderHitTarget,
} from 'ooxml-ui/pptx';
import React, { useState, useCallback, useMemo } from 'react';
import type { CSSProperties } from 'react';

import { DEFAULT_TEXT_COLOR } from '../constants';
import {
	cn,
	getImageEffectsFilter,
	getImageEffectsOpacity,
	getImageRenderStyle,
	getShapeVisualStyle,
	getTextStyleForElement,
	isConnectorOrLineElement,
	isEditableTextElement,
	renderVectorShape,
} from '../utils';
import { build3DExtrusionData } from '../utils/shape-visual-3d';
import { ActionAffordances, useActionAffordance } from './elements/ActionAffordance';
import { ConnectorElementRenderer } from './elements/ConnectorElementRenderer';
import { getElementInteractionProps } from './elements/element-interaction-props';
import {
	renderDagDuotoneFilterForElement,
	getContainerStyle,
} from './elements/element-renderer-helpers';
import type { ElementRendererProps } from './elements/element-renderer-types';
import { shapeParams } from './elements/element-shape-params';
import { renderBody } from './elements/ElementBody';
import { Extrusion3DOverlay } from './elements/Extrusion3DOverlay';
import { getScopedElementHandlers } from './elements/scoped-element-handlers';
import { selectionOutlineStyle } from './elements/selection-control-artwork';
import { ShapeEffectOverlay } from './elements/ShapeEffectOverlay';
import { StaticElementRenderer } from './StaticElementRenderer';

export type { ElementRendererProps } from './elements/element-renderer-types';
export { shapeParams } from './elements/element-shape-params';

export const ElementRenderer: React.FC<ElementRendererProps> = React.memo(
	// oxlint-disable-next-line prefer-arrow-callback -- named fn gives the memo component its displayName
	function ElementRendererInner({
		element: el,
		activeSlide,
		isSelected,
		isInlineEditing,
		inlineEditingText,
		canInteract,
		presenting,
		spellCheckEnabled,
		mediaDataUrls,
		tableEditorState,
		selectionColorClass: selClr,
		showHoverBorder,
		opacity,
		templateEditing,
		zIndex,
		imageAltText,
		showResizeHandles,
		renderInk: doInk,
		renderGroups: doGrp,
		adjustmentHandles: adjH,
		onResizePointerDown,
		onAdjustmentPointerDown,
		onInlineEditChange,
		onInlineEditCommit,
		onInlineEditCancel,
		onTableCellSelect,
		onCommitCellEdit,
		onUpdateSmartArtElement,
		onFormatText,
		onResizeTableColumns,
		onResizeTableRow,
		findHighlights,
		onActionClick,
		onHyperlinkClick,
		animationState,
		presentationElementStates,
		allSlides,
		onZoomClick,
		sourceSlideIndex,
		fieldContext,
		tableStyleContext,
	}) {
		const {
			cellSelectHandler,
			cellCommitHandler,
			colResizeHandler,
			rowResizeHandler,
			smartArtUpdateHandler,
		} = getScopedElementHandlers(el.id, {
			onTableCellSelect,
			onCommitCellEdit,
			onResizeTableColumns,
			onResizeTableRow,
			onUpdateSmartArtElement,
		});
		const chartUpdateHandler = smartArtUpdateHandler;
		const { hf, fc, sw, sc } = shapeParams(el);
		// One shared verdict on what `a:spLocks` still allows, rather than five
		// bindings each reading a different subset of the flags off the element.
		const allow = resolveElementInteractivity(el);
		const backgroundAnimationState = presentationElementStates?.get(`${el.id}::pptx-bg`);
		const visualAnimationState = backgroundAnimationState ?? animationState;
		const isTxt = isEditableTextElement(el) && allow.textEditable;
		const txtSE = hasTextProperties(el) ? el.textStyle : undefined;
		// A font-style emphasis effect (Bold Flash, Bold Reveal, Underline, Change
		// Font Style/Size) overrides the runs' own inline bold/italic/underline/
		// size, which plain CSS inheritance cannot reach (the runs declare those
		// unconditionally). See `animation-text-style-css.ts`. NOT gated on
		// `hasTextProperties`: a table cell, a chart title/label/legend, and a
		// SmartArt node caption all animate this way too, and shared's selector
		// already scopes itself to this element's `data-element-id`.
		const textStyleOverrideCss = buildTextStyleOverrideCss(el.id, visualAnimationState?.textStyle);
		const ss = getShapeVisualStyle(
			el,
			hf,
			fc,
			sw,
			sc,
			visualAnimationState?.animatesFill,
			visualAnimationState?.animatesStroke,
		);
		const ts = getTextStyleForElement(el, DEFAULT_TEXT_COLOR);
		const isImg = el.type === 'picture' || el.type === 'image';
		const vs = renderVectorShape(
			el,
			isImg ? false : hf,
			fc,
			sw,
			sc,
			visualAnimationState?.animatesFill,
			visualAnimationState?.animatesStroke,
		);
		const isModel3D = el.type === 'model3d';
		const isConn = isConnectorOrLineElement(el);

		const shapeStyle3d = hasShapeProperties(el) ? el.shapeStyle : undefined;
		const extrusionData = useMemo(
			() =>
				build3DExtrusionData(shapeStyle3d?.shape3d, shapeStyle3d?.scene3d, fc, el.width, el.height),
			[shapeStyle3d?.shape3d, shapeStyle3d?.scene3d, fc, el.width, el.height],
		);

		// Authoring chrome for an Action Setting (amber badge + hover tooltip).
		// Resolved through shared so all five bindings agree on when it shows and
		// what it says; a hook, so it must sit above the early returns below.
		const actionAffordance = useActionAffordance(el, canInteract);

		const [isMediaPlaying, setIsMediaPlaying] = useState(false);
		const handleMediaPlayStateChange = useCallback((playing: boolean): void => {
			setIsMediaPlaying(playing);
		}, []);

		// The Selection Pane hid this element: draw nothing at all, exactly as
		// PowerPoint does. Skipping the subtree (rather than painting it with
		// `visibility: hidden`) is what keeps it out of hit-testing, the tab
		// order, the accessibility tree, and the html2canvas export raster. The
		// element is still listed in and selectable from the Selection Pane,
		// which reads the slide model rather than the rendered DOM.
		//
		// Placed after the hooks above, never before them: an early return at the
		// top of the component would make those hook calls conditional on a flag
		// the user toggles at runtime.
		if (!isElementRendered(el)) {
			return null;
		}

		if (isConn) {
			return (
				<ConnectorElementRenderer
					el={el}
					isSelected={isSelected}
					canInteract={canInteract}
					showResizeHandles={showResizeHandles && allow.resizable}
					showHoverBorder={showHoverBorder}
					selectionColorClass={selClr}
					opacity={opacity}
					zIndex={zIndex}
					adjustmentHandles={adjH}
					onResizePointerDown={onResizePointerDown}
					onAdjustmentPointerDown={onAdjustmentPointerDown}
					animationState={animationState}
					textStyleOverrideCss={textStyleOverrideCss}
				/>
			);
		}

		const effectiveCanInteract = canInteract && allow.selectable;
		const effectiveIsInlineEditing = isInlineEditing && canInteract && allow.textEditable;
		const canEditSmartArt = effectiveCanInteract && allow.textEditable;
		const canEditChart = effectiveCanInteract;

		const hasAction = Boolean(el.actionClick && onActionClick);
		const isZoom = el.type === 'zoom' && Boolean(onZoomClick);
		// The actionable rule itself lives in shared, so the four non-React
		// bindings (which classify in a post-render DOM pass) reach the same
		// verdict for the same deck instead of re-deriving it, or not at all.
		const aria = resolveElementAriaAttributes(el, {
			hasActionHandler: Boolean(onActionClick),
			hasHyperlinkHandler: Boolean(onHyperlinkClick),
			hasZoomHandler: Boolean(onZoomClick),
		});
		const isActionable = aria.actionable;

		// Selection / hover affordance. Drawn as an `outline` inset by 1px so it
		// lands exactly where the old 1px border did WITHOUT participating in
		// layout: as a border it was consuming 2px of every unstroked element's
		// content box (`box-sizing: border-box`), leaving shapes 2px small and
		// 1px off-origin versus PowerPoint.
		const selB = isSelected
			? `outline-1 -outline-offset-1 outline-${selClr} ring-2 ring-${selClr}/50`
			: showHoverBorder
				? 'outline-1 -outline-offset-1 outline-transparent hover:outline-primary/40'
				: '';
		const cur = effectiveIsInlineEditing
			? 'cursor-text'
			: effectiveCanInteract
				? !allow.movable
					? 'cursor-default'
					: 'cursor-move'
				: hasAction || isZoom
					? 'cursor-pointer'
					: '';

		const isPresentationPassive = presenting === true;
		const isFullscreenMedia =
			el.type === 'media' &&
			isMediaFullscreenActive({
				fullScreen: el.fullScreen,
				presenting: isPresentationPassive,
				playing: isMediaPlaying,
			});

		// Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE)
		// shape: a bigger, invisible, centred click/drag target, kept separate
		// from the painted box so a thin authored line never paints as a thick
		// bar in read-only rendering (issue #285). Never rendered while
		// presenting: nothing on the show stage is draggable or selectable.
		const hitTargetStyle = shouldRenderHitTarget(effectiveCanInteract, isPresentationPassive)
			? elementHitTargetStyle(el)
			: undefined;

		const isFocusable = effectiveCanInteract || isActionable;
		const containerStyle = getContainerStyle({
			el,
			isFullscreenMedia,
			isImg: isImg || isModel3D,
			zIndex,
			opacity,
			animationState,
			shapeVisualStyle: backgroundAnimationState ? {} : ss,
			has3DExtrusion: extrusionData.hasExtrusion,
			templateEditing,
		});
		const interactionProps = getElementInteractionProps({
			element: el,
			isEditableText: isTxt,
			canInteract: effectiveCanInteract,
			isInlineEditing: effectiveIsInlineEditing,
			isActionable,
			isPresentationPassive,
			onInlineEditCancel,
			onActionClick,
		});

		return (
			<div
				data-pptx-element='true'
				data-element-id={el.id}
				// Export restores authored paint without changing the live selection
				// ring or dropping a real shape shadow on this same wrapper.
				data-export-original-outline={containerStyle.outline ?? 'none'}
				data-export-original-outline-offset={containerStyle.outlineOffset ?? '0px'}
				data-export-original-box-shadow={containerStyle.boxShadow ?? 'none'}
				// The neutral marker `PRESENTATION_INERT_CLICK_SELECTOR` keys off, so
				// a tap or swipe on an action shape never ALSO steps the show on.
				// `StaticElementRenderer` and the four non-React bindings' DOM pass
				// stamp the same attribute.
				data-pptx-action={isActionable ? 'click' : undefined}
				role={aria.role}
				aria-label={aria.label}
				aria-roledescription={aria.roleDescription}
				aria-hidden={aria.hidden ? true : undefined}
				aria-selected={isSelected ? true : undefined}
				tabIndex={isFocusable ? 0 : -1}
				className={cn(
					'absolute',
					'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500',
					cur,
					// During a show this must stay EMPTY: `PRESENTATION_HIT_TEST_CSS`
					// (injected by `PresentationStage`) owns hit-testing there, because
					// it is the only form that can re-enable an action shape nested
					// inside inert scenery - an inline `pointer-events: none` on the
					// group could never do that, and React was the one binding that
					// wrote it. Off the show stage the inline rule still applies.
					inlineElementPointerEvents({
						interactive: effectiveCanInteract || isActionable,
						presenting: presenting === true,
					}) === 'none'
						? 'pointer-events-none'
						: '',
					// An unfilled, textless shape is a FRAME: PowerPoint hit-tests it on its
					// outline only, so its interior must not swallow clicks meant for what it
					// is drawn over. ShapeEffectOverlay paints a transparent
					// pointer-events:stroke band that opts the outline back in.
					isHollowShapeElement(el) ? 'pointer-events-none' : '',
					isFullscreenMedia ? 'pointer-events-auto' : '',
					selB,
					// Shared class the tooltip's `:hover` rule keys off (see
					// `ACTION_AFFORDANCE_CSS`), replacing React's Tailwind `group/link`
					// so the four non-Tailwind bindings reveal it the same way.
					actionAffordance.showLinkTooltip && LINK_TOOLTIP_HOST_CLASS,
				)}
				style={{
					...containerStyle,
					...(isSelected ? selectionOutlineStyle(selClr) : {}),
				}}
				{...interactionProps}
			>
				{renderDagDuotoneFilterForElement(el)}
				{textStyleOverrideCss && <style>{textStyleOverrideCss}</style>}
				{hitTargetStyle && (
					<div
						aria-hidden='true'
						data-pptx-hit-target='true'
						style={hitTargetStyle as CSSProperties}
					/>
				)}
				{backgroundAnimationState ? (
					<div
						data-pptx-animation-layer='background'
						style={{
							...ss,
							position: 'absolute',
							inset: 0,
							transformOrigin: 'center',
							visibility: backgroundAnimationState.visible === false ? 'hidden' : 'visible',
							animation: backgroundAnimationState.cssAnimation,
							pointerEvents: 'none',
						}}
					>
						<ShapeEffectOverlay
							element={el}
							animatesFill={visualAnimationState?.animatesFill}
							animatesStroke={visualAnimationState?.animatesStroke}
						/>
						{extrusionData.hasExtrusion && <Extrusion3DOverlay data={extrusionData} />}
						{isImg ? null : vs}
					</div>
				) : (
					<>
						<ShapeEffectOverlay
							element={el}
							animatesFill={visualAnimationState?.animatesFill}
							animatesStroke={visualAnimationState?.animatesStroke}
						/>
						{extrusionData.hasExtrusion && <Extrusion3DOverlay data={extrusionData} />}
					</>
				)}
				{renderBody({
					el,
					isImg,
					isEditing: effectiveIsInlineEditing,
					editText: inlineEditingText,
					spellCheck: spellCheckEnabled,
					txtSE,
					txtS: ts,
					vecShape: backgroundAnimationState && !isImg ? null : vs,
					imgStyle: getImageRenderStyle(el),
					imgFilter: getImageEffectsFilter(el),
					imgOpacity: getImageEffectsOpacity(el),
					imgAlt: imageAltText,
					isTxtEl: isTxt,
					media: mediaDataUrls,
					tableSt: tableEditorState,
					isSel: isSelected,
					doInk,
					doGrp,
					renderGroupChild: (child, index) => (
						<StaticElementRenderer
							key={child.id}
							element={child}
							activeSlide={activeSlide}
							allSlides={allSlides}
							mediaDataUrls={mediaDataUrls}
							sourceSlideIndex={sourceSlideIndex}
							zIndex={index}
							// A morph pairs a `!!`-named shape across a grouping boundary
							// (shared `morph-flatten`) and keys the animation by the
							// CHILD's id, so the child needs both its own animation and a
							// `data-element-id` to be addressable - the group node alone
							// cannot express a child moving independently of its siblings.
							animation={presentationElementStates?.get(child.id)?.cssAnimation}
							exposeElementId
							parentGroupFill={getGroupChildParentFill(el)}
							// A grouped child keeps its own `a:hlinkClick`; PowerPoint
							// treats it as an individually clickable target even though
							// the group is a single selectable object. Only wire it up
							// where the group itself is not the action target, so a
							// child link cannot shadow one set on the group.
							onActionClick={el.actionClick ? undefined : onActionClick}
							actionRequiresModifier={effectiveCanInteract}
						/>
					),
					onEditChange: onInlineEditChange,
					onCommit: onInlineEditCommit,
					onCancel: onInlineEditCancel,
					onCellSel: cellSelectHandler,
					onCellCommit: cellCommitHandler,
					onColResize: colResizeHandler,
					onRowResize: rowResizeHandler,
					findHl: findHighlights,
					onHyperlinkClick,
					isPresentationPassive,
					// Same rule as the other four bindings: the hint belongs to the
					// editable canvas, not to a read-only viewer or the show stage.
					placeholderPromptMode: canInteract && !isPresentationPassive ? 'edit' : 'present',
					handleMediaPlayStateChange,
					presentationElementStates,
					slideElements: activeSlide?.elements,
					allSlides,
					onZoomClick,
					sourceSlideIndex,
					fieldContext,
					tableStyleContext,
					canEditSmartArt,
					onUpdateSmartArtElement: smartArtUpdateHandler,
					canEditChart,
					onUpdateChartElement: chartUpdateHandler,
					onFormatText,
				})}
				<ActionAffordances affordance={actionAffordance} />
				{/* Resize/rotate/adjustment handles do NOT render here. This div
				    carries the preset's `clip-path` (`shapeVisualStyle`'s clipPath
				    cascade for a non-rectangular preset like `rightArrow`), which
				    excludes every DESCENDANT from hit-testing wherever it falls
				    outside the polygon, not just from paint. An adjustment handle is
				    deliberately measured onto a preset geometry VERTEX (PowerPoint's
				    own convention), and for a preset like `rightArrow` that vertex
				    sits exactly on a sharp convex corner of the clip polygon, so a
				    handle nested here had roughly half its hit area, including its
				    own centre, excluded from hit-testing: pointer events fell
				    through to whatever was drawn underneath instead of reaching the
				    handle (`canvas-interaction.spec.ts`: "dragging the second handle
				    of a multi-adjust preset moves it, not the first"). There is no
				    per-descendant CSS escape from an ancestor's `clip-path`, so
				    `SlideCanvas` renders `SelectionHandleOverlay` as an UNCLIPPED
				    stage-level sibling of this div for the selected element instead,
				    the same place `ConnectorEndpointOverlay` and `MotionPathOverlay`
				    already live. This div's own class/style pointer-events rules
				    (see above) are untouched by that: they still exist to make
				    exactly the shape's own silhouette clickable, which is a
				    different, unrelated concern from where its auxiliary handle UI
				    paints. */}
			</div>
		);
	},
);

// viewers/pptx/packages/vue/src/viewer/components/ElementRenderer.vue
<script setup lang="ts">
import type { PptxElement, ShapeStyle } from 'pptx-viewer-core';
import { hasShapeProperties, hasTextProperties } from 'pptx-viewer-core';
import {
	buildParagraphs,
	buildTextBody3DSceneStyle,
	buildTextStyleOverrideCss,
	getGroupChildParentFill,
	getOverflowSegments,
	hasTextWarp,
	inlineElementPointerEvents,
	isElementRendered,
	isEquationOnlyText,
	placeholderPromptDescriptor,
} from 'ooxml-ui/pptx';
import type { CSSProperties } from 'vue';
import { computed } from 'vue';

import { useElementHitTargetStyle } from '../composables/element-hit-target';
import {
	getContainerStyle,
	getShapeFillStrokeStyle,
	getTextBlockStyle,
} from '../composables/element-style';
import { injectFieldContext, resolveFieldContext } from '../composables/field-context';
import { injectPresentationElementStates } from '../composables/presentation-element-states';
import { useRendering3DFlags } from '../composables/rendering-3d-flags';
import { injectSlideElements, resolveSlideElements } from '../composables/slide-elements';
import { build3DExtrusionData } from '../composables/visual-3d';
import ActionButtonGlyphOverlay from './ActionButtonGlyphOverlay.vue';
import ChartRenderer from './ChartRenderer.vue';
import ConnectorRenderer from './ConnectorRenderer.vue';
import ContentPartRenderer from './ContentPartRenderer.vue';
import DuotoneFilterDefs from './DuotoneFilterDefs.vue';
import ElementImageBox from './ElementImageBox.vue';
import ElementMediaBox from './ElementMediaBox.vue';
import EquationRenderer from './EquationRenderer.vue';
import Extrusion3DOverlay from './Extrusion3DOverlay.vue';
import InkRenderer from './InkRenderer.vue';
import Model3DRenderer from './Model3DRenderer.vue';
import OleRenderer from './OleRenderer.vue';
import ShapeEffectOverlay from './ShapeEffectOverlay.vue';
import SlideTextBlock from './SlideTextBlock.vue';
import SmartArt3DRenderer from './SmartArt3DRenderer.vue';
import SmartArtRenderer from './SmartArtRenderer.vue';
import TableRenderer from './TableRenderer.vue';
import WordArtText from './WordArtText.vue';
import ZoomRenderer from './ZoomRenderer.vue';

/**
 * ElementRenderer: Vue port of the React `ElementRenderer.tsx`.
 *
 * A thin dispatcher: renders a slide element by its `type` discriminant,
 * delegating each non-trivial type to a dedicated renderer component. The text
 * paragraph/bullet model is built by the shared, framework-agnostic
 * `buildParagraphs`; image/media branches live in their own box components.
 */
const props = defineProps<{
	element: PptxElement;
	mediaDataUrls: Map<string, string>;
	zIndex: number;
	/**
	 * When true, emit the `data-pptx-element` test/interaction hook. Only the
	 * primary editable canvas sets this; thumbnails, the sorter, the export
	 * stage and presentation mode render without it.
	 */
	interactive?: boolean;
	/**
	 * When true, emit the `data-pptx-element` marker even though `interactive` is
	 * off. The main canvas sets this for template (master/layout) elements, which
	 * are interaction-locked outside edit-template mode but are still rendered
	 * slide elements as far as the contract is concerned (mirrors React, which
	 * always tags canvas elements and gates interactivity separately).
	 */
	marked?: boolean;
	/**
	 * When true, this element belongs to the slide layout/master and the viewer is
	 * in edit-template mode: draw a visual affordance so the user can tell apart
	 * the (now editable) shared template shapes from normal slide content.
	 */
	templateEditing?: boolean;
	/** True only on the live presentation stage; enables media autoplay. */
	presenting?: boolean;
	/**
	 * The enclosing group's fill (`GroupPptxElement.groupFill`), passed down by a
	 * group's render branch so a child painted with `a:grpFill` inherits it.
	 */
	parentGroupFill?: ShapeStyle;
	/**
	 * The element currently open in the element-level inline text editor
	 * (`InlineTextEditor.vue`, mounted separately in `ViewerCanvasOverlays.vue`),
	 * or `null`/`undefined` when nothing is being edited.
	 *
	 * Mirrors React's `ElementBody.renderBody`, which swaps its static text
	 * render out for `InlineTextEditor` while `isEditing` is true rather than
	 * layering the two: without this, this renderer kept painting the element's
	 * normal text UNDERNEATH the editor overlay, and the editor's own
	 * translucent background let it show through as a duplicate, offset "text
	 * shadow" (issue #182).
	 */
	inlineEditingElementId?: string | null;
}>();

/** Host opt-in to the Three.js SmartArt renderer (provided by PowerPointViewer). */
const rendering3DFlags = useRendering3DFlags();
const smartArt3D = computed(() => rendering3DFlags.value.smartArt3D);

/** OOXML field-substitution context (slide number, date/time, etc.), provided by the viewer root. */
const fieldContextSource = injectFieldContext();

/** Sibling elements of the slide being painted, used to resolve linked text box chains. */
const slideElementsSource = injectSlideElements();

/**
 * Native-animation playback state for this element (present only during a running
 * presentation). Drives the staged chart / SmartArt build reveal and the
 * `p:animClr` fill / stroke relinquish, mirroring React's per-element
 * `animationState`. Absent (undefined) in editor / read-only rendering.
 */
const presentationStates = injectPresentationElementStates();
const animationState = computed(() => presentationStates.value.get(props.element.id));
/**
 * A font-style emphasis effect (Bold Flash, Bold Reveal, Underline, Change
 * Font Style/Size) overrides the runs' own inline bold/italic/underline/size,
 * which plain CSS inheritance cannot reach (the runs declare those
 * unconditionally). See `animation-text-style-css.ts`. NOT gated on
 * `hasTextProperties`: a table cell, a chart title/label/legend, and a
 * SmartArt node caption all animate this way too, and shared's selector
 * already scopes itself to this element's `data-element-id`, which every
 * delegated renderer's own root already carries (see `elementMarker` above).
 */
const textStyleOverrideCss = computed(() =>
	buildTextStyleOverrideCss(props.element.id, animationState.value?.textStyle),
);

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);
const shapeStyle = computed<CSSProperties>(() =>
	getShapeFillStrokeStyle(
		props.element,
		props.parentGroupFill,
		animationState.value?.animatesFill,
		animationState.value?.animatesStroke,
	),
);
/**
 * The fill handed to this group's `a:grpFill` children (undefined for
 * non-groups): its own, or - when it has none of its own - whatever this group
 * inherited, because `a:grpFill` resolves against the nearest ANCESTOR with a
 * fill rather than the immediate parent.
 */
const childParentGroupFill = computed<ShapeStyle | undefined>(() =>
	getGroupChildParentFill(props.element, props.parentGroupFill),
);
/**
 * Merge container + shape styles for the shape box. The shape style may carry a
 * 3D `transform` (from `visual-3d`); compose it with the container's
 * rotation/flip transform instead of letting the spread clobber it.
 */
const shapeDivStyle = computed<CSSProperties>(() => {
	const c = containerStyle.value;
	const s = shapeStyle.value;
	const merged: CSSProperties = { ...c, ...s };
	if (c.transform && s.transform) {
		merged.transform = `${c.transform} ${s.transform}`;
	}
	return merged;
});
const textStyle = computed<CSSProperties>(() => {
	const base = getTextBlockStyle(props.element);
	// Text body 3D scene (a:bodyPr/a:scene3d -> perspective + rotate transform),
	// mirroring React's ElementBody. Compose its transform with any existing
	// text-block transform rather than clobbering it. No-op when absent.
	const textStyleRaw = hasTextProperties(props.element) ? props.element.textStyle : undefined;
	const scene3d = buildTextBody3DSceneStyle(textStyleRaw, {
		width: props.element.width,
		height: props.element.height,
	}) as CSSProperties | undefined;
	if (!scene3d) {
		return base;
	}
	const merged: CSSProperties = { ...base, ...scene3d };
	if (base.transform && scene3d.transform) {
		merged.transform = `${String(base.transform)} ${String(scene3d.transform)}`;
	}
	return merged;
});

/**
 * CSS 3D extrusion side-panel data for shapes with `a:sp3d` extrusion depth.
 * Mirrors React's `ElementRenderer`: real extruded faces are rendered as
 * `<div>` panels (the box-shadow approximation from `getShapeFillStrokeStyle`
 * is kept underneath, as in React). `hasExtrusion` is false for the common
 * no-3D case, so the overlay renders nothing.
 */
const extrusionData = computed(() => {
	const ss = hasShapeProperties(props.element) ? props.element.shapeStyle : undefined;
	return build3DExtrusionData(
		ss?.shape3d,
		ss?.scene3d,
		ss?.fillColor,
		props.element.width,
		props.element.height,
	);
});

const isShapeLike = computed(() => props.element.type === 'text' || props.element.type === 'shape');
const isImageLike = computed(
	() => props.element.type === 'picture' || props.element.type === 'image',
);

/**
 * Whether this element is a pure equation box (OMML and nothing else). Those
 * delegate wholesale to `EquationRenderer`, which self-positions and centres
 * the maths. A body that MIXES prose with an inline `m:oMath` goes down the
 * ordinary paragraph path instead, where shared emits the equation as a run in
 * its authored position: sending it here dropped every word around it.
 */
const hasEquation = computed(
	() => hasTextProperties(props.element) && isEquationOnlyText(props.element.textSegments),
);

/** Whether this element's text is warped (WordArt / `prstTxWarp`). */
const isWarpedText = computed(() => hasTextWarp(props.element));

/**
 * The slice of an `a:linkedTxbx` chain's text this box renders, or `undefined`
 * when the element is not in a chain (the overwhelmingly common case, resolved
 * by a single field check inside the shared helper).
 */
const linkedSegments = computed(() =>
	getOverflowSegments(props.element, resolveSlideElements(slideElementsSource)),
);

/** Rendered paragraphs (runs + bullet/indent), built by shared logic. */
const paragraphs = computed(() =>
	buildParagraphs(props.element, resolveFieldContext(fieldContextSource), linkedSegments.value),
);
const hasText = computed(() =>
	paragraphs.value.some((p) => p.runs.length > 0 || p.bulletMarker !== undefined),
);
/**
 * An empty inherited placeholder's greyed-out hint ("Click to add title").
 * Shared decides the surface rule: the editing canvas only, never the live
 * stage, a thumbnail or an export.
 */
const placeholderPrompt = computed(() =>
	hasText.value
		? null
		: placeholderPromptDescriptor(
				props.element,
				props.interactive && !props.presenting ? 'edit' : 'present',
			),
);

/** Affordance class toggled on for editable template (master/layout) elements. */
const templateClass = computed(() => (props.templateEditing ? 'pptx-vue-template-editing' : null));

/**
 * The neutral element marker (`data-pptx-element="true"`) every binding
 * advertises for a rendered slide element, or `undefined` on a static surface.
 *
 * Bound on the delegated renderer components (chart, table, connector, ink,
 * ole, model3d, zoom, equation, 3D SmartArt) as well as on the branches that
 * render their own box: each of those components has a single root `<div>` that
 * already carries `data-element-id`, so Vue's attribute fallthrough lands the
 * marker on exactly that node. Without it those types painted correctly but
 * were not elements as far as the contract is concerned, so anything that
 * enumerates or hit-tests slide elements by the marker skipped them silently.
 *
 * `marked` keeps the marker on interaction-locked template-layer elements.
 */
const elementMarker = computed<'true' | undefined>(() =>
	props.interactive || props.marked ? 'true' : undefined,
);

/**
 * `pointer-events: none` on the root while this render is not interactive,
 * mirroring React's `pointer-events-none` Tailwind class and Angular's
 * `rootPointerEvents` computed (see `element-renderer.component.ts`) on the
 * same condition. `elementMarker` keeps the `data-pptx-element` contract
 * attribute on a locked template (master/layout) element so it stays
 * findable as a rendered slide element, but the attribute alone never
 * stopped clicks/drags from reaching it: without this, a layout/master
 * shape stayed fully clickable with `editTemplateMode` off, because nothing
 * on its DOM node reflected the stage's id-based lock.
 *
 * `null` while interactive (rather than clearing `pointerEvents` explicitly)
 * so the style-array merge below leaves an already-set `pointerEvents` (e.g.
 * the hollow-shape outline-only hit-test in `getShapeFillStrokeStyle`)
 * untouched instead of clobbering it.
 *
 * On a RUNNING SHOW the value is `null` too, whatever `interactive` says: the
 * rule there is `PRESENTATION_HIT_TEST_CSS`, which re-enables action shapes
 * nested inside inert ones, and an inline `none` here outranks that stylesheet.
 * Writing it made every on-slide Action Setting unclickable, so the show
 * advanced instead of following the link. `inlineElementPointerEvents` owns the
 * distinction for all five bindings.
 */
const rootPointerEvents = computed<CSSProperties | null>(() => {
	const value = inlineElementPointerEvents({
		interactive: props.interactive === true,
		presenting: props.presenting === true,
	});
	return value ? { pointerEvents: value } : null;
});

/*
 * The on-canvas action affordances (amber "has action" badge + hover link
 * tooltip) used to be rendered here, but only for the text / shape branch: this
 * component dispatches every other type straight to a per-type view whose root
 * IS the element node, so there was nowhere to put them for a picture, chart,
 * table or media element. They are now painted for ALL types at the stage
 * boundary by `applyElementActionAffordances` (see `SlideStage.vue`), from the
 * same shared rule and stylesheet the other four bindings use.
 */

/**
 * Whether this element reaches the canvas at all. The Selection Pane's eye
 * toggle writes `element.hidden` (and `p:cNvPr/@hidden` on save); a hidden
 * element is drawn nowhere, exactly as in PowerPoint. Rendering nothing (rather
 * than painting an invisible box) is what keeps it out of hit-testing, the tab
 * order and the export raster. It stays listed in and selectable from the
 * Selection Pane, which reads the slide model rather than the DOM.
 */
const isRendered = computed(() => isElementRendered(props.element));

/** This exact element is open in the element-level inline text editor right now. */
const isBeingInlineEdited = computed(() => props.element.id === props.inlineEditingElementId);

/**
 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE)
 * text/shape/group: a bigger, invisible, centred click/drag target, kept
 * separate from the painted box (`shapeDivStyle`, now always the authored
 * size) so a thin authored line never paints as a thick bar in read-only
 * rendering (issue #285). Never rendered while presenting: nothing on the
 * show stage is draggable or selectable.
 */
const hitTargetStyle = useElementHitTargetStyle(
	() => props.element,
	() => props.interactive,
	() => props.presenting,
);
</script>

<template>
	<!-- Hidden via the Selection Pane: render nothing at all (see `isRendered`). -->
	<template v-if="!isRendered" />

	<!-- Group: recurse into children. `shapeDivStyle` (not the bare
	     `containerStyle`) so the group's own `p:grpSpPr/a:effectLst` shadow /
	     glow `filter` from `getShapeFillStrokeStyle` reaches the composite. -->
	<div
		v-else-if="element.type === 'group'"
		class="pptx-vue-element pptx-vue-group"
		:class="templateClass"
		:style="[shapeDivStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="elementMarker"
	>
		<!-- Interaction-only hit-target for a degenerate group; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<!-- A group has no fill/outline/soft-edge of its own to paint here (see
		     `ShapeEffectOverlay`'s doc comment), but `p:grpSpPr/a:effectLst/a:reflection`
		     mirrors the whole group subtree, so this still needs mounting. -->
		<ShapeEffectOverlay :element="element" :media-data-urls="mediaDataUrls" />
		<ElementRenderer
			v-for="(child, i) in element.children ?? []"
			:key="child.id"
			:element="child"
			:media-data-urls="mediaDataUrls"
			:z-index="i"
			:interactive="interactive"
			:marked="marked"
			:presenting="presenting"
			:parent-group-fill="childParentGroupFill"
			:inline-editing-element-id="inlineEditingElementId"
		/>
	</div>

	<!-- Image / picture -->
	<ElementImageBox
		v-else-if="isImageLike"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:class="templateClass"
	/>

	<!-- Media (video/audio/poster) -->
	<ElementMediaBox
		v-else-if="element.type === 'media'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:class="templateClass"
	/>

	<!--
		Connector / line.

		This and every delegated renderer below take `data-pptx-element` by
		attribute fallthrough onto their single root box; see `elementMarker`.
	-->
	<ConnectorRenderer
		v-else-if="element.type === 'connector'"
		:element="element"
		:z-index="zIndex"
		:animation-state="animationState"
		:text-style-override-css="textStyleOverrideCss"
		:data-pptx-element="elementMarker"
	/>

	<!-- Delegated element renderers (same prop contract) -->
	<!--
		Table and chart take `interactive` as a real prop (they already gate their
		own editing on it) and mark their own root from it, so no fallthrough
		attribute is bound here: the table's root is a `v-if`, and a fallthrough
		attr on a branch that renders nothing warns at runtime.
	-->
	<TableRenderer
		v-else-if="element.type === 'table'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<ChartRenderer
		v-else-if="element.type === 'chart'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:animation-state="animationState"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<SmartArt3DRenderer
		v-else-if="element.type === 'smartArt' && smartArt3D"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:replay="presenting"
		:text-style="animationState?.textStyle"
		:text-style-override-css="textStyleOverrideCss"
		:data-pptx-element="elementMarker"
	/>
	<SmartArtRenderer
		v-else-if="element.type === 'smartArt'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:marked="marked"
		:presenting="presenting"
		:animation-state="animationState"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<InkRenderer
		v-else-if="element.type === 'ink'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:replay="presenting"
		:data-pptx-element="elementMarker"
	/>
	<ContentPartRenderer
		v-else-if="element.type === 'contentPart'"
		:element="element"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>
	<OleRenderer
		v-else-if="element.type === 'ole'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>
	<Model3DRenderer
		v-else-if="element.type === 'model3d'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>
	<ZoomRenderer
		v-else-if="element.type === 'zoom'"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>

	<!-- Equation (OMML → MathML): equation text boxes delegate wholesale -->
	<EquationRenderer
		v-else-if="hasEquation"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:data-pptx-element="elementMarker"
	/>

	<!-- Text / shape -->
	<div
		v-else-if="isShapeLike"
		class="pptx-vue-element pptx-vue-shape"
		:class="templateClass"
		:style="[shapeDivStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="elementMarker"
	>
		<DuotoneFilterDefs :element="element" />
		<!-- Interaction-only hit-target for a degenerate shape; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<!--
			`<style>` is a forbidden side-effect tag in an SFC template (the compiler
			rejects it even behind `v-if`), so the override is rendered through the
			dynamic `<component :is>` escape hatch instead.
		-->
		<component :is="'style'" v-if="textStyleOverrideCss">{{ textStyleOverrideCss }}</component>
		<!-- Soft-edge <filter> defs + DAG fill-overlay tint layer + reflection. -->
		<ShapeEffectOverlay :element="element" :media-data-urls="mediaDataUrls" />
		<Extrusion3DOverlay v-if="extrusionData.hasExtrusion" :data="extrusionData" />
		<!-- Action-button glyph (home/help/sound/arrows/...); self-hides for non-buttons. -->
		<ActionButtonGlyphOverlay :element="element" />
		<!-- While this element is open in the inline text editor, its live text is
		     drawn by that overlay instead (see `isBeingInlineEdited`); rendering it
		     here too produced a duplicate, offset "text shadow" (issue #182). -->
		<template v-if="!isBeingInlineEdited">
			<WordArtText v-if="isWarpedText" :element="element" :z-index="0" />
			<SlideTextBlock
				v-else-if="hasText"
				:paragraphs="paragraphs"
				:text-style="textStyle"
				:element-id="element.id"
				:sub-element-anim-states="presentationStates"
			/>
			<div
				v-else-if="placeholderPrompt"
				class="pptx-vue-text pptx-vue-placeholder-prompt"
				:style="[textStyle, placeholderPrompt.style]"
			>
				{{ placeholderPrompt.text }}
			</div>
		</template>
	</div>

	<!-- Fallback placeholder for not-yet-ported element types -->
	<div
		v-else
		class="pptx-vue-element pptx-vue-unsupported"
		:class="templateClass"
		:style="[containerStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="elementMarker"
	>
		<div class="pptx-vue-placeholder">{{ element.type }}</div>
	</div>
</template>
