// viewers/pptx/packages/angular/src/viewer/equation-renderer.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import type { SafeHtml } from '@angular/platform-browser';

import type { OmmlNode } from 'ooxml-ui/pptx';
import { ommlToMathml, sanitizeMathMl } from 'ooxml-ui/pptx';

/**
 * EquationRendererComponent: Angular port of the Vue `EquationRenderer.vue`
 * (single-equation variant).
 *
 * Renders one parsed OMML equation tree as inline MathML via Angular's
 * `DomSanitizer.bypassSecurityTrustHtml`, which is required because Angular's
 * default HTML sanitizer strips `<math>` namespace markup.
 *
 * The wrapper is an inline-block `<span>` so the component flows inside a text
 * paragraph in place of a regular text run. When an equation number is
 * supplied the layout mirrors the Vue numbered-equation row: centred equation
 * with the number right-aligned (flex row, width 100%).
 *
 * Pure conversion logic lives in `omml-to-mathml.ts` (Angular-free) so it can
 * be unit-tested without TestBed.
 */
@Component({
	selector: 'pptx-equation-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [],
	template: `
		@if (equationNumber()) {
			<span class="pptx-ng-equation-numbered">
				<span class="pptx-ng-equation-number-spacer" aria-hidden="true"
					>({{ equationNumber() }})</span
				>
				<span class="pptx-ng-equation pptx-ng-equation-centered" [innerHTML]="safeMathml()"></span>
				<span class="pptx-ng-equation-number">({{ equationNumber() }})</span>
			</span>
		} @else {
			<span class="pptx-ng-equation" [innerHTML]="safeMathml()"></span>
		}
	`,
	styles: [
		`
			:host {
				display: inline-block;
				vertical-align: middle;
			}

			.pptx-ng-equation {
				display: inline-block;
				vertical-align: middle;
				font-family: 'Cambria Math', 'STIX Two Math', serif;
			}

			.pptx-ng-equation-numbered {
				display: flex;
				justify-content: space-between;
				align-items: center;
				width: 100%;
			}

			.pptx-ng-equation-centered {
				flex: 1;
				text-align: center;
			}

			.pptx-ng-equation-number-spacer {
				visibility: hidden;
				white-space: nowrap;
			}

			.pptx-ng-equation-number {
				white-space: nowrap;
				font-family: 'Cambria Math', 'STIX Two Math', serif;
			}
		`,
	],
})
export class EquationRendererComponent {
	/** Parsed OMML equation tree (the `equationXml` field of a `TextSegment`). */
	readonly equationXml = input.required<Record<string, unknown>>();

	/** Optional equation number shown right-aligned, e.g. `"1"` → `(1)`. */
	readonly equationNumber = input<string | undefined>(undefined);

	private readonly sanitizer = inject(DomSanitizer);

	/**
	 * Converts the OMML input to MathML and wraps it in a `SafeHtml` value so
	 * Angular's `[innerHTML]` binding renders the `<math>` markup instead of
	 * stripping it.
	 *
	 * `bypassSecurityTrustHtml` switches Angular's own sanitiser off, and the
	 * OMML comes from an arbitrary deck, so the markup is run through the shared
	 * `sanitizeMathMl` (DOMPurify, MathML + SVG profiles) first. That is the same
	 * guarantee the other four bindings apply at their raw-HTML sinks.
	 */
	readonly safeMathml = computed<SafeHtml>(() =>
		// `equationXml` is typed `Record<string, unknown>` on the core segment; the
		// shared converter walks it as an `OmmlNode` (core's recursive `XmlObject`).
		this.sanitizer.bypassSecurityTrustHtml(
			sanitizeMathMl(ommlToMathml(this.equationXml() as OmmlNode)),
		),
	);
}

// viewers/pptx/packages/vue/src/viewer/components/EquationRenderer.vue
<script setup lang="ts">
import type { PptxElement, TextSegment } from 'pptx-viewer-core';
import { hasTextProperties } from 'pptx-viewer-core';
import type { OmmlNode } from 'ooxml-ui/pptx';
import { convertOmmlToMathMl, sanitizeMathMl } from 'ooxml-ui/pptx';
import type { CSSProperties } from 'vue';
import { computed } from 'vue';

import { useElementHitTargetStyle } from '../composables/element-hit-target';
import { getContainerStyle } from '../composables/element-style';

/**
 * EquationRenderer: renders an element's math equation(s) as inline MathML.
 *
 * Vue port of the React equation rendering path
 * (`text-segment-helpers.tsx#renderEquationSegment`). Equations live on text
 * elements as {@link TextSegment} entries whose `equationXml` field holds the
 * parsed OMML (`m:oMathPara` / `m:oMath`) tree. Each such segment is converted
 * to MathML via {@link convertOmmlToMathMl}, sanitised, and injected with
 * `v-html`: MathML is namespaced HTML, so browsers render `<math>` natively.
 *
 * The wrapper uses {@link getContainerStyle} for absolute positioning, matching
 * every other element renderer.
 */
const props = defineProps<{
	element: PptxElement;
	mediaDataUrls?: Map<string, string>;
	zIndex: number;
	/** True only on the main editable canvas; see `hitTargetStyle`. */
	interactive?: boolean;
	/** True only on the live presentation stage; see `hitTargetStyle`. */
	presenting?: boolean;
}>();

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);

/**
 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE)
 * equation box: see `ElementRenderer`'s `hitTargetStyle` doc comment (issue
 * #285). Never rendered while presenting.
 */
const hitTargetStyle = useElementHitTargetStyle(
	() => props.element,
	() => props.interactive,
	() => props.presenting,
);

/** One rendered equation: sanitised MathML markup + optional equation number. */
interface RenderedEquation {
	key: string;
	mathml: string;
	number?: string;
}

// `sanitizeMathMl` (DOMPurify MathML+SVG wrapper with non-DOM fallback) is
// shared with React via pptx-viewer-shared (render/mathml-sanitize).

/** Extract + convert every equation segment on the element. */
const equations = computed<RenderedEquation[]>(() => {
	const el = props.element;
	if (!hasTextProperties(el)) {
		return [];
	}
	const segments: TextSegment[] = el.textSegments ?? [];
	const out: RenderedEquation[] = [];
	segments.forEach((seg, i) => {
		if (!seg.equationXml) {
			return;
		}
		const mathml = convertOmmlToMathMl(seg.equationXml as OmmlNode);
		if (!mathml) {
			return;
		}
		out.push({
			key: `${el.id}-eq-${i}`,
			mathml: sanitizeMathMl(mathml),
			number: seg.equationNumber,
		});
	});
	return out;
});

/** True when the element carries at least one renderable equation. */
const hasEquationContent = computed(() => equations.value.length > 0);
</script>

<template>
	<div
		class="pptx-vue-element pptx-vue-equation-wrapper"
		:style="containerStyle"
		:data-element-id="element.id"
	>
		<!-- Interaction-only hit-target for a degenerate equation box; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<template v-if="hasEquationContent">
			<template v-for="eq in equations" :key="eq.key">
				<!-- Numbered equation: centered with the number right-aligned. -->
				<span v-if="eq.number" class="pptx-vue-equation-numbered">
					<span class="pptx-vue-equation-number-spacer" aria-hidden="true">({{ eq.number }})</span>
					<span class="pptx-vue-equation pptx-vue-equation-centered" v-html="eq.mathml" />
					<span class="pptx-vue-equation-number">({{ eq.number }})</span>
				</span>

				<!-- Plain inline equation. -->
				<span v-else class="pptx-vue-equation" v-html="eq.mathml" />
			</template>
		</template>
	</div>
</template>

<style scoped>
.pptx-vue-equation-wrapper {
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	gap: 0.25em;
}

.pptx-vue-equation {
	display: inline-block;
	vertical-align: middle;
	font-family: 'Cambria Math', 'STIX Two Math', serif;
}

.pptx-vue-equation-numbered {
	display: flex;
	justify-content: space-between;
	align-items: center;
	width: 100%;
}

.pptx-vue-equation-centered {
	flex: 1;
	text-align: center;
}

.pptx-vue-equation-number-spacer {
	visibility: hidden;
	white-space: nowrap;
}

.pptx-vue-equation-number {
	white-space: nowrap;
	font-family: 'Cambria Math', 'STIX Two Math', serif;
}
</style>
