// viewers/pptx/packages/angular/src/viewer/master-view-crud-row.component.ts
/**
 * master-view-crud-row.component.ts: the Slide Master view sidebar's
 * Insert/Duplicate/Delete/Rename Layout+Master button row, split out of
 * `MasterViewSidebarComponent` to keep that file under the repo's 300-LOC cap.
 *
 * Selector: `pptx-master-view-crud-row`
 */
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import type { MasterViewCrudAction, MasterViewCrudActionId } from 'ooxml-ui/pptx';

@Component({
	selector: 'pptx-master-view-crud-row',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<div
			class="crud-row"
			role="group"
			[attr.aria-label]="'pptx.masterView.slideMastersTitle' | translate"
		>
			@for (action of actions(); track action.id) {
				<button
					type="button"
					class="crud-btn"
					[attr.data-testid]="'pptx-master-crud-' + action.id"
					[disabled]="!action.enabled"
					[title]="action.disabledReasonKey ? (action.disabledReasonKey | translate) : null"
					(click)="pick.emit(action.id)"
				>
					{{ action.labelKey | translate }}
				</button>
			}
		</div>
	`,
	styles: `
		.crud-row {
			display: grid;
			grid-template-columns: repeat(2, 1fr);
			gap: 4px;
			margin-bottom: 10px;
		}
		.crud-btn {
			padding: 6px 4px;
			border: 1px solid var(--pptx-border, #33334d);
			border-radius: 5px;
			background: transparent;
			color: inherit;
			font-size: 10px;
			cursor: pointer;
		}
		.crud-btn:hover:not(:disabled) {
			background: var(--pptx-accent, #33334d);
		}
		.crud-btn:disabled {
			opacity: 0.45;
			cursor: not-allowed;
		}
	`,
})
export class MasterViewCrudRowComponent {
	readonly actions = input<readonly MasterViewCrudAction[]>([]);
	readonly pick = output<MasterViewCrudActionId>();
}

// viewers/pptx/packages/vue/src/viewer/components/MasterViewCrudRow.vue
<script setup lang="ts">
/**
 * MasterViewCrudRow: the Slide Master view sidebar's Insert/Duplicate/
 * Delete/Rename Layout and Slide Master buttons.
 *
 * One button per `masterViewCrudActions` entry (`pptx-viewer-shared`), which
 * already decides enabled/disabled and why (a layout still used by a slide,
 * the presentation's last remaining master), so this row never re-derives
 * PowerPoint's own rules. Split out of `MasterViewSidebar.vue` to keep that
 * file under the repo's ~300 LOC convention.
 */
import type { MasterViewCrudAction, MasterViewCrudActionId } from 'ooxml-ui/pptx';
import { useI18n } from 'vue-i18n';

defineProps<{
	actions: MasterViewCrudAction[];
	/** i18n message for the last command's failure, or null/undefined. */
	error?: string | null;
}>();

const emit = defineEmits<{
	run: [id: MasterViewCrudActionId];
}>();

const { t } = useI18n();
</script>

<template>
	<section v-if="actions.length > 0" class="pptx-vue-master-crud">
		<button
			v-for="action in actions"
			:key="action.id"
			type="button"
			class="pptx-vue-master-crud__btn"
			:disabled="!action.enabled"
			:title="action.disabledReasonKey ? t(action.disabledReasonKey) : undefined"
			:data-testid="`pptx-master-crud-${action.id}`"
			@click="emit('run', action.id)"
		>
			{{ t(action.labelKey) }}
		</button>
		<p v-if="error" class="pptx-vue-master-crud__error" role="alert">
			{{ error }}
		</p>
	</section>
</template>

<style scoped>
.pptx-vue-master-crud {
	display: flex;
	flex-wrap: wrap;
	gap: 4px;
	margin-bottom: 8px;
}

.pptx-vue-master-crud__btn {
	padding: 3px 6px;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
	background: transparent;
	color: var(--pptx-vue-foreground, #111827);
	font-size: 10px;
	cursor: pointer;
}

.pptx-vue-master-crud__btn:hover:not(:disabled) {
	background: var(--pptx-vue-muted, #f3f4f6);
}

.pptx-vue-master-crud__btn:disabled {
	color: var(--pptx-vue-muted-foreground, #9ca3af);
	cursor: not-allowed;
	opacity: 0.6;
}

.pptx-vue-master-crud__error {
	flex-basis: 100%;
	margin: 4px 0 0;
	font-size: 10px;
	color: #ef4444;
}
</style>
