// viewers/pptx/packages/svelte/src/viewer/components/MobileSheet.svelte
<script lang="ts">
	import type { SheetPointerEventLike } from 'ooxml-ui/pptx';
	import { activateModalFocus, createSheetDismissGesture } from 'ooxml-ui/pptx';

	const { title, onclose, children }: {
		title: string;
		onclose: () => void;
		children: import('svelte').Snippet;
	} = $props();

	let dragY = $state(0);
	let dragging = $state(false);
	const gesture = createSheetDismissGesture(
		(offset, active) => {
			dragY = offset;
			dragging = active;
		},
		() => onclose(),
	);
	const pointer = (event: PointerEvent): SheetPointerEventLike => ({
		clientY: event.clientY,
		pointerId: event.pointerId,
		currentTarget: event.currentTarget as HTMLElement,
	});

	function modalFocus(node: HTMLElement): { destroy(): void } {
		const release = activateModalFocus(node, { onEscape: onclose });
		return { destroy: release };
	}

	function dragHeader(node: HTMLElement): { destroy(): void } {
		const down = (event: PointerEvent): void => {
			if (!(event.target as HTMLElement).closest('button')) {
				gesture.pointerDown(pointer(event));
			}
		};
		const move = (event: PointerEvent): void => gesture.pointerMove(pointer(event));
		const up = (event: PointerEvent): void => gesture.pointerUp(pointer(event));
		const cancel = (event: PointerEvent): void => gesture.cancel(pointer(event));
		node.addEventListener('pointerdown', down);
		node.addEventListener('pointermove', move);
		node.addEventListener('pointerup', up);
		node.addEventListener('pointercancel', cancel);
		return {
			destroy(): void {
				node.removeEventListener('pointerdown', down);
				node.removeEventListener('pointermove', move);
				node.removeEventListener('pointerup', up);
				node.removeEventListener('pointercancel', cancel);
			},
		};
	}
</script>

<div class="pptx-svelte-mobile-sheet-host" role="dialog" aria-modal="true" aria-label={title}>
	<button type="button" class="pptx-svelte-mobile-sheet-backdrop" aria-label="Close" onclick={onclose}></button>
	<section use:modalFocus class="pptx-svelte-mobile-sheet" tabindex="-1" style:transform={dragY > 0 ? `translateY(${dragY}px)` : undefined} style:transition={dragging ? 'none' : undefined}>
		<header use:dragHeader>
			<span class="pptx-svelte-mobile-sheet-handle" aria-hidden="true"></span>
			<strong>{title}</strong>
			<button type="button" aria-label="Close" onclick={onclose}>&times;</button>
		</header>
		<div class="pptx-svelte-mobile-sheet-body">{@render children()}</div>
	</section>
</div>

<style>
	.pptx-svelte-mobile-sheet-host { position: absolute; z-index: 48; inset: 0 0 56px; display: flex; align-items: end; }
	.pptx-svelte-mobile-sheet-backdrop { position: absolute; inset: 0; width: 100%; border: 0; background: rgb(0 0 0 / 40%); }
	.pptx-svelte-mobile-sheet { position: relative; display: flex; flex-direction: column; width: 100%; max-height: min(70dvh, 620px); border: 1px solid var(--pptx-border, #33334d); border-bottom: 0; border-radius: 16px 16px 0 0; background: var(--pptx-background, #11111b); box-shadow: 0 -12px 36px rgb(0 0 0 / 35%); color: var(--pptx-foreground, #e2e8f0); transition: transform 150ms ease-out; }
	.pptx-svelte-mobile-sheet header { position:relative; display: grid; justify-items: center; gap: 5px; padding: 8px 16px 10px; border-bottom: 1px solid var(--pptx-border, #33334d); cursor: grab; touch-action: none; }
	.pptx-svelte-mobile-sheet header button { position:absolute; top:8px; right:12px; display:inline-flex; align-items:center; justify-content:center; width:32px; height:32px; border:0; border-radius:4px; background:transparent; color:inherit; font-size:20px; cursor:pointer; }
	/* Touch target: matches MIN_TOUCH_TARGET_PX (44) from pptx-viewer-shared's
	   render/responsive module. This is the shared mobile bottom-sheet shell
	   (Comments, Slides, Insert, ...), so fixing it once here reaches every
	   sheet. `!important` is load-bearing: ViewerGlobalStyles.svelte's
	   document-level `:global(...)` baseline reset out-specificities this
	   plain descendant selector. */
	@media (max-width: 767px) {
		.pptx-svelte-mobile-sheet header button { width: 44px !important; height: 44px !important; }
	}
	.pptx-svelte-mobile-sheet header button:hover { background:var(--pptx-accent,#33334d); }
	.pptx-svelte-mobile-sheet-handle { width: 40px; height: 4px; border-radius: 2px; background: var(--pptx-muted-foreground, #94a3b8); opacity: .45; }
	.pptx-svelte-mobile-sheet-body { overflow: auto; padding: 12px; overscroll-behavior: contain; }
</style>

// viewers/pptx/packages/vue/src/viewer/components/MobileSheet.vue
<script setup lang="ts">
/**
 * MobileSheet - reusable slide-up bottom sheet for the Vue `pptx-vue-viewer`.
 *
 * Vue port of `packages/react/src/viewer/components/mobile/MobileSheet.tsx`:
 *   - a tap-to-close backdrop,
 *   - a rounded-top panel that animates up from the bottom,
 *   - a handle + header that form one swipe-to-dismiss grab region
 *     (drag down past the threshold to close),
 *   - Escape closes the sheet.
 *
 * Visibility is owned by the parent (`v-if="isMobile && open"`); the body is
 * scrollable and sized via dvh so it survives the mobile address-bar collapse.
 */
import { activateModalFocus, MIN_TOUCH_TARGET_PX } from 'ooxml-ui/pptx';
import { nextTick, onBeforeUnmount, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { useSheetDismissDrag } from '../composables/useSheetDismissDrag';

const { t } = useI18n();

const props = defineProps<{ open: boolean; title?: string; inspector?: boolean }>();
const emit = defineEmits<{ close: [] }>();

const { dragY, dragging, onPointerDown, onPointerMove, onPointerUp } = useSheetDismissDrag(() =>
	emit('close'),
);

const panelRef = ref<HTMLElement | null>(null);
let releaseFocus: (() => void) | undefined;
watch(
	() => props.open,
	async (open) => {
		releaseFocus?.();
		releaseFocus = undefined;
		if (open) {
			await nextTick();
			if (panelRef.value) {
				releaseFocus = activateModalFocus(panelRef.value, { onEscape: () => emit('close') });
			}
		}
	},
	{ immediate: true },
);
onBeforeUnmount(() => releaseFocus?.());
</script>

<template>
	<div v-if="open" class="pptx-vue-msheet fixed inset-0 z-[60] flex flex-col justify-end">
		<!-- Backdrop -->
		<button
			type="button"
			:aria-label="t('pptx.settings.close')"
			class="absolute inset-0 border-0 bg-black/40 backdrop-blur-[2px]"
			@click="emit('close')"
		/>

		<!-- Panel -->
		<div
			ref="panelRef"
			class="pptx-vue-msheet-panel relative flex max-h-[85dvh] flex-col rounded-t-2xl border-t border-border bg-card text-foreground shadow-2xl"
			role="dialog"
			aria-modal="true"
			:aria-label="title || t('pptx.mobileSheet.ariaLabel')"
			tabindex="-1"
			:data-pptx-inspector="props.inspector ? '' : undefined"
			:style="{
				transform: dragY > 0 ? `translateY(${dragY}px)` : undefined,
				transition: dragging ? 'none' : 'transform 150ms ease-out',
			}"
		>
			<!-- Handle + header = one swipe-to-dismiss grab region -->
			<div
				class="shrink-0 cursor-grab touch-none select-none active:cursor-grabbing"
				@pointerdown="onPointerDown"
				@pointermove="onPointerMove"
				@pointerup="onPointerUp"
				@pointercancel="onPointerUp"
			>
				<div class="flex items-center justify-center pt-2 pb-1">
					<div class="h-1 w-10 rounded-full bg-muted-foreground/40" />
				</div>
				<div
					v-if="title"
					class="flex items-center justify-between gap-2 border-b border-border/60 px-4 pb-2"
				>
					<span class="truncate text-sm font-semibold text-foreground">{{ title }}</span>
					<button
						type="button"
						class="inline-flex items-center justify-center rounded text-xl text-muted-foreground hover:bg-accent hover:text-foreground"
						:style="{ minWidth: `${MIN_TOUCH_TARGET_PX}px`, minHeight: `${MIN_TOUCH_TARGET_PX}px` }"
						:aria-label="t('pptx.settings.close')"
						@pointerdown.stop
						@click="emit('close')"
					>
						&times;
					</button>
				</div>
			</div>

			<!-- Scrollable body -->
			<div
				class="flex-1 overflow-y-auto overscroll-contain pb-[max(env(safe-area-inset-bottom),0px)]"
			>
				<slot />
			</div>
		</div>
	</div>
</template>
