// viewers/pptx/packages/angular/src/viewer/mobile-bottom-bar.component.ts
/**
 * mobile-bottom-bar.component.ts: Persistent mobile bottom action bar.
 *
 * Ported from: packages/react/src/viewer/components/mobile/MobileBottomBar.tsx
 *
 * A fixed-to-bottom bar exposing the five primary per-selection / per-slide
 * actions for mobile editing, mirroring React's slot set:
 *
 *   Slides · Insert · Format · Comments · Notes
 *
 * Each slot either opens a bottom sheet/panel (slides / format / comments /
 * notes) or triggers an action (insert). The Menu, Undo/Redo and Present
 * controls live in the compact top toolbar (`MobileToolbarComponent`).
 *
 * A thin adapter around the shared `pptx-ui-mobile-bar`, which owns the
 * `<nav aria-label="Editor actions">` (the framework-neutral accessibility
 * contract the e2e specs assert against), the no-slides gating from shared's
 * `buildBarActions`, the pressed state and the comment badge. This maps the
 * inputs onto its state and re-emits its typed intents as the outputs the
 * viewer already wires.
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	CUSTOM_ELEMENTS_SCHEMA,
	inject,
	input,
	output,
} from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

import type {
	MobileBarIntent,
	MobileBarRequestEvent,
	MobileBarViewState,
} from 'ooxml-ui/pptx';
import { translationsSignal } from './translations-signal';

/** Which mobile sheet/panel is currently active (highlights its button). */
export type MobileBarSheet = 'slides' | 'inspector' | 'comments' | 'notes' | null;

@Component({
	selector: 'pptx-mobile-bottom-bar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `<pptx-ui-mobile-bar [state]="view()" (mobile-bar-request)="request($event)" />`,
	styles: [':host { display: block; }'],
})
export class MobileBottomBarComponent {
	// ── Inputs ────────────────────────────────────────────────────────────────

	/** Total slides; every slot disables at 0. */
	readonly slideCount = input<number>(0);
	/** Comments on the active slide, rendered as a badge (capped at 99+). */
	readonly commentCount = input<number>(0);
	/** The sheet that is currently open; its slot renders active. */
	readonly activeSheet = input<MobileBarSheet>(null);

	// ── Outputs ───────────────────────────────────────────────────────────────

	/** User tapped the Slides button. */
	readonly openSlides = output<void>();
	/** User tapped Insert (quick-inserts a text box). */
	readonly insert = output<void>();
	/** User tapped the Format (inspector) button. */
	readonly openFormat = output<void>();
	/** User tapped the Comments button. */
	readonly openComments = output<void>();
	/** User tapped the Notes button. */
	readonly notes = output<void>();

	private readonly translate = inject(TranslateService);
	private readonly translations = translationsSignal(this.translate);

	private readonly emitters: Record<MobileBarIntent['id'], () => void> = {
		slides: () => this.openSlides.emit(),
		insert: () => this.insert.emit(),
		inspector: () => this.openFormat.emit(),
		comments: () => this.openComments.emit(),
		notes: () => this.notes.emit(),
	};

	protected readonly view = computed<MobileBarViewState>(() => {
		this.translations();
		return {
			slideCount: this.slideCount(),
			activeSheet: this.activeSheet(),
			commentCount: this.commentCount(),
			translate: (key, params) => this.translate.instant(key, params),
		};
	});

	protected request(event: Event): void {
		this.emitters[(event as MobileBarRequestEvent).detail.id]();
	}
}

// viewers/pptx/packages/vue/src/viewer/components/MobileBottomBar.vue
<script setup lang="ts">
/**
 * MobileBottomBar - the Vue port of React's mobile bottom navigation
 * (`packages/react/src/viewer/components/mobile/MobileBottomBar.tsx`).
 *
 * Five labelled destination tabs - Slides / Insert / Format / Comments / Notes -
 * each opening a bottom sheet (or, for Insert, quick-inserting a text box),
 * matching the navigation pattern of Office Mobile and Google Slides. The active
 * tab is tinted and carries a top pill indicator.
 *
 * Slide navigation is a horizontal swipe and zoom is a pinch (both handled on the
 * canvas), so this bar carries no prev/next or zoom controls; Present, Save and
 * the section menu live in the top `MobileToolbar`. That division mirrors React,
 * whose mobile StatusBar is hidden and whose bottom bar is purely these five
 * targets.
 *
 * A thin adapter around the shared `pptx-ui-mobile-bar`, which owns the markup, the
 * no-slides gating, the pressed state and the comment badge. Conventions vs. React:
 * function-prop callbacks become emits, and the host is fixed to the bottom edge.
 */
import type { MobileBarIntent, MobileBarRequestEvent } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { MobileActiveSheet } from '../composables/useMobileChrome';

const { t } = useI18n();

const props = withDefaults(
	defineProps<{
		/** Total number of slides in the presentation; every tab disables at 0. */
		slideCount?: number;
		/** The currently-open sheet, so its tab renders active. */
		activeSheet?: MobileActiveSheet;
		/** Number of comments on the active slide (renders a badge, capped at 99+). */
		commentCount?: number;
		/**
		 * CSS pixels the on-screen keyboard covers. When > 0 the fixed bar lifts by
		 * this amount so it stays above the keyboard instead of under it.
		 */
		keyboardInset?: number;
	}>(),
	{ slideCount: 0 },
);

const emit = defineEmits<{
	slides: [];
	insert: [];
	format: [];
	comments: [];
	notes: [];
}>();

/** The shared vocabulary calls the Format tab `inspector`. */
const EVENT_BY_ID: Record<
	MobileBarIntent['id'],
	'slides' | 'insert' | 'format' | 'comments' | 'notes'
> = {
	slides: 'slides',
	insert: 'insert',
	inspector: 'format',
	comments: 'comments',
	notes: 'notes',
};

const state = computed(() => ({
	slideCount: props.slideCount ?? 0,
	// The Vue sheet kinds use `format` where the shared bar says `inspector`.
	activeSheet:
		props.activeSheet === 'format' ? ('inspector' as const) : (props.activeSheet ?? null),
	commentCount: props.commentCount,
	translate: t,
}));

function request(event: Event): void {
	// Vue's typed `emit` is an overload set that rejects a union argument, so
	// dispatch each event name as a literal.
	switch (EVENT_BY_ID[(event as MobileBarRequestEvent).detail.id]) {
		case 'slides':
			emit('slides');
			break;
		case 'insert':
			emit('insert');
			break;
		case 'format':
			emit('format');
			break;
		case 'comments':
			emit('comments');
			break;
		case 'notes':
			emit('notes');
			break;
	}
}

/** Translate the fixed bar up above the on-screen keyboard, if one is open. */
const barStyle = computed(() => {
	const inset = props.keyboardInset ?? 0;
	if (inset <= 0) {
		return undefined;
	}
	return {
		transform: `translateY(-${inset}px)`,
		transition: 'transform 150ms ease-out',
		willChange: 'transform',
	};
});
</script>

<template>
	<pptx-ui-mobile-bar
		class="pptx-vue-mobile-bar fixed bottom-0 left-0 right-0 z-40"
		:style="barStyle"
		:state.prop="state"
		@mobile-bar-request="request"
	/>
</template>
