// viewers/pptx/packages/react/src/viewer/components/notes/NotesToolbar.tsx
import type { NotesToolbarRequestEvent } from 'ooxml-ui/pptx';
import React, { useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';

interface NotesToolbarProps {
	isRichEditEnabled: boolean;
	hasAllSlides: boolean;
	onApplyRichCommand: (command: 'bold' | 'italic' | 'underline' | 'strikeThrough') => void;
	onToggleBulletList: () => void;
	onToggleNumberedList: () => void;
	onIndent: () => void;
	onOutdent: () => void;
	onInsertLink: (url: string, displayText: string) => void;
	onPrintClick: () => void;
	onToggleRichEdit: () => void;
}

/**
 * Thin adapter around the shared `pptx-ui-notes-toolbar`: it maps panel state
 * onto the element and routes typed `notes-request` intents to the editor
 * handlers. The buttons, roving focus and hyperlink popover are shared.
 */
export function NotesToolbar(p: NotesToolbarProps): React.ReactElement {
	const { t } = useTranslation();
	const ref = useRef<HTMLElement & { state: unknown }>(null);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		host.state = {
			rich: p.isRichEditEnabled,
			canFormat: p.isRichEditEnabled,
			showPrint: p.hasAllSlides,
			translate: t,
		};
	}, [p.isRichEditEnabled, p.hasAllSlides, t]);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		const request = (event: Event) => {
			const intent = (event as NotesToolbarRequestEvent).detail;
			switch (intent.kind) {
				case 'inline':
					p.onApplyRichCommand(intent.command);
					break;
				case 'paragraph':
					if (intent.command === 'bullet') {
						p.onToggleBulletList();
					} else if (intent.command === 'numbered') {
						p.onToggleNumberedList();
					} else if (intent.command === 'indent') {
						p.onIndent();
					} else {
						p.onOutdent();
					}
					break;
				case 'link':
					p.onInsertLink(intent.url, intent.text);
					break;
				case 'print':
					p.onPrintClick();
					break;
				case 'toggle-rich':
					p.onToggleRichEdit();
			}
		};
		host.addEventListener('notes-request', request);
		return () => host.removeEventListener('notes-request', request);
	}, [p]);
	return (
		<div className='mb-1'>
			<pptx-ui-notes-toolbar ref={ref} />
		</div>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/NotesToolbar.vue
<script setup lang="ts">
import type {
	NotesInlineCommand,
	NotesParagraphCommand,
	NotesToolbarRequestEvent,
	NotesToolbarViewState,
} from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * NotesToolbar: thin adapter around the shared `pptx-ui-notes-toolbar` element.
 *
 * The element owns the buttons, order, icons, roving focus, enabled state and
 * the hyperlink popover. This component maps panel state onto it and re-emits
 * its typed intents; the parent `NotesPanel` runs them through the shared notes
 * helpers (editor, selection edits, print and history stay native).
 */
const props = defineProps<{
	isRichEnabled: boolean;
}>();

const emit = defineEmits<{
	inline: [command: NotesInlineCommand];
	paragraph: [command: NotesParagraphCommand];
	insertLink: [url: string, displayText: string];
	print: [];
	toggleRich: [];
}>();

const { t } = useI18n();

const state = computed<NotesToolbarViewState>(() => ({
	rich: props.isRichEnabled,
	canFormat: props.isRichEnabled,
	showPrint: true,
	translate: t,
}));

function request(event: Event): void {
	const intent = (event as NotesToolbarRequestEvent).detail;
	switch (intent.kind) {
		case 'inline':
			emit('inline', intent.command);
			break;
		case 'paragraph':
			emit('paragraph', intent.command);
			break;
		case 'link':
			emit('insertLink', intent.url, intent.text);
			break;
		case 'print':
			emit('print');
			break;
		case 'toggle-rich':
			emit('toggleRich');
	}
}
</script>

<template>
	<pptx-ui-notes-toolbar
		class="pptx-vue-notes-toolbar"
		:state.prop="state"
		@notes-request="request"
	></pptx-ui-notes-toolbar>
</template>
