// viewers/pptx/packages/react/src/viewer/components/OleEditorDialog.tsx
import type {
	OleNestedDeckSlideDetail,
	OlePptxElement,
	OleSheetGrid,
	PptxElement,
} from 'pptx-viewer-core';
import {
	applyOleDocumentParagraphEdit,
	applyOleNestedDeckElementTextEdit,
	applyOleSheetCellEdit,
	getOleDocumentParagraphs,
	getOleNestedDeckDetail,
	getOleSheetGrid,
	replaceOleFile,
} from 'pptx-viewer-core';
import { buildOleContentUpdatePatch, buildOleEditDialogDescriptor } from 'ooxml-ui/pptx';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuX } from 'react-icons/lu';

import { DialogFooter } from './DialogFooter';
import { OleDeckEditor, OleDocumentEditor, OleSheetGridEditor } from './OleEditorDialogTabs';

/** Props for {@link OleEditorDialog}. */
export interface OleEditorDialogProps {
	isOpen: boolean;
	onClose: () => void;
	element: OlePptxElement;
	onUpdateElement: (updates: Partial<PptxElement>) => void;
}

/**
 * "Edit content" dialog for an embedded OLE object: a spreadsheet grid,
 * document paragraph list, or nested-deck slide title list depending on
 * the payload kind (`buildOleEditDialogDescriptor`), plus a Replace File
 * action always available regardless of kind.
 *
 * Every edit commits through the same core `ole-edit-api.ts` functions
 * every other binding calls, and the same `onUpdateElement` patch API every
 * other inspector field already uses, so undo/history/collaboration sync
 * works exactly like a typed-field edit.
 */
export function OleEditorDialog({
	isOpen,
	onClose,
	element,
	onUpdateElement,
}: OleEditorDialogProps): React.ReactElement | null {
	const { t } = useTranslation();
	const dialogRef = useRef<HTMLDivElement>(null);
	const fileInputRef = useRef<HTMLInputElement>(null);
	const descriptor = buildOleEditDialogDescriptor(element);

	const [grid, setGrid] = useState<OleSheetGrid | undefined>(undefined);
	const [paragraphs, setParagraphs] = useState<string[] | undefined>(undefined);
	const [deckSlides, setDeckSlides] = useState<OleNestedDeckSlideDetail[] | undefined>(undefined);
	const [loading, setLoading] = useState(false);
	const [saveError, setSaveError] = useState(false);

	// Async edit/save handlers below settle after their own awaits, which can
	// outlive the component (dialog closed, or unmounted entirely) if the OLE
	// round-trip is slow. Guard every post-await setState with this so a late
	// resolution never dispatches into an unmounted tree.
	const mountedRef = useRef(true);
	useEffect(
		() => () => {
			mountedRef.current = false;
		},
		[],
	);

	useEffect(() => {
		if (!isOpen || !descriptor.contentTab) {
			return;
		}
		let cancelled = false;
		setLoading(true);
		const kind = descriptor.contentTab.kind;
		const load = async () => {
			if (kind === 'sheet') {
				const value = await getOleSheetGrid(element);
				if (!cancelled) {
					setGrid(value);
				}
			} else if (kind === 'document') {
				const value = await getOleDocumentParagraphs(element);
				if (!cancelled) {
					setParagraphs(value);
				}
			} else if (kind === 'deck') {
				const value = await getOleNestedDeckDetail(element);
				if (!cancelled) {
					setDeckSlides(value);
				}
			}
			if (!cancelled) {
				setLoading(false);
			}
		};
		void load();
		return () => {
			cancelled = true;
		};
		// eslint-disable-next-line react-hooks/exhaustive-deps -- re-fetch only on open/element identity, not on every render
	}, [isOpen, element]);

	const commit = useCallback(
		(updated: OlePptxElement) => {
			if (!updated.oleContentDirty) {
				return;
			}
			onUpdateElement(buildOleContentUpdatePatch(updated) as Partial<PptxElement>);
		},
		[onUpdateElement],
	);

	const handleCellEdit = useCallback(
		async (row: number, col: number, value: string) => {
			try {
				const updated = await applyOleSheetCellEdit(element, { row, col, value });
				commit(updated);
				const refreshed = await getOleSheetGrid(updated);
				if (mountedRef.current) {
					setGrid(refreshed);
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit],
	);

	const handleParagraphEdit = useCallback(
		async (index: number, text: string) => {
			try {
				const updated = await applyOleDocumentParagraphEdit(element, index, text);
				commit(updated);
				const refreshed = await getOleDocumentParagraphs(updated);
				if (mountedRef.current) {
					setParagraphs(refreshed);
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit],
	);

	const handleDeckElementEdit = useCallback(
		async (slideIndex: number, deckElementId: string, text: string) => {
			try {
				const updated = await applyOleNestedDeckElementTextEdit(
					element,
					slideIndex,
					deckElementId,
					text,
				);
				commit(updated);
				const refreshed = await getOleNestedDeckDetail(updated);
				if (mountedRef.current) {
					setDeckSlides(refreshed);
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit],
	);

	const handleReplaceFile = useCallback(
		async (file: File) => {
			try {
				const bytes = new Uint8Array(await file.arrayBuffer());
				const updated = await replaceOleFile(element, bytes, file.name);
				commit(updated);
				if (mountedRef.current) {
					onClose();
				}
			} catch {
				if (mountedRef.current) {
					setSaveError(true);
				}
			}
		},
		[element, commit, onClose],
	);

	const handleKeyDown = useCallback(
		(e: React.KeyboardEvent) => {
			if (e.key === 'Escape') {
				e.preventDefault();
				onClose();
			}
		},
		[onClose],
	);

	if (!isOpen) {
		return null;
	}

	return (
		<div
			className='fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm'
			onClick={(e) => {
				if (e.target === e.currentTarget) {
					onClose();
				}
			}}
			onKeyDown={handleKeyDown}
		>
			{/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions -- stopPropagation only */}
			<div
				ref={dialogRef}
				className='bg-background border border-border rounded-xl shadow-2xl w-[560px] max-h-[80vh] flex flex-col overflow-hidden'
				onClick={(e) => e.stopPropagation()}
				role='dialog'
				aria-modal='true'
				tabIndex={-1}
				aria-label={t(descriptor.titleKey)}
			>
				<div className='flex items-center justify-between px-5 py-3 border-b border-border'>
					<h2 className='text-sm font-semibold text-foreground'>{t(descriptor.titleKey)}</h2>
					<button
						type='button'
						onClick={onClose}
						className='p-1 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors'
						aria-label={t('pptx.settings.close')}
					>
						<LuX className='w-4 h-4' />
					</button>
				</div>

				<div className='flex-1 overflow-y-auto px-5 py-4 space-y-3 text-sm'>
					{loading && (
						<p className='text-muted-foreground text-xs'>{t('pptx.ole.editDialog.loading')}</p>
					)}
					{saveError && (
						<p className='text-destructive text-xs'>{t('pptx.ole.editDialog.saveError')}</p>
					)}

					{!loading && descriptor.contentTab?.kind === 'sheet' && (
						<OleSheetGridEditor grid={grid} onCellEdit={handleCellEdit} t={t} />
					)}
					{!loading && descriptor.contentTab?.kind === 'document' && (
						<OleDocumentEditor paragraphs={paragraphs} onEdit={handleParagraphEdit} t={t} />
					)}
					{!loading && descriptor.contentTab?.kind === 'deck' && (
						<OleDeckEditor slides={deckSlides} onEdit={handleDeckElementEdit} t={t} />
					)}
					{!descriptor.contentTab && (
						<p className='text-muted-foreground text-xs'>{t('pptx.ole.editDialog.unsupported')}</p>
					)}
				</div>

				<div className='flex items-center justify-between gap-2 px-5 py-3 border-t border-border'>
					<input
						ref={fileInputRef}
						type='file'
						className='hidden'
						onChange={(e) => {
							const file = e.target.files?.[0];
							if (file) {
								void handleReplaceFile(file);
							}
						}}
					/>
					<DialogFooter
						actions={[
							{ id: 'replace', label: t('pptx.ole.editDialog.replaceFile'), align: 'start' },
							{ id: 'save', label: t('pptx.ole.editDialog.save'), variant: 'primary' },
						]}
						onAction={(id) => (id === 'replace' ? fileInputRef.current?.click() : onClose())}
					/>
					<button
						type='button'
						onClick={onClose}
						className='px-4 py-1.5 rounded-lg text-xs font-medium bg-primary hover:bg-primary/80 text-white transition-colors'
					>
						{t('pptx.ole.editDialog.save')}
					</button>
				</div>
			</div>
		</div>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/OleEditorDialog.vue
<script setup lang="ts">
/**
 * "Edit content" dialog for an embedded OLE object: a spreadsheet grid,
 * document paragraph list, or nested-deck slide title list depending on
 * the payload kind (`buildOleEditDialogDescriptor`), plus a Replace File
 * action always available regardless of kind.
 *
 * Vue port of React's `OleEditorDialog.tsx`. Every edit commits through the
 * same core `ole-edit-api.ts` functions every other binding calls, and the
 * same `update` patch event every other inspector field already emits, so
 * undo/history/collaboration sync works exactly like a typed-field edit.
 */
import type {
	OleNestedDeckSlideDetail,
	OlePptxElement,
	OleSheetGrid,
	PptxElement,
} from 'pptx-viewer-core';
import {
	applyOleDocumentParagraphEdit,
	applyOleNestedDeckElementTextEdit,
	applyOleSheetCellEdit,
	getOleDocumentParagraphs,
	getOleNestedDeckDetail,
	getOleSheetGrid,
	replaceOleFile,
} from 'pptx-viewer-core';
import { buildOleContentUpdatePatch, buildOleEditDialogDescriptor } from 'ooxml-ui/pptx';
import { computed, onUnmounted, ref, useTemplateRef, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';
import ModalDialog from './ModalDialog.vue';
import OleDeckEditor from './OleDeckEditor.vue';
import OleDocumentEditor from './OleDocumentEditor.vue';
import OleSheetGridEditor from './OleSheetGridEditor.vue';

const props = defineProps<{
	/** Whether the dialog is open. */
	open: boolean;
	/** The OLE element being edited. */
	element: OlePptxElement;
}>();

const emit = defineEmits<{
	(e: 'update', patch: Partial<PptxElement>): void;
	(e: 'close'): void;
}>();

const { t } = useI18n();

const descriptor = computed(() => buildOleEditDialogDescriptor(props.element));

const grid = ref<OleSheetGrid | undefined>(undefined);
const paragraphs = ref<string[] | undefined>(undefined);
const deckSlides = ref<OleNestedDeckSlideDetail[] | undefined>(undefined);
const loading = ref(false);
const saveError = ref(false);
const fileInput = useTemplateRef<HTMLInputElement>('fileInput');

// The edit handlers below settle after their own awaits (a re-encode or a
// full deck save/load round-trip), which can outlive the component if it is
// unmounted first. Guard every post-await write with this so a late
// resolution never touches state of a component that is gone.
let active = true;
onUnmounted(() => {
	active = false;
});

function close(): void {
	emit('close');
}

/** Re-fetch the content-tab data whenever the dialog opens or the target element changes. */
watch(
	[() => props.open, () => props.element],
	async ([isOpen, element]) => {
		const tab = buildOleEditDialogDescriptor(element).contentTab;
		if (!isOpen || !tab) {
			return;
		}
		loading.value = true;
		const kind = tab.kind;
		if (kind === 'sheet') {
			grid.value = await getOleSheetGrid(element);
		} else if (kind === 'document') {
			paragraphs.value = await getOleDocumentParagraphs(element);
		} else if (kind === 'deck') {
			deckSlides.value = await getOleNestedDeckDetail(element);
		}
		loading.value = false;
	},
	{ immediate: true },
);

function commit(updated: OlePptxElement): void {
	if (!updated.oleContentDirty) {
		return;
	}
	emit('update', buildOleContentUpdatePatch(updated) as Partial<PptxElement>);
}

async function handleCellEdit(row: number, col: number, value: string): Promise<void> {
	try {
		const updated = await applyOleSheetCellEdit(props.element, { row, col, value });
		commit(updated);
		const refreshed = await getOleSheetGrid(updated);
		if (active) {
			grid.value = refreshed;
		}
	} catch {
		if (active) {
			saveError.value = true;
		}
	}
}

async function handleParagraphEdit(index: number, text: string): Promise<void> {
	try {
		const updated = await applyOleDocumentParagraphEdit(props.element, index, text);
		commit(updated);
		const refreshed = await getOleDocumentParagraphs(updated);
		if (active) {
			paragraphs.value = refreshed;
		}
	} catch {
		if (active) {
			saveError.value = true;
		}
	}
}

async function handleDeckElementEdit(
	slideIndex: number,
	elementId: string,
	text: string,
): Promise<void> {
	try {
		const updated = await applyOleNestedDeckElementTextEdit(
			props.element,
			slideIndex,
			elementId,
			text,
		);
		commit(updated);
		const refreshed = await getOleNestedDeckDetail(updated);
		if (active) {
			deckSlides.value = refreshed;
		}
	} catch {
		if (active) {
			saveError.value = true;
		}
	}
}

async function handleReplaceFile(file: File): Promise<void> {
	try {
		const bytes = new Uint8Array(await file.arrayBuffer());
		const updated = await replaceOleFile(props.element, bytes, file.name);
		commit(updated);
		if (active) {
			close();
		}
	} catch {
		if (active) {
			saveError.value = true;
		}
	}
}

function onFileChange(event: Event): void {
	const file = (event.target as HTMLInputElement).files?.[0];
	if (file) {
		void handleReplaceFile(file);
	}
}
</script>

<template>
	<ModalDialog :open="props.open" :title="t(descriptor.titleKey)" @close="close">
		<div class="flex w-[min(90vw,520px)] flex-col gap-3 text-sm">
			<p v-if="loading" class="text-xs text-muted-foreground">
				{{ t('pptx.ole.editDialog.loading') }}
			</p>
			<p v-if="saveError" class="text-xs text-destructive">
				{{ t('pptx.ole.editDialog.saveError') }}
			</p>

			<template v-if="!loading">
				<OleSheetGridEditor
					v-if="descriptor.contentTab?.kind === 'sheet'"
					:grid="grid"
					@cell-edit="handleCellEdit"
				/>
				<OleDocumentEditor
					v-else-if="descriptor.contentTab?.kind === 'document'"
					:paragraphs="paragraphs"
					@edit="handleParagraphEdit"
				/>
				<OleDeckEditor
					v-else-if="descriptor.contentTab?.kind === 'deck'"
					:slides="deckSlides"
					@edit="handleDeckElementEdit"
				/>
				<p v-else class="text-xs text-muted-foreground">
					{{ t('pptx.ole.editDialog.unsupported') }}
				</p>
			</template>
		</div>

		<template #footer>
			<input ref="fileInput" type="file" class="hidden" @change="onFileChange" />
			<DialogFooter
				:actions="[
					{ id: 'replace', label: t('pptx.ole.editDialog.replaceFile'), align: 'start' },
					{ id: 'save', label: t('pptx.ole.editDialog.save'), variant: 'primary' },
				]"
				@action="(id) => (id === 'replace' ? fileInput?.click() : close())"
			/>
		</template>
	</ModalDialog>
</template>
