// viewers/pptx/packages/angular/src/viewer/ole-renderer.component.ts
import { NgStyle } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { OlePptxElement, PptxElement } from 'pptx-viewer-core';

import { getOleIconShapes, openUrlInNewTab } from 'ooxml-ui/pptx';
import type { OleIconShape } from 'ooxml-ui/pptx';
import type { StyleMap } from './element-style';
import {
	buildOleActionModel,
	getOleAriaLabel,
	getOleBadgeLabel,
	getOleDisplayName,
	getOleTypeColor,
	getOleTypeLabel,
	getPlaceholderStyle,
	oleActionsVisibleFor,
	resolveOleType,
} from './ole-renderer-helpers';
import type { OleActionModel, ResolvedOleType } from './ole-renderer-helpers';

/**
 * OleRendererComponent: Angular port of the React `renderOleElement`
 * (packages/react/src/viewer/components/elements/InkGroupRenderers.tsx) and
 * the Vue `OleRenderer.vue`.
 *
 * Renders an embedded OLE object (`OlePptxElement`). When a decoded preview
 * image is present (`previewImageData`) it is shown full-size with a small
 * type-badge overlay; otherwise a type-specific icon + label placeholder box
 * is drawn, mirroring the React / Vue fallback.
 *
 * Positioning is NOT this component's job: it fills the positioned, element-id
 * bearing box its host draws (see `element-renderer.component.ts`), the same
 * contract the chart and table renderers follow.
 *
 * Pure helpers (type resolution, colour / label maps, placeholder style) live
 * in `ole-renderer-helpers.ts` so they can be unit-tested without TestBed.
 *
 * Editing the embedded object in place is not possible (a browser cannot run
 * the native app that owns it); the action bar offers Download and, for
 * browser-openable types, Open in a new tab, when core extracted an embedded
 * payload. The object's Object Name (`oleName`) IS editable, via
 * `pptx-element-misc-properties` in the inspector; `displayName` / `ariaLabel`
 * below already read it through the shared `getOleDisplayName` /
 * `getOleAriaLabel` helpers.
 */
@Component({
	selector: 'pptx-ole-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, TranslatePipe],
	templateUrl: './ole-renderer.component.html',
	styleUrl: './ole-renderer.component.css',
})
export class OleRendererComponent {
	/** The element to render. Must be `type === 'ole'`. */
	readonly element = input.required<PptxElement>();

	/** True only on the main editable canvas; see `showActions`. */
	readonly interactive = input<boolean>(true);

	/** True only on the live presentation stage; see `showActions`. */
	readonly presenting = input<boolean>(false);

	/**
	 * Whether the Download / Open action bar may render at all.
	 *
	 * A still of a slide (thumbnail rail, presenter console panes, export
	 * raster) renders this component INSIDE a
	 * `<button aria-label="Go to slide N">`, so the action bar's own
	 * `<button>` would otherwise be invalid, un-clickable nested-button
	 * markup; the live presentation stage never offers element-level browser
	 * chrome either.
	 */
	readonly showActions = computed<boolean>(() =>
		oleActionsVisibleFor(this.interactive(), this.presenting()),
	);

	/** Narrowed OLE element: undefined when the input is not `type === 'ole'`. */
	private readonly ole = computed<OlePptxElement | undefined>(() => {
		const el = this.element();
		return el.type === 'ole' ? el : undefined;
	});

	/** Resolved application type (excel / word / pdf / visio / mathtype / unknown). */
	readonly oleType = computed<ResolvedOleType>(() => {
		const el = this.ole();
		return el ? resolveOleType(el) : 'unknown';
	});

	/** Brand hex colour for the resolved type. */
	readonly typeColor = computed<string>(() => getOleTypeColor(this.oleType()));

	/** Human-readable type label (e.g. "Excel Spreadsheet"). */
	readonly typeLabel = computed<string>(() => getOleTypeLabel(this.oleType()));

	/** Short uppercase badge text shown over the preview image. */
	readonly badgeLabel = computed<string>(() => getOleBadgeLabel(this.oleType()));

	/** Preview image data-URL, or undefined to show the placeholder. */
	readonly previewSrc = computed<string | undefined>(() => this.ole()?.previewImageData);

	/** Original file name, if present. */
	readonly fileName = computed<string | undefined>(() => this.ole()?.fileName);

	/** Primary display name: file name if present, otherwise the type label. */
	readonly displayName = computed<string>(() => {
		const el = this.ole();
		return el ? getOleDisplayName(el) : getOleTypeLabel('unknown');
	});

	/** Accessible label for the role="img" wrapper. */
	readonly ariaLabel = computed<string>(() => {
		const el = this.ole();
		return el ? getOleAriaLabel(el) : getOleTypeLabel('unknown');
	});

	/** Border + background style for the placeholder box. */
	readonly placeholderStyle = computed<StyleMap>(() => getPlaceholderStyle(this.oleType()));

	/**
	 * Data-driven `rect`/`line`/`text` primitives for the placeholder icon,
	 * shared with every other binding's OLE renderer so the icon glyphs
	 * (Excel grid, Word lines, PDF box, Visio diagram, MathType `f(x)`,
	 * generic linked-object) cannot drift apart. The template maps each
	 * primitive onto its own SVG element.
	 */
	readonly iconShapes = computed<OleIconShape[]>(() => getOleIconShapes(this.oleType()));

	/**
	 * Download / Open action model derived from the recovered embedded payload.
	 * When the input is not an OLE element, every action is disabled.
	 */
	readonly actions = computed<OleActionModel>(() => {
		const el = this.ole();
		if (!el) {
			return {
				canDownload: false,
				canOpen: false,
				downloadHref: undefined,
				downloadFileName: 'embedded-object',
				sizeLabel: undefined,
				info: [],
			};
		}
		return buildOleActionModel(el);
	});

	/**
	 * Descriptive tooltip for the wrapper: the info rows joined as
	 * "Label: value" pairs (e.g. "Type: Excel Spreadsheet, File: budget.xlsx,
	 * Size: 2.3 KB, Application: Excel.Sheet.12"). Falls back to the aria label
	 * when no rows are available.
	 */
	readonly infoTitle = computed<string>(() => {
		const rows = this.actions().info;
		if (rows.length === 0) {
			return this.ariaLabel();
		}
		return rows.map((row) => `${row.label}: ${row.value}`).join(', ');
	});

	/**
	 * Open the recovered embedded payload in a new browser tab. Routes through
	 * the shared {@link openUrlInNewTab} helper, which converts the `data:` URL to
	 * a Blob object URL first: browsers silently refuse to navigate a new
	 * top-level tab straight to a `data:` URL.
	 */
	openEmbedded(): void {
		const href = this.actions().downloadHref;
		if (href) {
			openUrlInNewTab(href);
		}
	}
}

// viewers/pptx/packages/vue/src/viewer/components/OleRenderer.vue
<script setup lang="ts">
import type { OlePptxElement, PptxElement } from 'pptx-viewer-core';
import {
	formatBytes,
	getOleAriaLabel,
	getOleBadgeLabel,
	getOleDisplayName,
	getOleIconShapes,
	getOleTypeColor,
	getOleTypeLabel,
	isBrowserOpenableMime,
	mediaSurfaceOf,
	oleActionsVisible,
	openUrlInNewTab,
	resolveOleType,
} from 'ooxml-ui/pptx';
import type { OleIconShape, ResolvedOleType } from 'ooxml-ui/pptx';
import type { CSSProperties } from 'vue';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { useElementHitTargetStyle } from '../composables/element-hit-target';
import { getContainerStyle } from '../composables/element-style';

/**
 * OleRenderer - Vue port of the React `renderOleElement`
 * (in `InkGroupRenderers.tsx`), viewer-first subset.
 *
 * Renders an embedded OLE object (`OlePptxElement`). When a decoded preview
 * image is present (`previewImageData`) it is shown with a small type badge
 * overlay; otherwise a type-specific icon + label placeholder box is drawn,
 * mirroring the React fallback.
 *
 * The OLE-type resolution (icon / colour / label) uses the shared
 * `resolveOleType` / `getOleIconShapes` helpers so the branding matches the
 * React renderer and cannot drift from it. Editing the embedded object in place
 * is not possible (a browser cannot run the native app that owns it); the
 * action bar below still offers Download and, for browser-openable types,
 * Open in a new tab, when core extracted an embedded payload. The object's
 * Object Name (`oleName`) IS editable, via `OlePropertiesPanel` in the
 * inspector; `displayName` / `ariaLabel` below already read it through the
 * shared `getOleDisplayName` / `getOleAriaLabel` helpers.
 */
const props = defineProps<{
	element: PptxElement;
	mediaDataUrls?: Map<string, string>;
	zIndex: number;
	/** True only on the main editable canvas; see `hitTargetStyle`. */
	interactive?: boolean;
	/** True only on the live presentation stage; see `hitTargetStyle`. */
	presenting?: boolean;
}>();

const { t } = useI18n();

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);

/**
 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE) OLE
 * object box: see `ElementRenderer`'s `hitTargetStyle` doc comment (issue
 * #285). Never rendered while presenting.
 */
const hitTargetStyle = useElementHitTargetStyle(
	() => props.element,
	() => props.interactive,
	() => props.presenting,
);

/**
 * Whether the interactive Download / Open action bar may render at all.
 *
 * A still of a slide (thumbnail rail, presenter console panes, export
 * raster) renders this component INSIDE a
 * `<button aria-label="Go to slide N">`, so the action bar's own `<button>`
 * would otherwise be invalid, un-clickable nested-button markup; the live
 * presentation stage never offers element-level browser chrome either. See
 * the shared `oleActionsVisible` decision.
 */
const showActions = computed(() =>
	oleActionsVisible(
		mediaSurfaceOf({
			interactive: props.interactive === true,
			presenting: props.presenting === true,
		}),
	),
);

const ole = computed<OlePptxElement | undefined>(() =>
	props.element.type === 'ole' ? props.element : undefined,
);

/** Resolve the OLE application type from oleObjectType, falling back to progId. */
const oleType = computed<ResolvedOleType>(() => {
	const el = ole.value;
	return el ? resolveOleType(el) : 'unknown';
});

const typeColor = computed(() => getOleTypeColor(oleType.value));
const typeLabel = computed(() => getOleTypeLabel(oleType.value));

/** Data-driven placeholder icon primitives for the resolved OLE type. */
const oleIconShapes = computed<OleIconShape[]>(() => getOleIconShapes(oleType.value));

const previewSrc = computed<string | undefined>(() => ole.value?.previewImageData);
const fileName = computed<string | undefined>(() => ole.value?.fileName);

/** Recovered embedded payload data-URL, if core extracted one on load. */
const embeddedData = computed<string | undefined>(() => ole.value?.oleEmbeddedData);

/** Name to use for the download / info caption: embedded name wins, then the
 * OLE link file name, then a type-derived default. */
const downloadName = computed<string>(
	() => ole.value?.oleEmbeddedFileName ?? fileName.value ?? `${typeLabel.value}`,
);

/** Placeholder caption: prefers the user-editable `oleName` (see the inspector's
 * Object Name field), then the embedded/linked file name, then the type label. */
const displayName = computed(() => (ole.value ? getOleDisplayName(ole.value) : typeLabel.value));

/** Human-readable size of the embedded payload, if known. */
const sizeLabel = computed<string | undefined>(() => formatBytes(ole.value?.oleEmbeddedByteSize));

/** The embedded MIME type, if known. */
const mimeType = computed<string | undefined>(() => ole.value?.oleEmbeddedMimeType);

/** Whether to offer an inline "Open" action (browser-renderable payload). */
const canOpenInBrowser = computed<boolean>(
	() => Boolean(embeddedData.value) && isBrowserOpenableMime(mimeType.value),
);

/** The application that produced the object (progId), if known. */
const application = computed<string | undefined>(() => ole.value?.oleProgId);

/** Multi-line info caption / accessible description: type, name, size, app. */
const infoLines = computed<string[]>(() => {
	const lines = [typeLabel.value];
	const name = ole.value?.oleEmbeddedFileName ?? fileName.value;
	if (name) {
		lines.push(name);
	}
	if (sizeLabel.value) {
		lines.push(sizeLabel.value);
	}
	if (application.value) {
		lines.push(application.value);
	}
	return lines;
});

const infoTitle = computed<string>(() => infoLines.value.join('\n'));

const ariaLabel = computed(() => (ole.value ? getOleAriaLabel(ole.value) : typeLabel.value));

/**
 * Open the embedded payload in a new browser tab. Used for browser-renderable
 * MIME types only. Routes through the shared {@link openUrlInNewTab} helper,
 * which converts the recovered `data:` URL to a Blob object URL first: browsers
 * silently refuse to navigate a new top-level tab straight to a `data:` URL.
 */
function openEmbedded(): void {
	const data = embeddedData.value;
	if (!data) {
		return;
	}
	openUrlInNewTab(data);
}

/** Swallow pointer/mouse interactions on the action bar so clicking an action
 * does not start a selection / drag in the editor. */
function stopInteraction(event: Event): void {
	event.stopPropagation();
}

/** Short uppercase badge text for the preview overlay. */
const badgeLabel = computed(() => getOleBadgeLabel(oleType.value));

const placeholderStyle = computed<CSSProperties>(() => ({
	border: `2px solid ${typeColor.value}33`,
	borderRadius: '6px',
	backgroundColor: `${typeColor.value}0d`,
}));
</script>

<template>
	<div
		class="pptx-vue-element pptx-vue-ole"
		:style="containerStyle"
		:data-element-id="element.id"
		role="group"
		:aria-label="ariaLabel"
		:title="infoTitle"
	>
		<!-- Interaction-only hit-target for a degenerate OLE object; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<!-- Preview image with type badge overlay -->
		<div v-if="previewSrc" class="pptx-vue-ole-preview">
			<img :src="previewSrc" :alt="ariaLabel" class="pptx-vue-ole-img" draggable="false" />
			<svg class="pptx-vue-ole-badge" width="24" height="24" viewBox="0 0 24 24">
				<rect x="2" y="2" width="20" height="20" rx="3" :fill="typeColor" />
				<text
					x="12"
					y="16"
					text-anchor="middle"
					fill="white"
					:font-size="badgeLabel.length > 4 ? 6 : 10"
					font-weight="bold"
				>
					{{ badgeLabel }}
				</text>
			</svg>
		</div>

		<!-- Type-specific placeholder box -->
		<div v-else class="pptx-vue-ole-placeholder" :style="placeholderStyle">
			<!-- Icon primitives (shared `getOleIconShapes`) for the resolved type. -->
			<svg width="36" height="36" viewBox="0 0 24 24" fill="none" aria-hidden="true">
				<template v-for="(shape, i) in oleIconShapes" :key="i">
					<rect v-if="shape.tag === 'rect'" v-bind="shape.attrs" :stroke="typeColor" />
					<line v-else-if="shape.tag === 'line'" v-bind="shape.attrs" :stroke="typeColor" />
					<text v-else v-bind="shape.attrs" :fill="typeColor">{{ shape.text }}</text>
				</template>
			</svg>

			<span class="pptx-vue-ole-name" :style="{ color: typeColor }">{{ displayName }}</span>
			<span v-if="fileName" class="pptx-vue-ole-sublabel">{{ typeLabel }}</span>
		</div>

		<!--
			Action bar: Download (and, for browser-openable types, Open) the
			recovered embedded payload, plus a compact info caption. Only shown
			when core extracted an embedded payload. pointer-events are enabled
			here (the visuals above are pointer-events:none) and interactions are
			stopped from bubbling so they do not start an editor selection/drag.
		-->
		<div
			v-if="embeddedData && showActions"
			class="pptx-vue-ole-actions"
			@pointerdown="stopInteraction"
			@mousedown="stopInteraction"
			@click="stopInteraction"
		>
			<span v-if="sizeLabel" class="pptx-vue-ole-meta">{{ sizeLabel }}</span>
			<a
				class="pptx-vue-ole-action"
				:href="embeddedData"
				:download="downloadName"
				:aria-label="t('pptx.ole.downloadName', { name: downloadName })"
				:title="t('pptx.ole.downloadName', { name: downloadName })"
			>
				{{ t('pptx.ole.download') }}
			</a>
			<button
				v-if="canOpenInBrowser"
				type="button"
				class="pptx-vue-ole-action"
				:aria-label="t('pptx.ole.openName', { name: downloadName })"
				:title="t('pptx.ole.openName', { name: downloadName })"
				@click="openEmbedded"
			>
				{{ t('pptx.ole.open') }}
			</button>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-ole-preview {
	position: relative;
	width: 100%;
	height: 100%;
}

.pptx-vue-ole-img {
	width: 100%;
	height: 100%;
	object-fit: contain;
	pointer-events: none;
	user-select: none;
	display: block;
}

.pptx-vue-ole-badge {
	position: absolute;
	bottom: 4px;
	right: 4px;
	z-index: 10;
	/* Decorative overlay: never intercept clicks meant for the action bar
	   (Download / Open), which shares the bottom-right corner. */
	pointer-events: none;
}

.pptx-vue-ole-placeholder {
	width: 100%;
	height: 100%;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	pointer-events: none;
	box-sizing: border-box;
}

.pptx-vue-ole-name {
	margin-top: 8px;
	font-size: 12px;
	font-weight: 500;
	max-width: 90%;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}

.pptx-vue-ole-sublabel {
	margin-top: 2px;
	font-size: 10px;
	color: rgba(0, 0, 0, 0.45);
	max-width: 90%;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}

.pptx-vue-ole-actions {
	position: absolute;
	left: 0;
	right: 0;
	bottom: 0;
	display: flex;
	align-items: center;
	justify-content: flex-end;
	gap: 6px;
	padding: 4px 6px;
	box-sizing: border-box;
	background: rgba(255, 255, 255, 0.82);
	border-top: 1px solid rgba(0, 0, 0, 0.08);
	font-size: 11px;
	/* Re-enable pointing on the action bar; the preview/icon above stay inert. */
	pointer-events: auto;
}

.pptx-vue-ole-meta {
	margin-right: auto;
	color: rgba(0, 0, 0, 0.55);
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}

.pptx-vue-ole-action {
	flex: none;
	padding: 2px 8px;
	border: 1px solid rgba(0, 0, 0, 0.18);
	border-radius: 4px;
	background: #fff;
	color: #1a1a1a;
	font: inherit;
	line-height: 1.4;
	cursor: pointer;
	text-decoration: none;
}

.pptx-vue-ole-action:hover {
	background: #f2f2f2;
}

.pptx-vue-ole-action:focus-visible {
	outline: 2px solid #2b6cb0;
	outline-offset: 1px;
}
</style>
