// viewers/pptx/packages/svelte/src/viewer/components/PresenterNotesRail.svelte
<script lang="ts">
	/**
	 * The presenter console's right-hand rail: clock, elapsed timer, slide
	 * navigation, the next-slide preview and the speaker notes.
	 *
	 * Three fixes over the strip-and-aside this replaced, all of them shared-rule
	 * violations rather than styling:
	 *
	 * - Every string was hard-coded English ("Current time", "Previous",
	 *   "Speaker notes", "No notes for this slide"); they now resolve through the
	 *   dictionary via the shared label keys.
	 * - Next was disabled on the last slide, which strands the presenter: see
	 *   `presenterNextDisabled` for why PowerPoint keeps it live.
	 * - Notes rendered as plain text, dropping every run style the deck authored.
	 *   The cascade is now the shared one React's rail uses: rich segments, then
	 *   plain text, then the "no notes" placeholder.
	 *
	 * The next-slide preview deliberately uses `nextPresentedSlide`, so it shows
	 * the slide the next forward press will actually land on rather than
	 * `slides[current + 1]` (which would preview a hidden slide the show skips).
	 *
	 * The rail's four controls (`prev`, `next`, `notes-font-decrease`,
	 * `notes-font-increase`) emit the SAME `data-pptx-presenter-control` attribute
	 * the console strip uses, because all five bindings agreed on one attribute so
	 * a framework-neutral e2e spec can query a single selector. Anything asserting
	 * the strip's own inventory therefore has to scope to
	 * `[data-pptx-presenter-strip]` rather than sweep the document.
	 */
	import type { PptxSlide } from 'pptx-viewer-core';
	import {
		clampNotesFontSize,
		formatElapsed,
		formatTime,
		nextPresentedSlide,
		notesSegmentsToSpans,
		NOTES_FONT_SIZE_MAX,
		NOTES_FONT_SIZE_MIN,
		NOTES_FONT_SIZE_STEP,
		PRESENTER_LAYOUT_METRICS,
		PRESENTER_RAIL_CONTROLS,
		PRESENTER_RAIL_LABEL_KEYS,
		presenterNextDisabled,
		presenterPrevDisabled,
	} from 'ooxml-ui/pptx';
	import type { AuthoredSlideRange, CanvasSize, ShowOrderCustomShow } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import { styleToString } from '../style';
	import SlideStage from './SlideStage.svelte';

	const {
		slides,
		current,
		canvasSize,
		mediaDataUrls,
		now,
		elapsed,
		notesSize,
		activeCustomShow,
		authoredRange,
		onmove,
		onnotessize,
	}: {
		slides: PptxSlide[];
		current: number;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		/** `Date.now()` of the console's clock tick, so the rail never owns a timer. */
		now: number;
		elapsed: number;
		notesSize: number;
		/**
		 * The custom show playback is restricted to, so the preview names the
		 * slide the next forward press actually reaches. Without it a running
		 * custom show previewed the next DECK slide instead of the next SHOW one.
		 */
		activeCustomShow?: ShowOrderCustomShow | null;
		/**
		 * `p:showPr/p:sldRg`: the deck's authored slide-range restriction (wave-4
		 * B1), passed to `nextPresentedSlide` alongside `activeCustomShow` so the
		 * preview never names a slide outside the range the show was opened into.
		 */
		authoredRange?: AuthoredSlideRange | null;
		onmove: (direction: -1 | 1) => void;
		onnotessize: (size: number) => void;
	} = $props();

	const t = useTranslator();

	/** The rail's own controls, looked up in the shared inventory by id. */
	function railLabel(id: string): string {
		const control = PRESENTER_RAIL_CONTROLS.find((item) => item.id === id);
		return control === undefined ? '' : t(control.labelKey);
	}

	const slide = $derived(slides[current]);
	const nextSlide = $derived(
		nextPresentedSlide(slides, current, activeCustomShow, authoredRange),
	);
	const nextScale = $derived(
		canvasSize.width > 0 ? PRESENTER_LAYOUT_METRICS.nextPreviewWidth / canvasSize.width : 1,
	);
	const spans = $derived(notesSegmentsToSpans(slide?.notesSegments ?? []));
	const plainNotes = $derived((slide?.notes ?? '').trim());
</script>

<aside class="pptx-svelte-presenter-rail">
	<header>
		<div>
			<small>{t(PRESENTER_RAIL_LABEL_KEYS.currentTime)}</small>
			<strong>{formatTime(new Date(now))}</strong>
		</div>
		<div>
			<small>{t(PRESENTER_RAIL_LABEL_KEYS.elapsed)}</small>
			<strong>{formatElapsed(elapsed)}</strong>
		</div>
	</header>

	<nav>
		<button
			type="button"
			data-pptx-presenter-control="prev"
			disabled={presenterPrevDisabled(current)}
			aria-label={railLabel('prev')}
			onclick={() => onmove(-1)}
		>
			{railLabel('prev')}
		</button>
		<span>{current + 1} / {slides.length}</span>
		<!-- Never disabled: the console has to be able to run off the end of the
		     show, or the presenter cannot finish and the audience display never
		     closes. The rule is `presenterNextDisabled`, not a local judgement. -->
		<button
			type="button"
			data-pptx-presenter-control="next"
			disabled={presenterNextDisabled()}
			aria-label={railLabel('next')}
			onclick={() => onmove(1)}
		>
			{railLabel('next')}
		</button>
	</nav>

	<section class="pptx-svelte-presenter-next">
		<small>{t(PRESENTER_RAIL_LABEL_KEYS.nextSlidePreview)}</small>
		{#if nextSlide}
			<div
				class="pptx-svelte-presenter-next-frame"
				data-pptx-presenter-next-preview
				style={`width:${canvasSize.width * nextScale}px;height:${canvasSize.height * nextScale}px`}
			>
				<SlideStage slide={nextSlide} {canvasSize} {mediaDataUrls} scale={nextScale} />
			</div>
		{:else}
			<em>{t(PRESENTER_RAIL_LABEL_KEYS.endOfPresentation)}</em>
		{/if}
	</section>

	<section class="pptx-svelte-presenter-notes">
		<header>
			<small>{t(PRESENTER_RAIL_LABEL_KEYS.speakerNotes)}</small>
			<div class="pptx-svelte-presenter-notes-size">
				<button
					type="button"
					data-pptx-presenter-control="notes-font-decrease"
					disabled={notesSize <= NOTES_FONT_SIZE_MIN}
					aria-label={railLabel('notes-font-decrease')}
					title={railLabel('notes-font-decrease')}
					onclick={() => onnotessize(clampNotesFontSize(notesSize - NOTES_FONT_SIZE_STEP))}
				>
					<!-- A literal minus glyph, not an em-dash and not an icon font. -->
					<span aria-hidden="true">-</span>
				</button>
				<span class="pptx-svelte-presenter-notes-readout">{notesSize}px</span>
				<button
					type="button"
					data-pptx-presenter-control="notes-font-increase"
					disabled={notesSize >= NOTES_FONT_SIZE_MAX}
					aria-label={railLabel('notes-font-increase')}
					title={railLabel('notes-font-increase')}
					onclick={() => onnotessize(clampNotesFontSize(notesSize + NOTES_FONT_SIZE_STEP))}
				>
					<span aria-hidden="true">+</span>
				</button>
			</div>
		</header>
		<div
			class="pptx-svelte-presenter-notes-body"
			data-pptx-presenter-notes
			style={`font-size:${notesSize}px`}
		>
			{#if spans.length > 0}
				{#each spans as span (span.key)}
					{#if span.kind === 'break'}
						<br />
					{:else}
						<span style={styleToString(span.style)}>{span.text}</span>
					{/if}
				{/each}
			{:else if plainNotes}
				{plainNotes}
			{:else}
				<em>{t(PRESENTER_RAIL_LABEL_KEYS.noNotes)}</em>
			{/if}
		</div>
	</section>
</aside>

<style>
	.pptx-svelte-presenter-rail {
		display: flex;
		flex: var(--pptx-pv-rail-flex);
		min-width: var(--pptx-pv-rail-min);
		max-width: var(--pptx-pv-rail-max);
		flex-direction: column;
		border-left: 1px solid var(--pptx-border, #334155);
	}

	header,
	nav {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 8px;
		padding: 12px;
		border-bottom: 1px solid var(--pptx-border, #334155);
	}

	header div {
		display: flex;
		flex-direction: column;
	}

	small {
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 10px;
		letter-spacing: 0.08em;
		text-transform: uppercase;
	}

	button {
		border: 0;
		border-radius: var(--pptx-pv-control-radius);
		padding: 7px 10px;
		background: var(--pptx-secondary, #334155);
		color: inherit;
		cursor: pointer;
	}

	button:disabled {
		opacity: 0.4;
		cursor: default;
	}

	.pptx-svelte-presenter-next {
		padding: 14px;
		border-bottom: 1px solid var(--pptx-border, #334155);
	}

	.pptx-svelte-presenter-next-frame {
		position: relative;
		margin-top: 8px;
		overflow: hidden;
	}

	.pptx-svelte-presenter-notes {
		display: flex;
		min-height: 0;
		flex: 1;
		flex-direction: column;
		padding: 12px;
	}

	.pptx-svelte-presenter-notes header {
		padding: 0 0 8px;
		border: 0;
	}

	.pptx-svelte-presenter-notes-size {
		display: flex;
		align-items: center;
		gap: 4px;
	}

	.pptx-svelte-presenter-notes-readout {
		min-width: 34px;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-family: ui-monospace, monospace;
		font-size: 10px;
		text-align: center;
	}

	.pptx-svelte-presenter-notes-body {
		flex: 1;
		padding: 12px;
		border: 1px solid var(--pptx-border, #334155);
		border-radius: 6px;
		line-height: 1.5;
		overflow: auto;
		white-space: pre-wrap;
	}
</style>

// viewers/pptx/packages/vue/src/viewer/components/PresenterNotesRail.vue
<script setup lang="ts">
/**
 * PresenterNotesRail - the right-hand 30% of the presenter console: wall clock,
 * elapsed timer, audience/exit buttons, prev/next navigation, the next-slide
 * preview and the scalable speaker notes.
 *
 * Split out of `PresenterView.vue`, which had grown past the repo's 300-line
 * ceiling. Every string here now resolves through the canonical
 * `pptx.presenter.*` keys (via the shared rail inventory); the rail previously
 * reached into `pptx.presenterView.*`, `pptx.mpresenter.*`, `pptx.mobileBar.*`
 * and `pptx.statusBar.*` for text that already had a canonical equivalent,
 * which is how four near-duplicate namespaces came to describe one console.
 */
import { ChevronLeft, ChevronRight, Minus, Plus, X } from 'lucide-vue-next';
import type { PptxSlide } from 'pptx-viewer-core';
import type { AuthoredSlideRange } from 'ooxml-ui/pptx';
import {
	nextPresentedSlide,
	PRESENTER_CONSOLE_CLASSES,
	PRESENTER_RAIL_LABEL_KEYS,
	presenterNextDisabled,
	presenterPrevDisabled,
} from 'ooxml-ui/pptx';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { PRESENTER_RAIL_CONTROL_LABEL_KEYS } from '../composables/presenter-console';
import {
	clampNotesFontSize,
	notesSegmentsToSpans,
	NOTES_FONT_SIZE_DEFAULT,
	NOTES_FONT_SIZE_MAX,
	NOTES_FONT_SIZE_MIN,
	NOTES_FONT_SIZE_STEP,
} from '../composables/presenter-view-utils';
import type { CanvasSize } from '../types';
import SlideStage from './SlideStage.vue';

const props = defineProps<{
	slides: PptxSlide[];
	currentSlideIndex: number;
	canvasSize: CanvasSize;
	mediaDataUrls: Map<string, string>;
	clockText: string;
	elapsedText: string;
	audienceOpen: boolean;
	/** Membership of the running custom show, when one is playing. */
	activeCustomShow?: { slideRIds: string[] } | null;
	/** `p:showPr/p:sldRg`, resolved to deck indexes; `null`/`undefined` for no range. */
	authoredRange?: AuthoredSlideRange | null;
}>();

const emit = defineEmits<{
	(e: 'move', direction: 1 | -1): void;
	(e: 'exit' | 'audience'): void;
}>();

const { t } = useI18n();
const railKeys = PRESENTER_RAIL_LABEL_KEYS;
const controlKeys = PRESENTER_RAIL_CONTROL_LABEL_KEYS;
const classes = PRESENTER_CONSOLE_CLASSES;

const currentSlide = computed<PptxSlide | undefined>(() => props.slides[props.currentSlideIndex]);
/**
 * The next slide the SHOW will present, not simply `index + 1`: hidden slides
 * are skipped and custom-show membership is honoured, so the preview matches
 * what the audience is about to see.
 *
 * The running show is part of that rule: while "Reverse" plays, the slide after
 * slide 3 is slide 2, and a rail that previewed slide 4 was rehearsing the
 * presenter into a segue the next press could not reach.
 */
const nextSlide = computed<PptxSlide | undefined>(() =>
	nextPresentedSlide(
		props.slides,
		props.currentSlideIndex,
		props.activeCustomShow,
		props.authoredRange,
	),
);

const notesText = computed(() => currentSlide.value?.notes ?? '');
const notesSpans = computed(() => {
	const segments = currentSlide.value?.notesSegments;
	return segments && segments.length > 0 ? notesSegmentsToSpans(segments) : null;
});
const hasPlainNotes = computed(() => notesText.value.trim().length > 0);

const notesFontSize = ref(NOTES_FONT_SIZE_DEFAULT);
function stepNotesFontSize(direction: 1 | -1): void {
	notesFontSize.value = clampNotesFontSize(notesFontSize.value + direction * NOTES_FONT_SIZE_STEP);
}

// Fit the next-slide preview into the rail panel.
const PREVIEW_WIDTH = 240;
const previewScale = computed(() =>
	props.canvasSize.width > 0 ? PREVIEW_WIDTH / props.canvasSize.width : 1,
);
const previewFrameStyle = computed(() => ({
	width: `${props.canvasSize.width * previewScale.value}px`,
	height: `${props.canvasSize.height * previewScale.value}px`,
}));
</script>

<template>
	<div class="pptx-vue-presenter-rail" :class="classes.rail">
		<!-- Header: clock + elapsed + audience/exit -->
		<div
			class="pptx-vue-presenter-header flex items-center justify-between gap-2 border-b border-border/60 px-4 py-3"
		>
			<div class="pptx-vue-presenter-time flex flex-col">
				<span class="pptx-vue-presenter-label" :class="classes.railHeading">{{
					t(railKeys.currentTime)
				}}</span>
				<span class="pptx-vue-presenter-clock font-mono text-lg tabular-nums text-foreground">{{
					clockText
				}}</span>
			</div>
			<div class="pptx-vue-presenter-time pptx-vue-presenter-time--right flex flex-col items-end">
				<span class="pptx-vue-presenter-label" :class="classes.railHeading">{{
					t(railKeys.elapsed)
				}}</span>
				<span class="pptx-vue-presenter-elapsed font-mono text-lg tabular-nums text-primary">{{
					elapsedText
				}}</span>
			</div>
			<div class="flex items-center gap-1">
				<button
					type="button"
					class="pptx-vue-presenter-audience-btn flex h-7 items-center justify-center rounded px-2 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
					:title="
						audienceOpen
							? t('pptx.presenter.closeAudienceWindow')
							: t('pptx.presenter.openAudienceWindow')
					"
					@click="emit('audience')"
				>
					{{
						audienceOpen
							? t('pptx.presenter.closeAudienceWindow')
							: t('pptx.presenter.openAudienceWindow')
					}}
				</button>
				<button
					type="button"
					class="pptx-vue-presenter-icon-btn flex h-7 w-7 items-center justify-center rounded text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
					:title="t('pptx.presenter.endPresentation')"
					:aria-label="t('pptx.presenter.endPresentation')"
					@click="emit('exit')"
				>
					<X class="h-4 w-4" aria-hidden="true" />
				</button>
			</div>
		</div>

		<!-- Navigation. Next stays live on the last slide: PowerPoint's console
		     advances from there to the end-of-show screen and then out of the
		     show, so disabling it stranded the presenter with no way to finish
		     and left the audience display open. -->
		<div
			class="pptx-vue-presenter-nav flex items-center justify-between border-b border-border/60 px-4 py-2"
		>
			<button
				type="button"
				class="pptx-vue-presenter-nav-btn inline-flex items-center gap-1.5 rounded bg-muted px-3 py-1.5 text-xs transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
				data-pptx-presenter-control="prev"
				:disabled="presenterPrevDisabled(currentSlideIndex)"
				:title="t(controlKeys.prev)"
				:aria-label="t(controlKeys.prev)"
				@click="emit('move', -1)"
			>
				<ChevronLeft class="h-4 w-4" aria-hidden="true" />
				{{ t(controlKeys.prev) }}
			</button>
			<span class="pptx-vue-presenter-counter font-mono text-sm tabular-nums text-foreground">
				{{ currentSlideIndex + 1 }} / {{ slides.length }}
			</span>
			<button
				type="button"
				class="pptx-vue-presenter-nav-btn inline-flex items-center gap-1.5 rounded bg-muted px-3 py-1.5 text-xs transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
				data-pptx-presenter-control="next"
				:disabled="presenterNextDisabled()"
				:title="t(controlKeys.next)"
				:aria-label="t(controlKeys.next)"
				@click="emit('move', 1)"
			>
				{{ t(controlKeys.next) }}
				<ChevronRight class="h-4 w-4" aria-hidden="true" />
			</button>
		</div>

		<!-- Next slide preview -->
		<div
			class="pptx-vue-presenter-section border-b border-border/60 px-4 py-3"
			data-pptx-presenter-next-preview
		>
			<div class="pptx-vue-presenter-label mb-2" :class="classes.railHeading">
				{{ t(railKeys.nextSlidePreview) }}
			</div>
			<div
				v-if="nextSlide"
				class="pptx-vue-presenter-preview-frame relative mt-2 overflow-hidden rounded border border-border/30"
				:style="previewFrameStyle"
			>
				<SlideStage
					:slide="nextSlide"
					:canvas-size="canvasSize"
					:media-data-urls="mediaDataUrls"
					:scale="previewScale"
				/>
			</div>
			<div
				v-else
				class="pptx-vue-presenter-preview-empty mt-2 flex h-16 items-center justify-center rounded border border-border/30 bg-muted/40 text-xs italic text-muted-foreground"
			>
				{{ t(railKeys.endOfPresentation) }}
			</div>
		</div>

		<!-- Speaker notes -->
		<div
			class="pptx-vue-presenter-notes-section flex flex-1 min-h-0 flex-col px-4 py-3"
			data-pptx-presenter-notes
		>
			<div class="pptx-vue-presenter-notes-head mb-2 flex items-center justify-between">
				<div class="pptx-vue-presenter-label" :class="classes.railHeading">
					{{ t(railKeys.speakerNotes) }}
				</div>
				<div class="pptx-vue-presenter-font-ctl flex items-center gap-1">
					<button
						type="button"
						class="pptx-vue-presenter-font-btn rounded p-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground disabled:cursor-not-allowed disabled:opacity-30"
						data-pptx-presenter-control="notes-font-decrease"
						:disabled="notesFontSize <= NOTES_FONT_SIZE_MIN"
						:title="t(controlKeys['notes-font-decrease'])"
						:aria-label="t(controlKeys['notes-font-decrease'])"
						@click="stepNotesFontSize(-1)"
					>
						<Minus class="h-3.5 w-3.5" aria-hidden="true" />
					</button>
					<span
						class="pptx-vue-presenter-font-val min-w-[28px] select-none text-center font-mono text-[10px] tabular-nums text-muted-foreground"
						>{{ notesFontSize }}px</span
					>
					<button
						type="button"
						class="pptx-vue-presenter-font-btn rounded p-0.5 text-muted-foreground transition-colors hover:bg-accent hover:text-foreground disabled:cursor-not-allowed disabled:opacity-30"
						data-pptx-presenter-control="notes-font-increase"
						:disabled="notesFontSize >= NOTES_FONT_SIZE_MAX"
						:title="t(controlKeys['notes-font-increase'])"
						:aria-label="t(controlKeys['notes-font-increase'])"
						@click="stepNotesFontSize(1)"
					>
						<Plus class="h-3.5 w-3.5" aria-hidden="true" />
					</button>
				</div>
			</div>
			<div
				class="pptx-vue-presenter-notes flex-1 overflow-y-auto whitespace-pre-wrap rounded border border-border/30 bg-muted/40 px-3 py-2 leading-relaxed text-foreground"
				:style="{ fontSize: `${notesFontSize}px` }"
			>
				<template v-if="notesSpans">
					<template v-for="span in notesSpans" :key="span.key">
						<br v-if="span.kind === 'break'" />
						<span v-else :style="span.style">{{ span.text }}</span>
					</template>
				</template>
				<template v-else-if="hasPlainNotes">{{ notesText }}</template>
				<span v-else class="pptx-vue-presenter-notes-empty italic text-muted-foreground">{{
					t(railKeys.noNotes)
				}}</span>
			</div>
		</div>
	</div>
</template>
