// viewers/pptx/packages/react/src/viewer/components/SlideTemplateGalleryDialog.tsx
/**
 * SlideTemplateGalleryDialog: the New Slide template gallery.
 *
 * Presents the shared slide-template catalogue as a grid of live-rendered
 * previews. Single click selects, double click or the Insert button inserts
 * the template after the current slide via the caller's history-integrated
 * insert path.
 */
import { SLIDE_TEMPLATES } from 'ooxml-ui/pptx';
import type { SlideTemplateId } from 'ooxml-ui/pptx';
import React, { useCallback, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuX } from 'react-icons/lu';

import { useModalDismissDrag } from '../hooks';
import { useModalFocus } from '../hooks/useModalFocus';
import { cn } from '../utils';
import { DialogFooter } from './DialogFooter';
import { SlideTemplatePreview } from './SlideTemplatePreview';

export interface SlideTemplateGalleryDialogProps {
	isOpen: boolean;
	onClose: () => void;
	onInsert: (templateId: SlideTemplateId) => void;
	/** Optional deck scheme so previews show the deck's theme colours. */
	scheme?: Record<string, string>;
}

export function SlideTemplateGalleryDialog({
	isOpen,
	onClose,
	onInsert,
	scheme,
}: SlideTemplateGalleryDialogProps): React.ReactElement | null {
	const { t } = useTranslation();
	const { panelStyle, handlers: dragHandlers } = useModalDismissDrag(onClose);
	const [selected, setSelected] = useState<SlideTemplateId | null>(null);
	const dialogRef = useRef<HTMLDivElement>(null);
	useModalFocus(isOpen, dialogRef, onClose);

	const handleInsert = useCallback(() => {
		if (!selected) {
			return;
		}
		onInsert(selected);
		onClose();
	}, [selected, onInsert, onClose]);

	if (!isOpen) {
		return null;
	}

	return (
		<>
			<button
				type='button'
				style={{ zIndex: 1200 }}
				className='fixed inset-0 bg-black/50'
				onClick={onClose}
				aria-label={t('pptx.slideTemplates.close')}
			/>

			<div
				style={{ zIndex: 1201 }}
				className='fixed inset-0 flex items-center justify-center pointer-events-none'
			>
				<div
					ref={dialogRef}
					style={panelStyle}
					className='pointer-events-auto w-[640px] max-w-[92vw] max-h-[80vh] rounded-lg border border-border bg-background shadow-2xl flex flex-col max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-w-none max-md:max-h-[88dvh] max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'
					role='dialog'
					aria-modal='true'
					aria-label={t('pptx.slideTemplates.galleryTitle')}
					tabIndex={-1}
				>
					<div
						{...dragHandlers}
						className='flex items-center justify-between px-4 py-3 border-b border-border touch-none'
					>
						<div className='flex flex-col gap-0.5'>
							<h2 className='text-sm font-medium text-foreground'>
								{t('pptx.slideTemplates.galleryTitle')}
							</h2>
							<p className='text-[11px] text-muted-foreground'>
								{t('pptx.slideTemplates.galleryDescription')}
							</p>
						</div>
						<button
							type='button'
							onClick={onClose}
							className='p-1 rounded hover:bg-muted transition-colors'
							aria-label={t('pptx.slideTemplates.close')}
						>
							<LuX className='w-4 h-4' />
						</button>
					</div>

					<div className='flex-1 p-3 overflow-y-auto'>
						<div
							className='grid grid-cols-3 gap-2'
							role='listbox'
							aria-label={t('pptx.slideTemplates.gallery')}
						>
							{SLIDE_TEMPLATES.map((spec) => (
								<button
									key={spec.id}
									type='button'
									role='option'
									aria-selected={selected === spec.id}
									aria-label={t(spec.nameKey)}
									title={t(spec.descriptionKey)}
									onClick={() => setSelected(spec.id)}
									onDoubleClick={() => {
										onInsert(spec.id);
										onClose();
									}}
									className={cn(
										'flex flex-col items-center gap-1 p-2 rounded border transition-colors',
										selected === spec.id
											? 'border-primary bg-primary/20'
											: 'border-border hover:border-border hover:bg-muted/50',
									)}
								>
									<div className='flex items-center justify-center bg-muted rounded'>
										<SlideTemplatePreview templateId={spec.id} scheme={scheme} />
									</div>
									<span className='text-[10px] text-foreground text-center leading-tight'>
										{t(spec.nameKey)}
									</span>
								</button>
							))}
						</div>
					</div>

					<div className='flex items-center justify-end gap-2 px-4 py-3 border-t border-border'>
						<DialogFooter
							actions={[
								{ id: 'cancel', label: t('pptx.slideTemplates.cancel') },
								{
									id: 'insert',
									label: t('pptx.slideTemplates.insert'),
									variant: 'primary',
									disabled: !selected,
								},
							]}
							onAction={(id) => (id === 'insert' ? handleInsert() : onClose())}
						/>
					</div>
				</div>
			</div>
		</>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/SlideTemplateGalleryDialog.vue
<script setup lang="ts">
import { SLIDE_TEMPLATES } from 'ooxml-ui/pptx';
import type { SlideTemplateId } from 'ooxml-ui/pptx';
import { ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';
import ModalDialog from './ModalDialog.vue';
import SlideTemplatePreview from './SlideTemplatePreview.vue';

/**
 * SlideTemplateGalleryDialog - the New Slide template gallery.
 *
 * Vue port of React's `SlideTemplateGalleryDialog.tsx`, built on
 * {@link ModalDialog}. Presents the shared slide-template catalogue as a grid
 * of live-rendered previews (`SlideTemplatePreview.vue`). Single click
 * selects, double click or the Insert button emits `insert` with the chosen
 * template id; the host routes the payload to its history-integrated insert
 * path.
 */
const props = defineProps<{
	/** Whether the dialog is open. */
	open: boolean;
	/** Optional deck scheme so previews show the deck's theme colours. */
	scheme?: Record<string, string>;
}>();

const emit = defineEmits<{
	/** Emitted with the chosen template id. */
	(e: 'insert', templateId: SlideTemplateId): void;
	/** Emitted when the dialog should close without inserting. */
	(e: 'close'): void;
}>();

const { t } = useI18n();

const selected = ref<SlideTemplateId | null>(null);

/** Re-seed the selection whenever the dialog (re)opens. */
watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			selected.value = null;
		}
	},
	{ immediate: true },
);

function select(id: SlideTemplateId): void {
	selected.value = id;
}

function insertTemplate(id: SlideTemplateId): void {
	emit('insert', id);
	emit('close');
}

function handleInsert(): void {
	if (selected.value) {
		insertTemplate(selected.value);
	}
}

function close(): void {
	emit('close');
}
</script>

<template>
	<ModalDialog :open="open" :title="t('pptx.slideTemplates.galleryTitle')" @close="close">
		<div class="pptx-vue-template-dialog flex max-h-[min(64vh,480px)] flex-col gap-2.5">
			<p class="pptx-vue-template-description text-[11px] text-muted-foreground">
				{{ t('pptx.slideTemplates.galleryDescription') }}
			</p>
			<div
				class="pptx-vue-template-gallery grid flex-1 grid-cols-3 gap-1 overflow-y-auto"
				role="listbox"
				:aria-label="t('pptx.slideTemplates.gallery')"
			>
				<button
					v-for="spec in SLIDE_TEMPLATES"
					:key="spec.id"
					type="button"
					role="option"
					:aria-selected="selected === spec.id"
					:aria-label="t(spec.nameKey)"
					:title="t(spec.descriptionKey)"
					class="pptx-vue-template-tile flex flex-col items-center gap-1 rounded border py-1 transition-colors"
					:class="
						selected === spec.id
							? 'pptx-vue-template-tile--active border-primary bg-primary/20'
							: 'border-border hover:border-border hover:bg-muted/50'
					"
					@click="select(spec.id)"
					@dblclick="insertTemplate(spec.id)"
				>
					<span class="pptx-vue-template-thumb flex items-center justify-center rounded bg-muted">
						<SlideTemplatePreview :template-id="spec.id" :scheme="props.scheme" />
					</span>
					<span
						class="pptx-vue-template-tile-label text-center text-[10px] leading-tight text-foreground"
					>
						{{ t(spec.nameKey) }}
					</span>
				</button>
			</div>
		</div>

		<template #footer>
			<DialogFooter
				:actions="[
					{ id: 'cancel', label: t('pptx.slideTemplates.cancel') },
					{
						id: 'insert',
						label: t('pptx.slideTemplates.insert'),
						variant: 'primary',
						disabled: !selected,
					},
				]"
				@action="(id) => (id === 'insert' ? handleInsert() : close())"
			/>
		</template>
	</ModalDialog>
</template>
