// viewers/pptx/packages/angular/src/viewer/smart-art-3d-renderer.component.ts
import { NgStyle } from '@angular/common';
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	ElementRef,
	inject,
	Injector,
	input,
	signal,
	viewChild,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxElement } from 'pptx-viewer-core';

import {
	commitSmartArtNodeFill,
	elementHitTargetStyle,
	measureSvgViewportRect,
	resolvePalette,
	resolveSmartArtThreeViewSpec,
	shouldRenderHitTarget,
	smartArtNodeAtPoint,
} from 'ooxml-ui/pptx';
import type { InlineEditRect, TextStyleAnimationDescriptor } from 'ooxml-ui/pptx';
import { EditorStateService } from './editor-state.service';
import { getContainerStyle } from './element-style';
import type { StyleMap } from './element-style';
import { Rendering3DService } from './rendering-3d.service';
import { SLIDE_CONTEXT } from './slide-context';
import {
	computeNode3DStyleBarStyle,
	getSmartArtData,
	toNode3DEditBox,
} from './smart-art-3d-renderer-helpers';
import { commitNodeText, findOwningSlideIndex } from './smart-art-inline-edit';
import type { InlineEditState } from './smart-art-inline-edit';
import { SmartArtRendererComponent } from './smart-art-renderer.component';
import { ThreeViewComponent } from './three-view.component';

/**
 * SmartArt3DRendererComponent: Angular 3D SmartArt view on the shared
 * `<pptx-three-view>`. The spec (`resolveSmartArtThreeViewSpec`) and the whole
 * scene live in the shared package; this component projects the SVG
 * `<pptx-smart-art-renderer>` as the element's fallback (shown while the scene
 * loads, and kept when `three` is missing or the scene fails). A diagram with
 * nothing to draw renders the plain SVG. Mirrors React's `SmartArt3DView.tsx`.
 *
 * When `canEdit` is true, an invisible `<pptx-smart-art-renderer>` overlay is
 * stacked over the scene. Double-clicking
 * on the overlay uses `document.elementsFromPoint` to locate the `<g>` bearing
 * `data-smartart-node-id`, then opens an inline textarea editor over that node
 * (same commit path as the SVG renderer: `EditorStateService.updateElement`).
 */
@Component({
	selector: 'pptx-smart-art-3d-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SmartArtRendererComponent, ThreeViewComponent, TranslatePipe],
	templateUrl: './smart-art-3d-renderer.component.html',
	styleUrl: './smart-art-3d-renderer.component.css',
})
export class SmartArt3DRendererComponent {
	readonly element = input.required<PptxElement>();
	readonly zIndex = input<number>(0);
	/** When true and the 3D scene is active, enables inline node text editing. */
	readonly canEdit = input<boolean>(false);
	/**
	 * Emit the neutral element marker (`data-pptx-element="true"`) on the node
	 * that also carries `data-element-id`: the 3D scene's root, or the box the
	 * SVG fallback branch is drawn into. Set only by the main interactive canvas.
	 */
	readonly markElement = input<boolean>(false);
	/** Whether inline editing (drag/resize) is enabled on this surface. */
	readonly editable = input<boolean>(false);
	/** True only on the live presentation stage; see `ElementRendererComponent.presenting`. */
	readonly presenting = input<boolean>(false);
	/**
	 * Active font-style emphasis override (Bold Flash, Bold Reveal, Underline,
	 * Change Font Style/Size) for every node's caption, driven by native-
	 * animation playback. Mirrors `ChartElementViewComponent`'s `textStyle`
	 * threading for the 3D chart scenes: a canvas-texture caption has no DOM
	 * text node the CSS-injection path (`buildTextStyleOverrideCss`) can reach,
	 * so the scene's own text style is the only way in.
	 */
	readonly textStyle = input<TextStyleAnimationDescriptor | undefined>(undefined);

	private readonly containerEl = viewChild<ElementRef<HTMLElement>>('container3d');
	private readonly nodeEditor3d = viewChild<ElementRef<HTMLTextAreaElement>>('nodeEditor3d');

	private readonly rendering3D = inject(Rendering3DService, { optional: true });

	/** The scene spec, or `null` (flag off, or nothing to draw): render the plain SVG. */
	protected readonly spec = computed(() =>
		resolveSmartArtThreeViewSpec(this.element(), this.rendering3D?.flags().smartArt3D ?? false),
	);

	/** `true` when no 3D scene applies; renders the SVG renderer on its own. */
	readonly useFallback = computed(() => this.spec() === null);

	protected readonly editState = signal<InlineEditState | null>(null);
	/** Live draft text, updated on every input event. */
	protected draftText = '';
	/** Guards against a cancel-triggered DOM-removal blur committing the edit. */
	private editSettled = false;

	private readonly editor = inject(EditorStateService, { optional: true });
	/** The hosting canvas's slide, for resolving template (master/layout) SmartArt. */
	private readonly slideContext = inject(SLIDE_CONTEXT, { optional: true });
	private readonly injector = inject(Injector);

	readonly containerStyle = computed<StyleMap>(() =>
		getContainerStyle(this.element(), this.zIndex()),
	);

	/**
	 * Interaction-only hit target for a degenerate 3D SmartArt; see
	 * `ElementRendererShapeComponent.hitTargetStyle`'s fuller doc (issue #285).
	 */
	readonly hitTargetStyle = computed(() =>
		shouldRenderHitTarget(this.editable(), this.presenting())
			? elementHitTargetStyle(this.element())
			: undefined,
	);

	private readonly smartArtData = computed(() => getSmartArtData(this.element()));

	/** Resolved palette for the hover swatch bar, as on the 2D diagram. */
	protected readonly palette = computed<string[]>(() => resolvePalette(this.smartArtData()));

	protected readonly hoveredNodeId = signal<string | null>(null);
	private readonly hoveredNodeRect = signal<InlineEditRect | null>(null);

	protected readonly styleBarStyle = computed<Record<string, string> | null>(() =>
		computeNode3DStyleBarStyle(this.hoveredNodeRect(), this.containerEl()?.nativeElement),
	);

	constructor() {
		// Auto-focus the textarea when the editor opens.
		effect(() => {
			if (this.editState()) {
				afterNextRender(
					() => {
						const el = this.nodeEditor3d()?.nativeElement;
						if (el) {
							el.focus();
							el.select();
						}
					},
					{ injector: this.injector },
				);
			}
		});
	}

	/**
	 * Locate the SmartArt node at the click position within the invisible
	 * overlay and open the inline editor. The overlay's node groups are
	 * `pointer-events: none`, which hit-testing (`document.elementsFromPoint`
	 * included) skips, so the node is found by geometry
	 * (`smartArtNodeAtPoint`).
	 */
	onOverlayDblClick(event: MouseEvent): void {
		const container = this.containerEl()?.nativeElement;
		const data = this.smartArtData();
		const overlay = event.currentTarget;
		if (!container || !data || !(overlay instanceof Element)) {
			return;
		}
		const nodeEl = smartArtNodeAtPoint(overlay, event.clientX, event.clientY);
		const nodeId = nodeEl?.getAttribute('data-smartart-node-id');
		// In the diagram's own SVG coordinates, as the 2D renderer measures: a
		// screen rect is wrong once the element is turned or the slide zoomed.
		const rect = nodeEl ? measureSvgViewportRect(nodeEl) : null;
		if (!nodeEl || !nodeId || !rect) {
			return;
		}
		// The editor owns this double-click: the stage must not act on it too.
		event.stopPropagation();
		const currentText = data.nodes.find((n) => n.id === nodeId)?.text ?? '';
		this.draftText = currentText;
		this.editSettled = false;
		this.hoveredNodeId.set(null);
		this.hoveredNodeRect.set(null);
		this.editState.set({ nodeId, box: toNode3DEditBox(rect), text: currentText });
	}

	/**
	 * Track the node under the pointer for the fill swatch bar. The overlay's
	 * node groups take no pointer events, so the node is found by geometry.
	 */
	onOverlayMouseMove(event: MouseEvent): void {
		const overlay = event.currentTarget;
		if (!(overlay instanceof Element) || this.editState()) {
			return;
		}
		const nodeEl = smartArtNodeAtPoint(overlay, event.clientX, event.clientY);
		const id = nodeEl?.getAttribute('data-smartart-node-id') ?? null;
		if (id !== this.hoveredNodeId()) {
			this.hoveredNodeId.set(id);
			this.hoveredNodeRect.set(id && nodeEl ? measureSvgViewportRect(nodeEl) : null);
		}
	}

	/**
	 * The overlay and the bar are siblings, so crossing from one to the other
	 * fires `mouseleave` on the first; only a leave elsewhere ends the hover.
	 */
	onHoverLeave(event: MouseEvent): void {
		const to = event.relatedTarget;
		if (to instanceof Node && this.containerEl()?.nativeElement.contains(to)) {
			return;
		}
		this.hoveredNodeId.set(null);
		this.hoveredNodeRect.set(null);
	}

	/** Apply a fill colour to a node through the same commit path as a text edit. */
	handleChangeNodeStyle(nodeId: string, fill: string): void {
		const next = commitSmartArtNodeFill(this.element(), nodeId, fill);
		if (!next || !this.editor) {
			return;
		}
		const slideIndex = findOwningSlideIndex(
			this.editor.slides(),
			this.element().id,
			this.slideContext?.slideId() ?? null,
		);
		if (slideIndex < 0) {
			return;
		}
		this.hoveredNodeId.set(null);
		this.hoveredNodeRect.set(null);
		this.editor.updateElement(slideIndex, this.element().id, {
			smartArtData: next,
		} as Partial<PptxElement>);
	}

	/** Update the live draft text on each keystroke. */
	updateDraft(event: Event): void {
		this.draftText = (event.target as HTMLTextAreaElement).value;
	}

	/** Enter commits (via blur); Escape cancels. Propagation always stopped. */
	onEditorKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			// Commit via blur so the single commit path runs once.
			(event.target as HTMLTextAreaElement).blur();
		} else if (event.key === 'Escape') {
			event.preventDefault();
			this.cancelEdit();
		}
	}

	/** Commit the current draft through EditorStateService (blur handler). */
	commitEdit(): void {
		if (this.editSettled) {
			this.editSettled = false;
			return;
		}
		const edit = this.editState();
		if (!edit) {
			return;
		}
		const text = this.draftText;
		this.editState.set(null);
		this.applyCommit(edit.nodeId, text);
	}

	/** Discard the current edit without committing. */
	cancelEdit(): void {
		// Mark as settled so the DOM-removal blur does not commit the cancelled edit.
		this.editSettled = true;
		this.editState.set(null);
	}

	private applyCommit(nodeId: string, text: string): void {
		const data = this.smartArtData();
		if (!data || !this.editor) {
			return;
		}
		const next = commitNodeText(data, nodeId, text);
		if (next === data) {
			return;
		} // no-op: text unchanged
		const slideIndex = findOwningSlideIndex(
			this.editor.slides(),
			this.element().id,
			this.slideContext?.slideId() ?? null,
		);
		if (slideIndex < 0) {
			return;
		}
		this.editor.updateElement(slideIndex, this.element().id, {
			smartArtData: next,
		} as Partial<PptxElement>);
	}
}

// viewers/pptx/packages/vue/src/viewer/components/SmartArt3DRenderer.vue
<script setup lang="ts">
/**
 * SmartArt3DRenderer - Vue 3D SmartArt view on the shared `<pptx-three-view>`.
 *
 * The spec (`resolveSmartArtThreeViewSpec`) and the whole scene live in
 * `pptx-viewer-shared`; this SFC only slots the SVG `SmartArtRenderer` in as
 * the element's fallback (shown while the scene loads, and kept when `three`
 * is missing or the scene fails) and, in edit mode, layers the inline
 * node-text editor on top. When no spec applies (the diagram has nothing to
 * draw) it renders the plain SVG `SmartArtRenderer`. Mirrors React's
 * `SmartArt3DView.tsx`.
 *
 * When the host provides a SmartArtNodeEditKey injection (edit mode), an
 * invisible SmartArtHitTestWrapper overlay is stacked over the scene.
 * Double-clicking it walks up from the click target to the nearest
 * `[data-node-id]` SVG group, projects its screen rect into container-local
 * coordinates, and opens an inline textarea editor for that node. Commits flow
 * through the same injection context the 2D renderer uses (undo/redo + save).
 */
import type { PptxElement } from 'pptx-viewer-core';
import {
	commitSmartArtNodeFill,
	elementInLocalFrame,
	measureSvgViewportRect,
	resolvePalette,
	resolveSmartArtThreeViewSpec,
	shouldCommitSmartArtNodeText,
	smartArtNodeAtPoint,
} from 'ooxml-ui/pptx';
import type { TextStyleAnimationDescriptor } from 'ooxml-ui/pptx';
import { computed, nextTick, ref } from 'vue';
import type { CSSProperties } from 'vue';
import { useI18n } from 'vue-i18n';

import { useElementHitTargetStyle } from '../composables/element-hit-target';
import { getContainerStyle } from '../composables/element-style';
import { useRendering3DFlags } from '../composables/rendering-3d-flags';
import { useSmartArtInlineEditState } from '../composables/smartart-inline-edit';
import { injectSmartArtNodeEdit } from '../composables/smartart-node-edit';
import { useSmartArtHoverRect } from '../composables/useSmartArtHoverRect';
import SmartArtHitTestWrapper from './SmartArtHitTestWrapper.vue';
import SmartArtNodeStyleBar from './SmartArtNodeStyleBar.vue';
import SmartArtRenderer from './SmartArtRenderer.vue';
import ThreeView from './ThreeView';

const props = defineProps<{
	element: PptxElement;
	mediaDataUrls?: Map<string, string>;
	zIndex: number;
	/** True only on the main editable canvas; see `hitTargetStyle`. */
	interactive?: boolean;
	/** True only on the live presentation stage; see `hitTargetStyle`. */
	presenting?: boolean;
	/**
	 * Active font-style emphasis override (Bold Flash, Bold Reveal, Underline,
	 * Change Font Style/Size), applied to every node caption by the scene. The
	 * parent `ElementRenderer`'s DOM CSS override (`buildTextStyleOverrideCss`)
	 * cannot reach a canvas-texture caption; the SVG fallback still takes the
	 * CSS override directly.
	 */
	textStyle?: TextStyleAnimationDescriptor;
	/** Forwarded to the fallback SVG `SmartArtRenderer` (see `textStyle` above). */
	textStyleOverrideCss?: string;
}>();

const { t } = useI18n();

const smartArtData = computed(() =>
	props.element.type === 'smartArt' ? props.element.smartArtData : undefined,
);

const flags = useRendering3DFlags();
const spec = computed(() => resolveSmartArtThreeViewSpec(props.element, flags.value.smartArt3D));

/** The element in the container's own frame, for the slotted fallback and hit-test copies. */
const localElement = computed(() => elementInLocalFrame(props.element));

const containerRef = ref<HTMLElement | null>(null);
const editorEl = ref<HTMLTextAreaElement | null>(null);

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);

/**
 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE) 3D
 * SmartArt scene: see `ElementRenderer`'s `hitTargetStyle` doc comment (issue
 * #285). Never rendered while presenting.
 */
const hitTargetStyle = useElementHitTargetStyle(
	() => props.element,
	() => props.interactive,
	() => props.presenting,
);

// ── Inline editing (injection-based, mirrors SmartArtRenderer.vue) ──────────

const nodeEdit = injectSmartArtNodeEdit();
const canEdit = computed(() => Boolean(nodeEdit?.canEdit()));

const editState = useSmartArtInlineEditState();

// The 2D renderer's hover swatch bar, over the scene: hover is tracked on the
// hit-test overlay, whose SVG shares the container's coordinates.
const palette = computed<string[]>(() => resolvePalette(smartArtData.value));
const styleBarEl = ref<HTMLElement | null>(null);
const {
	hoveredNodeId,
	hoveredNodeRect,
	onMouseMove: onHoverMouseMove,
	onMouseLeave: onHoverMouseLeave,
} = useSmartArtHoverRect(containerRef);

/** Approximate rendered size of the style bar (6 swatches + padding/border). */
const STYLE_BAR_WIDTH = 168;
const STYLE_BAR_HEIGHT = 40;

const styleBarStyle = computed<CSSProperties | undefined>(() => {
	const rect = hoveredNodeRect.value;
	const container = containerRef.value;
	if (!rect || !container) {
		return undefined;
	}
	const maxLeft = Math.max(0, container.clientWidth - STYLE_BAR_WIDTH);
	const maxTop = Math.max(0, container.clientHeight - STYLE_BAR_HEIGHT);
	return {
		position: 'absolute',
		left: `${Math.min(maxLeft, Math.max(0, rect.left + rect.width - STYLE_BAR_WIDTH))}px`,
		top: `${Math.min(maxTop, Math.max(0, rect.top - 22))}px`,
		zIndex: 25,
	};
});

/**
 * The overlay and the bar are siblings, so crossing from one to the other fires
 * `mouseleave` on the first; only a leave to somewhere else ends the hover.
 */
function onHoverLeave(event: MouseEvent): void {
	const to = event.relatedTarget;
	const host = containerRef.value;
	if (to instanceof Node && host?.contains(to) && !(to instanceof HTMLTextAreaElement)) {
		return;
	}
	onHoverMouseLeave();
}

/** Apply a fill colour to a node through the host's style commit. */
function handleChangeNodeStyle(nodeId: string, fill: string): void {
	const next = commitSmartArtNodeFill(props.element, nodeId, fill);
	if (next) {
		nodeEdit?.commitStyle?.(props.element.id, { smartArtData: next } as Partial<PptxElement>);
	}
}

function onOverlayDblClick(e: MouseEvent): void {
	// By geometry, not by event target: the overlay is invisible and the scene is
	// drawn in perspective, so the pointer often lands on a gap in the overlay.
	const overlay = e.currentTarget;
	const container = containerRef.value;
	if (!(overlay instanceof Element) || !container) {
		return;
	}
	const nodeEl = smartArtNodeAtPoint(overlay, e.clientX, e.clientY);
	if (!nodeEl) {
		return;
	}
	const nodeId = nodeEl.getAttribute('data-smartart-node-id');
	if (!nodeId || !nodeEdit) {
		return;
	}
	const data = smartArtData.value;
	if (!data) {
		return;
	}
	const currentText = data.nodes.find((n) => n.id === nodeId)?.text ?? '';
	// In the diagram's own SVG coordinates, as the 2D renderer measures: screen
	// rects are wrong once the element is turned or the slide zoomed.
	const rect = measureSvgViewportRect(nodeEl);
	if (!rect) {
		return;
	}
	editState.begin(nodeId, currentText, rect);
	void nextTick(() => {
		editorEl.value?.focus();
		editorEl.value?.select();
	});
}

function commitEdit(): void {
	const nodeId = editState.editingNodeId.value;
	const data = smartArtData.value;
	if (
		nodeId &&
		data &&
		nodeEdit &&
		shouldCommitSmartArtNodeText(data, nodeId, editState.draft.value)
	) {
		nodeEdit.commit(props.element.id, nodeId, editState.draft.value);
	}
	editState.cancel();
}
</script>

<template>
	<SmartArtRenderer
		v-if="!spec"
		:element="element"
		:media-data-urls="mediaDataUrls"
		:z-index="zIndex"
		:interactive="interactive"
		:presenting="presenting"
		:text-style-override-css="textStyleOverrideCss"
	/>
	<div
		v-else
		ref="containerRef"
		class="pptx-vue-element pptx-vue-smartart-3d"
		:style="containerStyle"
		:data-element-id="element.id"
	>
		<!-- Interaction-only hit-target for a degenerate 3D SmartArt; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<ThreeView :spec="spec" :interactive="canEdit" :text-style="textStyle">
			<SmartArtRenderer
				:element="localElement"
				:media-data-urls="mediaDataUrls"
				:z-index="0"
				:text-style-override-css="textStyleOverrideCss"
			/>
		</ThreeView>

		<template v-if="canEdit">
			<!-- Invisible SVG overlay: data-node-id groups are pointer-events hit targets -->
			<div
				class="pptx-vue-smartart-3d-hittest"
				@dblclick.stop="onOverlayDblClick"
				@mousemove="onHoverMouseMove($event, styleBarEl)"
				@mouseleave="onHoverLeave"
			>
				<SmartArtHitTestWrapper :element="localElement" :zIndex="0" />
			</div>

			<!-- Per-node fill colour picker (hover swatch bar), as on the 2D diagram -->
			<div
				v-if="hoveredNodeId && !editState.isEditing.value && hoveredNodeRect"
				ref="styleBarEl"
				:style="styleBarStyle"
				@mousemove="onHoverMouseMove($event, styleBarEl)"
				@mouseleave="onHoverLeave"
			>
				<SmartArtNodeStyleBar
					:palette="palette"
					@pick-fill="handleChangeNodeStyle(hoveredNodeId!, $event)"
				/>
			</div>

			<!-- Inline node text editor, positioned over the clicked node -->
			<textarea
				v-if="editState.isEditing.value && editState.rect.value"
				ref="editorEl"
				v-model="editState.draft.value"
				class="pptx-vue-smartart-3d-editor"
				spellcheck="false"
				:aria-label="t('pptx.smartArt.editNodeText')"
				:style="{
					left: `${editState.rect.value.left}px`,
					top: `${editState.rect.value.top}px`,
					width: `${editState.rect.value.width}px`,
					height: `${editState.rect.value.height}px`,
				}"
				@mousedown.stop
				@click.stop
				@dblclick.stop
				@blur="commitEdit"
				@keydown.enter.prevent="commitEdit"
				@keydown.esc.prevent="editState.cancel()"
				@keydown.stop
			/>
		</template>
	</div>
</template>

<style scoped>
/* Invisible hit-test overlay: fills the canvas area, captures dblclicks.
   opacity:0 makes it invisible while keeping it in the layout + event flow. */
.pptx-vue-smartart-3d-hittest {
	position: absolute;
	inset: 0;
	opacity: 0;
}

/* Force pointer-events:auto on SmartArt node groups within the hit-test overlay.
   SmartArtRenderer sets pointer-events:none on its <svg> element; groups only
   get pointer-events:auto when editable=true, which is disabled in the wrapper.
   This rule re-enables them so the dblclick target is the <g> element (carrying
   data-node-id) rather than the overlay div, enabling correct node resolution. */
.pptx-vue-smartart-3d-hittest :deep([data-node-id]) {
	pointer-events: auto;
}

.pptx-vue-smartart-3d-editor {
	position: absolute;
	z-index: 20;
	margin: 0;
	padding: 2px;
	box-sizing: border-box;
	border: 1px solid #2563eb;
	border-radius: 3px;
	resize: none;
	overflow: hidden;
	font: inherit;
	font-size: 12px;
	line-height: 1.2;
	text-align: center;
	color: #111;
	background: rgba(255, 255, 255, 0.95);
	outline: none;
	box-shadow: 0 2px 6px rgba(0, 0, 0, 0.15);
}
</style>
