// viewers/pptx/packages/react/src/viewer/components/StatusBar.tsx
import { resolveStatusBarSave, statusBarViewMode } from 'ooxml-ui/pptx';
import type { PptxUiStatusBarElement, StatusBarRequestEvent } from 'ooxml-ui/pptx';
import React, { useEffect, useRef } from 'react';
import { useTranslation } from 'react-i18next';

import type { AutosaveStatus } from '../hooks/useAutosave';

export interface StatusBarProps {
	slideCount: number;
	activeSlideIndex: number;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	/** Current zoom scale (0-1+ range, e.g. 1.0 = 100%). */
	scale?: number;
	/** Callback to zoom in. */
	onZoomIn?: () => void;
	/** Callback to zoom out. */
	onZoomOut?: () => void;
	/** Callback to zoom to fit. */
	onZoomToFit?: () => void;
	/** Whether the notes panel is expanded. */
	isNotesExpanded?: boolean;
	/** Toggle the notes panel. */
	onToggleNotes?: () => void;
	/** Current viewer mode. */
	mode?: string;
	/** Callback to switch viewer mode. */
	onSetMode?: (mode: 'edit' | 'present') => void;
	/** Callback to toggle slide sorter view. */
	onToggleSlideSorter?: () => void;
	/** Optional collaboration status indicator rendered inline. */
	collaborationSlot?: React.ReactNode;
	/** Hides the zoom in/out/to-fit control cluster. Maps to `hiddenActions: ['zoom']`. */
	hideZoomControls?: boolean;
	/** Hides the notes-panel toggle button. Maps to `hiddenActions: ['notes']`. */
	hideNotesToggle?: boolean;
	/** Hides the quick "Slide Show" (fullscreen present) toggle button. Maps to `hiddenActions: ['fullscreen']`. */
	hideFullscreenToggle?: boolean;
}

/**
 * Thin adapter around the shared `pptx-ui-status-bar`: it maps viewer state to the
 * element's controlled state and routes `status-request` intents to the handlers.
 */
export function StatusBar(p: StatusBarProps): React.ReactElement {
	const { t } = useTranslation();
	const ref = useRef<PptxUiStatusBarElement>(null);
	const save = resolveStatusBarSave(t, p.autosaveStatus, p.isDirty);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		host.state = {
			slideCount: p.slideCount,
			activeSlideIndex: p.activeSlideIndex,
			saveText: save.text,
			saveKind: save.kind,
			zoomPercent: p.scale !== undefined && !p.hideZoomControls ? (p.scale ?? 1) * 100 : undefined,
			showNotes: Boolean(p.onToggleNotes) && !p.hideNotesToggle,
			notesExpanded: p.isNotesExpanded === true,
			showViewModes: Boolean(p.onSetMode),
			showSorter: Boolean(p.onToggleSlideSorter),
			showSlideShow: !p.hideFullscreenToggle,
			viewMode: statusBarViewMode(p.mode),
			translate: t,
		};
	}, [p, save.text, save.kind, t]);
	useEffect(() => {
		const host = ref.current;
		if (!host) {
			return;
		}
		const request = (event: Event) => {
			switch ((event as StatusBarRequestEvent).detail.id) {
				case 'notes':
					p.onToggleNotes?.();
					break;
				case 'normal':
					p.onSetMode?.('edit');
					break;
				case 'sorter':
					p.onToggleSlideSorter?.();
					break;
				case 'slideShow':
					p.onSetMode?.('present');
					break;
				case 'zoomOut':
					p.onZoomOut?.();
					break;
				case 'zoomFit':
					p.onZoomToFit?.();
					break;
				case 'zoomIn':
					p.onZoomIn?.();
			}
		};
		host.addEventListener('status-request', request);
		return () => host.removeEventListener('status-request', request);
	}, [p]);
	return (
		<pptx-ui-status-bar ref={ref}>
			{p.collaborationSlot ? (
				<div slot='collaboration' style={{ display: 'contents' }}>
					{p.collaborationSlot}
				</div>
			) : null}
		</pptx-ui-status-bar>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/StatusBar.vue
<script setup lang="ts">
/**
 * StatusBar - thin adapter around the shared `pptx-ui-status-bar` element.
 *
 * The slide counter, save indicator, notes toggle, view-mode buttons and zoom
 * cluster live in the shared view. This component maps viewer state onto the
 * element's controlled state and re-emits its typed intents.
 */
import { resolveStatusBarSave, statusBarViewMode } from 'ooxml-ui/pptx';
import type { StatusBarRequestEvent, ToolbarActionId } from 'ooxml-ui/pptx';
import { computed, useSlots } from 'vue';
import { useI18n } from 'vue-i18n';

import type { AutosaveStatus } from '../composables/useAutosave';
import { useToolbarVisibility } from '../composables/useToolbarVisibility';

const { t } = useI18n();

const props = defineProps<{
	slideCount: number;
	activeSlideIndex: number;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	/** Epoch ms of the last successful autosave, for the "Saved <time>" label. */
	lastSavedAt?: number | null;
	/** Current zoom scale (1 = 100%). */
	scale?: number;
	/** Whether the notes panel is expanded. */
	isNotesExpanded?: boolean;
	/** Current viewer mode. */
	mode?: string;
	/** Whether the Notes toggle is shown (host has a notes panel). */
	showNotes?: boolean;
	/** Toolbar buttons the host has asked to hide (zoom, notes, fullscreen). */
	hiddenActions?: ToolbarActionId[];
}>();

const slots = useSlots();
const { isHidden } = useToolbarVisibility(() => props.hiddenActions);

const emit = defineEmits<{
	'zoom-in': [];
	'zoom-out': [];
	'zoom-to-fit': [];
	'toggle-notes': [];
	'set-mode': [mode: 'edit' | 'present'];
	'toggle-slide-sorter': [];
}>();

const state = computed(() => {
	const save = resolveStatusBarSave(
		t,
		props.autosaveStatus
			? { state: props.autosaveStatus, timestamp: props.lastSavedAt ?? undefined }
			: undefined,
		props.isDirty,
	);
	return {
		slideCount: props.slideCount,
		activeSlideIndex: props.activeSlideIndex,
		saveText: save.text,
		saveKind: save.kind,
		zoomPercent:
			props.scale !== undefined && !isHidden('zoom') ? (props.scale ?? 1) * 100 : undefined,
		showNotes: props.showNotes === true && !isHidden('notes'),
		notesExpanded: props.isNotesExpanded === true,
		showSlideShow: !isHidden('fullscreen'),
		viewMode: statusBarViewMode(props.mode),
		translate: t,
	};
});

function request(event: Event): void {
	switch ((event as StatusBarRequestEvent).detail.id) {
		case 'notes':
			emit('toggle-notes');
			break;
		case 'normal':
			emit('set-mode', 'edit');
			break;
		case 'sorter':
			emit('toggle-slide-sorter');
			break;
		case 'slideShow':
			emit('set-mode', 'present');
			break;
		case 'zoomOut':
			emit('zoom-out');
			break;
		case 'zoomFit':
			emit('zoom-to-fit');
			break;
		case 'zoomIn':
			emit('zoom-in');
	}
}
</script>

<template>
	<pptx-ui-status-bar :state.prop="state" @status-request="request">
		<div v-if="slots.collaboration" slot="collaboration" style="display: contents">
			<slot name="collaboration" />
		</div>
	</pptx-ui-status-bar>
</template>
