// viewers/pptx/packages/svelte/src/viewer/components/settings/OptionsPane.svelte
<script lang="ts">
	/**
	 * Generic File > Options pane: the tab's headline plus its schema-driven
	 * sections of controls, with a `special` snippet slot for the bespoke
	 * blocks (theme picker, clear-cache) and a `children` snippet rendered
	 * after the sections (custom panes such as Quick Access).
	 */
	import type { Snippet } from 'svelte';
	import type {
		ViewerOptions,
		ViewerOptionsGroupId,
		ViewerOptionsSection,
		ViewerOptionsTabDefinition,
	} from 'ooxml-ui/pptx';
	import { useTranslator } from '../../../i18n/context';
	import OptionsControlRow from './OptionsControlRow.svelte';

	const {
		tab,
		options,
		onchange,
		special,
		children,
	}: {
		tab: ViewerOptionsTabDefinition;
		options: ViewerOptions;
		onchange: (group: ViewerOptionsGroupId, key: string, value: boolean | number | string) => void;
		special?: Snippet<[ViewerOptionsSection]>;
		children?: Snippet;
	} = $props();
	const t = useTranslator();
</script>

<div class="pane">
	<p class="headline">{t(tab.descriptionKey)}</p>
	{#each tab.sections as section (section.id)}
		<section>
			<h3>{t(section.titleKey)}</h3>
			{#if section.descriptionKey}<p class="hint">{t(section.descriptionKey)}</p>{/if}
			{#each section.controls as control (`${control.group}.${control.key}`)}
				<OptionsControlRow {control} {options} {onchange} />
			{/each}
			{#if section.special}{@render special?.(section)}{/if}
		</section>
	{/each}
	{@render children?.()}
</div>

<style>
	.pane { display: flex; flex-direction: column; gap: 18px; }
	.headline { margin: 0; color: var(--pptx-foreground, #e2e8f0); font-size: 12.5px; font-weight: 600; }
	section h3 { margin: 0 0 4px; border-bottom: 1px solid color-mix(in srgb, var(--pptx-border, #3f3f52) 60%, transparent); padding-bottom: 4px; color: var(--pptx-muted-foreground, #94a3b8); font-size: 10.5px; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase; }
	.hint { margin: 0 0 8px; color: var(--pptx-muted-foreground, #94a3b8); font-size: 11px; }
</style>

// viewers/pptx/packages/vue/src/viewer/components/settings/OptionsPane.vue
<script setup lang="ts">
/**
 * OptionsPane - generic File > Options pane: the tab's headline plus its
 * schema-driven sections of controls. Vue counterpart of React's
 * `settings/OptionsPane.tsx`.
 *
 * Bespoke blocks (theme picker, clear-cache button) are rendered by the parent
 * through the scoped `special` slot, keyed by `section.special`; extra content
 * for custom panes (the Quick Access chooser) goes into the default slot.
 */
import type {
	ViewerOptions,
	ViewerOptionsGroupId,
	ViewerOptionsTabDefinition,
} from 'ooxml-ui/pptx';
import { useI18n } from 'vue-i18n';

import OptionsControlRow from './OptionsControlRow.vue';

defineProps<{
	tab: ViewerOptionsTabDefinition;
	options: ViewerOptions;
	onOptionChange: (
		group: ViewerOptionsGroupId,
		key: string,
		value: boolean | number | string,
	) => void;
}>();

const { t } = useI18n();
</script>

<template>
	<div class="pptx-vue-options-pane space-y-5">
		<p class="text-sm font-medium text-foreground">{{ t(tab.descriptionKey) }}</p>
		<section v-for="section in tab.sections" :key="section.id">
			<h3
				class="mb-1 border-b border-border/60 pb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground"
			>
				{{ t(section.titleKey) }}
			</h3>
			<p v-if="section.descriptionKey" class="mb-2 text-xs text-muted-foreground">
				{{ t(section.descriptionKey) }}
			</p>
			<div class="space-y-0.5">
				<OptionsControlRow
					v-for="control in section.controls"
					:key="`${control.group}.${control.key}.${section.id}`"
					:control="control"
					:options="options"
					:on-option-change="onOptionChange"
				/>
			</div>
			<slot v-if="section.special" name="special" :section="section" />
		</section>
		<slot />
	</div>
</template>
