// viewers/teams/packages/react/src/index.ts
import {
	createElement,
	forwardRef,
	useEffect,
	useImperativeHandle,
	useLayoutEffect,
	useRef,
	useState,
	useSyncExternalStore,
} from 'react';
import {
	applyTeamsProps,
	createTeams,
	defineTeamsApp,
	listenTeamsEvents,
	type TeamsApp,
	type TeamsClient,
	type TeamsClientOptions,
	type TeamsProps,
	type TeamsState,
} from 'teams-viewer';

export type { TeamsClient, TeamsClientOptions, TeamsProps, TeamsState } from 'teams-viewer';

/** `<Teams workspaceId="acme" userName="Ada" config={...} onOpenFile={...} />`: the full UI. */
export const Teams = forwardRef<TeamsApp | null, TeamsProps & { className?: string }>(function Teams(
	{ className, ...props },
	ref,
) {
	const el = useRef<TeamsApp | null>(null);
	const latest = useRef<TeamsProps>(props);
	const applied = useRef<TeamsProps>({});
	latest.current = props;
	useImperativeHandle(ref, () => el.current as TeamsApp, []);
	useLayoutEffect(() => {
		defineTeamsApp();
	}, []);
	// Props are applied after every render; unchanged values are skipped inside applyTeamsProps.
	useEffect(() => {
		if (!el.current) return;
		applyTeamsProps(el.current, props, applied.current);
		applied.current = props;
	});
	useEffect(() => (el.current ? listenTeamsEvents(el.current, () => latest.current) : undefined), []);
	return createElement('teams-app', {
		ref: el,
		class: className,
		style: { display: 'block', height: '100%' },
	});
});

/**
 * The raw hook: a core client for `options`, recreated when the workspace, user or server change
 * and destroyed on unmount. Returns `null` until mounted (and while `options` is `null`).
 *
 *   const client = useTeamsClient({ workspaceId: 'acme', user, config });
 *   const state = useTeamsState(client);
 */
export function useTeamsClient(options: TeamsClientOptions | null): TeamsClient | null {
	const [client, setClient] = useState<TeamsClient | null>(null);
	const key = options ? JSON.stringify([options.workspaceId, options.user, options.config]) : '';
	const latest = useRef(options);
	latest.current = options;
	useEffect(() => {
		const opts = latest.current;
		if (!opts) return;
		const created = createTeams(opts);
		setClient(created);
		return () => {
			created.destroy();
			setClient(null);
		};
	}, [key]);
	return client;
}

const NO_UNSUBSCRIBE = (): void => {};
/** The current immutable state of a client; re-renders on every change (`useSyncExternalStore`). */
export function useTeamsState(client: TeamsClient | null): TeamsState | null {
	return useSyncExternalStore(
		client ? client.subscribe : () => NO_UNSUBSCRIBE,
		() => (client ? client.getState() : null),
		() => null,
	);
}

/** `useTeamsClient` and `useTeamsState` in one call: `const { client, state } = useTeams(options)`. */
export function useTeams(options: TeamsClientOptions | null): {
	client: TeamsClient | null;
	state: TeamsState | null;
} {
	const client = useTeamsClient(options);
	return { client, state: useTeamsState(client) };
}

// viewers/teams/packages/solid/src/index.ts
import { createEffect, createSignal, onCleanup, onMount, type Accessor } from 'solid-js';
import {
	applyTeamsProps,
	createTeams,
	defineTeamsApp,
	listenTeamsEvents,
	type TeamsApp,
	type TeamsClient,
	type TeamsClientOptions,
	type TeamsProps,
	type TeamsState,
} from 'teams-viewer';

export type { TeamsClient, TeamsClientOptions, TeamsProps, TeamsState } from 'teams-viewer';

/**
 * Returns the `<teams-app>` element; use it as `{Teams(props)}` inside JSX. A plain function (no
 * JSX transform needed) keeps the package a lifecycle adapter: props are re-applied reactively
 * and handlers are read at event time.
 */
export function Teams(props: TeamsProps): HTMLElement {
	defineTeamsApp();
	const el = document.createElement('teams-app') as TeamsApp;
	el.style.display = 'block';
	el.style.height = '100%';
	let applied: TeamsProps = {};
	const snapshot = (): TeamsProps => ({
		...(props.workspaceId !== undefined ? { workspaceId: props.workspaceId } : {}),
		...(props.userName !== undefined ? { userName: props.userName } : {}),
		...(props.userId !== undefined ? { userId: props.userId } : {}),
		...(props.config !== undefined ? { config: props.config } : {}),
		...(props.uploadFile ? { uploadFile: props.uploadFile } : {}),
		...(props.openers ? { openers: props.openers } : {}),
	});
	createEffect(() => {
		const next = snapshot();
		applyTeamsProps(el, next, applied);
		applied = next;
	});
	onMount(() => onCleanup(listenTeamsEvents(el, () => props)));
	return el;
}

/**
 * The raw primitive: a client for `options()`, recreated when it changes and destroyed with the
 * owner. `state()` is a signal that holds the latest snapshot.
 *
 *   const { client, state } = createTeamsClient(() => ({ workspaceId: 'acme', user, config }));
 */
export function createTeamsClient(options: () => TeamsClientOptions | null): {
	client: Accessor<TeamsClient | null>;
	state: Accessor<TeamsState | null>;
} {
	const [client, setClient] = createSignal<TeamsClient | null>(null);
	const [state, setState] = createSignal<TeamsState | null>(null, { equals: false });
	createEffect(() => {
		const opts = options();
		if (!opts) return;
		const created = createTeams(opts);
		setClient(created);
		setState(created.getState());
		const off = created.subscribe(() => setState(created.getState()));
		onCleanup(() => {
			off();
			created.destroy();
			setClient(null);
			setState(null);
		});
	});
	return { client, state };
}
