// viewers/pptx/packages/svelte/src/viewer/components/SectionContextMenu.svelte
<script lang="ts">
	/**
	 * The slides rail's section-header right-click menu: Rename, Delete, Move
	 * Up, Move Down, Add Section After. The command list, separators and
	 * end-of-list gating come from `pptx-viewer-shared`'s
	 * `buildSectionContextMenuEntries`; this component only renders it, the
	 * sibling of `ThumbnailContextMenu.svelte`.
	 */
	import { buildSectionContextMenuEntries, clampFlyoutPosition } from 'ooxml-ui/pptx';
	import type { SectionContextMenuCommandId } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';

	const {
		x,
		y,
		sectionIndex,
		totalSections,
		onrun,
		onclose,
	}: {
		x: number;
		y: number;
		sectionIndex: number;
		totalSections: number;
		onrun: (id: SectionContextMenuCommandId) => void;
		onclose: () => void;
	} = $props();
	const t = useTranslator();

	const entries = $derived(buildSectionContextMenuEntries({ sectionIndex, totalSections }));

	let menuWidth = $state(0);
	let menuHeight = $state(0);
	const menuStyle = $derived.by(() => {
		const { left, top } = clampFlyoutPosition({
			x,
			y,
			width: menuWidth,
			height: menuHeight,
			viewportWidth: typeof window === 'undefined' ? 0 : window.innerWidth,
			viewportHeight: typeof window === 'undefined' ? 0 : window.innerHeight,
		});
		return `left: ${left}px; top: ${top}px`;
	});
</script>

<svelte:window
	onkeydown={(event) => {
		if (event.key === 'Escape') onclose();
	}}
/>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<div
	class="pptx-svelte-context-backdrop"
	aria-hidden="true"
	onclick={onclose}
	oncontextmenu={(event) => {
		event.preventDefault();
		onclose();
	}}
></div>
<div
	class="pptx-svelte-context-menu"
	data-pptx-context-menu="true"
	data-pptx-section-context-menu="true"
	role="menu"
	aria-label={t('pptx.sections.sectionButtonLabel')}
	style={menuStyle}
	bind:clientWidth={menuWidth}
	bind:clientHeight={menuHeight}
>
	{#each entries as entry (entry.id)}
		{#if entry.separatorBefore}<div class="pptx-svelte-context-separator" role="separator"></div>{/if}
		<button type="button" role="menuitem" disabled={entry.disabled} onclick={() => onrun(entry.id)}>
			{t(entry.labelKey)}
		</button>
	{/each}
</div>

<style>
	.pptx-svelte-context-backdrop { position: fixed; inset: 0; z-index: 119; }
	.pptx-svelte-context-menu { position: fixed; z-index: 120; display: flex; min-width: 160px; flex-direction: column; padding: 6px 0; border: 1px solid var(--pptx-border, #33334d); border-radius: var(--pptx-radius, 6px); background: var(--pptx-card, #1e1e2e); box-shadow: 0 18px 40px rgb(0 0 0 / 35%); color: var(--pptx-card-foreground, #e2e8f0); font-family: system-ui, sans-serif; font-size: 12px; }
	.pptx-svelte-context-menu button { padding: 6px 12px; border: 0; background: transparent; color: inherit; font: inherit; text-align: left; cursor: pointer; }
	.pptx-svelte-context-menu button:hover, .pptx-svelte-context-menu button:focus-visible { background: var(--pptx-accent, #33334d); outline: none; }
	.pptx-svelte-context-menu button:disabled { opacity: 0.45; cursor: default; }
	.pptx-svelte-context-menu button:disabled:hover { background: transparent; }
	.pptx-svelte-context-separator { height: 1px; margin: 5px 0; background: var(--pptx-border, #33334d); }
</style>

// viewers/pptx/packages/react/src/viewer/components/slides-pane/SectionContextMenu.tsx
import { buildSectionContextMenuEntries, sectionAddAfterSlideIndex } from 'ooxml-ui/pptx';
import type { SectionContextMenuCommandId } from 'ooxml-ui/pptx';
import type React from 'react';
import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';

import type { SlideSectionGroup } from '../../types';
import { ContextMenuItem, ContextMenuSeparator } from '../context-menu-parts';
import type { SectionContextMenuState } from './types';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface SectionContextMenuProps {
	state: SectionContextMenuState;
	sectionGroups: SlideSectionGroup[];
	totalSlides: number;
	onStartRename: (sectionId: string, currentLabel: string) => void;
	onDeleteSection?: (sectionId: string) => void;
	onMoveSectionUp?: (sectionId: string) => void;
	onMoveSectionDown?: (sectionId: string) => void;
	onAddSection?: (name: string, afterSlideIndex: number) => void;
	onClose: () => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * The section-header right-click menu. The command list, order, separators and
 * end-of-list gating come from the shared `buildSectionContextMenuEntries`, so
 * this menu cannot drift from the other four bindings.
 */
export function SectionContextMenu({
	state,
	sectionGroups,
	totalSlides,
	onStartRename,
	onDeleteSection,
	onMoveSectionUp,
	onMoveSectionDown,
	onAddSection,
	onClose,
}: SectionContextMenuProps): React.ReactElement {
	const { t } = useTranslation();

	useEffect(() => {
		const onKeyDown = (event: KeyboardEvent) => {
			if (event.key === 'Escape') {
				event.preventDefault();
				onClose();
			}
		};
		document.addEventListener('keydown', onKeyDown);
		return () => document.removeEventListener('keydown', onKeyDown);
	}, [onClose]);

	const entries = buildSectionContextMenuEntries({
		sectionIndex: state.sectionIndex,
		totalSections: state.totalSections,
	});

	const run = (id: SectionContextMenuCommandId): void => {
		const group = sectionGroups.find((g) => g.id === state.sectionId);
		switch (id) {
			case 'rename':
				if (group) {
					onStartRename(state.sectionId, group.label);
				}
				return;
			case 'delete':
				onDeleteSection?.(state.sectionId);
				break;
			case 'move-up':
				onMoveSectionUp?.(state.sectionId);
				break;
			case 'move-down':
				onMoveSectionDown?.(state.sectionId);
				break;
			case 'add-after':
				if (group) {
					onAddSection?.(
						t('pptx.sections.defaultName'),
						sectionAddAfterSlideIndex(
							group.slideIndexes[group.slideIndexes.length - 1],
							totalSlides,
						),
					);
				}
				break;
			default:
				break;
		}
		onClose();
	};

	return (
		<div
			data-pptx-context-menu='true'
			data-pptx-section-context-menu='true'
			role='menu'
			tabIndex={-1}
			aria-label={t('pptx.sections.sectionButtonLabel')}
			className='fixed z-50 min-w-[160px] rounded-md border border-border bg-popover py-1 text-xs text-foreground shadow-xl'
			style={{ left: state.x, top: state.y }}
			onClick={(e: React.MouseEvent) => e.stopPropagation()}
		>
			{entries.map((entry) => (
				<span key={entry.id}>
					{entry.separatorBefore && <ContextMenuSeparator />}
					<ContextMenuItem disabled={entry.disabled} onSelect={() => run(entry.id)}>
						{t(entry.labelKey)}
					</ContextMenuItem>
				</span>
			))}
		</div>
	);
}
