// demos/pptx/demo-svelte/src/App.svelte
<script lang="ts">
	/**
	 * Demo shell for `pptx-svelte-viewer`, mirroring demos/demo-vue/src/App.vue:
	 * the viewer fills the screen and a landing dropzone handles file open /
	 * new-deck creation. A
	 * `?room=<id>` URL param joins a serverless (y-webrtc P2P) collaboration
	 * session so two tabs on the same URL edit the same deck live.
	 */
	import type {
		CollaborationConfig,
		PptxAiConfig,
		PowerPointViewerApi,
		ViewerCustomization,
	} from 'pptx-svelte-viewer';
	// The openable-file allow list comes from the binding's public surface, not
	// a local regex: a hand-rolled `.pptx|.ppt|.json` refused a `.pptm` on drop
	// that the viewer's own File > Open accepted.
	import {
		forgetSessionDeck,
		isSupportedPresentationFile,
		loadPresentationDeck,
		PPTX_OPEN_ACCEPT,
		parsePresentationSessionId,
		PowerPointViewer,
		rememberSessionDeck,
		restoreSessionDeck,
		themeToCssVars,
	} from 'pptx-svelte-viewer';
	import { PptxHandler } from 'pptx-viewer-core';

	import { buildViewerAiConfig } from './ai-config';
	import { resolveAutoName, resolveAutoRoomId, randomUserColor } from './collab';
	import { language, t } from './demo-i18n.svelte';
	import { installDevViewerHandle } from '../../dev-viewer-handle';
	import { currentDemoCustomization } from '../../shared/demo-customization';
	import { currentDemoRootOptions } from '../../shared/demo-root-options';
	import { currentDemo3DFlags } from '../../shared/rendering-3d-flags';
	import { readStoredTheme, themes } from './themes';

	let viewerRef: PowerPointViewerApi | undefined = $state();
	$effect(() => installDevViewerHandle(() => viewerRef, import.meta.env.DEV));
	let bytes = $state<Uint8Array | null>(null);
	let fileName = $state('');
	// Built from the persisted demo AI settings when a deck opens; undefined
	// leaves the viewer with no AI assistant (the default when no key is set).
	let aiConfig = $state<PptxAiConfig | undefined>(undefined);
	const themeKey = readStoredTheme();
	let errorMessage = $state('');
	// eslint-disable-next-line prefer-const

	const params = new URLSearchParams(window.location.search);
	// The six opt-in Three.js scenes: on for a person, off under browser
	// automation unless a `?<flag>=1` query param opts in; see
	// demos/shared/rendering-3d-flags.ts for the rules and why.
	const { smartArt3D, surfaceChart3D, barChart3D, lineChart3D, areaChart3D, pieChart3D } =
		currentDemo3DFlags();
	// `?customization=<json>` (demos/shared/demo-customization.ts), for e2e.
	const customization = currentDemoCustomization() as ViewerCustomization | undefined;
	// `?showToolbar=0`, `?showThumbnails=0`, `?initialSlide=<n>`
	// (demos/shared/demo-root-options.ts), for e2e.
	const rootOptions = currentDemoRootOptions();
	const audienceSession = parsePresentationSessionId(window.location.hash);
	if (audienceSession) {
		void loadPresentationDeck(audienceSession).then((content) => {
			if (content) {
				bytes = content;
				fileName = 'Audience View';
			}
			return undefined;
		});
	}

	// ── Collaboration (serverless WebRTC P2P) ────────────────────────────
	// A `?room=<id>` param auto-joins that room on load (a peer with no local
	// deck yet still needs the viewer mounted to receive one). Once a deck is
	// open, the viewer's own toolbar Share/Broadcast buttons (built into
	// `pptx-svelte-viewer`) start a fresh session directly; `onCollabStart`
	// below stamps the resulting room id into the URL so the session survives
	// a refresh and can be copied from the address bar, mirroring `joinRoom`.
	const autoName = resolveAutoName();
	const autoColor = randomUserColor();
	let collaborationConfig = $state<CollaborationConfig | null>(null);

	function joinRoom(roomId: string): void {
		collaborationConfig = {
			roomId,
			serverUrl: '',
			transport: 'webrtc',
			userName: autoName,
			userColor: autoColor,
			role: 'collaborator',
		};
		setRoomUrlParam(roomId);
	}

	function setRoomUrlParam(roomId: string): void {
		const url = new URL(window.location.href);
		url.searchParams.set('room', roomId);
		window.history.replaceState(null, '', url.toString());
		document.title = `Collaborating: ${roomId} - PPTX Viewer`;
	}

	function clearRoomUrlParam(): void {
		const url = new URL(window.location.href);
		url.searchParams.delete('room');
		window.history.replaceState(null, '', url.toString());
	}

	function onCollabStart(config: CollaborationConfig): void {
		setRoomUrlParam(config.roomId);
	}

	function onCollabStop(): void {
		collaborationConfig = null;
		clearRoomUrlParam();
	}

	const urlRoom = params.get('room');

	// Prefilled values for the viewer's built-in Share dialog form.
	const shareDefaults = { roomId: resolveAutoRoomId(), userName: autoName };

	// Mount the viewer whenever we have a deck OR an active room (a joiner with
	// no local deck still needs the viewer mounted to receive the peer's slides).
	const viewerMounted = $derived(Boolean(bytes) || Boolean(collaborationConfig));

	const currentTheme = $derived((themes[themeKey] ?? themes.vermilionDark).theme);

	// Apply theme vars to :root so the dropzone chrome tracks the theme. Like
	// the React demo, the preset is NOT passed to <PowerPointViewer>: the
	// viewer's own Settings > Appearance picker owns the viewer chrome theme
	// (so "Default" resolves to the built-in defaults).
	let appliedVarKeys: string[] = [];
	$effect(() => {
		const vars = themeToCssVars(currentTheme);
		const root = document.documentElement;
		for (const key of appliedVarKeys) {
			root.style.removeProperty(key);
		}
		appliedVarKeys = Object.keys(vars);
		for (const key of appliedVarKeys) {
			root.style.setProperty(key, vars[key]);
		}
	});

	function openFile(file: File): void {
		dropSampleParam();
		errorMessage = '';
		aiConfig = buildViewerAiConfig();
		fileName = file.name;
		void file.arrayBuffer().then((buf) => {
			bytes = new Uint8Array(buf);
			document.title = `${file.name} - PPTX Viewer`;
			return undefined;
		});
	}

	let creating = $state(false);

	async function newPresentation(): Promise<void> {
		dropSampleParam();
		creating = true;
		aiConfig = buildViewerAiConfig();
		try {
			const { handler, data } = await PptxHandler.createBlank({
				title: 'Untitled Presentation',
				initialSlideCount: 1,
			});
			const saved = await handler.save(data.slides);
			handler.dispose();
			bytes = saved;
			fileName = 'Untitled Presentation';
			document.title = 'Untitled Presentation - PPTX Viewer';
		} finally {
			creating = false;
		}
	}

	// `?sample=1` auto-loads the bundled sample deck (used by the docs landing
	// page to embed a live, pre-populated viewer). With `?room=` too, the sample
	// seeds the collaboration session instead of a blank deck.
	const urlSample = params.get('sample') === '1';

	async function loadSampleDeck(): Promise<void> {
		try {
			const res = await fetch(`${import.meta.env.BASE_URL}sample-deck.pptx`);
			if (!res.ok) {
				throw new Error(`HTTP ${res.status}`);
			}
			const buf = await res.arrayBuffer();
			if (!bytes) {
				bytes = new Uint8Array(buf);
				fileName = 'sample-deck.pptx';
				document.title = 'sample-deck.pptx - PPTX Viewer';
			}
		} catch {
			// Sample not available: fall through to the regular dropzone.
		}
	}

	// ── Refresh survival ────────────────────────────────────────────────────
	// Remember the open deck for THIS tab, and reopen it on the next load. A
	// refresh used to drop the presentation and land the user back on the file
	// picker; now it comes back, with any autosaved edits (restoreSessionDeck
	// prefers the newer of the two). An audience tab is fed by the presenter
	// window, so it neither remembers nor restores.
	$effect(() => {
		const current = bytes;
		if (!current || audienceSession) {
			return;
		}
		void rememberSessionDeck(fileName, current);
	});

	/**
	 * Reopen the deck this tab had before a refresh, falling back to the
	 * `?sample=1` deck. A restored deck beats the sample: this tab has moved on
	 * from it (the user opened a deck of their own, possibly through the viewer's
	 * own File > Open), so the flag is retired rather than seeding it again.
	 */
	async function restoreSession(): Promise<void> {
		const deck = await restoreSessionDeck();
		if (!deck || bytes) {
			if (urlSample && !bytes) {
				await loadSampleDeck();
			}
			return;
		}
		dropSampleParam();
		aiConfig = buildViewerAiConfig();
		bytes = deck.data;
		fileName = deck.fileName;
		document.title = `${deck.fileName} - PPTX Viewer`;
	}

	/**
	 * Drop `?sample=1` from the address bar.
	 *
	 * The docs landing page embeds the demo with `?sample=1` so it opens
	 * pre-populated. Once the user opens a deck of their own that param is stale:
	 * left in place it would re-seed the bundled sample on the next refresh and
	 * throw away what they were looking at.
	 */
	function dropSampleParam(): void {
		const url = new URL(window.location.href);
		if (!url.searchParams.has('sample')) {
			return;
		}
		url.searchParams.delete('sample');
		window.history.replaceState(null, '', url.toString());
	}

	if (urlRoom) {
		joinRoom(urlRoom);
		void (urlSample ? loadSampleDeck() : newPresentation());
	} else if (!audienceSession) {
		// The audience branch above owns its tab; everything else reopens this
		// tab's deck, falling back to the sample and then to the dropzone.
		void restoreSession();
	}

	function onDrop(e: DragEvent): void {
		e.preventDefault();
		const file = e.dataTransfer?.files?.[0];
		if (file && isSupportedPresentationFile(file.name)) {
			openFile(file);
		}
	}

	function onInputChange(e: Event): void {
		const file = (e.target as HTMLInputElement).files?.[0];
		if (file) {
			openFile(file);
		}
	}

	// eslint-disable-next-line prefer-const -- `fileInput` is reassigned by Svelte bind:this.
	let fileInput: HTMLInputElement | null = $state(null);

	/** Open the native picker from the explicit Browse control. */
	function openFilePicker(): void {
		fileInput?.click();
	}

	/**
	 * The dashed zone paints `cursor: pointer` over its whole area and the copy
	 * says "click to browse", so the whole area has to open the picker, not just
	 * the one text line that happens to be a <label>. Clicks that originate on a
	 * button, on the label, or on the input itself are already handled by those
	 * elements; re-opening from here would double-fire or loop.
	 */
	function onZoneClick(e: MouseEvent): void {
		if ((e.target as HTMLElement).closest('button, label[for="file-input"], #file-input')) {
			return;
		}
		openFilePicker();
	}

	function onViewerError(message: string): void {
		errorMessage = message || t('demo.viewer.loadError');
		bytes = null;
		document.title = 'pptx-svelte-viewer demo';
		// A deck the viewer cannot load must not be reopened on every refresh.
		void forgetSessionDeck();
	}
</script>

{#if viewerMounted}
	<!-- Match the React demo's full-screen viewer shell and hide the build badge
	     once the presentation chrome is mounted. -->
	<main class="demo-shell" data-pptx-viewer>
		<PowerPointViewer
			bind:this={viewerRef}
			source={bytes}
			locale={language.current}
			{smartArt3D}
			{surfaceChart3D}
			{barChart3D}
			{lineChart3D}
			{areaChart3D}
			{pieChart3D}
			{customization}
			{...rootOptions}
			editable
			autosave
			autosaveIntervalMs={2000}
			fileName={fileName || undefined}
			filePath={fileName || (collaborationConfig ? `room-${collaborationConfig.roomId}.pptx` : undefined)}
			collaboration={collaborationConfig ?? undefined}
			{shareDefaults}
			ai={aiConfig}
			onstartcollaboration={onCollabStart}
			onstopcollaboration={onCollabStop}
			onerror={onViewerError}
		/>
	</main>
{:else}
	<main class="demo-stage">
		<h1 class="sr-only">PPTX Viewer</h1>
		<div
			class="demo-dropzone"
			role="group"
			data-testid="dropzone"
			aria-label={t('demo.dropzone.uploadAriaLabel')}
			onclick={onZoneClick}
			ondrop={onDrop}
			ondragover={(e) => e.preventDefault()}
		>
			<label class="demo-hint" for="file-input">{t('demo.dropzone.hint')}</label>
			<p class="demo-sub">{t('demo.dropzone.processed')}</p>
			<div class="demo-actions">
				<button
					type="button"
					class="demo-browse"
					data-testid="browse-files"
					onclick={(e) => (e.stopPropagation(), openFilePicker())}
				>
					{t('demo.dropzone.browse')}
				</button>
				<button type="button" onclick={(e) => (e.stopPropagation(), newPresentation())} disabled={creating}>
					{creating ? t('demo.dropzone.creating') : t('demo.dropzone.newPresentation')}
				</button>
			</div>
			{#if errorMessage}
				<p class="demo-error">{errorMessage}</p>
			{/if}
			<!-- stopPropagation: the programmatic click() would bubble back to the
			     zone's onclick and re-open the file chooser in a loop -->
			<input
				id="file-input"
				bind:this={fileInput}
				type="file"
				accept={PPTX_OPEN_ACCEPT}
				aria-label={t('demo.dropzone.uploadAriaLabel')}
				class="sr-only"
				onclick={(e) => e.stopPropagation()}
				onchange={onInputChange}
			/>
		</div>
	</main>
{/if}

// demos/pptx/demo-vue/src/App.vue
<script setup lang="ts">
import { PptxHandler } from 'pptx-viewer-core';
import { resolveLocaleParam } from 'pptx-viewer-locales';
// The openable-file allow list comes from the binding's public surface, not a
// local regex: a hand-rolled `.pptx|.ppt|.json` refused a `.pptm` on drop that
// the viewer's own File > Open accepted.
import {
	PPTX_OPEN_ACCEPT,
	PowerPointViewer,
	isAudienceTab,
	isSupportedPresentationFile,
	loadAudienceContent,
	parsePresentationSessionId,
	rememberSessionDeck,
	restoreSessionDeck,
	themeToCssVars,
} from 'pptx-vue-viewer';
import type {
	CollaborationConfig,
	PowerPointViewerExpose,
	ViewerCustomization,
} from 'pptx-vue-viewer';
import { computed, onBeforeUnmount, onMounted, ref, shallowRef, watchEffect } from 'vue';
import 'pptx-vue-viewer/styles';
import { useI18n } from 'vue-i18n';

import { installDevViewerHandle } from '../../dev-viewer-handle';
import { currentDemoCustomization } from '../../shared/demo-customization';
import { currentDemoRootOptions } from '../../shared/demo-root-options';
import { currentDemo3DFlags } from '../../shared/rendering-3d-flags';
import { useDemoAiConfig } from './ai-config';
import {
	isTrustedServerUrl,
	randomUserColor,
	resolveAutoName,
	resolveAutoRoomId,
	resolveDefaultServerUrl,
} from './collab';
import i18n from './i18n';
import type { LanguageCode } from './languages';
import { languageKeys } from './languages';
import { themes } from './themes';

/**
 * Demo app for `pptx-vue-viewer`, mirroring the React `demo/main.tsx`.
 *
 * The viewer fills the screen; there is no demo header (download lives in the
 * viewer's File menu). URL params drive collaboration / broadcast / audience joins.
 */

const viewerRef = shallowRef<PowerPointViewerExpose>();
let removeDevViewerHandle: (() => void) | undefined;
onMounted(() => {
	removeDevViewerHandle = installDevViewerHandle(() => viewerRef.value, import.meta.env.DEV);
});
onBeforeUnmount(() => removeDevViewerHandle?.());

const content = shallowRef<Uint8Array | null>(null);
const fileName = ref('');
// Whether the "does this tab have a deck to reopen?" check has finished. The
// `?sample=1` auto-load waits for it so a restored deck wins over the sample.
const restoreChecked = ref(false);

// Demo AI provider: the host builds an OpenAI-compatible browser model from
// localStorage-supplied fields and passes it to the viewer's optional `ai`
// prop. The demo ships no key and no config UI, so this is normally undefined
// and the assistant simply stays off.
const aiConfig = useDemoAiConfig();

const themeKey = ref<string>(readStoredTheme());

function readStoredTheme(): string {
	try {
		return localStorage.getItem('pptx-demo-theme') ?? 'vermilionDark';
	} catch {
		return 'vermilionDark';
	}
}

const currentPreset = computed(() => themes[themeKey.value] ?? themes.vermilionDark);

const { t } = useI18n();

// ── Language ────────────────────────────────────────────────────────────────
// An explicit `?locale=` wins over the stored preference, so the docs
// landing page's live demo embed (docs/.vitepress/theme/landing/useLiveDemo.ts)
// can drive this pane to the site's active locale; with no param, the demo's
// own picker keeps working as before.
function readStoredLanguage(): LanguageCode {
	let stored: LanguageCode = 'en';
	try {
		const value = localStorage.getItem('pptx-demo-lang');
		stored = value && languageKeys.includes(value as LanguageCode) ? (value as LanguageCode) : 'en';
	} catch {
		stored = 'en';
	}
	return resolveLocaleParam(window.location.search, stored) as LanguageCode;
}

const languageKey = ref<LanguageCode>(readStoredLanguage());
watchEffect(() => {
	i18n.global.locale.value = languageKey.value;
});

// ── Apply theme vars to :root so the dropzone chrome tracks the theme ──────
let appliedVarKeys: string[] = [];
watchEffect(() => {
	const vars = themeToCssVars(currentPreset.value.theme);
	const root = document.documentElement;
	for (const key of appliedVarKeys) {
		root.style.removeProperty(key);
	}
	appliedVarKeys = Object.keys(vars);
	for (const key of appliedVarKeys) {
		root.style.setProperty(key, vars[key]);
	}
});
onBeforeUnmount(() => {
	const root = document.documentElement;
	for (const key of appliedVarKeys) {
		root.style.removeProperty(key);
	}
});

// ── URL-based collaboration / broadcast join ───────────────────────────────
const params = new URLSearchParams(window.location.search);
const urlRoom = ref(params.get('room'));
const urlBroadcast = ref(params.get('broadcast'));
const urlName = params.get('name');
// Serverless peer-to-peer joins carry `?transport=webrtc` (and optional
// `?signaling=a,b`); they need no `?server=` and no file server round-trip.
const urlTransport = params.get('transport');
const urlSignaling = params.get('signaling')?.split(',').filter(Boolean) ?? [];
const isWebrtcJoin = urlTransport === 'webrtc';
// For a webrtc join the server URL is intentionally blank (P2P); otherwise fall
// back to the configured relay / localhost default.
const urlServer = isWebrtcJoin ? '' : (params.get('server') ?? resolveDefaultServerUrl());
// The six opt-in Three.js scenes: on for a person, off under browser
// automation unless a `?<flag>=1` query param opts in; see
// demos/shared/rendering-3d-flags.ts for the rules and why.
const { smartArt3D, surfaceChart3D, barChart3D, lineChart3D, areaChart3D, pieChart3D } =
	currentDemo3DFlags();
// `?customization=<json>` (demos/shared/demo-customization.ts), for e2e.
const customization = currentDemoCustomization() as ViewerCustomization | undefined;
// `?showToolbar=0`, `?showThumbnails=0`, `?initialSlide=<n>`
// (demos/shared/demo-root-options.ts), for e2e.
const rootOptions = currentDemoRootOptions();
// `?sample=1` auto-loads the bundled sample deck (used by the docs landing
// page to embed a live, pre-populated viewer).
const urlSample = params.get('sample') === '1';

// Stable defaults for the Share dialog (demo-specific).
const autoRoomId = resolveAutoRoomId();
const autoName = resolveAutoName();
const defaultServerUrl = resolveDefaultServerUrl();

// ── Collaboration state ────────────────────────────────────────────────────
const collaborationConfig = shallowRef<CollaborationConfig | null>(null);

// A webrtc join is serverless, so it bypasses the trusted-host allowlist (there
// is no server to trust); a websocket join still requires a trusted server.
const joinAllowed = isWebrtcJoin || isTrustedServerUrl(urlServer);

// Auto-connect if room is in URL (collaboration mode).
watchEffect(() => {
	if (urlRoom.value && !collaborationConfig.value && joinAllowed) {
		collaborationConfig.value = {
			roomId: urlRoom.value,
			serverUrl: urlServer,
			userName: urlName ?? autoName,
			userColor: randomUserColor(),
			...(isWebrtcJoin
				? { transport: 'webrtc', signaling: urlSignaling.length ? urlSignaling : undefined }
				: {}),
		};
	} else if (urlRoom.value && !joinAllowed) {
		console.warn(
			`Ignoring ?room= auto-connect because ?server=${urlServer} is not in the trusted-host allowlist. Use the Share dialog to connect explicitly.`,
		);
	}
});

// Auto-connect if broadcast is in URL (viewer mode).
watchEffect(() => {
	if (urlBroadcast.value && !collaborationConfig.value && joinAllowed) {
		collaborationConfig.value = {
			roomId: urlBroadcast.value,
			serverUrl: urlServer,
			userName: urlName ?? autoName,
			userColor: randomUserColor(),
			role: 'viewer',
			...(isWebrtcJoin
				? { transport: 'webrtc', signaling: urlSignaling.length ? urlSignaling : undefined }
				: {}),
		};
	} else if (urlBroadcast.value && !joinAllowed) {
		console.warn(
			`Ignoring ?broadcast= auto-connect because ?server=${urlServer} is not in the trusted-host allowlist.`,
		);
	}
});

function handleStartCollaboration(config: CollaborationConfig): void {
	collaborationConfig.value = config;
	const webrtc = config.transport === 'webrtc';
	// Update URL with room/broadcast info for sharing.
	const url = new URL(window.location.href);
	// The viewer's broadcast session is the session owner (role 'owner'); a
	// regular collaboration session is role 'collaborator'.
	if (config.role === 'owner') {
		url.searchParams.set('broadcast', config.roomId);
	} else {
		url.searchParams.set('room', config.roomId);
	}
	// A serverless webrtc session shares `transport=webrtc` (no server URL);
	// a websocket session shares its server so joiners fetch the file from it.
	if (webrtc) {
		url.searchParams.set('transport', 'webrtc');
		url.searchParams.delete('server');
		if (config.signaling?.length) {
			url.searchParams.set('signaling', config.signaling.join(','));
		}
	} else {
		url.searchParams.set('server', config.serverUrl);
		url.searchParams.delete('transport');
		url.searchParams.delete('signaling');
	}
	window.history.replaceState({}, '', url.toString());
	// Upload PPTX content to the collab server so joiners can download it.
	// Restricted to trusted hosts to prevent crafted ?server= URLs from
	// exfiltrating user content. Serverless webrtc has no file server: joiners
	// receive the deck through Y.Doc late-joiner sync instead.
	const bytes = content.value;
	if (config.sessionIntent !== 'join' && !webrtc && bytes && isTrustedServerUrl(config.serverUrl)) {
		const httpUrl = config.serverUrl.replace(/^ws/u, 'http');
		void fetch(`${httpUrl}/file/${encodeURIComponent(config.roomId)}`, {
			method: 'POST',
			body: bytes as BodyInit,
		}).catch(() => {
			/* server may not support file storage, fall back silently */
		});
	}
}

function handleStopCollaboration(): void {
	collaborationConfig.value = null;
	urlRoom.value = null;
	urlBroadcast.value = null;
	const url = new URL(window.location.href);
	url.searchParams.delete('room');
	url.searchParams.delete('broadcast');
	url.searchParams.delete('server');
	url.searchParams.delete('transport');
	url.searchParams.delete('signaling');
	url.searchParams.delete('name');
	window.history.replaceState({}, '', url.toString());
}

// Auto-load the bundled sample deck when `?sample=1` is present, so a
// `?sample=1&room=…` host pane seeds the session with the sample. Waits for the
// restore check below: a tab that already has a deck of its own must not have
// the sample dropped back on top of it.
watchEffect((onCleanup) => {
	if (!restoreChecked.value || !urlSample || content.value) {
		return;
	}
	let cancelled = false;
	void fetch(`${import.meta.env.BASE_URL}sample-deck.pptx`)
		.then((res) => {
			if (!res.ok) {
				throw new Error(`HTTP ${res.status}`);
			}
			return res.arrayBuffer();
		})
		.then((buf) => {
			if (!cancelled && !content.value) {
				content.value = new Uint8Array(buf);
				fileName.value = 'sample-deck.pptx';
			}
			return undefined;
		})
		.catch(() => {
			// Sample not available: fall through to the regular dropzone.
		});
	onCleanup(() => {
		cancelled = true;
	});
});

// When joining via URL with a room/broadcast param, download PPTX from the
// collab server, but ONLY if the server is in the trusted-host allowlist.
const joinRoomId = computed(() => urlRoom.value ?? urlBroadcast.value);
watchEffect((onCleanup) => {
	const roomId = joinRoomId.value;
	if (!roomId || content.value) {
		return;
	}
	// Serverless webrtc joins have no file server: the deck arrives via Y.Doc
	// late-joiner sync, so skip the HTTP fetch entirely.
	if (isWebrtcJoin) {
		return;
	}
	if (!isTrustedServerUrl(urlServer)) {
		console.warn(
			`Refusing to fetch presentation from untrusted ?server=${urlServer}. Add the host to TRUSTED_COLLAB_HOSTS or use the Share dialog.`,
		);
		return;
	}
	let cancelled = false;
	const httpUrl = urlServer.replace(/^ws/u, 'http');
	void fetch(`${httpUrl}/file/${encodeURIComponent(roomId)}`)
		.then((res) => {
			if (!res.ok) {
				throw new Error('Not found');
			}
			return res.arrayBuffer();
		})
		.then((buf) => {
			if (cancelled) {
				return undefined;
			}
			content.value = new Uint8Array(buf);
			fileName.value = urlBroadcast.value ? 'Broadcast Session' : 'Collaboration Session';
			return undefined;
		})
		.catch(() => {
			// File not available on server, user will need to load manually.
		});
	onCleanup(() => {
		cancelled = true;
	});
});

// Fallback: try IndexedDB if server download didn't work (same-browser tabs).
// A `?sample=1` host seeds the session from the bundled deck instead, so never
// race it with the IndexedDB / blank-deck fallbacks.
watchEffect((onCleanup) => {
	if (!joinRoomId.value || content.value || urlSample) {
		return;
	}
	let cancelled = false;
	const timer = setTimeout(() => {
		void loadAudienceContent().then((bytes) => {
			if (cancelled || !bytes) {
				return undefined;
			}
			content.value = bytes;
			fileName.value = 'Collaboration Session';
			return undefined;
		});
	}, 1500);
	onCleanup(() => {
		cancelled = true;
		clearTimeout(timer);
	});
});

// Serverless webrtc joins have no file server and no IndexedDB seed: bootstrap
// a blank deck so the viewer mounts and starts collaborating. The owner's real
// slides then arrive through Y.Doc late-joiner sync and replace the blank deck.
watchEffect((onCleanup) => {
	if (!isWebrtcJoin || !joinRoomId.value || content.value || urlSample) {
		return;
	}
	let cancelled = false;
	void PptxHandler.createBlank({ title: 'Collaboration Session', initialSlideCount: 1 })
		.then(({ handler, data }) => handler.save(data.slides))
		.then((bytes) => {
			if (cancelled || content.value) {
				return undefined;
			}
			content.value = bytes;
			fileName.value = 'Collaboration Session';
			return undefined;
		});
	onCleanup(() => {
		cancelled = true;
	});
});

// When opened as an audience tab, load the PPTX content from IndexedDB.
onMounted(() => {
	if (!isAudienceTab()) {
		return;
	}
	void loadAudienceContent(parsePresentationSessionId(window.location.hash) ?? undefined).then(
		(bytes) => {
			if (!bytes) {
				return undefined;
			}
			content.value = bytes;
			fileName.value = 'Audience View';
			return undefined;
		},
	);
});

// ── Refresh survival ───────────────────────────────────────────────────────
// Remember the open deck for THIS tab, and reopen it on the next load. A
// refresh used to drop the presentation and land the user back on the file
// picker; now it comes back, with any autosaved edits (restoreSessionDeck
// prefers the newer of the two). An audience tab is fed by the presenter
// window, so it neither remembers nor restores.
watchEffect(() => {
	const bytes = content.value;
	if (!bytes || isAudienceTab()) {
		return;
	}
	void rememberSessionDeck(fileName.value, bytes);
});

onMounted(() => {
	// Collaboration / broadcast / audience tabs are fed by the session; they never
	// restore, and must not hold the sample fetch up either.
	if (joinRoomId.value || isAudienceTab()) {
		restoreChecked.value = true;
		return;
	}
	void restoreSessionDeck().then((deck) => {
		if (deck && !content.value) {
			// This tab has moved on from the bundled sample (the user opened a deck
			// of their own, possibly through the viewer's own File > Open), so a
			// leftover `?sample=1` must not re-seed it on the next refresh.
			dropSampleParam();
			content.value = deck.data;
			fileName.value = deck.fileName;
		}
		restoreChecked.value = true;
		return undefined;
	});
});

/**
 * Drop `?sample=1` from the address bar.
 *
 * The docs landing page embeds the demo with `?sample=1` so it opens
 * pre-populated. Once the user opens a deck of their own that param is stale:
 * left in place it would re-seed the bundled sample on the next refresh and
 * throw away what they were looking at.
 */
function dropSampleParam(): void {
	const url = new URL(window.location.href);
	if (!url.searchParams.has('sample')) {
		return;
	}
	url.searchParams.delete('sample');
	window.history.replaceState({}, '', url.toString());
}

// Update document title when in collaboration/broadcast mode.
watchEffect(() => {
	const config = collaborationConfig.value;
	if (config && content.value) {
		const prefix =
			config.role === 'owner'
				? '[Broadcasting]'
				: config.role === 'viewer'
					? '[Watching]'
					: '[Collab]';
		document.title = `${prefix} ${fileName.value} - PPTX Viewer`;
	}
});

// Reflect the loaded deck's name in the document title (all other demos do
// this). The collaboration effect above owns the title while a session is
// active; otherwise show "<fileName> - PPTX Viewer", falling back to the plain
// demo title before any deck is opened.
watchEffect(() => {
	if (collaborationConfig.value) {
		return;
	}
	document.title =
		content.value && fileName.value ? `${fileName.value} - PPTX Viewer` : 'pptx-vue-viewer demo';
});

function onDirtyChange(dirty: boolean): void {
	document.title = dirty ? `* ${fileName.value} - PPTX Viewer` : `${fileName.value} - PPTX Viewer`;
}

// ── Loading ────────────────────────────────────────────────────────────────
function loadFile(file: File): void {
	dropSampleParam();
	fileName.value = file.name;
	const reader = new FileReader();
	reader.onload = () => {
		content.value = new Uint8Array(reader.result as ArrayBuffer);
	};
	reader.readAsArrayBuffer(file);
}

async function newPresentation(): Promise<void> {
	dropSampleParam();
	const { handler, data } = await PptxHandler.createBlank({
		title: 'Untitled Presentation',
		initialSlideCount: 1,
	});
	content.value = await handler.save(data.slides);
	fileName.value = 'Untitled Presentation';
}

function onDrop(e: DragEvent): void {
	e.preventDefault();
	const file = e.dataTransfer?.files?.[0];
	if (file && isSupportedPresentationFile(file.name)) {
		loadFile(file);
	}
}

function onInputChange(e: Event): void {
	const file = (e.target as HTMLInputElement).files?.[0];
	if (file) {
		loadFile(file);
	}
}

const fileInput = ref<HTMLInputElement | null>(null);

/** Open the native picker from the explicit Browse control. */
function openFilePicker(): void {
	fileInput.value?.click();
}

/**
 * The dashed zone paints `cursor: pointer` over its whole area and the copy
 * says "click to browse", so the whole area has to open the picker, not just
 * the one text line that happens to be a <label>. Clicks that originate on a
 * button, on the label, or on the input itself are already handled by those
 * elements; re-opening from here would double-fire or loop.
 */
function onZoneClick(e: MouseEvent): void {
	if ((e.target as HTMLElement).closest('button, label[for="file-input"], #file-input')) {
		return;
	}
	openFilePicker();
}
</script>

<template>
	<main v-if="content" class="demo-shell">
		<PowerPointViewer
			ref="viewerRef"
			:content="content"
			:file-name="fileName"
			autosave
			:autosave-interval-ms="2000"
			can-edit
			:smartArt3D="smartArt3D"
			:surfaceChart3D="surfaceChart3D"
			:barChart3D="barChart3D"
			:lineChart3D="lineChart3D"
			:areaChart3D="areaChart3D"
			:pieChart3D="pieChart3D"
			:customization="customization"
			:show-toolbar="rootOptions.showToolbar"
			:show-thumbnails="rootOptions.showThumbnails"
			:initial-slide="rootOptions.initialSlide"
			:ai="aiConfig"
			:author-name="collaborationConfig?.userName ?? autoName"
			:collaboration="collaborationConfig ?? undefined"
			:share-defaults="{ roomId: autoRoomId, userName: autoName, serverUrl: defaultServerUrl }"
			@start-collaboration="handleStartCollaboration"
			@stop-collaboration="handleStopCollaboration"
			@dirty-change="onDirtyChange"
		/>
	</main>

	<main v-else class="demo-stage">
		<h1 class="sr-only">PPTX Viewer</h1>
		<div
			class="demo-dropzone"
			role="group"
			data-testid="dropzone"
			:aria-label="t('demo.dropzone.uploadAriaLabel')"
			@click="onZoneClick"
			@drop="onDrop"
			@dragover.prevent
		>
			<template v-if="urlBroadcast">
				<p class="demo-join">
					{{ t('demo.dropzone.joiningBroadcast') }} <code>{{ urlBroadcast }}</code>
				</p>
				<p class="demo-hint">{{ t('demo.dropzone.loadingBroadcast') }}</p>
			</template>
			<template v-else-if="urlRoom">
				<p class="demo-join">
					{{ t('demo.dropzone.joiningSession') }} <code>{{ urlRoom }}</code>
				</p>
				<label class="demo-hint" for="file-input">{{ t('demo.dropzone.hintCollab') }}</label>
			</template>
			<template v-else>
				<label class="demo-hint" for="file-input">{{ t('demo.dropzone.hint') }}</label>
			</template>
			<p class="demo-sub">{{ t('demo.dropzone.processed') }}</p>
			<div class="demo-actions">
				<button
					type="button"
					class="demo-browse"
					data-testid="browse-files"
					@click.stop="openFilePicker"
				>
					{{ t('demo.dropzone.browse') }}
				</button>
				<button type="button" @click.stop="newPresentation">
					{{ t('demo.dropzone.newPresentation') }}
				</button>
			</div>
			<input
				id="file-input"
				ref="fileInput"
				type="file"
				:accept="PPTX_OPEN_ACCEPT"
				:aria-label="t('demo.dropzone.uploadAriaLabel')"
				class="sr-only"
				@change="onInputChange"
			/>
		</div>
	</main>
</template>

<style>
body {
	font-family:
		system-ui,
		-apple-system,
		'Segoe UI',
		Roboto,
		sans-serif;
	/* Never let demo chrome overflow horizontally; on mobile a wider-than-viewport
	   page expands the layout viewport and mis-anchors the viewer's fixed bottom bar. */
	overflow-x: hidden;
}

.demo-shell {
	height: 100dvh;
	width: 100vw;
}
</style>
