// viewers/pptx/packages/angular/src/viewer/equation-editor-dialog.component.ts
/**
 * equation-editor-dialog.component.ts: Insert / edit a LaTeX-based equation.
 *
 * Selector: `pptx-equation-editor-dialog`
 *
 * Angular port of the React `EquationEditorDialog`. A modal for authoring an
 * equation as LaTeX, with a live MathML preview and a gallery of common
 * templates. Composes {@link ModalDialogComponent} and
 * {@link EquationTemplateGalleryComponent}. Internally converts LaTeX to OMML
 * (Office Math Markup Language) for the emitted value and to MathML for the
 * on-screen preview.
 *
 * Behaviour:
 *  - Host owns the `open` flag and supplies `existingOmml` when editing.
 *  - Seeds the LaTeX textarea from `existingOmml` (via `convertOmmlToLatex`)
 *    each time the dialog opens; empty for a fresh insert.
 *  - Emits `insert` with the recomputed OMML object, then `close`.
 *  - Emits `close` on Cancel, the `x` button, backdrop click, and Escape.
 *
 * Pure conversion logic lives in the vendored shared render modules
 * (`convertLatexToOmml`, `convertOmmlToLatex`, `ommlToMathml`) and in
 * {@link ./equation-editor-helpers}.
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import type { SafeHtml } from '@angular/platform-browser';
import { TranslatePipe } from '@ngx-translate/core';

import { convertLatexToOmml, convertOmmlToLatex } from 'ooxml-ui/pptx';
import type { DialogFooterActionSpec } from './dialog-footer.component';
import { DialogFooterComponent } from './dialog-footer.component';
import { latexToMathml } from './equation-editor-helpers';
import { EquationTemplateGalleryComponent } from './equation-template-gallery.component';
import { ModalDialogComponent } from './modal-dialog.component';

@Component({
	selector: 'pptx-equation-editor-dialog',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [
		DialogFooterComponent,
		ModalDialogComponent,
		EquationTemplateGalleryComponent,
		TranslatePipe,
	],
	template: `
		<pptx-modal-dialog [open]="open()" [title]="dialogTitle() | translate" (close)="close.emit()">
			<div class="pptx-ng-eq">
				<!-- Live preview -->
				<div class="pptx-ng-eq-preview">
					@if (hasContent()) {
						<div class="pptx-ng-eq-math" [innerHTML]="previewMathml()"></div>
					} @else {
						<span class="pptx-ng-eq-placeholder">{{
							'pptx.equation.previewPlaceholder' | translate
						}}</span>
					}
				</div>

				<!-- LaTeX input -->
				<div class="pptx-ng-eq-field">
					<label class="pptx-ng-eq-label" for="pptx-ng-eq-latex">{{
						'pptx.equation.latexInput' | translate
					}}</label>
					<textarea
						id="pptx-ng-eq-latex"
						class="pptx-ng-eq-textarea"
						spellcheck="false"
						placeholder="\\frac{a}{b} + \\sqrt{c}"
						[value]="latex()"
						(input)="latex.set(asValue($event))"
						(keydown)="onKeyDown($event)"
					></textarea>
					<p class="pptx-ng-eq-hint">{{ 'pptx.equation.latexHint' | translate }}</p>
				</div>

				<pptx-equation-template-gallery [activeLatex]="latex()" (select)="latex.set($event)" />
			</div>

			<div footer>
				<pptx-dialog-footer [actions]="footerActions()" (action)="onFooterAction($event)" />
			</div>
		</pptx-modal-dialog>
	`,
	styles: [
		`
			.pptx-ng-eq {
				display: flex;
				flex-direction: column;
				gap: 1rem;
				width: min(88vw, 600px);
			}
			.pptx-ng-eq-preview {
				display: flex;
				align-items: center;
				justify-content: center;
				min-height: 80px;
				padding: 1rem;
				border: 1px solid var(--pptx-border, #374151);
				border-radius: 0.5rem;
				background: var(--pptx-muted, #111827);
			}
			.pptx-ng-eq-math {
				font-size: 1.5rem;
				color: var(--pptx-foreground, #f3f4f6);
				font-family: 'Cambria Math', 'STIX Two Math', serif;
			}
			.pptx-ng-eq-placeholder {
				font-size: 0.8125rem;
				font-style: italic;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
			.pptx-ng-eq-field {
				display: flex;
				flex-direction: column;
				gap: 0.375rem;
			}
			.pptx-ng-eq-label {
				font-size: 0.75rem;
				font-weight: 500;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
			.pptx-ng-eq-textarea {
				width: 100%;
				height: 6rem;
				padding: 0.5rem 0.75rem;
				border: 1px solid var(--pptx-border, #374151);
				border-radius: 0.5rem;
				background: var(--pptx-muted, #111827);
				color: var(--pptx-foreground, #f3f4f6);
				font-size: 0.8125rem;
				font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
				resize: none;
			}
			.pptx-ng-eq-textarea:focus {
				outline: none;
				border-color: var(--pptx-primary, #6366f1);
			}
			.pptx-ng-eq-hint {
				margin: 0;
				font-size: 0.6875rem;
				color: var(--pptx-muted-foreground, #9ca3af);
			}
		`,
	],
})
export class EquationEditorDialogComponent {
	/** Footer actions for the shared `pptx-ui-dialog-footer`. */
	protected readonly footerActions = computed<DialogFooterActionSpec[]>(() => [
		{ id: 'cancel', labelKey: 'pptx.equation.cancel' },
		{
			id: 'insert',
			labelKey: this.isEditing() ? 'pptx.equation.update' : 'pptx.equation.insert',
			variant: 'primary' as const,
			disabled: !this.hasContent(),
		},
	]);

	protected onFooterAction(id: string): void {
		if (id === 'insert') {
			this.onInsert();
		} else {
			this.close.emit();
		}
	}

	/** Whether the dialog is visible. */
	readonly open = input<boolean>(false);

	/** When editing an existing equation, its OMML tree (null for a fresh insert). */
	readonly existingOmml = input<Record<string, unknown> | null>(null);

	/** Fired with the OMML object to insert / update on the slide. */
	readonly insert = output<Record<string, unknown>>();

	/** Fired when the dialog is dismissed. */
	readonly close = output<void>();

	private readonly sanitizer = inject(DomSanitizer);

	/** Current LaTeX source in the textarea. */
	readonly latex = signal('');

	/** True when editing an existing equation (drives the title / button label). */
	readonly isEditing = computed(() => this.existingOmml() !== null);

	/** Header title: edit vs insert. */
	readonly dialogTitle = computed(() =>
		this.isEditing() ? 'pptx.equation.editTitle' : 'pptx.equation.insertTitle',
	);

	/** Live OMML compiled from the current LaTeX ({} on failure / empty input). */
	private readonly omml = computed<Record<string, unknown>>(() => {
		const value = this.latex();
		if (!value.trim()) {
			return {};
		}
		try {
			return convertLatexToOmml(value);
		} catch {
			return {};
		}
	});

	/** Whether there is a renderable equation (drives preview + insert enabling). */
	readonly hasContent = computed(
		() => this.latex().trim().length > 0 && Object.keys(this.omml()).length > 0,
	);

	/** Sanitized MathML preview for the current LaTeX. */
	readonly previewMathml = computed<SafeHtml>(() =>
		this.sanitizer.bypassSecurityTrustHtml(latexToMathml(this.latex())),
	);

	constructor() {
		// Seed the LaTeX field from the existing OMML each time the dialog opens.
		effect(() => {
			if (this.open()) {
				const existing = this.existingOmml();
				this.latex.set(existing ? convertOmmlToLatex(existing) : '');
			}
		});
	}

	asValue(event: Event): string {
		return (event.target as HTMLTextAreaElement).value;
	}

	onKeyDown(event: KeyboardEvent): void {
		if (event.key === 'Enter' && (event.metaKey || event.ctrlKey)) {
			event.preventDefault();
			this.onInsert();
		}
	}

	onInsert(): void {
		if (!this.hasContent()) {
			return;
		}
		this.insert.emit(this.omml());
		this.close.emit();
	}
}

// viewers/pptx/packages/svelte/src/viewer/components/ribbon/insert/EquationEditorDialog.svelte
<script lang="ts">
	/**
	 * EquationEditorDialog: modal LaTeX equation editor mirroring React's
	 * `EquationEditorDialog.tsx`: a live MathML preview, a LaTeX textarea, and
	 * the shared template gallery (`EQUATION_TEMPLATES`), with Ctrl+Enter to
	 * insert and Escape/backdrop to dismiss. Converts LaTeX to OMML via the
	 * shared `latex-to-omml` module on Insert; every rendered MathML string
	 * goes through `mathml-sanitize` before the `{@html ...}` binding.
	 *
	 * Insert mode adds a new equation shape (`buildEquationInsertElement`);
	 * edit mode (an `editor.equationOps.editingId` is set) seeds the textarea
	 * from the existing OMML and applies the replacement in place.
	 */
	import DialogFooter from '../../DialogFooter.svelte';
	import { compileLatexEquation, convertOmmlToLatex } from 'ooxml-ui/pptx';
	import type { CanvasSize } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../../i18n/context';
	import type { EditorState } from '../../../editor/editor-state.svelte';
	import { buildEquationInsertElement } from '../../../editor';
	import EquationTemplateGallery from './EquationTemplateGallery.svelte';

	const {
		editor,
		canvasSize,
		open,
		onclose,
	}: {
		editor: EditorState;
		canvasSize: CanvasSize;
		open: boolean;
		onclose: () => void;
	} = $props();
	const t = useTranslator();

	/** Sample placeholder shown in the empty LaTeX textarea. */
	const LATEX_PLACEHOLDER = '\\frac{a}{b} + \\sqrt{c}';

	let latex = $state('');
	let wasOpen = false;
	// eslint-disable-next-line prefer-const
	let textareaEl = $state<HTMLTextAreaElement | null>(null);

	const isEditing = $derived(Boolean(editor.equationOps.editingId));

	/** Live LaTeX -> OMML -> MathML for the preview + the insert payload. */
	const compiled = $derived(compileLatexEquation(latex));

	const hasContent = $derived(latex.trim().length > 0 && Object.keys(compiled.omml).length > 0);

	// Re-seed the textarea on every open transition: from the existing OMML in
	// edit mode, empty for a fresh insert (so a cancelled session never leaks
	// stale LaTeX into the next one).
	$effect(() => {
		if (open && !wasOpen) {
			const existing = editor.equationOps.omml;
			latex = existing ? convertOmmlToLatex(existing) : '';
			textareaEl?.focus();
		}
		wasOpen = open;
	});

	function insert(): void {
		if (!hasContent) {
			return;
		}
		if (editor.equationOps.editingId) {
			editor.equationOps.apply(compiled.omml);
		} else {
			editor.insertElement(buildEquationInsertElement(compiled.omml, canvasSize));
		}
		latex = '';
		onclose();
	}

	function onKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Escape') {
			onclose();
		} else if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) {
			event.preventDefault();
			insert();
		}
	}

	function onBackdropClick(event: MouseEvent): void {
		if (event.target === event.currentTarget) {
			onclose();
		}
	}
</script>

{#if open}
	<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
	<div class="backdrop" onclick={onBackdropClick} onkeydown={onKeydown} role="presentation">
		<!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
		<section
			role="dialog"
			tabindex="-1"
			aria-modal="true"
			aria-label={t(isEditing ? 'pptx.equation.editTitle' : 'pptx.equation.insertTitle')}
		>
			<header>
				<h2>{t(isEditing ? 'pptx.equation.editTitle' : 'pptx.equation.insertTitle')}</h2>
				<button type="button" class="close" aria-label={t('pptx.settings.close')} onclick={onclose}>×</button>
			</header>

			<div class="preview" class:empty={!hasContent}>
				{#if hasContent}
					<!-- eslint-disable-next-line svelte/no-at-html-tags -->
					<span class="math">{@html compiled.mathml}</span>
				{:else}
					{t('pptx.equation.previewPlaceholder')}
				{/if}
			</div>

			<label class="field">
				<span class="label">{t('pptx.equation.latexInput')}</span>
				<textarea
					bind:this={textareaEl}
					rows="3"
					placeholder={LATEX_PLACEHOLDER}
					spellcheck="false"
					disabled={!editor.editable}
					bind:value={latex}
				></textarea>
				<span class="hint">{t('pptx.equation.latexHint')}</span>
			</label>

			<EquationTemplateGallery activeLatex={latex} onselect={(next) => (latex = next)} />

			<footer><DialogFooter actions={[{ id: 'cancel', label: t('pptx.equation.cancel') }, { id: 'insert', label: t(isEditing ? 'pptx.equation.update' : 'pptx.equation.insert'), variant: 'primary', disabled: !editor.editable || !hasContent }]} onaction={(id) => (id === 'insert' ? insert() : onclose())} /></footer>
		</section>
	</div>
{/if}

<style>
	.backdrop {
		position: fixed;
		inset: 0;
		z-index: 1200;
		display: grid;
		place-items: center;
		background: #0009;
	}

	section {
		display: flex;
		flex-direction: column;
		gap: 12px;
		width: min(600px, calc(100vw - 32px));
		max-height: 85vh;
		overflow-y: auto;
		padding: 18px;
		border: 1px solid var(--pptx-border, #3f3f52);
		border-radius: 11px;
		background: var(--pptx-card, #1e1e2e);
		color: var(--pptx-foreground, #f3f4f6);
	}

	header {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	h2 {
		margin: 0;
		font-size: 14px;
	}

	.close {
		border: none;
		background: none;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 16px;
		cursor: pointer;
		padding: 2px 6px;
		border-radius: var(--pptx-radius, 6px);
	}

	.close:hover {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-accent-foreground, #f8fafc);
	}

	.preview {
		display: flex;
		align-items: center;
		justify-content: center;
		min-height: 72px;
		padding: 12px;
		border: 1px solid var(--pptx-border, #3f3f52);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #2a2a3d);
		font-size: 22px;
	}

	.preview.empty {
		font-size: 12px;
		font-style: italic;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.math {
		font-family: 'Cambria Math', 'STIX Two Math', serif;
	}

	.field {
		display: flex;
		flex-direction: column;
		gap: 5px;
	}

	.label {
		font-size: 11px;
		font-weight: 500;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	textarea {
		width: 100%;
		padding: 6px 8px;
		border: 1px solid var(--pptx-border, #3f3f52);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b);
		color: inherit;
		font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
		font-size: 12px;
		resize: vertical;
	}

	textarea:disabled {
		opacity: 0.4;
	}

	.hint {
		font-size: 10px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	footer {
		display: flex;
		justify-content: flex-end;
		gap: 7px;
	}
	

	</style>
