// viewers/pptx/packages/svelte/src/viewer/components/AutosaveRecoveryDialog.svelte
<script lang="ts">
	/**
	 * AutosaveRecoveryDialog: "Recover unsaved changes?" for a deck that has a
	 * crash-recovery snapshot in the shared IndexedDB store.
	 *
	 * Purely presentational, and deliberately dumb: every decision (whether a
	 * snapshot is worth offering, how old it is, which strings describe it) is
	 * already made by `pptx-viewer-shared`'s `autosaveRecoveryPrompt` and arrives
	 * here as the descriptor below, so all five bindings show the same dialog.
	 */
	import History from '@lucide/svelte/icons/history';
	import type { AutosaveRecoveryPrompt } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import DialogFooter from './DialogFooter.svelte';

	const { prompt, discarding = false, onrestore, ondiscard }: { prompt: AutosaveRecoveryPrompt; discarding?: boolean; onrestore: () => void; ondiscard: () => void } = $props();
	const t = useTranslator();
	const title = $derived(t(prompt.titleKey));
	const savedLabel = $derived(t('pptx.autosave.recovery.savedLabel', { when: t(prompt.ageKey, prompt.ageParams) }));
</script>
<div class="backdrop" data-pptx-autosave-recovery="true"><!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role --><section role="dialog" tabindex="-1" aria-modal="true" aria-label={title} aria-busy={discarding}><header><b><History size={20} aria-hidden="true" /></b><div><h2>{title}</h2><p>{t(prompt.messageKey, prompt.messageParams)}</p><small>{savedLabel}</small></div></header><footer><DialogFooter actions={[{ id: 'discard', label: t(prompt.discardKey), icon: 'trash', disabled: discarding }, { id: 'restore', label: t(prompt.restoreKey), variant: 'primary', icon: 'restore', disabled: discarding }]} onaction={(id) => (id === 'restore' ? onrestore() : ondiscard())} /></footer></section></div>
<style>
	.backdrop{position:fixed;inset:0;z-index:1250;display:grid;place-items:center;padding:16px;background:#0009}section{width:min(420px,100%);max-height:calc(100dvh - 32px);overflow-y:auto;padding:22px;border:1px solid var(--pptx-border,#3f3f52);border-radius:12px;background:var(--pptx-card,#1e1e2e);box-shadow:0 24px 80px #0009}header{display:flex;gap:12px}header>b{display:grid;width:40px;height:40px;flex:0 0 40px;place-items:center;border-radius:50%;background:color-mix(in srgb,var(--pptx-primary,#c43b32) 18%,transparent);color:var(--pptx-primary,#c43b32)}header>div{min-width:0}h2,p{margin:0}h2{font-size:16px}p{margin-top:4px;overflow-wrap:anywhere;color:var(--pptx-muted-foreground,#94a3b8);font-size:13px}small{display:block;margin-top:6px;color:var(--pptx-muted-foreground,#94a3b8);font-size:12px}footer{margin-top:24px}
</style>

// viewers/pptx/packages/react/src/viewer/components/AutosaveRecoveryDialog.tsx
/**
 * AutosaveRecoveryDialog: "we found unsaved changes for this deck, want them?"
 *
 * Pure presentation over the shared `AutosaveRecoveryPrompt` descriptor, so the
 * five bindings offer the same recovery with the same words. Every string is a
 * key chosen by `pptx-viewer-shared`; this component picks none of them.
 */
import type { AutosaveRecoveryPrompt } from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { LuHistory } from 'react-icons/lu';

import { DialogFooter } from './DialogFooter';

export interface AutosaveRecoveryDialogProps {
	/** The descriptor to render, or null to render nothing. */
	prompt: AutosaveRecoveryPrompt | null;
	onRestore: () => void;
	onDiscard: () => void;
	busy?: boolean;
}

export function AutosaveRecoveryDialog({
	prompt,
	onRestore,
	onDiscard,
	busy = false,
}: AutosaveRecoveryDialogProps): React.ReactElement | null {
	const { t } = useTranslation();

	if (!prompt) {
		return null;
	}

	const title = t(prompt.titleKey);
	const when = t(prompt.ageKey, prompt.ageParams);

	return (
		<div
			style={{ zIndex: 1200 }}
			className='fixed inset-0 flex items-center justify-center bg-black/50 p-4'
			data-pptx-autosave-recovery='true'
		>
			<div
				role='dialog'
				aria-modal='true'
				aria-label={title}
				aria-busy={busy}
				className='bg-background border border-border rounded-lg shadow-xl w-[440px] max-w-full max-h-[calc(100dvh-2rem)] overflow-y-auto p-6'
			>
				<div className='flex items-center gap-3 mb-3'>
					<div className='flex items-center justify-center w-10 h-10 rounded-full bg-primary/10'>
						<LuHistory className='w-5 h-5 text-primary' />
					</div>
					<h2 className='text-base font-semibold text-foreground'>{title}</h2>
				</div>
				<p className='text-sm text-muted-foreground [overflow-wrap:anywhere]'>
					{t(prompt.messageKey, prompt.messageParams)}
				</p>
				<p className='text-xs text-muted-foreground mt-2'>
					{t('pptx.autosave.recovery.savedLabel', { when })}
				</p>
				<div className='mt-6'>
					<DialogFooter
						actions={[
							{ id: 'discard', label: t(prompt.discardKey), icon: 'trash', disabled: busy },
							{
								id: 'restore',
								label: t(prompt.restoreKey),
								variant: 'primary',
								icon: 'restore',
								disabled: busy,
							},
						]}
						onAction={(id) => (id === 'restore' ? onRestore() : onDiscard())}
					/>
				</div>
			</div>
		</div>
	);
}
