// viewers/pptx/packages/angular/src/viewer/mobile-presenter-view.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	computed,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxElement, PptxSlide } from 'pptx-viewer-core';

import type { AuthoredSlideRange, CanvasSize, ShowOrderCustomShow } from 'ooxml-ui/pptx';
import {
	formatMobileElapsed,
	mobileElapsedSince,
	mobileNextThumbSize,
	mobileSlideCounter,
	presenterNextDisabled,
	presenterPrevDisabled,
	visibleTemplateElements as filterVisibleTemplateElements,
} from 'ooxml-ui/pptx';
import { currentSlideAt, nextSlideAfter, resolvePresenterNotes } from './presenter-view-helpers';
import { SlideCanvasComponent } from './slide-canvas.component';

/** Clock tick interval (ms) for the elapsed-timer display. */
const CLOCK_TICK_MS = 1000;

/**
 * MobilePresenterViewComponent: single-column phone layout for presenter /
 * speaker view, shown instead of the desktop split-screen
 * `PresenterViewComponent` when the speaker enters presenter mode on a small
 * screen (the orchestrator branches on `IsMobileService.isMobile()`). The
 * desktop layout is left unchanged; only the layout differs.
 *
 * Top to bottom: header (elapsed timer + slide counter + exit), the current
 * slide large, a small next-slide thumbnail, scrollable speaker notes, and
 * prev/next controls; all offset by the device safe-area insets. Pure geometry
 * / labels / time formatting come from `pptx-viewer-shared` (`presenter-mobile`,
 * re-exported via `../internal/shared`). Slide rendering reuses
 * `pptx-slide-canvas` like the desktop presenter.
 *
 * Selector: `pptx-mobile-presenter-view`. Keyboard navigation is owned by the
 * orchestrator; this component registers no document keydown listener.
 */
@Component({
	selector: 'pptx-mobile-presenter-view',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, SlideCanvasComponent, TranslatePipe],
	styleUrl: './mobile-presenter-view.component.css',
	templateUrl: './mobile-presenter-view.component.html',
})
export class MobilePresenterViewComponent {
	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	readonly slides = input.required<PptxSlide[]>();
	readonly currentSlideIndex = input.required<number>();
	/**
	 * The running custom show, or null for the whole deck. The "next slide"
	 * preview MUST honour it: while a show is playing, the slide the next
	 * forward press lands on is the show's next member, not `index + 1`.
	 */
	readonly activeCustomShow = input<ShowOrderCustomShow | null>(null);
	/**
	 * The deck's authored `p:showPr/p:sldRg` slide-range restriction, or null
	 * for the whole deck. The next-slide preview must honour it the same way it
	 * honours {@link activeCustomShow}.
	 */
	readonly authoredRange = input<AuthoredSlideRange | null>(null);
	readonly canvasSize = input.required<CanvasSize>();
	readonly templateElements = input<readonly PptxElement[]>([]);
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	readonly presentationStartTime = input<number | null>(null);

	// ------------------------------------------------------------------
	// Outputs
	// ------------------------------------------------------------------

	readonly movePresentationSlide = output<1 | -1>();
	readonly exit = output<void>();

	// ------------------------------------------------------------------
	// Internal state
	// ------------------------------------------------------------------

	/** Live wall-clock (epoch ms), advanced once per second. */
	private readonly now = signal(Date.now());

	constructor() {
		if (typeof setInterval !== 'undefined') {
			const handle = setInterval(() => this.now.set(Date.now()), CLOCK_TICK_MS);
			inject(DestroyRef).onDestroy(() => clearInterval(handle));
		}
	}

	// ------------------------------------------------------------------
	// Derived signals
	// ------------------------------------------------------------------

	protected readonly currentSlide = computed<PptxSlide | undefined>(() =>
		currentSlideAt(this.slides(), this.currentSlideIndex()),
	);

	protected readonly nextSlide = computed<PptxSlide | undefined>(() =>
		nextSlideAfter(
			this.slides(),
			this.currentSlideIndex(),
			this.activeCustomShow(),
			this.authoredRange(),
		),
	);

	protected readonly currentPreviewSlide = computed<PptxSlide | undefined>(() =>
		this.withTemplate(this.currentSlide()),
	);

	protected readonly nextPreviewSlide = computed<PptxSlide | undefined>(() =>
		this.withTemplate(this.nextSlide()),
	);

	protected readonly notes = computed(() => resolvePresenterNotes(this.currentSlide()));

	protected readonly elapsedLabel = computed<string>(() =>
		formatMobileElapsed(mobileElapsedSince(this.presentationStartTime(), this.now())),
	);

	protected readonly counterLabel = computed<string>(() =>
		mobileSlideCounter(this.currentSlideIndex(), this.slides().length),
	);

	// The desktop console's rules, not a phone-sized copy of them: Next stays live
	// on the last slide so the presenter can reach the end-of-show screen and
	// finish, exactly as the split-screen console does.
	protected readonly prevDisabled = computed<boolean>(() =>
		presenterPrevDisabled(this.currentSlideIndex()),
	);

	protected readonly nextDisabled = computed<boolean>(() => presenterNextDisabled());

	/** Next-slide thumbnail box (CSS px); width drives the slide-canvas autoFit. */
	protected readonly thumbStyle = computed(() => {
		const size = this.canvasSize();
		const thumb = mobileNextThumbSize(size.width, size.height);
		return { width: `${thumb.width}px`, height: `${thumb.height}px` };
	});

	// ------------------------------------------------------------------
	// Helpers
	// ------------------------------------------------------------------

	private withTemplate(slide: PptxSlide | undefined): PptxSlide | undefined {
		if (!slide) {
			return undefined;
		}
		const template = filterVisibleTemplateElements(slide, this.templateElements());
		if (template.length === 0) {
			return slide;
		}
		return { ...slide, elements: [...template, ...slide.elements] };
	}
}

// viewers/pptx/packages/react/src/viewer/components/MobilePresenterView.tsx
import type { PptxElement, PptxSlide } from 'pptx-viewer-core';
import type { AuthoredSlideRange, ShowOrderCustomShow } from 'ooxml-ui/pptx';
import {
	formatMobileElapsed,
	mobileElapsedSince,
	mobileSlideCounter,
	nextPresentedSlide,
	presenterNextDisabled,
	presenterPrevDisabled,
} from 'ooxml-ui/pptx';
/**
 * MobilePresenterView: single-column phone layout for presenter/speaker view.
 *
 * Shown instead of the desktop split-screen `PresenterView` when the speaker
 * enters presenter mode on a small screen (see `ViewerPresentationLayer`).
 * The desktop layout is left byte-for-byte unchanged; only the layout differs.
 *
 * Layout, top to bottom: the current slide large, a header row (elapsed timer
 * + slide counter + exit), a small "next" thumbnail, the scrollable speaker
 * notes, and prev/next controls; everything is offset by the device safe-area
 * insets. All pure geometry / labels / time formatting come from
 * `pptx-viewer-shared` (`presenter-mobile`).
 *
 * Keyboard navigation is owned by the parent `usePresentationKeyboard` hook;
 * this component registers no key listener (matching `PresenterView`).
 */
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuChevronLeft, LuChevronRight, LuX } from 'react-icons/lu';

import type { CanvasSize } from '../types';
import { renderNotesSegments } from './presenter-view-utils';
import { ScaledSlidePreview } from './ScaledSlidePreview';

// ---------------------------------------------------------------------------
// Props (a subset of PresenterViewProps so the two are wiring-compatible)
// ---------------------------------------------------------------------------

export interface MobilePresenterViewProps {
	slides: PptxSlide[];
	currentSlideIndex: number;
	canvasSize: CanvasSize;
	templateElements: PptxElement[];
	/** The running custom show, so the next-slide preview follows its order. */
	activeCustomShow?: ShowOrderCustomShow | null;
	/** The deck's authored `p:sldRg` range, so the preview never shows a slide outside it. */
	authoredRange?: AuthoredSlideRange | undefined;
	presentationStartTime: number | null;
	onMovePresentationSlide: (direction: 1 | -1) => void;
	onExit: () => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function MobilePresenterView({
	slides,
	currentSlideIndex,
	canvasSize,
	templateElements,
	activeCustomShow,
	authoredRange,
	presentationStartTime,
	onMovePresentationSlide,
	onExit,
}: MobilePresenterViewProps): React.ReactElement {
	const { t } = useTranslation();

	// -- Elapsed timer (1 Hz tick) -------------------------------------------
	const [now, setNow] = useState(Date.now());
	useEffect(() => {
		const interval = window.setInterval(() => setNow(Date.now()), 1000);
		return () => window.clearInterval(interval);
	}, []);
	const elapsed = mobileElapsedSince(presentationStartTime, now);

	// -- Slide data ----------------------------------------------------------
	const currentSlide = slides[currentSlideIndex];
	// The preview must be the slide the next advance really lands on, so it runs
	// the shared show-order rule and skips slides the author hid.
	const nextSlide = nextPresentedSlide(slides, currentSlideIndex, activeCustomShow, authoredRange);

	if (!currentSlide) {
		return (
			<div className='absolute inset-0 z-50 flex items-center justify-center bg-card text-muted-foreground'>
				{t('pptx.presenter.noSlides')}
			</div>
		);
	}

	const notesText = currentSlide.notes ?? '';
	const notesSegments = currentSlide.notesSegments;
	const hasRichNotes = notesSegments && notesSegments.length > 0;

	// The desktop console's rules, not a phone-sized copy of them: Next stays live
	// on the last slide so the presenter can reach the end-of-show screen and
	// finish, exactly as the split-screen console does.
	const prevDisabled = presenterPrevDisabled(currentSlideIndex);
	const nextDisabled = presenterNextDisabled();

	const insetStyle: React.CSSProperties = {
		paddingTop: 'env(safe-area-inset-top, 0px)',
		paddingBottom: 'env(safe-area-inset-bottom, 0px)',
		paddingLeft: 'env(safe-area-inset-left, 0px)',
		paddingRight: 'env(safe-area-inset-right, 0px)',
	};

	return (
		<div className='absolute inset-0 z-50 flex flex-col bg-card text-foreground' style={insetStyle}>
			{/* Header: elapsed timer + slide counter + exit */}
			<div className='flex items-center justify-between gap-2 px-4 py-2 border-b border-border/60'>
				<div className='flex flex-col'>
					<span className='text-[10px] text-muted-foreground uppercase tracking-wider'>
						{t('pptx.presenter.elapsed')}
					</span>
					<span className='text-lg font-mono tabular-nums text-primary'>
						{formatMobileElapsed(elapsed)}
					</span>
				</div>
				<span className='text-sm font-mono tabular-nums text-foreground'>
					{mobileSlideCounter(currentSlideIndex, slides.length)}
				</span>
				<button
					type='button'
					onClick={onExit}
					className='flex items-center justify-center w-11 h-11 min-w-11 min-h-11 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors'
					title={t('pptx.presenter.endPresentation')}
					aria-label={t('pptx.presenter.endPresentation')}
				>
					<LuX className='w-5 h-5' />
				</button>
			</div>

			{/* Current slide (large) */}
			<div className='flex items-center justify-center bg-black px-3 py-3'>
				<div className='w-full max-w-[640px]'>
					<ScaledSlidePreview
						slide={currentSlide}
						templateElements={templateElements}
						canvasSize={canvasSize}
					/>
				</div>
			</div>

			{/* Next thumbnail */}
			<div className='flex items-center gap-3 px-4 py-2 border-b border-border/60'>
				<span className='text-[10px] text-muted-foreground uppercase tracking-wider whitespace-nowrap'>
					{t('pptx.presenter.nextSlidePreview')}
				</span>
				<div className='w-[132px] flex-shrink-0'>
					{nextSlide ? (
						<ScaledSlidePreview
							slide={nextSlide}
							templateElements={templateElements}
							canvasSize={canvasSize}
						/>
					) : (
						<div className='flex items-center justify-center h-12 rounded border border-border/30 bg-muted/40 text-[10px] text-muted-foreground italic'>
							{t('pptx.presenter.endOfPresentation')}
						</div>
					)}
				</div>
			</div>

			{/* Speaker notes (scrollable) */}
			<div className='flex-1 flex flex-col min-h-0 px-4 py-2'>
				<div className='text-[10px] text-muted-foreground uppercase tracking-wider mb-1'>
					{t('pptx.presenter.speakerNotes')}
				</div>
				<div className='flex-1 overflow-y-auto rounded border border-border/30 bg-muted/40 px-3 py-2 text-foreground whitespace-pre-wrap leading-relaxed text-[15px]'>
					{hasRichNotes ? (
						renderNotesSegments(notesSegments)
					) : notesText.trim().length > 0 ? (
						notesText
					) : (
						<span className='italic text-muted-foreground'>{t('pptx.presenter.noNotes')}</span>
					)}
				</div>
			</div>

			{/* Prev / Next controls */}
			<div className='flex items-center justify-between gap-3 px-4 py-2 border-t border-border/60'>
				<button
					type='button'
					data-pptx-presenter-control='prev'
					onClick={() => onMovePresentationSlide(-1)}
					disabled={prevDisabled}
					className='inline-flex items-center justify-center gap-1.5 flex-1 h-11 rounded bg-muted hover:bg-accent disabled:opacity-40 disabled:cursor-not-allowed text-sm transition-colors'
					title={t('pptx.presenter.previousSlide')}
					aria-label={t('pptx.presenter.previousSlide')}
				>
					<LuChevronLeft className='w-5 h-5' />
					{t('pptx.presenter.prev')}
				</button>
				<button
					type='button'
					data-pptx-presenter-control='next'
					onClick={() => onMovePresentationSlide(1)}
					disabled={nextDisabled}
					className='inline-flex items-center justify-center gap-1.5 flex-1 h-11 rounded bg-muted hover:bg-accent disabled:opacity-40 disabled:cursor-not-allowed text-sm transition-colors'
					title={t('pptx.presenter.nextSlide')}
					aria-label={t('pptx.presenter.nextSlide')}
				>
					{t('pptx.presenter.next')}
					<LuChevronRight className='w-5 h-5' />
				</button>
			</div>
		</div>
	);
}
