// viewers/pptx/packages/svelte/src/viewer/components/PresentationSubtitleBar.svelte
<script lang="ts">
	import { captionDisplayText, getSpeechRecognitionCtor, mergeCaptionResults, subtitleRecognitionLanguage, subtitleSettingsFromOptions } from 'ooxml-ui/pptx';
	import type { SpeechSupportState } from 'ooxml-ui/pptx';
	import { useTranslator } from '../../i18n/context';
	import { useViewerOptions } from '../state/viewer-options-context';

	const { enabled }: { enabled: boolean; locale?: string } = $props();
	const t = useTranslator();
	const options = useViewerOptions();
	let support = $state<SpeechSupportState>('unknown');
	let caption = $state('');
	$effect(() => {
		const language = subtitleRecognitionLanguage(subtitleSettingsFromOptions(options.options), navigator.language);
		caption = '';
		if (!enabled) { return; }
		const Ctor = getSpeechRecognitionCtor();
		if (!Ctor) { support = 'unsupported'; return; }
		support = 'supported';
		const recognition = new Ctor();
		let active = true;
		recognition.continuous = true;
		recognition.interimResults = true;
		recognition.lang = language;
		recognition.onresult = (event) => (caption = mergeCaptionResults(event.resultIndex, event.results));
		recognition.onend = () => { if (active) { try { recognition.start(); } catch {} } };
		try { recognition.start(); } catch { support = 'unsupported'; }
		return () => { active = false; recognition.stop(); };
	});
	const text = $derived(captionDisplayText(support, caption, t('pptx.subtitles.notSupported'), t('pptx.subtitles.listening')));
</script>

{#if enabled}<div class="bar" role="status" aria-live="polite">{text}</div>{/if}
<style>.bar{position:absolute;z-index:72;right:10%;bottom:28px;left:10%;padding:10px 18px;border-radius:8px;background:#000c;color:#fff;text-align:center;font-size:18px;line-height:1.4;pointer-events:none}</style>

// viewers/pptx/packages/react/src/viewer/components/PresentationSubtitleBar.tsx
/**
 * PresentationSubtitleBar
 *
 * Shows a live subtitle/caption bar during presentation mode.
 * Uses Web Speech API when available and falls back to a
 * localized "not supported" message otherwise.
 */
import {
	getSpeechRecognitionCtor,
	mergeCaptionResults,
	subtitleRecognitionLanguage,
	subtitleSettingsFromOptions,
} from 'ooxml-ui/pptx';
import type { SpeechRecognitionLite, SpeechRecognitionEventLite } from 'ooxml-ui/pptx';
import React, { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';

import { useViewerOptionsContext } from './viewer-options-context';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface PresentationSubtitleBarProps {
	visible: boolean;
	onCaptionChange?: (caption: string) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PresentationSubtitleBar({
	visible,
	onCaptionChange,
}: PresentationSubtitleBarProps): React.ReactElement | null {
	const { t } = useTranslation();
	const language = subtitleRecognitionLanguage(
		subtitleSettingsFromOptions(useViewerOptionsContext()),
		typeof navigator === 'undefined' ? 'en-US' : navigator.language,
	);
	const [captionText, setCaptionText] = useState<string>('');
	const [supportState, setSupportState] = useState<'unknown' | 'supported' | 'unsupported'>(
		'unknown',
	);
	const recognitionRef = useRef<SpeechRecognitionLite | null>(null);
	const shouldRunRef = useRef<boolean>(false);

	useEffect(() => {
		if (!visible) {
			shouldRunRef.current = false;
			recognitionRef.current?.stop();
			recognitionRef.current = null;
			setCaptionText('');
			return;
		}

		shouldRunRef.current = true;
		const RecognitionCtor = getSpeechRecognitionCtor();
		if (!RecognitionCtor) {
			setSupportState('unsupported');
			return;
		}
		setSupportState('supported');

		const recognition = new RecognitionCtor();
		recognition.continuous = true;
		recognition.interimResults = true;
		recognition.lang = language;

		recognition.onresult = (event: SpeechRecognitionEventLite) => {
			const merged = mergeCaptionResults(event.resultIndex, event.results);
			if (merged.length > 0) {
				setCaptionText(merged);
				onCaptionChange?.(merged);
			}
		};

		recognition.onerror = () => {
			// Keep the bar active and let `onend` attempt restart while visible.
		};
		recognition.onend = () => {
			if (!shouldRunRef.current) {
				return;
			}
			try {
				recognition.start();
			} catch {
				// Browser may throttle rapid restarts; next visibility toggle retries.
			}
		};

		recognitionRef.current = recognition;
		try {
			recognition.start();
		} catch {
			setSupportState('unsupported');
		}

		return () => {
			shouldRunRef.current = false;
			recognition.stop();
			recognitionRef.current = null;
		};
	}, [visible, onCaptionChange, language]);

	if (!visible) {
		return null;
	}

	const renderedText =
		supportState === 'unsupported'
			? t('pptx.subtitles.notSupported')
			: captionText.length > 0
				? captionText
				: t('pptx.subtitles.listening');

	return (
		<div className='absolute bottom-14 left-1/2 -translate-x-1/2 z-[70] max-w-[80%] min-w-[300px]'>
			<div className='px-6 py-3 rounded-lg bg-black/75 backdrop-blur-sm border border-white/10'>
				<p className='text-center text-[15px] text-white/70 italic'>{renderedText}</p>
			</div>
		</div>
	);
}
