// viewers/pptx/packages/vue/src/viewer/components/PresentationSubtitleBar.vue
<script setup lang="ts">
import {
	captionDisplayText,
	getSpeechRecognitionCtor,
	mergeCaptionResults,
	subtitleRecognitionLanguage,
	subtitleSettingsFromOptions,
	DEFAULT_VIEWER_OPTIONS,
} from 'ooxml-ui/pptx';
import type {
	SpeechRecognitionEventLite,
	SpeechRecognitionLite,
	SpeechSupportState,
} from 'ooxml-ui/pptx';
import { computed, inject, onBeforeUnmount, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { ViewerOptionsKey } from '../composables/useViewerOptionsStore';

/**
 * PresentationSubtitleBar - live subtitle/caption bar shown during presentation
 * mode. Uses the Web Speech API (`SpeechRecognition` / `webkitSpeechRecognition`)
 * when available and falls back to a "not supported" message otherwise. Vue port
 * of the React `PresentationSubtitleBar`.
 *
 * Recognition runs only while `visible` is true; toggling `visible` off stops
 * the recogniser and clears the caption.
 */

const props = defineProps<{
	visible: boolean;
}>();

const { t } = useI18n();
const options = inject(ViewerOptionsKey, ref(DEFAULT_VIEWER_OPTIONS));
const language = computed(() =>
	subtitleRecognitionLanguage(
		subtitleSettingsFromOptions(options.value),
		typeof navigator === 'undefined' ? 'en-US' : navigator.language,
	),
);

const captionText = ref('');
const supportState = ref<SpeechSupportState>('unknown');

let recognition: SpeechRecognitionLite | null = null;
let shouldRun = false;

function stopRecognition(): void {
	shouldRun = false;
	recognition?.stop();
	recognition = null;
}

function startRecognition(): void {
	if (typeof window === 'undefined') {
		supportState.value = 'unsupported';
		return;
	}
	shouldRun = true;
	const RecognitionCtor = getSpeechRecognitionCtor();
	if (!RecognitionCtor) {
		supportState.value = 'unsupported';
		return;
	}
	supportState.value = 'supported';

	const recog = new RecognitionCtor();
	recog.continuous = true;
	recog.interimResults = true;
	recog.lang = language.value;

	recog.onresult = (event: SpeechRecognitionEventLite): void => {
		const merged = mergeCaptionResults(event.resultIndex, event.results);
		if (merged.length > 0) {
			captionText.value = merged;
		}
	};

	recog.onerror = (): void => {
		// Keep the bar active; `onend` attempts a restart while visible.
	};
	recog.onend = (): void => {
		if (!shouldRun) {
			return;
		}
		try {
			recog.start();
		} catch {
			// Browser may throttle rapid restarts; next visibility toggle retries.
		}
	};

	recognition = recog;
	try {
		recog.start();
	} catch {
		supportState.value = 'unsupported';
	}
}

watch(
	() => [props.visible, language.value] as const,
	([visible]) => {
		stopRecognition();
		if (!visible) {
			captionText.value = '';
			return;
		}
		startRecognition();
	},
	{ immediate: true },
);

onBeforeUnmount(stopRecognition);

const renderedText = computed<string>(() =>
	captionDisplayText(
		supportState.value,
		captionText.value,
		t('pptx.subtitles.notSupported'),
		t('pptx.subtitles.listening'),
	),
);
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-subtitle-bar absolute bottom-14 left-1/2 z-[70] max-w-[80%] min-w-[300px] -translate-x-1/2"
	>
		<div
			class="pptx-vue-subtitle-inner rounded-lg border border-white/10 bg-black/75 px-6 py-3 backdrop-blur-sm"
		>
			<p class="pptx-vue-subtitle-text m-0 text-center text-[15px] italic text-white/70">
				{{ renderedText }}
			</p>
		</div>
	</div>
</template>

// viewers/pptx/packages/react/src/viewer/components/PresentationSubtitleBar.tsx
/**
 * PresentationSubtitleBar
 *
 * Shows a live subtitle/caption bar during presentation mode.
 * Uses Web Speech API when available and falls back to a
 * localized "not supported" message otherwise.
 */
import {
	getSpeechRecognitionCtor,
	mergeCaptionResults,
	subtitleRecognitionLanguage,
	subtitleSettingsFromOptions,
} from 'ooxml-ui/pptx';
import type { SpeechRecognitionLite, SpeechRecognitionEventLite } from 'ooxml-ui/pptx';
import React, { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';

import { useViewerOptionsContext } from './viewer-options-context';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface PresentationSubtitleBarProps {
	visible: boolean;
	onCaptionChange?: (caption: string) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PresentationSubtitleBar({
	visible,
	onCaptionChange,
}: PresentationSubtitleBarProps): React.ReactElement | null {
	const { t } = useTranslation();
	const language = subtitleRecognitionLanguage(
		subtitleSettingsFromOptions(useViewerOptionsContext()),
		typeof navigator === 'undefined' ? 'en-US' : navigator.language,
	);
	const [captionText, setCaptionText] = useState<string>('');
	const [supportState, setSupportState] = useState<'unknown' | 'supported' | 'unsupported'>(
		'unknown',
	);
	const recognitionRef = useRef<SpeechRecognitionLite | null>(null);
	const shouldRunRef = useRef<boolean>(false);

	useEffect(() => {
		if (!visible) {
			shouldRunRef.current = false;
			recognitionRef.current?.stop();
			recognitionRef.current = null;
			setCaptionText('');
			return;
		}

		shouldRunRef.current = true;
		const RecognitionCtor = getSpeechRecognitionCtor();
		if (!RecognitionCtor) {
			setSupportState('unsupported');
			return;
		}
		setSupportState('supported');

		const recognition = new RecognitionCtor();
		recognition.continuous = true;
		recognition.interimResults = true;
		recognition.lang = language;

		recognition.onresult = (event: SpeechRecognitionEventLite) => {
			const merged = mergeCaptionResults(event.resultIndex, event.results);
			if (merged.length > 0) {
				setCaptionText(merged);
				onCaptionChange?.(merged);
			}
		};

		recognition.onerror = () => {
			// Keep the bar active and let `onend` attempt restart while visible.
		};
		recognition.onend = () => {
			if (!shouldRunRef.current) {
				return;
			}
			try {
				recognition.start();
			} catch {
				// Browser may throttle rapid restarts; next visibility toggle retries.
			}
		};

		recognitionRef.current = recognition;
		try {
			recognition.start();
		} catch {
			setSupportState('unsupported');
		}

		return () => {
			shouldRunRef.current = false;
			recognition.stop();
			recognitionRef.current = null;
		};
	}, [visible, onCaptionChange, language]);

	if (!visible) {
		return null;
	}

	const renderedText =
		supportState === 'unsupported'
			? t('pptx.subtitles.notSupported')
			: captionText.length > 0
				? captionText
				: t('pptx.subtitles.listening');

	return (
		<div className='absolute bottom-14 left-1/2 -translate-x-1/2 z-[70] max-w-[80%] min-w-[300px]'>
			<div className='px-6 py-3 rounded-lg bg-black/75 backdrop-blur-sm border border-white/10'>
				<p className='text-center text-[15px] text-white/70 italic'>{renderedText}</p>
			</div>
		</div>
	);
}
