// viewers/pptx/packages/vue/src/viewer/components/PrintDialog.vue
<script setup lang="ts">
/**
 * PrintDialog - full-featured print options dialog for the Vue viewer.
 *
 * Vue port of the React `PrintDialog.tsx`. Owns the print-settings state and,
 * on confirm, emits a resolved {@link PrintSettings} for the host to feed into
 * `usePrint().print(settings)`. Built on the reusable {@link ModalDialog} shell
 * and the {@link PrintSettingsPanel} fieldset; a lightweight live preview is
 * shown for the handout / notes layouts.
 *
 * Props:
 *  - `open`                  : visibility flag (host-owned).
 *  - `slides`                : the slides, for range bounds + outline preview.
 *  - `activeSlideIndex`      : current slide (for "current slide" range).
 *  - `defaultSlidesPerPage?` : seed from presentation props (clamped to valid).
 *  - `defaultFrameSlides?`   : seed from presentation props.
 *
 * Emits:
 *  - `print` : `PrintSettings`, the user confirmed; run the print flow.
 *  - `close` : the dialog was dismissed.
 */
import type { PptxSlide } from 'pptx-viewer-core';
import { DEFAULT_VIEWER_OPTIONS, resolveDefaultPrintSettings } from 'ooxml-ui/pptx';
import { computed, inject, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { ViewerOptionsKey } from '../composables/useViewerOptionsStore';
import DialogFooter from './DialogFooter.vue';
import ModalDialog from './ModalDialog.vue';
import {
	computePageCount,
	computeSlideCount,
	computeSlideIndices,
	effectiveOrientation,
	getHandoutGrid,
	resolveSlidesPerPage,
} from './print-dialog-types';
import type {
	HandoutSlidesPerPage,
	PrintColorMode,
	PrintOrientation,
	PrintSettings,
	PrintSlideRange,
	PrintWhat,
} from './print-dialog-types';
import PrintSettingsPanel from './PrintSettingsPanel.vue';

const props = defineProps<{
	open: boolean;
	slides: PptxSlide[];
	activeSlideIndex: number;
	defaultSlidesPerPage?: number;
	defaultFrameSlides?: boolean;
}>();

const emit = defineEmits<{
	print: [settings: PrintSettings];
	close: [];
}>();

const { t } = useI18n();

// File > Options > Advanced > Print. `undefined` (Options > "Use the most
// recently used print settings") keeps this dialog's own sticky in-session
// ref state below, since it is only reseeded when the dialog re-opens.
const injectedViewerOptions = inject(ViewerOptionsKey, undefined);
const printOptionDefaults = computed(() =>
	resolveDefaultPrintSettings(injectedViewerOptions?.value ?? DEFAULT_VIEWER_OPTIONS),
);

// ── State ──────────────────────────────────────────────────────────────
const printWhat = ref<PrintWhat>(printOptionDefaults.value?.printWhat ?? 'slides');
const orientation = ref<PrintOrientation>('landscape');
const colorMode = ref<PrintColorMode>(printOptionDefaults.value?.colorMode ?? 'color');
const frameSlides = ref<boolean>(
	printOptionDefaults.value?.frameSlides ?? props.defaultFrameSlides ?? false,
);
const slidesPerPage = ref<HandoutSlidesPerPage>(resolveSlidesPerPage(props.defaultSlidesPerPage));
const slideRange = ref<PrintSlideRange>('all');
const customFrom = ref<number>(1);
const customTo = ref<number>(props.slides.length);

/** Re-seed the form from the props each time the dialog opens. */
watch(
	() => props.open,
	(isOpen) => {
		if (isOpen) {
			const defaults = printOptionDefaults.value;
			printWhat.value = defaults?.printWhat ?? 'slides';
			orientation.value = 'landscape';
			colorMode.value = defaults?.colorMode ?? 'color';
			frameSlides.value = defaults?.frameSlides ?? props.defaultFrameSlides ?? false;
			slidesPerPage.value = resolveSlidesPerPage(props.defaultSlidesPerPage);
			slideRange.value = 'all';
			customFrom.value = 1;
			customTo.value = props.slides.length;
		}
	},
);

// ── Derived ────────────────────────────────────────────────────────────
const totalSlides = computed(() => props.slides.length);

const resolvedOrientation = computed<PrintOrientation>(() =>
	effectiveOrientation(printWhat.value, orientation.value),
);

const slideCount = computed(() =>
	computeSlideCount(slideRange.value, totalSlides.value, customFrom.value, customTo.value),
);

const pageCount = computed(() =>
	computePageCount(printWhat.value, slideCount.value, slidesPerPage.value),
);

const previewSlideIndices = computed(() =>
	computeSlideIndices(
		slideRange.value,
		props.activeSlideIndex,
		totalSlides.value,
		customFrom.value,
		customTo.value,
	),
);

const handoutGrid = computed(() => getHandoutGrid(slidesPerPage.value));

const showHandoutPreview = computed(() => printWhat.value === 'handouts');
const showNotesPreview = computed(() => printWhat.value === 'notes');

// ── Handlers ───────────────────────────────────────────────────────────
function close(): void {
	emit('close');
}

function confirmPrint(): void {
	emit('print', {
		printWhat: printWhat.value,
		orientation: resolvedOrientation.value,
		colorMode: colorMode.value,
		frameSlides: frameSlides.value,
		slidesPerPage: slidesPerPage.value,
		slideRange: slideRange.value,
		customRangeFrom: Math.max(1, Math.min(customFrom.value, totalSlides.value || 1)),
		customRangeTo: Math.max(1, Math.min(customTo.value, totalSlides.value || 1)),
		// Options > Advanced > "Print scale to fit"; no dialog control of its own
		// (PowerPoint keeps this an Options default, not a per-job choice).
		scaleToFit: printOptionDefaults.value?.scaleToFit ?? true,
	});
}
</script>

<template>
	<ModalDialog :open="open" :title="t('pptx.print.title')" @close="close">
		<div class="pptx-vue-print-body flex min-w-[480px] gap-5 max-md:min-w-0 max-md:flex-col">
			<PrintSettingsPanel
				:print-what="printWhat"
				:orientation="orientation"
				:color-mode="colorMode"
				:frame-slides="frameSlides"
				:slides-per-page="slidesPerPage"
				:slide-range="slideRange"
				:custom-from="customFrom"
				:custom-to="customTo"
				:total-slides="totalSlides"
				:active-slide-index="activeSlideIndex"
				@update:print-what="printWhat = $event"
				@update:orientation="orientation = $event"
				@update:color-mode="colorMode = $event"
				@update:frame-slides="frameSlides = $event"
				@update:slides-per-page="slidesPerPage = $event"
				@update:slide-range="slideRange = $event"
				@update:custom-from="customFrom = $event"
				@update:custom-to="customTo = $event"
			/>

			<!-- Lightweight preview for handout / notes layouts -->
			<div
				v-if="showHandoutPreview || showNotesPreview"
				class="pptx-vue-print-preview flex w-[180px] shrink-0 flex-col items-center gap-2.5 border-l border-border pl-4 max-md:w-full max-md:border-l-0 max-md:border-t max-md:pl-0 max-md:pt-4"
			>
				<span
					class="pptx-vue-print-preview-title text-[10px] uppercase tracking-wide text-muted-foreground"
				>
					{{ t('pptx.animations.preview') }}
				</span>

				<div
					v-if="previewSlideIndices.length === 0"
					class="pptx-vue-print-preview-empty flex h-full items-center justify-center text-xs text-muted-foreground"
				>
					{{ t('pptx.statusBar.noSlides') }}
				</div>

				<!-- Handout grid preview -->
				<div
					v-else-if="showHandoutPreview"
					class="pptx-vue-print-preview-page"
					:style="{
						display: 'grid',
						gridTemplateColumns: `repeat(${handoutGrid.columns}, 1fr)`,
						gridTemplateRows: `repeat(${handoutGrid.rows}, 1fr)`,
					}"
				>
					<div
						v-for="cellIndex in handoutGrid.rows * handoutGrid.columns"
						:key="cellIndex"
						class="pptx-vue-print-preview-cell"
						:class="{ 'pptx-vue-print-preview-cell--framed': frameSlides }"
					>
						<span v-if="previewSlideIndices[cellIndex - 1] !== undefined">
							{{ previewSlideIndices[cellIndex - 1] + 1 }}
						</span>
					</div>
				</div>

				<!-- Notes preview -->
				<div v-else class="pptx-vue-print-preview-notes-page">
					<div
						class="pptx-vue-print-preview-cell"
						:class="{ 'pptx-vue-print-preview-cell--framed': frameSlides }"
					>
						<span>{{ (previewSlideIndices[0] ?? 0) + 1 }}</span>
					</div>
					<div class="pptx-vue-print-preview-lines">
						<div v-for="line in 5" :key="line" class="pptx-vue-print-preview-line" />
					</div>
				</div>
			</div>
		</div>

		<template #footer>
			<span class="pptx-vue-print-estimate mr-auto text-xs text-muted-foreground">
				{{
					pageCount === 1
						? t('pptx.print.page', { count: pageCount })
						: t('pptx.print.pages', { count: pageCount })
				}}
				·
				{{
					slideCount === 1
						? t('pptx.print.slide', { count: slideCount })
						: t('pptx.print.slides', { count: slideCount })
				}}
			</span>
			<DialogFooter
				:actions="[
					{ id: 'cancel', label: t('pptx.share.cancel') },
					{ id: 'print', label: t('pptx.print.printButton'), variant: 'primary', icon: 'print' },
				]"
				@action="(id) => (id === 'print' ? confirmPrint() : close())"
			/>
		</template>
	</ModalDialog>
</template>

<style scoped>
.pptx-vue-print-preview-page {
	width: 130px;
	height: 184px;
	gap: 4px;
	padding: 6px;
	background: #ffffff;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.pptx-vue-print-preview-notes-page {
	display: flex;
	flex-direction: column;
	gap: 6px;
	width: 130px;
	height: 184px;
	padding: 8px;
	background: #ffffff;
	border: 1px solid var(--pptx-vue-border, #e5e7eb);
	border-radius: 4px;
	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.pptx-vue-print-preview-notes-page .pptx-vue-print-preview-cell {
	height: 70px;
}

.pptx-vue-print-preview-cell {
	display: flex;
	align-items: center;
	justify-content: center;
	background: #f9fafb;
	border: 1px solid #d1d5db;
	border-radius: 2px;
	font-size: 9px;
	font-weight: 500;
	color: #9ca3af;
}

.pptx-vue-print-preview-cell--framed {
	border: 2px solid #1f2937;
}

.pptx-vue-print-preview-lines {
	display: flex;
	flex-direction: column;
	justify-content: space-evenly;
	flex: 1;
	padding: 0 2px;
}

.pptx-vue-print-preview-line {
	height: 0;
	border-bottom: 1px solid #d1d5db;
}
</style>

// viewers/pptx/packages/react/src/viewer/components/PrintDialog.tsx
/**
 * PrintDialog: Full-featured print dialog for PowerPoint presentations.
 *
 * Options: print what (slides/handouts/notes/outline), slides per page,
 * orientation, colour mode, frame slides, slide range.
 */
import { getDensePanelTouchTargetPx, resolveDefaultPrintSettings } from 'ooxml-ui/pptx';
import React, { useCallback, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuPrinter, LuX } from 'react-icons/lu';

import { useModalDismissDrag } from '../hooks';
import { useIsMobile } from '../hooks/useIsMobile';
import { DialogFooter } from './DialogFooter';
import { PrintPreview, NotesPagePreview } from './print';
import type {
	PrintWhat,
	PrintOrientation,
	PrintColorMode,
	HandoutSlidesPerPage,
	PrintSlideRange,
	PrintDialogProps,
} from './print-dialog-types';
import { HANDOUT_OPTIONS } from './print-dialog-types';
import { PrintSettingsPanel } from './PrintSettingsPanel';
import { useViewerOptionsContext } from './viewer-options-context';

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function PrintDialog({
	open,
	onClose,
	onPrint,
	slides,
	activeSlideIndex,
	defaultSlidesPerPage,
	defaultFrameSlides,
}: PrintDialogProps): React.ReactElement | null {
	const { t } = useTranslation();
	const { panelStyle, handlers: dragHandlers } = useModalDismissDrag(onClose);
	const { viewportWidth } = useIsMobile();
	const touchTargetPx = getDensePanelTouchTargetPx(viewportWidth);
	const closeBtnStyle = { minWidth: touchTargetPx, minHeight: touchTargetPx };

	// File > Options > Advanced > Print. `undefined` (Options > "Use the most
	// recently used print settings") keeps this dialog's own sticky in-session
	// state, since its component instance stays mounted (returns `null` while
	// `open` is false) rather than remounting, so React state already IS the
	// "most recent settings" store across opens within one viewer session.
	const printOptionDefaults = resolveDefaultPrintSettings(useViewerOptionsContext());

	// ── State ───────────────────────────────────────────────────────────
	const [printWhat, setPrintWhat] = useState<PrintWhat>(printOptionDefaults?.printWhat ?? 'slides');
	const [orientation, setOrientation] = useState<PrintOrientation>('landscape');
	const [colorMode, setColorMode] = useState<PrintColorMode>(
		printOptionDefaults?.colorMode ?? 'color',
	);
	const [frameSlides, setFrameSlides] = useState(
		printOptionDefaults?.frameSlides ?? defaultFrameSlides ?? false,
	);
	const [slidesPerPage, setSlidesPerPage] = useState<HandoutSlidesPerPage>(
		(HANDOUT_OPTIONS.includes(defaultSlidesPerPage as HandoutSlidesPerPage)
			? defaultSlidesPerPage
			: 6) as HandoutSlidesPerPage,
	);
	const [slideRange, setSlideRange] = useState<PrintSlideRange>('all');
	const [customFrom, setCustomFrom] = useState(1);
	const [customTo, setCustomTo] = useState(slides.length);

	// ── Derived ─────────────────────────────────────────────────────────
	const effectiveOrientation = useMemo<PrintOrientation>(() => {
		if (printWhat === 'notes' || printWhat === 'outline') {
			return 'portrait';
		}
		if (printWhat === 'handouts') {
			return 'portrait';
		}
		return orientation;
	}, [printWhat, orientation]);

	const slideCount = useMemo(() => {
		if (slideRange === 'all') {
			return slides.length;
		}
		if (slideRange === 'current') {
			return 1;
		}
		const from = Math.max(1, Math.min(customFrom, slides.length));
		const to = Math.max(from, Math.min(customTo, slides.length));
		return to - from + 1;
	}, [slideRange, slides.length, customFrom, customTo]);

	const pageCount = useMemo(() => {
		if (printWhat === 'slides') {
			return slideCount;
		}
		if (printWhat === 'notes') {
			return slideCount;
		}
		if (printWhat === 'outline') {
			return 1;
		}
		return Math.ceil(slideCount / slidesPerPage);
	}, [printWhat, slideCount, slidesPerPage]);

	const previewSlideIndices = useMemo<number[]>(() => {
		if (slideRange === 'current') {
			return [activeSlideIndex];
		}
		if (slideRange === 'custom') {
			const from = Math.max(0, customFrom - 1);
			const to = Math.min(slides.length - 1, customTo - 1);
			return Array.from({ length: Math.max(0, to - from + 1) }, (_, i) => from + i);
		}
		return Array.from({ length: slides.length }, (_, i) => i);
	}, [slideRange, activeSlideIndex, customFrom, customTo, slides.length]);

	// ── Handlers ────────────────────────────────────────────────────────
	const handlePrint = useCallback(() => {
		onPrint({
			printWhat,
			orientation: effectiveOrientation,
			colorMode,
			frameSlides,
			slidesPerPage,
			slideRange,
			customRangeFrom: Math.max(1, Math.min(customFrom, slides.length)),
			customRangeTo: Math.max(1, Math.min(customTo, slides.length)),
			// Options > Advanced > "Print scale to fit"; no dialog control of its
			// own (PowerPoint keeps this an Options default, not a per-job choice).
			scaleToFit: printOptionDefaults?.scaleToFit ?? true,
		});
	}, [
		printWhat,
		effectiveOrientation,
		colorMode,
		frameSlides,
		slidesPerPage,
		slideRange,
		customFrom,
		customTo,
		slides.length,
		printOptionDefaults?.scaleToFit,
		onPrint,
	]);

	if (!open) {
		return null;
	}

	// ── Render ──────────────────────────────────────────────────────────
	return (
		<div
			style={{ zIndex: 1200 }}
			className='fixed inset-0 flex items-center justify-center bg-black/60 backdrop-blur-sm'
		>
			<div
				style={panelStyle}
				role='dialog'
				aria-modal='true'
				aria-label={t('pptx.print.title')}
				className='w-[780px] max-h-[90vh] rounded-xl border border-border bg-background shadow-2xl flex flex-col max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-w-none max-md:max-h-[88dvh] max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'
			>
				{/* Header — also a swipe-down-to-dismiss grab region on touch. */}
				<div
					{...dragHandlers}
					className='flex items-center justify-between px-5 py-4 border-b border-border touch-none'
				>
					<div className='flex items-center gap-2'>
						<LuPrinter className='w-4 h-4 text-muted-foreground' />
						<h2 className='text-sm font-semibold text-foreground'>{t('pptx.print.title')}</h2>
					</div>
					<button
						type='button'
						onClick={onClose}
						style={closeBtnStyle}
						className='p-1 rounded hover:bg-accent text-muted-foreground hover:text-foreground transition-colors inline-flex items-center justify-center'
					>
						<LuX className='w-4 h-4' />
					</button>
				</div>

				{/* Body */}
				<div className='flex-1 overflow-y-auto px-5 py-4 flex gap-5 max-md:flex-col'>
					{/* Left: Settings */}
					<PrintSettingsPanel
						printWhat={printWhat}
						onPrintWhatChange={setPrintWhat}
						orientation={orientation}
						onOrientationChange={setOrientation}
						colorMode={colorMode}
						onColorModeChange={setColorMode}
						frameSlides={frameSlides}
						onFrameSlidesChange={setFrameSlides}
						slidesPerPage={slidesPerPage}
						onSlidesPerPageChange={setSlidesPerPage}
						slideRange={slideRange}
						onSlideRangeChange={setSlideRange}
						customFrom={customFrom}
						onCustomFromChange={setCustomFrom}
						customTo={customTo}
						onCustomToChange={setCustomTo}
						totalSlides={slides.length}
						activeSlideIndex={activeSlideIndex}
					/>

					{/* Right: Preview */}
					{printWhat === 'handouts' && (
						<div className='w-[230px] shrink-0 border-l border-border pl-4 overflow-y-auto max-md:w-full max-md:border-l-0 max-md:border-t max-md:pl-0 max-md:pt-3'>
							<PrintPreview
								slideIndices={previewSlideIndices}
								slidesPerPage={slidesPerPage}
								orientation={effectiveOrientation}
								frameSlides={frameSlides}
							/>
						</div>
					)}
					{printWhat === 'notes' && (
						<div className='w-[230px] shrink-0 border-l border-border pl-4 overflow-y-auto max-md:w-full max-md:border-l-0 max-md:border-t max-md:pl-0 max-md:pt-3'>
							<NotesPagePreview
								slideIndices={previewSlideIndices}
								slides={slides}
								frameSlides={frameSlides}
							/>
						</div>
					)}
				</div>

				{/* Footer */}
				<div className='flex items-center justify-between px-5 py-3 border-t border-border'>
					<span className='text-xs text-muted-foreground'>
						{t('pptx.print.pageEstimate', {
							pages: pageCount,
							slides: slideCount,
						})}
					</span>
					<div className='flex gap-2'>
						<DialogFooter
							actions={[
								{ id: 'cancel', label: t('pptx.common.cancel') },
								{
									id: 'print',
									label: t('pptx.print.printButton'),
									variant: 'primary',
									icon: 'print',
								},
							]}
							onAction={(id) => (id === 'print' ? handlePrint() : onClose())}
						/>
					</div>
				</div>
			</div>
		</div>
	);
}
