// viewers/pptx/packages/svelte/src/viewer/components/SettingsDialog.svelte
<script lang="ts">
	import Settings from '@lucide/svelte/icons/settings';
	import X from '@lucide/svelte/icons/x';
	import { untrack } from 'svelte';
	import {
		DEFAULT_QUICK_ACCESS_COMMAND_IDS,
		activateModalFocus,
		VIEWER_OPTIONS_TABS,
		customizeOptionsTabs,
		isOptionsPageVisible,
		resolveViewerAddinStatus,
	} from 'ooxml-ui/pptx';
	import type {
		ThemeCatalogEntry,
		ViewerOptions,
		ViewerOptionsSection,
		ViewerOptionsTabId,
	} from 'ooxml-ui/pptx';
	import type { LocaleCatalogEntry } from 'ooxml-ui/pptx/i18n';
	import { useTranslator } from '../../i18n/context';
	import { useViewerCustomization } from '../state/viewer-customization.svelte';
	import type { ViewerOptionsState } from '../state/viewer-options.svelte';
	import SettingsAiSection from './ai/SettingsAiSection.svelte';
	import SettingsAppearanceTab from './SettingsAppearanceTab.svelte';
	import SettingsCustomFontsSection from './SettingsCustomFontsSection.svelte';
	import SettingsLanguageTab from './SettingsLanguageTab.svelte';
	import OptionsAddInsPane from './settings/OptionsAddInsPane.svelte';
	import OptionsPane from './settings/OptionsPane.svelte';
	import OptionsQuickAccessPane from './settings/OptionsQuickAccessPane.svelte';
	import OptionsRibbonPane from './settings/OptionsRibbonPane.svelte';

	const {
		optionsState,
		onclose,
		themeKey,
		themeCatalog,
		onsetthemekey,
		locale,
		availableLocales,
		onsetlocale,
		aiEnabled = false,
		collabActive = false,
		customFontFamilies = [],
		oncustomfont = () => {},
	}: {
		/** The shared File > Options state (store + behavior projections). */
		optionsState: ViewerOptionsState;
		onclose: () => void;
		themeKey: string;
		themeCatalog: readonly ThemeCatalogEntry[];
		onsetthemekey: (key: string) => void;
		locale: string;
		availableLocales?: readonly LocaleCatalogEntry[];
		onsetlocale: (code: string) => void;
		/** When true, an "AI" section is shown for exporting detailed chat logs. */
		aiEnabled?: boolean;
		/** Live collaboration session state, for the Add-ins pane's status column. */
		collabActive?: boolean;
		/** Families registered this session via the Fonts section. */
		customFontFamilies?: readonly string[];
		/** A font file was registered; the ribbon adds the family to its list. */
		oncustomfont?: (family: string) => void;
	} = $props();

	const t = useTranslator();
	const customization = useViewerCustomization();
	/** Synthetic tab id for the AI section (appended only when `aiEnabled`). */
	const AI_TAB_ID = 'ai';
	// The schema after the host's customisation: hidden pages / sections /
	// settings removed, locked settings marked `readOnly` (shared decides).
	const tabs = $derived(customizeOptionsTabs(VIEWER_OPTIONS_TABS, customization.resolved));
	const showAiTab = $derived(aiEnabled && isOptionsPageVisible(customization.resolved, AI_TAB_ID));
	// eslint-disable-next-line prefer-const -- reassigned in the nav markup below
	let activeTabId = $state<ViewerOptionsTabId | typeof AI_TAB_ID>('general');
	// A tab the host hides while it is active falls back to the first visible one.
	const activeTab = $derived(tabs.find((entry) => entry.id === activeTabId) ?? tabs[0]);
	const aiActive = $derived(showAiTab && (activeTabId === AI_TAB_ID || !activeTab));
	const options = $derived<ViewerOptions>(optionsState.options);
	// Real runtime signals for the Add-ins pane's active/inactive split: the two
	// three.js-backed renderers follow Advanced > "Disable 3D rendering", and
	// the collaboration module follows the live session. The rest of the
	// catalog (EMF/MTX converters, locales) has no on/off switch, so it keeps
	// `resolveViewerAddinRows`'s `active: true` fallback.
	const addinStatus = $derived(
		resolveViewerAddinStatus(options.advanced.disable3DRendering, collabActive),
	);

	// Snapshot taken when the dialog mounts; Cancel restores it wholesale.
	// Deliberately the value at open time, so read outside reactive tracking.
	const snapshot = untrack(() => optionsState.options);

	function onchange(group: Parameters<ViewerOptionsState['setValue']>[0], key: string, value: boolean | number | string): void {
		optionsState.setValue(group, key, value);
	}
	function cancel(): void {
		optionsState.restore(snapshot);
		onclose();
	}
	function modalFocus(node: HTMLElement): { destroy(): void } {
		return { destroy: activateModalFocus(node, { onEscape: onclose }) };
	}
	function clearCache(): void {
		void optionsState.clearCache().catch(() => {
			// Keep the options dialog usable when IndexedDB rejects cleanup.
		});
	}
	function isSpecial(section: ViewerOptionsSection): boolean {
		return (
			section.special === 'themePicker' ||
			section.special === 'clearCache' ||
			section.special === 'customFonts'
		);
	}
</script>

<div class="backdrop">
	<button class="scrim" type="button" aria-label={t('pptx.settings.closeSettings')} onclick={onclose}></button>
	<!-- svelte-ignore a11y_no_noninteractive_element_to_interactive_role -->
	<section use:modalFocus role="dialog" tabindex="-1" aria-modal="true" aria-label={t('pptx.options.title')}>
		<header>
			<div><b><Settings size={20} aria-hidden="true" /></b><h2>{t('pptx.options.title')}</h2></div>
			<button type="button" aria-label={t('pptx.settings.close')} onclick={onclose}><X size={16} aria-hidden="true" /></button>
		</header>
		<div class="layout">
			<nav aria-label={t('pptx.options.title')}>
				{#each tabs as tab (tab.id)}
					<button class:active={!aiActive && activeTab?.id === tab.id} onclick={() => (activeTabId = tab.id)}>{t(tab.labelKey)}</button>
				{/each}
				{#if showAiTab}
					<button class:active={aiActive} onclick={() => (activeTabId = AI_TAB_ID)}>{t('pptx.ai.settingsSectionTitle')}</button>
				{/if}
			</nav>
			<div class="body">
				{#if aiActive}
					<p class="headline">{t('pptx.ai.settingsSectionTitle')}</p>
					<SettingsAiSection />
				{:else if !activeTab}
					<!-- Every page is hidden by the host: nothing to render. -->
				{:else if activeTab.custom === 'language'}
					<p class="headline">{t(activeTab.descriptionKey)}</p>
					<section class="lang">
						<h3>{t('pptx.options.language.displayLanguage')}</h3>
						<p class="hint">{t('pptx.options.language.displayLanguageDescription')}</p>
						<SettingsLanguageTab {locale} {availableLocales} onselect={onsetlocale} />
					</section>
				{:else if activeTab.custom === 'ribbon'}
					<p class="headline">{t(activeTab.descriptionKey)}</p>
					<OptionsRibbonPane {options} ontabhiddenchange={(id, hidden) => optionsState.setRibbonTabHidden(id, hidden)} onreset={() => optionsState.reset('ribbon')} />
				{:else if activeTab.custom === 'addIns'}
					<p class="headline">{t(activeTab.descriptionKey)}</p>
					<OptionsAddInsPane {addinStatus} />
				{:else}
					<OptionsPane tab={activeTab} {options} {onchange}>
						{#snippet special(section)}
							{#if section.special === 'themePicker'}
								<SettingsAppearanceTab {themeKey} {themeCatalog} onselect={onsetthemekey} />
							{:else if section.special === 'customFonts'}
								<SettingsCustomFontsSection
									enabled={options.general.enableCustomFontUpload}
									families={customFontFamilies}
									onregistered={oncustomfont}
								/>
							{:else if section.special === 'clearCache'}
								<p class="hint">{t('pptx.options.save.clearCacheDescription')}</p>
								<button type="button" class="ghost" onclick={clearCache}>{t('pptx.options.save.clearCacheNow')}</button>
							{/if}
						{/snippet}
						{#if activeTab.custom === 'quickAccess'}
							<OptionsQuickAccessPane {options} oncommandschange={(ids) => optionsState.setQuickAccessCommands(ids)} onreset={() => optionsState.setQuickAccessCommands([...DEFAULT_QUICK_ACCESS_COMMAND_IDS])} />
						{/if}
					</OptionsPane>
				{/if}
			</div>
		</div>
		<footer>
			<button type="button" class="ghost" onclick={() => optionsState.reset()}>{t('pptx.options.resetAll')}</button>
			<div class="actions">
				<button type="button" class="ghost" onclick={cancel}>{t('pptx.common.cancel')}</button>
				<button type="button" class="primary" onclick={onclose}>{t('pptx.common.ok')}</button>
			</div>
		</footer>
	</section>
</div>

<style>
	.backdrop { position: fixed; inset: 0; z-index: 1200; display: grid; place-items: center; background: #0009; }
	.scrim { position: absolute; inset: 0; border: 0; background: transparent; }
	section[role='dialog'] { position: relative; display: flex; flex-direction: column; width: min(56rem, calc(100vw - 32px)); max-height: 85vh; overflow: hidden; border: 1px solid var(--pptx-border, #3f3f52); border-radius: 13px; background: var(--pptx-card, #1e1e2e); box-shadow: 0 24px 80px #0009; }
	header, header div { display: flex; align-items: center; }
	header { justify-content: space-between; padding: 14px 18px; border-bottom: 1px solid var(--pptx-border, #3f3f52); }
	header div { gap: 9px; }
	h2 { margin: 0; font-size: 14px; color: var(--pptx-foreground, #e2e8f0); }
	header b { display: inline-flex; color: var(--pptx-primary, #c43b32); }
	header > button { display: inline-flex; align-items: center; justify-content: center; border: 0; background: transparent; color: inherit; cursor: pointer; }
	.layout { display: flex; min-height: 0; flex: 1; }
	nav { display: flex; flex-direction: column; width: 176px; flex-shrink: 0; gap: 2px; overflow-y: auto; padding: 8px; border-right: 1px solid var(--pptx-border, #3f3f52); }
	nav button { border: 0; border-radius: 6px; padding: 8px 12px; background: transparent; color: var(--pptx-foreground, #e2e8f0); font-size: 13px; text-align: left; white-space: nowrap; cursor: pointer; }
	nav button:hover { background: var(--pptx-muted, #2a2a3d); }
	nav button.active { background: color-mix(in srgb, var(--pptx-primary, #c43b32) 16%, transparent); color: var(--pptx-primary, #c43b32); font-weight: 600; }
	.body { min-height: 0; flex: 1; overflow-y: auto; padding: 16px 20px; }
	.headline { margin: 0 0 14px; color: var(--pptx-foreground, #e2e8f0); font-size: 12.5px; font-weight: 600; }
	.lang h3 { margin: 0 0 4px; color: var(--pptx-muted-foreground, #94a3b8); font-size: 10.5px; font-weight: 700; letter-spacing: 0.05em; text-transform: uppercase; }
	.hint { margin: 0 0 8px; color: var(--pptx-muted-foreground, #94a3b8); font-size: 11px; }
	footer { display: flex; align-items: center; justify-content: space-between; gap: 8px; padding: 12px 18px; border-top: 1px solid var(--pptx-border, #3f3f52); }
	.actions { display: flex; gap: 8px; }
	button.ghost { border: 1px solid var(--pptx-border, #3f3f52); border-radius: 6px; padding: 6px 14px; background: transparent; color: var(--pptx-foreground, #e2e8f0); font-size: 12px; cursor: pointer; }
	button.primary { border: 0; border-radius: 6px; padding: 6px 16px; background: var(--pptx-primary, #c43b32); color: #fff; font-size: 12px; font-weight: 600; cursor: pointer; }
	/* 767px, not an ad hoc 600px: matches MOBILE_BREAKPOINT (768) from
	   pptx-viewer-shared's render/responsive module, the single threshold
	   every binding's dense-panel layout is measured against (CLAUDE.md
	   Rule 2 - two breakpoints drifting apart is the exact failure mode this
	   module exists to prevent). */
	@media (max-width: 767px) {
		section[role='dialog'] { position: fixed; inset: auto 0 0; width: 100%; max-height: 88dvh; border-radius: 16px 16px 0 0; }
		.layout { flex-direction: column; }
		nav { flex-direction: row; width: 100%; overflow-x: auto; border-right: 0; border-bottom: 1px solid var(--pptx-border, #3f3f52); }
		/* Touch target: matches MIN_TOUCH_TARGET_PX (44) from pptx-viewer-shared's render/responsive module. */
		header > button { min-width: 44px !important; min-height: 44px !important; }
		nav button { min-width: 44px !important; min-height: 44px !important; }
		footer button { min-height: 44px !important; }
	}
</style>

// viewers/pptx/packages/react/src/viewer/components/SettingsDialog.tsx
import type {
	ThemeCatalogEntry,
	ToolbarTabId,
	ViewerAddinStatus,
	ViewerOptions,
	ViewerOptionsGroupId,
	ViewerOptionsTabId,
} from 'ooxml-ui/pptx';
import {
	DEFAULT_QUICK_ACCESS_COMMAND_IDS,
	VIEWER_OPTIONS_TABS,
	customizeOptionsTabs,
	getDensePanelTouchTargetPx,
	isOptionsPageVisible,
	shouldStickyActionRow,
} from 'ooxml-ui/pptx';
import type { PptxAiChatStore } from 'ooxml-ui/pptx/ai';
import type { LocaleCatalogEntry } from 'ooxml-ui/pptx/i18n';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuSettings, LuX } from 'react-icons/lu';

import { useModalDismissDrag } from '../hooks';
import { useIsMobile } from '../hooks/useIsMobile';
import { cn } from '../utils';
import { OptionsAddInsPane } from './settings/OptionsAddInsPane';
import { OptionsPane } from './settings/OptionsPane';
import { OptionsQuickAccessPane } from './settings/OptionsQuickAccessPane';
import { OptionsRibbonPane } from './settings/OptionsRibbonPane';
import { SettingsAiTab } from './SettingsAiTab';
import { SettingsAppearanceTab } from './SettingsAppearanceTab';
import { SettingsCustomFontsSection } from './SettingsCustomFontsSection';
import { SettingsLanguageTab } from './SettingsLanguageTab';
import { useViewerCustomizationContext } from './viewer-customization-context';

/** Synthetic tab id for the AI section (appended only when `aiEnabled`). */
const AI_TAB_ID = 'ai';

/**
 * Stable empty default for `customFontFamilies`. A fresh `[]` in the parameter
 * list is a new reference every render, which breaks referential equality for
 * anything downstream that memoises on it.
 */
const NO_CUSTOM_FONT_FAMILIES: readonly string[] = [];
type SettingsTabId = ViewerOptionsTabId | typeof AI_TAB_ID;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SettingsDialogProps {
	isOpen: boolean;
	onClose: () => void;
	/** Full File > Options snapshot rendered by every pane. */
	options: ViewerOptions;
	onOptionChange: (
		group: ViewerOptionsGroupId,
		key: string,
		value: boolean | number | string,
	) => void;
	/** Restore a snapshot wholesale (Cancel semantics). */
	onRestoreOptions: (options: ViewerOptions) => void;
	onRibbonTabHiddenChange: (tabId: ToolbarTabId, hidden: boolean) => void;
	onQuickAccessCommandsChange: (commandIds: string[]) => void;
	onResetOptions: (group?: ViewerOptionsGroupId) => void;
	/** Options > Save > "Delete cached files". */
	onClearCache: () => void;
	/** Availability flags for the Add-ins pane. */
	addinStatus?: ViewerAddinStatus;
	/** Key of the currently active theme catalog entry. */
	themeKey: string;
	availableThemes: readonly ThemeCatalogEntry[];
	onSelectTheme: (key: string) => void;
	/** Currently active locale code. */
	localeCode: string;
	availableLocales: readonly LocaleCatalogEntry[];
	onSelectLocale: (code: string) => void;
	/** When true, an "AI" section is shown for exporting detailed chat logs. */
	aiEnabled?: boolean;
	/** Families registered this session via the Fonts section. */
	customFontFamilies?: readonly string[];
	/** Called after a font file is registered, so the ribbon picks it up. */
	onCustomFontRegistered?: (family: string) => void;
	/** Chat store the AI section reads from (defaults to the shared store). */
	chatStore?: PptxAiChatStore;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * File > Options: a PowerPoint Options-style dialog with the ten shared
 * categories in a left rail and schema-driven panes on the right. Changes
 * apply live; Cancel restores the snapshot taken when the dialog opened.
 */
export function SettingsDialog({
	isOpen,
	onClose,
	options,
	onOptionChange,
	onRestoreOptions,
	onRibbonTabHiddenChange,
	onQuickAccessCommandsChange,
	onResetOptions,
	onClearCache,
	addinStatus,
	themeKey,
	availableThemes,
	onSelectTheme,
	localeCode,
	availableLocales,
	onSelectLocale,
	aiEnabled,
	chatStore,
	customFontFamilies = NO_CUSTOM_FONT_FAMILIES,
	onCustomFontRegistered,
}: SettingsDialogProps): React.ReactElement | null {
	const [activeTabId, setActiveTabId] = useState<SettingsTabId>('general');
	const { t } = useTranslation();
	const customization = useViewerCustomizationContext();
	const { panelStyle, handlers: dragHandlers } = useModalDismissDrag(onClose);
	const { viewportWidth, viewportHeight } = useIsMobile();
	const touchTargetPx = getDensePanelTouchTargetPx(viewportWidth);
	const navBtnStyle = { minHeight: touchTargetPx, minWidth: touchTargetPx };
	const closeBtnStyle = { minWidth: touchTargetPx, minHeight: touchTargetPx };
	const footerBtnStyle = { minHeight: touchTargetPx };
	const stickyFooterClass = shouldStickyActionRow(viewportWidth, viewportHeight)
		? 'sticky bottom-0 bg-popover'
		: '';
	const snapshotRef = useRef<ViewerOptions | null>(null);
	const wasOpenRef = useRef(false);

	// Snapshot on open for Cancel semantics.
	useEffect(() => {
		if (isOpen && !wasOpenRef.current) {
			snapshotRef.current = options;
		}
		wasOpenRef.current = isOpen;
	}, [isOpen, options]);

	const handleCancel = useCallback(() => {
		if (snapshotRef.current) {
			onRestoreOptions(snapshotRef.current);
		}
		onClose();
	}, [onClose, onRestoreOptions]);

	// Close (confirming) on Escape.
	const handleKeyDown = useCallback(
		(e: KeyboardEvent) => {
			if (e.key === 'Escape') {
				onClose();
			}
		},
		[onClose],
	);

	useEffect(() => {
		if (isOpen) {
			document.addEventListener('keydown', handleKeyDown);
			return () => document.removeEventListener('keydown', handleKeyDown);
		}
	}, [isOpen, handleKeyDown]);

	if (!isOpen) {
		return null;
	}

	// Host customisation: hidden pages/sections/settings dropped, locked
	// settings marked read-only. A hidden active tab falls back to the first.
	const tabs = customizeOptionsTabs(VIEWER_OPTIONS_TABS, customization);
	const showAiTab = Boolean(aiEnabled) && isOptionsPageVisible(customization, AI_TAB_ID);
	const activeTab = tabs.find((tab) => tab.id === activeTabId) ?? tabs[0];
	const aiActive = activeTabId === AI_TAB_ID && showAiTab;
	if (!activeTab) {
		return null;
	}
	const currentTabId: SettingsTabId = aiActive ? AI_TAB_ID : activeTab.id;

	return (
		<>
			{/* Backdrop */}
			<button
				type='button'
				style={{ zIndex: 1200 }}
				className='fixed inset-0 bg-black/60'
				aria-label={t('pptx.settings.closeSettings')}
				onClick={onClose}
			/>
			{/* Dialog */}
			<div
				style={{ zIndex: 1201 }}
				className='fixed inset-0 flex items-center justify-center pointer-events-none'
			>
				<div
					style={panelStyle}
					role='dialog'
					aria-modal='true'
					aria-label={t('pptx.options.title')}
					className='pointer-events-auto flex max-h-[85vh] w-[min(56rem,calc(100%-2rem))] flex-col rounded-xl border border-border bg-popover shadow-2xl backdrop-blur-xl max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:max-h-[88dvh] max-md:w-full max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'
				>
					{/* Header - also a swipe-down-to-dismiss grab region on touch. */}
					<div
						{...dragHandlers}
						className='flex items-center justify-between border-b border-border/60 px-5 py-4 touch-none'
					>
						<div className='flex items-center gap-2'>
							<LuSettings className='h-5 w-5 text-primary' />
							<h2 className='text-sm font-semibold text-foreground'>{t('pptx.options.title')}</h2>
						</div>
						<button
							type='button'
							onClick={onClose}
							style={closeBtnStyle}
							className='rounded p-1 transition-colors hover:bg-accent inline-flex items-center justify-center'
							aria-label={t('pptx.settings.close')}
						>
							<LuX className='h-4 w-4 text-muted-foreground' />
						</button>
					</div>

					{/* Body: category rail + pane */}
					<div className='flex min-h-0 flex-1 max-md:flex-col'>
						<nav
							aria-label={t('pptx.options.title')}
							className='w-44 shrink-0 space-y-0.5 overflow-y-auto border-r border-border/60 p-2 max-md:flex max-md:w-full max-md:space-y-0 max-md:gap-1 max-md:overflow-x-auto max-md:border-b max-md:border-r-0'
						>
							{tabs.map((tab) => (
								<button
									key={tab.id}
									type='button'
									onClick={() => setActiveTabId(tab.id)}
									aria-current={currentTabId === tab.id}
									style={navBtnStyle}
									className={cn(
										'flex w-full items-center whitespace-nowrap rounded px-3 py-2 text-left text-sm transition-colors max-md:w-auto',
										currentTabId === tab.id
											? 'bg-primary/10 font-medium text-primary'
											: 'text-foreground hover:bg-accent',
									)}
								>
									{t(tab.labelKey)}
								</button>
							))}
							{showAiTab && (
								<button
									type='button'
									onClick={() => setActiveTabId(AI_TAB_ID)}
									aria-current={aiActive}
									style={navBtnStyle}
									className={cn(
										'flex w-full items-center whitespace-nowrap rounded px-3 py-2 text-left text-sm transition-colors max-md:w-auto',
										aiActive
											? 'bg-primary/10 font-medium text-primary'
											: 'text-foreground hover:bg-accent',
									)}
								>
									{t('pptx.ai.settingsSectionTitle')}
								</button>
							)}
						</nav>

						<div className='min-h-0 flex-1 overflow-y-auto px-5 py-4'>
							{aiActive ? (
								<div className='space-y-4'>
									<p className='text-sm font-medium text-foreground'>
										{t('pptx.ai.settingsSectionTitle')}
									</p>
									<SettingsAiTab store={chatStore} />
								</div>
							) : activeTab.custom === 'language' ? (
								<div className='space-y-4'>
									<p className='text-sm font-medium text-foreground'>
										{t(activeTab.descriptionKey)}
									</p>
									<section>
										<h3 className='mb-1 border-b border-border/60 pb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground'>
											{t('pptx.options.language.displayLanguage')}
										</h3>
										<p className='mb-2 text-xs text-muted-foreground'>
											{t('pptx.options.language.displayLanguageDescription')}
										</p>
										<SettingsLanguageTab
											activeLocale={localeCode}
											locales={availableLocales}
											onSelectLocale={onSelectLocale}
										/>
									</section>
								</div>
							) : activeTab.custom === 'ribbon' ? (
								<div className='space-y-4'>
									<p className='text-sm font-medium text-foreground'>
										{t(activeTab.descriptionKey)}
									</p>
									<OptionsRibbonPane
										options={options}
										onRibbonTabHiddenChange={onRibbonTabHiddenChange}
										onResetRibbon={() => onResetOptions('ribbon')}
									/>
								</div>
							) : activeTab.custom === 'addIns' ? (
								<div className='space-y-4'>
									<p className='text-sm font-medium text-foreground'>
										{t(activeTab.descriptionKey)}
									</p>
									<OptionsAddInsPane addinStatus={addinStatus} />
								</div>
							) : (
								<OptionsPane
									tab={activeTab}
									options={options}
									onOptionChange={onOptionChange}
									renderSpecial={(section) => {
										if (section.special === 'themePicker') {
											return (
												<div className='mt-2'>
													<SettingsAppearanceTab
														activeThemeKey={themeKey}
														themes={availableThemes}
														onSelectTheme={onSelectTheme}
													/>
												</div>
											);
										}
										if (section.special === 'customFonts') {
											return (
												<SettingsCustomFontsSection
													enabled={options.general.enableCustomFontUpload}
													families={customFontFamilies}
													onRegistered={(family) => onCustomFontRegistered?.(family)}
												/>
											);
										}
										if (section.special === 'clearCache') {
											return (
												<div className='mt-2'>
													<p className='mb-2 text-xs text-muted-foreground'>
														{t('pptx.options.save.clearCacheDescription')}
													</p>
													<button
														type='button'
														onClick={onClearCache}
														className='rounded border border-border px-3 py-1.5 text-xs text-foreground transition-colors hover:bg-accent'
													>
														{t('pptx.options.save.clearCacheNow')}
													</button>
												</div>
											);
										}
										return null;
									}}
								>
									{activeTab.custom === 'quickAccess' && (
										<OptionsQuickAccessPane
											options={options}
											onQuickAccessCommandsChange={onQuickAccessCommandsChange}
											onResetQuickAccess={() =>
												onQuickAccessCommandsChange([...DEFAULT_QUICK_ACCESS_COMMAND_IDS])
											}
										/>
									)}
								</OptionsPane>
							)}
						</div>
					</div>

					{/* Footer */}
					<div
						className={`flex items-center justify-between gap-2 border-t border-border/60 px-5 py-3 ${stickyFooterClass}`}
					>
						<button
							type='button'
							onClick={() => onResetOptions()}
							style={footerBtnStyle}
							className='rounded border border-border px-3 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground'
						>
							{t('pptx.options.resetAll')}
						</button>
						<div className='flex items-center gap-2'>
							<button
								type='button'
								onClick={handleCancel}
								style={footerBtnStyle}
								className='rounded border border-border px-4 py-1.5 text-xs text-foreground transition-colors hover:bg-accent'
							>
								{t('pptx.common.cancel')}
							</button>
							<button
								type='button'
								onClick={onClose}
								style={footerBtnStyle}
								className='rounded bg-primary px-4 py-1.5 text-xs font-medium text-primary-foreground transition-colors hover:bg-primary/90'
							>
								{t('pptx.common.ok')}
							</button>
						</div>
					</div>
				</div>
			</div>
		</>
	);
}
