// viewers/pptx/packages/svelte/src/viewer/components/ribbon/home/SlideTemplatePreview.svelte
<script lang="ts">
	/**
	 * SlideTemplatePreview: live-rendered miniature of a slide template.
	 *
	 * Mirrors React's `SlideTemplatePreview` (and the SmartArt gallery
	 * pattern): build the exact elements insertion would produce (shared
	 * `buildSlideTemplateContent`) at full canvas size, render them through
	 * the real `SlideStage` / `ElementRenderer` pipeline, and scale the stage
	 * down so the preview is pixel-faithful to what Insert lands in the deck.
	 */
	import type { PptxSlide } from 'pptx-viewer-core';
	import { buildSlideTemplateContent } from 'ooxml-ui/pptx';
	import type { SlideTemplateId } from 'ooxml-ui/pptx';

	import SlideStage from '../../SlideStage.svelte';

	const {
		templateId,
		scheme,
	}: {
		templateId: SlideTemplateId;
		/** Optional deck scheme so the preview shows the deck's theme colours. */
		scheme?: Record<string, string>;
	} = $props();

	/** Full-size stage the template is built at (standard 16:9 canvas). */
	const PREVIEW_CANVAS = { width: 1280, height: 720 };
	/** 144px tile width over the 1280px stage = scale 0.1125 (tile 144 x 81). */
	const PREVIEW_SCALE = 144 / PREVIEW_CANVAS.width;

	const mediaDataUrls = new Map<string, string>();
	const previewSlide = $derived.by((): PptxSlide => {
		const content = buildSlideTemplateContent(templateId, {
			slideWidth: PREVIEW_CANVAS.width,
			slideHeight: PREVIEW_CANVAS.height,
			...(scheme ? { scheme } : {}),
			idFor: (index) => `tpl-preview-${templateId}-${index}`,
		});
		return {
			id: `tpl-preview-${templateId}`,
			rId: '',
			slideNumber: 1,
			elements: content.elements,
			...(content.backgroundColor ? { backgroundColor: content.backgroundColor } : {}),
		};
	});
</script>

<div class="pptx-svelte-slide-template-preview" aria-hidden="true">
	<SlideStage
		slide={previewSlide}
		canvasSize={PREVIEW_CANVAS}
		{mediaDataUrls}
		scale={PREVIEW_SCALE}
	/>
</div>

<style>
	.pptx-svelte-slide-template-preview {
		width: 144px;
		height: 81px;
		overflow: hidden;
		border-radius: 4px;
		background: #fff;
		pointer-events: none;
	}
</style>

// viewers/pptx/packages/react/src/viewer/components/SlideTemplatePreview.tsx
/**
 * SlideTemplatePreview: live-rendered miniature of a slide template.
 *
 * Mirrors the SmartArt gallery pattern: build the exact elements insertion
 * would produce (shared `buildSlideTemplateContent`) at full canvas size,
 * render them through the real StaticElementRenderer, and scale the stage
 * down with a CSS transform so the preview is pixel-faithful.
 */
import type { PptxSlide } from 'pptx-viewer-core';
import { buildSlideTemplateContent } from 'ooxml-ui/pptx';
import type { SlideTemplateId } from 'ooxml-ui/pptx';
import React, { useMemo } from 'react';

import { StaticElementRenderer } from './StaticElementRenderer';

/** Full-size stage the template is built at (standard 16:9 canvas). */
const PREVIEW_CANVAS_WIDTH = 1280;
const PREVIEW_CANVAS_HEIGHT = 720;
/** Rendered tile width in px. */
const PREVIEW_TILE_WIDTH = 144;
const PREVIEW_SCALE = PREVIEW_TILE_WIDTH / PREVIEW_CANVAS_WIDTH;
const PREVIEW_TILE_HEIGHT = Math.round(PREVIEW_CANVAS_HEIGHT * PREVIEW_SCALE);

export interface SlideTemplatePreviewProps {
	templateId: SlideTemplateId;
	/** Optional deck scheme so the preview shows the deck's theme colours. */
	scheme?: Record<string, string>;
}

export function SlideTemplatePreview({
	templateId,
	scheme,
}: SlideTemplatePreviewProps): React.ReactElement {
	const previewSlide: PptxSlide = useMemo(() => {
		const content = buildSlideTemplateContent(templateId, {
			slideWidth: PREVIEW_CANVAS_WIDTH,
			slideHeight: PREVIEW_CANVAS_HEIGHT,
			...(scheme ? { scheme } : {}),
			idFor: (index) => `tpl-preview-${templateId}-${index}`,
		});
		return {
			id: `tpl-preview-${templateId}`,
			rId: '',
			slideNumber: 1,
			elements: content.elements,
			...(content.backgroundColor ? { backgroundColor: content.backgroundColor } : {}),
		};
	}, [templateId, scheme]);

	return (
		<div
			aria-hidden='true'
			className='overflow-hidden pointer-events-none rounded'
			style={{
				width: PREVIEW_TILE_WIDTH,
				height: PREVIEW_TILE_HEIGHT,
				backgroundColor: previewSlide.backgroundColor ?? '#FFFFFF',
			}}
		>
			<div
				style={{
					position: 'relative',
					width: PREVIEW_CANVAS_WIDTH,
					height: PREVIEW_CANVAS_HEIGHT,
					transform: `scale(${PREVIEW_SCALE})`,
					transformOrigin: 'top left',
				}}
			>
				{previewSlide.elements.map((element, index) => (
					<StaticElementRenderer
						key={element.id}
						element={element}
						activeSlide={previewSlide}
						allSlides={[previewSlide]}
						zIndex={index}
					/>
				))}
			</div>
		</div>
	);
}
