// viewers/pptx/packages/angular/src/viewer/slide-template-preview.component.ts
/**
 * slide-template-preview.component.ts: live miniature of one slide template.
 *
 * Selector: `pptx-slide-template-preview`
 *
 * Angular port of the React `SlideTemplatePreview.tsx`, mirroring the SmartArt
 * gallery pattern (`smart-art-preview.component.ts`): the exact elements
 * insertion would produce (shared `buildSlideTemplateContent`) are built at
 * full canvas size (1280x720), rendered through the REAL
 * `pptx-element-renderer`, and scaled down with a CSS transform so the preview
 * is pixel-faithful to the inserted slide.
 *
 * @module angular-viewer/slide-template-preview
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import type { PptxElement } from 'pptx-viewer-core';

import { buildSlideTemplateContent } from 'ooxml-ui/pptx';
import type { SlideTemplateId } from 'ooxml-ui/pptx';
import { ElementRendererComponent } from './element-renderer.component';

/** Full-size stage the template is built at (standard 16:9 canvas). */
const PREVIEW_CANVAS_WIDTH = 1280;
const PREVIEW_CANVAS_HEIGHT = 720;

/** The elements + background of one preview tile. */
interface TemplatePreviewContent {
	elements: PptxElement[];
	backgroundColor: string;
}

@Component({
	selector: 'pptx-slide-template-preview',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ElementRendererComponent],
	template: `
		<div
			class="pptx-tpl-preview"
			aria-hidden="true"
			[style.background-color]="content().backgroundColor"
		>
			<div class="pptx-tpl-preview__stage">
				@for (element of content().elements; track element.id; let i = $index) {
					<pptx-element-renderer
						[element]="element"
						[zIndex]="i"
						[interactive]="false"
						[canvasWidth]="canvasWidth"
						[canvasHeight]="canvasHeight"
						[slideElements]="content().elements"
					/>
				}
			</div>
		</div>
	`,
	// NOTE: values must stay in sync with the PREVIEW_* constants above; the
	// Angular AOT compiler requires `styles` to be a static string (no
	// interpolation), so the numbers are written out literally
	// (144 = 1280 * 0.1125, 81 = 720 * 0.1125).
	styles: `
		.pptx-tpl-preview {
			width: 144px;
			height: 81px;
			overflow: hidden;
			pointer-events: none;
			border-radius: 4px;
		}
		.pptx-tpl-preview__stage {
			position: relative;
			width: 1280px;
			height: 720px;
			transform: scale(0.1125);
			transform-origin: top left;
		}
	`,
})
export class SlideTemplatePreviewComponent {
	/** The slide template to draw a thumbnail for. */
	readonly templateId = input.required<SlideTemplateId>();

	/** Optional deck scheme map so the preview shows the deck's theme colours. */
	readonly scheme = input<Record<string, string> | undefined>(undefined);

	protected readonly canvasWidth = PREVIEW_CANVAS_WIDTH;
	protected readonly canvasHeight = PREVIEW_CANVAS_HEIGHT;

	/** The exact content insertion would produce, built at full canvas size. */
	protected readonly content = computed<TemplatePreviewContent>(() => {
		const templateId = this.templateId();
		const scheme = this.scheme();
		const built = buildSlideTemplateContent(templateId, {
			slideWidth: PREVIEW_CANVAS_WIDTH,
			slideHeight: PREVIEW_CANVAS_HEIGHT,
			...(scheme ? { scheme } : {}),
			idFor: (index) => `tpl-preview-${templateId}-${index}`,
		});
		return {
			elements: built.elements,
			backgroundColor: built.backgroundColor ?? '#FFFFFF',
		};
	});
}

// viewers/pptx/packages/react/src/viewer/components/SlideTemplatePreview.tsx
/**
 * SlideTemplatePreview: live-rendered miniature of a slide template.
 *
 * Mirrors the SmartArt gallery pattern: build the exact elements insertion
 * would produce (shared `buildSlideTemplateContent`) at full canvas size,
 * render them through the real StaticElementRenderer, and scale the stage
 * down with a CSS transform so the preview is pixel-faithful.
 */
import type { PptxSlide } from 'pptx-viewer-core';
import { buildSlideTemplateContent } from 'ooxml-ui/pptx';
import type { SlideTemplateId } from 'ooxml-ui/pptx';
import React, { useMemo } from 'react';

import { StaticElementRenderer } from './StaticElementRenderer';

/** Full-size stage the template is built at (standard 16:9 canvas). */
const PREVIEW_CANVAS_WIDTH = 1280;
const PREVIEW_CANVAS_HEIGHT = 720;
/** Rendered tile width in px. */
const PREVIEW_TILE_WIDTH = 144;
const PREVIEW_SCALE = PREVIEW_TILE_WIDTH / PREVIEW_CANVAS_WIDTH;
const PREVIEW_TILE_HEIGHT = Math.round(PREVIEW_CANVAS_HEIGHT * PREVIEW_SCALE);

export interface SlideTemplatePreviewProps {
	templateId: SlideTemplateId;
	/** Optional deck scheme so the preview shows the deck's theme colours. */
	scheme?: Record<string, string>;
}

export function SlideTemplatePreview({
	templateId,
	scheme,
}: SlideTemplatePreviewProps): React.ReactElement {
	const previewSlide: PptxSlide = useMemo(() => {
		const content = buildSlideTemplateContent(templateId, {
			slideWidth: PREVIEW_CANVAS_WIDTH,
			slideHeight: PREVIEW_CANVAS_HEIGHT,
			...(scheme ? { scheme } : {}),
			idFor: (index) => `tpl-preview-${templateId}-${index}`,
		});
		return {
			id: `tpl-preview-${templateId}`,
			rId: '',
			slideNumber: 1,
			elements: content.elements,
			...(content.backgroundColor ? { backgroundColor: content.backgroundColor } : {}),
		};
	}, [templateId, scheme]);

	return (
		<div
			aria-hidden='true'
			className='overflow-hidden pointer-events-none rounded'
			style={{
				width: PREVIEW_TILE_WIDTH,
				height: PREVIEW_TILE_HEIGHT,
				backgroundColor: previewSlide.backgroundColor ?? '#FFFFFF',
			}}
		>
			<div
				style={{
					position: 'relative',
					width: PREVIEW_CANVAS_WIDTH,
					height: PREVIEW_CANVAS_HEIGHT,
					transform: `scale(${PREVIEW_SCALE})`,
					transformOrigin: 'top left',
				}}
			>
				{previewSlide.elements.map((element, index) => (
					<StaticElementRenderer
						key={element.id}
						element={element}
						activeSlide={previewSlide}
						allSlides={[previewSlide]}
						zIndex={index}
					/>
				))}
			</div>
		</div>
	);
}
