// viewers/pptx/packages/vue/src/viewer/components/ribbon/LayoutGalleryMenu.vue
<script setup lang="ts">
/**
 * LayoutGalleryMenu: the grid of layout thumbnails shared by the New Slide and
 * Layout menus. Vue port of React's `toolbar/LayoutGalleryMenu.tsx`.
 *
 * Both menus previously listed layout names as plain text, which is not enough
 * to tell "Title and Content" from "Two Content" in a themed deck.
 */
import type { PptxLayoutOption, PptxLayoutPreview, PptxSlide } from 'pptx-viewer-core';
import { buildLayoutPreviewGeometry, isCurrentLayout } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import SlideStage from '../SlideStage.vue';
import { vAnchoredPopup } from './anchored-popup';

/** Thumbnail box size, matching PowerPoint's gallery tiles. */
const THUMB_WIDTH = 128;
const THUMB_HEIGHT = 72;

/** Cap on artwork drawn per thumbnail; layouts never legitimately exceed this. */
const MAX_PREVIEW_ELEMENTS = 100;

const props = defineProps<{
	layoutOptions: PptxLayoutOption[];
	/** Artwork by layout path; tiles stay name-only until it arrives. */
	previews: ReadonlyMap<string, PptxLayoutPreview>;
	/** Marks the active tile. Omitted by New Slide, which has no "current". */
	currentLayoutPath?: string;
	/** The trigger button this menu hangs below (position: fixed anchor; see `anchored-popup.ts`). */
	anchor?: HTMLElement | null;
}>();

const emit = defineEmits<{ (event: 'select', layout: PptxLayoutOption): void }>();

const { t } = useI18n();

/** No media in a layout thumbnail; images arrive already decoded as data URLs. */
const EMPTY_MEDIA = new Map<string, string>();

const tiles = computed(() =>
	props.layoutOptions.map((layout) => {
		const preview = props.previews.get(layout.path);
		const geometry = buildLayoutPreviewGeometry(preview, THUMB_WIDTH, THUMB_HEIGHT);
		const slide: PptxSlide = {
			id: `layout-preview-${layout.path}`,
			rId: '',
			slideNumber: 0,
			elements: (preview?.elements ?? []).slice(0, MAX_PREVIEW_ELEMENTS),
			backgroundColor: geometry.backgroundColor,
		};
		return {
			layout,
			geometry,
			slide,
			canvasSize: { width: geometry.surfaceWidth, height: geometry.surfaceHeight },
			isCurrent: isCurrentLayout(layout, props.currentLayoutPath),
		};
	}),
);
</script>

<template>
	<div
		class="z-50 flex flex-col w-[620px] pt-1"
		data-testid="layout-gallery-menu"
		v-anchored-popup="{ anchor: props.anchor }"
	>
		<div
			class="grid grid-cols-4 gap-2 rounded-lg border border-border bg-popover backdrop-blur-lg shadow-2xl p-3 max-h-[520px] overflow-y-auto"
		>
			<p v-if="tiles.length === 0" class="col-span-4 px-2 py-3 text-xs text-muted-foreground">
				{{ t('pptx.layoutGallery.empty') }}
			</p>
			<button
				v-for="tile in tiles"
				:key="tile.layout.path"
				type="button"
				:aria-current="tile.isCurrent ? 'true' : undefined"
				:title="
					tile.isCurrent
						? `${tile.layout.name} (${t('pptx.layoutGallery.current')})`
						: tile.layout.name
				"
				:class="
					cn(
						'relative flex min-w-0 flex-col items-center gap-1 rounded border-2 p-1 text-xs text-foreground transition-colors hover:bg-muted',
						tile.isCurrent ? 'border-primary bg-primary/10' : 'border-transparent',
					)
				"
				@click="emit('select', tile.layout)"
			>
				<div
					class="relative shrink-0 overflow-hidden rounded-sm border border-border/70 shadow-sm"
					:style="{
						width: `${tile.geometry.boxWidth}px`,
						height: `${tile.geometry.boxHeight}px`,
						backgroundColor: tile.geometry.backgroundColor,
					}"
				>
					<SlideStage
						:slide="tile.slide"
						:canvas-size="tile.canvasSize"
						:media-data-urls="EMPTY_MEDIA"
						:scale="tile.geometry.scale"
					/>
					<!-- Placeholder outlines sit inside the scaled surface, so their
					     border width is pre-divided by the scale to stay visible. -->
					<div
						class="absolute left-0 top-0 origin-top-left"
						:style="{
							width: `${tile.geometry.surfaceWidth}px`,
							height: `${tile.geometry.surfaceHeight}px`,
							transform: `scale(${tile.geometry.scale})`,
						}"
					>
						<div
							v-for="frame in tile.geometry.frames"
							:key="frame.key"
							class="absolute border-dashed border-muted-foreground/70 bg-background/20"
							:style="{
								left: `${frame.left}px`,
								top: `${frame.top}px`,
								width: `${frame.width}px`,
								height: `${frame.height}px`,
								borderWidth: `${tile.geometry.frameBorderWidth}px`,
								borderStyle: 'dashed',
							}"
						/>
					</div>
				</div>
				<span class="w-full truncate text-center">{{ tile.layout.name }}</span>
			</button>
		</div>
	</div>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/ribbon/home/LayoutGalleryMenu.svelte
<script lang="ts">
	/**
	 * LayoutGalleryMenu: the grid of layout thumbnails shared by the New Slide
	 * and Layout menus. Svelte port of React's `toolbar/LayoutGalleryMenu.tsx`.
	 *
	 * Both menus previously listed layout names as plain text, which is not
	 * enough to tell "Title and Content" from "Two Content" in a themed deck.
	 */
	import type { PptxLayoutOption, PptxLayoutPreview, PptxSlide } from 'pptx-viewer-core';
	import { buildLayoutPreviewGeometry, isCurrentLayout } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../../i18n/context';
	import SlideStage from '../../SlideStage.svelte';

	/** Thumbnail box size, matching PowerPoint's gallery tiles. */
	const THUMB_WIDTH = 128;
	const THUMB_HEIGHT = 72;

	/** Cap on artwork drawn per thumbnail; layouts never legitimately exceed this. */
	const MAX_PREVIEW_ELEMENTS = 100;

	/** No media in a layout thumbnail; images arrive already decoded. */
	const EMPTY_MEDIA = new Map<string, string>();

	const {
		layouts,
		previews,
		currentLayoutPath,
		onselect,
	}: {
		layouts: readonly PptxLayoutOption[];
		previews: ReadonlyMap<string, PptxLayoutPreview>;
		currentLayoutPath?: string;
		onselect: (layout: PptxLayoutOption) => void;
	} = $props();

	const t = useTranslator();

	const tiles = $derived(
		layouts.map((layout) => {
			const preview = previews.get(layout.path);
			const geometry = buildLayoutPreviewGeometry(preview, THUMB_WIDTH, THUMB_HEIGHT);
			const slide: PptxSlide = {
				id: `layout-preview-${layout.path}`,
				rId: '',
				slideNumber: 0,
				elements: (preview?.elements ?? []).slice(0, MAX_PREVIEW_ELEMENTS),
				backgroundColor: geometry.backgroundColor,
			};
			return {
				layout,
				geometry,
				slide,
				canvasSize: { width: geometry.surfaceWidth, height: geometry.surfaceHeight },
				current: isCurrentLayout(layout, currentLayoutPath),
			};
		}),
	);
</script>

<div class="pptx-svelte-lgal" data-testid="layout-gallery-menu">
	{#if tiles.length === 0}
		<span class="pptx-svelte-lgal-empty">{t('pptx.layoutGallery.empty')}</span>
	{:else}
		{#each tiles as tile (tile.layout.path)}
			<button
				type="button"
				role="menuitem"
				class="pptx-svelte-lgal-tile"
				class:pptx-svelte-lgal-current={tile.current}
				aria-current={tile.current ? 'true' : undefined}
				title={tile.current
					? `${tile.layout.name} (${t('pptx.layoutGallery.current')})`
					: tile.layout.name}
				onclick={() => onselect(tile.layout)}
			>
				<div
					class="pptx-svelte-lgal-thumb"
					style:width={`${tile.geometry.boxWidth}px`}
					style:height={`${tile.geometry.boxHeight}px`}
					style:background-color={tile.geometry.backgroundColor}
				>
					<SlideStage
						slide={tile.slide}
						canvasSize={tile.canvasSize}
						mediaDataUrls={EMPTY_MEDIA}
						scale={tile.geometry.scale}
					/>
					<!-- Placeholder outlines sit inside the scaled surface, so their
					     border width is pre-divided by the scale to stay visible. -->
					<div
						class="pptx-svelte-lgal-frames"
						style:width={`${tile.geometry.surfaceWidth}px`}
						style:height={`${tile.geometry.surfaceHeight}px`}
						style:transform={`scale(${tile.geometry.scale})`}
					>
						{#each tile.geometry.frames as frame (frame.key)}
							<div
								class="pptx-svelte-lgal-frame"
								style:left={`${frame.left}px`}
								style:top={`${frame.top}px`}
								style:width={`${frame.width}px`}
								style:height={`${frame.height}px`}
								style:border-width={`${tile.geometry.frameBorderWidth}px`}
							></div>
						{/each}
					</div>
				</div>
				<span class="pptx-svelte-lgal-name">{tile.layout.name}</span>
			</button>
		{/each}
	{/if}
</div>

<style>
	.pptx-svelte-lgal {
		display: grid;
		grid-template-columns: repeat(4, minmax(0, 1fr));
		gap: 8px;
		width: 620px;
		max-height: 520px;
		overflow-y: auto;
		padding: 12px;
	}

	.pptx-svelte-lgal-empty {
		grid-column: 1 / -1;
		padding: 8px;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 11px;
	}

	.pptx-svelte-lgal-tile {
		display: flex;
		min-width: 0;
		flex-direction: column;
		align-items: center;
		gap: 4px;
		border: 2px solid transparent;
		border-radius: var(--pptx-radius, 6px);
		background: transparent;
		color: inherit;
		padding: 4px;
		font: inherit;
		font-size: 11px;
		cursor: pointer;
	}

	.pptx-svelte-lgal-tile:hover {
		background: var(--pptx-accent, #33334d);
	}

	.pptx-svelte-lgal-current {
		border-color: var(--pptx-primary, #2563eb);
		background: color-mix(in srgb, var(--pptx-primary, #2563eb) 12%, transparent);
	}

	.pptx-svelte-lgal-thumb {
		position: relative;
		flex: none;
		overflow: hidden;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: 2px;
	}

	.pptx-svelte-lgal-frames {
		position: absolute;
		left: 0;
		top: 0;
		transform-origin: top left;
	}

	.pptx-svelte-lgal-frame {
		position: absolute;
		border-style: dashed;
		border-color: color-mix(in srgb, var(--pptx-muted-foreground, #94a3b8) 70%, transparent);
		background: color-mix(in srgb, var(--pptx-background, #0f172a) 20%, transparent);
	}

	.pptx-svelte-lgal-name {
		width: 100%;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		text-align: center;
	}
</style>
