// viewers/pptx/packages/react/src/viewer/components/SlideTemplateGalleryDialog.tsx
/**
 * SlideTemplateGalleryDialog: the New Slide template gallery.
 *
 * Presents the shared slide-template catalogue as a grid of live-rendered
 * previews. Single click selects, double click or the Insert button inserts
 * the template after the current slide via the caller's history-integrated
 * insert path.
 */
import { SLIDE_TEMPLATES } from 'ooxml-ui/pptx';
import type { SlideTemplateId } from 'ooxml-ui/pptx';
import React, { useCallback, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { LuX } from 'react-icons/lu';

import { useModalDismissDrag } from '../hooks';
import { useModalFocus } from '../hooks/useModalFocus';
import { cn } from '../utils';
import { DialogFooter } from './DialogFooter';
import { SlideTemplatePreview } from './SlideTemplatePreview';

export interface SlideTemplateGalleryDialogProps {
	isOpen: boolean;
	onClose: () => void;
	onInsert: (templateId: SlideTemplateId) => void;
	/** Optional deck scheme so previews show the deck's theme colours. */
	scheme?: Record<string, string>;
}

export function SlideTemplateGalleryDialog({
	isOpen,
	onClose,
	onInsert,
	scheme,
}: SlideTemplateGalleryDialogProps): React.ReactElement | null {
	const { t } = useTranslation();
	const { panelStyle, handlers: dragHandlers } = useModalDismissDrag(onClose);
	const [selected, setSelected] = useState<SlideTemplateId | null>(null);
	const dialogRef = useRef<HTMLDivElement>(null);
	useModalFocus(isOpen, dialogRef, onClose);

	const handleInsert = useCallback(() => {
		if (!selected) {
			return;
		}
		onInsert(selected);
		onClose();
	}, [selected, onInsert, onClose]);

	if (!isOpen) {
		return null;
	}

	return (
		<>
			<button
				type='button'
				style={{ zIndex: 1200 }}
				className='fixed inset-0 bg-black/50'
				onClick={onClose}
				aria-label={t('pptx.slideTemplates.close')}
			/>

			<div
				style={{ zIndex: 1201 }}
				className='fixed inset-0 flex items-center justify-center pointer-events-none'
			>
				<div
					ref={dialogRef}
					style={panelStyle}
					className='pointer-events-auto w-[640px] max-w-[92vw] max-h-[80vh] rounded-lg border border-border bg-background shadow-2xl flex flex-col max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:w-full max-md:max-w-none max-md:max-h-[88dvh] max-md:rounded-t-2xl max-md:rounded-b-none max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]'
					role='dialog'
					aria-modal='true'
					aria-label={t('pptx.slideTemplates.galleryTitle')}
					tabIndex={-1}
				>
					<div
						{...dragHandlers}
						className='flex items-center justify-between px-4 py-3 border-b border-border touch-none'
					>
						<div className='flex flex-col gap-0.5'>
							<h2 className='text-sm font-medium text-foreground'>
								{t('pptx.slideTemplates.galleryTitle')}
							</h2>
							<p className='text-[11px] text-muted-foreground'>
								{t('pptx.slideTemplates.galleryDescription')}
							</p>
						</div>
						<button
							type='button'
							onClick={onClose}
							className='p-1 rounded hover:bg-muted transition-colors'
							aria-label={t('pptx.slideTemplates.close')}
						>
							<LuX className='w-4 h-4' />
						</button>
					</div>

					<div className='flex-1 p-3 overflow-y-auto'>
						<div
							className='grid grid-cols-3 gap-2'
							role='listbox'
							aria-label={t('pptx.slideTemplates.gallery')}
						>
							{SLIDE_TEMPLATES.map((spec) => (
								<button
									key={spec.id}
									type='button'
									role='option'
									aria-selected={selected === spec.id}
									aria-label={t(spec.nameKey)}
									title={t(spec.descriptionKey)}
									onClick={() => setSelected(spec.id)}
									onDoubleClick={() => {
										onInsert(spec.id);
										onClose();
									}}
									className={cn(
										'flex flex-col items-center gap-1 p-2 rounded border transition-colors',
										selected === spec.id
											? 'border-primary bg-primary/20'
											: 'border-border hover:border-border hover:bg-muted/50',
									)}
								>
									<div className='flex items-center justify-center bg-muted rounded'>
										<SlideTemplatePreview templateId={spec.id} scheme={scheme} />
									</div>
									<span className='text-[10px] text-foreground text-center leading-tight'>
										{t(spec.nameKey)}
									</span>
								</button>
							))}
						</div>
					</div>

					<div className='flex items-center justify-end gap-2 px-4 py-3 border-t border-border'>
						<DialogFooter
							actions={[
								{ id: 'cancel', label: t('pptx.slideTemplates.cancel') },
								{
									id: 'insert',
									label: t('pptx.slideTemplates.insert'),
									variant: 'primary',
									disabled: !selected,
								},
							]}
							onAction={(id) => (id === 'insert' ? handleInsert() : onClose())}
						/>
					</div>
				</div>
			</div>
		</>
	);
}

// viewers/pptx/packages/svelte/src/viewer/components/ribbon/home/SlideTemplateGalleryDialog.svelte
<script lang="ts">
	/**
	 * SlideTemplateGalleryDialog: the Home > Slide Templates modal, mirroring
	 * React's `SlideTemplateGalleryDialog` and this binding's SmartArtDialog
	 * conventions. Presents the shared slide-template catalogue as a listbox
	 * grid of live previews: single click selects, double click or the Insert
	 * button inserts, Escape / backdrop / Cancel dismiss.
	 */
	import DialogFooter from '../../DialogFooter.svelte';
	import { SLIDE_TEMPLATES } from 'ooxml-ui/pptx';
	import type { SlideTemplateId } from 'ooxml-ui/pptx';
	import { onMount } from 'svelte';

	import { useTranslator } from '../../../../i18n/context';
	import SlideTemplatePreview from './SlideTemplatePreview.svelte';

	const {
		scheme,
		oncancel,
		oninsert,
	}: {
		/** Optional deck scheme so previews show the deck's theme colours. */
		scheme?: Record<string, string>;
		oncancel: () => void;
		oninsert: (templateId: SlideTemplateId) => void;
	} = $props();
	const t = useTranslator();

	let selected = $state<SlideTemplateId | null>(null);
	// eslint-disable-next-line prefer-const
	let panel = $state<HTMLDivElement>();

	onMount(() => panel?.focus());

	function insert(): void {
		if (selected) {
			oninsert(selected);
		}
	}

	function onWindowKeydown(event: KeyboardEvent): void {
		if (event.key === 'Escape') {
			event.preventDefault();
			event.stopPropagation();
			oncancel();
		}
	}
</script>

<svelte:window onkeydown={onWindowKeydown} />

<div class="pptx-svelte-slide-templates-host">
	<button
		type="button"
		class="pptx-svelte-slide-templates-backdrop"
		aria-label={t('pptx.slideTemplates.close')}
		onclick={oncancel}
	></button>
	<div
		bind:this={panel}
		class="pptx-svelte-slide-templates-dialog"
		role="dialog"
		aria-modal="true"
		aria-label={t('pptx.slideTemplates.galleryTitle')}
		tabindex="-1"
	>
		<header>
			<div class="pptx-svelte-slide-templates-heading">
				<h2>{t('pptx.slideTemplates.galleryTitle')}</h2>
				<p>{t('pptx.slideTemplates.galleryDescription')}</p>
			</div>
			<button
				type="button"
				class="pptx-svelte-slide-templates-close"
				aria-label={t('pptx.slideTemplates.close')}
				onclick={oncancel}
			>
				<svg viewBox="0 0 16 16" aria-hidden="true"><path d="m3 3 10 10M13 3 3 13" /></svg>
			</button>
		</header>

		<div class="pptx-svelte-slide-templates-scroll">
			<div
				class="pptx-svelte-slide-templates-grid"
				role="listbox"
				aria-label={t('pptx.slideTemplates.gallery')}
			>
				{#each SLIDE_TEMPLATES as spec (spec.id)}
					<button
						type="button"
						role="option"
						class="pptx-svelte-slide-templates-tile"
						class:is-selected={selected === spec.id}
						aria-selected={selected === spec.id}
						aria-label={t(spec.nameKey)}
						title={t(spec.descriptionKey)}
						onclick={() => (selected = spec.id)}
						ondblclick={() => oninsert(spec.id)}
					>
						<SlideTemplatePreview templateId={spec.id} {scheme} />
						<span>{t(spec.nameKey)}</span>
					</button>
				{/each}
			</div>
		</div>

		<footer><DialogFooter actions={[{ id: 'cancel', label: t('pptx.slideTemplates.cancel') }, { id: 'insert', label: t('pptx.slideTemplates.insert'), variant: 'primary', disabled: !selected }]} onaction={(id) => (id === 'insert' ? insert() : oncancel())} /></footer>
	</div>
</div>

<style>
	.pptx-svelte-slide-templates-host {
		position: fixed;
		z-index: 1200;
		inset: 0;
		display: grid;
		place-items: center;
		padding: 24px;
	}

	.pptx-svelte-slide-templates-backdrop {
		position: absolute;
		inset: 0;
		width: 100%;
		border: 0;
		background: rgb(0 0 0 / 50%);
	}

	.pptx-svelte-slide-templates-dialog {
		position: relative;
		display: flex;
		flex-direction: column;
		width: min(640px, 92vw);
		max-height: 80vh;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: calc(var(--pptx-radius, 6px) + 2px);
		outline: none;
		background: var(--pptx-background, #11111b);
		box-shadow: 0 24px 70px rgb(0 0 0 / 48%);
		color: var(--pptx-foreground, #e2e8f0);
	}

	header,
	footer {
		display: flex;
		align-items: center;
		padding: 12px 16px;
	}

	header {
		justify-content: space-between;
		border-bottom: 1px solid var(--pptx-border, #33334d);
	}

	.pptx-svelte-slide-templates-heading {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.pptx-svelte-slide-templates-heading h2 {
		margin: 0;
		font-size: 14px;
		font-weight: 600;
	}

	.pptx-svelte-slide-templates-heading p {
		margin: 0;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 11px;
	}

	button {
		border: 0;
		border-radius: var(--pptx-radius, 6px);
		font: inherit;
	}

	.pptx-svelte-slide-templates-close {
		display: grid;
		place-items: center;
		width: 28px;
		height: 28px;
		background: transparent;
		color: inherit;
		cursor: pointer;
	}

	.pptx-svelte-slide-templates-close:hover,

	.pptx-svelte-slide-templates-close svg {
		width: 16px;
		height: 16px;
		fill: none;
		stroke: currentColor;
		stroke-width: 1.5;
	}

	.pptx-svelte-slide-templates-scroll {
		flex: 1 1 auto;
		min-height: 0;
		padding: 12px;
		overflow-y: auto;
	}

	.pptx-svelte-slide-templates-grid {
		display: grid;
		grid-template-columns: repeat(3, minmax(0, 1fr));
		gap: 8px;
	}

	.pptx-svelte-slide-templates-tile {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 4px;
		padding: 8px;
		border: 1px solid var(--pptx-border, #33334d);
		background: transparent;
		color: inherit;
		cursor: pointer;
		font-size: 10px;
		line-height: 1.2;
		text-align: center;
	}

	.pptx-svelte-slide-templates-tile:hover {
		background: color-mix(in srgb, var(--pptx-muted, #2a2a3d) 50%, transparent);
	}

	.pptx-svelte-slide-templates-tile.is-selected {
		border-color: var(--pptx-primary, #6366f1);
		background: color-mix(in srgb, var(--pptx-primary, #6366f1) 20%, transparent);
	}

	footer {
		justify-content: flex-end;
		gap: 8px;
		border-top: 1px solid var(--pptx-border, #33334d);
	}

	

	

	@media (max-width: 640px) {
		.pptx-svelte-slide-templates-host {
			align-items: end;
			padding: 0;
		}

		.pptx-svelte-slide-templates-dialog {
			width: 100%;
			max-height: 88dvh;
			border-radius: 16px 16px 0 0;
		}
	}
</style>
