// viewers/pptx/packages/vue/src/viewer/components/ribbon/SlidesGroup.vue
<script setup lang="ts">
/**
 * SlidesGroup: New Slide split button, Slide Templates, Layout (apply to
 * current), Reset and Section. All of it, including the layout thumbnail
 * galleries, is the shared `pptx-ui-ribbon-home-slides` element. The host only
 * draws each tile's real artwork (SlideStage, teleported into the tile so
 * provide/inject keeps working), loads the previews when a gallery opens, and
 * runs the edits. The Slide Templates dialog stays native.
 */
import type { PptxLayoutPreview, PptxSlide } from 'pptx-viewer-core';
import type {
	HomeLayoutArtwork,
	RibbonHomeLayoutModel,
	RibbonHomePopupEvent,
	RibbonHomeRequestEvent,
	SlideTemplateId,
} from 'ooxml-ui/pptx';
import { homeSnapshotTranslator, slidesHomeControls } from 'ooxml-ui/pptx';
import { computed, ref, shallowRef } from 'vue';
import { useI18n } from 'vue-i18n';

import SlideStage from '../SlideStage.vue';
import SlideTemplateGalleryDialog from '../SlideTemplateGalleryDialog.vue';
import type { LayoutOption } from './ribbon-types';

interface Props {
	canEdit: boolean;
	layoutOptions: LayoutOption[];
	/** Marks the active tile in the Layout menu. */
	currentLayoutPath?: string;
	/** Supplies gallery artwork; without it the menus stay name-only. */
	loadLayoutPreviews?: () => Promise<PptxLayoutPreview[]>;
	onInsertSlideFromLayout: (path: string, name?: string) => void;
	onInsertSlideFromTemplate?: (templateId: SlideTemplateId) => void;
	/** Deck scheme map so template previews show the deck's theme colours. */
	templateScheme?: Record<string, string>;
	onApplyLayout?: (path: string) => void;
	onResetSlide?: () => void;
	onAddSection?: () => void;
}

const props = defineProps<Props>();
const { t, locale } = useI18n();

/** Cap on artwork drawn per thumbnail; layouts never legitimately exceed this. */
const MAX_PREVIEW_ELEMENTS = 100;
/** No media in a layout thumbnail; images arrive already decoded as data URLs. */
const EMPTY_MEDIA = new Map<string, string>();

const previews = ref<ReadonlyMap<string, PptxLayoutPreview>>(new Map());
const layouts = computed<RibbonHomeLayoutModel>(() => ({
	layouts: props.layoutOptions,
	current: props.currentLayoutPath,
	previews: previews.value,
}));

const state = computed(() => ({
	controls: slidesHomeControls({
		editable: props.canEdit,
		hasLayouts: props.layoutOptions.length > 0,
		hasSlides: true,
		showTemplates: Boolean(props.onInsertSlideFromTemplate),
		newSlideNeedsLayout: true,
		resetNeedsSlide: false,
		layouts: layouts.value,
	}),
	// The locale is read so a language switch re-translates the shared labels.
	locale: locale.value,
	translate: homeSnapshotTranslator(['slides'], t),
}));

/** Tiles the shared gallery asked this host to fill with artwork. */
interface Artwork {
	key: number;
	container: HTMLElement;
	slide: PptxSlide;
	width: number;
	height: number;
	scale: number;
}
const artworks = shallowRef<Artwork[]>([]);
let nextKey = 0;
const drawArtwork: HomeLayoutArtwork = (preview, geometry, container) => {
	const entry: Artwork = {
		key: nextKey++,
		container,
		slide: {
			id: `layout-preview-${preview.path}`,
			rId: '',
			slideNumber: 0,
			elements: preview.elements.slice(0, MAX_PREVIEW_ELEMENTS),
			backgroundColor: geometry.backgroundColor,
		},
		width: geometry.surfaceWidth,
		height: geometry.surfaceHeight,
		scale: 1,
	};
	artworks.value = [...artworks.value, entry];
	return () => {
		artworks.value = artworks.value.filter((item) => item !== entry);
	};
};

/**
 * Layout artwork, fetched the first time either gallery opens: parsing every
 * layout part is only worth doing once the user asks to see the thumbnails.
 */
function onPopup(event: Event): void {
	const { open } = (event as RibbonHomePopupEvent).detail;
	const load = props.loadLayoutPreviews;
	if (!open || !load) {
		return;
	}
	void load()
		.then((loaded) => {
			previews.value = new Map(loaded.map((preview) => [preview.path, preview]));
			return undefined;
		})
		// A layout that will not parse costs the user a name-only tile, not a broken menu.
		.catch(() => undefined);
}

const templateGalleryOpen = ref(false);

function request(event: RibbonHomeRequestEvent): void {
	const { id, value } = event.detail;
	switch (id) {
		case 'home.slides.newSlide': {
			const layout =
				value === undefined
					? props.layoutOptions[0]
					: props.layoutOptions.find((option) => option.path === value);
			if (layout) {
				props.onInsertSlideFromLayout(layout.path, layout.name);
			}
			break;
		}
		case 'home.slides.slideTemplates':
			templateGalleryOpen.value = true;
			break;
		case 'home.slides.layout':
			props.onApplyLayout?.(String(value));
			break;
		case 'home.slides.reset':
			props.onResetSlide?.();
			break;
		case 'home.slides.section':
			props.onAddSection?.();
	}
}
</script>

<template>
	<pptx-ui-ribbon-home-slides
		:state.prop="state"
		:layoutArtwork.prop="drawArtwork"
		@home-request="request"
		@home-popup="onPopup"
	/>
	<Teleport v-for="art in artworks" :key="art.key" :to="art.container">
		<SlideStage
			:slide="art.slide"
			:canvas-size="{ width: art.width, height: art.height }"
			:media-data-urls="EMPTY_MEDIA"
			:scale="art.scale"
		/>
	</Teleport>
	<SlideTemplateGalleryDialog
		v-if="props.onInsertSlideFromTemplate"
		:open="templateGalleryOpen"
		:scheme="props.templateScheme"
		@insert="props.onInsertSlideFromTemplate?.($event)"
		@close="templateGalleryOpen = false"
	/>
</template>

// viewers/pptx/packages/svelte/src/viewer/components/ribbon/home/SlidesGroup.svelte
<script lang="ts">
	/**
	 * Home slide controls. Buttons, caption, gating and both layout galleries
	 * (New Slide's caret and Layout) are the shared `pptx-ui-ribbon-home-slides`
	 * element; this adapter loads the deck's layouts when a gallery opens, draws
	 * each layout's artwork through its own slide renderer, keeps the template
	 * gallery dialog and runs every edit so operations keep history and
	 * active-slide navigation.
	 */
	import type { PptxLayoutOption, PptxLayoutPreview } from 'pptx-viewer-core';
	import {
		homeSnapshotTranslator,
		scopeLayoutOptionsToSlide,
		slidesHomeControls,
	} from 'ooxml-ui/pptx';
	import type { PptxUiRibbonHomeElement, RibbonHomeRequestEvent } from 'ooxml-ui/pptx';
	import { useTranslator } from '../../../../i18n/context';
	import type { EditorState } from '../../../editor/editor-state.svelte';
	import { createLayoutArtwork } from './home-adapter';
	import SlideTemplatesLauncher from './SlideTemplatesLauncher.svelte';

	const { editor, onnavigate }: { editor: EditorState; onnavigate: (index: number) => void } =
		$props();
	const t = useTranslator();

	let templatesOpen = $state(false);
	let layouts = $state<PptxLayoutOption[]>([]);
	/** Artwork is fetched alongside the layout list, only once a gallery opens. */
	let previews = $state<ReadonlyMap<string, PptxLayoutPreview>>(new Map());
	const layoutArtwork = createLayoutArtwork();
	const currentLayoutPath = $derived(editor.slides[editor.currentSlideIndex]?.layoutPath);
	/** Scoped to the active slide's own master; dedupes same-named layouts across masters. */
	const scopedLayouts = $derived(scopeLayoutOptionsToSlide(layouts, currentLayoutPath));

	// The layout list loads lazily on opening, so the caret and Layout stay
	// available; Reset has no slide requirement but Section needs a slide.
	const view = $derived({
		controls: {
			...slidesHomeControls({
				editable: editor.editable,
				hasLayouts: true,
				hasSlides: editor.slides.length > 0,
				showTemplates: true,
				newSlideNeedsLayout: false,
				resetNeedsSlide: false,
				layouts: {
					layouts: scopedLayouts.map(({ path, name }) => ({ path, name })),
					current: currentLayoutPath,
					previews,
				},
			}),
			'home.slides.section': { disabled: !editor.editable || editor.slides.length === 0 },
		},
		translate: homeSnapshotTranslator(['slides'], t),
	});

	function go(index: number | null): void {
		if (index !== null) {
			onnavigate(index);
		}
	}
	async function load(): Promise<void> {
		layouts = await editor.slidesOps.availableLayouts();
		previews = await editor.slidesOps.layoutPreviews();
	}
	function popup(event: Event): void {
		const { id, open } = (event as CustomEvent<{ id: string; open: boolean }>).detail;
		if (open && (id === 'home.slides.newSlide' || id === 'home.slides.layout')) {
			void load();
		}
	}
	function request(event: RibbonHomeRequestEvent): void {
		const { id, value } = event.detail;
		switch (id) {
			case 'home.slides.newSlide':
				if (value === undefined) {
					go(editor.slidesOps.insertSlideAfterCurrent());
				} else {
					const name = layouts.find((layout) => layout.path === value)?.name;
					go(editor.slidesOps.insertSlideFromLayout(String(value), name));
				}
				break;
			case 'home.slides.slideTemplates':
				templatesOpen = true;
				break;
			case 'home.slides.layout':
				void editor.slidesOps.applyLayout(String(value)).then(go);
				break;
			case 'home.slides.reset':
				void editor.slidesOps.resetSlide().then(go);
				break;
			case 'home.slides.section':
				editor.sectionOps.add(t('pptx.sections.defaultName'));
		}
	}
	// eslint-disable-next-line prefer-const
	let strip: PptxUiRibbonHomeElement | undefined = $state();
	$effect(() => {
		if (strip) {
			strip.layoutArtwork = layoutArtwork;
		}
	});
</script>

<div class="pptx-svelte-rgroup">
	<pptx-ui-ribbon-home-slides
		bind:this={strip}
		state={view}
		onhome-request={request}
		onhome-popup={popup}
	></pptx-ui-ribbon-home-slides>
	<SlideTemplatesLauncher {editor} {onnavigate} bind:open={templatesOpen} />
</div>

<style>
	.pptx-svelte-rgroup {
		display: contents;
	}
</style>
