// viewers/pptx/packages/vue/src/viewer/components/ai/AiChatPanel.vue
<script setup lang="ts">
/**
 * AiChatPanel: the right-hand AI assistant pane. Loaded via
 * `defineAsyncComponent` from `PowerPointViewer.vue`, so its
 * `pptx-viewer-shared/ai` runtime imports only load when the panel is first
 * opened.
 *
 * The panel is a thin shell: it builds/guards the session via {@link useAiChat}
 * and, once ready, delegates the whole conversation to {@link AiConversation}.
 * `AiConversation` resolves the optional `@ai-sdk/vue` peer itself with a
 * top-level `await import(...)` (see its doc), which makes it an async-setup
 * component; the `<Suspense>` below is required so Vue has somewhere to mount
 * it once that import resolves.
 */
import { LoaderCircle, Sparkles, TriangleAlert, X } from 'lucide-vue-next';
import type { PptxAiBridge, PptxAiConfig } from 'ooxml-ui/pptx/ai';
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { useAiChat } from '../../composables/ai/useAiChat';
import type { AiPanelController } from '../../composables/ai/useAiPanelController';
import { useAiPanelController } from '../../composables/ai/useAiPanelController';
import AiConversation from './AiConversation.vue';

const props = defineProps<{
	bridge: PptxAiBridge;
	config: PptxAiConfig;
	panelWidth?: number;
	/**
	 * Focus / pick / live-tool controller owned by `PowerPointViewer` (it reads
	 * the live canvas selection). When the panel is mounted standalone (tests), a
	 * self-contained fallback controller keeps the focus bar functional.
	 */
	aiPanel?: AiPanelController;
}>();
const emit = defineEmits<{ (e: 'close'): void }>();
const { t } = useI18n();

const { state, session, initError } = useAiChat(props.bridge, props.config);
const panelStyle = computed(() =>
	props.panelWidth ? { width: `${props.panelWidth}px` } : undefined,
);

// Fall back to a standalone controller (empty selection) when the host does not
// supply one, so the panel renders its focus bar in isolation too.
const fallbackPanel = useAiPanelController({
	activeSlideIndex: ref(0),
	selectedElementIds: ref<string[]>([]),
	selectedElement: () => null,
});
const panel = computed<AiPanelController>(() => props.aiPanel ?? fallbackPanel);
</script>

<template>
	<div
		data-pptx-ai-panel=""
		class="absolute right-0 top-0 z-30 flex h-full w-80 flex-col border-l border-border bg-card shadow-xl max-md:inset-x-0 max-md:top-auto max-md:bottom-0 max-md:h-[75dvh] max-md:w-full max-md:rounded-t-2xl max-md:border-l-0 max-md:border-t max-md:shadow-2xl"
		:style="panelStyle"
	>
		<div class="flex items-center gap-2 border-b border-border px-3 py-2">
			<Sparkles class="w-4 h-4 text-primary" />
			<span class="text-sm font-semibold text-foreground">{{ t('pptx.ai.title') }}</span>
			<button
				type="button"
				:title="t('pptx.ai.close')"
				:aria-label="t('pptx.ai.close')"
				class="ml-auto flex items-center justify-center rounded-sm p-1 text-muted-foreground transition-colors hover:bg-accent max-md:min-w-[44px]! max-md:min-h-[44px]!"
				@click="emit('close')"
			>
				<X class="w-4 h-4" />
			</button>
		</div>

		<div
			v-if="state === 'checking'"
			class="flex flex-1 flex-col items-center justify-center gap-2 text-muted-foreground"
		>
			<LoaderCircle class="w-5 h-5 animate-spin" />
		</div>

		<div
			v-else-if="state === 'unavailable' || state === 'error'"
			class="flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center"
		>
			<TriangleAlert class="w-6 h-6 text-muted-foreground" />
			<p class="text-sm font-medium text-foreground">{{ t('pptx.ai.unavailableTitle') }}</p>
			<p class="text-[12px] text-muted-foreground">
				{{ initError?.message ?? t('pptx.ai.unavailableHint') }}
			</p>
		</div>

		<Suspense v-else-if="state === 'ready' && session">
			<AiConversation
				:session="session"
				:config="props.config"
				:bridge="props.bridge"
				:ai-panel="panel"
			/>
			<template #fallback>
				<div class="flex flex-1 flex-col items-center justify-center gap-2 text-muted-foreground">
					<LoaderCircle class="w-5 h-5 animate-spin" />
				</div>
			</template>
		</Suspense>
	</div>
</template>

// viewers/pptx/packages/react/src/viewer/components/ai/AiChatPanel.tsx
/**
 * AiChatPanel: the right-hand AI assistant pane. Default-exported so it can be
 * `React.lazy`-loaded (its `pptx-viewer-shared/ai` runtime imports only load
 * when the panel is first opened).
 *
 * `useChat` is a prop, not a static `@ai-sdk/react` import: see the doc on
 * {@link UseChatFn} / `AiChatPanelLazy` for why.
 *
 * The panel is a thin shell: it builds/guards the session via {@link useAiChat}
 * and, once ready, delegates the whole conversation to {@link AiConversation}.
 */
import type { PptxAiBridge, PptxAiConfig } from 'ooxml-ui/pptx/ai';
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { LuLoaderCircle, LuSparkles, LuTriangleAlert, LuX } from 'react-icons/lu';

import { deckIdFromBridge } from '../../hooks/ai/ai-deck-id';
import { useAiChat } from '../../hooks/ai/useAiChat';
import type { UseChatFn } from '../../hooks/ai/useAiConversation';
import type { AiPanelController } from '../../hooks/ai/useAiPanelController';
import { AiConversation } from './AiConversation';

export interface AiChatPanelProps {
	/** `@ai-sdk/react`'s `useChat`, resolved by `AiChatPanelLazy`'s lazy factory. */
	useChat: UseChatFn;
	bridge: PptxAiBridge;
	config: PptxAiConfig;
	aiPanel: AiPanelController;
	onClose: () => void;
	panelWidth?: number;
}

export default function AiChatPanel({
	useChat,
	bridge,
	config,
	aiPanel,
	onClose,
	panelWidth,
}: AiChatPanelProps) {
	const { t } = useTranslation();
	const { state, session, initError } = useAiChat(bridge, config);
	const deckId = useMemo(() => deckIdFromBridge(bridge), [bridge]);

	return (
		<div
			data-pptx-ai-panel=''
			// Desktop: right-edge side panel. Mobile (max-md): a bottom sheet, not a
			// full-screen overlay - a full-height panel covered the whole canvas so
			// AI-created/selected elements could not be tapped ("breaks the clicking
			// flow"). Matches the app's other mobile panels (theme editor etc.), so
			// the top of the canvas stays visible and interactive above the sheet.
			className='absolute right-0 top-0 z-30 flex h-full w-80 flex-col border-l border-border bg-card shadow-xl max-md:inset-x-0 max-md:top-auto max-md:bottom-0 max-md:h-[75dvh] max-md:w-full max-md:rounded-t-2xl max-md:border-l-0 max-md:border-t max-md:shadow-2xl'
			style={panelWidth ? { width: panelWidth } : undefined}
		>
			<div className='flex items-center gap-2 border-b border-border px-3 py-2'>
				<LuSparkles className='w-4 h-4 text-primary' />
				<span className='text-sm font-semibold text-foreground'>{t('pptx.ai.title')}</span>
				<button
					type='button'
					onClick={onClose}
					title={t('pptx.ai.close')}
					aria-label={t('pptx.ai.close')}
					className='ml-auto rounded-sm p-1 text-muted-foreground transition-colors hover:bg-accent max-md:min-w-[44px]! max-md:min-h-[44px]! flex items-center justify-center'
				>
					<LuX className='w-4 h-4' />
				</button>
			</div>

			{state === 'checking' && (
				<div className='flex flex-1 flex-col items-center justify-center gap-2 text-muted-foreground'>
					<LuLoaderCircle className='w-5 h-5 animate-spin' />
				</div>
			)}

			{(state === 'unavailable' || state === 'error') && (
				<div className='flex flex-1 flex-col items-center justify-center gap-2 px-6 text-center'>
					<LuTriangleAlert className='w-6 h-6 text-muted-foreground' />
					<p className='text-sm font-medium text-foreground'>{t('pptx.ai.unavailableTitle')}</p>
					<p className='text-[12px] text-muted-foreground'>
						{initError?.message ?? t('pptx.ai.unavailableHint')}
					</p>
				</div>
			)}

			{state === 'ready' && session && (
				<AiConversation
					useChat={useChat}
					session={session}
					config={config}
					bridge={bridge}
					aiPanel={aiPanel}
					deckId={deckId}
				/>
			)}
		</div>
	);
}
