// viewers/pptx/packages/svelte/src/viewer/components/ai/AiProposalCard.svelte
<script lang="ts">
	/**
	 * AiProposalCard: a single staged, not-yet-applied change the assistant is
	 * suggesting. Reads like a human suggestion: a clear title, a plain-language
	 * description of what will happen (via `humanizeDiffLine`), and friendly Apply
	 * / Discard buttons. The full description is shown (never truncated); long
	 * lists scroll rather than clip. The accept/reject callbacks route through the
	 * proposal store.
	 */
	import Check from '@lucide/svelte/icons/check';
	import X from '@lucide/svelte/icons/x';
	import { humanizeDiffLine } from 'ooxml-ui/pptx/ai';
	import type { ProposalView } from 'ooxml-ui/pptx/ai';

	import { useTranslator } from '../../../i18n/context';

	const {
		proposal,
		onaccept,
		onreject,
	}: {
		proposal: ProposalView;
		onaccept: (id: string) => void;
		onreject: (id: string) => void;
	} = $props();

	const t = useTranslator();

	const lines = $derived(proposal.summary.map(humanizeDiffLine));
</script>

<div class="pptx-svelte-ai-proposal" data-proposal-id={proposal.id}>
	<div class="pptx-svelte-ai-proposal-tag">{t('pptx.ai.proposedChange')}</div>
	<div class="pptx-svelte-ai-proposal-label">{proposal.label}</div>
	{#if lines.length > 0}
		<ul class="pptx-svelte-ai-proposal-summary">
			{#each lines as line, i (i)}
				<li>{line}</li>
			{/each}
		</ul>
	{/if}
	<div class="pptx-svelte-ai-proposal-actions">
		<button
			type="button"
			class="pptx-svelte-ai-proposal-btn is-accept"
			onclick={() => onaccept(proposal.id)}
		>
			<Check size={13} aria-hidden="true" />
			{t('pptx.ai.accept')}
		</button>
		<button
			type="button"
			class="pptx-svelte-ai-proposal-btn is-reject"
			onclick={() => onreject(proposal.id)}
		>
			<X size={13} aria-hidden="true" />
			{t('pptx.ai.reject')}
		</button>
	</div>
</div>

<style>
	.pptx-svelte-ai-proposal {
		border: 1px solid color-mix(in srgb, var(--pptx-primary, #6366f1) 40%, transparent);
		border-radius: var(--pptx-radius, 6px);
		background: color-mix(in srgb, var(--pptx-primary, #6366f1) 6%, transparent);
		padding: 10px;
	}

	.pptx-svelte-ai-proposal-tag {
		margin-bottom: 6px;
		font-size: 10px;
		font-weight: 600;
		letter-spacing: 0.04em;
		text-transform: uppercase;
		color: var(--pptx-primary, #a5b4fc);
	}

	.pptx-svelte-ai-proposal-label {
		font-size: 12px;
		font-weight: 500;
		color: var(--pptx-card-foreground, #e2e8f0);
	}

	.pptx-svelte-ai-proposal-summary {
		margin: 4px 0 0;
		padding-left: 16px;
		list-style: disc;
		font-size: 11px;
		color: var(--pptx-muted-foreground, #94a3b8);
		max-height: 10rem;
		overflow-y: auto;
	}

	.pptx-svelte-ai-proposal-summary li {
		word-break: break-word;
	}

	.pptx-svelte-ai-proposal-actions {
		display: flex;
		align-items: center;
		gap: 8px;
		margin-top: 8px;
	}

	.pptx-svelte-ai-proposal-btn {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		padding: 4px 8px;
		border-radius: 3px;
		border: 1px solid transparent;
		font: inherit;
		font-size: 11px;
		font-weight: 500;
		cursor: pointer;
	}

	.pptx-svelte-ai-proposal-btn.is-accept {
		background: var(--pptx-primary, #6366f1);
		color: var(--pptx-primary-foreground, #fff);
	}

	.pptx-svelte-ai-proposal-btn.is-accept:hover {
		background: color-mix(in srgb, var(--pptx-primary, #6366f1) 90%, #000);
	}

	.pptx-svelte-ai-proposal-btn.is-reject {
		background: transparent;
		border-color: var(--pptx-border, #33334d);
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-ai-proposal-btn.is-reject:hover {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-accent-foreground, #f8fafc);
	}
</style>

// viewers/pptx/packages/react/src/viewer/components/ai/AiProposalCard.tsx
import type { ProposalView } from 'ooxml-ui/pptx/ai';
import { humanizeDiffLine } from 'ooxml-ui/pptx/ai';
/**
 * AiProposalCard: a single staged, not-yet-applied change the assistant is
 * suggesting. Reads like a human suggestion: a clear title, a plain-language
 * description of what will happen, and friendly Apply / Discard buttons. The
 * full description is shown (never truncated); long lists scroll rather than
 * clip. The accept/reject callbacks route through the proposal store.
 */
import { useTranslation } from 'react-i18next';
import { LuCheck, LuX } from 'react-icons/lu';

export interface AiProposalCardProps {
	proposal: ProposalView;
	onAccept: (id: string) => void;
	onReject: (id: string) => void;
}

export function AiProposalCard({ proposal, onAccept, onReject }: AiProposalCardProps) {
	const { t } = useTranslation();
	const lines = proposal.summary.map(humanizeDiffLine);

	return (
		<div className='rounded-md border border-primary/40 bg-primary/5 p-2.5'>
			<div className='mb-1.5 text-[11px] font-semibold uppercase tracking-wide text-primary'>
				{t('pptx.ai.proposedChange')}
			</div>
			<div className='text-[12px] font-medium text-foreground'>{proposal.label}</div>
			{lines.length > 0 && (
				<ul className='mt-1 max-h-40 space-y-0.5 overflow-y-auto text-[11px] text-muted-foreground'>
					{lines.map((line, i) => (
						<li key={i} className='break-words'>
							{line}
						</li>
					))}
				</ul>
			)}
			<div className='mt-2 flex items-center gap-2'>
				<button
					type='button'
					onClick={() => onAccept(proposal.id)}
					className='inline-flex items-center gap-1 rounded-sm bg-primary px-2 py-1 text-[11px] font-medium text-primary-foreground transition-colors hover:bg-primary/90'
				>
					<LuCheck className='w-3.5 h-3.5' />
					{t('pptx.ai.accept')}
				</button>
				<button
					type='button'
					onClick={() => onReject(proposal.id)}
					className='inline-flex items-center gap-1 rounded-sm border border-border px-2 py-1 text-[11px] text-muted-foreground transition-colors hover:bg-accent'
				>
					<LuX className='w-3.5 h-3.5' />
					{t('pptx.ai.reject')}
				</button>
			</div>
		</div>
	);
}
