// viewers/pptx/packages/vue/src/viewer/components/inspector/ChartComboTypeOptions.vue
<script setup lang="ts">
import type { PptxChartSeries, PptxChartType } from 'pptx-viewer-core';
import { COMBO_SERIES_TYPE_OPTIONS, COMBO_SUPPORTED_TYPES } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

/**
 * ChartComboTypeOptions: per-series chart-type override for combo charts.
 * Mirrors React's `ChartComboTypeOptions`. Emits `setSeriesType(index, type)`
 * where `null` reverts the series to the chart-level type.
 */
const props = defineProps<{
	chartType: PptxChartType;
	series: readonly PptxChartSeries[];
}>();

const emit = defineEmits<{
	setSeriesType: [index: number, seriesType: PptxChartType | null];
}>();

const { t } = useI18n();

const visible = computed(
	() => COMBO_SUPPORTED_TYPES.has(props.chartType) && props.series.length >= 2,
);

function onChange(event: Event, index: number): void {
	const value = (event.target as HTMLSelectElement).value;
	emit('setSeriesType', index, value === '' ? null : (value as PptxChartType));
}
</script>

<template>
	<div
		v-if="visible"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.comboTypes') }}
		</div>
		<div class="space-y-1.5">
			<div
				v-for="(s, i) in props.series"
				:key="`${s.name}-${i}`"
				class="flex items-center gap-2 text-[11px]"
			>
				<span class="flex-1 truncate" :title="s.name">{{ s.name }}</span>
				<pptx-ui-select
					class="pptx-vue-chart-input flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full"
					data-testid="chart-combo-type"
					:value="s.seriesChartType ?? ''"
					@change="onChange($event, i)"
				>
					<option v-for="opt in COMBO_SERIES_TYPE_OPTIONS" :key="opt.value" :value="opt.value">
						{{ t(opt.labelKey) }}
					</option>
				</pptx-ui-select>
			</div>
		</div>
	</div>
</template>

// viewers/pptx/packages/angular/src/viewer/chart-combo-type-options.component.ts
/**
 * chart-combo-type-options.component.ts: Per-series combo chart-type controls.
 *
 * Selector: `pptx-chart-combo-type-options`
 *
 * Mirrors React's `ChartComboTypeOptions.tsx`: for cartesian charts (and existing
 * combos) with 2+ series, each series gets a chart-type selector so it can be
 * plotted with a different type (e.g. a line series inside a bar chart). Routes
 * through the `setSeriesChartType` immutable wrapper and emits a new
 * `ChartPptxElement`.
 *
 * @module angular-viewer/chart-combo-type-options
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	input,
	output,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { ChartPptxElement, PptxChartSeries, PptxChartType } from 'pptx-viewer-core';

import { COMBO_SERIES_TYPE_OPTIONS, COMBO_SUPPORTED_TYPES } from 'ooxml-ui/pptx';
import { setSeriesChartType } from './chart-data-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { selectValue } from './chart-event-helpers';

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-chart-combo-type-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (supported()) {
			<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.comboTypes' | translate">
				<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.comboTypes' | translate }}</h4>
				<div class="pptx-chart-card__group">
					@for (s of series(); track $index; let i = $index) {
						<div class="pptx-chart-card__row">
							<span class="pptx-chart-card__name" [title]="s.name">{{ s.name }}</span>
							<pptx-ui-select
								class="pptx-chart-card__input"
								[disabled]="!canEdit()"
								[value]="s.seriesChartType ?? ''"
								(change)="onType(i, $event)"
							>
								@for (opt of typeOptions; track opt.value) {
									<option [value]="opt.value" [selected]="opt.value === (s.seriesChartType ?? '')">
										{{ opt.labelKey | translate }}
									</option>
								}
							</pptx-ui-select>
						</div>
					}
				</div>
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartComboTypeOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	protected readonly typeOptions = COMBO_SERIES_TYPE_OPTIONS;

	protected readonly series = computed<PptxChartSeries[]>(
		() => this.element().chartData?.series ?? [],
	);

	protected readonly supported = computed(() => {
		const type = this.element().chartData?.chartType as PptxChartType | undefined;
		return type !== undefined && COMBO_SUPPORTED_TYPES.has(type) && this.series().length >= 2;
	});

	protected onType(index: number, event: Event): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(
			setSeriesChartType(this.element(), index, value === '' ? null : (value as PptxChartType)),
		);
	}
}
