// viewers/pptx/packages/react/src/viewer/components/inspector/ChartTypeSelector.tsx
import type { PptxChartData, PptxChartType } from 'pptx-viewer-core';
import type { ChartTypeSelectValue } from 'ooxml-ui/pptx';
import { resolveDisplayedChartType } from 'ooxml-ui/pptx';
import { useTranslation } from 'react-i18next';

import { WebSelect } from '../WebControls';
import {
	CARD,
	CHART_TYPE_OPTIONS,
	GROUPING_OPTIONS,
	GROUPING_SUPPORTED_TYPES,
	HEADING,
	INPUT,
} from './chart-panel-constants';

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------
export interface ChartTypeSelectorProps {
	title: string | undefined;
	chartType: PptxChartType;
	/**
	 * Full chart data, used only to resolve the "Pareto" display type (see
	 * `resolveDisplayedChartType`): a Pareto chart is `chartType: 'histogram'`
	 * plus a `paretoLine`-layout series and has no `PptxChartType` of its own,
	 * so the picker cannot tell it apart from `chartType` alone.
	 */
	chartData: Pick<PptxChartData, 'chartType' | 'series'>;
	grouping: PptxChartData['grouping'] | undefined;
	seriesCount: number;
	categoryCount: number;
	canEdit: boolean;
	onUpdateChartData: (patch: Partial<PptxChartData>) => void;
	/** Commits an edited flat title, collapsing multi-run rich text to the dominant style. */
	onTitleChange: (text: string) => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export function ChartTypeSelector({
	title,
	chartType,
	chartData,
	grouping,
	seriesCount,
	categoryCount,
	canEdit,
	onUpdateChartData,
	onTitleChange,
}: ChartTypeSelectorProps) {
	const { t } = useTranslation();
	const supportsGrouping = GROUPING_SUPPORTED_TYPES.has(chartType);
	const displayedType: ChartTypeSelectValue = resolveDisplayedChartType(chartData);

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.chart.heading')}</div>
			<div className='text-[11px] text-muted-foreground mb-1'>
				{seriesCount} {t('pptx.chart.series')} &middot; {categoryCount} {t('pptx.chart.categories')}
			</div>

			{/* Title */}
			<label className='flex items-center gap-2 text-[11px]'>
				<span className='w-10 text-muted-foreground shrink-0'>{t('pptx.chart.title')}</span>
				<input
					type='text'
					disabled={!canEdit}
					className={INPUT}
					value={title ?? ''}
					onChange={(e) => onTitleChange(e.target.value)}
				/>
			</label>

			{/* Chart type selector */}
			<label className='flex items-center gap-2 text-[11px]'>
				<span className='w-10 text-muted-foreground shrink-0'>{t('pptx.chart.type')}</span>
				<WebSelect
					aria-label={t('pptx.chart.type')}
					disabled={!canEdit}
					className={INPUT}
					value={displayedType}
					onChange={(e) =>
						onUpdateChartData({
							chartType: e.target.value as PptxChartType,
						})
					}
				>
					{CHART_TYPE_OPTIONS.map((opt) => (
						<option key={opt.value} value={opt.value}>
							{t(opt.labelKey)}
						</option>
					))}
				</WebSelect>
			</label>

			{/* Grouping mode (bar/line/area only) */}
			{supportsGrouping && (
				<label className='flex items-center gap-2 text-[11px]'>
					<span className='w-10 text-muted-foreground shrink-0'>{t('pptx.chart.grouping')}</span>
					<WebSelect
						aria-label={t('pptx.chart.grouping')}
						disabled={!canEdit}
						className={INPUT}
						value={grouping ?? 'clustered'}
						onChange={(e) =>
							onUpdateChartData({
								grouping: e.target.value as PptxChartData['grouping'],
							})
						}
					>
						{GROUPING_OPTIONS.map((opt) => (
							<option key={opt.value} value={opt.value}>
								{t(opt.labelKey)}
							</option>
						))}
					</WebSelect>
				</label>
			)}
		</div>
	);
}

// viewers/pptx/packages/angular/src/viewer/chart-type-selector.component.ts
/**
 * chart-type-selector.component.ts: chart type / title / grouping inspector.
 *
 * Selector: `pptx-chart-type-selector`
 *
 * Angular port of the React `ChartTypeSelector`. Lets the user rename the
 * chart, change its type (routed through the shared `patchChartData`, which
 * clears grouping the new type doesn't support and adapts the category/series
 * shape via core's `chartDataChangeType`), and, for bar/line/area charts,
 * pick clustered/stacked/percent-stacked grouping. Every edit emits a
 * fully-updated element through `elementChange`, committed by the inspector
 * as one undoable history entry.
 */
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	input,
	output,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { ChartPptxElement, PptxChartData } from 'pptx-viewer-core';

import type { ChartTypeSelectValue } from 'ooxml-ui/pptx';
import {
	CHART_TYPE_OPTIONS,
	collapseChartTitleRunsForEdit,
	GROUPING_OPTIONS,
	GROUPING_SUPPORTED_TYPES,
	patchChartData,
	resolveDisplayedChartType,
} from 'ooxml-ui/pptx';
import { isSelectControl } from './control-event-targets';

/**
 * Apply an inspector patch (title/type/grouping) to a chart element, routing
 * it through the shared `patchChartData`. Exported standalone (rather than
 * kept private on the component) so it is directly testable without an
 * Angular TestBed, matching `action-settings-panel.component.ts`'s pattern.
 */
export function applyChartTypeSelectorPatch(
	element: ChartPptxElement,
	patch: Partial<PptxChartData>,
): ChartPptxElement | null {
	if (!element.chartData) {
		return null;
	}
	return { ...element, chartData: patchChartData(element.chartData, patch) };
}

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-chart-type-selector',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (data(); as chartData) {
			<div class="pptx-cts">
				<label class="pptx-cts__field">
					<span class="pptx-cts__lbl">{{ 'pptx.chart.title' | translate }}</span>
					<input
						type="text"
						class="pptx-cts__input"
						[disabled]="!canEdit()"
						[value]="chartData.title ?? ''"
						(change)="onTitle($event)"
					/>
				</label>

				<label class="pptx-cts__field">
					<span class="pptx-cts__lbl">{{ 'pptx.chart.type' | translate }}</span>
					<pptx-ui-select
						class="pptx-cts__input"
						[attr.aria-label]="'pptx.chart.type' | translate"
						[disabled]="!canEdit()"
						[value]="displayedType()"
						(change)="onType($event)"
					>
						@for (opt of typeOptions; track opt.value) {
							<option [value]="opt.value" [selected]="opt.value === displayedType()">
								{{ opt.labelKey | translate }}
							</option>
						}
					</pptx-ui-select>
				</label>

				@if (supportsGrouping()) {
					<label class="pptx-cts__field">
						<span class="pptx-cts__lbl">{{ 'pptx.chart.grouping' | translate }}</span>
						<pptx-ui-select
							class="pptx-cts__input"
							[attr.aria-label]="'pptx.chart.grouping' | translate"
							[disabled]="!canEdit()"
							[value]="chartData.grouping ?? 'clustered'"
							(change)="onGrouping($event)"
						>
							@for (opt of groupingOptions; track opt.value) {
								<option
									[value]="opt.value"
									[selected]="opt.value === (chartData.grouping ?? 'clustered')"
								>
									{{ opt.labelKey | translate }}
								</option>
							}
						</pptx-ui-select>
					</label>
				}
			</div>
		}
	`,
	styles: `
		.pptx-cts {
			display: flex;
			flex-direction: column;
			gap: 0.35rem;
		}
		.pptx-cts__field {
			display: flex;
			align-items: center;
			gap: 0.4rem;
			font-size: 11px;
		}
		.pptx-cts__lbl {
			flex: 0 0 auto;
			min-width: 2.5rem;
			color: var(--pptx-inspector-muted, #888);
		}
		.pptx-cts__input {
			flex: 1 1 auto;
			min-width: 0;
		}

		/*
		 * Touch target: matches MIN_TOUCH_TARGET_PX (44) from
		 * pptx-viewer-shared's render/responsive module.
		 */
		@media (max-width: 767px) {
			.pptx-cts__input {
				min-height: 44px;
			}
		}
	`,
})
export class ChartTypeSelectorComponent {
	/** The chart element being edited. */
	readonly element = input.required<ChartPptxElement>();
	/** Whether editing is enabled. */
	readonly canEdit = input<boolean>(true);
	/** Emits the fully-updated element after any edit. */
	readonly elementChange = output<ChartPptxElement>();

	protected readonly typeOptions = CHART_TYPE_OPTIONS;
	protected readonly groupingOptions = GROUPING_OPTIONS;

	protected readonly data = computed(() => this.element().chartData);
	protected readonly supportsGrouping = computed(() => {
		const chartType = this.data()?.chartType;
		return chartType !== undefined && GROUPING_SUPPORTED_TYPES.has(chartType);
	});
	/**
	 * The type shown as selected. "Pareto" has no `PptxChartType` of its own
	 * (docs/guide/limitations.md's ChartEx row): it is `chartType: 'histogram'`
	 * plus a `paretoLine`-layout series, so reading `chartType` raw would show
	 * "Histogram" for a chart the user picked "Pareto" for.
	 */
	protected readonly displayedType = computed<ChartTypeSelectValue | undefined>(() => {
		const data = this.data();
		return data ? resolveDisplayedChartType(data) : undefined;
	});

	protected onTitle(event: Event): void {
		const target = event.target;
		if (target instanceof HTMLInputElement) {
			// A multi-run title collapses to one run in its dominant style so an
			// edit does not leave another, now-stale run's text trailing the new
			// title; see `collapseChartTitleRunsForEdit`'s doc.
			this.emit(collapseChartTitleRunsForEdit(this.data(), target.value));
		}
	}

	protected onType(event: Event): void {
		const target = event.target;
		if (isSelectControl(target)) {
			this.emit({ chartType: target.value as PptxChartData['chartType'] });
		}
	}

	protected onGrouping(event: Event): void {
		const target = event.target;
		if (isSelectControl(target)) {
			this.emit({ grouping: target.value as PptxChartData['grouping'] });
		}
	}

	private emit(patch: Partial<PptxChartData>): void {
		const next = applyChartTypeSelectorPatch(this.element(), patch);
		if (next) {
			this.elementChange.emit(next);
		}
	}
}
