// viewers/pptx/packages/vue/src/viewer/components/inspector/ChartAxisStyleOptions.vue
<script setup lang="ts">
import type { PptxChartAxisFormatting } from 'pptx-viewer-core';
import { EDITABLE_AXIS_ROWS, GRIDLINE_DASH_OPTIONS } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { injectRecentColors } from '../../composables/recent-colors-context';
import type {
	ChartAxisTitleStyleEdit,
	ChartGridlineStyleEdit,
} from '../../composables/useChartEditing';

/**
 * ChartAxisStyleOptions: per-axis log scale, axis-title font styling, and
 * major/minor gridline line styling (colour/width/dash). Mirrors React's
 * `ChartAxisStyleOptions`. Routes through the SDK-op emits exposed by
 * `useChartEditing` (log scale / title style / gridline style).
 */
const props = defineProps<{
	axes: readonly PptxChartAxisFormatting[] | undefined;
}>();

const emit = defineEmits<{
	setLogScale: [
		axisType: PptxChartAxisFormatting['axisType'],
		opts: { enabled: boolean; base?: number },
	];
	setTitleStyle: [axisType: PptxChartAxisFormatting['axisType'], edit: ChartAxisTitleStyleEdit];
	setGridlineStyle: [
		axisType: PptxChartAxisFormatting['axisType'],
		which: 'major' | 'minor',
		edit: ChartGridlineStyleEdit,
	];
}>();

const { t } = useI18n();
const recentColors = injectRecentColors();

type AxisRow = (typeof EDITABLE_AXIS_ROWS)[number] & { axis: PptxChartAxisFormatting };

const rows = computed<AxisRow[]>(() =>
	EDITABLE_AXIS_ROWS.map((row) => ({
		...row,
		axis: props.axes?.find((a) => a.axisType === row.type),
	})).filter((row): row is AxisRow => Boolean(row.axis)),
);

function onLogToggle(event: Event, row: AxisRow): void {
	emit('setLogScale', row.type, {
		enabled: (event.target as HTMLInputElement).checked,
		base: row.axis.logBase,
	});
}

function onLogBase(event: Event, row: AxisRow): void {
	const num = Number.parseFloat((event.target as HTMLInputElement).value);
	if (Number.isFinite(num) && num > 1) {
		emit('setLogScale', row.type, { enabled: true, base: num });
	}
}

function onFontFamily(event: Event, row: AxisRow): void {
	emit('setTitleStyle', row.type, {
		fontFamily: (event.target as HTMLInputElement).value || null,
	});
}

function onFontSize(event: Event, row: AxisRow): void {
	const num = Number.parseFloat((event.target as HTMLInputElement).value);
	emit('setTitleStyle', row.type, { fontSize: Number.isFinite(num) ? num : null });
}

function onBold(event: Event, row: AxisRow): void {
	emit('setTitleStyle', row.type, { fontBold: (event.target as HTMLInputElement).checked });
}

function onColor(event: Event, row: AxisRow): void {
	emit('setTitleStyle', row.type, { fontColor: (event.target as HTMLInputElement).value });
}

function onColorCommit(event: Event): void {
	recentColors?.push((event.target as HTMLInputElement).value);
}

function gridSpPr(row: AxisRow, which: 'major' | 'minor') {
	return which === 'major' ? row.axis.majorGridlinesSpPr : row.axis.minorGridlinesSpPr;
}

function gridEnabled(row: AxisRow, which: 'major' | 'minor'): boolean {
	return Boolean(which === 'major' ? row.axis.majorGridlines : row.axis.minorGridlines);
}

function onGridColor(event: Event, row: AxisRow, which: 'major' | 'minor'): void {
	emit('setGridlineStyle', row.type, which, { color: (event.target as HTMLInputElement).value });
}

function onGridColorCommit(event: Event): void {
	recentColors?.push((event.target as HTMLInputElement).value);
}

function onGridWidth(event: Event, row: AxisRow, which: 'major' | 'minor'): void {
	const num = Number.parseFloat((event.target as HTMLInputElement).value);
	emit('setGridlineStyle', row.type, which, { width: Number.isFinite(num) ? num : null });
}

function onGridDash(event: Event, row: AxisRow, which: 'major' | 'minor'): void {
	emit('setGridlineStyle', row.type, which, {
		dashStyle: (event.target as HTMLSelectElement).value || null,
	});
}

const INPUT = 'flex-1 bg-muted border border-border rounded px-1.5 py-0.5 w-full';
const GRID_KINDS: ReadonlyArray<{ which: 'major' | 'minor'; labelKey: string }> = [
	{ which: 'major', labelKey: 'pptx.chart.majorGridlines' },
	{ which: 'minor', labelKey: 'pptx.chart.minorGridlines' },
];
</script>

<template>
	<div
		v-if="rows.length > 0"
		class="pptx-vue-chart-card rounded border border-border bg-card p-2 space-y-2"
	>
		<div class="pptx-vue-chart-heading text-[11px] uppercase tracking-wide text-muted-foreground">
			{{ t('pptx.chart.axisStyling') }}
		</div>
		<div v-for="row in rows" :key="row.type" class="space-y-1.5">
			<div class="text-[11px] font-medium">{{ t(row.labelKey) }}</div>
			<div class="space-y-1.5 ml-2">
				<div v-if="row.hasScale" class="flex items-center gap-2">
					<label class="flex items-center gap-2 cursor-pointer">
						<pptx-ui-checkbox
							data-testid="chart-axis-log-scale"
							:checked="row.axis.logScale ?? false"
							@change="onLogToggle($event, row)"
						/>
						<span class="text-[11px]">{{ t('pptx.chart.logScale') }}</span>
					</label>
					<input
						v-if="row.axis.logScale"
						type="number"
						min="2"
						data-testid="chart-axis-log-base"
						:title="t('pptx.chart.logBase')"
						class="w-16 bg-muted border border-border rounded px-1.5 py-0.5 text-[11px]"
						:value="row.axis.logBase ?? 10"
						@input="onLogBase($event, row)"
					/>
				</div>

				<div class="flex items-center gap-2 text-[11px]">
					<span class="w-12 text-muted-foreground shrink-0">{{ t('pptx.chart.titleFont') }}</span>
					<input
						type="text"
						:class="INPUT"
						data-testid="chart-axis-title-font"
						:placeholder="t('pptx.chart.auto')"
						:value="row.axis.fontFamily ?? ''"
						@input="onFontFamily($event, row)"
					/>
					<input
						type="number"
						min="4"
						max="96"
						data-testid="chart-axis-title-size"
						:title="t('pptx.chart.fontSize')"
						class="w-14 bg-muted border border-border rounded px-1.5 py-0.5"
						:value="row.axis.fontSize ?? ''"
						:placeholder="t('pptx.chart.auto')"
						@input="onFontSize($event, row)"
					/>
				</div>
				<div class="flex items-center gap-3 text-[11px]">
					<label class="flex items-center gap-1 cursor-pointer">
						<pptx-ui-checkbox
							data-testid="chart-axis-title-bold"
							:checked="row.axis.fontBold ?? false"
							@change="onBold($event, row)"
						/>
						<span>{{ t('pptx.chart.bold') }}</span>
					</label>
					<label class="flex items-center gap-1">
						<span class="text-muted-foreground">{{ t('pptx.chart.titleColor') }}</span>
						<input
							type="color"
							data-testid="chart-axis-title-color"
							class="h-6 w-8 cursor-pointer rounded border border-border bg-transparent"
							:value="row.axis.fontColor ?? '#000000'"
							@input="onColor($event, row)"
							@change="onColorCommit"
						/>
					</label>
				</div>

				<template v-for="kind in GRID_KINDS" :key="kind.which">
					<div v-if="gridEnabled(row, kind.which)" class="flex items-center gap-2 text-[11px]">
						<span class="w-12 text-muted-foreground shrink-0">{{ t(kind.labelKey) }}</span>
						<input
							type="color"
							data-testid="chart-gridline-color"
							:title="t('pptx.chart.gridlineColor')"
							class="h-6 w-8 cursor-pointer rounded border border-border bg-transparent"
							:value="gridSpPr(row, kind.which)?.strokeColor ?? '#d9d9d9'"
							@input="onGridColor($event, row, kind.which)"
							@change="onGridColorCommit"
						/>
						<input
							type="number"
							min="0.25"
							step="0.25"
							data-testid="chart-gridline-width"
							:title="t('pptx.chart.gridlineWidth')"
							class="w-14 bg-muted border border-border rounded px-1.5 py-0.5"
							:value="gridSpPr(row, kind.which)?.strokeWidth ?? ''"
							:placeholder="t('pptx.chart.auto')"
							@input="onGridWidth($event, row, kind.which)"
						/>
						<pptx-ui-select
							:class="INPUT"
							data-testid="chart-gridline-dash"
							:title="t('pptx.chart.gridlineDash')"
							:value="gridSpPr(row, kind.which)?.strokeDashStyle ?? ''"
							@change="onGridDash($event, row, kind.which)"
						>
							<option v-for="opt in GRIDLINE_DASH_OPTIONS" :key="opt.value" :value="opt.value">
								{{ t(opt.labelKey) }}
							</option>
						</pptx-ui-select>
					</div>
				</template>
			</div>
		</div>
	</div>
</template>

// viewers/pptx/packages/angular/src/viewer/chart-axis-style-options.component.ts
/**
 * chart-axis-style-options.component.ts: Per-axis log scaling, title font, and
 * gridline line styling. Selector: `pptx-chart-axis-style-options`.
 *
 * Mirrors React's `ChartAxisStyleOptions.tsx`: log scale (value/date axes)
 * with a base, axis-title font family/size/bold/colour, and major/minor
 * gridline colour/width/dash (shown only when enabled). Routes through
 * `setAxisLogScale` / `setAxisTitleStyle` / `setGridlineStyle`.
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	output,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type {
	ChartPptxElement,
	PptxChartAxisFormatting,
	PptxChartAxisType,
} from 'pptx-viewer-core';

import { GRIDLINE_DASH_OPTIONS } from 'ooxml-ui/pptx';
import { setAxisLogScale, setAxisTitleStyle, setGridlineStyle } from './chart-data-helpers';
import { CHART_EDITOR_STYLES } from './chart-editor-styles';
import { boolFromEvent, numFromEvent, selectValue, stringFromEvent } from './chart-event-helpers';
import { RecentColorsService } from './recent-colors.service';

interface AxisRow {
	type: PptxChartAxisType;
	labelKey: string;
	hasScale: boolean;
	axis: PptxChartAxisFormatting;
}

const AXIS_DEFS: ReadonlyArray<{ type: PptxChartAxisType; labelKey: string; hasScale: boolean }> = [
	{ type: 'valAx', labelKey: 'pptx.chart.valueAxis', hasScale: true },
	{ type: 'dateAx', labelKey: 'pptx.chart.dateAxis', hasScale: true },
	{ type: 'catAx', labelKey: 'pptx.chart.categoryAxis', hasScale: false },
];

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-chart-axis-style-options',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (rows().length > 0) {
			<section class="pptx-chart-card" [attr.aria-label]="'pptx.chart.axisStyling' | translate">
				<h4 class="pptx-chart-card__heading">{{ 'pptx.chart.axisStyling' | translate }}</h4>
				@for (row of rows(); track row.type) {
					<div class="pptx-chart-card__group">
						<div class="pptx-chart-card__subhead">{{ row.labelKey | translate }}</div>
						<div class="pptx-chart-card__group pptx-chart-card__group--indent">
							@if (row.hasScale) {
								<div class="pptx-chart-card__row">
									<label class="pptx-chart-card__check">
										<pptx-ui-checkbox
											[disabled]="!canEdit()"
											[checked]="row.axis.logScale ?? false"
											(change)="onLogScale(row.type, row.axis, $event)"
										></pptx-ui-checkbox>
										<span>{{ 'pptx.chart.logScale' | translate }}</span>
									</label>
									@if (row.axis.logScale) {
										<input
											type="number"
											min="2"
											class="pptx-chart-card__input pptx-chart-card__input--num"
											[title]="'pptx.chart.logBase' | translate"
											[disabled]="!canEdit()"
											[value]="row.axis.logBase ?? 10"
											(change)="onLogBase(row.type, $event)"
										/>
									}
								</div>
							}

							<div class="pptx-chart-card__row">
								<span class="pptx-chart-card__label">{{ 'pptx.chart.titleFont' | translate }}</span>
								<input
									type="text"
									class="pptx-chart-card__input"
									[placeholder]="'pptx.chart.auto' | translate"
									[disabled]="!canEdit()"
									[value]="row.axis.fontFamily ?? ''"
									(change)="onTitleFont(row.type, $event)"
								/>
								<input
									type="number"
									min="4"
									max="96"
									class="pptx-chart-card__input pptx-chart-card__input--num"
									[title]="'pptx.chart.fontSize' | translate"
									[placeholder]="'pptx.chart.auto' | translate"
									[disabled]="!canEdit()"
									[value]="row.axis.fontSize ?? ''"
									(change)="onTitleSize(row.type, $event)"
								/>
							</div>
							<div class="pptx-chart-card__row">
								<label class="pptx-chart-card__check">
									<pptx-ui-checkbox
										[disabled]="!canEdit()"
										[checked]="row.axis.fontBold ?? false"
										(change)="onTitleBold(row.type, $event)"
									></pptx-ui-checkbox>
									<span>{{ 'pptx.chart.bold' | translate }}</span>
								</label>
								<span class="pptx-chart-card__label">{{
									'pptx.chart.titleColor' | translate
								}}</span>
								<input
									type="color"
									class="pptx-chart-card__color"
									[disabled]="!canEdit()"
									[value]="row.axis.fontColor ?? '#000000'"
									(input)="onTitleColor(row.type, $event)"
									(change)="pushRecentColor($event)"
								/>
							</div>

							@for (which of gridlineKinds; track which) {
								@if (gridlineEnabled(row.axis, which)) {
									<div class="pptx-chart-card__row">
										<span class="pptx-chart-card__label">
											{{
												(which === 'major'
													? 'pptx.chart.majorGridlines'
													: 'pptx.chart.minorGridlines'
												) | translate
											}}
										</span>
										<input
											type="color"
											class="pptx-chart-card__color"
											[title]="'pptx.chart.gridlineColor' | translate"
											[disabled]="!canEdit()"
											[value]="gridlineSpPr(row.axis, which)?.strokeColor ?? '#d9d9d9'"
											(input)="onGridlineColor(row.type, which, $event)"
											(change)="pushRecentColor($event)"
										/>
										<input
											type="number"
											min="0.25"
											step="0.25"
											class="pptx-chart-card__input pptx-chart-card__input--num"
											[title]="'pptx.chart.gridlineWidth' | translate"
											[placeholder]="'pptx.chart.auto' | translate"
											[disabled]="!canEdit()"
											[value]="gridlineSpPr(row.axis, which)?.strokeWidth ?? ''"
											(change)="onGridlineWidth(row.type, which, $event)"
										/>
										<pptx-ui-select
											class="pptx-chart-card__input"
											[title]="'pptx.chart.gridlineDash' | translate"
											[disabled]="!canEdit()"
											[value]="gridDash(row.axis, which)"
											(change)="onGridlineDash(row.type, which, $event)"
										>
											@for (opt of dashOptions; track opt.value) {
												<option
													[value]="opt.value"
													[selected]="opt.value === gridDash(row.axis, which)"
												>
													{{ opt.labelKey | translate }}
												</option>
											}
										</pptx-ui-select>
									</div>
								}
							}
						</div>
					</div>
				}
			</section>
		}
	`,
	styles: CHART_EDITOR_STYLES,
})
export class ChartAxisStyleOptionsComponent {
	readonly element = input.required<ChartPptxElement>();
	readonly canEdit = input<boolean>(true);
	readonly elementChange = output<ChartPptxElement>();

	/** Optional: absent in a standalone unit test with no viewer-level DI tree. */
	private readonly recentColors = inject(RecentColorsService, { optional: true });

	protected readonly dashOptions = GRIDLINE_DASH_OPTIONS;
	protected readonly gridlineKinds = ['major', 'minor'] as const;

	/**
	 * Record the committed (native `change`, not the live-preview `input`)
	 * colour into the shared "Recent colours" list.
	 */
	protected pushRecentColor(event: Event): void {
		const value = stringFromEvent(event);
		if (value) {
			this.recentColors?.push(value);
		}
	}

	protected readonly rows = computed<AxisRow[]>(() => {
		const axes = this.element().chartData?.axes ?? [];
		const result: AxisRow[] = [];
		for (const def of AXIS_DEFS) {
			const axis = axes.find((a) => a.axisType === def.type);
			if (axis) {
				result.push({ ...def, axis });
			}
		}
		return result;
	});

	protected gridlineEnabled(axis: PptxChartAxisFormatting, which: 'major' | 'minor'): boolean {
		return which === 'major' ? (axis.majorGridlines ?? false) : (axis.minorGridlines ?? false);
	}

	protected gridlineSpPr(axis: PptxChartAxisFormatting, which: 'major' | 'minor') {
		return which === 'major' ? axis.majorGridlinesSpPr : axis.minorGridlinesSpPr;
	}

	protected gridDash(axis: PptxChartAxisFormatting, which: 'major' | 'minor'): string {
		return this.gridlineSpPr(axis, which)?.strokeDashStyle ?? '';
	}
	protected onLogScale(
		axisType: PptxChartAxisType,
		axis: PptxChartAxisFormatting,
		event: Event,
	): void {
		this.elementChange.emit(
			setAxisLogScale(this.element(), axisType, {
				enabled: boolFromEvent(event),
				base: axis.logBase,
			}),
		);
	}

	protected onLogBase(axisType: PptxChartAxisType, event: Event): void {
		const num = numFromEvent(event);
		if (typeof num !== 'number' || num <= 1) {
			return;
		}
		this.elementChange.emit(
			setAxisLogScale(this.element(), axisType, { enabled: true, base: num }),
		);
	}

	protected onTitleFont(axisType: PptxChartAxisType, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(
			setAxisTitleStyle(this.element(), axisType, { fontFamily: value || null }),
		);
	}

	protected onTitleSize(axisType: PptxChartAxisType, event: Event): void {
		const num = numFromEvent(event);
		if (num === undefined) {
			return;
		}
		this.elementChange.emit(setAxisTitleStyle(this.element(), axisType, { fontSize: num }));
	}

	protected onTitleBold(axisType: PptxChartAxisType, event: Event): void {
		this.elementChange.emit(
			setAxisTitleStyle(this.element(), axisType, { fontBold: boolFromEvent(event) }),
		);
	}

	protected onTitleColor(axisType: PptxChartAxisType, event: Event): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(setAxisTitleStyle(this.element(), axisType, { fontColor: value }));
	}

	protected onGridlineColor(
		axisType: PptxChartAxisType,
		which: 'major' | 'minor',
		event: Event,
	): void {
		const value = stringFromEvent(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(setGridlineStyle(this.element(), axisType, which, { color: value }));
	}

	protected onGridlineWidth(
		axisType: PptxChartAxisType,
		which: 'major' | 'minor',
		event: Event,
	): void {
		const num = numFromEvent(event);
		if (num === undefined) {
			return;
		}
		this.elementChange.emit(setGridlineStyle(this.element(), axisType, which, { width: num }));
	}

	protected onGridlineDash(
		axisType: PptxChartAxisType,
		which: 'major' | 'minor',
		event: Event,
	): void {
		const value = selectValue(event);
		if (value === null) {
			return;
		}
		this.elementChange.emit(
			setGridlineStyle(this.element(), axisType, which, { dashStyle: value || null }),
		);
	}
}
