// viewers/pptx/packages/vue/src/viewer/components/ConnectorRenderer.vue
<script setup lang="ts">
import {
	getLineGlowFilterCss,
	getLineShadowParams,
	markerPath,
	screenStrokeWidth,
} from 'ooxml-ui/pptx';
import type { ElementAnimationState } from 'ooxml-ui/pptx';
import type { ConnectorArrowType, PptxElement, TextSegment, TextStyle } from 'pptx-viewer-core';
import { hasShapeProperties, hasTextProperties } from 'pptx-viewer-core';
import type { CSSProperties } from 'vue';
import { computed } from 'vue';

import {
	connectorNeedsPath,
	getCompoundLineOffsets,
	getCompoundLineWidths,
	getConnectorPathGeometry,
} from '../composables/connector-routing';
import { DEFAULT_STROKE_COLOR } from '../constants';
import ConnectorTextOverlay from './ConnectorTextOverlay.vue';

/**
 * ConnectorRenderer: Vue port of the React `ConnectorElementRenderer`.
 *
 * Renders straight, bent, and curved connectors as an inline SVG spanning the
 * element's bounding box, with stroke colour/width/dash, start/end arrowheads,
 * and compound (double/triple) line support.
 *
 * Supported connector types:
 * - straightConnector1 / line  → simple <line> element
 * - bentConnector2/3/4/5       → orthogonal elbow path (L commands)
 * - curvedConnector2/3/4/5     → Bézier curve path (Q / C commands)
 * - compound lines (dbl/thickThin/thinThick/tri) → parallel offset strokes
 *
 * Flip is baked into the path geometry (not a CSS transform) so arrowheads
 * point the right way for both straight and multi-segment connectors.
 *
 * Connector labels (a non-empty `<p:txBody>` on the connector) render via the
 * {@link ConnectorTextOverlay} child, centred over the bounding box.
 *
 * Line-level shadow (`a:ln/a:outerShdw`) renders as an SVG `feDropShadow` on the
 * primary stroke; line glow (`a:ln/a:glow`) as a CSS `drop-shadow` filter on the
 * wrapper. Both reuse the shared visual-effects helpers.
 */
const props = defineProps<{
	element: PptxElement;
	zIndex: number;
	/**
	 * Native-animation playback state. When an active `p:animClr` colour animation
	 * targets the stroke (`animatesStroke`), the SVG stroke is painted `inherit` so
	 * the wrapper's animated `stroke` keyframes cascade into the line + arrowheads.
	 */
	animationState?: ElementAnimationState;
	/**
	 * Scoped `!important` CSS override for an active font-style emphasis effect
	 * (Bold Flash, Bold Reveal, Underline, Change Font Style/Size), built by the
	 * parent `ElementRenderer` (`buildTextStyleOverrideCss`) so the connector's
	 * own caption animates the same way a shape's text does.
	 */
	textStyleOverrideCss?: string;
}>();

const ss = computed(() =>
	hasShapeProperties(props.element) ? props.element.shapeStyle : undefined,
);

const strokeWidth = computed(() => Math.max(0, ss.value?.strokeWidth ?? 2));
const strokeColor = computed(() =>
	props.animationState?.animatesStroke
		? 'inherit'
		: (ss.value?.strokeColor ?? DEFAULT_STROKE_COLOR),
);
const strokeOpacity = computed(() => ss.value?.strokeOpacity ?? 1);

const dashArray = computed<string | undefined>(() => {
	const dash = ss.value?.strokeDash;
	const w = Math.max(strokeWidth.value, 1);
	if (!dash || dash === 'solid') {
		return undefined;
	}
	if (dash === 'dot' || dash === 'sysDot') {
		return `${w} ${w}`;
	}
	return `${w * 3} ${w}`;
});

const w = computed(() => Math.max(props.element.width, 1));
const h = computed(() => Math.max(props.element.height, 1));

// ── Compound line support ─────────────────────────────────────────────────────

const compoundLine = computed(() => ss.value?.compoundLine);

const compoundOffsets = computed(() =>
	getCompoundLineOffsets(compoundLine.value, strokeWidth.value),
);
const compoundWidths = computed(() => getCompoundLineWidths(compoundLine.value, strokeWidth.value));

// ── Path / geometry routing ───────────────────────────────────────────────────

/**
 * Whether this connector uses multi-segment routing (bent or curved).
 * When true we render a <path> instead of a <line>.
 */
const usePathRouting = computed(() => {
	const shapeType = hasShapeProperties(props.element) ? props.element.shapeType : undefined;
	return connectorNeedsPath(shapeType);
});

/**
 * SVG path geometry computed from the connector type, dimensions, flip flags,
 * and adjustment values.  Only used when `usePathRouting` is true.
 */
const pathGeometry = computed(() => {
	if (!usePathRouting.value) {
		return null;
	}
	const el = props.element;
	if (!hasShapeProperties(el)) {
		return null;
	}
	return getConnectorPathGeometry(el);
});

// Straight connector endpoints (used when !usePathRouting), mirrored by flips.
const x1 = computed(() => (props.element.flipHorizontal ? w.value : 0));
const y1 = computed(() => (props.element.flipVertical ? h.value : 0));
const x2 = computed(() => (props.element.flipHorizontal ? 0 : w.value));
const y2 = computed(() => (props.element.flipVertical ? 0 : h.value));

// ── Pointer hit target ────────────────────────────────────────────────────────

/**
 * WHY a separate invisible stroke: the wrapper is `pointer-events: none` (so a
 * connector's empty bounding box never swallows clicks meant for the shapes it
 * spans), which left the line itself unclickable too. No pointer route reached
 * a connector at all, so the inspector's connector card could only be opened
 * from the Elements list. React has always carried this transparent, generously
 * wide stroke that opts back INTO hit testing; `pointer-events: stroke` keeps
 * the target on the line and off the box.
 */
const hitTargetWidth = computed(() => Math.max(strokeWidth.value * 3, 14));

/** The routed path when the connector bends, else its straight endpoints. */
const hitPathData = computed(() =>
	usePathRouting.value && pathGeometry.value
		? pathGeometry.value.pathData
		: `M ${x1.value} ${y1.value} L ${x2.value} ${y2.value}`,
);

// ── Arrowheads ───────────────────────────────────────────────────────────────

const startArrow = computed(() => normalizeArrow(ss.value?.connectorStartArrow));
const endArrow = computed(() => normalizeArrow(ss.value?.connectorEndArrow));

function normalizeArrow(a: ConnectorArrowType | undefined): ConnectorArrowType | undefined {
	return a && a !== 'none' ? a : undefined;
}

/** Distinct, DOM-id-safe marker ids per element + side. */
const markerSeed = computed(() => props.element.id.replace(/[^a-zA-Z0-9_-]/gu, '_'));
const startMarkerId = computed(() => `${markerSeed.value}-start`);
const endMarkerId = computed(() => `${markerSeed.value}-end`);

// ── Wrapper style ─────────────────────────────────────────────────────────────

const wrapperStyle = computed<CSSProperties>(() => {
	const el = props.element;
	const style: CSSProperties = {
		position: 'absolute',
		left: `${el.x}px`,
		top: `${el.y}px`,
		width: `${el.width}px`,
		height: `${el.height}px`,
		zIndex: props.zIndex,
		pointerEvents: 'none',
		overflow: 'visible',
	};
	if (el.rotation) {
		// Flip is handled via path geometry, so only rotation goes on the transform.
		style.transform = `rotate(${el.rotation}deg)`;
	}
	if (typeof el.opacity === 'number') {
		style.opacity = el.opacity;
	}
	if (lineGlow.value) {
		style.filter = lineGlow.value;
	}
	if (el.hidden) {
		style.display = 'none';
	}
	return style;
});

// ── Marker shape helpers ──────────────────────────────────────────────────────

// Pass the `@w`/`@len` arrow size tokens so `sm`/`med`/`lg` heads scale; the
// returned MarkerShape carries the suggested `markerWidth` (length along the
// line) and `markerHeight` (perpendicular width) applied on the <marker> below.
const startMarker = computed(() =>
	startArrow.value
		? markerPath(
				startArrow.value,
				ss.value?.connectorStartArrowWidth,
				ss.value?.connectorStartArrowLength,
			)
		: null,
);
const endMarker = computed(() =>
	endArrow.value
		? markerPath(
				endArrow.value,
				ss.value?.connectorEndArrowWidth,
				ss.value?.connectorEndArrowLength,
			)
		: null,
);

// ── Line shadow / glow effects ─────────────────────────────────────────────────

/** Resolved line-shadow params (feDropShadow), or undefined when no shadow. */
const lineShadow = computed(() => getLineShadowParams(ss.value));
/** CSS `drop-shadow` filter for a line glow, applied to the wrapper. */
const lineGlow = computed(() => getLineGlowFilterCss(ss.value));
/** DOM-safe id for the shadow <filter>. */
const shadowFilterId = computed(() => `${markerSeed.value}-line-shadow`);

// ── Connector text label ───────────────────────────────────────────────────────

/** The element narrowed to its text properties, when it carries any. */
const textEl = computed(() => (hasTextProperties(props.element) ? props.element : undefined));

/** Trimmed plain-text label (empty when the connector has no text). */
const connectorText = computed(() => textEl.value?.text?.trim() ?? '');
/** Per-run styled text segments, when present. */
const connectorTextSegments = computed<readonly TextSegment[] | undefined>(
	() => textEl.value?.textSegments,
);
/** Paragraph-level text style (font/colour/alignment). */
const connectorTextStyle = computed<TextStyle | undefined>(() => textEl.value?.textStyle);

// ── Compound offset style helpers ─────────────────────────────────────────────

/**
 * Build the transform style string for a compound stroke at the given offset.
 * Returns undefined for offset === 0 (no transform needed).
 */
function offsetTransform(offset: number): string | undefined {
	if (offset === 0) {
		return undefined;
	}
	return `translate(0, ${offset}px)`;
}

/** Painted width of strand `idx`: floored at 1px, and at one device pixel on screen. */
function strandWidth(idx: number): number {
	return Math.max(compoundWidths.value[idx] ?? strokeWidth.value, 1);
}

/** Inline style of strand `idx` (shared `device-pixel-stroke`, plus its offset). */
function strandStyle(idx: number, offset: number): CSSProperties {
	return { strokeWidth: screenStrokeWidth(strandWidth(idx)), transform: offsetTransform(offset) };
}
</script>

<template>
	<div
		class="pptx-vue-element pptx-vue-connector"
		:style="wrapperStyle"
		:data-element-id="element.id"
	>
		<!--
			`<style>` is a forbidden side-effect tag in an SFC template, so the
			override is rendered through the dynamic `<component :is>` escape
			hatch instead (see `ElementRenderer.vue`).
		-->
		<component :is="'style'" v-if="textStyleOverrideCss">{{ textStyleOverrideCss }}</component>
		<svg
			:width="w"
			:height="h"
			:viewBox="`0 0 ${w} ${h}`"
			style="overflow: visible; display: block"
		>
			<defs>
				<marker
					v-if="startMarker"
					:id="startMarkerId"
					viewBox="0 0 10 10"
					refX="5"
					refY="5"
					:markerWidth="startMarker.markerWidth"
					:markerHeight="startMarker.markerHeight"
					orient="auto-start-reverse"
					markerUnits="strokeWidth"
				>
					<circle v-if="startMarker.shape === 'circle'" cx="5" cy="5" r="4" :fill="strokeColor" />
					<path
						v-else
						:d="startMarker.d"
						:fill="startMarker.strokeOnly ? 'none' : strokeColor"
						:stroke="startMarker.strokeOnly ? strokeColor : undefined"
					/>
				</marker>
				<marker
					v-if="endMarker"
					:id="endMarkerId"
					viewBox="0 0 10 10"
					refX="5"
					refY="5"
					:markerWidth="endMarker.markerWidth"
					:markerHeight="endMarker.markerHeight"
					orient="auto-start-reverse"
					markerUnits="strokeWidth"
				>
					<circle v-if="endMarker.shape === 'circle'" cx="5" cy="5" r="4" :fill="strokeColor" />
					<path
						v-else
						:d="endMarker.d"
						:fill="endMarker.strokeOnly ? 'none' : strokeColor"
						:stroke="endMarker.strokeOnly ? strokeColor : undefined"
					/>
				</marker>
				<filter v-if="lineShadow" :id="shadowFilterId" x="-50%" y="-50%" width="200%" height="200%">
					<feDropShadow
						:dx="lineShadow.offsetX"
						:dy="lineShadow.offsetY"
						:stdDeviation="lineShadow.blur / 2"
						:flood-color="lineShadow.color"
						:flood-opacity="lineShadow.opacity"
					/>
				</filter>
			</defs>

			<!-- Invisible click target: the only pointer-reachable part of a connector. -->
			<path
				class="pptx-vue-connector-hit"
				:d="hitPathData"
				fill="none"
				stroke="transparent"
				:stroke-width="hitTargetWidth"
				stroke-linecap="round"
				stroke-linejoin="round"
				style="pointer-events: stroke"
			/>

			<!-- ── Bent / curved connector: multi-segment <path> ─────────────────── -->
			<template v-if="usePathRouting && pathGeometry">
				<path
					v-for="(offset, idx) in compoundOffsets"
					:key="idx"
					:d="pathGeometry.pathData"
					fill="none"
					:stroke="strokeColor"
					:stroke-width="strandWidth(idx)"
					:stroke-opacity="strokeOpacity"
					:stroke-dasharray="dashArray"
					stroke-linecap="round"
					stroke-linejoin="round"
					:filter="idx === 0 && lineShadow ? `url(#${shadowFilterId})` : undefined"
					:style="strandStyle(idx, offset)"
					:marker-start="idx === 0 && startMarker ? `url(#${startMarkerId})` : undefined"
					:marker-end="
						idx === compoundOffsets.length - 1 && endMarker ? `url(#${endMarkerId})` : undefined
					"
				/>
			</template>

			<!-- ── Straight connector: simple <line> (or compound parallel lines) ─ -->
			<template v-else>
				<line
					v-for="(offset, idx) in compoundOffsets"
					:key="idx"
					:x1="x1"
					:y1="y1 + offset"
					:x2="x2"
					:y2="y2 + offset"
					:stroke="strokeColor"
					:stroke-width="strandWidth(idx)"
					:style="strandStyle(idx, 0)"
					:stroke-opacity="strokeOpacity"
					:stroke-dasharray="dashArray"
					stroke-linecap="round"
					:filter="idx === 0 && lineShadow ? `url(#${shadowFilterId})` : undefined"
					:marker-start="idx === 0 && startMarker ? `url(#${startMarkerId})` : undefined"
					:marker-end="
						idx === compoundOffsets.length - 1 && endMarker ? `url(#${endMarkerId})` : undefined
					"
				/>
			</template>
		</svg>

		<!-- Connector label, centred over the path (rendered above the SVG). -->
		<ConnectorTextOverlay
			v-if="connectorTextSegments"
			:text="connectorText"
			:segments="connectorTextSegments"
			:text-style="connectorTextStyle"
		/>
	</div>
</template>

// viewers/pptx/packages/angular/src/viewer/connector-renderer.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { getLineGlowFilterCss, getLineShadowParams, screenStrokeWidth } from 'ooxml-ui/pptx';
import type { ElementAnimationState } from 'ooxml-ui/pptx';
import { hasShapeProperties } from 'pptx-viewer-core';
import type { PptxElement, TextSegment, TextStyle } from 'pptx-viewer-core';

import { buildConnectorGeometry } from './connector-path';
import type { MarkerShape } from './connector-path';
import type { Rect } from './connector-routing';
import { ConnectorTextOverlayComponent } from './connector-text-overlay.component';
import { DynamicStyleComponent } from './dynamic-style.component';

/**
 * ConnectorRendererComponent: Angular port of the Vue `ConnectorRenderer.vue`
 * (and the React `ConnectorElementRenderer`, basic subset).
 *
 * Renders straight connectors/lines as an inline SVG spanning the element's
 * bounding box, with stroke colour/width/dash and start/end arrowheads. Flip
 * is baked into the endpoints (not a CSS transform) so arrowheads point the
 * right way.
 *
 * Renders straight (`<line>`), bent (elbow) and curved (Bézier) connectors via
 * `connector-path.ts`. When obstacle rects are supplied (`obstacles` input,
 * absolute slide coords), bent connectors are routed around them with an A*
 * orthogonal router. A connector's optional text label is painted on top via
 * `ConnectorTextOverlayComponent`.
 *
 * All path/style math lives in `connector-path.ts` / `connector-routing.ts`
 * (pure TS, no Angular dependency) so it can be unit-tested without TestBed.
 * Compound (double/triple) lines render as parallel strands and line caps map
 * from `a:ln/@cap`; both derive from the shared connector geometry.
 *
 * Line shadows use an SVG drop-shadow filter and line glow uses the shared
 * CSS filter builder, matching the other framework bindings.
 */
@Component({
	selector: 'pptx-connector-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [ConnectorTextOverlayComponent, DynamicStyleComponent],
	template: `
		<div
			class="pptx-ng-element pptx-ng-connector"
			[style]="wrapperStyle()"
			[attr.data-element-id]="elementIdAttr()"
			[attr.data-pptx-element]="interactive() || marked() ? 'true' : null"
		>
			<!-- A font-style emphasis effect (Bold Flash, Bold Reveal, Underline,
			     Change Font Style/Size) overrides the caption's own inline
			     bold/italic/underline/size, which plain CSS inheritance cannot
			     reach. See animation-text-style-css.ts. -->
			<pptx-dynamic-style [css]="textStyleOverrideCss()" />
			<svg
				[attr.width]="geo().svgW"
				[attr.height]="geo().svgH"
				[attr.viewBox]="viewBox()"
				style="overflow: visible; display: block"
			>
				<defs>
					@if (geo().startMarker) {
						<marker
							[attr.id]="geo().startMarkerId"
							viewBox="0 0 10 10"
							refX="5"
							refY="5"
							[attr.markerWidth]="geo().startMarker!.markerWidth"
							[attr.markerHeight]="geo().startMarker!.markerHeight"
							orient="auto-start-reverse"
							markerUnits="strokeWidth"
						>
							@if (geo().startMarker!.shape === 'circle') {
								<circle cx="5" cy="5" r="4" [attr.fill]="strokeColor()" />
							} @else {
								<path [attr.d]="geo().startMarker!.d" [attr.fill]="strokeColor()" />
							}
						</marker>
					}
					@if (geo().endMarker) {
						<marker
							[attr.id]="geo().endMarkerId"
							viewBox="0 0 10 10"
							refX="5"
							refY="5"
							[attr.markerWidth]="geo().endMarker!.markerWidth"
							[attr.markerHeight]="geo().endMarker!.markerHeight"
							orient="auto-start-reverse"
							markerUnits="strokeWidth"
						>
							@if (geo().endMarker!.shape === 'circle') {
								<circle cx="5" cy="5" r="4" [attr.fill]="strokeColor()" />
							} @else {
								<path [attr.d]="geo().endMarker!.d" [attr.fill]="strokeColor()" />
							}
						</marker>
					}
					@if (lineShadow(); as shadow) {
						<filter [attr.id]="shadowFilterId()" x="-50%" y="-50%" width="200%" height="200%">
							<feDropShadow
								[attr.dx]="shadow.offsetX"
								[attr.dy]="shadow.offsetY"
								[attr.stdDeviation]="shadow.blur / 2"
								[attr.flood-color]="shadow.color"
								[attr.flood-opacity]="shadow.opacity"
							/>
						</filter>
					}
				</defs>
				<!--
					The only pointer-reachable part of a connector: a transparent stroke
					along the line that opts back into hit testing. The wrapper is
					pointer-events:none so a connector's mostly-empty bounding box never
					swallows clicks meant for the shapes it spans, which left the line
					itself unclickable until this path existed.
				-->
				<path
					class="pptx-ng-connector-hit"
					[attr.d]="geo().hitPathD"
					fill="none"
					stroke="transparent"
					[attr.stroke-width]="geo().hitStrokeWidth"
					stroke-linecap="round"
					stroke-linejoin="round"
					style="pointer-events: stroke"
				/>
				@for (strand of strands(); track strand.key) {
					@if (geo().pathD) {
						<path
							[attr.d]="geo().pathD"
							fill="none"
							[attr.stroke]="strokeColor()"
							[attr.stroke-width]="strand.width"
							[style.stroke-width]="strand.cssWidth"
							[attr.stroke-opacity]="geo().strokeOpacity"
							[attr.stroke-dasharray]="geo().dashArray ?? null"
							[attr.stroke-linecap]="geo().strokeLinecap"
							stroke-linejoin="round"
							[attr.transform]="strand.transform"
							[attr.filter]="strand.shadowFilter"
							[attr.marker-start]="strand.markerStart"
							[attr.marker-end]="strand.markerEnd"
						/>
					} @else {
						<line
							[attr.x1]="geo().x1"
							[attr.y1]="geo().y1"
							[attr.x2]="geo().x2"
							[attr.y2]="geo().y2"
							[attr.stroke]="strokeColor()"
							[attr.stroke-width]="strand.width"
							[style.stroke-width]="strand.cssWidth"
							[attr.stroke-opacity]="geo().strokeOpacity"
							[attr.stroke-dasharray]="geo().dashArray ?? null"
							[attr.stroke-linecap]="geo().strokeLinecap"
							[attr.transform]="strand.transform"
							[attr.filter]="strand.shadowFilter"
							[attr.marker-start]="strand.markerStart"
							[attr.marker-end]="strand.markerEnd"
						/>
					}
				}
			</svg>
			<pptx-connector-text-overlay
				[text]="connectorText()"
				[segments]="connectorSegments()"
				[textStyle]="connectorTextStyle()"
			/>
		</div>
	`,
})
export class ConnectorRendererComponent {
	readonly element = input.required<PptxElement>();
	readonly zIndex = input<number>(0);
	/** Obstacle rects (absolute slide coords) for A* routing of bent connectors. */
	readonly obstacles = input<readonly Rect[]>([]);
	readonly canvasWidth = input<number>(0);
	readonly canvasHeight = input<number>(0);
	/** See ElementRenderer.interactive: gates the data-pptx-element contract attr. */
	readonly interactive = input<boolean>(true);
	/** Keep the data-pptx-element marker on interaction-locked template elements. */
	readonly marked = input<boolean>(false);
	/**
	 * When true (default), the rendered node carries `data-element-id`. The
	 * miniature surfaces that paint every slide at once turn it off so one
	 * element id resolves to exactly one node in the document; see
	 * `ElementRendererComponent.exposeElementId`.
	 */
	readonly exposeElementId = input<boolean>(true);

	/** `data-element-id` for this element, or null on a miniature surface. */
	readonly elementIdAttr = computed<string | null>(() =>
		this.exposeElementId() ? this.element().id : null,
	);

	/**
	 * Native-animation playback state. When an active `p:animClr` colour animation
	 * targets the stroke (`animatesStroke`), the SVG stroke + arrowheads paint
	 * `inherit` so the wrapper's animated `stroke` keyframes cascade in. Absent
	 * outside a running presentation.
	 */
	readonly animationState = input<ElementAnimationState | undefined>(undefined);

	/**
	 * Scoped `!important` CSS override for an active font-style emphasis effect
	 * (Bold Flash, Bold Reveal, Underline, Change Font Style/Size), built by the
	 * parent `ElementRendererComponent` (`buildTextStyleOverrideCss`) so a
	 * connector's own caption animates the same way a shape's text does.
	 */
	readonly textStyleOverrideCss = input<string | undefined>(undefined);

	/** All derived geometry, recomputed on every input change. */
	readonly geo = computed(() => {
		const obstacles = this.obstacles();
		const routing =
			obstacles.length > 0
				? { obstacles, canvasWidth: this.canvasWidth(), canvasHeight: this.canvasHeight() }
				: undefined;
		return buildConnectorGeometry(this.element(), this.zIndex(), routing);
	});

	readonly viewBox = computed(() => `0 0 ${this.geo().svgW} ${this.geo().svgH}`);
	/**
	 * Stroke paint for the line + arrowheads: `inherit` while a `p:animClr` stroke
	 * colour animation is active (so the wrapper keyframes own it), else the
	 * geometry's resolved stroke colour.
	 */
	readonly strokeColor = computed(() =>
		this.animationState()?.animatesStroke ? 'inherit' : this.geo().strokeColor,
	);
	private readonly shapeStyle = computed(() => {
		const element = this.element();
		return hasShapeProperties(element) ? element.shapeStyle : undefined;
	});
	readonly lineShadow = computed(() => getLineShadowParams(this.shapeStyle()));
	readonly lineGlow = computed(() => getLineGlowFilterCss(this.shapeStyle()));
	readonly shadowFilterId = computed(
		() => `${this.geo().startMarkerId.replace(/-start$/u, '')}-line-shadow`,
	);
	readonly wrapperStyle = computed(() => {
		const glow = this.lineGlow();
		return glow ? `${this.geo().wrapperStyle};filter:${glow}` : this.geo().wrapperStyle;
	});

	/**
	 * Parallel strokes for compound (double/triple) line styles. A single line
	 * yields one strand at offset 0. Each strand carries its own width and is
	 * translated perpendicular to the line; only the first strand paints the
	 * start marker and only the last paints the end marker.
	 */
	readonly strands = computed<ConnectorStrand[]>(() => {
		const g = this.geo();
		const offsets = g.compoundOffsets;
		const last = offsets.length - 1;
		return offsets.map((offset, idx) => ({
			key: idx,
			width: Math.max(g.compoundWidths[idx] ?? g.strokeWidth, 1),
			cssWidth: screenStrokeWidth(Math.max(g.compoundWidths[idx] ?? g.strokeWidth, 1)),
			transform: offset !== 0 ? `translate(0 ${offset})` : null,
			shadowFilter: idx === 0 && this.lineShadow() ? `url(#${this.shadowFilterId()})` : null,
			markerStart: idx === 0 ? g.startMarkerRef : null,
			markerEnd: idx === last ? g.endMarkerRef : null,
		}));
	});

	// Connectors carry an optional text label (PptxTextProperties). Narrow the
	// union once here so the template can bind the overlay inputs.
	private readonly textProps = computed(
		() => this.element() as { text?: string; textSegments?: TextSegment[]; textStyle?: TextStyle },
	);
	readonly connectorText = computed(() => this.textProps().text);
	readonly connectorSegments = computed(() => this.textProps().textSegments);
	readonly connectorTextStyle = computed(() => this.textProps().textStyle);
}

/** One parallel stroke of a (possibly compound) connector line. */
interface ConnectorStrand {
	key: number;
	width: number;
	/** `width` as the on-screen CSS width: never under one device pixel. */
	cssWidth: string;
	transform: string | null;
	shadowFilter: string | null;
	markerStart: string | null;
	markerEnd: string | null;
}

// Re-export the MarkerShape type so consumers can reference it if needed.
export type { MarkerShape };
