// viewers/pptx/packages/vue/src/viewer/components/inspector/EffectSoundRow.vue
<script setup lang="ts">
import { Play } from 'lucide-vue-next';
import { EFFECT_SOUND_CATALOGUE, getEffectSoundAsset } from 'ooxml-ui/pptx';
import type { EffectSoundState } from 'ooxml-ui/pptx';
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { playAnimationSound } from '../../composables/animation-sound';

const NONE_VALUE = 'none';
const CURRENT_VALUE = 'current';
const OTHER_VALUE = 'other';

const props = defineProps<{
	soundState: EffectSoundState;
}>();
const emit = defineEmits<{
	pick: [pick: { dataUrl: string; fileName?: string } | undefined];
	pickStock: [catalogueId: string];
}>();
const { t } = useI18n();

const fileInput = ref<HTMLInputElement | null>(null);

function selectedValue(): string {
	return props.soundState.catalogueId ?? (props.soundState.hasSound ? CURRENT_VALUE : NONE_VALUE);
}

function onSelectChange(event: Event): void {
	const value = (event.target as HTMLSelectElement).value;
	if (value === OTHER_VALUE) {
		fileInput.value?.click();
		return;
	}
	if (value === NONE_VALUE) {
		emit('pick', undefined);
		return;
	}
	if (value === CURRENT_VALUE) {
		return;
	}
	emit('pickStock', value);
}

function onFileChange(event: Event): void {
	const input = event.target as HTMLInputElement;
	const file = input.files?.[0];
	input.value = '';
	if (!file) {
		return;
	}
	const reader = new FileReader();
	reader.onload = () => {
		if (typeof reader.result === 'string') {
			emit('pick', { dataUrl: reader.result, fileName: file.name });
		}
	};
	reader.readAsDataURL(file);
}

function onPreview(): void {
	if (!props.soundState.catalogueId) {
		return;
	}
	const asset = getEffectSoundAsset(props.soundState.catalogueId);
	if (asset) {
		playAnimationSound(asset.dataUrl);
	}
}
</script>

<template>
	<label
		>{{ t('pptx.animation.sound') }}
		<div class="pptx-vue-sound-row">
			<pptx-ui-select
				:aria-label="t('pptx.animation.sound')"
				:value="selectedValue()"
				@change="onSelectChange"
			>
				<option :value="NONE_VALUE">{{ t('pptx.animation.sound.none') }}</option>
				<option v-if="soundState.hasSound && !soundState.catalogueId" :value="CURRENT_VALUE">
					{{ soundState.fileName ?? t('pptx.animation.sound.custom') }}
				</option>
				<option v-for="entry in EFFECT_SOUND_CATALOGUE" :key="entry.id" :value="entry.id">
					{{ t(entry.i18nKey) }}
				</option>
				<option :value="OTHER_VALUE">{{ t('pptx.animation.sound.other') }}</option>
			</pptx-ui-select>
			<button
				type="button"
				:aria-label="t('pptx.animation.sound.preview')"
				:disabled="!soundState.catalogueId"
				class="pptx-vue-sound-preview"
				@click="onPreview"
			>
				<Play :size="12" />
			</button>
		</div>
		<input
			ref="fileInput"
			type="file"
			accept="audio/*"
			:aria-label="t('pptx.animation.sound.chooseFile')"
			class="pptx-vue-hidden-file-input"
			tabindex="-1"
			@change="onFileChange"
		/>
	</label>
</template>

<style scoped>
.pptx-vue-hidden-file-input {
	display: none;
}
.pptx-vue-sound-row {
	display: flex;
	align-items: center;
	gap: 4px;
}
.pptx-vue-sound-preview {
	flex-shrink: 0;
}
.pptx-vue-sound-preview:disabled {
	opacity: 0.4;
}
</style>

// viewers/pptx/packages/angular/src/viewer/effect-sound-row.component.ts
/**
 * effect-sound-row.component.ts: the animation panel's effect sound row.
 *
 * PowerPoint's own gallery of 19 built-in stock sounds, "No Sound", and
 * "Other Sound..." (a custom audio file picked from disk), plus a Preview
 * button for the currently-selected stock sound.
 *
 * Selector: `pptx-effect-sound-row`
 *
 * Its own component for the same reason as {@link MotionPathRowComponent}:
 * keeps {@link AnimationAuthorPanelComponent} under this repo's 300-LOC cap.
 *
 * Reference binding: packages/react/src/viewer/components/inspector/EffectSoundRow.tsx
 *
 * @module viewer/effect-sound-row
 */
import {
	ChangeDetectionStrategy,
	Component,
	CUSTOM_ELEMENTS_SCHEMA,
	ElementRef,
	input,
	output,
	viewChild,
} from '@angular/core';
import { LucidePlay } from '@lucide/angular';
import { TranslatePipe } from '@ngx-translate/core';

import { EFFECT_SOUND_CATALOGUE, getEffectSoundAsset } from 'ooxml-ui/pptx';
import type { EffectSoundState } from 'ooxml-ui/pptx';
import { playAnimationSound } from './animation-sound';

const NONE_VALUE = 'none';
const CURRENT_VALUE = 'current';
const OTHER_VALUE = 'other';

/** A newly-picked sound file, staged for embedding on the next save. */
export interface EffectSoundPick {
	dataUrl: string;
	fileName?: string;
}

@Component({
	selector: 'pptx-effect-sound-row',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe, LucidePlay],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `
		<label class="pptx-ng-anim__section pptx-ng-effect-sound">
			<span class="pptx-ng-anim__label">{{ 'pptx.animation.sound' | translate }}</span>
			<div class="pptx-ng-effect-sound__row">
				<pptx-ui-select
					[attr.aria-label]="'pptx.animation.sound' | translate"
					[attr.value]="selectedValue()"
					class="pptx-ng-anim__select"
					[disabled]="!canEdit()"
					(change)="onSelect($event)"
				>
					<option [value]="NONE_VALUE" [selected]="selectedValue() === NONE_VALUE">
						{{ 'pptx.animation.sound.none' | translate }}
					</option>
					@if (soundState().hasSound && !soundState().catalogueId) {
						<option [value]="CURRENT_VALUE" [selected]="selectedValue() === CURRENT_VALUE">
							{{ soundState().fileName ?? ('pptx.animation.sound.custom' | translate) }}
						</option>
					}
					@for (entry of catalogue; track entry.id) {
						<option [value]="entry.id" [selected]="selectedValue() === entry.id">
							{{ entry.i18nKey | translate }}
						</option>
					}
					<option [value]="OTHER_VALUE" [selected]="selectedValue() === OTHER_VALUE">
						{{ 'pptx.animation.sound.other' | translate }}
					</option>
				</pptx-ui-select>
				<button
					type="button"
					class="pptx-ng-effect-sound__preview"
					[attr.aria-label]="'pptx.animation.sound.preview' | translate"
					[disabled]="!soundState().catalogueId"
					(click)="onPreview()"
				>
					<svg lucidePlay class="h-3 w-3"></svg>
				</button>
			</div>
			<input
				#fileInput
				type="file"
				accept="audio/*"
				[attr.aria-label]="'pptx.animation.sound.chooseFile' | translate"
				class="pptx-ng-effect-sound__file-input"
				tabindex="-1"
				(change)="onFileChange($event)"
			/>
		</label>
	`,
	styles: `
		.pptx-ng-effect-sound__file-input {
			display: none;
		}
		.pptx-ng-effect-sound__row {
			display: flex;
			align-items: center;
			gap: 4px;
		}
		.pptx-ng-effect-sound__preview:disabled {
			opacity: 0.4;
		}
	`,
})
export class EffectSoundRowComponent {
	readonly soundState = input.required<EffectSoundState>();
	readonly canEdit = input<boolean>(true);
	readonly pick = output<EffectSoundPick | undefined>();
	readonly pickStock = output<string>();

	protected readonly NONE_VALUE = NONE_VALUE;
	protected readonly CURRENT_VALUE = CURRENT_VALUE;
	protected readonly OTHER_VALUE = OTHER_VALUE;
	protected readonly catalogue = EFFECT_SOUND_CATALOGUE;

	private readonly fileInput = viewChild<ElementRef<HTMLInputElement>>('fileInput');

	protected selectedValue(): string {
		const state = this.soundState();
		return state.catalogueId ?? (state.hasSound ? CURRENT_VALUE : NONE_VALUE);
	}

	protected onSelect(event: Event): void {
		const target = event.target;
		if (!(target instanceof HTMLElement) || !('value' in target)) {
			return;
		}
		const value = String(target.value);
		if (value === OTHER_VALUE) {
			this.fileInput()?.nativeElement.click();
			return;
		}
		if (value === NONE_VALUE) {
			this.pick.emit(undefined);
			return;
		}
		if (value === CURRENT_VALUE) {
			return;
		}
		this.pickStock.emit(value);
	}

	protected onFileChange(event: Event): void {
		const target = event.target;
		if (!(target instanceof HTMLInputElement)) {
			return;
		}
		const file = target.files?.[0];
		target.value = '';
		if (!file) {
			return;
		}
		const reader = new FileReader();
		reader.onload = () => {
			if (typeof reader.result === 'string') {
				this.pick.emit({ dataUrl: reader.result, fileName: file.name });
			}
		};
		reader.readAsDataURL(file);
	}

	protected onPreview(): void {
		const catalogueId = this.soundState().catalogueId;
		if (!catalogueId) {
			return;
		}
		const asset = getEffectSoundAsset(catalogueId);
		if (asset) {
			playAnimationSound(asset.dataUrl);
		}
	}
}
