// viewers/pptx/packages/svelte/src/viewer/components/inspector/MediaTrimTimeline.svelte
<script lang="ts">
	import type { MediaBookmark } from 'pptx-viewer-core';
	import { mediaTimelineGeometry, mediaTrimEndSeconds, mediaTrimRangeForDrag } from 'ooxml-ui/pptx';

	const { duration, startMs, endMs, currentTime, bookmarks, onchange, onseek }: { duration: number; startMs: number; endMs?: number; currentTime: number; bookmarks: MediaBookmark[]; onchange: (startMs: number, endMs: number) => void; onseek: (seconds: number) => void } = $props();
	// eslint-disable-next-line prefer-const
	let bar = $state<HTMLDivElement>();
	// eslint-disable-next-line prefer-const
	let dragging = $state<'start' | 'end' | null>(null);
	const safeDuration = $derived(Math.max(duration, 0.1));
	// `endMs` is p14:trim/@end's distance from the clip's tail; the shared
	// helpers convert to and from the absolute position the scrubber draws.
	const trimEndMs = $derived(endMs ?? 0);
	const effectiveEndSeconds = $derived(mediaTrimEndSeconds(duration, trimEndMs));
	const geometry = $derived(mediaTimelineGeometry(duration, startMs, trimEndMs, currentTime));

	function timeAt(clientX: number): number {
		const rect = bar?.getBoundingClientRect();
		if (!rect) {
			return 0;
		}
		return Math.max(0, Math.min(1, (clientX - rect.left) / rect.width)) * safeDuration;
	}
	function move(event: PointerEvent): void {
		if (!dragging) {
			return;
		}
		const range = mediaTrimRangeForDrag(dragging, timeAt(event.clientX), duration, startMs, trimEndMs);
		onchange(range.trimStartMs, range.trimEndMs);
	}
	function keySeek(event: KeyboardEvent): void {
		if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') {
			return;
		}
		event.preventDefault();
		onseek(Math.max(0, Math.min(duration, currentTime + (event.key === 'ArrowRight' ? 0.5 : -0.5))));
	}
</script>

<svelte:window onpointermove={move} onpointerup={() => (dragging = null)} />
<div class="times"><span>{(startMs / 1000).toFixed(1)}s</span><span>{effectiveEndSeconds.toFixed(1)}s</span></div>
<div class="timeline" bind:this={bar} role="slider" aria-label="Media trim timeline" aria-valuemin="0" aria-valuemax={duration} aria-valuenow={currentTime} tabindex="0" onclick={(event) => onseek(timeAt(event.clientX))} onkeydown={keySeek}>
	<div class="range" style={`left:${geometry.startPercent}%;right:${100 - geometry.endPercent}%`}></div>
	<div class="playhead" style={`left:${geometry.playheadPercent}%`}></div>
	<button type="button" class="handle start" aria-label="Trim start" style={`left:${geometry.startPercent}%`} data-pptx-compact onpointerdown={(event) => { event.stopPropagation(); dragging = 'start'; }}></button>
	<button type="button" class="handle end" aria-label="Trim end" style={`left:${geometry.endPercent}%`} data-pptx-compact onpointerdown={(event) => { event.stopPropagation(); dragging = 'end'; }}></button>
	{#each bookmarks as bookmark}<button type="button" class="bookmark" title={bookmark.label} aria-label={bookmark.label} style={`left:${bookmark.time / safeDuration * 100}%`} data-pptx-compact onclick={(event) => { event.stopPropagation(); onseek(bookmark.time); }}></button>{/each}
</div>

<style>.times{display:flex;justify-content:space-between;color:var(--pptx-muted-foreground);font-size:9px}.timeline{position:relative;height:22px;border-radius:5px;background:var(--pptx-muted);cursor:pointer}.range{position:absolute;inset-block:0;background:color-mix(in srgb,var(--pptx-primary) 30%,transparent)}.playhead{position:absolute;inset-block:0;width:2px;background:white}.handle,.bookmark{position:absolute;top:0;bottom:0;width:7px;transform:translateX(-50%);border:0;background:var(--pptx-primary);cursor:ew-resize}.bookmark{width:3px;background:#facc15;cursor:pointer}</style>

// viewers/pptx/packages/angular/src/viewer/media-trim-timeline.component.ts
import {
	ChangeDetectionStrategy,
	Component,
	ElementRef,
	HostListener,
	computed,
	input,
	output,
	signal,
	viewChild,
} from '@angular/core';
import type { MediaBookmark } from 'pptx-viewer-core';

import {
	formatMediaTime,
	mediaTimelineGeometry,
	mediaTimeFromPointer,
	mediaTrimEndSeconds,
	mediaTrimRangeForDrag,
} from 'ooxml-ui/pptx';
import type { MediaTrimHandle, MediaTrimRange } from 'ooxml-ui/pptx';

@Component({
	selector: 'pptx-media-trim-timeline',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div class="labels">
			<span>{{ startLabel() }}</span>
			<span>{{ endLabel() }}</span>
		</div>
		<div #bar class="bar" (click)="seekFromClick($event)">
			<div
				class="selection"
				[style.left.%]="geometry().startPercent"
				[style.width.%]="geometry().endPercent - geometry().startPercent"
			></div>
			<div class="playhead" [style.left.%]="geometry().playheadPercent"></div>
			@if (canEdit()) {
				<button
					type="button"
					class="handle start"
					data-pptx-compact
					[style.left.%]="geometry().startPercent"
					(pointerdown)="beginDrag('start', $event)"
					aria-label="Trim start"
				></button>
				<button
					type="button"
					class="handle end"
					data-pptx-compact
					[style.left.%]="geometry().endPercent"
					(pointerdown)="beginDrag('end', $event)"
					aria-label="Trim end"
				></button>
			}
			@for (bookmark of bookmarks(); track bookmark.id) {
				<button
					type="button"
					class="bookmark"
					data-pptx-compact
					[style.left.%]="bookmarkPercent(bookmark)"
					[title]="bookmark.label"
					(click)="seekBookmark(bookmark, $event)"
				></button>
			}
		</div>
	`,
	styles: `
		:host {
			display: grid;
			gap: 4px;
		}
		.labels {
			display: flex;
			justify-content: space-between;
			color: var(--pptx-inspector-muted, #aaa);
			font-size: 10px;
			font-variant-numeric: tabular-nums;
		}
		.bar {
			position: relative;
			height: 20px;
			overflow: hidden;
			border-radius: 4px;
			background: var(--pptx-inspector-input-bg, #2d2d2d);
			cursor: pointer;
			user-select: none;
		}
		.selection {
			position: absolute;
			inset-block: 0;
			border-radius: 4px;
			background: color-mix(in srgb, var(--pptx-primary, #2563eb) 32%, transparent);
		}
		.playhead {
			position: absolute;
			z-index: 2;
			inset-block: 0;
			width: 2px;
			background: #fff;
			pointer-events: none;
		}
		.handle {
			position: absolute;
			z-index: 4;
			inset-block: 0;
			width: 8px;
			padding: 0;
			border: 0;
			border-radius: 3px;
			background: var(--pptx-primary, #2563eb);
			cursor: ew-resize;
			transform: translateX(-4px);
			touch-action: none;
		}
		.bookmark {
			position: absolute;
			z-index: 3;
			inset-block: 0;
			width: 4px;
			padding: 0;
			border: 0;
			background: #facc15b3;
			transform: translateX(-2px);
			cursor: pointer;
		}
	`,
})
export class MediaTrimTimelineComponent {
	readonly duration = input.required<number>();
	readonly trimStartMs = input<number>(0);
	readonly trimEndMs = input<number>(0);
	readonly currentTime = input<number>(0);
	readonly bookmarks = input<MediaBookmark[]>([]);
	readonly canEdit = input<boolean>(true);
	readonly trimChange = output<MediaTrimRange>();
	readonly seek = output<number>();

	private readonly bar = viewChild<ElementRef<HTMLDivElement>>('bar');
	private readonly dragging = signal<MediaTrimHandle | null>(null);
	protected readonly geometry = computed(() =>
		mediaTimelineGeometry(
			this.duration(),
			this.trimStartMs(),
			this.trimEndMs(),
			this.currentTime(),
		),
	);
	protected readonly startLabel = computed(() => formatMediaTime(this.trimStartMs() / 1000));
	// `trimEndMs` is p14:trim/@end's distance from the clip's tail.
	protected readonly endLabel = computed(() =>
		formatMediaTime(mediaTrimEndSeconds(this.duration(), this.trimEndMs())),
	);

	protected beginDrag(handle: MediaTrimHandle, event: PointerEvent): void {
		event.preventDefault();
		event.stopPropagation();
		this.dragging.set(handle);
	}

	@HostListener('window:pointermove', ['$event'])
	protected continueDrag(event: PointerEvent): void {
		const handle = this.dragging();
		if (!handle) {
			return;
		}
		this.trimChange.emit(
			mediaTrimRangeForDrag(
				handle,
				this.timeFromPointer(event.clientX),
				this.duration(),
				this.trimStartMs(),
				this.trimEndMs(),
			),
		);
	}

	@HostListener('window:pointerup')
	protected endDrag(): void {
		this.dragging.set(null);
	}

	protected seekFromClick(event: MouseEvent): void {
		this.seek.emit(this.timeFromPointer(event.clientX));
	}

	protected seekBookmark(bookmark: MediaBookmark, event: MouseEvent): void {
		event.stopPropagation();
		this.seek.emit(bookmark.time);
	}

	protected bookmarkPercent(bookmark: MediaBookmark): number {
		return Math.min(100, Math.max(0, (bookmark.time / Math.max(1, this.duration())) * 100));
	}

	private timeFromPointer(clientX: number): number {
		const rect = this.bar()?.nativeElement.getBoundingClientRect();
		return rect ? mediaTimeFromPointer(clientX, rect.left, rect.width, this.duration()) : 0;
	}
}
