// viewers/pptx/packages/vue/src/viewer/components/MobileSheet.vue
<script setup lang="ts">
/**
 * MobileSheet - reusable slide-up bottom sheet for the Vue `pptx-vue-viewer`.
 *
 * Vue port of `packages/react/src/viewer/components/mobile/MobileSheet.tsx`:
 *   - a tap-to-close backdrop,
 *   - a rounded-top panel that animates up from the bottom,
 *   - a handle + header that form one swipe-to-dismiss grab region
 *     (drag down past the threshold to close),
 *   - Escape closes the sheet.
 *
 * Visibility is owned by the parent (`v-if="isMobile && open"`); the body is
 * scrollable and sized via dvh so it survives the mobile address-bar collapse.
 */
import { activateModalFocus, MIN_TOUCH_TARGET_PX } from 'ooxml-ui/pptx';
import { nextTick, onBeforeUnmount, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { useSheetDismissDrag } from '../composables/useSheetDismissDrag';

const { t } = useI18n();

const props = defineProps<{ open: boolean; title?: string; inspector?: boolean }>();
const emit = defineEmits<{ close: [] }>();

const { dragY, dragging, onPointerDown, onPointerMove, onPointerUp } = useSheetDismissDrag(() =>
	emit('close'),
);

const panelRef = ref<HTMLElement | null>(null);
let releaseFocus: (() => void) | undefined;
watch(
	() => props.open,
	async (open) => {
		releaseFocus?.();
		releaseFocus = undefined;
		if (open) {
			await nextTick();
			if (panelRef.value) {
				releaseFocus = activateModalFocus(panelRef.value, { onEscape: () => emit('close') });
			}
		}
	},
	{ immediate: true },
);
onBeforeUnmount(() => releaseFocus?.());
</script>

<template>
	<div v-if="open" class="pptx-vue-msheet fixed inset-0 z-[60] flex flex-col justify-end">
		<!-- Backdrop -->
		<button
			type="button"
			:aria-label="t('pptx.settings.close')"
			class="absolute inset-0 border-0 bg-black/40 backdrop-blur-[2px]"
			@click="emit('close')"
		/>

		<!-- Panel -->
		<div
			ref="panelRef"
			class="pptx-vue-msheet-panel relative flex max-h-[85dvh] flex-col rounded-t-2xl border-t border-border bg-card text-foreground shadow-2xl"
			role="dialog"
			aria-modal="true"
			:aria-label="title || t('pptx.mobileSheet.ariaLabel')"
			tabindex="-1"
			:data-pptx-inspector="props.inspector ? '' : undefined"
			:style="{
				transform: dragY > 0 ? `translateY(${dragY}px)` : undefined,
				transition: dragging ? 'none' : 'transform 150ms ease-out',
			}"
		>
			<!-- Handle + header = one swipe-to-dismiss grab region -->
			<div
				class="shrink-0 cursor-grab touch-none select-none active:cursor-grabbing"
				@pointerdown="onPointerDown"
				@pointermove="onPointerMove"
				@pointerup="onPointerUp"
				@pointercancel="onPointerUp"
			>
				<div class="flex items-center justify-center pt-2 pb-1">
					<div class="h-1 w-10 rounded-full bg-muted-foreground/40" />
				</div>
				<div
					v-if="title"
					class="flex items-center justify-between gap-2 border-b border-border/60 px-4 pb-2"
				>
					<span class="truncate text-sm font-semibold text-foreground">{{ title }}</span>
					<button
						type="button"
						class="inline-flex items-center justify-center rounded text-xl text-muted-foreground hover:bg-accent hover:text-foreground"
						:style="{ minWidth: `${MIN_TOUCH_TARGET_PX}px`, minHeight: `${MIN_TOUCH_TARGET_PX}px` }"
						:aria-label="t('pptx.settings.close')"
						@pointerdown.stop
						@click="emit('close')"
					>
						&times;
					</button>
				</div>
			</div>

			<!-- Scrollable body -->
			<div
				class="flex-1 overflow-y-auto overscroll-contain pb-[max(env(safe-area-inset-bottom),0px)]"
			>
				<slot />
			</div>
		</div>
	</div>
</template>

// viewers/pptx/packages/angular/src/viewer/mobile-sheet.component.ts
/**
 * mobile-sheet.component.ts: Reusable slide-up bottom sheet for mobile.
 *
 * Ported from: packages/react/src/viewer/components/mobile/MobileSheet.tsx
 *
 * A fixed overlay with:
 *   - a semi-transparent backdrop (tap to close)
 *   - a rounded-top panel that slides up from the bottom
 *   - a drag handle: dragging down by > 120 px dismisses the sheet
 *   - Escape key closes the sheet
 *
 * Inputs
 *   open          : controls visibility
 *   title         : optional header text
 *   heightFraction : initial height as fraction of dvh (default 0.6)
 *   fullScreen    : when true, the sheet covers the full viewport height
 *
 * Outputs
 *   closed : emits when the user dismisses the sheet
 *
 * Content is projected via `<ng-content>`.
 */

import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	ElementRef,
	computed,
	effect,
	inject,
	input,
	output,
	signal,
	viewChild,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { activateModalFocus } from 'ooxml-ui/pptx';

/** Drag-down distance in pixels that triggers dismissal. */
const DISMISS_THRESHOLD = 120;

@Component({
	selector: 'pptx-mobile-sheet',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, TranslatePipe],
	templateUrl: './mobile-sheet.component.html',
	styleUrl: './mobile-sheet.component.css',
})
export class MobileSheetComponent {
	private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');
	private releaseFocus: (() => void) | undefined;
	/** Controls whether the sheet is visible. */
	readonly open = input<boolean>(false);

	/** Optional header text displayed above the body. */
	readonly title = input<string>('');

	/**
	 * Height of the sheet as a fraction of the viewport height (0–1).
	 * Ignored when `fullScreen` is true.
	 */
	readonly heightFraction = input<number>(0.6);

	/** When true, the sheet occupies the full viewport height. */
	readonly fullScreen = input<boolean>(false);

	/** Emits when the user closes the sheet (backdrop tap, swipe, or Escape). */
	readonly closed = output<void>();

	// ── Drag state ────────────────────────────────────────────────────────────

	private _dragStartY: number | null = null;
	private _dragPointerId: number | null = null;

	/** Current translateY applied during an active drag (px). */
	readonly dragY = signal<number>(0);

	/** Whether a drag is in progress (suppresses CSS transition during drag). */
	readonly isDragging = signal<boolean>(false);

	// ── Derived panel style ───────────────────────────────────────────────────

	readonly panelStyle = computed<Record<string, string>>(() => {
		const height = this.fullScreen()
			? 'calc(100dvh - env(safe-area-inset-top, 0px))'
			: `${Math.round(this.heightFraction() * 100)}dvh`;

		const dy = this.dragY();
		const transform = dy > 0 ? `translateY(${dy}px)` : '';
		const transition = this.isDragging() ? 'none' : 'transform 150ms ease-out';

		const style: Record<string, string> = { height };
		if (transform) {
			style['transform'] = transform;
		}
		style['transition'] = transition;
		return style;
	});

	constructor() {
		effect(() => {
			const open = this.open();
			const panel = this.panel()?.nativeElement;
			this.releaseFocus?.();
			this.releaseFocus =
				open && panel
					? activateModalFocus(panel, { onEscape: () => this.closed.emit() })
					: undefined;
		});
		inject(DestroyRef).onDestroy(() => this.releaseFocus?.());
	}

	// ── Pointer events (drag-to-dismiss) ─────────────────────────────────────

	onPointerDown(event: PointerEvent): void {
		if ((event.target as HTMLElement).closest('button')) {
			return;
		}
		this._dragStartY = event.clientY;
		this._dragPointerId = event.pointerId;
		this.isDragging.set(true);
		(event.target as HTMLElement).setPointerCapture(event.pointerId);
	}

	onPointerMove(event: PointerEvent): void {
		if (this._dragStartY === null || event.pointerId !== this._dragPointerId) {
			return;
		}
		const delta = event.clientY - this._dragStartY;
		this.dragY.set(Math.max(0, delta));
	}

	onPointerUp(event: PointerEvent): void {
		if (this._dragStartY === null || event.pointerId !== this._dragPointerId) {
			return;
		}
		const delta = event.clientY - this._dragStartY;
		this._dragStartY = null;
		this._dragPointerId = null;
		this.isDragging.set(false);
		this.dragY.set(0);

		if (delta > DISMISS_THRESHOLD) {
			this.closed.emit();
		}
	}
}
