// viewers/pptx/packages/react/src/viewer/components/mobile/MobileToolbar.tsx
import type {
	MobileToolbarId,
	MobileToolbarIntent,
	PptxUiMobileToolbarElement,
} from 'ooxml-ui/pptx';
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

import { useToolbarVisibility } from '../../hooks/useToolbarVisibility';
import { useWebControl } from '../../hooks/useWebControl';
import type { ToolbarProps } from '../toolbar/toolbar-types';
import { MobileMenuSheet } from './MobileMenuSheet';

/**
 * Mobile-first replacement for the desktop ribbon toolbar.
 *
 * A thin adapter around the shared `pptx-ui-mobile-toolbar`, which renders a
 * single compact row of essential controls:
 *   menu · undo · redo · [AI] · save · present · share
 *
 * All section-specific functionality (Home/Insert/Design/etc.) lives in the
 * MobileMenuSheet that opens from the hamburger menu, and the contextual
 * action bar at the bottom of the screen handles common per-selection tasks.
 */
export function MobileToolbar(props: ToolbarProps): React.ReactElement {
	const { t } = useTranslation();
	const { mode, canUndo, canRedo, onUndo, onRedo, onSetMode, onSaveAsPptx } = props;
	const [menuOpen, setMenuOpen] = useState(false);
	const { isHidden } = useToolbarVisibility(props.hiddenActions);

	const showEdit = mode === 'edit' || mode === 'master';
	const hidden: MobileToolbarId[] = [];
	if (isHidden('undo')) {
		hidden.push('undo');
	}
	if (isHidden('redo')) {
		hidden.push('redo');
	}
	if (isHidden('fullscreen')) {
		hidden.push('present');
	}
	if (isHidden('share')) {
		hidden.push('share');
	}

	const handlers: Record<MobileToolbarId, () => void> = {
		menu: () => setMenuOpen(true),
		undo: onUndo,
		redo: onRedo,
		ai: () => props.onToggleAiPanel?.(),
		save: onSaveAsPptx,
		present: () => onSetMode('present'),
		share: () => props.onOpenShareDialog?.(),
	};
	const ref = useWebControl<PptxUiMobileToolbarElement>(
		{
			editable: showEdit,
			canUndo,
			canRedo,
			aiVisible: props.aiEnabled === true,
			aiActive: props.isAiPanelOpen === true,
			menuOpen,
			hidden,
			translate: t,
		},
		{
			'mobile-toolbar-request': (event) => handlers[(event.detail as MobileToolbarIntent).id](),
		},
	);

	return (
		<div className='relative z-20'>
			<pptx-ui-mobile-toolbar ref={ref} />
			{/* Section sheet */}
			<MobileMenuSheet open={menuOpen} onClose={() => setMenuOpen(false)} {...props} />
		</div>
	);
}

// viewers/pptx/packages/angular/src/viewer/mobile-toolbar.component.ts
/**
 * mobile-toolbar.component.ts: Compact mobile top toolbar.
 *
 * Ported from: packages/react/src/viewer/components/mobile/MobileToolbar.tsx
 *
 * A single compact row that replaces the desktop ribbon below the 768px
 * breakpoint. Renders the essential always-available controls:
 *
 *   Menu · Undo · Redo · [spacer] · AI · Save · Present · Share
 *
 * A thin adapter around the shared `pptx-ui-mobile-toolbar`, which owns the
 * `role="toolbar"` with `aria-label="Toolbar"` (the framework-neutral
 * accessibility contract the e2e specs assert against, via
 * `getByRole('toolbar', { name: 'Toolbar' })`) and the slot order, icons and
 * gating. This maps the inputs onto its state and re-emits its typed intents as
 * the outputs the viewer already wires.
 *
 * Section-specific functionality (Insert/Design/Export/etc.) lives in the
 * `MobileMenuSheetComponent` that opens from the Menu button; per-selection
 * actions live in the `MobileBottomBarComponent` at the bottom of the screen.
 *
 * Each input/output is documented on its own declaration below.
 */

import {
	ChangeDetectionStrategy,
	Component,
	computed,
	CUSTOM_ELEMENTS_SCHEMA,
	inject,
	input,
	output,
} from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

import { isActionHidden } from 'ooxml-ui/pptx';
import type {
	MobileToolbarId,
	MobileToolbarRequestEvent,
	MobileToolbarViewState,
	ToolbarActionId,
} from 'ooxml-ui/pptx';
import { translationsSignal } from './translations-signal';

@Component({
	selector: 'pptx-mobile-toolbar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `
		<pptx-ui-mobile-toolbar [state]="view()" (mobile-toolbar-request)="request($event)" />
	`,
	styles: [':host { display: block; }'],
})
export class MobileToolbarComponent {
	// ── Inputs ────────────────────────────────────────────────────────────────

	/** Whether Undo is available. */
	readonly canUndo = input<boolean>(false);
	/** Whether Redo is available. */
	readonly canRedo = input<boolean>(false);
	/** Whether Present can start (a deck with at least one slide is open). */
	readonly canPresent = input<boolean>(true);
	/** Whether the deck is editable; gates Menu, Undo/Redo, AI and Share. */
	readonly canEdit = input<boolean>(false);
	/** Whether the section menu sheet is open (reflected as `aria-expanded`). */
	readonly menuOpen = input<boolean>(false);
	/** Whether the host opted into the AI assistant. */
	readonly aiEnabled = input<boolean>(false);
	/** Whether the AI panel is open (reflected as `aria-pressed`). */
	readonly aiPanelOpen = input<boolean>(false);
	/** Toolbar buttons the host wants hidden (undo / redo / fullscreen / share). */
	readonly hiddenActions = input<ToolbarActionId[]>([]);

	// ── Outputs ───────────────────────────────────────────────────────────────

	readonly toggleMenu = output<void>();
	readonly toggleAiPanel = output<void>();
	readonly undo = output<void>();
	readonly redo = output<void>();
	readonly share = output<void>();
	readonly save = output<void>();
	readonly present = output<void>();

	private readonly translate = inject(TranslateService);
	private readonly translations = translationsSignal(this.translate);

	private readonly emitters: Record<MobileToolbarId, () => void> = {
		menu: () => this.toggleMenu.emit(),
		undo: () => this.undo.emit(),
		redo: () => this.redo.emit(),
		ai: () => this.toggleAiPanel.emit(),
		save: () => this.save.emit(),
		present: () => this.present.emit(),
		share: () => this.share.emit(),
	};

	protected readonly view = computed<MobileToolbarViewState>(() => {
		this.translations();
		const actions = this.hiddenActions();
		const hidden: MobileToolbarId[] = [];
		if (isActionHidden('undo', actions)) {
			hidden.push('undo');
		}
		if (isActionHidden('redo', actions)) {
			hidden.push('redo');
		}
		if (isActionHidden('fullscreen', actions)) {
			hidden.push('present');
		}
		if (isActionHidden('share', actions)) {
			hidden.push('share');
		}
		return {
			editable: this.canEdit(),
			canUndo: this.canUndo(),
			canRedo: this.canRedo(),
			aiVisible: this.aiEnabled(),
			aiActive: this.aiPanelOpen(),
			menuOpen: this.menuOpen(),
			hidden,
			disabled: this.canPresent() ? [] : ['present'],
			translate: (key, params) => this.translate.instant(key, params),
		};
	});

	protected request(event: Event): void {
		this.emitters[(event as MobileToolbarRequestEvent).detail.id]();
	}
}
