// viewers/pptx/packages/svelte/src/viewer/collab/components/ModalDialog.svelte
<script lang="ts">
	/**
	 * ModalDialog: a reusable, dismissable modal shell for the Svelte viewer's
	 * collaboration dialogs. Svelte port of the Vue `ModalDialog.vue` shell
	 * (minus the Teleport-to-body and swipe-to-dismiss touch gesture, which Vue
	 * needs because it mounts deep inside a large ribbon tree; this package's
	 * dialogs mount directly at the viewer root, alongside `ExportProgressModal`,
	 * so a plain fixed-position overlay is sufficient).
	 *
	 * Unlike `ExportProgressModal` (which is intentionally non-dismissable while
	 * an export is in flight), this shell closes on backdrop click, the close
	 * button, or Escape, since none of its callers block a critical operation.
	 */
	import { activateModalFocus } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';
	import type { ModalDialogProps } from './props';

	const { open, title, onclose, children, footer }: ModalDialogProps = $props();

	const t = useTranslator();

	function onBackdropClick(): void {
		onclose();
	}

	function modalFocus(node: HTMLElement): { destroy(): void } {
		const release = activateModalFocus(node, { onEscape: onclose });
		return { destroy: release };
	}
</script>

{#if open}
	<div
		class="pptx-svelte-modal-backdrop"
		role="presentation"
		onclick={onBackdropClick}
	>
		<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
		<div
			use:modalFocus
			class="pptx-svelte-modal-panel"
			role="dialog"
			aria-modal="true"
			aria-label={title}
			tabindex="-1"
			onclick={(event) => event.stopPropagation()}
		>
			<header class="pptx-svelte-modal-header">
				{#if title}
					<h2 class="pptx-svelte-modal-title">{title}</h2>
				{:else}
					<span></span>
				{/if}
				<button
					type="button"
					class="pptx-svelte-modal-close"
					aria-label={t('pptx.settings.close')}
					onclick={onclose}
				>
					&times;
				</button>
			</header>
			<div class="pptx-svelte-modal-body">
				{@render children?.()}
			</div>
			{#if footer}
				<footer class="pptx-svelte-modal-footer">
					{@render footer()}
				</footer>
			{/if}
		</div>
	</div>
{/if}

<style>
	.pptx-svelte-modal-backdrop {
		position: fixed;
		inset: 0;
		z-index: 1100;
		display: flex;
		align-items: center;
		justify-content: center;
		background: rgba(0, 0, 0, 0.5);
	}

	.pptx-svelte-modal-panel {
		display: flex;
		flex-direction: column;
		width: min(92vw, 420px);
		max-height: 88vh;
		overflow: hidden;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: calc(var(--pptx-radius, 6px) + 6px);
		background: var(--pptx-popover, #111827);
		color: var(--pptx-popover-foreground, #f3f4f6);
		box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
		overscroll-behavior: contain;
		font-family: system-ui, sans-serif;
	}

	.pptx-svelte-modal-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 12px;
		padding: 12px 16px;
		border-bottom: 1px solid var(--pptx-border, #33334d);
	}

	.pptx-svelte-modal-title {
		margin: 0;
		font-size: 14px;
		font-weight: 600;
		line-height: 1.3;
	}

	.pptx-svelte-modal-close {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 24px;
		height: 24px;
		border: none;
		border-radius: var(--pptx-radius, 6px);
		background: transparent;
		color: var(--pptx-muted-foreground, #94a3b8);
		font-size: 18px;
		line-height: 1;
		cursor: pointer;
	}

	.pptx-svelte-modal-close:hover {
		background: var(--pptx-accent, #33334d);
		color: var(--pptx-accent-foreground, #f8fafc);
	}

	.pptx-svelte-modal-body {
		overflow-y: auto;
		padding: 16px;
	}

	.pptx-svelte-modal-footer {
		display: flex;
		justify-content: flex-end;
		gap: 8px;
		padding: 12px 16px;
		border-top: 1px solid var(--pptx-border, #33334d);
	}

	/*
	 * Dense-panel responsive treatment (see `pptx-viewer-shared`'s
	 * `render/responsive/*`), applied via CSS since this shell has no
	 * reactive script state of its own:
	 *  - `isDensePanelCompact` / `MOBILE_BREAKPOINT` = 768px -> `max-width: 767px`.
	 *  - `MIN_TOUCH_TARGET_PX` = 44 -> the close button's min box below that width.
	 * Below the breakpoint the panel becomes a bottom sheet (matching React's
	 * `max-md:` classes on `ShareDialog.tsx`) instead of a centered card, since
	 * a fixed-width modal is easy to mis-tap at 360px and wastes vertical room
	 * a sheet reclaims from the bottom safe area.
	 */
	@media (max-width: 767px) {
		.pptx-svelte-modal-backdrop {
			align-items: flex-end;
		}

		.pptx-svelte-modal-panel {
			width: 100%;
			max-width: none;
			max-height: 88dvh;
			border-radius: calc(var(--pptx-radius, 6px) + 6px) calc(var(--pptx-radius, 6px) + 6px) 0 0;
			border-right: 0;
			border-bottom: 0;
			border-left: 0;
			padding-bottom: max(env(safe-area-inset-bottom), 0px);
		}

		/*
		 * `!important` is load-bearing: ViewerGlobalStyles.svelte's
		 * document-level
		 * `:global(.pptx-svelte-viewer :is(button, [role='button']):not(...):not(...))`
		 * baseline reset out-specificities a plain scoped class selector.
		 */
		.pptx-svelte-modal-close {
			min-width: 44px !important;
			min-height: 44px !important;
		}
	}
</style>

// viewers/pptx/packages/angular/src/viewer/modal-dialog.component.ts
/**
 * modal-dialog.component.ts: Reusable, accessible modal dialog shell.
 *
 * Selector: `pptx-modal-dialog`
 *
 * Angular counterpart of the Vue `ModalDialog.vue` and the React package's
 * ad-hoc dialog shells. Renders a full-screen backdrop plus a centered panel
 * with a header (title + close `×`), a default content area for the body, and
 * a footer area for action buttons. The other dialogs compose it.
 *
 * Behaviour:
 *  - The host owns the `open` flag; the component is purely presentational.
 *  - Emits `close` on the `×` button, on a backdrop click, and on `Escape`.
 *  - Body and footer are projected via `<ng-content>`. The footer slot uses a
 *    `[footer]` attribute selector so it can be omitted (no footer bar then).
 *
 * Usage:
 * ```html
 * <pptx-modal-dialog [open]="show()" title="Hyperlink" (close)="show.set(false)">
 *   <div>…body…</div>
 *   <div footer>
 *     <button>Cancel</button>
 *   </div>
 * </pptx-modal-dialog>
 * ```
 */

import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	ElementRef,
	computed,
	effect,
	inject,
	input,
	output,
	signal,
	viewChild,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { activateModalFocus } from 'ooxml-ui/pptx';
import { IsMobileService } from './is-mobile';

/**
 * Map the mobile flag to the modal-panel class list. Pure (no Angular / DOM) so
 * it can be unit-tested without TestBed: on mobile the panel gets the
 * `is-mobile` modifier that turns it into a bottom sheet (matching the CSS media
 * query, but driven by the {@link IsMobileService} 768px breakpoint so the three
 * frameworks switch chrome at the same width).
 */
export function modalPanelClass(isMobile: boolean): string {
	return isMobile ? 'pptx-ng-modal-panel is-mobile' : 'pptx-ng-modal-panel';
}

@Component({
	selector: 'pptx-modal-dialog',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	providers: [IsMobileService],
	template: `
		@if (open()) {
			<div
				class="pptx-ng-modal-backdrop"
				[class.is-mobile]="mobile.isMobile()"
				(click)="onBackdropClick()"
			>
				<div
					#panel
					[class]="panelClass()"
					role="dialog"
					aria-modal="true"
					[attr.aria-busy]="busy() ? 'true' : null"
					tabindex="-1"
					[attr.aria-label]="title() || null"
					[style.transform]="dragY() > 0 ? 'translateY(' + dragY() + 'px)' : null"
					[style.transition]="dragging() ? 'none' : 'transform 150ms ease-out'"
					(click)="$event.stopPropagation()"
				>
					<header
						class="pptx-ng-modal-header"
						(pointerdown)="onHeaderPointerDown($event)"
						(pointermove)="onHeaderPointerMove($event)"
						(pointerup)="onHeaderPointerUp($event)"
						(pointercancel)="onHeaderPointerUp($event)"
					>
						@if (title()) {
							<h2 class="pptx-ng-modal-title">{{ title() }}</h2>
						} @else {
							<span></span>
						}
						<button
							type="button"
							class="pptx-ng-modal-close"
							[attr.aria-label]="'pptx.common.close' | translate"
							[disabled]="closeDisabled()"
							(click)="requestClose()"
						>
							&times;
						</button>
					</header>

					<div class="pptx-ng-modal-body">
						<ng-content />
					</div>

					<footer class="pptx-ng-modal-footer">
						<ng-content select="[footer]" />
					</footer>
				</div>
			</div>
		}
	`,
	styles: [
		`
			.pptx-ng-modal-backdrop {
				position: fixed;
				inset: 0;
				z-index: 1000;
				display: flex;
				align-items: center;
				justify-content: center;
				background: rgba(0, 0, 0, 0.45);
			}

			.pptx-ng-modal-panel {
				display: flex;
				flex-direction: column;
				min-width: 320px;
				max-width: min(92vw, 480px);
				max-height: 88vh;
				overflow: hidden;
				background: var(--pptx-popover, #ffffff);
				color: var(--pptx-foreground, #111827);
				border: 1px solid var(--pptx-border, #e5e7eb);
				border-radius: var(--pptx-radius, 8px);
				box-shadow: 0 10px 40px rgba(0, 0, 0, 0.35);
				overscroll-behavior: contain;
			}

			.pptx-ng-modal-header {
				display: flex;
				align-items: center;
				justify-content: space-between;
				gap: 12px;
				padding: 12px 16px;
				border-bottom: 1px solid var(--pptx-border, #e5e7eb);
				/* Lets touch users swipe the header down to dismiss without the
				   browser hijacking the gesture for scrolling. */
				touch-action: none;
			}

			.pptx-ng-modal-title {
				margin: 0;
				font-size: 14px;
				font-weight: 600;
				line-height: 1.4;
			}

			.pptx-ng-modal-close {
				display: inline-flex;
				align-items: center;
				justify-content: center;
				width: 24px;
				height: 24px;
				padding: 0;
				font-size: 18px;
				line-height: 1;
				color: var(--pptx-muted-foreground, #6b7280);
				background: transparent;
				border: none;
				border-radius: 4px;
				cursor: pointer;
			}

			.pptx-ng-modal-close:hover {
				color: var(--pptx-foreground, #111827);
				background: var(--pptx-muted, #f3f4f6);
			}

			.pptx-ng-modal-close:disabled {
				cursor: not-allowed;
				opacity: 0.55;
			}

			.pptx-ng-modal-body {
				padding: 16px;
				overflow-y: auto;
			}

			.pptx-ng-modal-footer {
				display: flex;
				flex-wrap: wrap;
				justify-content: flex-end;
				gap: 8px;
				padding: 12px 16px;
				border-top: 1px solid var(--pptx-border, #e5e7eb);
			}

			/* Hide the footer bar entirely when nothing is projected into it. */
			.pptx-ng-modal-footer:empty {
				display: none;
			}

			/*
			 * Mobile: dock the panel full-width at the bottom as a bottom sheet
			 * (rounded top, dvh-capped height with internal scroll, safe-area
			 * padding). The backdrop stops centering so the panel can pin itself
			 * to the bottom edge. Desktop keeps the centered card above.
			 *
			 * Driven two ways that share the same declarations: the .is-mobile
			 * class (set from IsMobileService, the canonical 768px breakpoint) and
			 * a CSS media query as a no-JS fallback. Keeping both means the sheet
			 * appears even if the service has not yet wired up.
			 */
			.pptx-ng-modal-backdrop.is-mobile {
				align-items: flex-end;
				justify-content: stretch;
			}

			.pptx-ng-modal-panel.is-mobile {
				min-width: 0;
				max-width: none;
				width: 100%;
				max-height: 88dvh;
				border-left: none;
				border-right: none;
				border-bottom: none;
				border-top-left-radius: 16px;
				border-top-right-radius: 16px;
				border-bottom-left-radius: 0;
				border-bottom-right-radius: 0;
				padding-bottom: max(env(safe-area-inset-bottom), 0px);
			}

			@media (max-width: 767px), (pointer: coarse) {
				.pptx-ng-modal-backdrop {
					align-items: flex-end;
					justify-content: stretch;
				}

				.pptx-ng-modal-panel {
					min-width: 0;
					max-width: none;
					width: 100%;
					max-height: 88dvh;
					border-left: none;
					border-right: none;
					border-bottom: none;
					border-top-left-radius: 16px;
					border-top-right-radius: 16px;
					border-bottom-left-radius: 0;
					border-bottom-right-radius: 0;
					padding-bottom: max(env(safe-area-inset-bottom), 0px);
				}

				/*
				 * Touch target: matches MIN_TOUCH_TARGET_PX (44) from
				 * pptx-viewer-shared's render/responsive module. Every Angular
				 * modal (Share, Hyperlink, Options, Print, ...) composes this
				 * shell, so fixing the close button once here reaches all of
				 * them instead of each dialog re-implementing its own header.
				 */
				.pptx-ng-modal-close {
					width: 44px;
					height: 44px;
					font-size: 22px;
				}
			}
		`,
	],
})
export class ModalDialogComponent {
	private readonly panel = viewChild<ElementRef<HTMLElement>>('panel');
	private releaseFocus: (() => void) | undefined;

	/** Whether the dialog is visible. */
	readonly open = input<boolean>(false);

	/** Optional heading shown in the header bar. */
	readonly title = input<string>('');

	/** Prevent Escape, backdrop, close-button and drag dismissal. */
	readonly closeDisabled = input(false);

	/** Expose an in-flight action to assistive technology. */
	readonly busy = input(false);

	/** Fired on backdrop click, the `×` button, and `Escape`. */
	readonly close = output<void>();

	/** Reactive viewport / pointer flags (drives the bottom-sheet layout). */
	protected readonly mobile = inject(IsMobileService);

	/**
	 * Panel class list: gains the `is-mobile` bottom-sheet modifier under the
	 * mobile breakpoint. See {@link modalPanelClass}.
	 */
	protected readonly panelClass = computed(() => modalPanelClass(this.mobile.isMobile()));

	constructor() {
		effect(() => {
			const open = this.open();
			const panel = this.panel()?.nativeElement;
			this.releaseFocus?.();
			this.releaseFocus =
				open && panel
					? activateModalFocus(panel, { onEscape: () => this.requestClose() })
					: undefined;
		});
		inject(DestroyRef).onDestroy(() => this.releaseFocus?.());
	}

	requestClose(): void {
		if (this.closeDisabled()) {
			return;
		}
		this.close.emit();
	}

	/**
	 * Backdrop clicks close the dialog; clicks bubbling up from the panel are
	 * stopped in the template, so this only ever fires for the backdrop itself.
	 */
	onBackdropClick(): void {
		this.requestClose();
	}

	// ── Swipe-down-to-dismiss (touch/pen only) ─────────────────────────────────
	/** Live downward drag offset for the panel (px; 0 when idle). */
	readonly dragY = signal(0);
	/** True while a header drag is in progress (suppresses the snap-back transition). */
	readonly dragging = signal(false);
	private dragStartY: number | null = null;

	onHeaderPointerDown(event: PointerEvent): void {
		// Touch/pen only, and never from the × button or a form control, so a
		// desktop mouse and header clicks are entirely unaffected.
		if (event.pointerType === 'mouse') {
			return;
		}
		if ((event.target as HTMLElement).closest('button, a, input, select, textarea')) {
			return;
		}
		this.dragStartY = event.clientY;
		this.dragging.set(true);
		(event.target as HTMLElement).setPointerCapture?.(event.pointerId);
	}

	onHeaderPointerMove(event: PointerEvent): void {
		if (this.dragStartY === null) {
			return;
		}
		this.dragY.set(Math.max(0, event.clientY - this.dragStartY));
	}

	onHeaderPointerUp(event: PointerEvent): void {
		if (this.dragStartY === null) {
			return;
		}
		const delta = event.clientY - this.dragStartY;
		this.dragStartY = null;
		this.dragging.set(false);
		(event.target as HTMLElement).releasePointerCapture?.(event.pointerId);
		// 120 px matches the mobile-sheet DISMISS_THRESHOLD for consistency.
		if (delta > 120) {
			this.requestClose();
		}
		this.dragY.set(0);
	}
}
