// viewers/pptx/packages/react/src/viewer/components/settings/OptionsPane.tsx
/* oxlint-disable eslint/one-var -- this module predates the rule and combining
   every sibling const in a function into one comma-list would hurt
   readability, not help it (see chart-view-model.ts for the same rationale). */
import { clampOptionNumber, getDensePanelTouchTargetPx } from 'ooxml-ui/pptx';
import type {
	ViewerOptions,
	ViewerOptionsControl,
	ViewerOptionsSection,
	ViewerOptionsTabDefinition,
} from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { LuInfo } from 'react-icons/lu';

import { useIsMobile } from '../../hooks/useIsMobile';
import { cn } from '../../utils';
import { WebCheckbox, WebSelect } from '../WebControls';

export type OptionChangeHandler = (
	group: keyof ViewerOptions,
	key: string,
	value: boolean | number | string,
) => void;

export interface OptionsPaneProps {
	tab: ViewerOptionsTabDefinition;
	options: ViewerOptions;
	onOptionChange: OptionChangeHandler;
	/** Bespoke blocks (theme picker, clear-cache, shortcut list) keyed by `section.special`. */
	renderSpecial?: (section: ViewerOptionsSection) => React.ReactNode;
	/** Extra content rendered after the generic sections (custom panes). */
	children?: React.ReactNode;
}

function readValue(
	options: ViewerOptions,
	control: ViewerOptionsControl,
): boolean | number | string | undefined {
	const group = options[control.group] as unknown as Record<string, unknown>;
	const value = group[control.key];
	return typeof value === 'boolean' || typeof value === 'number' || typeof value === 'string'
		? value
		: undefined;
}

function InfoTip({ text }: { text: string }): React.ReactElement {
	return (
		<span title={text} className='inline-flex cursor-help align-middle'>
			<LuInfo className='ml-1 h-3.5 w-3.5 text-primary/70' aria-label={text} />
		</span>
	);
}

/** A host-locked setting (`control.readOnly`) never emits a change. */
const IGNORE_CHANGE: OptionChangeHandler = () => undefined;

function ControlRow({
	control,
	options,
	onOptionChange: emitChange,
}: {
	control: ViewerOptionsControl;
	options: ViewerOptions;
	onOptionChange: OptionChangeHandler;
}): React.ReactElement | null {
	const { t } = useTranslation();
	const { viewportWidth } = useIsMobile();
	// One-per-row fields (not a dense repeating grid), so every field/toggle
	// in every Options tab gets the WCAG touch target below the mobile
	// breakpoint from this single shared control-row renderer, per CLAUDE.md
	// Rule 2 - never re-derive this per tab.
	const fieldMinHeight = getDensePanelTouchTargetPx(viewportWidth);
	const value = readValue(options, control);
	const label = t(control.labelKey);
	const info = control.infoKey ? <InfoTip text={t(control.infoKey)} /> : null;
	const rowClass = cn('flex items-center justify-between gap-3 py-1.5', control.indent && 'pl-6');
	const rowStyle = { minHeight: fieldMinHeight };
	const locked = control.readOnly === true;
	const lockedTitle = locked ? t('pptx.options.lockedByHost') : undefined;
	const onOptionChange = locked ? IGNORE_CHANGE : emitChange;

	if (control.kind === 'toggle') {
		return (
			<label className={cn(rowClass, 'cursor-pointer select-none')} style={rowStyle}>
				<span className='text-sm text-foreground'>
					{label}
					{info}
				</span>
				<WebCheckbox
					checked={value === true}
					aria-label={label}
					disabled={locked}
					title={lockedTitle}
					onChange={(event) =>
						onOptionChange(
							control.group,
							control.key,
							(event.currentTarget as HTMLElement & { checked: boolean }).checked,
						)
					}
				/>
			</label>
		);
	}

	if (control.kind === 'select') {
		return (
			<div className={rowClass} style={rowStyle}>
				<span className='text-sm text-foreground'>
					{label}
					{info}
				</span>
				<WebSelect
					aria-label={label}
					disabled={locked}
					title={lockedTitle}
					style={{ minHeight: fieldMinHeight }}
					value={typeof value === 'string' ? value : ''}
					onChange={(event) =>
						onOptionChange(
							control.group,
							control.key,
							(event.currentTarget as HTMLElement & { value: string }).value,
						)
					}
				>
					{control.choices.map((choice) => (
						<option key={choice.value} value={choice.value}>
							{t(choice.labelKey)}
						</option>
					))}
				</WebSelect>
			</div>
		);
	}

	if (control.kind === 'number') {
		return (
			<div className={rowClass} style={rowStyle}>
				<span className='text-sm text-foreground'>
					{label}
					{info}
				</span>
				<span className='flex items-center gap-1.5'>
					<input
						type='number'
						aria-label={label}
						disabled={locked}
						title={lockedTitle}
						style={{ minHeight: fieldMinHeight }}
						className='w-20 rounded border border-border bg-background px-2 py-1 text-right text-xs text-foreground'
						min={control.min}
						max={control.max}
						step={control.step ?? 1}
						value={typeof value === 'number' ? value : control.min}
						onChange={(event) => {
							const clamped = clampOptionNumber(event.target.value, control.min, control.max);
							if (clamped !== undefined) {
								onOptionChange(control.group, control.key, clamped);
							}
						}}
					/>
					{control.unitKey && (
						<span className='text-xs text-muted-foreground'>{t(control.unitKey)}</span>
					)}
				</span>
			</div>
		);
	}

	return (
		<div className={rowClass} style={rowStyle}>
			<span className='text-sm text-foreground'>
				{label}
				{info}
			</span>
			<input
				type='text'
				aria-label={label}
				disabled={locked}
				title={lockedTitle}
				style={{ minHeight: fieldMinHeight }}
				className='w-48 max-w-[55%] rounded border border-border bg-background px-2 py-1 text-xs text-foreground'
				maxLength={control.maxLength}
				value={typeof value === 'string' ? value : ''}
				onChange={(event) => onOptionChange(control.group, control.key, event.target.value)}
			/>
		</div>
	);
}

/**
 * Generic File > Options pane: headline plus sections of schema-driven
 * controls, with `renderSpecial` slots for the bespoke blocks.
 */
export function OptionsPane({
	tab,
	options,
	onOptionChange,
	renderSpecial,
	children,
}: OptionsPaneProps): React.ReactElement {
	const { t } = useTranslation();
	return (
		<div className='space-y-5'>
			<p className='text-sm font-medium text-foreground'>{t(tab.descriptionKey)}</p>
			{tab.sections.map((section) => (
				<section key={section.id}>
					<h3 className='mb-1 border-b border-border/60 pb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground'>
						{t(section.titleKey)}
					</h3>
					{section.descriptionKey && (
						<p className='mb-2 text-xs text-muted-foreground'>{t(section.descriptionKey)}</p>
					)}
					<div className='space-y-0.5'>
						{section.controls.map((control) => (
							<ControlRow
								key={`${control.group}.${control.key}.${section.id}`}
								control={control}
								options={options}
								onOptionChange={onOptionChange}
							/>
						))}
					</div>
					{section.special && renderSpecial?.(section)}
				</section>
			))}
			{children}
		</div>
	);
}

// viewers/pptx/packages/angular/src/viewer/options-pane.component.ts
/**
 * options-pane.component.ts: generic, schema-driven File > Options pane
 * (Angular port of React's `settings/OptionsPane.tsx`).
 *
 * Renders one {@link ViewerOptionsTabDefinition}: the headline, then each
 * section's toggle/select/number/text controls with optional "(i)" info
 * tooltips and PowerPoint-style indenting. Bespoke blocks are handled via
 * `special`: `clearCache` renders inline (emitting {@link clearCache}), and
 * `themePicker` projects host content marked `themePicker` (the appearance
 * swatch gallery). Extra custom content (the Quick Access chooser) projects
 * after the sections.
 */
import {
	ChangeDetectionStrategy,
	Component,
	CUSTOM_ELEMENTS_SCHEMA,
	input,
	output,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { clampOptionNumber } from 'ooxml-ui/pptx';
import type {
	ViewerOptionPrimitive,
	ViewerOptions,
	ViewerOptionsControl,
	ViewerOptionsGroupId,
	ViewerOptionsTabDefinition,
} from 'ooxml-ui/pptx';
import { OPTIONS_PANE_STYLES } from './options-pane-styles';

/** One dialog-level option edit (group + key + new primitive value). */
export interface OptionValueChange {
	group: ViewerOptionsGroupId;
	key: string;
	value: ViewerOptionPrimitive;
}

/** Read a control's current primitive value off the options snapshot. */
export function readOptionValue(
	options: ViewerOptions,
	control: Pick<ViewerOptionsControl, 'group' | 'key'>,
): ViewerOptionPrimitive | undefined {
	const group = options[control.group] as unknown as Record<string, unknown>;
	// oxlint-disable-next-line eslint/one-var -- distinct concern from the lookup above, forcing one statement hurts readability
	const value = group[control.key];
	return typeof value === 'boolean' || typeof value === 'number' || typeof value === 'string'
		? value
		: undefined;
}

@Component({
	selector: 'pptx-options-pane',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `
		<div class="pptx-ng-options-pane">
			<p class="pptx-ng-options-headline">{{ tab().descriptionKey | translate }}</p>
			@for (section of tab().sections; track section.id) {
				<section class="pptx-ng-options-section">
					<h3>{{ section.titleKey | translate }}</h3>
					@if (section.descriptionKey; as descriptionKey) {
						<p class="pptx-ng-options-note">{{ descriptionKey | translate }}</p>
					}
					@for (control of section.controls; track control.group + '.' + control.key) {
						@if (control.kind === 'toggle') {
							<!-- The whole row is the label so the 44px touch target
							     (see the compact media query below) isn't limited to the
							     22px checkbox glyph itself. -->
							<label class="pptx-ng-options-row" [class.is-indented]="control.indent">
								<span class="pptx-ng-options-label">
									{{ control.labelKey | translate }}
									@if (control.infoKey; as infoKey) {
										<span
											class="pptx-ng-options-info"
											[title]="infoKey | translate"
											aria-hidden="true"
											>&#9432;</span
										>
									}
								</span>
								<pptx-ui-checkbox
									class="pptx-ng-options-check"
									[checked]="value(control) === true"
									[attr.aria-label]="control.labelKey | translate"
									[attr.disabled]="control.readOnly ? '' : null"
									[attr.title]="control.readOnly ? ('pptx.options.lockedByHost' | translate) : null"
									(change)="emitToggle(control, $event)"
								/>
							</label>
						} @else {
							<div class="pptx-ng-options-row" [class.is-indented]="control.indent">
								<span class="pptx-ng-options-label">
									{{ control.labelKey | translate }}
									@if (control.infoKey; as infoKey) {
										<span
											class="pptx-ng-options-info"
											[title]="infoKey | translate"
											aria-hidden="true"
											>&#9432;</span
										>
									}
								</span>
								@switch (control.kind) {
									@case ('select') {
										<pptx-ui-select
											class="pptx-ng-options-select"
											[value]="value(control)"
											[attr.aria-label]="control.labelKey | translate"
											[attr.disabled]="control.readOnly ? '' : null"
											[attr.title]="
												control.readOnly ? ('pptx.options.lockedByHost' | translate) : null
											"
											(change)="emitSelect(control, $event)"
										>
											@for (choice of selectChoices(control); track choice.value) {
												<option [value]="choice.value" [selected]="choice.value === value(control)">
													{{ choice.labelKey | translate }}
												</option>
											}
										</pptx-ui-select>
									}
									@case ('number') {
										<span class="pptx-ng-options-number">
											<input
												type="number"
												[min]="numberMin(control)"
												[max]="numberMax(control)"
												[value]="value(control)"
												[attr.aria-label]="control.labelKey | translate"
												[attr.disabled]="control.readOnly ? '' : null"
												[attr.title]="
													control.readOnly ? ('pptx.options.lockedByHost' | translate) : null
												"
												(change)="emitNumber(control, $event)"
											/>
											@if (numberUnitKey(control); as unitKey) {
												<span class="pptx-ng-options-note">{{ unitKey | translate }}</span>
											}
										</span>
									}
									@default {
										<input
											type="text"
											class="pptx-ng-options-text"
											maxlength="64"
											[value]="value(control) ?? ''"
											[attr.aria-label]="control.labelKey | translate"
											[attr.disabled]="control.readOnly ? '' : null"
											[attr.title]="
												control.readOnly ? ('pptx.options.lockedByHost' | translate) : null
											"
											(change)="emitText(control, $event)"
										/>
									}
								}
							</div>
						}
					}
					@if (section.special === 'themePicker') {
						<ng-content select="[themePicker]" />
					} @else if (section.special === 'customFonts') {
						<ng-content select="[customFonts]" />
					} @else if (section.special === 'clearCache') {
						<p class="pptx-ng-options-note">
							{{ 'pptx.options.save.clearCacheDescription' | translate }}
						</p>
						<button type="button" class="pptx-ng-options-btn" (click)="clearCache.emit()">
							{{ 'pptx.options.save.clearCacheNow' | translate }}
						</button>
					}
				</section>
			}
			<ng-content />
		</div>
	`,
	styles: [OPTIONS_PANE_STYLES],
})
export class OptionsPaneComponent {
	readonly tab = input.required<ViewerOptionsTabDefinition>();
	readonly options = input.required<ViewerOptions>();
	/** One control edited (applied live by the host). */
	readonly valueChange = output<OptionValueChange>();
	/** Options > Save > "Delete cached files" pressed. */
	readonly clearCache = output<void>();

	protected value(control: ViewerOptionsControl): ViewerOptionPrimitive | undefined {
		return readOptionValue(this.options(), control);
	}

	protected selectChoices(
		control: ViewerOptionsControl,
	): readonly { value: string; labelKey: string }[] {
		return control.kind === 'select' ? control.choices : [];
	}

	protected numberMin(control: ViewerOptionsControl): number {
		return control.kind === 'number' ? control.min : 0;
	}

	protected numberMax(control: ViewerOptionsControl): number {
		return control.kind === 'number' ? control.max : 0;
	}

	protected numberUnitKey(control: ViewerOptionsControl): string | undefined {
		return control.kind === 'number' ? control.unitKey : undefined;
	}

	protected emitToggle(control: ViewerOptionsControl, event: Event): void {
		this.emit(control, (event.target as HTMLElement & { checked: boolean }).checked);
	}

	protected emitSelect(control: ViewerOptionsControl, event: Event): void {
		this.emit(control, (event.target as HTMLElement & { value: string }).value);
	}

	protected emitNumber(control: ViewerOptionsControl, event: Event): void {
		if (control.kind !== 'number') {
			return;
		}
		const clamped = clampOptionNumber(
			(event.target as HTMLInputElement).value,
			control.min,
			control.max,
		);
		if (clamped !== undefined) {
			this.emit(control, clamped);
		}
	}

	protected emitText(control: ViewerOptionsControl, event: Event): void {
		this.emit(control, (event.target as HTMLInputElement).value);
	}

	private emit(control: ViewerOptionsControl, value: ViewerOptionPrimitive): void {
		// A host-locked setting (customization.options.locked) never changes.
		if (control.readOnly === true) {
			return;
		}
		this.valueChange.emit({ group: control.group, key: control.key, value });
	}
}
