// viewers/pptx/packages/vue/src/viewer/components/inspector/PresentationSettingsCard.vue
<script setup lang="ts">
import type { PptxPresentationProperties } from 'pptx-viewer-core';
import {
	printPropertiesFrameSlides,
	printPropertiesSlidesPerPage,
	withFrameSlides,
	withSlidesPerPage,
} from 'ooxml-ui/pptx';
import { useI18n } from 'vue-i18n';

/**
 * PresentationSettingsCard: deck-wide slide-show / print settings, shown in the
 * slide inspector. Vue port of the React `inspector/PresentationSettingsCards.tsx`
 * (`PresentationSettingsCard`). The parent owns `presentationProperties` and
 * commits each patch; the theme and slide-size cards from React are handled by
 * dedicated Vue surfaces and are not duplicated here.
 */
const props = withDefaults(
	defineProps<{
		presentationProperties: PptxPresentationProperties;
		canEdit?: boolean;
	}>(),
	{ canEdit: true },
);

const emit = defineEmits<{
	update: [patch: Partial<PptxPresentationProperties>];
}>();

const { t } = useI18n();

function onNumber(e: Event): number {
	return Number((e.target as HTMLInputElement).value);
}
</script>

<template>
	<div data-pptx-chrome="presentation-fields" class="space-y-1.5 text-[11px]">
		<label class="flex items-center justify-between gap-2">
			<span class="text-muted-foreground">{{ t('pptx.presentationSettings.showType') }}</span>
			<!-- Nested in its `<label>`, so without this its accessible label would
			     be the caption plus every option: see `SlideTransitionPanel.vue`. -->
			<pptx-ui-select
				class="w-28 max-md:min-h-[44px]!"
				:aria-label="t('pptx.presentationSettings.showType')"
				:disabled="!props.canEdit"
				:value="props.presentationProperties.showType ?? 'presented'"
				@change="
					emit('update', {
						showType: ($event.target as HTMLElement & { value: string }).value as
							'presented' | 'browsed' | 'kiosk',
					})
				"
			>
				<option value="presented">{{ t('pptx.presentationSettings.showTypePresented') }}</option>
				<option value="browsed">{{ t('pptx.presentationSettings.showTypeBrowsed') }}</option>
				<option value="kiosk">{{ t('pptx.presentationSettings.showTypeKiosk') }}</option>
			</pptx-ui-select>
		</label>

		<label class="flex items-center justify-between gap-2">
			<span class="text-muted-foreground">{{
				t('pptx.presentationSettings.loopContinuously')
			}}</span>
			<pptx-ui-checkbox
				:aria-label="t('pptx.presentationSettings.loopContinuously')"
				:disabled="!props.canEdit"
				:checked="Boolean(props.presentationProperties.loopContinuously)"
				@change="
					emit('update', {
						loopContinuously: ($event.target as HTMLElement & { checked: boolean }).checked,
					})
				"
			/>
		</label>

		<label class="flex items-center justify-between gap-2">
			<span class="text-muted-foreground">{{ t('pptx.presentationSettings.showNarration') }}</span>
			<pptx-ui-checkbox
				:aria-label="t('pptx.presentationSettings.showNarration')"
				:disabled="!props.canEdit"
				:checked="props.presentationProperties.showWithNarration !== false"
				@change="
					emit('update', {
						showWithNarration: ($event.target as HTMLElement & { checked: boolean }).checked,
					})
				"
			/>
		</label>

		<label class="flex items-center justify-between gap-2">
			<span class="text-muted-foreground">{{ t('pptx.presentationSettings.showAnimation') }}</span>
			<pptx-ui-checkbox
				:aria-label="t('pptx.presentationSettings.showAnimation')"
				:disabled="!props.canEdit"
				:checked="props.presentationProperties.showWithAnimation !== false"
				@change="
					emit('update', {
						showWithAnimation: ($event.target as HTMLElement & { checked: boolean }).checked,
					})
				"
			/>
		</label>

		<label class="flex items-center justify-between gap-2">
			<span class="text-muted-foreground">{{ t('pptx.presentationSettings.frameSlides') }}</span>
			<pptx-ui-checkbox
				:aria-label="t('pptx.presentationSettings.frameSlides')"
				:disabled="!props.canEdit"
				:checked="printPropertiesFrameSlides(props.presentationProperties.printProperties)"
				@change="
					emit('update', {
						printProperties: withFrameSlides(
							props.presentationProperties.printProperties,
							($event.target as HTMLElement & { checked: boolean }).checked,
						),
					})
				"
			/>
		</label>

		<label class="flex items-center justify-between gap-2">
			<span class="text-muted-foreground">{{ t('pptx.presentationSettings.slidesPerPage') }}</span>
			<input
				type="number"
				:min="1"
				:max="16"
				:disabled="!props.canEdit"
				class="w-20 rounded border border-border bg-muted px-2 py-1 text-xs"
				:value="printPropertiesSlidesPerPage(props.presentationProperties.printProperties)"
				@input="
					emit('update', {
						printProperties: withSlidesPerPage(
							props.presentationProperties.printProperties,
							onNumber($event),
						),
					})
				"
			/>
		</label>
	</div>
</template>

// viewers/pptx/packages/angular/src/viewer/presentation-settings-card.component.ts
/**
 * presentation-settings-card.component.ts: PRESENTATION card of the default
 * (no-selection) inspector, mirroring React's `PresentationSettingsCard`
 * (PresentationSettingsCards.tsx): show type, loop, narration, animation,
 * frame-slides and slides-per-page controls over `PptxPresentationProperties`.
 *
 * Edits patch the loader's `presentationProperties` signal (the same object
 * `LoadContentService.saveSlides` serialises) and mark the editor dirty.
 */
import {
	ChangeDetectionStrategy,
	Component,
	CUSTOM_ELEMENTS_SCHEMA,
	computed,
	inject,
	input,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxPresentationProperties } from 'pptx-viewer-core';

import {
	printPropertiesFrameSlides,
	printPropertiesSlidesPerPage,
	withFrameSlides,
	withSlidesPerPage,
} from 'ooxml-ui/pptx/render/presentation-print-settings';
import { EditorStateService } from './editor-state.service';
import { INSPECTOR_CARD_STYLES } from './inspector-card-styles';
import { LoadContentService } from './load-content.service';

@Component({
	selector: 'pptx-presentation-settings-card',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `
		<section class="icard pptx-editor-presentation-card" data-pptx-chrome="inspector-card">
			<h3 class="icard__heading" data-pptx-chrome="inspector-heading">
				{{ 'pptx.slideInspector.presentation' | translate }}
			</h3>
			<div data-pptx-chrome="presentation-fields">
				<label class="icard__row">
					<span class="icard__label">{{ 'pptx.presentationSettings.showType' | translate }}</span>
					<pptx-ui-select
						[attr.aria-label]="'pptx.presentationSettings.showType' | translate"
						class="icard__web-select"
						[disabled]="!canEdit()"
						[value]="props().showType ?? 'presented'"
						(change)="onShowTypeChange($event)"
					>
						<option value="presented">
							{{ 'pptx.presentationSettings.showTypePresented' | translate }}
						</option>
						<option value="browsed">
							{{ 'pptx.presentationSettings.showTypeBrowsed' | translate }}
						</option>
						<option value="kiosk">
							{{ 'pptx.presentationSettings.showTypeKiosk' | translate }}
						</option>
					</pptx-ui-select>
				</label>
				<label class="icard__row">
					<span class="icard__label">
						{{ 'pptx.presentationSettings.loopContinuously' | translate }}
					</span>
					<pptx-ui-checkbox
						[attr.aria-label]="'pptx.presentationSettings.loopContinuously' | translate"
						[disabled]="!canEdit()"
						[checked]="!!props().loopContinuously"
						(change)="onCheckbox($event, 'loopContinuously')"
					/>
				</label>
				<label class="icard__row">
					<span class="icard__label">
						{{ 'pptx.presentationSettings.showNarration' | translate }}
					</span>
					<pptx-ui-checkbox
						[attr.aria-label]="'pptx.presentationSettings.showNarration' | translate"
						[disabled]="!canEdit()"
						[checked]="props().showWithNarration !== false"
						(change)="onCheckbox($event, 'showWithNarration')"
					/>
				</label>
				<label class="icard__row">
					<span class="icard__label">
						{{ 'pptx.presentationSettings.showAnimation' | translate }}
					</span>
					<pptx-ui-checkbox
						[attr.aria-label]="'pptx.presentationSettings.showAnimation' | translate"
						[disabled]="!canEdit()"
						[checked]="props().showWithAnimation !== false"
						(change)="onCheckbox($event, 'showWithAnimation')"
					/>
				</label>
				<label class="icard__row">
					<span class="icard__label">{{
						'pptx.presentationSettings.frameSlides' | translate
					}}</span>
					<pptx-ui-checkbox
						[attr.aria-label]="'pptx.presentationSettings.frameSlides' | translate"
						[disabled]="!canEdit()"
						[checked]="frameSlides()"
						(change)="onFrameSlidesChange($event)"
					/>
				</label>
				<label class="icard__row">
					<span class="icard__label">
						{{ 'pptx.presentationSettings.slidesPerPage' | translate }}
					</span>
					<input
						type="number"
						class="icard__input icard__input--number"
						min="1"
						max="16"
						[disabled]="!canEdit()"
						[value]="slidesPerPage()"
						(change)="onSlidesPerPageChange($event)"
					/>
				</label>
			</div>
		</section>
	`,
	styles: [INSPECTOR_CARD_STYLES],
})
export class PresentationSettingsCardComponent {
	/** Whether the controls are enabled. */
	readonly canEdit = input<boolean>(true);

	private readonly loader = inject(LoadContentService);
	private readonly editor = inject(EditorStateService);

	protected readonly props = this.loader.presentationProperties;

	protected readonly frameSlides = computed(() =>
		printPropertiesFrameSlides(this.props().printProperties),
	);
	protected readonly slidesPerPage = computed(() =>
		printPropertiesSlidesPerPage(this.props().printProperties),
	);

	private patch(patch: Partial<PptxPresentationProperties>): void {
		this.loader.presentationProperties.update((current) => ({ ...current, ...patch }));
		this.editor.dirty.set(true);
	}

	protected onShowTypeChange(event: Event): void {
		const value = (event.target as HTMLElement & { value: string }).value;
		this.patch({ showType: value as 'presented' | 'browsed' | 'kiosk' });
	}

	protected onCheckbox(
		event: Event,
		key: 'loopContinuously' | 'showWithNarration' | 'showWithAnimation',
	): void {
		this.patch({ [key]: (event.target as HTMLElement & { checked: boolean }).checked });
	}

	protected onFrameSlidesChange(event: Event): void {
		const checked = (event.target as HTMLElement & { checked: boolean }).checked;
		this.patch({ printProperties: withFrameSlides(this.props().printProperties, checked) });
	}

	protected onSlidesPerPageChange(event: Event): void {
		const value = Number((event.target as HTMLInputElement).value);
		if (Number.isFinite(value) && value >= 1) {
			this.patch({ printProperties: withSlidesPerPage(this.props().printProperties, value) });
		}
	}
}
