// viewers/pptx/packages/svelte/src/viewer/presentation/PresentationTransitionOverlay.svelte
<script lang="ts">
	/**
	 * PresentationTransitionOverlay: animates a slide change in presentation mode
	 * (Svelte port of the Vue overlay of the same name). It stacks two
	 * {@link SlideStage} layers, both scaled identically to the underlying
	 * presentation frame:
	 *   - the outgoing (old) slide as a snapshot layer, and
	 *   - the incoming (new) slide.
	 *
	 * The incoming slide's transition is mapped to CSS `animation` shorthands via
	 * the framework-agnostic {@link resolveSlideTransition}; each layer's z-index
	 * comes from `outgoingOnTop`. When the configured duration elapses it calls
	 * `ondone`, at which point the host drops the overlay and leaves the static
	 * incoming slide rendered by its main stage. The `@keyframes` themselves are
	 * injected once at document level (see `keyframes.ts`).
	 */
	import type { PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';
	import {
		applySlideTransitionSound,
		getFragmentedTransitionDescriptor,
		resolveSlideTransition,
		resolveTransitionDurationMs,
	} from 'ooxml-ui/pptx';
	import type { CanvasSize, CssStyleMap } from 'ooxml-ui/pptx';
	import { onDestroy, onMount } from 'svelte';

	import { playAnimationSound, stopAnimationSound } from './animation-sound';
	import FragmentedTransitionLayer from './FragmentedTransitionLayer.svelte';
	import MorphExtraLayers from './MorphExtraLayers.svelte';
	import { useMorphTransitionOverlay } from './use-morph-transition-overlay.svelte';
	import SlideStage from '../components/SlideStage.svelte';
	import { styleToString } from '../style';

	const {
		outgoingSlide,
		incomingSlide,
		canvasSize,
		mediaDataUrls,
		scale = 1,
		transition,
		ondone,
	}: {
		outgoingSlide: PptxSlide | undefined;
		incomingSlide: PptxSlide | undefined;
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		scale?: number;
		transition: PptxSlideTransition | undefined;
		ondone: () => void;
	} = $props();

	const animations = $derived(resolveSlideTransition(transition));
	/** Effective duration (ms); `0` for instant (none/cut). */
	const durationMs = $derived(resolveTransitionDurationMs(transition));

	/**
	 * Multi-fragment descriptor for the seven cinematic transitions measured
	 * as many independent fragments/particles/panels (vortex, honeycomb,
	 * glitter, shred, fracture, curtains, airplane). `undefined` for every
	 * other type, in which case `animations` above (the single-layer
	 * resolver) drives both layers exactly as before.
	 */
	const fragmented = $derived(
		getFragmentedTransitionDescriptor(
			transition?.type ?? 'none',
			durationMs,
			transition?.direction,
			transition?.spokes,
			transition?.pattern,
		),
	);

	function layerStyle(animation: string, zIndex: number): CssStyleMap {
		const style: CssStyleMap = { zIndex };
		if (animation !== 'none') {
			style.animation = animation;
		}
		return style;
	}

	/**
	 * Morph moves individual shapes between the two slides rather than wiping the
	 * whole surface, so when it is active the incoming layer plays per-element
	 * keyframes (scoped by `data-pptx-morph-incoming`) and the outgoing layer
	 * animates each of its own shapes: gliding onto its counterpart (dissolving
	 * into it when its appearance changed) or fading out in place without one.
	 * See `use-morph-transition-overlay.svelte.ts`.
	 */
	const morph = useMorphTransitionOverlay({
		transition: () => transition,
		outgoingSlide: () => outgoingSlide,
		incomingSlide: () => incomingSlide,
		durationMs: () => durationMs,
	});
	const morphPlan = $derived(morph.morphPlan);
	const morphOutgoingSlide = $derived(morph.morphOutgoingSlide);
	const morphLiftedSlide = $derived(morph.morphLiftedSlide);
	const morphCrossfadeGroups = $derived(morph.morphCrossfadeGroups);
	const morphCss = $derived(morph.morphCss);

	// A layer-wide animation would drag every shape as one block and cancel the
	// morph, so the layers stay unanimated while a plan is active.
	const outgoingZIndex = $derived(morphPlan ? 2 : animations.outgoingOnTop ? 2 : 1);
	const incomingZIndex = $derived(morphPlan ? 1 : animations.outgoingOnTop ? 1 : 2);
	const outgoingStyle = $derived(
		styleToString(layerStyle(morphPlan ? 'none' : animations.outgoing, outgoingZIndex)),
	);
	const incomingStyle = $derived(
		styleToString(layerStyle(morphPlan ? 'none' : animations.incoming, incomingZIndex)),
	);
	const liftedStyle = styleToString(layerStyle('none', 3));

	/**
	 * Play or stop this transition's sound action (`p:sndAc/p:stSnd`/`p:endSnd`)
	 * the instant it starts. `transition.soundPath` is a raw in-archive path;
	 * `mediaDataUrls` is the same Blob-URL cache the load pipeline
	 * pre-populates for it (`collectAnimationSoundPaths`, extended to also
	 * collect a slide transition's own sound). Reuses the per-effect sound
	 * singleton (`animation-sound.ts`) so a transition sound and an animation
	 * sound cannot talk over each other, matching PowerPoint's "one sound
	 * plays at a time" behaviour. NOT stopped on this component's own
	 * destroy: a "Loop Until Next Sound" sound must keep playing across the
	 * static period between this overlay tearing down and the next
	 * transition's own sound action; the presentation controller stops it on
	 * leaving the show.
	 */
	$effect(() => {
		applySlideTransitionSound(transition, (soundPath) => mediaDataUrls.get(soundPath), {
			play: playAnimationSound,
			stop: stopAnimationSound,
		});
	});

	let timer: ReturnType<typeof setTimeout> | null = null;

	onMount(() => {
		// A small buffer past the animation duration lets the CSS `forwards` fill
		// settle before the host swaps back to the static slide.
		timer = setTimeout(
			() => {
				timer = null;
				ondone();
			},
			Math.max(0, durationMs) + 50,
		);
	});

	onDestroy(() => {
		if (timer !== null) {
			clearTimeout(timer);
			timer = null;
		}
	});
</script>

<div class="pptx-svelte-transition-overlay" data-pptx-transition-overlay>
	{#if morphPlan}
		<!-- eslint-disable-next-line svelte/no-at-html-tags -- generated keyframes, no user input -->
		{@html `<style>${morphCss}</style>`}
	{/if}
	{#if !morphPlan && fragmented?.outgoing}
		<FragmentedTransitionLayer
			layer={fragmented.outgoing}
			slide={outgoingSlide}
			{canvasSize}
			{mediaDataUrls}
			{scale}
			zIndex={outgoingZIndex}
			layerName="outgoing"
		/>
	{:else}
		<div
			class="pptx-svelte-transition-layer"
			data-pptx-transition-layer="outgoing"
			data-pptx-morph-outgoing={morphPlan ? 'true' : undefined}
			style={outgoingStyle}
		>
			<!-- transparentBackground during a morph: this layer sits ABOVE the
			     incoming slide and only carries the departing shapes, so painting the
			     outgoing slide's own (always opaque) background here would cover the
			     whole morph with a flat slab for its entire duration. -->
			<SlideStage
				slide={morphPlan ? morphOutgoingSlide : outgoingSlide}
				{canvasSize}
				{mediaDataUrls}
				{scale}
				transparentBackground={Boolean(morphPlan)}
			/>
		</div>
	{/if}
	{#if !morphPlan && fragmented?.incoming}
		<FragmentedTransitionLayer
			layer={fragmented.incoming}
			slide={incomingSlide}
			{canvasSize}
			{mediaDataUrls}
			{scale}
			zIndex={incomingZIndex}
			layerName="incoming"
		/>
	{:else}
		<div
			class="pptx-svelte-transition-layer"
			data-pptx-transition-layer="incoming"
			data-pptx-morph-incoming={morphPlan ? 'true' : undefined}
			style={incomingStyle}
		>
			<SlideStage slide={incomingSlide} {canvasSize} {mediaDataUrls} {scale} />
		</div>
	{/if}
	<!-- The two morph-only extra layers (arriving-above-departing "lifted"
	     shapes, and same-pair crossfade groups) - see `MorphExtraLayers.svelte`. -->
	<MorphExtraLayers
		liftedSlide={morphLiftedSlide}
		{liftedStyle}
		crossfadeGroups={morphCrossfadeGroups}
		{canvasSize}
		{mediaDataUrls}
		{scale}
	/>
</div>

<style>
	.pptx-svelte-transition-overlay {
		position: absolute;
		inset: 0;
		overflow: hidden;
		pointer-events: none;
	}

	/* `inset: 0`, not `top/left: 0`: the stage inside scales with a CSS
	   `transform`, which never changes its laid-out box, so an auto-sized layer
	   measures the deck's NATIVE size (1280x720) while the stage paints the
	   display size (1920x1080). With `overflow: hidden` that cropped every
	   transition to a deck-sized top-left corner and the rest of the screen cut
	   straight to the next slide. Pinning to the overlay (already the frame's
	   scaled footprint) puts the clip on the slide edge, where it belongs. */
	.pptx-svelte-transition-layer {
		position: absolute;
		inset: 0;
		overflow: hidden;
		will-change: transform, opacity, clip-path, filter;
	}
</style>

// viewers/pptx/packages/angular/src/viewer/presentation-transition-overlay.component.ts
import { NgStyle } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	effect,
	inject,
	input,
	output,
} from '@angular/core';
import type { PptxElement, PptxSlide, PptxSlideTransition } from 'pptx-viewer-core';

import type { CanvasSize } from 'ooxml-ui/pptx';
import { applySlideTransitionSound, buildMorphScopedCss } from 'ooxml-ui/pptx';
import { playAnimationSound, stopAnimationSound } from './animation-sound';
import { FragmentedTransitionLayerComponent } from './fragmented-transition-layer.component';
import { MorphExtraLayersComponent } from './morph-extra-layers.component';
import { createTransitionOverlayState } from './presentation-transition-overlay-state';
import { SlideCanvasComponent } from './slide-canvas.component';
import { ensureTransitionKeyframes } from './transition-keyframes';

export {
	classicIncomingLayerSlide,
	morphCrossfadeGroupSlides,
	morphLiftedSlide,
} from './presentation-transition-overlay-morph';
export type { MorphCrossfadeGroupSlides } from './presentation-transition-overlay-morph';

/** Safety margin (ms) added to the animation duration before firing complete. */
const COMPLETE_MARGIN_MS = 50;

/**
 * PresentationTransitionOverlayComponent: plays a PowerPoint slide transition
 * over the presentation stage.
 *
 * Renders the *outgoing* (previous) slide as an absolutely-positioned layer
 * with the resolved CSS exit animation; the *incoming* slide is rendered by the
 * underlying stage (the existing `pptx-presentation-overlay`). The `outgoingOnTop`
 * descriptor controls whether the outgoing layer sits above or below the stage,
 * letting cover/uncover/push read correctly. Fires `complete` once the animation
 * finishes so the orchestrator can tear the overlay down.
 *
 * Selector: `pptx-presentation-transition-overlay`
 *
 * Inputs:
 *   - `outgoingSlide`    (required): the leaving slide to animate
 *   - `canvasSize`       (required): logical slide dimensions (px)
 *   - `transition`       (required): the transition definition (from the slide)
 *   - `templateElements`: master/layout elements behind the outgoing slide
 *   - `mediaDataUrls`   : data-URL map for media assets
 *   - `durationMs`      : explicit override; otherwise derived from `transition`
 *   - `zoom`            : the stage's live zoom, so the outgoing slide animates
 *                         at the same size as the incoming one
 *
 * Outputs:
 *   - `complete`: emits void when the transition animation completes
 *
 * Designed to compose with `PresentationOverlayComponent` WITHOUT editing it:
 * the orchestrator stacks this overlay on top of the stage while a transition
 * is in flight and removes it on `complete`.
 */
@Component({
	selector: 'pptx-presentation-transition-overlay',
	host: { 'data-pptx-transition-overlay': '' },
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [
		NgStyle,
		SlideCanvasComponent,
		FragmentedTransitionLayerComponent,
		MorphExtraLayersComponent,
	],
	styleUrl: './presentation-transition-overlay.component.css',
	templateUrl: './presentation-transition-overlay.component.html',
})
export class PresentationTransitionOverlayComponent {
	// ------------------------------------------------------------------
	// Inputs
	// ------------------------------------------------------------------

	readonly outgoingSlide = input.required<PptxSlide>();
	readonly canvasSize = input.required<CanvasSize>();
	readonly transition = input.required<PptxSlideTransition>();
	readonly templateElements = input<readonly PptxElement[]>([]);
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	/** Explicit duration override (ms). When omitted, derived from `transition`. */
	readonly durationMs = input<number | undefined>(undefined);
	/**
	 * The stage's live zoom (the same value the underlying `pptx-slide-canvas`
	 * renders at). The outgoing layer MUST use it: left at 1 the leaving slide
	 * animates out at its intrinsic size over a full-screen incoming slide,
	 * which reads as the slide snapping small the instant a transition starts.
	 */
	readonly zoom = input<number>(1);
	/**
	 * The arriving slide. Required only for Morph, which has to match shapes
	 * across both slides; every other transition ignores it.
	 */
	readonly incomingSlide = input<PptxSlide | undefined>(undefined);

	// ------------------------------------------------------------------
	// Outputs
	// ------------------------------------------------------------------

	readonly complete = output<void>();

	// ------------------------------------------------------------------
	// Internal
	// ------------------------------------------------------------------

	private readonly destroyRef = inject(DestroyRef);
	/** Active completion timer handle, so re-running re-arms cleanly. */
	private completeTimer: ReturnType<typeof setTimeout> | null = null;
	/** Whether `complete` has already fired for the current run. */
	private fired = false;

	constructor() {
		ensureTransitionKeyframes();

		// Re-arm the completion timer + sound whenever the transition or its
		// resolved duration changes.
		effect(() => {
			const ms = this.resolvedDurationMs();
			this.applyTransitionSound(this.transition());
			this.armCompletion(ms);
		});

		// Morph keyframes + per-element rules. They must reach the LIVE stage,
		// which is a sibling component, so they are injected at document level.
		// Element ids embed their slide path, so unscoped rules cannot leak onto
		// another slide's elements.
		effect(() => {
			const plan = this.morphPlan();
			this.applyMorphStyle(
				plan
					? [
							buildMorphScopedCss(plan, '', 'incoming'),
							buildMorphScopedCss(plan, 'data-pptx-morph-outgoing', 'outgoing'),
							// Scoped, so it outranks the unscoped `incoming` rule that holds
							// the stage's copy of the same element invisible.
							buildMorphScopedCss(plan, 'data-pptx-morph-lifted', 'lifted'),
						].join('\n')
					: null,
			);
		});

		this.destroyRef.onDestroy(() => {
			this.clearTimer();
			stopAnimationSound();
			this.applyMorphStyle(null);
		});
	}

	/** Owned `<style>` element carrying the active morph rules, if any. */
	private morphStyle: HTMLStyleElement | null = null;

	private applyMorphStyle(css: string | null): void {
		if (typeof document === 'undefined') {
			return;
		}
		if (css === null) {
			this.morphStyle?.remove();
			this.morphStyle = null;
			return;
		}
		if (!this.morphStyle) {
			this.morphStyle = document.createElement('style');
			document.head.appendChild(this.morphStyle);
		}
		this.morphStyle.textContent = css;
	}

	// ------------------------------------------------------------------
	// Derived state (see `presentation-transition-overlay-state.ts`)
	// ------------------------------------------------------------------

	private readonly state = createTransitionOverlayState({
		outgoingSlide: this.outgoingSlide,
		incomingSlide: this.incomingSlide,
		canvasSize: this.canvasSize,
		transition: this.transition,
		templateElements: this.templateElements,
		durationMs: this.durationMs,
		zoom: this.zoom,
	});

	protected readonly resolvedDurationMs = this.state.resolvedDurationMs;
	protected readonly animations = this.state.animations;
	protected readonly fragmented = this.state.fragmented;
	protected readonly fragmentedOutgoing = this.state.fragmentedOutgoing;
	protected readonly fragmentedIncoming = this.state.fragmentedIncoming;
	protected readonly fragmentedOutgoingZIndex = this.state.fragmentedOutgoingZIndex;
	protected readonly fragmentedIncomingZIndex = this.state.fragmentedIncomingZIndex;
	protected readonly incomingFragmentSlide = this.state.incomingFragmentSlide;
	protected readonly morphPlan = this.state.morphPlan;
	protected readonly isMorph = this.state.isMorph;
	protected readonly layerSlide = this.state.layerSlide;
	protected readonly liftedSlide = this.state.liftedSlide;
	protected readonly crossfadeGroups = this.state.crossfadeGroups;
	protected readonly layerStyle = this.state.layerStyle;
	protected readonly incomingLayerSlide = this.state.incomingLayerSlide;
	protected readonly incomingLayerStyle = this.state.incomingLayerStyle;
	protected readonly slideBoxStyle = this.state.slideBoxStyle;

	// ------------------------------------------------------------------
	// Completion timing + sound
	// ------------------------------------------------------------------

	private armCompletion(durationMs: number): void {
		this.clearTimer();
		this.fired = false;
		if (typeof setTimeout === 'undefined') {
			return;
		}
		this.completeTimer = setTimeout(() => {
			this.completeTimer = null;
			if (this.fired) {
				return;
			}
			this.fired = true;
			this.complete.emit();
		}, durationMs + COMPLETE_MARGIN_MS);
	}

	private clearTimer(): void {
		if (this.completeTimer !== null) {
			clearTimeout(this.completeTimer);
			this.completeTimer = null;
		}
	}

	/**
	 * Play or stop this transition's sound action (`p:sndAc/p:stSnd`/`p:endSnd`).
	 *
	 * `transition.soundPath` is a raw in-archive path (e.g. `ppt/media/media3.wav`)
	 * that a bare `Audio` element constructed straight from it cannot fetch; it
	 * must be resolved through `mediaDataUrls()`, the same Blob-URL cache
	 * `load-content.service.ts`
	 * pre-populates via `collectAnimationSoundPaths` (extended to also collect
	 * `slide.transition?.soundPath` alongside per-effect animation sounds).
	 * Reuses the shared per-effect sound singleton (`animation-sound.ts`) rather
	 * than a private `Audio` element, so a transition sound and an animation
	 * sound cannot talk over each other, matching PowerPoint's "one sound plays
	 * at a time" behaviour.
	 */
	private applyTransitionSound(transition: PptxSlideTransition): void {
		applySlideTransitionSound(transition, (soundPath) => this.mediaDataUrls().get(soundPath), {
			play: playAnimationSound,
			stop: stopAnimationSound,
		});
	}
}
