// viewers/pptx/packages/svelte/src/viewer/components/PresentationToolbar.svelte
<script lang="ts">
	/**
	 * The slide-show toolbar: the floating, auto-hiding bar at the bottom centre
	 * of a running show.
	 *
	 * A thin adapter around the shared `pptx-ui-present-toolbar`. The inventory,
	 * order, measurements, colour palettes and elapsed readout come from
	 * `pptx-viewer-shared` (the element renders the shared `present-chrome`
	 * inventory), which React, Vue, Angular and Vanilla now share too. This keeps
	 * the positioned, auto-hiding wrapper (`PresentToolbarChrome`) and routes the
	 * element's typed intents to the annotation model.
	 *
	 * The wrapper metrics arrive as CSS custom properties on an inline `style`
	 * attribute because a Svelte scoped style block is compiled ahead of time and
	 * cannot read a TypeScript value. (Do not write the literal style tag in this
	 * comment: svelte2tsx, which `svelte-check` runs on, scans for it textually
	 * and would decide the script block ends here.)
	 */
	import { presentToolbarStyleAttr, toggleBlackboard } from 'ooxml-ui/pptx';
	import type {
		PresentationBlackout,
		PresentToolbarRequestEvent,
		PresentToolbarViewState,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import type { PresentationAnnotations } from '../presentation/presentation-annotations.svelte';
	import { PresentToolbarChrome } from './presentation-toolbar.svelte';

	const {
		annotations,
		chrome = new PresentToolbarChrome(),
		current,
		total,
		presenterMode,
		blackout = 'none',
		onblackoutchange,
		onmove,
		onpresenterview,
		onexit,
		popupToolbarEnabled = true,
	}: {
		annotations: PresentationAnnotations;
		/**
		 * Fade / auto-hide state. Injected by the viewer so PowerPoint's Ctrl+H can
		 * reach the SAME flag from the show's key handler; the default keeps this
		 * component usable on its own (and in its own tests).
		 */
		chrome?: PresentToolbarChrome;
		/** Zero-based index of the slide on screen. */
		current: number;
		total: number;
		presenterMode: boolean;
		/** The show's blackout state, mirrored from the presenter snapshot. */
		blackout?: PresentationBlackout;
		/** Route a blackout change back to the presenter session's snapshot. */
		onblackoutchange?: (value: PresentationBlackout) => void;
		/** Step the show forward (1) or back (-1). */
		onmove: (direction: 1 | -1) => void;
		onpresenterview: () => void;
		onexit: () => void;
		/** File > Options > Advanced > "Show popup toolbar" (default true). */
		popupToolbarEnabled?: boolean;
	} = $props();

	const t = useTranslator();
	const metricVars = presentToolbarStyleAttr();

	// bind:this writes this (invisible to the linter's prefer-const analysis).
	// eslint-disable-next-line prefer-const
	let wrapperEl = $state<HTMLDivElement | undefined>(undefined);

	$effect(() =>
		chrome.attach({
			// `offsetParent` IS the positioned show surface the bar is absolutely
			// placed against, so the trigger zone needs no prop drilling.
			getContainer: () => (wrapperEl?.offsetParent as HTMLElement | null) ?? null,
			popupToolbarEnabled: () => popupToolbarEnabled,
		}),
	);

	const view = $derived<PresentToolbarViewState>({
		current,
		total,
		tool: annotations.tool,
		penColor: annotations.penColor,
		highlighterColor: annotations.highlighterColor,
		hasAnnotations: annotations.count > 0,
		blackout,
		presenterViewVisible: true,
		presenterViewActive: presenterMode,
		startTime: chrome.startedAt,
		translate: t,
	});

	function request(event: PresentToolbarRequestEvent): void {
		const intent = event.detail;
		switch (intent.id) {
			case 'move':
				onmove(intent.direction);
				break;
			case 'tool':
				// Choose a tool, or disarm it when it is already active (PowerPoint's toggle).
				annotations.tool = annotations.tool === intent.tool ? 'none' : intent.tool;
				break;
			case 'color':
				// Picking a colour also arms its tool, matching React.
				if (intent.tool === 'pen') {
					annotations.penColor = intent.color;
				} else {
					annotations.highlighterColor = intent.color;
				}
				annotations.tool = intent.tool;
				break;
			case 'blackboard': {
				// One click arms the black screen + pen together, or disarms both.
				const next = toggleBlackboard(blackout, annotations.tool);
				annotations.tool = next.tool;
				onblackoutchange?.(next.blackout);
				break;
			}
			case 'clear':
				annotations.clear();
				break;
			case 'presenterView':
				onpresenterview();
				break;
			case 'end':
				onexit();
		}
	}

	/**
	 * Contain pointer traffic: without this a control press would ALSO reach the
	 * stage's click-to-advance handler and skip a slide. It has to be a template
	 * handler, not an action calling `addEventListener`: Svelte 5 delegates
	 * `click`/`pointerdown` from the app root, so a real listener on this
	 * container would stop propagation before the delegated walk ever reached
	 * the button that was actually pressed.
	 */
	function stop(event: Event): void {
		event.stopPropagation();
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions, a11y_click_events_have_key_events -->
<div
	class="pptx-svelte-present-wrapper"
	class:hidden={!chrome.visible}
	style={metricVars}
	bind:this={wrapperEl}
	onmouseenter={() => chrome.enter()}
	onmouseleave={() => chrome.leave()}
	onclick={stop}
	onpointerdown={stop}
>
	<pptx-ui-present-toolbar state={view} onpresent-toolbar-request={request}
	></pptx-ui-present-toolbar>
</div>

<style>
	.pptx-svelte-present-wrapper { position: absolute; bottom: var(--pptx-pt-bottom); left: 50%; z-index: var(--pptx-pt-z); transform: translateX(-50%); transition: opacity var(--pptx-pt-fade) ease; }
	.pptx-svelte-present-wrapper.hidden { opacity: 0; pointer-events: none; }
</style>

// viewers/pptx/packages/angular/src/viewer/presentation-toolbar.component.ts
/**
 * presentation-toolbar.component.ts: the floating bottom-centre toolbar of a
 * running slide show.
 *
 * Selector: `pptx-presentation-toolbar`
 *
 * A thin adapter around the shared `pptx-ui-present-toolbar`. The inventory, the
 * order, the measurements, the colour palettes and the elapsed readout are NOT
 * decided here: the element renders them from `PRESENT_TOOLBAR_CONTROLS` /
 * `PRESENT_TOOLBAR_METRICS` in `pptx-viewer-shared`, which is what stops this bar
 * drifting from the other four bindings again. Angular previously shipped a
 * bottom-LEFT strip of four annotation tools plus a captions button, so a
 * presenter had no visible way to step slides, read the elapsed time, open
 * presenter view or leave the show.
 *
 * The component HOST is the auto-hiding positioner (it carries
 * `PRESENT_TOOLBAR_CLASSES.wrapper` and the opacity), so the show overlay only has
 * to place the element; positioning and fade live with the behaviour that drives
 * them.
 *
 * Annotation state is read from the overlay-provided
 * {@link PresentationAnnotationsService} rather than passed in, the same way
 * `PresentationAnnotationOverlayComponent` does it, which keeps the input
 * surface to the four things the bar cannot know: where in the deck it is, when
 * the show started, whether presenter view is up, and how to leave.
 */
import {
	ChangeDetectionStrategy,
	Component,
	CUSTOM_ELEMENTS_SCHEMA,
	DestroyRef,
	ElementRef,
	HostListener,
	computed,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

import { isInBottomTriggerZone, PRESENT_TOOLBAR_CLASSES } from 'ooxml-ui/pptx';
import type {
	PresentToolbarIntent,
	PresentToolbarRequestEvent,
	PresentToolbarViewState,
} from 'ooxml-ui/pptx';
import { PresentationAnnotationsService } from './presentation-annotations.service';
import { PresentToolbarAutoHide, runBlackboardToggle } from './presentation-toolbar-view';
import { PresenterWindowService } from './presenter-window.service';
import { translationsSignal } from './translations-signal';

export type { PresentToolbarAction } from './presentation-toolbar-view';

@Component({
	selector: 'pptx-presentation-toolbar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `
		<pptx-ui-present-toolbar [state]="view()" (present-toolbar-request)="request($event)" />
	`,
	styles: [':host { display: block; }'],
	host: {
		'[class]': 'wrapperClass',
		'[style.opacity]': 'visible() ? 1 : 0',
		'[style.pointer-events]': 'visible() ? "auto" : "none"',
		'(mouseenter)': 'onMouseEnter()',
		'(mouseleave)': 'onMouseLeave()',
	},
})
export class PresentationToolbarComponent {
	// ------------------------------------------------------------------
	// Inputs / outputs
	// ------------------------------------------------------------------

	/** Zero-based index of the slide on screen. */
	readonly currentSlideIndex = input.required<number>();
	/** Total slides in the show. */
	readonly totalSlides = input.required<number>();
	/** Epoch ms the show started; the readout counts from mount when `null`. */
	readonly presentationStartTime = input<number | null>(null);
	/** Whether the presenter view window is up (reflected on its toggle). */
	readonly presenterMode = input<boolean>(false);
	/** File > Options > Advanced > "Show popup toolbar" (default true). */
	readonly popupToolbarEnabled = input<boolean>(true);

	/** Step the show forward (1) or back (-1). */
	readonly move = output<1 | -1>();
	/** Leave the show. */
	readonly endPresentation = output<void>();
	/** Open or close the presenter view. */
	readonly presenterViewToggle = output<void>();

	// ------------------------------------------------------------------
	// Injected state
	// ------------------------------------------------------------------

	protected readonly annotations = inject(PresentationAnnotationsService);
	private readonly presenterWindow = inject(PresenterWindowService);
	private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
	private readonly translate = inject(TranslateService);
	private readonly translations = translationsSignal(this.translate);

	protected readonly wrapperClass = PRESENT_TOOLBAR_CLASSES.wrapper;

	// ------------------------------------------------------------------
	// Derived state
	// ------------------------------------------------------------------

	/** Whether the bar is currently faded in (auto-hide). */
	readonly visible = signal(false);

	private readonly mountedAt = Date.now();

	protected readonly view = computed<PresentToolbarViewState>(() => {
		this.translations();
		return {
			current: this.currentSlideIndex(),
			total: this.totalSlides(),
			tool: this.annotations.tool(),
			penColor: this.annotations.penColor(),
			highlighterColor: this.annotations.highlighterColor(),
			hasAnnotations: this.annotations.annotationStrokes().length > 0,
			blackout: this.presenterWindow.snapshot().blackout,
			presenterViewVisible: true,
			presenterViewActive: this.presenterMode(),
			startTime: this.presentationStartTime() ?? this.mountedAt,
			translate: (key, params) => this.translate.instant(key, params),
		};
	});

	private readonly autoHide = new PresentToolbarAutoHide((value) => {
		this.visible.set(value);
	});

	constructor() {
		inject(DestroyRef).onDestroy(() => {
			this.autoHide.dispose();
		});
	}

	// ------------------------------------------------------------------
	// Auto-hide
	// ------------------------------------------------------------------

	@HostListener('document:mousemove', ['$event'])
	protected onDocumentMouseMove(event: MouseEvent): void {
		if (!this.popupToolbarEnabled()) {
			return;
		}
		const surface = this.host.nativeElement.parentElement;
		if (surface) {
			const rect = surface.getBoundingClientRect();
			if (isInBottomTriggerZone(event.clientY, rect.height, rect.top)) {
				this.autoHide.poke();
				return;
			}
		}
		// Any movement reveals the bar and restarts the countdown.
		this.autoHide.poke();
	}

	/** PowerPoint's Ctrl+H: flip the bar's visibility. */
	toggleVisible(): void {
		this.visible.update((shown) => !shown);
	}

	protected onMouseEnter(): void {
		this.autoHide.enter();
	}

	protected onMouseLeave(): void {
		this.autoHide.leave();
	}

	// ------------------------------------------------------------------
	// Controls
	// ------------------------------------------------------------------

	protected request(event: Event): void {
		const intent: PresentToolbarIntent = (event as PresentToolbarRequestEvent).detail;
		switch (intent.id) {
			case 'move':
				this.move.emit(intent.direction);
				return;
			case 'tool':
				this.annotations.setTool(intent.tool);
				return;
			case 'color':
				if (intent.tool === 'pen') {
					this.annotations.setPenColor(intent.color);
				} else {
					this.annotations.setHighlighterColor(intent.color);
				}
				if (this.annotations.tool() !== intent.tool) {
					this.annotations.setTool(intent.tool);
				}
				return;
			case 'blackboard':
				runBlackboardToggle({
					blackout: this.presenterWindow.snapshot().blackout,
					tool: this.annotations.tool(),
					setBlackout: (blackout) => this.presenterWindow.updateSnapshot({ blackout }),
					setTool: (tool) => this.annotations.setTool(tool),
				});
				return;
			case 'clear':
				this.annotations.clearAnnotations();
				return;
			case 'presenterView':
				this.presenterViewToggle.emit();
				return;
			case 'end':
				this.endPresentation.emit();
		}
	}
}
