// viewers/pptx/packages/svelte/src/viewer/components/ReadingViewOverlay.svelte
<script lang="ts">
	/**
	 * PowerPoint's Reading View.
	 *
	 * The deck at full window size with the editor chrome reduced to a nav bar.
	 * This is NOT the slide show: no Fullscreen API, no pointer tools, no
	 * presenter console, no blackout. The reader gets the slide, a counter and
	 * three controls, and Escape puts them back in the editor on the slide they
	 * stopped at.
	 *
	 * `position: fixed; inset: 0` fills the browser window without requesting
	 * fullscreen, which is exactly the difference between this view and a show.
	 * The slide itself is drawn by the ordinary `SlideStage`, so Reading View can
	 * never disagree with the main canvas about how a deck looks, and it applies
	 * no element cap: this is the one view whose entire purpose is reading the
	 * content.
	 */
	import ChevronLeft from '@lucide/svelte/icons/chevron-left';
	import ChevronRight from '@lucide/svelte/icons/chevron-right';
	import X from '@lucide/svelte/icons/x';
	import type { PptxSlide } from 'pptx-viewer-core';
	import {
		READING_VIEW_ATTR,
		READING_VIEW_COUNTER_ATTR,
		READING_VIEW_STAGE_ATTR,
	} from 'ooxml-ui/pptx';
	import type { CanvasSize } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../i18n/context';
	import { ReadingViewSession } from '../state/reading-view.svelte';
	import { styleToString } from '../style';
	import SlideStage from './SlideStage.svelte';

	const {
		slides,
		canvasSize,
		mediaDataUrls,
		activeSlideIndex,
		onexit,
	}: {
		slides: PptxSlide[];
		canvasSize: CanvasSize;
		mediaDataUrls: Map<string, string>;
		/** Slide the editor was on when the view was opened. */
		activeSlideIndex: number;
		/** Receives the slide the reader ended on. */
		onexit: (slideIndex: number) => void;
	} = $props();

	const t = useTranslator();

	// The session is built once: it owns the reader's position, which must not be
	// reset when the editor underneath reacts to a key that also reached it.
	// svelte-ignore state_referenced_locally
	const session = new ReadingViewSession({
		initialSlideIndex: activeSlideIndex,
		getSlideCount: () => slides.length,
		getCanvasSize: () => canvasSize,
		onExit: (slideIndex) => onexit(slideIndex),
	});

	// Capture phase, deliberately: `<svelte:window onkeydown>` can only bubble,
	// and by then the editor still mounted underneath has already acted on the
	// key. Reading View is modal over it, so the key has to be intercepted on
	// the way down.
	$effect(() => {
		const handle = (event: KeyboardEvent): void => session.handleKey(event);
		window.addEventListener('keydown', handle, true);
		return () => window.removeEventListener('keydown', handle, true);
	});

	const slide = $derived(slides[session.state.slideIndex]);
	const stageStyle = $derived(
		styleToString({
			width: `${Math.max(canvasSize.width, 1) * session.scale}px`,
			height: `${Math.max(canvasSize.height, 1) * session.scale}px`,
		}),
	);

	// Neutral data attributes rather than classes: `e2e/` addresses all five
	// bindings through one selector, and each binding styles itself as it likes.
	const rootAttrs = { [READING_VIEW_ATTR]: 'true' };
	const stageAttrs = { [READING_VIEW_STAGE_ATTR]: 'true' };
	const counterAttrs = { [READING_VIEW_COUNTER_ATTR]: 'true' };
</script>

{#if session.state.open && slide}
	<div
		{...rootAttrs}
		class="pptx-svelte-readingview"
		role="region"
		aria-label={t('pptx.view.readingView')}
	>
		<div
			class="pptx-svelte-readingview-viewport"
			bind:clientWidth={session.viewportWidth}
			bind:clientHeight={session.viewportHeight}
		>
			{#if session.scale > 0}
				<div
					{...stageAttrs}
					class="pptx-svelte-readingview-stage"
					aria-roledescription="slide"
					style={stageStyle}
				>
					<SlideStage
						{slide}
						{canvasSize}
						{mediaDataUrls}
						scale={session.scale}
						presenting={false}
					/>
				</div>
			{/if}
		</div>
		<div class="pptx-svelte-readingview-nav">
			<button
				type="button"
				aria-label={t('pptx.common.previous')}
				title={t('pptx.common.previous')}
				disabled={!session.canPrevious}
				onclick={() => session.run({ command: 'previous' })}
			>
				<ChevronLeft size={16} aria-hidden="true" />
			</button>
			<span {...counterAttrs} class="pptx-svelte-readingview-counter">{session.counter}</span>
			<button
				type="button"
				aria-label={t('pptx.common.next')}
				title={t('pptx.common.next')}
				disabled={!session.canNext}
				onclick={() => session.run({ command: 'next' })}
			>
				<ChevronRight size={16} aria-hidden="true" />
			</button>
			<button
				type="button"
				aria-label={t('pptx.statusBar.normalView')}
				title={t('pptx.statusBar.normalView')}
				onclick={() => session.run({ command: 'exit' })}
			>
				<X size={16} aria-hidden="true" />
			</button>
		</div>
	</div>
{/if}

<style>
	.pptx-svelte-readingview {
		position: fixed;
		inset: 0;
		z-index: 1300;
		display: flex;
		flex-direction: column;
		background: #171721;
	}

	.pptx-svelte-readingview-viewport {
		display: flex;
		flex: 1;
		min-height: 0;
		align-items: center;
		justify-content: center;
	}

	.pptx-svelte-readingview-stage {
		position: relative;
		overflow: hidden;
		background: #fff;
		box-shadow: 0 24px 60px rgb(0 0 0 / 55%);
	}

	.pptx-svelte-readingview-nav {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 12px;
		padding: 8px 16px;
		border-top: 1px solid rgb(255 255 255 / 10%);
	}

	.pptx-svelte-readingview-nav button {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 32px;
		height: 32px;
		border: 0;
		border-radius: 4px;
		background: transparent;
		color: rgb(255 255 255 / 80%);
		cursor: pointer;
	}

	.pptx-svelte-readingview-nav button:hover:not(:disabled) {
		background: rgb(255 255 255 / 15%);
		color: #fff;
	}

	.pptx-svelte-readingview-nav button:disabled {
		opacity: 0.3;
		cursor: default;
	}

	.pptx-svelte-readingview-counter {
		min-width: 64px;
		color: rgb(255 255 255 / 70%);
		font-size: 12px;
		font-variant-numeric: tabular-nums;
		text-align: center;
	}
</style>

// viewers/pptx/packages/angular/src/viewer/reading-view-overlay.component.ts
/**
 * reading-view-overlay.component.ts: PowerPoint's Reading View, Angular binding.
 *
 * Deliberately NOT built on {@link PresentationOverlayComponent}. Reading View
 * is the deck at full WINDOW size with the editor chrome cut back to a nav bar:
 * reusing the slide-show overlay would drag the Fullscreen API, the pointer
 * tools, blackout and the presenter console in with it, which is exactly the
 * weight a reader asked to escape. `position: fixed; inset: 0` fills the browser
 * window without requesting fullscreen, matching PowerPoint and the sibling
 * {@link SlideSorterOverlayComponent}.
 *
 * Every navigation rule (what Page Down does, when advancing past the last
 * slide closes the view, whether Previous is live) comes from
 * `render/reading-view` in `pptx-viewer-shared`, so the five bindings cannot
 * drift apart. Nothing in this file decides which slide comes next.
 *
 * Reference binding: packages/react/src/viewer/components/ReadingViewOverlay.tsx
 */
import {
	AfterViewInit,
	ChangeDetectionStrategy,
	Component,
	ElementRef,
	OnDestroy,
	OnInit,
	computed,
	input,
	output,
	signal,
	viewChild,
} from '@angular/core';
import { LucideChevronLeft, LucideChevronRight, LucideX } from '@lucide/angular';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxSlide } from 'pptx-viewer-core';

import {
	CLOSED_READING_VIEW,
	applyReadingViewCommand,
	canGoNext,
	canGoPrevious,
	createPresentationKeyBuffer,
	formatSlideCounter,
	handleReadingViewKey,
	openReadingView,
	readingViewFitScale,
} from 'ooxml-ui/pptx';
import type { CanvasSize, ReadingViewCommand, ReadingViewState } from 'ooxml-ui/pptx';
import { READING_VIEW_OVERLAY_STYLES } from './reading-view-overlay.styles';
import { SlideCanvasComponent } from './slide-canvas.component';

/** Breathing room between the slide and the window edge, in CSS pixels. */
const READING_VIEW_PADDING = 24;

@Component({
	selector: 'pptx-reading-view-overlay',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [SlideCanvasComponent, TranslatePipe, LucideChevronLeft, LucideChevronRight, LucideX],
	styles: READING_VIEW_OVERLAY_STYLES,
	template: `
		@if (visibleSlide(); as slide) {
			<div
				class="pptx-ng-reading-root"
				data-pptx-reading-view="true"
				role="region"
				[attr.aria-label]="'pptx.view.readingView' | translate"
			>
				<div #viewport class="pptx-ng-reading-viewport">
					@if (scale() > 0) {
						<div
							class="pptx-ng-reading-stage"
							data-pptx-reading-view-stage="true"
							aria-roledescription="slide"
							[style.width.px]="stageWidth()"
							[style.height.px]="stageHeight()"
						>
							<pptx-slide-canvas
								[slide]="slide"
								[canvasSize]="canvasSize()"
								[mediaDataUrls]="mediaDataUrls()"
								[zoom]="scale()"
								[autoFit]="false"
								[interactive]="false"
							/>
						</div>
					}
				</div>
				<div class="pptx-ng-reading-nav">
					<button
						type="button"
						class="pptx-ng-reading-btn"
						[attr.aria-label]="'pptx.common.previous' | translate"
						[title]="'pptx.common.previous' | translate"
						[disabled]="!canPrevious()"
						(click)="run({ command: 'previous' })"
					>
						<svg lucideChevronLeft class="h-4 w-4"></svg>
					</button>
					<span class="pptx-ng-reading-counter" data-pptx-reading-view-counter="true">{{
						counter()
					}}</span>
					<button
						type="button"
						class="pptx-ng-reading-btn"
						[attr.aria-label]="'pptx.common.next' | translate"
						[title]="'pptx.common.next' | translate"
						[disabled]="!canNext()"
						(click)="run({ command: 'next' })"
					>
						<svg lucideChevronRight class="h-4 w-4"></svg>
					</button>
					<button
						type="button"
						class="pptx-ng-reading-btn"
						[attr.aria-label]="'pptx.statusBar.normalView' | translate"
						[title]="'pptx.statusBar.normalView' | translate"
						(click)="run({ command: 'exit' })"
					>
						<svg lucideX class="h-4 w-4"></svg>
					</button>
				</div>
			</div>
		}
	`,
})
export class ReadingViewOverlayComponent implements OnInit, AfterViewInit, OnDestroy {
	/**
	 * The deck to read, template (master/layout) elements already merged in. The
	 * host passes its merged display deck rather than a separate template layer:
	 * the reader navigates inside this overlay, so a single "active slide's
	 * template elements" array would paint slide 1's master over slide 2.
	 */
	readonly slides = input<readonly PptxSlide[]>([]);
	readonly canvasSize = input.required<CanvasSize>();
	readonly mediaDataUrls = input<Map<string, string>>(new Map());
	/** Slide the editor was on when Reading View was entered. */
	readonly activeSlideIndex = input<number>(0);

	/** Emits the slide the reader ended on, so the editor lands there. */
	readonly exit = output<number>();

	/** Whether the view is on screen and which slide it shows (shared state). */
	protected readonly state = signal<ReadingViewState>(CLOSED_READING_VIEW);

	private readonly viewportRef = viewChild<ElementRef<HTMLElement>>('viewport');
	/** Measured size of the area the slide is fitted into, in CSS pixels. */
	private readonly viewport = signal<{ width: number; height: number }>({ width: 0, height: 0 });

	/**
	 * PowerPoint's "type a slide number, then Enter" jump. One buffer per open
	 * session, and every key mapped through it EXACTLY once: mapping mutates the
	 * buffer, so a second call would swallow the digit it just accumulated.
	 */
	private readonly keyBuffer = createPresentationKeyBuffer();

	/** Bound once so the capture-phase listener can be removed again. */
	private readonly keyListener = (event: KeyboardEvent): void => this.onKeyDown(event);
	private resizeObserver: ResizeObserver | null = null;

	ngOnInit(): void {
		// Inputs are only bound by now, so the opening slide cannot be read in a
		// field initializer. Clamping lives in the shared opener.
		this.state.set(openReadingView(this.activeSlideIndex(), this.slides().length));
		// Capture phase on `window`, which is why this cannot be a @HostListener
		// (those can only register in the bubble phase). The editor is still mounted
		// and still listening underneath this overlay, and until the reader's keys
		// were swallowed first an arrow key both turned the page AND nudged the
		// selected shape behind it, so merely reading a deck edited it.
		window.addEventListener('keydown', this.keyListener, true);
	}

	ngAfterViewInit(): void {
		const element = this.viewportRef()?.nativeElement;
		if (!element || typeof ResizeObserver === 'undefined') {
			return;
		}
		this.resizeObserver = new ResizeObserver((entries) => {
			const rect = entries[0]?.contentRect;
			if (rect) {
				this.viewport.set({ width: rect.width, height: rect.height });
			}
		});
		this.resizeObserver.observe(element);
	}

	ngOnDestroy(): void {
		window.removeEventListener('keydown', this.keyListener, true);
		this.resizeObserver?.disconnect();
		this.resizeObserver = null;
	}

	/** The slide on screen, or undefined when closed or the deck is empty. */
	protected readonly visibleSlide = computed<PptxSlide | undefined>(() => {
		const state = this.state();
		return state.open ? this.slides()[state.slideIndex] : undefined;
	});

	/** Fit scale for the slide; 0 before the first layout pass. */
	protected readonly scale = computed(() =>
		readingViewFitScale(this.canvasSize(), this.viewport(), READING_VIEW_PADDING),
	);

	protected readonly stageWidth = computed(() => this.canvasSize().width * this.scale());
	protected readonly stageHeight = computed(() => this.canvasSize().height * this.scale());

	protected readonly counter = computed(() =>
		formatSlideCounter(this.state().slideIndex, this.slides().length),
	);

	protected readonly canPrevious = computed(() => canGoPrevious(this.state()));
	protected readonly canNext = computed(() => canGoNext(this.state(), this.slides().length));

	/** Apply a navigation intent, handing the reader back to the editor on close. */
	protected run(command: ReadingViewCommand): void {
		const previous = this.state();
		const next = applyReadingViewCommand(previous, command, this.slides().length);
		this.state.set(next);
		if (previous.open && !next.open) {
			// Leaving a PowerPoint view returns the editor to the slide that was on
			// screen, not the one it was on before.
			this.exit.emit(previous.slideIndex);
		}
	}

	/**
	 * Window-level so no element has to hold focus, matching the slide show.
	 * Writing {@link state} marks this `OnPush` view dirty and notifies Angular's
	 * change-detection scheduler, so no manual `markForCheck` is needed even
	 * though the listener is not a host binding.
	 */
	protected onKeyDown(event: KeyboardEvent): void {
		if (!this.state().open) {
			return;
		}
		// Handled exactly once: the call mutates `keyBuffer` to accumulate a typed
		// slide number, so handling twice would swallow every digit.
		const { command, swallow, preventDefault } = handleReadingViewKey(event, this.keyBuffer);
		if (swallow) {
			event.stopPropagation();
		}
		if (preventDefault) {
			// Space and the arrows would otherwise scroll the editor underneath.
			event.preventDefault();
		}
		if (command.command !== 'none') {
			this.run(command);
		}
	}
}
