// viewers/pptx/packages/svelte/src/viewer/components/SettingsLanguageTab.svelte
<script lang="ts">
	/**
	 * File > Options > Language: a list of locale choices. Defaults to every
	 * locale actually registered via `pptx-svelte-viewer/i18n`'s
	 * `registerTranslations` (English ships built in), labelled from the
	 * shared `LOCALE_CATALOG`, so this never offers a locale with no
	 * registered dictionary. A host can override the list with
	 * `availableLocales`.
	 */
	import { LOCALE_CATALOG } from 'ooxml-ui/pptx/i18n';
	import type { LocaleCatalogEntry } from 'ooxml-ui/pptx/i18n';
	import { getRegisteredLocales } from '../../i18n/translator';
	import { useTranslator } from '../../i18n/context';

	const {
		locale,
		availableLocales,
		onselect,
	}: {
		locale: string;
		availableLocales?: readonly LocaleCatalogEntry[];
		onselect: (code: string) => void;
	} = $props();
	const t = useTranslator();
	const choices = $derived<readonly LocaleCatalogEntry[]>(
		availableLocales ?? LOCALE_CATALOG.filter((entry) => getRegisteredLocales().includes(entry.code)),
	);
</script>

<div class="list" role="group" aria-label={t('pptx.settings.language')}>
	{#each choices as entry (entry.code)}
		<button
			type="button"
			class:active={entry.code === locale}
			aria-pressed={entry.code === locale}
			onclick={() => onselect(entry.code)}
		>
			<span class="native">{entry.nativeLabel}</span>
			<span class="label">{entry.label}</span>
		</button>
	{/each}
</div>

<style>
	.list {
		display: flex;
		flex-direction: column;
		gap: 4px;
		padding: 4px 0;
	}

	.list button {
		display: flex;
		align-items: baseline;
		gap: 8px;
		padding: 9px 11px;
		border: 0;
		border-radius: 6px;
		background: var(--pptx-muted, #2a2a3d);
		color: inherit;
		cursor: pointer;
		font: inherit;
		font-size: 12px;
		text-align: left;
	}

	.list button:hover {
		background: var(--pptx-accent, #33334d);
	}

	.list button.active {
		outline: 2px solid var(--pptx-primary, #c43b32);
		outline-offset: -2px;
	}

	.native {
		font-weight: 600;
	}

	.label {
		color: var(--pptx-muted-foreground, #94a3b8);
	}
</style>

// viewers/pptx/packages/angular/src/viewer/settings-language-tab.component.ts
/**
 * settings-language-tab.component.ts: File > Options > Language tab.
 *
 * A simple list over the resolved locale catalog (host-supplied
 * `availableLocales`, or every locale `TranslateService.getLangs()` reports
 * registered, mapped through `LOCALE_CATALOG` for display labels). Extracted
 * out of `SettingsDialogComponent` to keep that file under the repo's
 * ~300-LOC guideline.
 */
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';

import type { LocaleCatalogEntry } from 'ooxml-ui/pptx/i18n';

@Component({
	selector: 'pptx-settings-language-tab',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div class="pptx-ng-settings-list" role="radiogroup">
			@for (entry of locales(); track entry.code) {
				<button
					type="button"
					role="radio"
					class="pptx-ng-settings-row pptx-ng-lang-row"
					[attr.aria-checked]="entry.code === activeCode()"
					[class.is-active]="entry.code === activeCode()"
					(click)="select.emit(entry.code)"
				>
					<span>{{ entry.nativeLabel }}</span>
					<span class="pptx-ng-lang-en">{{ entry.label }}</span>
				</button>
			}
		</div>
	`,
	styles: [
		`
			.pptx-ng-lang-row {
				width: 100%;
				border: 0;
				background: transparent;
				color: inherit;
				cursor: pointer;
			}
			.pptx-ng-lang-row.is-active {
				color: var(--pptx-primary);
				font-weight: 600;
			}
			.pptx-ng-lang-en {
				color: var(--pptx-muted-foreground);
			}
		`,
	],
})
export class SettingsLanguageTabComponent {
	readonly locales = input.required<readonly LocaleCatalogEntry[]>();
	readonly activeCode = input<string>('en');
	readonly select = output<string>();
}
