// viewers/pptx/packages/vue/src/viewer/components/SettingsDialog.vue
<script setup lang="ts">
/**
 * SettingsDialog - the PowerPoint "File > Options" parity dialog.
 *
 * Vue counterpart of the React `SettingsDialog.tsx`: the ten shared categories
 * (`VIEWER_OPTIONS_TABS`) in a left rail with schema-driven panes on the right
 * (`OptionsPane` and the bespoke Ribbon / Quick Access / Add-ins panes).
 * Changes apply live through `onOptionChange`; Cancel restores the snapshot
 * taken when the dialog opened; OK (or Escape / backdrop) closes confirming.
 *
 * Renders its own wide overlay instead of the shared `ModalDialog`, whose
 * 480px max-width cannot host the two-column category-rail layout.
 */
import { Settings, X } from 'lucide-vue-next';
import type {
	ToolbarTabId,
	ViewerAddinStatus,
	ViewerOptions,
	ViewerOptionsGroupId,
} from 'ooxml-ui/pptx';
import { DEFAULT_QUICK_ACCESS_COMMAND_IDS, getDensePanelTouchTargetPx } from 'ooxml-ui/pptx';
import type { PptxAiChatStore } from 'ooxml-ui/pptx/ai';
import { computed, onBeforeUnmount, onMounted, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import type { LocaleCatalogEntry } from '../../i18n';
import type { ThemeCatalogEntry } from '../../theme';
import {
	AI_OPTIONS_TAB_ID as AI_TAB_ID,
	useCustomizedOptionsTabs,
} from '../composables/useCustomizedOptionsTabs';
import { useIsMobile } from '../composables/useIsMobile';
import OptionsAddInsPane from './settings/OptionsAddInsPane.vue';
import OptionsPane from './settings/OptionsPane.vue';
import OptionsQuickAccessPane from './settings/OptionsQuickAccessPane.vue';
import OptionsRibbonPane from './settings/OptionsRibbonPane.vue';
import SettingsAiTab from './SettingsAiTab.vue';
import SettingsAppearanceTab from './SettingsAppearanceTab.vue';
import SettingsCustomFontsSection from './SettingsCustomFontsSection.vue';
import SettingsLanguageTab from './SettingsLanguageTab.vue';

const props = defineProps<{
	/** Whether the dialog is visible. */
	open: boolean;
	/** Full File > Options snapshot rendered by every pane. */
	options: ViewerOptions;
	onOptionChange: (
		group: ViewerOptionsGroupId,
		key: string,
		value: boolean | number | string,
	) => void;
	/** Restore a snapshot wholesale (Cancel semantics). */
	onRestoreOptions: (options: ViewerOptions) => void;
	onRibbonTabHiddenChange: (tabId: ToolbarTabId, hidden: boolean) => void;
	onQuickAccessCommandsChange: (commandIds: string[]) => void;
	onResetOptions: (group?: ViewerOptionsGroupId) => void;
	/** Options > Save > "Delete cached files". */
	onClearCache: () => void;
	/** Availability flags for the Add-ins pane. */
	addinStatus?: ViewerAddinStatus;
	/** Key of the currently active theme-catalog entry. */
	themeKey: string;
	/** Invoked with the entry's `key` when the user picks an Appearance swatch. */
	onThemeSelect: (key: string) => void;
	/** Code of the currently active locale. */
	localeCode: string;
	/** Invoked with the entry's `code` when the user picks a Language choice. */
	onLocaleSelect: (code: string) => void;
	/** Theme choices to offer; defaults to the built-in catalog. */
	availableThemes?: ThemeCatalogEntry[];
	/** Locale choices to offer on the Language pane. */
	availableLocales: LocaleCatalogEntry[];
	/** When true, an "AI" section is shown for exporting detailed chat logs. */
	aiEnabled?: boolean;
	/** Families registered this session via the Fonts section. */
	customFontFamilies?: readonly string[];
	/** Chat store the AI section reads from (defaults to the shared store). */
	chatStore?: PptxAiChatStore;
}>();

const emit = defineEmits<{
	/** Emitted when the dialog should close (changes kept). */
	(e: 'close'): void;
	/** A font file was registered; the ribbon adds the family to its list. */
	(e: 'customFontRegistered', family: string): void;
}>();

const { t } = useI18n();
const { viewportWidth } = useIsMobile();
const closeBtnStyle = computed(() => {
	const size = getDensePanelTouchTargetPx(viewportWidth.value);
	return { minWidth: `${size}px`, minHeight: `${size}px` };
});
// The category rail's own tabs are discrete one-per-row controls too, so they
// get the same touch target as the close button below the mobile breakpoint
// (React's SettingsDialog.tsx `navBtnStyle` does the same for its own nav -
// CLAUDE.md Rule 1, this binding had imported the shared function but never
// applied it to the nav buttons).
const navBtnStyle = computed(() => {
	const size = getDensePanelTouchTargetPx(viewportWidth.value);
	return { minHeight: `${size}px`, minWidth: `${size}px` };
});

// The rail after the host's UI customisation (hidden pages/sections/settings,
// locked settings marked read-only); see `useCustomizedOptionsTabs`.
const { visibleTabs, showAiTab, activeTabId, activeTab } = useCustomizedOptionsTabs(() =>
	Boolean(props.aiEnabled),
);

/** Snapshot taken on open, restored wholesale by Cancel. */
let snapshot: ViewerOptions | null = null;
watch(
	() => props.open,
	(isOpen, wasOpen) => {
		if (isOpen && !wasOpen) {
			snapshot = props.options;
		}
	},
	{ immediate: true },
);

function close(): void {
	emit('close');
}

function cancel(): void {
	if (snapshot) {
		props.onRestoreOptions(snapshot);
	}
	close();
}

function resetQuickAccess(): void {
	props.onQuickAccessCommandsChange([...DEFAULT_QUICK_ACCESS_COMMAND_IDS]);
}

// Close (confirming) on Escape while open.
function onDocumentKeydown(event: KeyboardEvent): void {
	if (props.open && event.key === 'Escape') {
		event.preventDefault();
		close();
	}
}
onMounted(() => document.addEventListener('keydown', onDocumentKeydown));
onBeforeUnmount(() => document.removeEventListener('keydown', onDocumentKeydown));
</script>

<template>
	<Teleport to="body">
		<template v-if="open && activeTab">
			<!-- Backdrop -->
			<button
				type="button"
				class="pptx-vue-options-backdrop fixed inset-0 z-[1200] bg-black/60"
				:aria-label="t('pptx.settings.closeSettings')"
				@click="close"
			/>
			<!-- Dialog -->
			<div class="pointer-events-none fixed inset-0 z-[1201] flex items-center justify-center">
				<div
					role="dialog"
					aria-modal="true"
					:aria-label="t('pptx.options.title')"
					class="pptx-vue-options-dialog pointer-events-auto flex max-h-[85vh] w-[min(56rem,calc(100%-2rem))] flex-col rounded-xl border border-border bg-popover text-foreground shadow-2xl backdrop-blur-xl max-md:fixed max-md:inset-x-0 max-md:bottom-0 max-md:top-auto max-md:max-h-[88dvh] max-md:w-full max-md:rounded-b-none max-md:rounded-t-2xl max-md:border-x-0 max-md:border-b-0 max-md:pb-[max(env(safe-area-inset-bottom),0px)]"
				>
					<!-- Header -->
					<div
						class="pptx-vue-options-header flex items-center justify-between border-b border-border/60 px-5 py-4"
					>
						<div class="flex items-center gap-2">
							<Settings class="h-5 w-5 text-primary" aria-hidden="true" />
							<h2 class="text-sm font-semibold text-foreground">{{ t('pptx.options.title') }}</h2>
						</div>
						<button
							type="button"
							class="flex items-center justify-center rounded p-1 transition-colors hover:bg-accent"
							:style="closeBtnStyle"
							:aria-label="t('pptx.settings.close')"
							@click="close"
						>
							<X class="h-4 w-4 text-muted-foreground" />
						</button>
					</div>

					<!-- Body: category rail + pane -->
					<div class="flex min-h-0 flex-1 max-md:flex-col">
						<nav
							:aria-label="t('pptx.options.title')"
							class="pptx-vue-options-rail w-44 shrink-0 space-y-0.5 overflow-y-auto border-r border-border/60 p-2 max-md:flex max-md:w-full max-md:space-y-0 max-md:gap-1 max-md:overflow-x-auto max-md:border-b max-md:border-r-0"
						>
							<button
								v-for="tab in visibleTabs"
								:key="tab.id"
								type="button"
								:aria-current="activeTabId === tab.id"
								class="block w-full whitespace-nowrap rounded px-3 py-2 text-left text-sm transition-colors max-md:w-auto"
								:class="
									activeTabId === tab.id
										? 'bg-primary/10 font-medium text-primary'
										: 'text-foreground hover:bg-accent'
								"
								:style="navBtnStyle"
								@click="activeTabId = tab.id"
							>
								{{ t(tab.labelKey) }}
							</button>
							<button
								v-if="showAiTab"
								type="button"
								:aria-current="activeTabId === AI_TAB_ID"
								class="block w-full whitespace-nowrap rounded px-3 py-2 text-left text-sm transition-colors max-md:w-auto"
								:class="
									activeTabId === AI_TAB_ID
										? 'bg-primary/10 font-medium text-primary'
										: 'text-foreground hover:bg-accent'
								"
								:style="navBtnStyle"
								@click="activeTabId = AI_TAB_ID"
							>
								{{ t('pptx.ai.settingsSectionTitle') }}
							</button>
						</nav>

						<div class="pptx-vue-options-body min-h-0 flex-1 overflow-y-auto px-5 py-4">
							<!-- AI: detailed chat-log export (shown only when enabled) -->
							<div v-if="activeTabId === AI_TAB_ID" class="space-y-4">
								<p class="text-sm font-medium text-foreground">
									{{ t('pptx.ai.settingsSectionTitle') }}
								</p>
								<SettingsAiTab :store="chatStore" />
							</div>

							<!-- Language: bespoke pane around the locale list -->
							<div v-else-if="activeTab.custom === 'language'" class="space-y-4">
								<p class="text-sm font-medium text-foreground">{{ t(activeTab.descriptionKey) }}</p>
								<section>
									<h3
										class="mb-1 border-b border-border/60 pb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground"
									>
										{{ t('pptx.options.language.displayLanguage') }}
									</h3>
									<p class="mb-2 text-xs text-muted-foreground">
										{{ t('pptx.options.language.displayLanguageDescription') }}
									</p>
									<SettingsLanguageTab
										:locale-code="localeCode"
										:locales="availableLocales"
										:on-select="onLocaleSelect"
									/>
								</section>
							</div>

							<!-- Customize Ribbon -->
							<div v-else-if="activeTab.custom === 'ribbon'" class="space-y-4">
								<p class="text-sm font-medium text-foreground">{{ t(activeTab.descriptionKey) }}</p>
								<OptionsRibbonPane
									:options="options"
									:on-ribbon-tab-hidden-change="onRibbonTabHiddenChange"
									:on-reset-ribbon="() => onResetOptions('ribbon')"
								/>
							</div>

							<!-- Add-ins -->
							<div v-else-if="activeTab.custom === 'addIns'" class="space-y-4">
								<p class="text-sm font-medium text-foreground">{{ t(activeTab.descriptionKey) }}</p>
								<OptionsAddInsPane :addin-status="addinStatus" />
							</div>

							<!-- Generic schema pane (plus the Quick Access chooser) -->
							<OptionsPane
								v-else
								:tab="activeTab"
								:options="options"
								:on-option-change="onOptionChange"
							>
								<template #special="{ section }">
									<div v-if="section.special === 'themePicker'" class="mt-2">
										<SettingsAppearanceTab
											:theme-key="themeKey"
											:catalog="availableThemes"
											:on-select="onThemeSelect"
										/>
									</div>
									<SettingsCustomFontsSection
										v-else-if="section.special === 'customFonts'"
										:enabled="props.options.general.enableCustomFontUpload"
										:families="props.customFontFamilies ?? []"
										@registered="(family: string) => emit('customFontRegistered', family)"
									/>
									<div v-else-if="section.special === 'clearCache'" class="mt-2">
										<p class="mb-2 text-xs text-muted-foreground">
											{{ t('pptx.options.save.clearCacheDescription') }}
										</p>
										<button
											type="button"
											class="rounded border border-border px-3 py-1.5 text-xs text-foreground transition-colors hover:bg-accent"
											@click="onClearCache"
										>
											{{ t('pptx.options.save.clearCacheNow') }}
										</button>
									</div>
								</template>
								<OptionsQuickAccessPane
									v-if="activeTab.custom === 'quickAccess'"
									:options="options"
									:on-quick-access-commands-change="onQuickAccessCommandsChange"
									:on-reset-quick-access="resetQuickAccess"
								/>
							</OptionsPane>
						</div>
					</div>

					<!-- Footer -->
					<div
						class="pptx-vue-options-footer flex items-center justify-between gap-2 border-t border-border/60 px-5 py-3"
					>
						<button
							type="button"
							class="rounded border border-border px-3 py-1.5 text-xs text-muted-foreground transition-colors hover:bg-accent hover:text-foreground max-md:min-h-[44px]!"
							@click="onResetOptions()"
						>
							{{ t('pptx.options.resetAll') }}
						</button>
						<div class="flex items-center gap-2">
							<button
								type="button"
								class="rounded border border-border px-4 py-1.5 text-xs text-foreground transition-colors hover:bg-accent max-md:min-h-[44px]!"
								@click="cancel"
							>
								{{ t('pptx.common.cancel') }}
							</button>
							<button
								type="button"
								class="rounded bg-primary px-4 py-1.5 text-xs font-medium text-primary-foreground transition-colors hover:bg-primary/90 max-md:min-h-[44px]!"
								@click="close"
							>
								{{ t('pptx.common.ok') }}
							</button>
						</div>
					</div>
				</div>
			</div>
		</template>
	</Teleport>
</template>

// viewers/pptx/packages/angular/src/viewer/settings-dialog.component.ts
/**
 * settings-dialog.component.ts: the File > Options dialog (Angular port of
 * React's `SettingsDialog.tsx`).
 *
 * A PowerPoint Options-style dialog: the ten shared categories from
 * {@link VIEWER_OPTIONS_TABS} in a left rail, schema-driven panes on the right
 * ({@link OptionsPaneComponent}), and bespoke panes for Language (locale list),
 * Customize Ribbon, Quick Access Toolbar, and Add-ins. Changes apply live
 * through the host's options store; Cancel restores the snapshot taken when
 * the dialog opened, while OK / Escape / backdrop keep the edits.
 *
 * Built as its own overlay + panel (not `pptx-modal-dialog`) because the
 * two-column rail layout needs the wide footprint the shared modal shell does
 * not provide, mirroring how `insert-smart-art-dialog` sizes itself.
 */
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	HostListener,
	input,
	output,
	signal,
	untracked,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { customizeOptionsTabs, isOptionsPageVisible, THEME_CATALOG } from 'ooxml-ui/pptx';
import type {
	ThemeCatalogEntry,
	ViewerAddinStatus,
	ViewerOptions,
	ViewerOptionsGroupId,
	ViewerOptionsTabId,
} from 'ooxml-ui/pptx';
import { LOCALE_CATALOG } from 'ooxml-ui/pptx/i18n';
import type { LocaleCatalogEntry } from 'ooxml-ui/pptx/i18n';
import { AiSettingsSectionComponent } from './ai/ai-settings-section.component';
import { OptionsAddInsPaneComponent } from './options-add-ins-pane.component';
import { OptionsPaneComponent } from './options-pane.component';
import type { OptionValueChange } from './options-pane.component';
import { OptionsQuickAccessPaneComponent } from './options-quick-access-pane.component';
import { OptionsRibbonPaneComponent } from './options-ribbon-pane.component';
import type { RibbonTabHiddenChange } from './options-ribbon-pane.component';
import { SettingsAppearanceTabComponent } from './settings-appearance-tab.component';
import { SettingsCustomFontsComponent } from './settings-custom-fonts.component';
import {
	OPTIONS_DIALOG_TABS,
	resolveOptionsTab,
	resolveVisibleOptionsTabId,
} from './settings-dialog-tabs';
import { SettingsLanguageTabComponent } from './settings-language-tab.component';
import { injectResolvedCustomization } from './viewer-customization.service';

export type { ViewerSettings } from 'ooxml-ui/pptx';
export { OPTIONS_DIALOG_TABS, resolveOptionsTab } from './settings-dialog-tabs';

@Component({
	selector: 'pptx-settings-dialog',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [
		TranslatePipe,
		OptionsPaneComponent,
		OptionsRibbonPaneComponent,
		OptionsQuickAccessPaneComponent,
		OptionsAddInsPaneComponent,
		SettingsAppearanceTabComponent,
		SettingsCustomFontsComponent,
		SettingsLanguageTabComponent,
		AiSettingsSectionComponent,
	],
	template: `
		@if (open()) {
			<button
				type="button"
				class="pptx-ng-options-backdrop"
				[attr.aria-label]="'pptx.settings.closeSettings' | translate"
				(click)="close.emit()"
			></button>
			<div
				class="pptx-ng-options-modal"
				role="dialog"
				aria-modal="true"
				[attr.aria-label]="'pptx.options.title' | translate"
			>
				<div class="pptx-ng-options-header">
					<h2>{{ 'pptx.options.title' | translate }}</h2>
					<button
						type="button"
						class="pptx-ng-options-x"
						[attr.aria-label]="'pptx.settings.close' | translate"
						(click)="close.emit()"
					>
						&#10005;
					</button>
				</div>

				<div class="pptx-ng-options-layout">
					<nav [attr.aria-label]="'pptx.options.title' | translate">
						@for (tab of tabs(); track tab.id) {
							<button
								type="button"
								[attr.aria-current]="shownTabId() === tab.id"
								[class.is-active]="shownTabId() === tab.id"
								(click)="activeTabId.set(tab.id)"
							>
								{{ tab.labelKey | translate }}
							</button>
						}
						@if (aiTabVisible()) {
							<button
								type="button"
								[attr.aria-current]="shownTabId() === 'ai'"
								[class.is-active]="shownTabId() === 'ai'"
								(click)="activeTabId.set('ai')"
							>
								{{ 'pptx.ai.settingsSectionTitle' | translate }}
							</button>
						}
					</nav>

					<div class="pptx-ng-options-content">
						@if (shownTabId() === 'ai') {
							<p class="pptx-ng-options-headline">
								{{ 'pptx.ai.settingsSectionTitle' | translate }}
							</p>
							<pptx-ai-settings-section />
						} @else {
							@switch (activeTab().custom) {
								@case ('language') {
									<p class="pptx-ng-options-headline">
										{{ activeTab().descriptionKey | translate }}
									</p>
									<h3 class="pptx-ng-options-subhead">
										{{ 'pptx.options.language.displayLanguage' | translate }}
									</h3>
									<p class="pptx-ng-options-note">
										{{ 'pptx.options.language.displayLanguageDescription' | translate }}
									</p>
									<pptx-settings-language-tab
										[locales]="availableLocales()"
										[activeCode]="localeCode()"
										(select)="localeSelect.emit($event)"
									/>
								}
								@case ('ribbon') {
									<p class="pptx-ng-options-headline">
										{{ activeTab().descriptionKey | translate }}
									</p>
									<pptx-options-ribbon-pane
										[options]="options()"
										(tabHiddenChange)="ribbonTabHiddenChange.emit($event)"
										(resetRibbon)="resetOptions.emit('ribbon')"
									/>
								}
								@case ('addIns') {
									<p class="pptx-ng-options-headline">
										{{ activeTab().descriptionKey | translate }}
									</p>
									<pptx-options-add-ins-pane [addinStatus]="addinStatus()" />
								}
								@default {
									<pptx-options-pane
										[tab]="activeTab()"
										[options]="options()"
										(valueChange)="optionChange.emit($event)"
										(clearCache)="clearCache.emit()"
									>
										<div themePicker>
											<pptx-settings-appearance-tab
												[themes]="availableThemes()"
												[activeKey]="themeKey()"
												(select)="themeKeySelect.emit($event)"
											/>
										</div>
										<div customFonts>
											<pptx-settings-custom-fonts
												[enabled]="options().general.enableCustomFontUpload"
												[families]="customFontFamilies()"
												(registered)="customFontRegistered.emit($event)"
											/>
										</div>
										@if (activeTab().custom === 'quickAccess') {
											<pptx-options-quick-access-pane
												[options]="options()"
												(commandsChange)="quickAccessCommandsChange.emit($event)"
											/>
										}
									</pptx-options-pane>
								}
							}
						}
					</div>
				</div>

				<div class="pptx-ng-options-footer">
					<button
						type="button"
						class="pptx-ng-options-ghost"
						(click)="resetOptions.emit(undefined)"
					>
						{{ 'pptx.options.resetAll' | translate }}
					</button>
					<span class="pptx-ng-options-footer-end">
						<button type="button" class="pptx-ng-options-ghost" (click)="cancel()">
							{{ 'pptx.common.cancel' | translate }}
						</button>
						<button type="button" class="pptx-ng-options-ok" (click)="close.emit()">
							{{ 'pptx.common.ok' | translate }}
						</button>
					</span>
				</div>
			</div>
		}
	`,
	styleUrl: './settings-dialog.component.css',
})
export class SettingsDialogComponent {
	readonly open = input(false);
	/** Full File > Options snapshot rendered by every pane. */
	readonly options = input.required<ViewerOptions>();
	/** Selected theme catalog key, for General > Appearance. */
	readonly themeKey = input<string>('default');
	readonly availableThemes = input<readonly ThemeCatalogEntry[]>(THEME_CATALOG);
	/** Active locale code, for the Language category. */
	readonly localeCode = input<string>('en');
	readonly availableLocales = input<readonly LocaleCatalogEntry[]>(LOCALE_CATALOG);
	/** Availability flags for the Add-ins pane (unset ids default to active). */
	readonly addinStatus = input<ViewerAddinStatus | undefined>(undefined);
	/**
	 * Whether to show the bespoke "AI" category (chat-log export), gated by the
	 * host on the `ai` config. Absent by default (no AI category).
	 */
	readonly aiExportVisible = input<boolean>(false);

	readonly optionChange = output<OptionValueChange>();
	/** Restore a snapshot wholesale (Cancel semantics). */
	readonly restoreOptions = output<ViewerOptions>();
	readonly ribbonTabHiddenChange = output<RibbonTabHiddenChange>();
	readonly quickAccessCommandsChange = output<string[]>();
	/** Reset one tab-group (or everything when `undefined`). */
	readonly resetOptions = output<ViewerOptionsGroupId | undefined>();
	readonly clearCache = output<void>();
	readonly themeKeySelect = output<string>();
	/** Families registered this session via the Fonts section. */
	readonly customFontFamilies = input<readonly string[]>([]);
	/** A font file was registered; the ribbon adds the family to its list. */
	readonly customFontRegistered = output<string>();
	readonly localeSelect = output<string>();
	readonly close = output<void>();

	private readonly customization = injectResolvedCustomization();
	/** The categories after the host's customisation (hidden pages/sections/settings dropped). */
	protected readonly tabs = computed(() =>
		customizeOptionsTabs(OPTIONS_DIALOG_TABS, this.customization()),
	);
	protected readonly aiTabVisible = computed(
		() => this.aiExportVisible() && isOptionsPageVisible(this.customization(), 'ai'),
	);
	/** Requested category id, or the bespoke `'ai'` sentinel for the AI export pane. */
	protected readonly activeTabId = signal<ViewerOptionsTabId | 'ai'>('general');
	/** The requested category, or the first visible one when the host hid it. */
	protected readonly shownTabId = computed(() =>
		resolveVisibleOptionsTabId(this.activeTabId(), this.tabs(), this.aiTabVisible()),
	);
	protected readonly activeTab = computed(() => {
		const id = this.shownTabId();
		return resolveOptionsTab(id === 'ai' ? 'general' : id, this.tabs());
	});

	/** Snapshot taken when the dialog opens, restored by Cancel. */
	private snapshot: ViewerOptions | null = null;
	private wasOpen = false;

	constructor() {
		effect(() => {
			const isOpen = this.open();
			if (isOpen && !this.wasOpen) {
				this.snapshot = untracked(() => this.options());
			}
			this.wasOpen = isOpen;
		});
	}

	/** Cancel: restore the on-open snapshot, then close. */
	protected cancel(): void {
		if (this.snapshot) {
			this.restoreOptions.emit(this.snapshot);
		}
		this.close.emit();
	}

	/** Escape confirms (keeps edits), mirroring React's dialog. */
	@HostListener('document:keydown.escape')
	protected onEscape(): void {
		if (this.open()) {
			this.close.emit();
		}
	}
}
