// viewers/pptx/packages/react/src/viewer/components/inspector/SlideSizeCard.tsx
/**
 * SlideSizeCard: the Design > Slide Size control, inspector edition.
 *
 * Every decision here (which preset a size matches, what a preset produces in
 * a given orientation, and whether the EMU size or the typed pixels win) comes
 * from `pptx-viewer-shared`'s `slide-size` module, so the other four bindings
 * can render the same descriptor without re-deriving any of it.
 */
import {
	resolveSlideSizeSelection,
	slideSizeFromPreset,
	SLIDE_SIZE_PRESETS,
	withSlideSizeOrientation,
} from 'ooxml-ui/pptx';
import type { SlideSizeEmu, SlideSizeOrientation, SlideSizeRescaleMode } from 'ooxml-ui/pptx';
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';

import type { CanvasSize } from '../../types';
import { WebSelect } from '../WebControls';
import { CARD, HEADING, INPUT } from './inspector-pane-constants';
import { SlideSizeRescalePrompt } from './SlideSizeRescalePrompt';

/** Sentinel `<option>` value for a size that matches no preset. */
const CUSTOM_PRESET_VALUE = '';

export interface SlideSizeCardProps {
	canvasSize: CanvasSize;
	/**
	 * The EMU `p:sldSz` the viewer holds. Absent until a deck loads, in which
	 * case the pixel canvas alone decides the selection.
	 */
	slideSizeEmu?: SlideSizeEmu | undefined;
	canEdit: boolean;
	/** Raw W/H pixel edit. */
	onUpdate: (size: CanvasSize) => void;
	/**
	 * A preset or orientation pick, in EMU. Distinct from {@link onUpdate}
	 * because a pixel round-trip is lossy: Ledger is 12179300 EMU = 1278.5px,
	 * and the integer pixel it rounds to would cost the deck its preset.
	 *
	 * `rescaleMode` is set only when the user confirmed the Maximize/Ensure Fit
	 * prompt below for a size change that affects existing content.
	 */
	onUpdateSlideSize?: (size: SlideSizeEmu, rescaleMode?: SlideSizeRescaleMode) => void;
	/** Whether any slide has at least one element; gates the rescale prompt. */
	hasContent: boolean;
}

/** Whether two EMU sizes differ, ignoring `type` (a preset id carries no geometry of its own). */
function sizesDiffer(a: SlideSizeEmu, b: SlideSizeEmu): boolean {
	return a.widthEmu !== b.widthEmu || a.heightEmu !== b.heightEmu;
}

export function SlideSizeCard({
	canvasSize,
	slideSizeEmu,
	canEdit,
	onUpdate,
	onUpdateSlideSize,
	hasContent,
}: SlideSizeCardProps): React.ReactElement {
	const { t } = useTranslation();
	const selection = resolveSlideSizeSelection({ current: slideSizeEmu, canvas: canvasSize });
	const presetDisabled = !canEdit || !onUpdateSlideSize;

	// PowerPoint's Maximize/Ensure Fit prompt: held here rather than applied
	// immediately whenever the picked size differs from the current one AND the
	// deck actually has content to rescale. An empty deck (or a size that
	// happens to match already) applies directly, matching today's behaviour.
	const [pendingSize, setPendingSize] = useState<SlideSizeEmu | null>(null);

	const applyOrPromptSize = (nextSize: SlideSizeEmu): void => {
		if (hasContent && sizesDiffer(selection.size, nextSize)) {
			setPendingSize(nextSize);
			return;
		}
		onUpdateSlideSize?.(nextSize);
	};

	const handlePreset = (labelKey: string): void => {
		const preset = SLIDE_SIZE_PRESETS.find((candidate) => candidate.labelKey === labelKey);
		if (!preset) {
			return;
		}
		applyOrPromptSize(slideSizeFromPreset(preset, selection.orientation));
	};

	const handleOrientation = (orientation: SlideSizeOrientation): void => {
		applyOrPromptSize(withSlideSizeOrientation(selection.size, orientation));
	};

	const handleRescale = (mode: SlideSizeRescaleMode): void => {
		if (!pendingSize) {
			return;
		}
		onUpdateSlideSize?.(pendingSize, mode);
		setPendingSize(null);
	};

	return (
		<div className={CARD}>
			<div className={HEADING}>{t('pptx.slideSize.title')}</div>
			<div className='space-y-1.5 text-[11px]'>
				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground'>{t('pptx.slideSize.presets')}</span>
					<WebSelect
						aria-label={t('pptx.slideSize.presets')}
						data-pptx-slide-size-preset
						disabled={presetDisabled}
						className={INPUT}
						value={selection.preset?.labelKey ?? CUSTOM_PRESET_VALUE}
						onChange={(e) => handlePreset(e.target.value)}
					>
						{/* Only offered while the size actually is custom: picking
						    "Custom" is not an instruction PowerPoint can carry out. */}
						{selection.preset === undefined && (
							<option value={CUSTOM_PRESET_VALUE}>{t('pptx.slideSize.customSize')}</option>
						)}
						{SLIDE_SIZE_PRESETS.map((preset) => (
							<option key={preset.labelKey} value={preset.labelKey}>
								{t(`pptx.slideSize.preset.${preset.labelKey}`)}
							</option>
						))}
					</WebSelect>
				</label>

				<label className='flex flex-col gap-1'>
					<span className='text-muted-foreground'>{t('pptx.slideSize.orientation')}</span>
					<WebSelect
						aria-label={t('pptx.slideSize.orientation')}
						data-pptx-slide-size-orientation
						disabled={presetDisabled}
						className={INPUT}
						value={selection.orientation}
						onChange={(e) => handleOrientation(e.target.value as SlideSizeOrientation)}
					>
						<option value='landscape'>{t('pptx.slideSize.landscape')}</option>
						<option value='portrait'>{t('pptx.slideSize.portrait')}</option>
					</WebSelect>
				</label>

				<div className='grid grid-cols-2 gap-1.5'>
					{(
						[
							['W', 'width'],
							['H', 'height'],
						] as const
					).map(([label, key]) => (
						<label key={key} className='flex items-center gap-1'>
							<span className='text-muted-foreground'>{label}</span>
							<input
								type='number'
								className={INPUT}
								disabled={!canEdit}
								value={canvasSize[key]}
								onChange={(e) => onUpdate({ ...canvasSize, [key]: Number(e.target.value) })}
							/>
						</label>
					))}
				</div>

				{pendingSize && <SlideSizeRescalePrompt onChoose={handleRescale} />}
			</div>
		</div>
	);
}

// viewers/pptx/packages/angular/src/viewer/slide-size-card.component.ts
/**
 * slide-size-card.component.ts: SLIDE SIZE card of the default (no-selection)
 * inspector: PowerPoint's "Slide Size" preset list and Portrait/Landscape
 * toggle over the raw width/height (px) inputs.
 *
 * Every decision here belongs to the shared `render/slide-size` module: which
 * presets exist, which one a size matches, what a preset means in a given
 * orientation, and which of the EMU size / the pixel canvas wins when the two
 * disagree. This component only maps that descriptor onto controls.
 *
 * The EMU size is the persisted one and is deliberately not derived from the
 * pixels: Ledger is 12179300 EMU = 1278.5px, and a round-trip through an
 * integer pixel would cost the deck its `ppSlideSizeLedgerPaper` identity.
 * `resolveSlideSizeSelection` encodes that rule, so both controls write the EMU
 * size AND the canvas size, and the raw W/H inputs write only the canvas (which
 * is exactly the "user typed a custom size" case the rule falls back for).
 *
 * Slide-size RESCALE prompt (shared `render/slide-size-rescale`,
 * `resolveSlideSizeRescaleTransform` / `scaleSlidesForSizeChange`): PowerPoint
 * asks Maximize-or-Ensure-Fit whenever a size change would resize existing
 * content and the deck has content to resize. A size change that leaves the
 * pending prompt unanswered does not commit until the user picks a mode (or
 * there is nothing to scale, in which case it commits immediately, as before).
 */
import {
	ChangeDetectionStrategy,
	Component,
	computed,
	inject,
	input,
	signal,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';

import {
	scaleSlidesForSizeChange,
	SLIDE_SIZE_PRESETS,
	slideSizeFromCanvasPx,
	slideSizeFromPreset,
	slideSizeToCanvasPx,
	withSlideSizeOrientation,
} from 'ooxml-ui/pptx';
import type {
	SlideSizeEmu,
	SlideSizeOrientation,
	SlideSizePreset,
	SlideSizeRescaleMode,
} from 'ooxml-ui/pptx';
import { EditorStateService } from './editor-state.service';
import { INSPECTOR_CARD_STYLES } from './inspector-card-styles';
import { LoadContentService } from './load-content.service';

/** Sentinel `<option>` value for a size that matches no preset. */
const CUSTOM_PRESET_VALUE = '';

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-slide-size-card',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		<section class="icard" data-pptx-chrome="inspector-card">
			<h3 class="icard__heading" data-pptx-chrome="inspector-heading">
				{{ 'pptx.slideSize.title' | translate }}
			</h3>
			<label class="icard__col">
				<span class="icard__label">{{ 'pptx.slideSize.presets' | translate }}</span>
				<pptx-ui-select
					[attr.aria-label]="'pptx.slideSize.presets' | translate"
					[attr.value]="selectedPresetValue()"
					class="icard__select"
					data-pptx-slide-size-preset
					[disabled]="!canEdit()"
					(change)="onPresetChange($event)"
				>
					@if (!selection().preset) {
						<option [value]="CUSTOM_PRESET_VALUE" [selected]="true">
							{{ 'pptx.slideSize.customSize' | translate }}
						</option>
					}
					@for (preset of presets; track preset.labelKey) {
						<option
							[value]="preset.labelKey"
							[selected]="preset.labelKey === selectedPresetValue()"
						>
							{{ 'pptx.slideSize.preset.' + preset.labelKey | translate }}
						</option>
					}
				</pptx-ui-select>
			</label>
			<div class="icard__col">
				<span class="icard__label">{{ 'pptx.slideSize.orientation' | translate }}</span>
				<div class="icard__row">
					@for (option of orientations; track option) {
						<button
							type="button"
							class="icard__btn"
							data-pptx-slide-size-orientation
							[attr.data-value]="option"
							[class.icard__btn--on]="selection().orientation === option"
							[attr.aria-pressed]="selection().orientation === option"
							[disabled]="!canEdit()"
							(click)="onOrientation(option)"
						>
							{{ 'pptx.slideSize.' + option | translate }}
						</button>
					}
				</div>
			</div>
			<div class="icard__grid2">
				<label class="icard__row">
					<!-- Compact "W"/"H" labels, matching React's SlideSizeCard. -->
					<span class="icard__label">W</span>
					<input
						type="number"
						class="icard__input icard__input--number"
						min="1"
						[disabled]="!canEdit()"
						[value]="size().width"
						(change)="onChange($event, 'width')"
					/>
				</label>
				<label class="icard__row">
					<span class="icard__label">H</span>
					<input
						type="number"
						class="icard__input icard__input--number"
						min="1"
						[disabled]="!canEdit()"
						[value]="size().height"
						(change)="onChange($event, 'height')"
					/>
				</label>
			</div>

			@if (pendingResize(); as pending) {
				<div class="icard__col" data-testid="pptx-slide-size-rescale-prompt">
					<span class="icard__label">{{ 'pptx.slideSize.rescaleTitle' | translate }}</span>
					<p class="icard__hint">{{ 'pptx.slideSize.rescaleDescription' | translate }}</p>
					<div class="icard__row">
						<button
							type="button"
							class="icard__btn"
							data-testid="pptx-slide-size-rescale-maximize"
							[title]="'pptx.slideSize.rescaleMaximizeHint' | translate"
							(click)="onRescaleChoice(pending, 'maximize')"
						>
							{{ 'pptx.slideSize.rescaleMaximize' | translate }}
						</button>
						<button
							type="button"
							class="icard__btn"
							data-testid="pptx-slide-size-rescale-ensure-fit"
							[title]="'pptx.slideSize.rescaleEnsureFitHint' | translate"
							(click)="onRescaleChoice(pending, 'ensureFit')"
						>
							{{ 'pptx.slideSize.rescaleEnsureFit' | translate }}
						</button>
					</div>
				</div>
			}
		</section>
	`,
	styles: [
		INSPECTOR_CARD_STYLES,
		`
			.icard__hint {
				font-size: 11px;
				color: var(--pptx-inspector-muted, #888);
				margin: 0 0 0.35rem;
			}
			.icard__btn--on {
				background: var(--pptx-inspector-accent, #2f6feb);
				border-color: var(--pptx-inspector-accent, #2f6feb);
				color: #fff;
			}
		`,
	],
})
export class SlideSizeCardComponent {
	/** Whether the inputs are enabled. */
	readonly canEdit = input<boolean>(true);

	private readonly loader = inject(LoadContentService);
	private readonly editor = inject(EditorStateService);
	private readonly translate = inject(TranslateService);

	protected readonly CUSTOM_PRESET_VALUE = CUSTOM_PRESET_VALUE;
	protected readonly presets = SLIDE_SIZE_PRESETS;
	protected readonly orientations: readonly SlideSizeOrientation[] = ['landscape', 'portrait'];

	protected readonly size = this.loader.canvasSize;
	protected readonly selection = this.loader.slideSizeSelection;
	protected readonly selectedPresetValue = computed(
		() => this.selection().preset?.labelKey ?? CUSTOM_PRESET_VALUE,
	);

	/**
	 * A confirmed size that differs from the current one and has at least one
	 * element to rescale, awaiting the user's Maximize/Ensure-Fit choice. `null`
	 * once answered (or when no prompt was needed) so the inline prompt hides.
	 */
	protected readonly pendingResize = signal<SlideSizeEmu | null>(null);

	protected onPresetChange(event: Event): void {
		const labelKey = (event.target as HTMLSelectElement).value;
		const preset: SlideSizePreset | undefined = SLIDE_SIZE_PRESETS.find(
			(candidate) => candidate.labelKey === labelKey,
		);
		if (!preset) {
			return;
		}
		this.apply(slideSizeFromPreset(preset, this.selection().orientation));
	}

	protected onOrientation(orientation: SlideSizeOrientation): void {
		const current = this.selection();
		if (current.orientation === orientation) {
			return;
		}
		this.apply(withSlideSizeOrientation(current.size, orientation));
	}

	protected onChange(event: Event, dim: 'width' | 'height'): void {
		const value = Number((event.target as HTMLInputElement).value);
		if (!Number.isFinite(value) || value < 1) {
			return;
		}
		this.apply(slideSizeFromCanvasPx({ ...this.loader.canvasSize(), [dim]: value }));
	}

	/**
	 * PowerPoint's Maximize/Ensure-Fit prompt: choosing a mode rescales every
	 * slide's elements (one undoable history entry via
	 * `EditorStateService.applyReplacement`) before the new size itself commits.
	 */
	protected onRescaleChoice(pending: SlideSizeEmu, mode: SlideSizeRescaleMode): void {
		const oldSize = this.selection().size;
		const rescaled = scaleSlidesForSizeChange(this.editor.slides(), oldSize, pending, mode);
		this.editor.applyReplacement(rescaled, this.translate.instant('pptx.slideSize.rescaleTitle'));
		this.commit(pending);
		this.pendingResize.set(null);
	}

	/**
	 * Commit a confirmed size, prompting first (PowerPoint's Maximize/Ensure
	 * Fit) when it differs from the current size AND the deck has at least one
	 * element anywhere to rescale; an empty deck commits directly, as before.
	 */
	private apply(next: SlideSizeEmu): void {
		const current = this.selection().size;
		const sizeChanged = current.widthEmu !== next.widthEmu || current.heightEmu !== next.heightEmu;
		const hasContent = this.editor.slides().some((slide) => slide.elements.length > 0);
		if (sizeChanged && hasContent) {
			this.pendingResize.set(next);
			return;
		}
		this.commit(next);
	}

	/** Commit an EMU size and the canvas size it implies, together. */
	private commit(next: SlideSizeEmu): void {
		this.loader.slideSizeEmu.set(next);
		this.loader.canvasSize.set(slideSizeToCanvasPx(next));
		this.editor.dirty.set(true);
	}
}
