// viewers/pptx/packages/vue/src/viewer/components/SmartArtRenderer.vue
<script setup lang="ts">
import type {
	PptxElement,
	PptxSmartArtChrome,
	PptxSmartArtDrawingShape,
	PptxSmartArtNode,
	SmartArtStyle,
} from 'pptx-viewer-core';
import { setSmartArtNodeStyle } from 'pptx-viewer-core';
import {
	buildChromeStyle,
	buildSmartArtA11y,
	canDrillDown,
	computeDrawingViewBox,
	measureSvgViewportRect,
	projectDrawingShapes,
	resolveRevealedDrawingShapeNodeIds,
	resolvePalette,
	resolveRevealedDrawingShapes,
	resolveRevealedSmartArtNodes,
	shouldCommitSmartArtNodeText,
	smartArtConnectorPaint,
	smartArtNodeLabel,
	styleShadowFilter,
} from 'ooxml-ui/pptx';
import type {
	ElementAnimationState,
	RenderedShape,
	SmartArtConnectorPaint,
	SmartArtNodeLabel,
} from 'ooxml-ui/pptx';
import type { CSSProperties } from 'vue';
import { computed, nextTick, ref } from 'vue';
import { useI18n } from 'vue-i18n';

import { useElementHitTargetStyle } from '../composables/element-hit-target';
import { getContainerStyle } from '../composables/element-style';
import {
	nodeIdsInRenderOrder,
	useSmartArtInlineEditState,
} from '../composables/smartart-inline-edit';
import type {
	RenderedCircleNode,
	RenderedPolygonNode,
	RenderedRectNode,
	SmartArtLayoutResult as ComputedLayout,
} from '../composables/smartart-layout';
import { computeSmartArtElementLayout } from '../composables/smartart-layout';
import { injectSmartArtNodeEdit } from '../composables/smartart-node-edit';
import { useSmartArtHoverRect } from '../composables/useSmartArtHoverRect';
import SmartArtNodeStyleBar from './SmartArtNodeStyleBar.vue';

/**
 * SmartArtRenderer - Vue port of the React SmartArt renderer
 * (`viewer/utils/smartart*.tsx`).
 *
 * Data path: this component renders from the **pre-computed drawing shapes**
 * (`smartArtData.drawingShapes`) extracted by the core engine from
 * `ppt/diagrams/drawing*.xml`, mirroring React's `smartart-drawing.tsx`.
 * That is the path React prefers when drawing shapes are present, and it
 * avoids reimplementing the ~2800 LOC of layout math in the
 * `smartart-cycle/process/hierarchy/...` family.
 *
 * Fallbacks (mirroring `renderSmartArtElement`'s early returns):
 *  - No `smartArtData` or zero nodes → a small "SmartArt" placeholder.
 *  - Nodes present but no drawing shapes → a simple stacked block list of the
 *    node text (the common-case fallback; the full per-family layout renderers
 *    are out of scope per the porting brief).
 *
 * The whole graphic is wrapped in chrome (background / outline) when present.
 */
const props = defineProps<{
	element: PptxElement;
	mediaDataUrls?: Map<string, string>;
	zIndex: number;
	/**
	 * True only for the main editable canvas instance. The `data-testid` layout
	 * hooks are emitted solely when interactive so the identical mini-renders in
	 * the thumbnail rail / slide sorter / presenter don't duplicate the id and
	 * break single-element test locators.
	 */
	interactive?: boolean;
	/** Emit the data-pptx-element marker even when not interactive (template layer). */
	marked?: boolean;
	/** True only on the live presentation stage; see `hitTargetStyle`. */
	presenting?: boolean;
	/**
	 * Native-animation playback state. A staged diagram build
	 * (`build.kind === 'diagram'`) reveals the leading nodes / drawing shapes for
	 * the current progress; absent or non-diagram state renders every node.
	 */
	animationState?: ElementAnimationState;
	/**
	 * Scoped `!important` CSS override for an active font-style emphasis effect
	 * (Bold Flash, Bold Reveal, Underline, Change Font Style/Size), built by the
	 * parent `ElementRenderer` (`buildTextStyleOverrideCss`) so a SmartArt node
	 * caption animates the same way a shape's text does.
	 */
	textStyleOverrideCss?: string;
}>();

const { t } = useI18n();

// ── Resolved SmartArt data ───────────────────────────────────────────────────

const smartArtData = computed(() =>
	props.element.type === 'smartArt' ? props.element.smartArtData : undefined,
);

const nodes = computed<PptxSmartArtNode[]>(() => smartArtData.value?.nodes ?? []);

// ── Accessibility (shared view-model) ────────────────────────────────────────
//
// The generated SVG is opaque to assistive technology, so we derive a
// screen-reader description for the whole diagram (`role="img"` + aria-label on
// the chrome container) and a per-node label looked up by node id, via the
// framework-agnostic `buildSmartArtA11y` from pptx-viewer-shared.

const a11y = computed(() =>
	smartArtData.value ? buildSmartArtA11y(smartArtData.value) : undefined,
);

const nodeLabels = computed<Map<string, string>>(() => {
	const map = new Map<string, string>();
	for (const n of a11y.value?.nodes ?? []) {
		map.set(n.id, n.label);
	}
	return map;
});

/** Per-node ARIA label / SVG <title> text, by node id (empty when unknown). */
function nodeLabel(nodeId: string | undefined): string | undefined {
	return nodeId ? nodeLabels.value.get(nodeId) : undefined;
}

const palette = computed<string[]>(() => resolvePalette(smartArtData.value));

const style = computed<SmartArtStyle>(() => smartArtData.value?.style ?? 'flat');

const chrome = computed<PptxSmartArtChrome | undefined>(() => smartArtData.value?.chrome);

const containerStyle = computed<CSSProperties>(() =>
	getContainerStyle(props.element, props.zIndex),
);

/**
 * `pointer-events: none` on the root while not interactive, mirroring
 * React's `pointer-events-none` class / Angular's `rootPointerEvents`. The
 * inner `.pptx-vue-smartart-svg` is already `pointer-events: none` by default
 * CSS (with editable node groups opting back in via
 * `.pptx-vue-smartart-editable`), but nothing previously gated the OUTER
 * `pptx-vue-smartart` box itself, so its background/chrome area stayed
 * clickable even while `marked` locked the element (e.g. a template/master
 * diagram with `editTemplateMode` off). `null` while interactive so the
 * style-array merge leaves any pre-existing `pointerEvents` untouched.
 */
const rootPointerEvents = computed<CSSProperties | null>(() =>
	props.interactive ? null : { pointerEvents: 'none' },
);

/**
 * Interaction-only affordance for a degenerate (sub-MIN_ELEMENT_SIZE)
 * SmartArt: see `ElementRenderer`'s `hitTargetStyle` doc comment (issue
 * #285). Never rendered while presenting.
 */
const hitTargetStyle = useElementHitTargetStyle(
	() => props.element,
	() => props.interactive,
	() => props.presenting,
);

/**
 * The chrome wrapper's background/outline decision, from the shared
 * `buildChromeStyle` (same function Angular/Svelte/Vanilla call directly).
 * Its `CssStyleMap` return is kebab-case; Vue's `CSSProperties` accepts both
 * kebab and camelCase keys, so this only needs a type cast, not a converter.
 */
const chromeStyle = computed<CSSProperties>(() => buildChromeStyle(chrome.value) as CSSProperties);

// ── Drawing-shape path (mirrors smartart-drawing.tsx) ────────────────────────

const drawingShapes = computed<PptxSmartArtDrawingShape[]>(
	() => smartArtData.value?.drawingShapes ?? [],
);

const hasDrawingShapes = computed(() => drawingShapes.value.length > 0);

// ── Staged diagram build (p:bldDgm) reveal ──────────────────────────────────
//
// When an active native animation carries a staged diagram build, reveal only
// the leading nodes / drawing shapes for the current progress, preferring the
// AUTHORED per-node `p:graphicEl/@id` reveal set (`animationState.diagramReveal`)
// over the click-count estimate when available; the view box is still computed
// from the FULL shape set so the diagram does not rescale as it builds.
// Mirrors React's `SmartArtRenderer` reveal slice.

const diagramReveal = computed(() =>
	resolveRevealedSmartArtNodes(
		nodes.value,
		props.animationState,
		smartArtData.value?.presLayoutVars,
	),
);

/** Leading node prefix revealed so far (full list when no partial build). */
const revealedNodes = computed<PptxSmartArtNode[]>(() => diagramReveal.value.nodes);

/** Revealed drawing-shape subset, preferring the authored node-id set. */
const revealedShapeList = computed<PptxSmartArtDrawingShape[]>(() =>
	drawingShapes.value.length === 0
		? drawingShapes.value
		: resolveRevealedDrawingShapes(drawingShapes.value, nodes.value, props.animationState),
);

/** Shape descriptor plus the source node id used for inline editing. */
type EditableShape = RenderedShape & { nodeId?: string };

const drawingViewBox = computed(() => computeDrawingViewBox(drawingShapes.value));

const renderedShapes = computed<EditableShape[]>(() => {
	// Each shape maps back to its source node id via the shared best-effort
	// resolver (positional / reflow-suffix / unique-text), rather than a
	// running index into `nodes` in original order: a staged build's revealed
	// shape SUBSET is not necessarily a leading prefix (the authored-index
	// diagramReveal descriptor can reveal an out-of-order set), so the two
	// lists are no longer guaranteed to walk in lockstep.
	const revealed = revealedShapeList.value;
	const nodeIds = resolveRevealedDrawingShapeNodeIds(drawingShapes.value, revealed, nodes.value);
	return projectDrawingShapes(
		props.element.id,
		revealed,
		drawingViewBox.value,
		palette.value,
		style.value,
	).map((shape, i) => ({
		...shape,
		nodeId: nodeIds[i],
	}));
});

/**
 * Seed text for an inline edit. The rendered lines are a wrapped view of the
 * authored string, so they are joined back with spaces rather than newlines to
 * avoid writing the wrap points into the node.
 */
function shapeEditText(shape: EditableShape): string {
	return shape.textLines.map((line) => line.text).join(' ');
}

const shadowFilter = computed(() => styleShadowFilter(style.value));

// ── SVG layout fallback (no drawing shapes) ──────────────────────────────────
//
// When drawing shapes are absent the component runs the pure-geometry layout
// engine from `smartart-layout.ts` to produce an SVG approximation.

const fallbackLayout = computed<ComputedLayout | undefined>(() => {
	if (hasDrawingShapes.value || nodes.value.length === 0) {
		return undefined;
	}
	const data = smartArtData.value;
	return computeSmartArtElementLayout(
		data ?? {},
		revealedNodes.value,
		{ width: props.element.width, height: props.element.height },
		palette.value,
		style.value,
		props.element.id,
	);
});

// ── Fallback-layout label / connector paint ──────────────────────────────────
//
// The layout descriptor's optional fields (per-node font colour / weight /
// style, off-centre label anchors for target leaders, gear legend rows and
// timeline captions, and per-connector stroke) are resolved by the shared
// decision functions below. The template binds the result and computes nothing.

/** Resolved connector paint, index-aligned with `fallbackLayout.connectors`. */
const fallbackConnectors = computed<SmartArtConnectorPaint[]>(() =>
	(fallbackLayout.value?.connectors ?? []).map((conn) => smartArtConnectorPaint(conn)),
);

/** Resolved label descriptors, index-aligned with `fallbackLayout.nodes`. */
const fallbackLabels = computed<SmartArtNodeLabel[]>(() =>
	(fallbackLayout.value?.nodes ?? []).map((node) => smartArtNodeLabel(node)),
);

const isEmpty = computed(() => nodes.value.length === 0 && !hasDrawingShapes.value);

// ── Inline on-canvas node text editing ───────────────────────────────────────
//
// A node-edit context, when provided by the host (edit mode, not presenting),
// lets a double-click on a node open an inline <textarea> over it. Commit flows
// through the SAME core op the inspector uses (`updateSmartArtNodeText` via
// `updateElement`), so undo/redo and save round-trip are identical.

const nodeEdit = injectSmartArtNodeEdit();
// G8: `a:graphicFrameLocks/@noDrilldown` forbids entering this SmartArt's
// individual nodes for editing.
const editable = computed(() => Boolean(nodeEdit?.canEdit()) && canDrillDown(props.element));

/**
 * Source node ids in fallback render order (index-aligned with layout nodes).
 * Flattened over the REVEALED prefix, since that is what the layout engine was
 * handed: a staged diagram build otherwise mapped ids past the reveal point.
 */
const fallbackNodeIds = computed<string[]>(() =>
	fallbackLayout.value ? nodeIdsInRenderOrder(revealedNodes.value) : [],
);

const edit = useSmartArtInlineEditState();
const rootEl = ref<HTMLElement | null>(null);
const editorEl = ref<HTMLTextAreaElement | null>(null);
// Anchors the style-bar popover; mousemove events landing inside it must not
// clear the hover state, or the popover would unmount as soon as the pointer
// reaches the swatches it needs to be clicked.
const styleBarEl = ref<HTMLElement | null>(null);
const {
	hoveredNodeId,
	hoveredNodeRect,
	onMouseMove: onHoverMouseMove,
	onMouseLeave,
} = useSmartArtHoverRect(rootEl);

function onMouseMove(event: MouseEvent): void {
	onHoverMouseMove(event, styleBarEl.value);
}

/** Approximate rendered size of the style bar (6 swatches + padding/border). */
const STYLE_BAR_WIDTH = 168;
const STYLE_BAR_HEIGHT = 40;

/** Style-bar position, clamped so it stays within the chrome's clipped bounds. */
const styleBarStyle = computed<CSSProperties | undefined>(() => {
	const rect = hoveredNodeRect.value;
	const container = rootEl.value;
	if (!rect || !container) {
		return undefined;
	}
	const maxLeft = Math.max(0, container.clientWidth - STYLE_BAR_WIDTH);
	const maxTop = Math.max(0, container.clientHeight - STYLE_BAR_HEIGHT);
	return {
		position: 'absolute',
		left: `${Math.min(maxLeft, Math.max(0, rect.left + rect.width - STYLE_BAR_WIDTH))}px`,
		top: `${Math.min(maxTop, Math.max(0, rect.top - 22))}px`,
		zIndex: 25,
	};
});

/**
 * Enter edit mode using local SVG geometry. The textarea inherits the same
 * outer canvas transform, so its coordinates must not include zoom twice.
 */
function beginEdit(nodeId: string | undefined, text: string, event: Event): void {
	if (!editable.value || !nodeId) {
		return;
	}
	const target = event.currentTarget as Element | null;
	const host = rootEl.value;
	if (!target || !host) {
		return;
	}
	const rect = measureSvgViewportRect(target);
	if (!rect) {
		return;
	}
	edit.begin(nodeId, text, rect);
	void nextTick(() => {
		editorEl.value?.focus();
		editorEl.value?.select();
	});
}

/** Commit the draft text through the host op, skipping no-op edits. */
function commitEdit(): void {
	const nodeId = edit.editingNodeId.value;
	const data = smartArtData.value;
	if (nodeId && data && nodeEdit && shouldCommitSmartArtNodeText(data, nodeId, edit.draft.value)) {
		nodeEdit.commit(props.element.id, nodeId, edit.draft.value);
	}
	edit.cancel();
}

function cancelEdit(): void {
	edit.cancel();
}

/** Apply a fill colour to a node by id, routing through the host commitStyle op. */
function handleChangeNodeStyle(nodeId: string, fill: string): void {
	const data = smartArtData.value;
	if (!data || !nodeEdit) {
		return;
	}
	const next = setSmartArtNodeStyle(data, nodeId, { fillColor: fill });
	if (next !== data) {
		nodeEdit.commitStyle?.(props.element.id, { smartArtData: next } as Partial<PptxElement>);
	}
}

/**
 * Stop all keydown bubbling so parent shortcuts (Delete, arrow keys, etc.)
 * do not fire while typing in the editor. Enter commits; Shift+Enter inserts
 * a newline; Escape cancels.
 */
function onEditorKeydown(event: KeyboardEvent): void {
	event.stopPropagation();
	if (event.key === 'Enter' && !event.shiftKey) {
		event.preventDefault();
		commitEdit();
	} else if (event.key === 'Escape') {
		event.preventDefault();
		cancelEdit();
	}
}
</script>

<template>
	<div
		class="pptx-vue-element pptx-vue-smartart"
		:style="[containerStyle, rootPointerEvents]"
		:data-element-id="element.id"
		:data-pptx-element="props.interactive || props.marked ? 'true' : undefined"
		aria-roledescription="diagram"
	>
		<!-- Interaction-only hit-target for a degenerate SmartArt; see `hitTargetStyle`. -->
		<div
			v-if="hitTargetStyle"
			aria-hidden="true"
			data-pptx-hit-target="true"
			:style="hitTargetStyle"
		/>
		<!--
			`<style>` is a forbidden side-effect tag in an SFC template, so the
			override is rendered through the dynamic `<component :is>` escape
			hatch instead (see `ElementRenderer.vue`).
		-->
		<component :is="'style'" v-if="textStyleOverrideCss">{{ textStyleOverrideCss }}</component>
		<div
			ref="rootEl"
			class="pptx-vue-smartart-chrome"
			:style="chromeStyle"
			:role="a11y ? 'img' : undefined"
			:aria-label="a11y?.label"
			@mousemove="onMouseMove"
			@mouseleave="onMouseLeave"
		>
			<!-- Empty / no-data placeholder -->
			<div v-if="isEmpty" class="pptx-vue-smartart-placeholder">
				{{ t('pptx.smartArt.placeholder') }}
			</div>

			<!-- Pre-computed drawing shapes (preferred path) -->
			<svg
				v-else-if="hasDrawingShapes"
				class="pptx-vue-smartart-svg"
				:data-testid="props.interactive ? 'smartart-drawing-shapes' : undefined"
				:viewBox="`0 0 ${drawingViewBox.width} ${drawingViewBox.height}`"
				preserveAspectRatio="xMidYMid meet"
			>
				<g
					v-for="shape in renderedShapes"
					:key="shape.key"
					:class="{ 'pptx-vue-smartart-editable': editable && shape.nodeId }"
					:data-node-id="shape.nodeId"
					:data-smartart-node-id="shape.nodeId || undefined"
					:tabindex="editable && shape.nodeId ? 0 : undefined"
					:role="nodeLabel(shape.nodeId) ? 'img' : undefined"
					:aria-label="nodeLabel(shape.nodeId)"
					:style="shadowFilter ? { filter: shadowFilter } : undefined"
					@dblclick="beginEdit(shape.nodeId, shapeEditText(shape), $event)"
					@keydown.enter.prevent="beginEdit(shape.nodeId, shapeEditText(shape), $event)"
				>
					<title v-if="nodeLabel(shape.nodeId)">{{ nodeLabel(shape.nodeId) }}</title>
					<defs v-if="shape.gradient">
						<radialGradient
							v-if="shape.gradient.kind === 'radial'"
							:id="shape.gradient.id"
							:cx="shape.gradient.cx"
							:cy="shape.gradient.cy"
							:r="shape.gradient.r"
						>
							<stop
								v-for="(stop, si) in shape.gradient.stops"
								:key="si"
								:offset="stop.offset"
								:stop-color="stop.color"
								:stop-opacity="stop.opacity"
							/>
						</radialGradient>
						<linearGradient
							v-else
							:id="shape.gradient.id"
							:x1="shape.gradient.x1"
							:y1="shape.gradient.y1"
							:x2="shape.gradient.x2"
							:y2="shape.gradient.y2"
						>
							<stop
								v-for="(stop, si) in shape.gradient.stops"
								:key="si"
								:offset="stop.offset"
								:stop-color="stop.color"
								:stop-opacity="stop.opacity"
							/>
						</linearGradient>
					</defs>
					<image
						v-if="shape.kind === 'image'"
						:x="shape.x"
						:y="shape.y"
						:width="shape.width"
						:height="shape.height"
						:href="shape.imageUrl"
						preserveAspectRatio="xMidYMid meet"
						:transform="shape.transform"
					/>
					<ellipse
						v-else-if="shape.kind === 'ellipse'"
						:cx="shape.cx"
						:cy="shape.cy"
						:rx="shape.width / 2"
						:ry="shape.height / 2"
						:fill="shape.fill"
						:fill-opacity="shape.fillOpacity"
						:stroke="shape.stroke"
						:stroke-width="shape.strokeWidth"
						:transform="shape.transform"
					/>
					<path
						v-else-if="shape.kind === 'path'"
						:d="shape.pathData"
						:fill="shape.fill"
						:fill-opacity="shape.fillOpacity"
						:stroke="shape.stroke"
						:stroke-width="shape.strokeWidth"
						:transform="shape.pathTransform"
					/>
					<rect
						v-else
						:x="shape.x"
						:y="shape.y"
						:width="shape.width"
						:height="shape.height"
						:rx="shape.rx"
						:fill="shape.fill"
						:fill-opacity="shape.fillOpacity"
						:stroke="shape.stroke"
						:stroke-width="shape.strokeWidth"
						:transform="shape.transform"
					/>
					<text
						v-if="shape.textLines.length > 0"
						:x="shape.textX"
						text-anchor="middle"
						dominant-baseline="central"
						:fill="shape.fontColor"
						:font-size="shape.fontSize"
						:font-family="shape.fontFamily"
						:font-weight="shape.fontWeight"
						:font-style="shape.fontStyle"
					>
						<tspan v-for="(line, li) in shape.textLines" :key="li" :x="shape.textX" :y="line.y">
							{{ line.text }}
						</tspan>
					</text>
				</g>
			</svg>

			<!-- Fallback: SVG layout computed from node tree -->
			<svg
				v-else-if="fallbackLayout"
				class="pptx-vue-smartart-svg"
				:viewBox="fallbackLayout.viewBox"
				preserveAspectRatio="xMidYMid meet"
				:data-testid="props.interactive ? `smartart-${fallbackLayout.family}` : undefined"
				:data-layout-family="fallbackLayout.family"
			>
				<!-- Connectors (render first so they appear behind nodes) -->
				<path
					v-for="(conn, ci) in fallbackLayout.connectors"
					:key="conn.key"
					:d="fallbackConnectors[ci]!.d"
					fill="none"
					:stroke="fallbackConnectors[ci]!.stroke"
					:stroke-width="fallbackConnectors[ci]!.strokeWidth"
					:opacity="fallbackConnectors[ci]!.opacity"
					:stroke-dasharray="fallbackConnectors[ci]!.dash"
				/>
				<!-- Rendered nodes -->
				<g
					v-for="(node, i) in fallbackLayout.nodes"
					:key="node.key"
					:class="{ 'pptx-vue-smartart-editable': editable && fallbackNodeIds[i] }"
					:data-node-id="fallbackNodeIds[i]"
					:data-smartart-node-id="fallbackNodeIds[i] || undefined"
					:tabindex="editable && fallbackNodeIds[i] ? 0 : undefined"
					:role="nodeLabel(fallbackNodeIds[i]) ? 'img' : undefined"
					:aria-label="nodeLabel(fallbackNodeIds[i])"
					:style="fallbackLayout.shadowFilter ? { filter: fallbackLayout.shadowFilter } : undefined"
					@dblclick="beginEdit(fallbackNodeIds[i], node.text, $event)"
					@keydown.enter.prevent="beginEdit(fallbackNodeIds[i], node.text, $event)"
				>
					<title v-if="nodeLabel(fallbackNodeIds[i])">{{ nodeLabel(fallbackNodeIds[i]) }}</title>
					<!-- Circle nodes (cycle, radial, venn, target, gear, timeline) -->
					<circle
						v-if="node.kind === 'circle'"
						:cx="(node as RenderedCircleNode).cx"
						:cy="(node as RenderedCircleNode).cy"
						:r="(node as RenderedCircleNode).r"
						:fill="node.fill"
						:stroke="node.stroke"
						:stroke-width="node.strokeWidth"
						:opacity="node.opacity"
					/>
					<!-- Polygon nodes (process, pyramid, funnel) -->
					<polygon
						v-else-if="node.kind === 'polygon'"
						:points="(node as RenderedPolygonNode).points"
						:fill="node.fill"
						:stroke="node.stroke"
						:stroke-width="node.strokeWidth"
						:opacity="node.opacity"
					/>
					<!-- Rect nodes (list, matrix, hierarchy) -->
					<rect
						v-else
						:x="(node as RenderedRectNode).x"
						:y="(node as RenderedRectNode).y"
						:width="(node as RenderedRectNode).width"
						:height="(node as RenderedRectNode).height"
						:rx="(node as RenderedRectNode).rx"
						:fill="node.fill"
						:stroke="node.stroke"
						:stroke-width="node.strokeWidth"
						:opacity="node.opacity"
					/>
					<!--
						Label: placement, colour, weight and baseline all arrive decided
						from shared, so an off-centre caption (target leader, gear legend
						row, timeline caption above / below the axis) lands beside its
						node rather than on top of it.
					-->
					<text
						v-if="fallbackLabels[i]!.visible"
						:x="fallbackLabels[i]!.x"
						:text-anchor="fallbackLabels[i]!.textAnchor"
						:dominant-baseline="fallbackLabels[i]!.dominantBaseline"
						:fill="fallbackLabels[i]!.fill"
						:font-size="fallbackLabels[i]!.fontSize"
						:font-weight="fallbackLabels[i]!.fontWeight"
						:font-style="fallbackLabels[i]!.fontStyle"
					>
						<tspan
							v-for="(line, li) in fallbackLabels[i]!.lines"
							:key="li"
							:x="fallbackLabels[i]!.x"
							:y="line.y"
						>
							{{ line.text }}
						</tspan>
					</text>
				</g>
			</svg>

			<!-- Per-node fill colour picker (hover swatch bar, edit mode only) -->
			<div
				v-if="editable && hoveredNodeId && !edit.isEditing.value && hoveredNodeRect"
				ref="styleBarEl"
				:style="styleBarStyle"
			>
				<SmartArtNodeStyleBar
					:palette="palette"
					@pick-fill="handleChangeNodeStyle(hoveredNodeId!, $event)"
				/>
			</div>

			<!-- Inline node text editor overlay (edit mode only) -->
			<textarea
				v-if="edit.isEditing.value && edit.rect.value"
				ref="editorEl"
				v-model="edit.draft.value"
				class="pptx-vue-smartart-node-editor"
				spellcheck="false"
				:aria-label="t('pptx.smartArt.editNodeText')"
				:style="{
					left: `${edit.rect.value.left}px`,
					top: `${edit.rect.value.top}px`,
					width: `${edit.rect.value.width}px`,
					height: `${edit.rect.value.height}px`,
				}"
				@keydown="onEditorKeydown"
				@mousedown.stop
				@click.stop
				@dblclick.stop
				@blur="commitEdit"
			/>
		</div>
	</div>
</template>

<style scoped>
.pptx-vue-smartart-chrome {
	position: relative;
	box-sizing: border-box;
	overflow: hidden;
}

.pptx-vue-smartart-svg {
	width: 100%;
	height: 100%;
	pointer-events: none;
}

/* Editable node groups opt back into pointer events so a double-click can
   enter inline edit mode without breaking element selection/drag elsewhere. */
.pptx-vue-smartart-editable {
	pointer-events: auto;
	cursor: text;
}

/* Hover ring: outline does not render on SVG <g> elements in all browsers,
   so drop-shadow is used as the visual confirmation that a node is editable. */
.pptx-vue-smartart-editable:hover {
	filter: drop-shadow(0 0 2px rgba(96, 165, 250, 0.8));
}

.pptx-vue-smartart-node-editor {
	position: absolute;
	z-index: 2;
	margin: 0;
	padding: 2px;
	border: 1px solid #2563eb;
	border-radius: 3px;
	box-sizing: border-box;
	resize: none;
	overflow: hidden;
	font: inherit;
	font-size: 12px;
	line-height: 1.2;
	text-align: center;
	color: #111;
	background: #fff;
}

.pptx-vue-smartart-placeholder {
	width: 100%;
	height: 100%;
	display: flex;
	align-items: center;
	justify-content: center;
	font-size: 11px;
	color: rgba(255, 255, 255, 0.8);
	pointer-events: none;
}

.pptx-vue-smartart-list {
	width: 100%;
	height: 100%;
	display: flex;
	flex-direction: column;
	gap: 4px;
	padding: 4px;
	box-sizing: border-box;
	overflow: hidden;
}

.pptx-vue-smartart-block {
	flex: 1 1 0;
	min-height: 0;
	display: flex;
	align-items: center;
	justify-content: center;
	padding: 2px 6px;
	border-radius: 4px;
	color: #fff;
	font-size: 12px;
	text-align: center;
	overflow: hidden;
}
</style>

// viewers/pptx/packages/angular/src/viewer/smart-art-renderer.component.ts
import { NgStyle } from '@angular/common';
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	DestroyRef,
	effect,
	ElementRef,
	inject,
	Injector,
	input,
	signal,
	viewChild,
} from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import type { PptxElement, PptxSmartArtData } from 'pptx-viewer-core';
import { setSmartArtNodeStyle } from 'pptx-viewer-core';

import {
	buildSmartArtA11y,
	measureSvgViewportRect,
	computeSmartArtElementLayout,
	findSmartArtNodeText,
	flattenNodes,
	rebuildDrawingShapesIfCleared,
	resolveRevealedDrawingShapeNodeIds,
	resolveRevealedDrawingShapes,
	resolveRevealedSmartArtNodes,
} from 'ooxml-ui/pptx';
import type {
	ElementAnimationState,
	InlineEditRect,
	RenderedNode,
	SmartArtA11y,
	SmartArtConnectorPaint,
	SmartArtLayoutResult,
	SmartArtNodeLabel,
} from 'ooxml-ui/pptx';
import { EditorStateService } from './editor-state.service';
import type { StyleMap } from './element-style';
import { SLIDE_CONTEXT } from './slide-context';
import {
	buildChromeStyle,
	computeDrawingViewBox,
	projectDrawingShapes,
	resolvePalette,
	styleShadowFilter,
} from './smart-art-drawing';
import type { DrawingViewBox, RenderedShape } from './smart-art-drawing';
import {
	beginDrawingNodeEdit,
	beginNodeEdit,
	canEditSmartArtNodes,
	commitNodeText,
	findOwningSlideIndex,
} from './smart-art-inline-edit';
import type { InlineEditState } from './smart-art-inline-edit';
import {
	layoutConnectorPaints,
	layoutNodeLabels,
	narrowToCircle,
	narrowToPolygon,
	narrowToRect,
} from './smart-art-renderer-helpers';

/**
 * SmartArtRendererComponent: Angular SmartArt renderer.
 *
 * Data path mirrors the Vue `SmartArtRenderer.vue` and the React renderer:
 *  1. **Drawing shapes** (`smartArtData.drawingShapes`) -- the preferred path
 *     when the core extracted per-shape geometry from `ppt/diagrams/drawing*.xml`.
 *  2. **Shared SVG-fallback engine** (`computeSmartArtLayout`) -- when no drawing
 *     shapes exist, the framework-agnostic engine in `pptx-viewer-shared`
 *     positions/styles the node tree across all 10 layout families (list /
 *     process / cycle / hierarchy / matrix / radial / pyramid / venn / funnel /
 *     target), returning `RenderedNode[]` (rect / circle / polygon) +
 *     `RenderedConnector[]` view-models. Every binding renders the same
 *     geometry; this maps those view-models to SVG exactly as Vue does.
 *  3. **Placeholder** -- when there is neither data nor any nodes/shapes.
 *
 * Positioning is NOT this component's job: its chrome root fills the positioned,
 * element-id bearing box its host draws (the element dispatcher, the 3D
 * renderer's fallback branch, or a preview stage), the same contract the chart
 * and table renderers follow. Owning `left`/`top` here too offset the diagram
 * twice, and stamping the element id on this root hid the host's marked node
 * from anything reading the element contract by id.
 */
@Component({
	selector: 'pptx-smart-art-renderer',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [NgStyle, TranslatePipe],
	templateUrl: './smart-art-renderer.component.html',
	styleUrl: './smart-art-renderer.component.css',
})
export class SmartArtRendererComponent {
	/** The smartArt element to render. Must be `type === 'smartArt'`. */
	readonly element = input.required<PptxElement>();

	/**
	 * Whether inline on-canvas node-text editing is enabled. False in
	 * presentation / read-only / thumbnail contexts (mirrors the table renderer's
	 * `editable` input). Double-clicking a node only enters edit mode when true.
	 */
	readonly editable = input<boolean>(false);

	/**
	 * Native-animation playback state. A staged diagram build
	 * (`build.kind === 'diagram'`) reveals the leading nodes / drawing shapes for
	 * the current progress; absent or non-diagram state renders every node. The
	 * view box is still computed from the FULL shape set so the diagram does not
	 * rescale as it builds. Mirrors the Vue `SmartArtRenderer`'s reveal slice.
	 */
	readonly animationState = input<ElementAnimationState | undefined>(undefined);

	/**
	 * The editor state layer. Optional: the renderer is also used outside the
	 * editing viewer (thumbnails, export), where this service is not provided.
	 * Inline editing commits through `updateElement` here, the exact channel the
	 * inspector's SmartArt panel uses, so undo/redo + save round-trip are shared.
	 */
	private readonly editor = inject(EditorStateService, { optional: true });
	/** The hosting canvas's slide, for resolving template (master/layout) SmartArt. */
	private readonly slideContext = inject(SLIDE_CONTEXT, { optional: true });
	private readonly injector = inject(Injector);
	private readonly translate = inject(TranslateService);

	/** The node currently being edited on the canvas, or null. */
	protected readonly editState = signal<InlineEditState | null>(null);

	/** The mounted `<textarea>` for the active node edit, if any. */
	private readonly nodeEditor = viewChild<ElementRef<HTMLTextAreaElement>>('nodeEditor');

	/** Container div ref used to project hover rects into local coordinates. */
	private readonly smartartContainer = viewChild<ElementRef>('smartartContainer');

	/**
	 * The mounted style-bar popover, if any. Mousemove events landing inside it
	 * must not clear hover state, or the popover would unmount as soon as the
	 * pointer reaches the swatches it needs to be clicked.
	 */
	private readonly styleBar = viewChild<ElementRef>('styleBar');

	/** Pending "leave" timeout: grace period for the pointer to reach the style bar. */
	private hideTimeout: ReturnType<typeof setTimeout> | null = null;

	/**
	 * Guards against a cancel-triggered DOM-removal blur committing the edit.
	 * Set to true before programmatic cancellation; reset to false on each new edit.
	 */
	private editSettled = false;

	/** Whether node double-click / Enter enters inline edit (editable + has editor). */
	readonly canEditNodes = computed(() =>
		canEditSmartArtNodes(this.editable(), this.editor !== null, this.element()),
	);

	constructor() {
		inject(DestroyRef).onDestroy(() => this.cancelPendingHide());
		// Focus + select-all the editor as soon as it mounts (mirrors the table
		// renderer's cell-input effect).
		effect(() => {
			if (this.editState()) {
				afterNextRender(
					() => {
						const el = this.nodeEditor()?.nativeElement;
						if (el) {
							el.focus();
							el.select();
						}
					},
					{ injector: this.injector },
				);
			}
		});
	}

	private readonly smartArtData = computed(() => {
		const el = this.element();
		return el.type === 'smartArt' ? el.smartArtData : undefined;
	});

	readonly chromeStyle = computed<StyleMap>(() => buildChromeStyle(this.smartArtData()?.chrome));

	readonly palette = computed<string[]>(() => resolvePalette(this.smartArtData()));

	readonly artStyle = computed(() => this.smartArtData()?.style ?? 'flat');

	readonly nodes = computed(() => this.smartArtData()?.nodes ?? []);

	readonly shadowFilter = computed<string | undefined>(() => styleShadowFilter(this.artStyle()));

	private readonly rawDrawingShapes = computed(() => this.smartArtData()?.drawingShapes ?? []);

	readonly hasDrawingShapes = computed(() => this.rawDrawingShapes().length > 0);

	// ── Staged diagram build (p:bldDgm) reveal ──────────────────────────────
	//
	// When an active native animation carries a staged diagram build, reveal only
	// the leading nodes / drawing shapes for the current progress, preferring the
	// AUTHORED per-node `p:graphicEl/@id` reveal set (animationState().diagramReveal)
	// over the click-count estimate when available; the view box is still computed
	// from the FULL shape set so the diagram does not rescale.

	private readonly diagramReveal = computed(() =>
		resolveRevealedSmartArtNodes(
			this.nodes(),
			this.animationState(),
			this.smartArtData()?.presLayoutVars,
		),
	);

	/** Leading node prefix revealed so far (full list when no partial build). */
	private readonly revealedNodes = computed(() => this.diagramReveal().nodes);

	/** Revealed drawing-shape subset, preferring the authored node-id set. */
	private readonly revealedShapeList = computed(() => {
		const shapes = this.rawDrawingShapes();
		return shapes.length === 0
			? shapes
			: resolveRevealedDrawingShapes(shapes, this.nodes(), this.animationState());
	});

	private readonly viewBox = computed<DrawingViewBox>(() =>
		computeDrawingViewBox(this.rawDrawingShapes()),
	);

	/** `viewBox` attribute string for the drawing-shapes `<svg>`. */
	readonly svgViewBox = computed<string>(() => {
		const vb = this.viewBox();
		return `0 0 ${vb.width} ${vb.height}`;
	});

	readonly renderedShapes = computed<RenderedShape[]>(() =>
		projectDrawingShapes(
			this.element().id,
			this.revealedShapeList(),
			this.viewBox(),
			this.palette(),
			this.artStyle(),
		),
	);

	/**
	 * Node id for each drawing shape (index-aligned with `renderedShapes`).
	 * Used to tag `<g>` elements with `data-smartart-node-id` so the 3D
	 * renderer's hit-test overlay can resolve a click to a node.
	 *
	 * Aligned with the REVEALED subset `renderedShapes` projects: during a staged
	 * `p:bldDgm` build that differs from the full list, and indexing the full
	 * list's ids by rendered position stamped the first node's id onto whichever
	 * shape the authored reveal showed first (Gamma carried Alpha's id).
	 */
	readonly drawingShapeNodeIds = computed<(string | undefined)[]>(() =>
		resolveRevealedDrawingShapeNodeIds(
			this.rawDrawingShapes(),
			this.revealedShapeList(),
			this.nodes(),
		),
	);

	// ── Shared SVG-fallback engine (no drawing shapes) ──────────────────────

	readonly layout = computed<SmartArtLayoutResult>(() => {
		const el = this.element();
		const data = this.smartArtData();
		return computeSmartArtElementLayout(
			data ?? {},
			this.revealedNodes(),
			{ width: Math.max(el.width, 1), height: Math.max(el.height, 1) },
			this.palette(),
			this.artStyle(),
			el.id,
		);
	});

	readonly hasLayout = computed(() => this.layout().nodes.length > 0);

	// ── Fallback-layout label / connector paint (shared decisions) ──────────
	//
	// `RenderedNode` / `RenderedConnector` carry OPTIONAL paint and placement
	// fields (per-node font colour / weight / style, off-centre label anchors,
	// per-connector stroke / width / opacity / dash). This template used to
	// hardcode `fill="white"` and park circle labels on `cx`/`cy`, so target
	// leader captions, gear legend rows and timeline captions all sat on the
	// node centre. Both descriptors below are resolved once per layout by the
	// shared decision functions; the template binds them and computes nothing.

	/** Label descriptors, index-aligned with `layout().nodes`. */
	readonly layoutLabels = computed<SmartArtNodeLabel[]>(() => layoutNodeLabels(this.layout()));

	/** Connector paint, index-aligned with `layout().connectors`. */
	readonly layoutConnectors = computed<SmartArtConnectorPaint[]>(() =>
		layoutConnectorPaints(this.layout()),
	);

	// ── Accessibility view-model (shared) ───────────────────────────────────

	/**
	 * Screen-reader metadata for the whole diagram, derived by the shared
	 * `buildSmartArtA11y`. The container SVG gets `role="img"` + this `label`;
	 * each node gets a per-node `aria-label` + `<title>` resolved by node id.
	 */
	readonly a11y = computed<SmartArtA11y | undefined>(() => {
		const data = this.smartArtData();
		return data ? buildSmartArtA11y(data) : undefined;
	});

	/** Map of node id -> accessibility label (for per-node `<title>` lookup). */
	private readonly a11yLabelById = computed<Map<string, string>>(() => {
		const map = new Map<string, string>();
		for (const node of this.a11y()?.nodes ?? []) {
			map.set(node.id, node.label);
		}
		return map;
	});

	/**
	 * Source node ids in fallback render order, index-aligned with
	 * `layout().nodes`. The layout engine walks the node tree depth-first, so
	 * flattening it is the mapping every binding uses.
	 *
	 * This component used to parse the id back out of the rendered node's `key`
	 * instead, which broke on any family whose key carries an extra segment: the
	 * gear legend's `<id>-gear-extra-<nodeId>-<i>` resolved to `extra-<nodeId>`,
	 * so its `data-smartart-node-id` did not match any model node and an inline
	 * edit on a legend row committed nowhere.
	 */
	readonly layoutNodeIds = computed<(string | undefined)[]>(() =>
		flattenNodes(this.revealedNodes()).map((node) => node.id),
	);

	/**
	 * Data-model node id for the rendered node at `index` (or `null`). Exposed
	 * as a method so the template can use it: Angular AOT templates can only
	 * call component members, not imported functions.
	 */
	nodeIdAt(index: number): string | null {
		return this.layoutNodeIds()[index] ?? null;
	}

	/** Resolve the accessibility label for the rendered node at `index`. */
	nodeAriaLabel(index: number): string | null {
		const nodeId = this.nodeIdAt(index);
		if (nodeId === null) {
			return null;
		}
		return this.a11yLabelById().get(nodeId) ?? null;
	}

	/** Cached drawings use the revealed shape mapping, not fallback node order. */
	drawingNodeAriaLabel(index: number): string | null {
		const nodeId = this.drawingShapeNodeIds()[index];
		return nodeId ? (this.a11yLabelById().get(nodeId) ?? null) : null;
	}

	/**
	 * Polite live-region message announcing the most recent node-text commit.
	 * Empty between commits so assistive tech only speaks on change.
	 */
	readonly liveMessage = signal<string>('');

	protected readonly hoveredNodeId = signal<string | null>(null);
	protected readonly hoveredNodeRect = signal<InlineEditRect | null>(null);

	/** Narrowing helpers bound as class properties for template type-checking. */
	protected readonly asCircle = narrowToCircle;
	protected readonly asPolygon = narrowToPolygon;
	protected readonly asRect = narrowToRect;

	// ── Inline node-text editing ───────────────────────────────────────────

	onDrawingNodeDblClick(event: Event, index: number): void {
		this.enterDrawingEdit(event, index);
	}

	onDrawingNodeKeydown(event: KeyboardEvent, index: number): void {
		if ((event.key === 'Enter' || event.key === 'F2') && this.enterDrawingEdit(event, index)) {
			event.preventDefault();
		}
	}

	private enterDrawingEdit(event: Event, index: number): boolean {
		const nodeId = this.drawingShapeNodeIds()[index];
		const data = this.smartArtData();
		const group = event.currentTarget;
		const container = this.smartartContainer()?.nativeElement as HTMLElement | undefined;
		if (
			!this.canEditNodes() ||
			!nodeId ||
			!data ||
			!container ||
			!(group instanceof SVGGraphicsElement)
		) {
			return false;
		}
		// SVG-local boxes avoid applying the stage's zoom/rotation a second time.
		const textBox = group.querySelector('text')?.getBBox();
		const box = textBox && textBox.width > 0 && textBox.height > 0 ? textBox : group.getBBox();
		const seed = beginDrawingNodeEdit(
			nodeId,
			findSmartArtNodeText(data, nodeId),
			box,
			this.viewBox(),
			{ width: container.clientWidth, height: container.clientHeight },
		);
		if (!seed) {
			return false;
		}
		event.stopPropagation();
		this.editSettled = false;
		this.editState.set(seed);
		return true;
	}

	/** Double-click a node enters inline edit mode (when editable). */
	onNodeDblClick(event: Event, node: RenderedNode, index: number): void {
		if (!this.canEditNodes()) {
			return;
		}
		event.stopPropagation();
		this.enterEdit(node, index);
	}

	/** Enter / F2 on a focused node enters inline edit mode (when editable). */
	onNodeKeydown(event: KeyboardEvent, node: RenderedNode, index: number): void {
		if (!this.canEditNodes() || (event.key !== 'Enter' && event.key !== 'F2')) {
			return;
		}
		event.preventDefault();
		event.stopPropagation();
		this.enterEdit(node, index);
	}

	/** Commit the current edit (called on blur). */
	commitEdit(event: Event): void {
		if (this.editSettled) {
			this.editSettled = false;
			return;
		}
		const edit = this.editState();
		if (!edit) {
			return;
		}
		const value = (event.target as HTMLTextAreaElement).value;
		this.editState.set(null);
		this.applyCommit(edit.nodeId, value);
	}

	/** Enter commits (Shift+Enter inserts a newline); Escape cancels. */
	onEditorKeydown(event: KeyboardEvent): void {
		event.stopPropagation();
		if (event.key === 'Enter' && !event.shiftKey) {
			event.preventDefault();
			// Commit via blur so the single commit path runs once.
			(event.target as HTMLTextAreaElement).blur();
		} else if (event.key === 'Escape') {
			event.preventDefault();
			// Mark as settled so the DOM-removal blur does not commit the cancelled edit.
			this.editSettled = true;
			this.editState.set(null);
		}
	}

	/** Resolve the node id + geometry and open the editor seeded with full text. */
	private enterEdit(node: RenderedNode, index: number): void {
		this.editSettled = false;
		const nodeId = this.nodeIdAt(index);
		const seed = beginNodeEdit(node, this.element().id, this.rawNodeText(node, index), nodeId);
		if (seed) {
			this.editState.set(seed);
		}
	}

	/** The node's full (untruncated) data-model text, falling back to rendered text. */
	private rawNodeText(node: RenderedNode, index: number): string {
		const nodeId = this.nodeIdAt(index);
		if (nodeId === null) {
			return node.text;
		}
		const match = flattenNodes(this.nodes()).find((n) => n.id === nodeId);
		return match ? match.text : node.text;
	}

	/** Commit edited text through the shared editor state (one history entry). */
	private applyCommit(nodeId: string, text: string): void {
		const data = this.smartArtData();
		const editor = this.editor;
		if (!data || !editor) {
			return;
		}
		const next = commitNodeText(data, nodeId, text);
		if (next === data) {
			return;
		}
		const slideIndex = findOwningSlideIndex(
			editor.slides(),
			this.element().id,
			this.slideContext?.slideId() ?? null,
		);
		if (slideIndex < 0) {
			return;
		}
		editor.updateElement(slideIndex, this.element().id, {
			smartArtData: this.reflow(next),
		} as Partial<PptxElement>);
		// Announce the commit to assistive technology via the polite live region.
		this.liveMessage.set(
			text.trim().length > 0
				? this.translate.instant('pptx.smartart.nodeUpdated', { text: text.trim() })
				: this.translate.instant('pptx.smartart.nodeCleared'),
		);
	}

	// ── Style bar & hover tracking ────────────────────────────────────────

	/** Approximate rendered size of the style bar (6 swatches + padding/border). */
	private static readonly STYLE_BAR_WIDTH = 168;
	private static readonly STYLE_BAR_HEIGHT = 40;

	/** Grace period (ms) before clearing hover state once the pointer leaves the
	 * node, so it can cross the small visual gap to the style bar. */
	private static readonly HIDE_GRACE_MS = 150;

	protected readonly styleBarStyle = computed<Record<string, string> | null>(() => {
		const rect = this.hoveredNodeRect();
		const cnt = this.smartartContainer()?.nativeElement as HTMLElement | undefined;
		if (!rect || !cnt) {
			return null;
		}
		const maxLeft = Math.max(0, cnt.clientWidth - SmartArtRendererComponent.STYLE_BAR_WIDTH);
		const maxTop = Math.max(0, cnt.clientHeight - SmartArtRendererComponent.STYLE_BAR_HEIGHT);
		return {
			position: 'absolute',
			left: `${Math.min(maxLeft, Math.max(0, rect.left + rect.width - SmartArtRendererComponent.STYLE_BAR_WIDTH))}px`,
			top: `${Math.min(maxTop, Math.max(0, rect.top - 22))}px`,
			'z-index': '25',
		};
	});

	protected onMouseMove(event: MouseEvent): void {
		if (!this.canEditNodes()) {
			return;
		}
		const nodeEl = this.findNodeEl(event.target as EventTarget);
		const cnt = this.smartartContainer()?.nativeElement as HTMLElement | undefined;
		if (nodeEl && cnt) {
			this.cancelPendingHide();
			const id = nodeEl.getAttribute('data-smartart-node-id');
			this.hoveredNodeId.set(id);
			this.hoveredNodeRect.set(id ? measureSvgViewportRect(nodeEl) : null);
			return;
		}
		// Pointer may be over the style-bar popover anchored to the currently
		// hovered node (not the node itself) - keep the hover state so the
		// popover doesn't unmount out from under the pointer.
		const styleBarEl = this.styleBar()?.nativeElement as HTMLElement | undefined;
		if (styleBarEl && event.target instanceof Node && styleBarEl.contains(event.target)) {
			this.cancelPendingHide();
			return;
		}
		this.cancelPendingHide();
		this.hideTimeout = setTimeout(() => {
			this.hoveredNodeId.set(null);
			this.hoveredNodeRect.set(null);
			this.hideTimeout = null;
		}, SmartArtRendererComponent.HIDE_GRACE_MS);
	}

	protected onMouseLeave(): void {
		this.cancelPendingHide();
		this.hoveredNodeId.set(null);
		this.hoveredNodeRect.set(null);
	}

	private cancelPendingHide(): void {
		if (this.hideTimeout !== null) {
			clearTimeout(this.hideTimeout);
			this.hideTimeout = null;
		}
	}

	private findNodeEl(target: EventTarget | null): Element | null {
		let el = target instanceof Element ? target : null;
		while (el) {
			if (el.hasAttribute('data-smartart-node-id')) {
				return el;
			}
			el = el.parentElement;
		}
		return null;
	}

	protected handleChangeNodeStyle(nodeId: string, fill: string): void {
		const data = this.smartArtData();
		if (!data || !this.editor) {
			return;
		}
		const next = setSmartArtNodeStyle(data, nodeId, { fillColor: fill });
		if (next === data) {
			return;
		}
		const slideIndex = findOwningSlideIndex(
			this.editor.slides(),
			this.element().id,
			this.slideContext?.slideId() ?? null,
		);
		if (slideIndex < 0) {
			return;
		}
		this.editor.updateElement(slideIndex, this.element().id, {
			smartArtData: this.reflow(next),
		} as Partial<PptxElement>);
	}

	/**
	 * Reflow `drawingShapes` back from the shared layout engine when an edit op
	 * cleared them (every text/style edit does) -- otherwise the renderer falls
	 * back to the generic SVG layout for every node, not just the edited one.
	 */
	private reflow(data: PptxSmartArtData): PptxSmartArtData {
		const el = this.element();
		return rebuildDrawingShapesIfCleared(
			data,
			data.layout,
			resolvePalette(data),
			data.style ?? 'flat',
			el.id,
			{ width: el.width, height: el.height },
		);
	}

	// ── Empty / no-data state ──────────────────────────────────────────────

	readonly isEmpty = computed(() => this.nodes().length === 0 && !this.hasDrawingShapes());
}

// Re-export helper types used in the template so template type-checking works.
export type { DrawingViewBox, RenderedShape };
