// viewers/pptx/packages/vue/src/viewer/components/StatusBar.vue
<script setup lang="ts">
/**
 * StatusBar - thin adapter around the shared `pptx-ui-status-bar` element.
 *
 * The slide counter, save indicator, notes toggle, view-mode buttons and zoom
 * cluster live in the shared view. This component maps viewer state onto the
 * element's controlled state and re-emits its typed intents.
 */
import { resolveStatusBarSave, statusBarViewMode } from 'ooxml-ui/pptx';
import type { StatusBarRequestEvent, ToolbarActionId } from 'ooxml-ui/pptx';
import { computed, useSlots } from 'vue';
import { useI18n } from 'vue-i18n';

import type { AutosaveStatus } from '../composables/useAutosave';
import { useToolbarVisibility } from '../composables/useToolbarVisibility';

const { t } = useI18n();

const props = defineProps<{
	slideCount: number;
	activeSlideIndex: number;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	/** Epoch ms of the last successful autosave, for the "Saved <time>" label. */
	lastSavedAt?: number | null;
	/** Current zoom scale (1 = 100%). */
	scale?: number;
	/** Whether the notes panel is expanded. */
	isNotesExpanded?: boolean;
	/** Current viewer mode. */
	mode?: string;
	/** Whether the Notes toggle is shown (host has a notes panel). */
	showNotes?: boolean;
	/** Toolbar buttons the host has asked to hide (zoom, notes, fullscreen). */
	hiddenActions?: ToolbarActionId[];
}>();

const slots = useSlots();
const { isHidden } = useToolbarVisibility(() => props.hiddenActions);

const emit = defineEmits<{
	'zoom-in': [];
	'zoom-out': [];
	'zoom-to-fit': [];
	'toggle-notes': [];
	'set-mode': [mode: 'edit' | 'present'];
	'toggle-slide-sorter': [];
}>();

const state = computed(() => {
	const save = resolveStatusBarSave(
		t,
		props.autosaveStatus
			? { state: props.autosaveStatus, timestamp: props.lastSavedAt ?? undefined }
			: undefined,
		props.isDirty,
	);
	return {
		slideCount: props.slideCount,
		activeSlideIndex: props.activeSlideIndex,
		saveText: save.text,
		saveKind: save.kind,
		zoomPercent:
			props.scale !== undefined && !isHidden('zoom') ? (props.scale ?? 1) * 100 : undefined,
		showNotes: props.showNotes === true && !isHidden('notes'),
		notesExpanded: props.isNotesExpanded === true,
		showSlideShow: !isHidden('fullscreen'),
		viewMode: statusBarViewMode(props.mode),
		translate: t,
	};
});

function request(event: Event): void {
	switch ((event as StatusBarRequestEvent).detail.id) {
		case 'notes':
			emit('toggle-notes');
			break;
		case 'normal':
			emit('set-mode', 'edit');
			break;
		case 'sorter':
			emit('toggle-slide-sorter');
			break;
		case 'slideShow':
			emit('set-mode', 'present');
			break;
		case 'zoomOut':
			emit('zoom-out');
			break;
		case 'zoomFit':
			emit('zoom-to-fit');
			break;
		case 'zoomIn':
			emit('zoom-in');
	}
}
</script>

<template>
	<pptx-ui-status-bar :state.prop="state" @status-request="request">
		<div v-if="slots.collaboration" slot="collaboration" style="display: contents">
			<slot name="collaboration" />
		</div>
	</pptx-ui-status-bar>
</template>

// viewers/pptx/packages/angular/src/viewer/status-bar.component.ts
/**
 * status-bar.component.ts: bottom status bar for the Angular editor chrome.
 *
 * A thin adapter around the shared `pptx-ui-status-bar` element: the slide
 * counter, save indicator, notes toggle, view-mode buttons and zoom cluster are
 * rendered by the shared view. This component maps viewer state onto the
 * element's controlled state and re-emits its typed intents as outputs the
 * {@link PowerPointViewerComponent} already has handlers for.
 *
 * A host may project a connection indicator with `[pptxCollabStatus]`; the
 * projected element must also carry `slot="collaboration"`.
 */
import {
	ChangeDetectionStrategy,
	Component,
	CUSTOM_ELEMENTS_SCHEMA,
	inject,
	input,
	output,
} from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { TranslateService } from '@ngx-translate/core';
import { map, merge, startWith } from 'rxjs';

import { isActionHidden, resolveStatusBarSave } from 'ooxml-ui/pptx';
import type {
	StatusBarControlId,
	StatusBarRequestEvent,
	StatusBarViewState,
	ToolbarActionId,
} from 'ooxml-ui/pptx';
import type { AutosaveStatus } from './autosave.service';

@Component({
	selector: 'pptx-status-bar',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	host: { class: 'contents' },
	template: `
		<pptx-ui-status-bar [state]="view()" (status-request)="request($event)">
			<ng-content select="[pptxCollabStatus]"></ng-content>
		</pptx-ui-status-bar>
	`,
})
export class StatusBarComponent {
	readonly slideIndex = input<number>(0);
	readonly slideCount = input<number>(0);
	readonly canEdit = input<boolean>(false);
	readonly dirty = input<boolean>(false);
	/** Current autosave engine status; drives the save-state text + colour. */
	readonly autosaveStatus = input<AutosaveStatus | undefined>(undefined);
	readonly notesOpen = input<boolean>(false);
	readonly zoomPercent = input<number>(100);
	/** True when the slide-sorter overlay is open (active-state styling). */
	readonly sorterActive = input<boolean>(false);
	/** True when the presentation overlay is open (active-state styling). */
	readonly presenting = input<boolean>(false);
	/** Toolbar buttons the host wants hidden (notes/fullscreen/zoom independently). */
	readonly hiddenActions = input<ToolbarActionId[]>([]);

	readonly toggleNotes = output<void>();
	readonly normalView = output<void>();
	readonly openSorter = output<void>();
	readonly slideShow = output<void>();
	readonly zoomIn = output<void>();
	readonly zoomOut = output<void>();
	readonly zoomReset = output<void>();

	private readonly translate = inject(TranslateService);
	/** Changes on language/dictionary updates so OnPush re-translates the view. */
	private readonly translations = toSignal(
		merge(this.translate.onLangChange, this.translate.onTranslationChange).pipe(
			map(() => Date.now()),
			startWith(0),
		),
		{ initialValue: 0 },
	);

	private readonly intents: Record<StatusBarControlId, () => void> = {
		notes: () => this.toggleNotes.emit(),
		normal: () => this.normalView.emit(),
		sorter: () => this.openSorter.emit(),
		slideShow: () => this.slideShow.emit(),
		zoomOut: () => this.zoomOut.emit(),
		zoomFit: () => this.zoomReset.emit(),
		zoomIn: () => this.zoomIn.emit(),
	};

	protected view(): StatusBarViewState {
		this.translations();
		const t = (key: string, params?: Record<string, string | number>): string =>
			this.translate.instant(key, params);
		const hidden = (id: ToolbarActionId) => isActionHidden(id, this.hiddenActions());
		const save = resolveStatusBarSave(t, this.autosaveStatus(), this.dirty());
		return {
			slideCount: this.slideCount(),
			activeSlideIndex: this.slideIndex(),
			saveText: save.text,
			saveKind: save.kind,
			zoomPercent: hidden('zoom') ? undefined : this.zoomPercent(),
			showNotes: !hidden('notes'),
			notesExpanded: this.notesOpen(),
			showSlideShow: !hidden('fullscreen'),
			// "Normal" is active when neither the sorter nor the slideshow is showing.
			viewMode: this.presenting() ? 'slideShow' : this.sorterActive() ? 'sorter' : 'normal',
			translate: t,
		};
	}

	protected request(event: Event): void {
		this.intents[(event as StatusBarRequestEvent).detail.id]();
	}
}
