// viewers/pptx/packages/svelte/src/viewer/components/ribbon/slideshow/SubtitleSettingsControl.svelte
<script lang="ts">
	import { subtitleSettingsFromOptions, subtitleSettingsLabels, updateSubtitleSettings } from 'ooxml-ui/pptx';
	import type { SubtitleSettingsChangeEvent } from 'ooxml-ui/pptx';
	import { useTranslator } from '../../../../i18n/context';
	import { useViewerOptions } from '../../../state/viewer-options-context';

	const t = useTranslator();
	const options = useViewerOptions();
	function commit(event: Event): void {
		updateSubtitleSettings(options, (event as SubtitleSettingsChangeEvent).detail);
	}
</script>

<pptx-ui-subtitle-settings data-ribbon-control="slideShow.captions.subtitleSettings"
	settings={subtitleSettingsFromOptions(options.options)} labels={subtitleSettingsLabels(t)}
	languageDisabled={options.isLocked('accessibility', 'subtitleLanguage')}
	onsubtitle-settings-change={commit}
></pptx-ui-subtitle-settings>

// viewers/pptx/packages/angular/src/viewer/subtitle-settings-control.component.ts
import { ChangeDetectionStrategy, Component, CUSTOM_ELEMENTS_SCHEMA, inject } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

import {
	subtitleSettingsFromOptions,
	subtitleSettingsLabels,
	updateSubtitleSettings,
} from 'ooxml-ui/pptx';
import type { SubtitleSettingsChangeEvent } from 'ooxml-ui/pptx';
import { ViewerOptionsService } from './viewer-options.service';

@Component({
	selector: 'pptx-subtitle-settings-control',
	standalone: true,
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: { class: 'contents' },
	template: `<pptx-ui-subtitle-settings
		data-ribbon-control="slideShow.captions.subtitleSettings"
		[settings]="settings()"
		[labels]="labels()"
		[languageDisabled]="options.store.isLocked('accessibility', 'subtitleLanguage')"
		(subtitle-settings-change)="commit($event)"
	></pptx-ui-subtitle-settings>`,
})
export class SubtitleSettingsControlComponent {
	protected readonly options =
		inject(ViewerOptionsService, { optional: true }) ?? new ViewerOptionsService();
	private readonly translate = inject(TranslateService);
	protected settings() {
		return subtitleSettingsFromOptions(this.options.options());
	}
	protected labels() {
		return subtitleSettingsLabels((key) => this.translate.instant(key));
	}
	protected commit(event: Event): void {
		updateSubtitleSettings(this.options.store, (event as SubtitleSettingsChangeEvent).detail);
	}
}
