// viewers/pptx/packages/svelte/src/viewer/components/inspector/TableStyleEditorFields.svelte
<script lang="ts">
	/**
	 * Field editors for whichever part `TableStyleEditor.svelte` currently has
	 * selected. Mirrors React's `TableStyleEditorFields.tsx` / Vue's
	 * `TableStyleEditorFields.vue`.
	 */
	import type { TableStyleEditorDescriptor, TableStyleEditorFieldEdit } from 'ooxml-ui/pptx';
	import {
		TABLE_STYLE_BORDER_SIDE_LABEL_KEYS,
		TABLE_STYLE_BORDER_SIDES,
		TABLE_STYLE_DASH_PRESETS,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';
	import ThemeColorSwatchGrid from './ThemeColorSwatchGrid.svelte';

	const {
		descriptor,
		themeColorMap,
		canEdit,
		onedit,
	}: {
		descriptor: TableStyleEditorDescriptor;
		themeColorMap: Record<string, string> | undefined;
		canEdit: boolean;
		onedit: (edit: TableStyleEditorFieldEdit) => void;
	} = $props();

	const t = useTranslator();
</script>

<div class="fields">
	<div class="group">
		<span class="hdg">{t('pptx.tableStyleEditor.fillSection')}</span>
		<div class="row">
			<input type="color" disabled={!canEdit} value={descriptor.fill.color.hex} onchange={(e) => onedit({ kind: 'fillColor', hex: e.currentTarget.value, ref: undefined })} />
			<label class="check"><pptx-ui-checkbox disabled={!canEdit} checked={descriptor.fill.noFill} onchange={(e) => onedit({ kind: 'fillNone', noFill: e.currentTarget.checked })} ></pptx-ui-checkbox>{t('pptx.tableStyleEditor.noFill')}</label>
		</div>
		<ThemeColorSwatchGrid {themeColorMap} disabled={!canEdit} selectedRef={descriptor.fill.color.ref} selectedHex={descriptor.fill.color.hex} onpick={(c) => onedit({ kind: 'fillColor', hex: c.hex, ref: c.ref })} />
	</div>

	{#if descriptor.hasTextAndBorders}
		<div class="group">
			<span class="hdg">{t('pptx.tableStyleEditor.textSection')}</span>
			<div class="row">
				<button type="button" disabled={!canEdit} class:active={descriptor.text.bold} onclick={() => onedit({ kind: 'textBold', value: !descriptor.text.bold })}>{t('pptx.format.bold')}</button>
				<button type="button" disabled={!canEdit} class:active={descriptor.text.italic} onclick={() => onedit({ kind: 'textItalic', value: !descriptor.text.italic })}>{t('pptx.format.italic')}</button>
				<button type="button" disabled={!canEdit} class:active={descriptor.text.underline} onclick={() => onedit({ kind: 'textUnderline', value: !descriptor.text.underline })}>{t('pptx.format.underline')}</button>
			</div>
			<label class="row">{t('pptx.tableStyleEditor.textColor')}<input type="color" disabled={!canEdit} value={descriptor.text.color.hex} onchange={(e) => onedit({ kind: 'textColor', hex: e.currentTarget.value, ref: undefined })} /></label>
			<ThemeColorSwatchGrid {themeColorMap} disabled={!canEdit} selectedRef={descriptor.text.color.ref} selectedHex={descriptor.text.color.hex} onpick={(c) => onedit({ kind: 'textColor', hex: c.hex, ref: c.ref })} />
		</div>

		<div class="group">
			<span class="hdg">{t('pptx.tableStyleEditor.bordersSection')}</span>
			{#each TABLE_STYLE_BORDER_SIDES as side (side)}
				{@const border = descriptor.borders[side]}
				<div class="border-row">
					<span class="side-lbl">{t(TABLE_STYLE_BORDER_SIDE_LABEL_KEYS[side])}</span>
					<input type="color" disabled={!canEdit} value={border.color.hex} onchange={(e) => onedit({ kind: 'borderColor', side, hex: e.currentTarget.value, ref: undefined })} />
					<input type="number" min="0" max="20" disabled={!canEdit} value={border.width} onchange={(e) => onedit({ kind: 'borderWidth', side, width: Number(e.currentTarget.value) })} />
					<pptx-ui-select disabled={!canEdit} value={border.dash} onchange={(e) => onedit({ kind: 'borderDash', side, dash: e.currentTarget.value })}>
						{#each TABLE_STYLE_DASH_PRESETS as dash (dash)}<option value={dash}>{dash}</option>{/each}
					</pptx-ui-select>
					<label class="check"><pptx-ui-checkbox disabled={!canEdit} checked={border.noFill} onchange={(e) => onedit({ kind: 'borderNone', side, noFill: e.currentTarget.checked })} ></pptx-ui-checkbox>{t('pptx.tableStyleEditor.noBorder')}</label>
				</div>
			{/each}
		</div>
	{/if}
</div>

<style>
	.fields { display: flex; flex-direction: column; gap: 8px; }
	.group { display: flex; flex-direction: column; gap: 4px; }
	.hdg { font-size: 10px; text-transform: uppercase; letter-spacing: 0.03em; color: var(--pptx-muted-foreground); }
	.row { display: flex; align-items: center; gap: 6px; font-size: 11px; }
	.check { display: flex; align-items: center; gap: 4px; font-size: 11px; }
	.border-row { display: flex; align-items: center; gap: 5px; font-size: 11px; }
	.side-lbl { width: 110px; flex-shrink: 0; color: var(--pptx-muted-foreground); }
	input[type='color'] { height: 24px; width: 32px; border: 1px solid var(--pptx-border); border-radius: 4px; background: transparent; cursor: pointer; padding: 0; }
	input[type='number'], select { height: 24px; border: 1px solid var(--pptx-border); border-radius: 4px; background: var(--pptx-background); color: inherit; }
	input[type='number'] { width: 48px; }
	button { border: 1px solid var(--pptx-border); border-radius: 4px; padding: 3px 6px; background: var(--pptx-muted); color: inherit; }
	button.active { background: var(--pptx-primary, #c43b32); color: #fff; }
	/* Touch target: matches MIN_TOUCH_TARGET_PX (44) from pptx-viewer-shared's
	   render/responsive module. Bold/Italic/Underline are single-letter
	   labels, so both dimensions need the floor, not just height. */
	@media (max-width: 767px) {
		.row button, select, input[type='number'] { min-height: 44px; }
		.row button { min-width: 44px; }
	}
</style>

// viewers/pptx/packages/angular/src/viewer/table-style-editor-fields.component.ts
/**
 * table-style-editor-fields.component.ts: field editors (fill/text/borders)
 * for whichever part `TableStyleEditorComponent` currently has selected.
 * Split out from that shell purely to keep both files under the repo's
 * 300-LOC budget. Mirrors React's `TableStyleEditorFields.tsx` and Vue's
 * `TableStyleEditorFields.vue`.
 *
 * @module viewer/table-style-editor-fields
 */
import {
	ChangeDetectionStrategy,
	Component,
	input,
	output,
	CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import type { TableStyleEditorDescriptor, TableStyleEditorFieldEdit } from 'ooxml-ui/pptx';
import {
	TABLE_STYLE_BORDER_SIDE_LABEL_KEYS,
	TABLE_STYLE_BORDER_SIDES,
	TABLE_STYLE_DASH_PRESETS,
} from 'ooxml-ui/pptx';
import { isSelectControl, isCheckboxControl } from './control-event-targets';
import { ThemeColorSwatchGridComponent } from './theme-color-swatch-grid.component';

function inputValue(event: Event): string {
	const t = event.target;
	return t instanceof HTMLInputElement || isSelectControl(t) ? t.value : '';
}

function checkedValue(event: Event): boolean {
	const t = event.target;
	return isCheckboxControl(t) ? t.checked : false;
}

@Component({
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	selector: 'pptx-table-style-editor-fields',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe, ThemeColorSwatchGridComponent],
	template: `
		@if (descriptor(); as d) {
			<div class="pptx-tse-fields">
				<div class="pptx-tse-fields__group">
					<div class="pptx-tse-fields__hdg">
						{{ 'pptx.tableStyleEditor.fillSection' | translate }}
					</div>
					<div class="pptx-tse-fields__row">
						<input
							type="color"
							class="pptx-tse-fields__color"
							[disabled]="!canEdit()"
							[value]="d.fill.color.hex"
							(change)="edit.emit({ kind: 'fillColor', hex: inputValue($event), ref: undefined })"
						/>
						<label class="pptx-tse-fields__check">
							<pptx-ui-checkbox
								[disabled]="!canEdit()"
								[checked]="d.fill.noFill"
								(change)="edit.emit({ kind: 'fillNone', noFill: checkedValue($event) })"
							></pptx-ui-checkbox>
							{{ 'pptx.tableStyleEditor.noFill' | translate }}
						</label>
					</div>
					<pptx-theme-color-swatch-grid
						[disabled]="!canEdit()"
						[selectedRef]="d.fill.color.ref"
						[selectedHex]="d.fill.color.hex"
						(pick)="edit.emit({ kind: 'fillColor', hex: $event.hex, ref: $event.ref })"
					/>
				</div>

				@if (d.hasTextAndBorders) {
					<div class="pptx-tse-fields__group">
						<div class="pptx-tse-fields__hdg">
							{{ 'pptx.tableStyleEditor.textSection' | translate }}
						</div>
						<div class="pptx-tse-fields__row">
							<button
								type="button"
								class="pptx-tse-fields__flag-btn"
								[disabled]="!canEdit()"
								[class.pptx-tse-fields__active]="d.text.bold"
								(click)="edit.emit({ kind: 'textBold', value: !d.text.bold })"
							>
								{{ 'pptx.format.bold' | translate }}
							</button>
							<button
								type="button"
								class="pptx-tse-fields__flag-btn"
								[disabled]="!canEdit()"
								[class.pptx-tse-fields__active]="d.text.italic"
								(click)="edit.emit({ kind: 'textItalic', value: !d.text.italic })"
							>
								{{ 'pptx.format.italic' | translate }}
							</button>
							<button
								type="button"
								class="pptx-tse-fields__flag-btn"
								[disabled]="!canEdit()"
								[class.pptx-tse-fields__active]="d.text.underline"
								(click)="edit.emit({ kind: 'textUnderline', value: !d.text.underline })"
							>
								{{ 'pptx.format.underline' | translate }}
							</button>
						</div>
						<label class="pptx-tse-fields__row">
							<span>{{ 'pptx.tableStyleEditor.textColor' | translate }}</span>
							<input
								type="color"
								class="pptx-tse-fields__color"
								[disabled]="!canEdit()"
								[value]="d.text.color.hex"
								(change)="edit.emit({ kind: 'textColor', hex: inputValue($event), ref: undefined })"
							/>
						</label>
						<pptx-theme-color-swatch-grid
							[disabled]="!canEdit()"
							[selectedRef]="d.text.color.ref"
							[selectedHex]="d.text.color.hex"
							(pick)="edit.emit({ kind: 'textColor', hex: $event.hex, ref: $event.ref })"
						/>
					</div>

					<div class="pptx-tse-fields__group">
						<div class="pptx-tse-fields__hdg">
							{{ 'pptx.tableStyleEditor.bordersSection' | translate }}
						</div>
						@for (side of sides; track side) {
							<div class="pptx-tse-fields__border-row">
								<span class="pptx-tse-fields__side-lbl">{{
									borderSideLabelKeys[side] | translate
								}}</span>
								<input
									type="color"
									class="pptx-tse-fields__color pptx-tse-fields__color--sm"
									[disabled]="!canEdit()"
									[value]="d.borders[side].color.hex"
									(change)="
										edit.emit({
											kind: 'borderColor',
											side,
											hex: inputValue($event),
											ref: undefined,
										})
									"
								/>
								<input
									type="number"
									min="0"
									max="20"
									class="pptx-tse-fields__num"
									[disabled]="!canEdit()"
									[value]="d.borders[side].width"
									(change)="edit.emit({ kind: 'borderWidth', side, width: inputNumber($event) })"
								/>
								<pptx-ui-select
									class="pptx-tse-fields__dash"
									[disabled]="!canEdit()"
									[value]="d.borders[side].dash"
									(change)="edit.emit({ kind: 'borderDash', side, dash: inputValue($event) })"
								>
									@for (dash of dashPresets; track dash) {
										<option [value]="dash" [selected]="dash === d.borders[side].dash">
											{{ dash }}
										</option>
									}
								</pptx-ui-select>
								<label class="pptx-tse-fields__check">
									<pptx-ui-checkbox
										[disabled]="!canEdit()"
										[checked]="d.borders[side].noFill"
										(change)="edit.emit({ kind: 'borderNone', side, noFill: checkedValue($event) })"
									></pptx-ui-checkbox>
									{{ 'pptx.tableStyleEditor.noBorder' | translate }}
								</label>
							</div>
						}
					</div>
				}
			</div>
		}
	`,
	styles: `
		.pptx-tse-fields {
			display: flex;
			flex-direction: column;
			gap: 0.5rem;
		}
		.pptx-tse-fields__group {
			display: flex;
			flex-direction: column;
			gap: 0.25rem;
		}
		.pptx-tse-fields__hdg {
			font-size: 10px;
			text-transform: uppercase;
			letter-spacing: 0.03em;
			color: var(--pptx-inspector-muted, #888);
		}
		.pptx-tse-fields__row {
			display: flex;
			align-items: center;
			gap: 0.5rem;
			font-size: 11px;
		}
		.pptx-tse-fields__check {
			display: flex;
			align-items: center;
			gap: 0.25rem;
			font-size: 11px;
		}
		.pptx-tse-fields__color {
			height: 1.5rem;
			width: 2rem;
			border: 1px solid var(--pptx-inspector-border, #444);
			border-radius: 3px;
			background: transparent;
			cursor: pointer;
		}
		.pptx-tse-fields__color--sm {
			width: 1.75rem;
		}
		.pptx-tse-fields__border-row {
			display: flex;
			align-items: center;
			gap: 0.4rem;
			font-size: 11px;
		}
		.pptx-tse-fields__side-lbl {
			width: 7rem;
			flex-shrink: 0;
			color: var(--pptx-inspector-muted, #888);
		}
		.pptx-tse-fields__num {
			width: 3rem;
			border: 1px solid var(--pptx-inspector-border, #444);
			border-radius: 3px;
			background: var(--pptx-inspector-input-bg, #2d2d2d);
			color: inherit;
		}
		.pptx-tse-fields__dash {
			border: 1px solid var(--pptx-inspector-border, #444);
			border-radius: 3px;
			background: var(--pptx-inspector-input-bg, #2d2d2d);
			color: inherit;
		}
		.pptx-tse-fields__active {
			background: var(--pptx-inspector-active, #3a3a3a);
		}

		/*
		 * Touch target: matches MIN_TOUCH_TARGET_PX (44) from
		 * pptx-viewer-shared's render/responsive module. Bold/Italic/Underline
		 * are single-letter labels, so a height-only floor still leaves them
		 * narrow (a WCAG miss on the smaller side); both dimensions need it.
		 */
		@media (max-width: 767px) {
			.pptx-tse-fields__flag-btn {
				min-width: 44px;
				min-height: 44px;
			}
		}
	`,
})
export class TableStyleEditorFieldsComponent {
	readonly descriptor = input.required<TableStyleEditorDescriptor | undefined>();
	readonly canEdit = input<boolean>(true);
	readonly edit = output<TableStyleEditorFieldEdit>();

	protected readonly sides = TABLE_STYLE_BORDER_SIDES;
	protected readonly dashPresets = TABLE_STYLE_DASH_PRESETS;
	protected readonly borderSideLabelKeys = TABLE_STYLE_BORDER_SIDE_LABEL_KEYS;

	protected inputValue(event: Event): string {
		return inputValue(event);
	}

	/** Templates cannot reach the `Number` global, so the coercion lives here. */
	protected inputNumber(event: Event): number {
		return Number(inputValue(event));
	}

	protected checkedValue(event: Event): boolean {
		return checkedValue(event);
	}
}
