// viewers/pptx/packages/vue/src/viewer/components/TableResizeOverlay.vue
<script setup lang="ts">
import {
	columnHandleSegments,
	computeColumnBoundaries,
	computeResizedColumnWidths,
	computeResizedRowHeight,
	computeTableMergeCrossings,
	DEFAULT_ROW_HEIGHT,
	getTableResizeScale,
	isColumnBoundaryMergedAt,
	isRowBoundaryMergedAt,
	rowHandleSegments,
} from 'ooxml-ui/pptx';
import type { PptxTableRow } from 'pptx-viewer-core';
import { computed, nextTick, onBeforeUnmount, ref, watch } from 'vue';

/**
 * TableResizeOverlay: Vue port of React's `utils/table-render-resize.tsx`.
 *
 * Wraps a rendered table (default slot) and, when `editable`, draws draggable
 * column-boundary and row-boundary handles on top. Column boundaries are placed
 * from the proportional widths; row boundaries are measured from the mounted
 * `<tr>` heights. The pure drag math (redistribute two adjacent column
 * proportions, clamp a dragged row height) lives in `pptx-viewer-shared`
 * (`render/table-resize.ts`), so this component only owns the DOM interaction.
 * A boundary stretch inside a merged cell is neither drawn nor hit-tested
 * (`render/table-resize-merge.ts`), so a press there reaches the cell.
 */
const props = defineProps<{
	/** Column widths as proportions summing to ~1. */
	columnWidths: number[];
	/** The table's rows, for the merges that interrupt a boundary. */
	rows?: readonly PptxTableRow[];
	/** When false the overlay renders only the slotted table (no handles). */
	editable: boolean;
}>();

const emit = defineEmits<{
	/** New column widths (proportions summing to 1) after a column drag. */
	resizeColumns: [widths: number[]];
	/** New pixel height for `rowIndex` after a row drag. */
	resizeRow: [rowIndex: number, height: number];
}>();

const containerRef = ref<HTMLDivElement | null>(null);
/** Cumulative bottom-edge pixel positions of the internal row boundaries. */
const rowBounds = ref<number[]>([]);
/** Measured table height, for the column-boundary segments. */
const tableHeight = ref(0);

interface DragState {
	type: 'col' | 'row';
	index: number;
	startPos: number;
	handleEl: HTMLElement;
	initialWidths?: number[];
	initialRowHeight?: number;
}
let drag: DragState | null = null;

/** Cumulative left-edge percentages of the internal column boundaries. */
const colBoundaries = computed<number[]>(() => computeColumnBoundaries(props.columnWidths));

/** Where merged cells interrupt the internal boundaries. */
const crossings = computed(() =>
	computeTableMergeCrossings(props.rows ?? [], props.columnWidths.length),
);

/** Measure row boundaries from the mounted table rows (skip the last edge). */
function measureRows(): void {
	const container = containerRef.value;
	const table = container?.querySelector('table');
	if (!table) {
		return;
	}
	tableHeight.value = table.offsetHeight;
	const trs = table.querySelectorAll('tbody > tr');
	const bounds: number[] = [];
	let cumulative = 0;
	trs.forEach((tr, i) => {
		cumulative += (tr as HTMLElement).offsetHeight;
		if (i < trs.length - 1) {
			bounds.push(cumulative);
		}
	});
	const prev = rowBounds.value;
	const same = prev.length === bounds.length && prev.every((v, i) => v === bounds[i]);
	if (!same) {
		rowBounds.value = bounds;
	}
}

// Re-measure whenever the widths change (a proxy for content/layout changes).
watch(
	() => [props.columnWidths, props.rows, props.editable] as const,
	() => {
		void nextTick(measureRows);
	},
	{ immediate: true, deep: true },
);

function onMouseMove(event: MouseEvent): void {
	if (!drag) {
		return;
	}
	event.preventDefault();
	const delta = drag.type === 'col' ? event.clientX - drag.startPos : event.clientY - drag.startPos;
	drag.handleEl.style.transform =
		drag.type === 'col' ? `translateX(${delta}px)` : `translateY(${delta}px)`;
}

function onMouseUp(event: MouseEvent): void {
	const container = containerRef.value;
	if (!drag || !container) {
		return;
	}
	const rect = container.getBoundingClientRect();
	if (event.clientX !== drag.startPos && drag.type === 'col' && drag.initialWidths) {
		const deltaProp = (event.clientX - drag.startPos) / rect.width;
		emit('resizeColumns', computeResizedColumnWidths(drag.initialWidths, drag.index, deltaProp));
	} else if (event.clientY !== drag.startPos && drag.type === 'row') {
		const deltaY = event.clientY - drag.startPos;
		emit(
			'resizeRow',
			drag.index,
			computeResizedRowHeight(drag.initialRowHeight ?? DEFAULT_ROW_HEIGHT, deltaY),
		);
	}
	drag.handleEl.style.transform = '';
	document.body.style.cursor = '';
	document.body.style.userSelect = '';
	window.removeEventListener('mousemove', onMouseMove);
	window.removeEventListener('mouseup', onMouseUp);
	drag = null;
}

/** Proximity-based drag initiation: detect clicks near column/row boundaries. */
const HANDLE_ZONE = 3; // px tolerance for boundary hit detection
function onContainerMouseDown(event: MouseEvent): void {
	if (!props.editable) {
		return;
	}
	const container = containerRef.value;
	if (!container) {
		return;
	}
	const rect = container.getBoundingClientRect();
	const localX = event.clientX - rect.left;
	const localY = event.clientY - rect.top;
	const scaleY = getTableResizeScale(rect.height, container.offsetHeight);

	// Check column boundaries
	for (let i = 0; i < colBoundaries.value.length; i++) {
		const boundaryX = (colBoundaries.value[i] / 100) * rect.width;
		if (
			Math.abs(localX - boundaryX) <= HANDLE_ZONE &&
			!isColumnBoundaryMergedAt(crossings.value, i, rowBounds.value, localY / scaleY)
		) {
			event.preventDefault();
			event.stopPropagation();
			document.body.style.cursor = 'col-resize';
			document.body.style.userSelect = 'none';
			drag = {
				type: 'col',
				index: i,
				startPos: event.clientX,
				handleEl: container,
				initialWidths: [...props.columnWidths],
			};
			window.addEventListener('mousemove', onMouseMove);
			window.addEventListener('mouseup', onMouseUp);
			return;
		}
	}

	// Check row boundaries
	for (let i = 0; i < rowBounds.value.length; i++) {
		if (
			Math.abs(localY - rowBounds.value[i] * scaleY) <= HANDLE_ZONE &&
			!isRowBoundaryMergedAt(crossings.value, i, props.columnWidths, localX / (rect.width || 1))
		) {
			event.preventDefault();
			event.stopPropagation();
			const table = container.querySelector('table');
			const tr = table?.querySelectorAll('tbody > tr')[i] as HTMLElement | undefined;
			document.body.style.cursor = 'row-resize';
			document.body.style.userSelect = 'none';
			drag = {
				type: 'row',
				index: i,
				startPos: event.clientY,
				handleEl: container,
				initialRowHeight: tr?.offsetHeight ?? DEFAULT_ROW_HEIGHT,
			};
			window.addEventListener('mousemove', onMouseMove);
			window.addEventListener('mouseup', onMouseUp);
			return;
		}
	}
}

onBeforeUnmount(() => {
	window.removeEventListener('mousemove', onMouseMove);
	window.removeEventListener('mouseup', onMouseUp);
});
</script>

<template>
	<div
		ref="containerRef"
		class="pptx-vue-table-resize relative h-full w-full"
		@mousedown="onContainerMouseDown"
	>
		<slot />
		<template v-if="editable">
			<div
				v-for="(leftPct, i) in colBoundaries"
				:key="`col-h-${i}`"
				class="pptx-vue-table-resize__col absolute bottom-0 top-0 z-10 w-[6px]"
				:style="{ left: `calc(${leftPct}% - 3px)` }"
			>
				<div
					v-for="segment in columnHandleSegments(
						crossings.columns[i] ?? [],
						rowBounds,
						tableHeight,
					)"
					:key="segment.top"
					class="pptx-vue-table-resize__segment group absolute left-0 right-0 cursor-col-resize"
					:style="{
						top: `${segment.top}px`,
						height: tableHeight ? `${segment.height}px` : '100%',
					}"
				>
					<div
						class="mx-auto h-full w-px bg-transparent transition-colors group-hover:bg-blue-400/60"
					/>
				</div>
			</div>
			<div
				v-for="(topPx, i) in rowBounds"
				:key="`row-h-${i}`"
				class="pptx-vue-table-resize__row absolute left-0 right-0 z-10 h-[6px]"
				:style="{ top: `${topPx - 3}px` }"
			>
				<div
					v-for="segment in rowHandleSegments(crossings.rows[i] ?? [], columnWidths)"
					:key="segment.leftPct"
					class="pptx-vue-table-resize__segment group absolute bottom-0 top-0 cursor-row-resize"
					:style="{ left: `${segment.leftPct}%`, width: `${segment.widthPct}%` }"
				>
					<div
						class="my-auto h-px w-full bg-transparent transition-colors group-hover:bg-blue-400/60"
					/>
				</div>
			</div>
		</template>
	</div>
</template>

<style scoped>
/*
 * Resize handles must be transparent to pointer events. They sit above the
 * table cells (z-10) purely for visual stacking (hover indicator), but mouse
 * drag initiation is handled by the container's proximity-based mousedown
 * delegation below. This ensures touch taps always pass through to the
 * underlying table cells (enabling double-tap-to-edit on mobile) while
 * keeping the desktop mouse drag-to-resize functional.
 */
.pptx-vue-table-resize__col,
.pptx-vue-table-resize__row,
.pptx-vue-table-resize__segment {
	pointer-events: none;
}
</style>

// viewers/pptx/packages/angular/src/viewer/table-resize-overlay.component.ts
/**
 * table-resize-overlay.component.ts: draggable column / row resize handles.
 *
 * Selector: `pptx-table-resize-overlay`
 *
 * Angular port of the React `TableResizeOverlay`
 * (packages/react/src/viewer/utils/table-render-resize.tsx). It projects the
 * rendered `<table>` via `<ng-content>` and overlays thin draggable handles on
 * the internal column boundaries and row boundaries. Drag geometry is delegated
 * to `pptx-viewer-shared` (`computeColumnBoundaries` / `computeResizedColumnWidths`
 * / `computeResizedRowHeight`); this component only wires pointer events.
 *
 * A boundary stretch inside a merged cell gets no handle
 * (`render/table-resize-merge.ts`), so a press there reaches the cell.
 *
 * On drop it emits the new column-width array (`resizeColumns`) or the resized
 * row's index + height (`resizeRow`); the parent commits them through the editor
 * history path.
 */
import {
	afterNextRender,
	ChangeDetectionStrategy,
	Component,
	computed,
	effect,
	ElementRef,
	Injector,
	inject,
	input,
	output,
	signal,
} from '@angular/core';
import {
	columnHandleSegments,
	computeColumnBoundaries,
	computeResizedColumnWidths,
	computeResizedRowHeight,
	computeTableMergeCrossings,
	DEFAULT_ROW_HEIGHT,
	rowHandleSegments,
} from 'ooxml-ui/pptx';
import type { TableRowHandleSegment } from 'ooxml-ui/pptx';
import type { PptxTableRow } from 'pptx-viewer-core';

interface DragState {
	type: 'col' | 'row';
	index: number;
	startPos: number;
	handle: HTMLElement;
	initialWidths?: number[];
	initialRowHeight?: number;
}

@Component({
	selector: 'pptx-table-resize-overlay',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	template: `
		<div class="pptx-ng-tbl-resize" #container>
			<ng-content />
			@if (editable()) {
				@for (leftPct of colBoundaries(); track $index; let i = $index) {
					<div class="pptx-ng-tbl-resize__col" [style.left.%]="leftPct">
						@for (segment of colSegments(i); track segment.top) {
							<div
								class="pptx-ng-tbl-resize__segment pptx-ng-tbl-resize__col-segment"
								[style.top.px]="segment.top"
								[style.height]="tableHeight() ? segment.height + 'px' : '100%'"
								(pointerdown)="onColDown($event, i)"
							>
								<div class="pptx-ng-tbl-resize__col-line"></div>
							</div>
						}
					</div>
				}
				@for (topPx of rowBounds(); track $index; let i = $index) {
					<div class="pptx-ng-tbl-resize__row" [style.top.px]="topPx">
						@for (segment of rowSegments(i); track segment.leftPct) {
							<div
								class="pptx-ng-tbl-resize__segment pptx-ng-tbl-resize__row-segment"
								[style.left.%]="segment.leftPct"
								[style.width.%]="segment.widthPct"
								(pointerdown)="onRowDown($event, i)"
							>
								<div class="pptx-ng-tbl-resize__row-line"></div>
							</div>
						}
					</div>
				}
			}
		</div>
	`,
	styleUrl: './table-resize-overlay.component.css',
})
export class TableResizeOverlayComponent {
	/** Column widths as proportions summing to ~1. */
	readonly columnWidths = input.required<number[]>();
	/** Whether the resize handles are active. */
	readonly editable = input<boolean>(false);
	/** The table's rows, for the merges that interrupt a boundary. */
	readonly rows = input<readonly PptxTableRow[]>([]);

	/** Emitted on column-boundary drop with the renormalised width array. */
	readonly resizeColumns = output<number[]>();
	/** Emitted on row-boundary drop with the resized row's index + new height. */
	readonly resizeRow = output<{ index: number; height: number }>();

	private readonly host = inject(ElementRef) as ElementRef<HTMLElement>;
	private readonly injector = inject(Injector);

	/** Cumulative internal column-boundary positions as percentages (0-100). */
	readonly colBoundaries = computed<number[]>(() => computeColumnBoundaries(this.columnWidths()));

	/** Measured internal row-boundary offsets (px from the table top). */
	readonly rowBounds = signal<number[]>([]);
	/** Measured table height, for the column-boundary segments. */
	readonly tableHeight = signal(0);

	/** Where merged cells interrupt the internal boundaries. */
	readonly crossings = computed(() =>
		computeTableMergeCrossings(this.rows(), this.columnWidths().length),
	);

	/** The real-edge segments of column boundary `index`, in px from the table top. */
	colSegments(index: number): { top: number; height: number }[] {
		return columnHandleSegments(
			this.crossings().columns[index] ?? [],
			this.rowBounds(),
			this.tableHeight(),
		);
	}

	/** The real-edge segments of row boundary `index`, as percentages of the width. */
	rowSegments(index: number): TableRowHandleSegment[] {
		return rowHandleSegments(this.crossings().rows[index] ?? [], this.columnWidths());
	}

	private drag: DragState | null = null;
	private readonly onMove = (e: PointerEvent): void => this.handleMove(e);
	private readonly onUp = (e: PointerEvent): void => this.handleUp(e);

	constructor() {
		// Initial measure once the projected table has mounted, then keep the row
		// boundaries in sync: a ResizeObserver (when available) catches row-height
		// changes, and an effect re-measures when the column set changes.
		afterNextRender(
			() => {
				this.measureRows();
				this.observeResize();
			},
			{ injector: this.injector },
		);
		effect(() => {
			// Depend on the column widths so structural changes trigger a re-measure.
			this.columnWidths();
			this.rows();
			afterNextRender(() => this.measureRows(), { injector: this.injector });
		});
	}

	/** Observe the container so row-height changes re-measure the boundaries. */
	private observeResize(): void {
		const container = this.container();
		if (!container || typeof ResizeObserver === 'undefined') {
			return;
		}
		const observer = new ResizeObserver(() => this.measureRows());
		observer.observe(container);
	}

	private container(): HTMLElement | null {
		return this.host.nativeElement.querySelector('.pptx-ng-tbl-resize');
	}

	private measureRows(): void {
		const table = this.container()?.querySelector('table');
		if (!table) {
			return;
		}
		this.tableHeight.set(table.offsetHeight);
		const trs = table.querySelectorAll('tbody > tr');
		const bounds: number[] = [];
		let cumulative = 0;
		trs.forEach((tr, i) => {
			cumulative += (tr as HTMLElement).offsetHeight;
			if (i < trs.length - 1) {
				bounds.push(cumulative);
			}
		});
		const prev = this.rowBounds();
		if (prev.length !== bounds.length || prev.some((v, i) => v !== bounds[i])) {
			this.rowBounds.set(bounds);
		}
	}

	onColDown(event: PointerEvent, index: number): void {
		event.preventDefault();
		event.stopPropagation();
		this.beginDrag({
			type: 'col',
			index,
			startPos: event.clientX,
			handle: this.boundaryOf(event),
			initialWidths: [...this.columnWidths()],
		});
	}

	onRowDown(event: PointerEvent, index: number): void {
		event.preventDefault();
		event.stopPropagation();
		const table = this.container()?.querySelector('table');
		const tr = table?.querySelectorAll('tbody > tr')[index] as HTMLElement | undefined;
		this.beginDrag({
			type: 'row',
			index,
			startPos: event.clientY,
			handle: this.boundaryOf(event),
			initialRowHeight: tr?.offsetHeight ?? DEFAULT_ROW_HEIGHT,
		});
	}

	/** The whole boundary line a pressed segment belongs to, so the drag moves all of it. */
	private boundaryOf(event: PointerEvent): HTMLElement {
		const segment = event.currentTarget as HTMLElement;
		return segment.parentElement ?? segment;
	}

	private beginDrag(state: DragState): void {
		this.drag = state;
		document.addEventListener('pointermove', this.onMove);
		document.addEventListener('pointerup', this.onUp);
	}

	private handleMove(event: PointerEvent): void {
		const drag = this.drag;
		if (!drag) {
			return;
		}
		event.preventDefault();
		const delta =
			drag.type === 'col' ? event.clientX - drag.startPos : event.clientY - drag.startPos;
		drag.handle.style.transform =
			drag.type === 'col' ? `translateX(${delta}px)` : `translateY(${delta}px)`;
	}

	private handleUp(event: PointerEvent): void {
		const drag = this.drag;
		this.drag = null;
		document.removeEventListener('pointermove', this.onMove);
		document.removeEventListener('pointerup', this.onUp);
		if (!drag) {
			return;
		}
		drag.handle.style.transform = '';

		if (event.clientX !== drag.startPos && drag.type === 'col' && drag.initialWidths) {
			const rect = this.container()?.getBoundingClientRect();
			const width = rect?.width ?? 1;
			const deltaProp = (event.clientX - drag.startPos) / width;
			this.resizeColumns.emit(
				computeResizedColumnWidths(drag.initialWidths, drag.index, deltaProp),
			);
		} else if (event.clientY !== drag.startPos && drag.type === 'row') {
			const deltaY = event.clientY - drag.startPos;
			const height = computeResizedRowHeight(drag.initialRowHeight ?? DEFAULT_ROW_HEIGHT, deltaY);
			this.resizeRow.emit({ index: drag.index, height });
		}
	}
}
