// viewers/pptx/packages/svelte/src/viewer/components/inspector/ThemeColorSwatchGrid.svelte
<script lang="ts">
	/**
	 * PowerPoint's "Theme Colors" grid: ten columns (Background 1, Text 1,
	 * Background 2, Text 2, Accent 1..6) each with a base swatch and five
	 * luminance variants, built from the loaded deck's real theme colours
	 * (`EditorState.themeColorMap`) rather than a hard-coded Office palette.
	 *
	 * Renders nothing (not even the heading) when no deck theme is loaded yet,
	 * so callers can render this unconditionally alongside their existing
	 * hex/recent-colour controls.
	 */
	import type { PptxThemeColorRef } from 'pptx-viewer-core';
	import type { ThemeColorPickerCommit } from 'ooxml-ui/pptx';
	import {
		buildThemeColorSwatchGrid,
		findSelectedThemeSwatch,
		themeColorSwatchRows,
		themeSwatchCommit,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';

	const {
		themeColorMap,
		selectedRef,
		selectedHex,
		disabled = false,
		onpick,
	}: {
		themeColorMap: Record<string, string> | undefined;
		selectedRef?: PptxThemeColorRef;
		selectedHex?: string;
		disabled?: boolean;
		onpick: (commit: ThemeColorPickerCommit) => void;
	} = $props();

	const t = useTranslator();

	const columns = $derived(buildThemeColorSwatchGrid(themeColorMap));
	const rows = $derived(themeColorSwatchRows(columns));
	const selected = $derived(findSelectedThemeSwatch(columns, selectedRef, selectedHex));
</script>

{#if columns.length > 0}
	<div class="pptx-svelte-theme-swatch-grid">
		<div class="pptx-svelte-theme-swatch-grid-heading">{t('pptx.colorPicker.themeColors')}</div>
		<div class="pptx-svelte-theme-swatch-grid-rows">
			{#each rows as row, rowIndex (rowIndex)}
				<div class="pptx-svelte-theme-swatch-grid-row">
					{#each row as swatch, colIndex (colIndex)}
						{#if swatch}
							<button
								type="button"
								{disabled}
								data-pptx-compact
								class="pptx-svelte-theme-swatch-grid-swatch"
								class:pptx-svelte-theme-swatch-grid-swatch-selected={selected === swatch}
								style={`background-color:${swatch.hex}`}
								title={swatch.label}
								aria-label={swatch.label}
								onclick={() => onpick(themeSwatchCommit(swatch))}
							></button>
						{:else}
							<div class="pptx-svelte-theme-swatch-grid-empty"></div>
						{/if}
					{/each}
				</div>
			{/each}
		</div>
	</div>
{/if}

<style>
	.pptx-svelte-theme-swatch-grid {
		display: flex;
		flex-direction: column;
		gap: 4px;
		margin-top: 4px;
	}

	.pptx-svelte-theme-swatch-grid-heading {
		font-size: 10px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-theme-swatch-grid-rows {
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.pptx-svelte-theme-swatch-grid-row {
		display: flex;
		gap: 2px;
	}

	.pptx-svelte-theme-swatch-grid-swatch,
	.pptx-svelte-theme-swatch-grid-empty {
		width: 16px;
		height: 16px;
	}

	.pptx-svelte-theme-swatch-grid-swatch {
		padding: 0;
		border-radius: 2px;
		border: 1px solid var(--pptx-border, #33334d);
		cursor: pointer;
	}

	.pptx-svelte-theme-swatch-grid-swatch:hover:not(:disabled) {
		transform: scale(1.1);
	}

	.pptx-svelte-theme-swatch-grid-swatch:disabled {
		opacity: 0.4;
		cursor: not-allowed;
	}

	.pptx-svelte-theme-swatch-grid-swatch-selected {
		outline: 2px solid var(--pptx-primary, #6366f1);
		outline-offset: 1px;
	}
</style>

// viewers/pptx/packages/angular/src/viewer/theme-color-swatch-grid.component.ts
/**
 * theme-color-swatch-grid.component.ts: PowerPoint's "Theme Colors" grid (ten
 * columns - Background 1, Text 1, Background 2, Text 2, Accent 1..6 - each
 * with a base swatch and five luminance variants), built from the loaded
 * deck's real theme colours (`LoadContentService.themeColorMap`) rather than
 * a hard-coded Office palette.
 *
 * Mirrors React's `ThemeColorSwatchGrid.tsx` and Vue's
 * `ThemeColorSwatchGrid.vue`: a presentational grid that emits `pick` with
 * BOTH the resolved hex and the `PptxThemeColorRef` a caller should store so
 * the colour keeps following the theme after a later theme change.
 *
 * Renders nothing (not even the heading) when no deck theme is loaded yet,
 * so callers can render this unconditionally alongside their existing
 * hex/recent-colour controls.
 *
 * @module viewer/theme-color-swatch-grid
 */
import { ChangeDetectionStrategy, Component, computed, inject, input, output } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import type { PptxThemeColorRef } from 'pptx-viewer-core';

import type { ThemeColorPickerCommit } from 'ooxml-ui/pptx';
import {
	buildThemeColorSwatchGrid,
	findSelectedThemeSwatch,
	themeColorSwatchRows,
	themeSwatchCommit,
} from 'ooxml-ui/pptx';
import { LoadContentService } from './load-content.service';

@Component({
	selector: 'pptx-theme-color-swatch-grid',
	standalone: true,
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [TranslatePipe],
	template: `
		@if (columns().length > 0) {
			<div class="pptx-theme-swatch-grid">
				<div class="pptx-theme-swatch-grid__heading">
					{{ 'pptx.colorPicker.themeColors' | translate }}
				</div>
				<div class="pptx-theme-swatch-grid__rows">
					@for (row of rows(); track $index) {
						<div class="pptx-theme-swatch-grid__row">
							@for (swatch of row; track $index) {
								@if (swatch) {
									<button
										type="button"
										data-pptx-compact
										class="pptx-theme-swatch-grid__swatch"
										[class.pptx-theme-swatch-grid__swatch--selected]="selected() === swatch"
										[style.background]="swatch.hex"
										[title]="swatch.label"
										[attr.aria-label]="swatch.label"
										[disabled]="disabled()"
										(mousedown)="$event.preventDefault()"
										(click)="pick.emit(commitOf(swatch))"
									></button>
								} @else {
									<div class="pptx-theme-swatch-grid__empty"></div>
								}
							}
						</div>
					}
				</div>
			</div>
		}
	`,
	styles: `
		.pptx-theme-swatch-grid {
			display: flex;
			flex-direction: column;
			gap: 0.2rem;
			margin-top: 0.25rem;
		}

		.pptx-theme-swatch-grid__heading {
			font-size: 10px;
			color: var(--pptx-inspector-muted, #888);
		}

		.pptx-theme-swatch-grid__rows {
			display: flex;
			flex-direction: column;
			gap: 0.125rem;
		}

		.pptx-theme-swatch-grid__row {
			display: flex;
			gap: 0.125rem;
		}

		.pptx-theme-swatch-grid__swatch,
		.pptx-theme-swatch-grid__empty {
			height: 1rem;
			width: 1rem;
		}

		.pptx-theme-swatch-grid__swatch {
			padding: 0;
			border-radius: 2px;
			border: 1px solid var(--pptx-inspector-border, #444);
			cursor: pointer;
			transition: transform 0.1s ease;
		}

		.pptx-theme-swatch-grid__swatch:hover:not(:disabled) {
			transform: scale(1.1);
		}

		.pptx-theme-swatch-grid__swatch:disabled {
			opacity: 0.4;
			cursor: not-allowed;
		}

		.pptx-theme-swatch-grid__swatch--selected {
			border-color: var(--pptx-inspector-primary, #3b82f6);
			box-shadow: 0 0 0 1px var(--pptx-inspector-primary, #3b82f6);
		}
	`,
})
export class ThemeColorSwatchGridComponent {
	private readonly loader = inject(LoadContentService);

	readonly disabled = input<boolean>(false);
	/** The element's current theme ref, if any (highlights the matching swatch). */
	readonly selectedRef = input<PptxThemeColorRef | undefined>(undefined);
	/** The element's current resolved hex, used to highlight a swatch when no ref is stored. */
	readonly selectedHex = input<string | undefined>(undefined);
	/** A swatch was clicked: both the resolved hex and the ref to store. */
	readonly pick = output<ThemeColorPickerCommit>();

	protected readonly columns = computed(() =>
		buildThemeColorSwatchGrid(this.loader.themeColorMap()),
	);
	protected readonly rows = computed(() => themeColorSwatchRows(this.columns()));
	protected readonly selected = computed(() =>
		findSelectedThemeSwatch(this.columns(), this.selectedRef(), this.selectedHex()),
	);

	protected commitOf = themeSwatchCommit;
}
