// viewers/pptx/packages/svelte/src/viewer/components/ribbon/home/ClipboardGroup.svelte
<script lang="ts">
	/**
	 * ClipboardGroup: Paste / Cut / Copy / Format Painter for the Home tab. The
	 * markup, gating and styles are the shared `pptx-ui-ribbon-home-clipboard`
	 * element; every mutation still routes through `EditorState`
	 * (`clipboardOps`, `formatPainter`) so undo/redo covers each action.
	 */
	import { clipboardHomeControls, homeSnapshotTranslator } from 'ooxml-ui/pptx';
	import type { RibbonHomeRequestEvent } from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../../i18n/context';
	import type { EditorState } from '../../../editor/editor-state.svelte';

	const { editor }: { editor: EditorState } = $props();
	const t = useTranslator();

	const state = $derived({
		controls: clipboardHomeControls({
			editable: editor.editable,
			hasSelection: editor.selectedElementId !== null,
			hasClipboard: editor.hasClipboard,
			formatPainterActive: editor.formatPainter.active,
			canFormatPaint: editor.formatPainter.enabled,
			showFormatPainter: true,
		}),
		translate: homeSnapshotTranslator(['clipboard'], t),
	});

	function request(event: RibbonHomeRequestEvent): void {
		switch (event.detail.id) {
			case 'home.clipboard.paste':
				editor.clipboardOps.pasteClipboard();
				break;
			case 'home.clipboard.cut':
				editor.clipboardOps.cutSelected();
				break;
			case 'home.clipboard.copy':
				editor.clipboardOps.copySelected();
				break;
			case 'home.clipboard.formatPainter':
				editor.formatPainter.toggle();
		}
	}
</script>

<pptx-ui-ribbon-home-clipboard {state} onhome-request={request}></pptx-ui-ribbon-home-clipboard>

// viewers/pptx/packages/vue/src/viewer/components/ribbon/ClipboardGroup.vue
<script setup lang="ts">
/**
 * ClipboardGroup: the Home tab's Clipboard group. Markup, icons, gating and
 * styles come from the shared `pptx-ui-ribbon-home-clipboard` element; this
 * adapter only maps its one `home-request` intent onto the existing handlers.
 */
import type { RibbonHomeRequestEvent } from 'ooxml-ui/pptx';
import { clipboardHomeControls, homeSnapshotTranslator } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { ElementClipboardPayload } from './ribbon-types';

interface Props {
	canEdit: boolean;
	/** Cut and Copy act on the selection, so with nothing selected they are disabled. */
	hasSelection: boolean;
	clipboardPayload: ElementClipboardPayload | null;
	formatPainterActive?: boolean;
	canActivateFormatPainter?: boolean;
	onCopy: () => void;
	onCut: () => void;
	onPaste: () => void;
	onToggleFormatPainter?: () => void;
}

const props = defineProps<Props>();
const { t } = useI18n();

const state = computed(() => ({
	controls: clipboardHomeControls({
		editable: props.canEdit,
		hasSelection: props.hasSelection,
		hasClipboard: Boolean(props.clipboardPayload),
		formatPainterActive: Boolean(props.formatPainterActive),
		canFormatPaint: props.canActivateFormatPainter !== false,
		showFormatPainter: Boolean(props.onToggleFormatPainter),
	}),
	translate: homeSnapshotTranslator(['clipboard'], t),
}));

function request(event: RibbonHomeRequestEvent): void {
	switch (event.detail.id) {
		case 'home.clipboard.paste':
			props.onPaste();
			break;
		case 'home.clipboard.cut':
			props.onCut();
			break;
		case 'home.clipboard.copy':
			props.onCopy();
			break;
		case 'home.clipboard.formatPainter':
			props.onToggleFormatPainter?.();
	}
}
</script>

<template>
	<pptx-ui-ribbon-home-clipboard :state.prop="state" @home-request="request" />
</template>
