// viewers/pptx/packages/react/src/viewer/components/toolbar/ClipboardGroup.tsx
import { clipboardHomeControls } from 'ooxml-ui/pptx';
import React, { useCallback, useMemo } from 'react';

import { WebHomeControls } from './WebHomeControls';

export interface ClipboardGroupProps {
	canEdit: boolean;
	/** Cut and Copy act on the selection, so they need one. */
	hasSelection: boolean;
	canPaste: boolean;
	formatPainterActive?: boolean;
	canActivateFormatPainter?: boolean;
	onCopy: () => void;
	onCut: () => void;
	onPaste: () => void;
	onToggleFormatPainter?: () => void;
}

/** Home > Clipboard: the shared Paste, Cut, Copy and Format Painter strip. */
export function ClipboardGroup(p: ClipboardGroupProps): React.ReactElement {
	const { canEdit, hasSelection, canPaste, formatPainterActive, canActivateFormatPainter } = p;
	const { onPaste, onCut, onCopy, onToggleFormatPainter } = p;
	const controls = useMemo(
		() =>
			clipboardHomeControls({
				editable: canEdit,
				hasSelection,
				hasClipboard: canPaste,
				formatPainterActive: Boolean(formatPainterActive),
				canFormatPaint: canActivateFormatPainter !== false,
				showFormatPainter: Boolean(onToggleFormatPainter),
			}),
		[
			canEdit,
			hasSelection,
			canPaste,
			formatPainterActive,
			canActivateFormatPainter,
			onToggleFormatPainter,
		],
	);
	const request = useCallback(
		(id: string) => {
			switch (id) {
				case 'home.clipboard.paste':
					onPaste();
					break;
				case 'home.clipboard.cut':
					onCut();
					break;
				case 'home.clipboard.copy':
					onCopy();
					break;
				case 'home.clipboard.formatPainter':
					onToggleFormatPainter?.();
			}
		},
		[onPaste, onCut, onCopy, onToggleFormatPainter],
	);
	return <WebHomeControls family='clipboard' controls={controls} onRequest={request} />;
}

// viewers/pptx/packages/vue/src/viewer/components/ribbon/ClipboardGroup.vue
<script setup lang="ts">
/**
 * ClipboardGroup: the Home tab's Clipboard group. Markup, icons, gating and
 * styles come from the shared `pptx-ui-ribbon-home-clipboard` element; this
 * adapter only maps its one `home-request` intent onto the existing handlers.
 */
import type { RibbonHomeRequestEvent } from 'ooxml-ui/pptx';
import { clipboardHomeControls, homeSnapshotTranslator } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import type { ElementClipboardPayload } from './ribbon-types';

interface Props {
	canEdit: boolean;
	/** Cut and Copy act on the selection, so with nothing selected they are disabled. */
	hasSelection: boolean;
	clipboardPayload: ElementClipboardPayload | null;
	formatPainterActive?: boolean;
	canActivateFormatPainter?: boolean;
	onCopy: () => void;
	onCut: () => void;
	onPaste: () => void;
	onToggleFormatPainter?: () => void;
}

const props = defineProps<Props>();
const { t } = useI18n();

const state = computed(() => ({
	controls: clipboardHomeControls({
		editable: props.canEdit,
		hasSelection: props.hasSelection,
		hasClipboard: Boolean(props.clipboardPayload),
		formatPainterActive: Boolean(props.formatPainterActive),
		canFormatPaint: props.canActivateFormatPainter !== false,
		showFormatPainter: Boolean(props.onToggleFormatPainter),
	}),
	translate: homeSnapshotTranslator(['clipboard'], t),
}));

function request(event: RibbonHomeRequestEvent): void {
	switch (event.detail.id) {
		case 'home.clipboard.paste':
			props.onPaste();
			break;
		case 'home.clipboard.cut':
			props.onCut();
			break;
		case 'home.clipboard.copy':
			props.onCopy();
			break;
		case 'home.clipboard.formatPainter':
			props.onToggleFormatPainter?.();
	}
}
</script>

<template>
	<pptx-ui-ribbon-home-clipboard :state.prop="state" @home-request="request" />
</template>
