// viewers/pptx/packages/svelte/src/viewer/components/ribbon/galleries/RibbonGallery.svelte
<script lang="ts">
	import { buildRibbonGallery } from 'ooxml-ui/pptx';
	import type { RibbonGalleryPickEvent, RibbonGalleryPlacement } from 'ooxml-ui/pptx';
	import { useTranslator } from '../../../../i18n/context';
	import { refocusViewerRoot } from '../anchored-popup';
	import { strictTranslator } from './gallery-labels';
	import { useRibbonGalleryHost } from './ribbon-gallery-host';

	const { placement, chevronOnly = false, tagControl = true }: { placement: RibbonGalleryPlacement; chevronOnly?: boolean; tagControl?: boolean } = $props();
	const host = useRibbonGalleryHost();
	const t = useTranslator();
	const translateLabel = strictTranslator(t);
	const descriptor = $derived(host ? host.build(placement.gallery) : buildRibbonGallery(placement.gallery, { element: null }));
	function pick(event: Event): void {
		refocusViewerRoot(event.currentTarget as HTMLElement);
		void host?.apply(placement.gallery, (event as RibbonGalleryPickEvent).detail.itemId);
	}
</script>
<pptx-ui-ribbon-gallery data-ribbon-control={tagControl ? placement.control : undefined} mode={placement.mode} chevron-only={chevronOnly || undefined}
	{descriptor} {translateLabel} disabled={!host} ongallery-pick={pick}></pptx-ui-ribbon-gallery>

// viewers/pptx/packages/vue/src/viewer/components/ribbon/RibbonGallery.vue
<script setup lang="ts">
import type { RibbonControlId, RibbonGalleryId, RibbonGalleryPickEvent } from 'ooxml-ui/pptx';

import { useRibbonGallery } from './use-ribbon-gallery';

const props = defineProps<{
	gallery: RibbonGalleryId;
	control?: RibbonControlId;
	mode: 'inline' | 'dropdown' | 'chevron';
}>();
const g = useRibbonGallery(() => props.gallery);
function pick(event: Event): void {
	g.pick((event as RibbonGalleryPickEvent).detail.itemId);
}
</script>
<template>
	<pptx-ui-ribbon-gallery
		:data-ribbon-control="props.control"
		:mode="props.mode === 'inline' ? 'inline' : 'dropdown'"
		:chevron-only="props.mode === 'chevron' || undefined"
		:descriptor.prop="g.descriptor.value"
		:translateLabel.prop="g.translate"
		:disabled.prop="g.disabled.value"
		@gallery-pick="pick"
	></pptx-ui-ribbon-gallery>
</template>
