// viewers/pptx/packages/svelte/src/viewer/components/ribbon/slideshow/SubtitleSettingsControl.svelte
<script lang="ts">
	import { subtitleSettingsFromOptions, subtitleSettingsLabels, updateSubtitleSettings } from 'ooxml-ui/pptx';
	import type { SubtitleSettingsChangeEvent } from 'ooxml-ui/pptx';
	import { useTranslator } from '../../../../i18n/context';
	import { useViewerOptions } from '../../../state/viewer-options-context';

	const t = useTranslator();
	const options = useViewerOptions();
	function commit(event: Event): void {
		updateSubtitleSettings(options, (event as SubtitleSettingsChangeEvent).detail);
	}
</script>

<pptx-ui-subtitle-settings data-ribbon-control="slideShow.captions.subtitleSettings"
	settings={subtitleSettingsFromOptions(options.options)} labels={subtitleSettingsLabels(t)}
	languageDisabled={options.isLocked('accessibility', 'subtitleLanguage')}
	onsubtitle-settings-change={commit}
></pptx-ui-subtitle-settings>

// viewers/pptx/packages/vue/src/viewer/components/ribbon/SubtitleSettingsControl.vue
<script setup lang="ts">
import {
	createViewerOptionsStore,
	subtitleSettingsFromOptions,
	subtitleSettingsLabels,
	updateSubtitleSettings,
} from 'ooxml-ui/pptx';
import type { SubtitleSettingsChangeEvent } from 'ooxml-ui/pptx';
import { inject, onScopeDispose, shallowRef } from 'vue';
import { useI18n } from 'vue-i18n';

import { ViewerOptionsStoreKey } from '../../composables/useViewerOptionsStore';

const { t } = useI18n();
const store = inject(ViewerOptionsStoreKey, null) ?? createViewerOptionsStore({ persist: false });
const options = shallowRef(store.getOptions());
onScopeDispose(
	store.subscribe((value) => {
		options.value = value;
	}),
);
function commit(event: Event): void {
	updateSubtitleSettings(store, (event as SubtitleSettingsChangeEvent).detail);
}
</script>

<template>
	<pptx-ui-subtitle-settings
		data-ribbon-control="slideShow.captions.subtitleSettings"
		:settings.prop="subtitleSettingsFromOptions(options)"
		:labels.prop="subtitleSettingsLabels(t)"
		:languageDisabled.prop="store.isLocked('accessibility', 'subtitleLanguage')"
		@subtitle-settings-change="commit"
	></pptx-ui-subtitle-settings>
</template>
