// viewers/pptx/packages/react/src/viewer/components/toolbar/TextSection.tsx
import { hasTextProperties } from 'pptx-viewer-core';
import type { PptxElement, PptxThemeColorRef, TextStyle } from 'pptx-viewer-core';
import { textFontSizePtToPx } from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';

import type { TableCellEditorState } from '../../types';
import type { ChangeCaseMode } from '../../utils/text-case-transform';
import { extractFontInfo } from './font-info';
import { FontFormatGroup } from './FontFormatGroup';
import { FontPickerGroup } from './FontPickerGroup';
import { ParagraphGroup } from './ParagraphGroup';
import { groupAttr } from './PowerPointRibbonControls';
import { getEffectiveTextStyle, textSectionBulletKind } from './text-section-state';
import { sep } from './toolbar-constants';
import { useParagraphListKind } from './useParagraphListKind';

export interface TextSectionProps {
	canEdit: boolean;
	selectedElement: PptxElement | null;
	tableEditorState?: TableCellEditorState | null;
	onUpdateTextStyle: (updates: Partial<TextStyle>) => void;
	/** Bullets / Numbering for a text element: the shared paragraph bullet toggle. */
	onToggleBullets: (kind: 'bullet' | 'numbered') => void;
	/** Rewrite the selected text's characters (PowerPoint's Aa "Change Case" dropdown). */
	onTransformTextCase: (mode: ChangeCaseMode) => void;
	/** Theme major/minor latin faces, leading the font dropdown. */
	themeFonts?: { heading?: string; body?: string };
	/** Families the deck embeds, offered as their own dropdown group. */
	embeddedFontFamilies?: readonly string[];
	/** Families registered this session via File > Options > Fonts. */
	customFontFamilies?: readonly string[];
}

export function TextSection(p: TextSectionProps): React.ReactElement {
	const { t } = useTranslation();
	const hasSel = Boolean(p.selectedElement);
	const canMut = hasSel && p.canEdit;
	const { fontFamily, fontSize } = extractFontInfo(p.selectedElement, p.themeFonts);
	const isTextEl = hasSel && p.selectedElement !== null && hasTextProperties(p.selectedElement);
	const isTable = hasSel && p.selectedElement?.type === 'table';
	const canFormat = isTextEl || isTable;
	const effectiveTs = getEffectiveTextStyle(p.selectedElement, p.tableEditorState);
	const selectedListKind = useParagraphListKind(p.selectedElement);
	const bulletKind = isTextEl
		? selectedListKind
		: textSectionBulletKind(p.selectedElement, p.tableEditorState);
	const toggleBullets = (kind: 'bullet' | 'numbered'): void => {
		if (!p.canEdit || !canFormat || !p.selectedElement) {
			return;
		}
		if (hasTextProperties(p.selectedElement)) {
			p.onToggleBullets(kind);
			return;
		}
		// Table cells keep their cell-style path.
		p.onUpdateTextStyle({ listType: effectiveTs?.listType === kind ? 'none' : kind });
	};

	const currentColor =
		isTextEl && p.selectedElement && hasTextProperties(p.selectedElement)
			? (p.selectedElement.textSegments?.[0]?.style?.color ??
				p.selectedElement.textStyle?.color ??
				'#000000')
			: (effectiveTs?.color ?? '#000000');

	const currentColorThemeRef: PptxThemeColorRef | undefined =
		isTextEl && p.selectedElement && hasTextProperties(p.selectedElement)
			? (p.selectedElement.textSegments?.[0]?.style?.colorRef ??
				p.selectedElement.textStyle?.colorRef)
			: undefined;

	const currentHighlight =
		isTextEl && p.selectedElement && hasTextProperties(p.selectedElement)
			? (p.selectedElement.textSegments?.[0]?.style?.highlightColor ??
				p.selectedElement.textStyle?.highlightColor ??
				'#ffff00')
			: '#ffff00';

	return (
		<>
			<div className='flex flex-col items-center gap-0.5' {...groupAttr('home.font')}>
				<div className='flex items-center gap-1' data-pptx-chrome='font-controls'>
					<FontPickerGroup
						// A table needs a selected cell for the family and size boxes to mean anything.
						enabled={p.canEdit && (isTextEl || (isTable && Boolean(p.tableEditorState)))}
						fontFamily={fontFamily}
						fontSize={fontSize}
						themeFonts={p.themeFonts}
						embeddedFonts={p.embeddedFontFamilies}
						customFonts={p.customFontFamilies}
						onFamily={(family) => p.onUpdateTextStyle({ fontFamily: family })}
						onSize={(size) =>
							p.onUpdateTextStyle({
								fontSize:
									p.selectedElement && hasTextProperties(p.selectedElement)
										? textFontSizePtToPx(size)
										: size,
							})
						}
					/>
					<FontFormatGroup
						canMut={canMut}
						canFormat={canFormat}
						isTextEl={isTextEl}
						selectedElement={p.selectedElement}
						tableEditorState={p.tableEditorState}
						effectiveTs={effectiveTs}
						isTable={isTable}
						currentColor={currentColor}
						currentColorRef={currentColorThemeRef}
						currentHighlight={currentHighlight}
						onUpdateTextStyle={p.onUpdateTextStyle}
						onTransformTextCase={p.onTransformTextCase}
					/>
				</div>
				<span data-pptx-chrome='ribbon-group-label'>{t('pptx.ribbon.font')}</span>
			</div>

			{sep}

			<ParagraphGroup
				canMut={canMut}
				canFormat={canFormat}
				bulletKind={bulletKind}
				effectiveTs={effectiveTs}
				onToggleBullets={toggleBullets}
				onUpdateTextStyle={p.onUpdateTextStyle}
			/>
		</>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/ribbon/TextSection.vue
<script setup lang="ts">
/** Vue's Home character-formatting controls and thin editor wiring. */
import { hasTextProperties } from 'pptx-viewer-core';
import type { PptxElement, PptxThemeColorRef, TextStyle } from 'pptx-viewer-core';
import type { ChangeCaseMode } from 'ooxml-ui/pptx';
import { textFontSizePtToPx } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { getEffectiveTextStyle } from './effective-text-style';
import FontHomeControls from './FontHomeControls.vue';
import FontPickers from './FontPickers.vue';
import ParagraphGroup from './ParagraphGroup.vue';
import { SEP } from './ribbon-constants';
import type { TableCellEditorState } from './ribbon-types';

interface Props {
	canEdit: boolean;
	selectedElement: PptxElement | null;
	tableEditorState?: TableCellEditorState | null;
	onUpdateTextStyle: (updates: Partial<TextStyle>) => void;
	onTransformTextCase: (mode: ChangeCaseMode) => void;
	/** Theme major/minor latin faces, leading the font dropdown. */
	themeFonts?: { heading?: string; body?: string };
	/** Families the deck embeds, offered as their own dropdown group. */
	embeddedFontFamilies?: readonly string[];
	/** Families registered this session via File > Options > Fonts. */
	customFontFamilies?: readonly string[];
}

const props = defineProps<Props>();

const { t } = useI18n();

const hasSel = computed(() => Boolean(props.selectedElement));
const canMut = computed(() => hasSel.value && props.canEdit);
const isTextEl = computed(
	() => hasSel.value && props.selectedElement !== null && hasTextProperties(props.selectedElement),
);
const isTable = computed(() => hasSel.value && props.selectedElement?.type === 'table');
// Enable formatting for text elements AND table cells
const canFormat = computed(() => isTextEl.value || isTable.value);
const effectiveTs = computed(() =>
	getEffectiveTextStyle(props.selectedElement, props.tableEditorState),
);

const currentColor = computed(() =>
	isTextEl.value && props.selectedElement && hasTextProperties(props.selectedElement)
		? (props.selectedElement.textSegments?.[0]?.style?.color ??
			props.selectedElement.textStyle?.color ??
			'#000000')
		: (effectiveTs.value?.color ?? '#000000'),
);

const currentColorThemeRef = computed<PptxThemeColorRef | undefined>(() =>
	isTextEl.value && props.selectedElement && hasTextProperties(props.selectedElement)
		? (props.selectedElement.textSegments?.[0]?.style?.colorRef ??
			props.selectedElement.textStyle?.colorRef)
		: undefined,
);

const currentHighlight = computed(() =>
	isTextEl.value && props.selectedElement && hasTextProperties(props.selectedElement)
		? (props.selectedElement.textSegments?.[0]?.style?.highlightColor ??
			props.selectedElement.textStyle?.highlightColor ??
			'#ffff00')
		: '#ffff00',
);

function handleColorChange(color: string, ref?: PptxThemeColorRef): void {
	if (!canFormat.value) {
		return;
	}
	props.onUpdateTextStyle({ color, colorRef: ref });
}

function handleHighlightChange(highlightColor: string): void {
	if (!canFormat.value) {
		return;
	}
	props.onUpdateTextStyle({ highlightColor });
}

function handleFmtClick(id: string): void {
	if (!canFormat.value || !props.selectedElement) {
		return;
	}
	const ts = effectiveTs.value;
	switch (id) {
		case 'bold':
			props.onUpdateTextStyle({ bold: !ts?.bold });
			break;
		case 'italic':
			props.onUpdateTextStyle({ italic: !ts?.italic });
			break;
		case 'underline':
			props.onUpdateTextStyle({ underline: !ts?.underline });
			break;
		case 'strikethrough':
			props.onUpdateTextStyle({ strikethrough: !ts?.strikethrough });
			break;
	}
}

function handleIncreaseFontSize(): void {
	if (!canFormat.value || !props.selectedElement) {
		return;
	}
	const current = effectiveTs.value?.fontSize ?? (isTextEl.value ? textFontSizePtToPx(18) : 18);
	const delta = isTextEl.value ? textFontSizePtToPx(2) : 2;
	props.onUpdateTextStyle({ fontSize: current + delta });
}

function handleDecreaseFontSize(): void {
	if (!canFormat.value || !props.selectedElement) {
		return;
	}
	const current = effectiveTs.value?.fontSize ?? (isTextEl.value ? textFontSizePtToPx(18) : 18);
	const delta = isTextEl.value ? textFontSizePtToPx(2) : 2;
	const minimum = isTextEl.value ? textFontSizePtToPx(1) : 1;
	props.onUpdateTextStyle({ fontSize: Math.max(minimum, current - delta) });
}

function handleClearFormatting(): void {
	if (!canFormat.value) {
		return;
	}
	props.onUpdateTextStyle({
		bold: false,
		italic: false,
		underline: false,
		strikethrough: false,
		highlightColor: undefined,
	});
}

/* ── Text Shadow ── */
function handleToggleTextShadow(): void {
	if (!canFormat.value) {
		return;
	}
	const hasShadow = Boolean(effectiveTs.value?.textShadowColor);
	if (hasShadow) {
		props.onUpdateTextStyle({ textShadowColor: undefined });
	} else {
		props.onUpdateTextStyle({
			textShadowColor: '#000000',
			textShadowBlur: 2,
			textShadowOffsetX: 1,
			textShadowOffsetY: 1,
		});
	}
}

function handleCharSpacing(value: number): void {
	if (canFormat.value) {
		props.onUpdateTextStyle({ characterSpacing: value });
	}
}
function handleChangeCase(value: ChangeCaseMode): void {
	if (!canFormat.value) {
		return;
	}
	if (isTable.value) {
		props.onUpdateTextStyle({ textCaps: value === 'upper' ? 'all' : 'none' });
	} else {
		props.onTransformTextCase(value);
	}
}
</script>

<template>
	<!-- ── Font group ── -->
	<div class="flex flex-col items-center gap-0.5" data-ribbon-group="home.font">
		<div class="flex items-center gap-1" data-pptx-chrome="font-controls">
			<FontPickers
				:can-edit="props.canEdit"
				:selected-element="props.selectedElement"
				:table-editor-state="props.tableEditorState"
				:on-update-text-style="props.onUpdateTextStyle"
				:theme-fonts="props.themeFonts"
				:embedded-font-families="props.embeddedFontFamilies"
				:custom-font-families="props.customFontFamilies"
			/>
			<FontHomeControls
				:disabled="!canMut || !canFormat"
				:text-style="effectiveTs"
				:color="currentColor"
				:color-ref="currentColorThemeRef"
				:highlight="currentHighlight"
				@format="handleFmtClick"
				@shadow="handleToggleTextShadow"
				@increase="handleIncreaseFontSize"
				@decrease="handleDecreaseFontSize"
				@clear="handleClearFormatting"
				@color="handleColorChange"
				@highlight="handleHighlightChange"
				@spacing="handleCharSpacing"
				@case="handleChangeCase"
			/>
		</div>
		<span data-pptx-chrome="ribbon-group-label">{{ t('pptx.ribbon.font') }}</span>
	</div>

	<div :class="SEP" />

	<!-- ── Paragraph group ── -->
	<ParagraphGroup
		:can-edit="props.canEdit"
		:selected-element="props.selectedElement"
		:table-editor-state="props.tableEditorState"
		:on-update-text-style="props.onUpdateTextStyle"
	/>
</template>
