// viewers/pptx/packages/react/src/viewer/components/toolbar/TitleBar.tsx
import type { ToolbarActionId } from 'ooxml-ui/pptx';
import React, { useMemo } from 'react';

import type { AutosaveStatus } from '../../hooks/useAutosave';
import type { ViewerMode } from '../../types';
import { TitleBarElement } from './TitleBarElement';

export interface TitleBarProps {
	mode: ViewerMode;
	canEdit: boolean;
	/** Display name of the open document (host-supplied). */
	fileName?: string;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	autosaveEnabled: boolean;
	/** Default true. False renders the AutoSave switch inert (host policy). */
	autosaveToggleAvailable?: boolean;
	onToggleAutosave: () => void;
	canUndo: boolean;
	canRedo: boolean;
	undoLabel?: string | null;
	redoLabel?: string | null;
	onUndo: () => void;
	onRedo: () => void;
	/** Quick-access save (downloads the .pptx). */
	onSave?: () => void;
	findReplaceOpen: boolean;
	onToggleFindReplace: () => void;
	/** Dispatch a command from the search palette. */
	onCommandSearch?: (command: string) => void;
	/** Host-supplied list of toolbar buttons/ribbon tabs to hide. */
	hiddenActions?: readonly ToolbarActionId[];
	/**
	 * Run a Quick Access command that is not one of the dedicated
	 * Save/Undo/Redo buttons (`presentFromStart`, `print`, ...), by catalog id.
	 */
	onQuickCommand?: (id: string) => void;
	/** Host-owned collaboration indicator, projected into the `collaboration` slot. */
	collaborationSlot?: React.ReactNode;
	/** Host-owned account/presence area, projected into the `account` slot. */
	accountSlot?: React.ReactNode;
}

/**
 * PowerPoint-style title bar: a thin adapter around the shared
 * `pptx-ui-title-bar`. Rendered above (outside) the ribbon toolbar.
 */
export function TitleBar(p: TitleBarProps): React.ReactElement {
	const input = useMemo(
		() => ({
			editing: (p.mode === 'edit' || p.mode === 'master') && p.canEdit,
			fileName: p.fileName,
			isDirty: p.isDirty,
			autosaveState: p.autosaveStatus?.state,
			autosaveReason: p.autosaveStatus?.state === 'disabled' ? p.autosaveStatus.reason : undefined,
			autosaveEnabled: p.autosaveEnabled,
			autosaveToggleAvailable: p.autosaveToggleAvailable,
			canUndo: p.canUndo,
			canRedo: p.canRedo,
			undoLabel: p.undoLabel,
			redoLabel: p.redoLabel,
			hiddenActions: p.hiddenActions,
			showSave: Boolean(p.onSave),
		}),
		[
			p.mode,
			p.canEdit,
			p.fileName,
			p.isDirty,
			p.autosaveStatus,
			p.autosaveEnabled,
			p.autosaveToggleAvailable,
			p.canUndo,
			p.canRedo,
			p.undoLabel,
			p.redoLabel,
			p.hiddenActions,
			p.onSave,
		],
	);
	return (
		<TitleBarElement
			input={input}
			onToggleAutosave={p.onToggleAutosave}
			onSave={p.onSave}
			onUndo={p.onUndo}
			onRedo={p.onRedo}
			onQuickCommand={p.onQuickCommand}
			onCommandSearch={p.onCommandSearch}
			onToggleFindReplace={p.onToggleFindReplace}
		>
			{p.collaborationSlot ? (
				<div slot='collaboration' style={{ display: 'contents' }}>
					{p.collaborationSlot}
				</div>
			) : null}
			{p.accountSlot ? (
				<div slot='account' style={{ display: 'contents' }}>
					{p.accountSlot}
				</div>
			) : null}
		</TitleBarElement>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/ribbon/TitleBar.vue
<script setup lang="ts">
/**
 * TitleBar - thin adapter around the shared `pptx-ui-title-bar` element.
 *
 * The logo, AutoSave switch, quick-access strip, file name, status and command
 * search live in the shared view. This component maps viewer state onto the
 * element's controlled state and routes its typed events to the host handlers.
 * `placement="belowRibbon"` renders only the options-driven extras row.
 */
import { buildTitleBarState } from 'ooxml-ui/pptx';
import type {
	TitleBarCommandSearchEvent,
	TitleBarEvent,
	TitleBarPlacement,
	ToolbarActionId,
} from 'ooxml-ui/pptx';
import { computed, useSlots } from 'vue';
import { useI18n } from 'vue-i18n';

import type { AutosaveStatus } from '../../composables/useAutosave';
import { useTitleBarQuickAccess } from '../../composables/useTitleBarQuickAccess';
import type { ViewerMode } from './ribbon-types';

interface Props {
	mode: ViewerMode;
	canEdit: boolean;
	fileName?: string;
	isDirty: boolean;
	autosaveStatus?: AutosaveStatus;
	autosaveEnabled: boolean;
	autosaveDisabledReason?: string;
	/** False when the host's `autosave: false` policy makes the switch inert. */
	autosaveToggleAvailable?: boolean;
	onToggleAutosave?: () => void;
	canUndo?: boolean;
	canRedo?: boolean;
	undoLabel?: string | null;
	redoLabel?: string | null;
	onUndo?: () => void;
	onRedo?: () => void;
	onSave?: () => void;
	findReplaceOpen?: boolean;
	onToggleFindReplace?: () => void;
	onCommandSearch?: (command: string) => void;
	/** Toolbar buttons the host has asked to hide (gates Undo/Redo independently). */
	hiddenActions?: ToolbarActionId[];
	/** Run a Quick Access command other than Save/Undo/Redo, by catalog id. */
	onQuickCommand?: (id: string) => void;
	/** `belowRibbon` renders only the extras row (Options > Quick Access > position). */
	placement?: TitleBarPlacement;
}

const props = withDefaults(defineProps<Props>(), { autosaveToggleAvailable: true });
const { t } = useI18n();
const slots = useSlots();
const { quickAccess, screenTip } = useTitleBarQuickAccess();

const state = computed(() =>
	buildTitleBarState({
		editing: (props.mode === 'edit' || props.mode === 'master') && props.canEdit,
		fileName: props.fileName,
		isDirty: props.isDirty,
		autosaveState: props.autosaveStatus,
		autosaveReason: props.autosaveDisabledReason,
		autosaveEnabled: props.autosaveEnabled,
		autosaveToggleAvailable: props.autosaveToggleAvailable,
		canUndo: props.canUndo ?? false,
		canRedo: props.canRedo ?? false,
		undoLabel: props.undoLabel,
		redoLabel: props.redoLabel,
		hiddenActions: props.hiddenActions,
		showSave: Boolean(props.onSave),
		quickAccess: quickAccess.value,
		screenTip,
		translate: t,
	}),
);

function onSearch(event: Event): void {
	const detail = (event as TitleBarCommandSearchEvent).detail;
	if (detail.command) {
		props.onCommandSearch?.(detail.command);
	} else {
		props.onToggleFindReplace?.();
	}
}
function onQuick(event: Event): void {
	props.onQuickCommand?.((event as TitleBarEvent<'quick-command'>).detail.id);
}
</script>

<template>
	<pptx-ui-title-bar
		:placement="props.placement ?? 'titleBar'"
		:state.prop="state"
		@toggle-autosave="props.onToggleAutosave?.()"
		@save="props.onSave?.()"
		@undo="props.onUndo?.()"
		@redo="props.onRedo?.()"
		@quick-command="onQuick"
		@command-search="onSearch"
	>
		<div v-if="slots.collaboration" slot="collaboration" style="display: contents">
			<slot name="collaboration" />
		</div>
		<div v-if="slots.account" slot="account" style="display: contents">
			<slot name="account" />
		</div>
	</pptx-ui-title-bar>
</template>
