// viewers/pptx/packages/react/src/viewer/components/toolbar/ToolbarPrimaryRow.tsx
import { isDialogAvailable, isFeatureEnabled, isPanelVisible } from 'ooxml-ui/pptx';
import React from 'react';
import { useTranslation } from 'react-i18next';
import { LuMessageSquare, LuPanelLeft, LuPanelRight, LuSettings, LuSparkles } from 'react-icons/lu';

import { cn } from '../../utils';
import { useCollaboration, UserAvatarBar } from '../collaboration';
import { useViewerCustomizationContext } from '../viewer-customization-context';
import { CustomShowsControls } from './CustomShowsControls';
import { ModeSwitcher } from './ModeSwitcher';
import { OverflowMenu } from './OverflowMenu';
import { ic, ics, sep } from './toolbar-constants';
import type { ToolbarProps } from './toolbar-types';

export function ToolbarPrimaryRow(p: ToolbarProps): React.ReactElement {
	const { t } = useTranslation();
	const {
		mode,
		canEdit,
		isSidebarCollapsed,
		isInspectorPaneOpen,
		onToggleSidebar,
		onToggleInspector,
	} = p;

	const collab = useCollaboration();
	// Host customisation: hidden panes lose their toggles, a removed Options
	// dialog loses its gear, disabled comments / sharing lose their chrome.
	const customization = useViewerCustomizationContext();
	const showSlidesToggle = isPanelVisible(customization, 'slidesPane');
	const showInspectorToggle = isPanelVisible(customization, 'inspector');
	const showComments = isFeatureEnabled(customization, 'comments');
	const showShare = isDialogAvailable(customization, 'share');
	const showSettings = isDialogAvailable(customization, 'options');

	const qab =
		'p-1 max-md:p-2 max-md:min-h-[40px] max-md:min-w-[40px] rounded-sm transition-colors hover:bg-accent/60 disabled:opacity-40 disabled:cursor-not-allowed active:scale-90 active:opacity-70';

	return (
		<div
			data-pptx-chrome='ribbon-primary'
			className='flex items-center gap-0.5 max-md:gap-0 px-1.5 py-0.5 max-md:px-1'
		>
			{/* Left: Slides pane toggle + Undo/Redo + Find */}
			{mode !== 'present' && showSlidesToggle && (
				<button
					type='button'
					onClick={onToggleSidebar}
					className={cn(qab, !isSidebarCollapsed ? 'text-foreground' : 'text-muted-foreground')}
					title={t('pptx.toolbar.toggleSlidesPanel')}
					aria-label={t('pptx.toolbar.toggleSlidesPanel')}
				>
					<LuPanelLeft className={ic} />
				</button>
			)}
			{/* Center spacer */}
			<div className='flex-1 min-w-2 max-md:min-w-1' />

			{/* Right: Comments + Present + Share + Inspector + Settings + Overflow */}
			{(mode === 'edit' || mode === 'master') && showComments && (
				<button
					type='button'
					onClick={p.onToggleComments}
					className={cn(
						qab,
						'relative max-md:hidden',
						p.isCommentsPanelOpen ? 'text-foreground' : 'text-muted-foreground',
					)}
					title={t('pptx.toolbar.comments')}
					aria-label={t('pptx.toolbar.comments')}
				>
					<LuMessageSquare className={ics} />
					{(p.slideCommentCount ?? 0) > 0 && (
						<span className='absolute -top-0.5 -right-0.5 flex items-center justify-center w-3.5 h-3.5 rounded-full bg-primary text-[8px] text-white leading-none'>
							{p.slideCommentCount}
						</span>
					)}
				</button>
			)}

			{/* Collaboration user avatars (inline, PowerPoint-style) */}
			{collab &&
				showShare &&
				(collab.status === 'connected' || collab.status === 'connecting') &&
				collab.remoteUsers.length > 0 && (
					<button
						type='button'
						onClick={p.onOpenShareDialog}
						className='mx-1 rounded-sm px-1 py-0.5 hover:bg-accent/60 transition-colors cursor-pointer'
						title={t('pptx.toolbar.sharingUsers', { count: collab.connectedCount })}
					>
						<UserAvatarBar
							remoteUsers={collab.remoteUsers}
							localUserName={collab.config.userName}
							localUserColor={collab.config.userColor ?? '#6366f1'}
							localUserAvatar={collab.config.userAvatar}
							status={collab.status}
						/>
					</button>
				)}

			<ModeSwitcher
				mode={p.mode}
				onSetMode={p.onSetMode}
				onCloseMasterView={p.onCloseMasterView}
				onToggleSlideSorter={p.onToggleSlideSorter}
				onEnterPresenterView={p.onEnterPresenterView}
				onEnterRehearsalMode={p.onEnterRehearsalMode}
				onOpenSetUpSlideShow={p.onOpenSetUpSlideShow}
				onOpenBroadcastDialog={p.onOpenBroadcastDialog}
				onToggleSubtitles={p.onToggleSubtitles}
				showSubtitles={p.showSubtitles}
			/>

			<CustomShowsControls
				customShows={p.customShows}
				activeCustomShowId={p.activeCustomShowId}
				canEdit={p.canEdit}
				isCurrentSlideInActiveShow={p.isCurrentSlideInActiveShow}
				onSetActiveCustomShowId={p.onSetActiveCustomShowId}
				onCreateCustomShow={p.onCreateCustomShow}
				onRenameActiveCustomShow={p.onRenameActiveCustomShow}
				onDeleteActiveCustomShow={p.onDeleteActiveCustomShow}
				onToggleCurrentSlideInActiveShow={p.onToggleCurrentSlideInActiveShow}
			/>

			{sep}

			{(mode === 'edit' || mode === 'master') && showInspectorToggle && (
				<button
					type='button'
					onClick={onToggleInspector}
					className={cn(qab, isInspectorPaneOpen ? 'text-foreground' : 'text-muted-foreground')}
					title={t('pptx.toolbar.toggleInspector')}
					aria-label={t('pptx.toolbar.toggleInspector')}
				>
					<LuPanelRight className={ic} />
				</button>
			)}

			{/* AI assistant: only rendered when the host opts in via the `ai` prop */}
			{p.aiEnabled && (mode === 'edit' || mode === 'master') && (
				<button
					type='button'
					onClick={p.onToggleAiPanel}
					className={cn(qab, p.isAiPanelOpen ? 'text-primary' : 'text-muted-foreground')}
					title={t('pptx.toolbar.toggleAiAssistant')}
					aria-label={t('pptx.toolbar.toggleAiAssistant')}
				>
					<LuSparkles className={ic} />
				</button>
			)}

			{/* Settings */}
			{showSettings && (
				<button
					type='button'
					onClick={p.onOpenSettings ?? p.onToggleShortcuts}
					className={cn(qab, 'text-muted-foreground')}
					title={t('pptx.toolbar.settingsShortcuts')}
					aria-label={t('pptx.toolbar.settings')}
				>
					<LuSettings className={ics} />
				</button>
			)}

			{!canEdit && p.isProtectedView && p.onEnableEditing ? (
				<button
					type='button'
					onClick={p.onEnableEditing}
					className='inline-flex items-center px-2 py-0.5 rounded-sm bg-amber-600/90 text-[10px] text-amber-50 transition-colors hover:bg-amber-600'
					title={t('pptx.options.trust.protectedViewInfo')}
				>
					{t('pptx.security.enableEditing')}
				</button>
			) : (
				!canEdit && (
					<span className='inline-flex items-center px-2 py-0.5 rounded-sm bg-amber-600/90 text-[10px] text-amber-50'>
						{t('pptx.toolbar.readOnly')}
					</span>
				)
			)}
			<OverflowMenu {...p} />
		</div>
	);
}

// viewers/pptx/packages/vue/src/viewer/components/ribbon/ToolbarPrimaryRow.vue
<script setup lang="ts">
/**
 * ToolbarPrimaryRow: Vue port of React's `toolbar/ToolbarPrimaryRow.tsx`.
 *
 * The ribbon's quick-access strip: slides-pane toggle, then a right cluster of
 * comments, mode switcher, custom-show controls, inspector toggle, settings,
 * read-only badge, and the overflow menu.
 *
 * Undo/Redo and the Find button now live in the title bar; the Share button
 * moved to the tab row (`TabRowActions`), mirroring React's PowerPoint chrome.
 *
 * The React row also renders inline collaboration avatars from a
 * `useCollaboration()` context; in Vue collaboration is host-instantiated (not a
 * ribbon-level context), so that purely-decorative avatar cluster is omitted.
 */
import { MessageSquare, PanelLeft, PanelRight, Settings, Sparkles } from 'lucide-vue-next';
import { isDialogAvailable, isPanelVisible } from 'ooxml-ui/pptx';
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';

import { cn } from '../../../utils';
import { useResolvedCustomization } from '../../composables/useViewerCustomization';
import CustomShowsControls from './CustomShowsControls.vue';
import ModeSwitcher from './ModeSwitcher.vue';
import OverflowMenu from './OverflowMenu.vue';
import { ic, ics, SEP } from './ribbon-constants';
import type { RibbonProps } from './ribbon-types';

interface Props extends RibbonProps {}

const props = defineProps<Props>();
const { t } = useI18n();
// Host UI customisation: hidden panels drop their toggles, a hidden Options
// dialog drops the gear.
const customization = useResolvedCustomization();
const slidesPaneVisible = computed(() => isPanelVisible(customization.value, 'slidesPane'));
const inspectorVisible = computed(() => isPanelVisible(customization.value, 'inspector'));
const optionsAvailable = computed(() => isDialogAvailable(customization.value, 'options'));

const qab =
	'p-1 max-md:p-2 max-md:min-h-[40px] max-md:min-w-[40px] rounded-sm transition-colors hover:bg-accent/60 disabled:opacity-40 disabled:cursor-not-allowed active:scale-90 active:opacity-70';
</script>

<template>
	<div
		data-pptx-chrome="ribbon-primary"
		class="flex items-center gap-0.5 max-md:gap-0 px-1.5 py-0.5 max-md:px-1"
	>
		<!-- Left: Slides pane toggle -->
		<button
			v-if="props.mode !== 'present' && slidesPaneVisible"
			type="button"
			:class="cn(qab, !props.isSidebarCollapsed ? 'text-foreground' : 'text-muted-foreground')"
			:title="t('pptx.toolbar.toggleSlidesPanel')"
			:aria-label="t('pptx.toolbar.toggleSlidesPanel')"
			@click="props.onToggleSidebar()"
		>
			<PanelLeft :class="ic" />
		</button>

		<!-- Center spacer -->
		<div class="flex-1 min-w-2 max-md:min-w-1" />

		<!-- Right: Comments + Present + Inspector + Settings + Overflow -->
		<button
			v-if="props.mode === 'edit' || props.mode === 'master'"
			type="button"
			:class="
				cn(
					qab,
					'relative max-md:hidden',
					props.isCommentsPanelOpen ? 'text-foreground' : 'text-muted-foreground',
				)
			"
			:title="t('pptx.toolbar.comments')"
			:aria-label="t('pptx.toolbar.comments')"
			@click="props.onToggleComments?.()"
		>
			<MessageSquare :class="ics" />
			<span
				v-if="(props.slideCommentCount ?? 0) > 0"
				class="absolute -top-0.5 -right-0.5 flex items-center justify-center w-3.5 h-3.5 rounded-full bg-primary text-[8px] text-white leading-none"
			>
				{{ props.slideCommentCount }}
			</span>
		</button>

		<ModeSwitcher
			:mode="props.mode"
			:on-set-mode="props.onSetMode"
			:on-close-master-view="props.onCloseMasterView"
			:on-enter-presenter-view="props.onEnterPresenterView"
			:on-enter-rehearsal-mode="props.onEnterRehearsalMode"
			:on-open-set-up-slide-show="props.onOpenSetUpSlideShow"
			:on-open-broadcast-dialog="props.onOpenBroadcastDialog"
			:on-toggle-subtitles="props.onToggleSubtitles"
			:show-subtitles="props.showSubtitles"
		/>

		<CustomShowsControls
			:custom-shows="props.customShows"
			:active-custom-show-id="props.activeCustomShowId"
			:can-edit="props.canEdit"
			:is-current-slide-in-active-show="props.isCurrentSlideInActiveShow"
			:on-set-active-custom-show-id="props.onSetActiveCustomShowId"
			:on-create-custom-show="props.onCreateCustomShow"
			:on-rename-active-custom-show="props.onRenameActiveCustomShow"
			:on-delete-active-custom-show="props.onDeleteActiveCustomShow"
			:on-toggle-current-slide-in-active-show="props.onToggleCurrentSlideInActiveShow"
		/>

		<div :class="SEP" />

		<button
			v-if="(props.mode === 'edit' || props.mode === 'master') && inspectorVisible"
			type="button"
			:class="cn(qab, props.isInspectorPaneOpen ? 'text-foreground' : 'text-muted-foreground')"
			:title="t('pptx.toolbar.toggleInspector')"
			:aria-label="t('pptx.toolbar.toggleInspector')"
			@click="props.onToggleInspector()"
		>
			<PanelRight :class="ic" />
		</button>

		<!-- AI assistant: only rendered when the host opts in via the `ai` prop -->
		<button
			v-if="props.aiEnabled && (props.mode === 'edit' || props.mode === 'master')"
			type="button"
			:class="cn(qab, props.isAiPanelOpen ? 'text-primary' : 'text-muted-foreground')"
			:title="t('pptx.toolbar.toggleAiAssistant')"
			:aria-label="t('pptx.toolbar.toggleAiAssistant')"
			@click="props.onToggleAiPanel?.()"
		>
			<Sparkles :class="ic" />
		</button>

		<!-- Settings -->
		<button
			v-if="optionsAvailable"
			type="button"
			:class="cn(qab, 'text-muted-foreground')"
			:title="t('pptx.toolbar.settingsShortcuts')"
			:aria-label="t('pptx.toolbar.settings')"
			@click="(props.onOpenSettings ?? props.onToggleShortcuts)()"
		>
			<Settings :class="ics" />
		</button>

		<span
			v-if="!props.canEdit"
			class="inline-flex items-center px-2 py-0.5 rounded-sm bg-amber-600/90 text-[10px] text-amber-50"
		>
			{{ t('pptx.toolbar.readOnly') }}
		</span>
		<OverflowMenu v-bind="props" />
	</div>
</template>
