// viewers/pptx/packages/vue/src/viewer/components/InlineTextEditor.vue
<script setup lang="ts">
/**
 * InlineTextEditor: a `contentEditable` overlay for editing an element's text
 * in place (Vue port of the React `elements/InlineTextEditor.tsx`).
 *
 * It is mounted inside the scaled slide stage (same coordinate space as
 * {@link SelectionOverlay}), positioned over the element's box, and seeded once
 * from the element's plain text. It does NOT re-bind its value while the user
 * types (the DOM owns the text during an edit) and only reports changes via
 * `change`, committing on blur (`commit`) or cancelling on Escape (`cancel`).
 * The host commits the typed text back onto the element's rich `textSegments`
 * (via `remapTextToSegments`) so per-run styling is preserved.
 */
import type { PptxElement, TextStyle } from 'pptx-viewer-core';
import {
	attachCollaborationInlineEditor,
	attachInlineListController,
	createInlineListSeed,
	initializeInlineListDom,
	inlineListBodyText,
	mapInlineTextFormatKey,
	placeCaretAt,
	readEditableText,
	readListActivationSelection,
	restoreInlineListBodySelection,
	takePendingCaretPoint,
} from 'ooxml-ui/pptx';
import type {
	CollaborationInlineEditor,
	CollaborationLivePatcher,
	InlineListController,
	InlineTextEditSnapshot,
} from 'ooxml-ui/pptx';
import { computed, nextTick, onBeforeUnmount, onMounted, ref, shallowRef, toRaw, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import { inlineEditorStyle } from './inline-editor-style';

const { t } = useI18n();

const props = withDefaults(
	defineProps<{
		element: PptxElement;
		livePatcher?: CollaborationLivePatcher;
		slideId?: string;
		/** Draw the browser's native red spell-check squiggles while editing (View ▸ Spell). */
		spellCheck?: boolean;
	}>(),
	{ spellCheck: true },
);

const emit = defineEmits<{
	change: [text: string, snapshot?: InlineTextEditSnapshot];
	commit: [];
	cancel: [];
	/** Ctrl/Cmd+B/I/U formatting toggle while editing (parity with React). */
	format: [updates: Partial<TextStyle>];
	listSession: [event: { controller: InlineListController; active: boolean }];
}>();

const editorRef = ref<HTMLDivElement | null>(null);
const listSeed = shallowRef(createInlineListSeed(toRaw(props.element)));
let listController: InlineListController | undefined;
let connected: CollaborationInlineEditor | undefined;
let disposed = false;
let activatingList = false;
watch(
	() => props.element,
	async (element) => {
		if (connected) {
			connected.checkModel(toRaw(element));
			return;
		}
		if (listSeed.value) {
			return;
		}
		const seed = createInlineListSeed(toRaw(element));
		if (!seed) {
			return;
		}
		const body = inlineListBodyText('textSegments' in element ? element.textSegments : undefined);
		if (editorRef.value && readEditableText(editorRef.value) !== body) {
			disposed = true;
			emit('cancel');
			return;
		}
		const selection = editorRef.value
			? readListActivationSelection(
					editorRef.value,
					inlineListBodyText('textSegments' in element ? element.textSegments : undefined),
				)
			: undefined;
		activatingList = true;
		listSeed.value = seed;
		await nextTick();
		if (!disposed) {
			initializeEditor(selection);
		}
		activatingList = false;
	},
);

/** The element's current plain text (seed value). */
function seedText(): string {
	return (props.element as { text?: string }).text ?? '';
}

/** Read the live text out of the contentEditable node. */
function extractText(): string {
	return editorRef.value?.innerText ?? '';
}

const editorStyle = computed(() =>
	inlineEditorStyle(props.element, Boolean(listSeed.value || props.livePatcher?.isActive())),
);

function initializeEditor(selection?: { start: number; end: number }): void {
	const node = editorRef.value;
	if (!node) {
		return;
	}
	const seed = listSeed.value;
	if (props.livePatcher?.isActive()) {
		connected = attachCollaborationInlineEditor(node, toRaw(props.element), {
			patcher: props.livePatcher,
			slideId: props.slideId,
			onSnapshot: (snapshot) => emit('change', snapshot.text, snapshot),
			onCancel: () => {
				disposed = true;
				emit('cancel');
			},
		});
		if (!connected) {
			disposed = true;
			emit('cancel');
			return;
		}
		listController = connected;
		emit('listSession', { controller: connected, active: true });
	} else if (seed && initializeInlineListDom(node, seed)) {
		listController = attachInlineListController(node, seed, {
			isCurrent: () => !disposed && props.element.id === seed.elementId && editorRef.value === node,
			onRead: (result) =>
				emit(
					'change',
					result.kind === 'supported' ? result.snapshot.text : result.text,
					result.kind === 'supported' ? result.snapshot : undefined,
				),
		});
		emit('listSession', { controller: listController, active: true });
	} else {
		node.innerText = seedText();
	}
	node.focus();
	// The caret goes where the click that opened the editor landed (PowerPoint),
	// else at the end of the seeded text (shared contract helpers).
	placeCaretAt(node, takePendingCaretPoint());
	if (seed && selection) {
		restoreInlineListBodySelection(seed, node, selection);
	}
}
onMounted(() => initializeEditor());
onBeforeUnmount(() => {
	disposed = true;
	listController?.dispose();
	if (listController) {
		emit('listSession', { controller: listController, active: false });
	}
});

function onInput(): void {
	if (!listController) {
		emit('change', extractText());
	}
}

function onBlur(): void {
	if (activatingList) {
		return;
	}
	if (disposed) {
		return;
	}
	if (listController) {
		const result = listController.refresh();
		if (connected && result.kind !== 'supported') {
			return;
		}
	} else {
		emit('change', extractText());
	}
	emit('commit');
}

/** The style the B/I/U toggles read their current state from. */
function currentTextStyle(): TextStyle | undefined {
	const el = props.element as {
		textSegments?: Array<{ style?: TextStyle }>;
		textStyle?: TextStyle;
	};
	if (!listController) {
		return el.textSegments?.[0]?.style ?? el.textStyle;
	}
	const current = listController.readSelection();
	const style =
		current.kind === 'supported'
			? current.snapshot.textSegments?.[current.selection?.startSegIdx ?? 0]?.style
			: el.textSegments?.[0]?.style;
	return {
		...style,
		bold: style?.bold ?? el.textStyle?.bold,
		italic: style?.italic ?? el.textStyle?.italic,
		underline: style?.underline ?? el.textStyle?.underline,
	};
}

/**
 * When the caret sits at a soft word-wrap boundary (no explicit line break,
 * just CSS wrapping), the space separating the two words is still part of the
 * text and lands right before the caret. Pressing Enter there splits the DOM
 * at that exact position, leaving the new paragraph break preceded by a stray
 * space (mirrors the React inline editor's fix). Since a space immediately
 * before a paragraph break is never visually meaningful, drop it before the
 * browser performs its native Enter/paragraph-split.
 */
function trimTrailingSpaceBeforeCaret(): void {
	const selection = window.getSelection();
	if (!selection || !selection.isCollapsed || selection.rangeCount === 0) {
		return;
	}
	const range = selection.getRangeAt(0);
	const { startContainer, startOffset } = range;
	if (startContainer.nodeType !== Node.TEXT_NODE || startOffset === 0) {
		return;
	}
	const text = startContainer.textContent ?? '';
	if (text.charAt(startOffset - 1) !== ' ') {
		return;
	}
	const trimRange = document.createRange();
	trimRange.setStart(startContainer, startOffset - 1);
	trimRange.setEnd(startContainer, startOffset);
	if (connected) {
		connected.mutate(trimRange, () => trimRange.deleteContents());
	} else {
		trimRange.deleteContents();
	}
}

function onKeydown(event: KeyboardEvent): void {
	if (listController && event.isComposing) {
		return;
	}
	// Inline formatting shortcuts (Ctrl/Cmd + B/I/U): resolved by the shared
	// keymap so this three-way switch is not hand-derived a fourth time.
	const property = mapInlineTextFormatKey(event);
	if (property) {
		event.preventDefault();
		event.stopPropagation();
		const ts = currentTextStyle();
		emit('format', { [property]: !ts?.[property] });
		return;
	}
	if (event.key === 'Escape') {
		event.preventDefault();
		if (listController) {
			disposed = true;
			listController.dispose();
		}
		emit('cancel');
		return;
	}
	if (event.key === 'Enter' && (!listController || (connected && !listSeed.value))) {
		trimTrailingSpaceBeforeCaret();
	}
}
</script>

<template>
	<div
		:key="listSeed ? 'list' : 'plain'"
		ref="editorRef"
		class="pptx-vue-inline-editor"
		data-inline-editor
		contenteditable="true"
		:spellcheck="props.spellCheck"
		role="textbox"
		:aria-label="t('pptx.inlineEditor.editText')"
		:style="editorStyle"
		@input="onInput"
		@blur="onBlur"
		@keydown="onKeydown"
		@pointerdown.stop
	/>
</template>

// viewers/pptx/packages/react/src/viewer/components/elements/InlineTextEditor.tsx
import type { PptxElement, TextStyle } from 'pptx-viewer-core';
import { hasTextProperties } from 'pptx-viewer-core';
import {
	getInlineEditorSelectionResult,
	isBulletMarkerSegment,
	mapInlineTextFormatKey,
	placeCaretAt,
	readEditableText,
	takePendingCaretPoint,
} from 'ooxml-ui/pptx';
import type { InlineTextEditSnapshot } from 'ooxml-ui/pptx';
import React, { useRef, useEffect, useLayoutEffect, useCallback } from 'react';

import { DEFAULT_TEXT_COLOR } from '../../constants';
import { getTextCompensationTransform, getTextWarpStyle, renderTextSegments } from '../../utils';
import {
	getPendingSelectionRestore,
	restoreSegmentSelection,
} from '../../utils/inline-selection-utils';
import { useInlineListEditor } from './useInlineListEditor';

/**
 * Rich inline text editor: uses a `contentEditable` div that renders the same
 * rich text segments as view mode so formatting (per-run fonts, sizes, colors,
 * bullets, paragraph indentation, text effects) is preserved while editing.
 *
 * Listed text publishes an authored-body snapshot from the native DOM so
 * paragraph and run formatting survive editing and pending Save. Other text
 * keeps the existing plain-text callback and segment-remapping path.
 *
 * The outer wrapper matches the view-mode text container exactly:
 * - `getTextLayoutStyle` for flex vertical alignment, body-inset padding, columns
 * - `getTextStyleForElement` (textStyle) for element-level font defaults
 * - `getTextWarpStyle` for text warp 3D transforms
 * - `getTextCompensationTransform` for rotation compensation
 */
export function InlineTextEditor({
	initialText,
	spellCheck,
	rtl,
	textDirection: _textDirection,
	textStyle,
	textStyleRaw,
	layoutStyle,
	element,
	onCommit,
	onCancel,
	onEditChange,
	onFormatText,
}: {
	initialText: string;
	spellCheck: boolean;
	rtl?: boolean;
	textDirection?: TextStyle['textDirection'];
	textStyle: React.CSSProperties;
	/** Raw TextStyle object for computing warp transforms. */
	textStyleRaw?: TextStyle;
	/** Layout style from getTextLayoutStyle; provides flex vertical alignment. */
	layoutStyle: React.CSSProperties;
	element: PptxElement;
	onCommit: () => void;
	onCancel: () => void;
	onEditChange: (t: string, snapshot?: InlineTextEditSnapshot) => void;
	/** Called when the user applies formatting via keyboard shortcut (Ctrl+B/I/U). */
	onFormatText?: (updates: Partial<TextStyle>) => void;
}) {
	const editorRef = useRef<HTMLDivElement>(null);
	const list = useInlineListEditor(element, editorRef, onEditChange, onCancel);

	// The editor is UNCONTROLLED: its content is seeded exactly once (below) and
	// the DOM owns the text from then on. `initialText` is updated by the parent
	// on every keystroke (via onEditChange), so if we rendered it as children
	// React would rewrite the text node on each change and the caret would jump
	// back to the start / typing would reverse. We therefore capture the seed
	// content on first render and never re-render it; live edits flow out through
	// handleInput, and the latest value is read from the DOM on commit/blur.
	const seedRef = useRef<{ initialText: string; hasRichSegments: boolean } | null>(null);
	if (seedRef.current === null) {
		seedRef.current = {
			initialText,
			hasRichSegments: Boolean(
				hasTextProperties(element) && element.textSegments && element.textSegments.length > 0,
			),
		};
	}
	const seed = seedRef.current;

	// Extract authored text from the contentEditable div. Rendered list markers
	// are annotated presentation chrome and are intentionally excluded.
	const extractText = useCallback((): string => {
		const el = editorRef.current;
		if (!el) {
			return seed.initialText;
		}
		return readEditableText(el);
	}, [seed]);

	// Sync text to parent on every input via ref (no re-render)
	const handleInput = useCallback(() => {
		if (!list.publish()) {
			onEditChange(extractText());
		}
	}, [extractText, list, onEditChange]);

	// When the caret sits at a soft word-wrap boundary (no explicit line break,
	// just CSS wrapping), the space that separates the two words is still part
	// of the text and lands right before the caret. Pressing Enter there splits
	// the DOM at that exact position, leaving the new paragraph break preceded
	// by a stray space: e.g. "fox jumps" wrapped as "fox " / "jumps" becomes
	// paragraphs "fox " and "jumps" instead of "fox" and "jumps". That extra,
	// invisible trailing character then counts toward the paragraph's measured
	// width, occasionally forcing an unwanted extra wrapped line. Since a space
	// immediately before a paragraph break is never visually meaningful, drop it
	// before the browser performs its native Enter/paragraph-split.
	const trimTrailingSpaceBeforeCaret = useCallback(() => {
		const selection = window.getSelection();
		if (!selection || !selection.isCollapsed || selection.rangeCount === 0) {
			return;
		}
		const range = selection.getRangeAt(0);
		const { startContainer, startOffset } = range;
		if (startContainer.nodeType !== Node.TEXT_NODE || startOffset === 0) {
			return;
		}
		const text = startContainer.textContent ?? '';
		if (text.charAt(startOffset - 1) !== ' ') {
			return;
		}
		const trimRange = document.createRange();
		trimRange.setStart(startContainer, startOffset - 1);
		trimRange.setEnd(startContainer, startOffset);
		if (list.connected) {
			list.mutate(trimRange, () => trimRange.deleteContents());
		} else {
			trimRange.deleteContents();
		}
	}, [list]);

	// Auto-focus on mount; the caret goes where the click that opened the editor
	// landed (PowerPoint), else at the end of the content (shared contract helpers).
	useEffect(() => {
		const el = editorRef.current;
		if (!el) {
			return;
		}
		el.focus();
		placeCaretAt(el, takePendingCaretPoint());
	}, []);

	// After a formatting update, React re-renders the contentEditable children
	// which destroys the DOM selection. Restore it from the pending info.
	const mountedRef = useRef(false);
	useLayoutEffect(() => {
		// Skip the initial mount; cursor is already placed by the effect above.
		if (!mountedRef.current) {
			mountedRef.current = true;
			return;
		}
		const pending = getPendingSelectionRestore();
		if (!pending || !editorRef.current || list.seed) {
			return;
		}
		restoreSegmentSelection(
			editorRef.current,
			pending.startSegIdx,
			pending.startOffset,
			pending.endSegIdx,
			pending.endOffset,
		);
	});

	// Build wrapper style matching view-mode exactly:
	// layoutStyle (flex alignment, vertical padding, columns) + textStyle (font defaults,
	// horizontal padding/insets) + warp transforms + compensation transform.
	//
	// View mode applies: getTextLayoutStyle + txtS + getTextWarpStyle + compensationTransform
	// We replicate that same order here.
	const warpStyle = getTextWarpStyle(textStyleRaw);

	// Merge the compensation transform with warp transform if both exist
	const compensationTransform = getTextCompensationTransform(element);
	const warpTransform = warpStyle?.transform;
	const mergedTransform =
		[compensationTransform, warpTransform].filter(Boolean).join(' ') || undefined;

	const wrapperStyle: React.CSSProperties = {
		...layoutStyle,
		...textStyle,
		...warpStyle,
		transform: mergedTransform,
		transformOrigin: warpStyle?.transformOrigin || 'center',
	};

	const nextInlineStyleValue = (property: 'bold' | 'italic' | 'underline'): boolean | undefined => {
		if (!hasTextProperties(element)) {
			return true;
		}
		// Range formatting is based on the first selected run, not the first run
		// in the text box. Keep the existing first-run fallback for a collapsed caret.
		const result = getInlineEditorSelectionResult(element.textSegments);
		if (
			result.kind === 'unsupported' ||
			(result.snapshot && result.snapshot.elementId !== element.id)
		) {
			return;
		}
		const selection = result.selection;
		const segments = result.snapshot?.textSegments ?? element.textSegments;
		const segment = selection
			? segments?.[selection.startSegIdx]
			: list.seed
				? segments?.find(
						(run) => !isBulletMarkerSegment(run) && !run.isParagraphBreak && run.text !== '\n',
					)
				: segments?.[0];
		return !(segment?.style?.[property] ?? element.textStyle?.[property]);
	};

	return (
		<div
			key={list.seed?.paragraphs[0].token ?? 'plain'}
			ref={editorRef}
			contentEditable
			suppressContentEditableWarning
			data-inline-editor
			spellCheck={spellCheck}
			dir={rtl ? 'rtl' : 'ltr'}
			className='relative z-10 w-full h-full whitespace-pre-wrap break-words leading-[1.3] outline-none'
			style={{
				...wrapperStyle,
				...(list.seed ? { textDecoration: 'none', textDecorationLine: 'none' } : {}),
				cursor: 'text',
				minHeight: '1em',
			}}
			// Touch surfaces drive canvas drag/marquee through onPointerDown (see
			// useCanvasEventHandlers.handleStagePointerDown). Without stopping it
			// here, tapping inside the editor to reposition the caret would bubble
			// to the stage and start dragging the element instead of editing.
			onPointerDown={(e) => e.stopPropagation()}
			onMouseDown={(e) => e.stopPropagation()}
			onClick={(e) => e.stopPropagation()}
			onInput={list.seed ? undefined : handleInput}
			onBlur={() => {
				if (!list.canCommit()) {
					return;
				}
				handleInput();
				onCommit();
			}}
			onKeyDown={(e) => {
				// Inline formatting shortcuts (Ctrl/Cmd + B/I/U), resolved by the
				// same shared helper Svelte and Vanilla use, so the three chords
				// cannot drift from one binding to the next.
				const property = onFormatText ? mapInlineTextFormatKey(e) : null;
				if (property) {
					e.preventDefault();
					e.stopPropagation();
					const value = nextInlineStyleValue(property);
					if (value !== undefined) {
						onFormatText?.({ [property]: value });
					}
					return;
				}
				if (e.key === 'Escape') {
					e.preventDefault();
					list.retire();
					onCancel();
					return;
				}
				if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
					e.preventDefault();
					if (!list.canCommit()) {
						return;
					}
					handleInput();
					onCommit();
					return;
				}
				if (e.key === 'Enter') {
					trimTrailingSpaceBeforeCaret();
				}
			}}
			// Prevent paste from inserting HTML: paste as plain text only
			onPaste={(e) => {
				e.preventDefault();
				const text = e.clipboardData.getData('text/plain');
				document.execCommand('insertText', false, text);
			}}
		>
			{list.seed
				? list.children
				: seed.hasRichSegments
					? renderTextSegments(element, DEFAULT_TEXT_COLOR)
					: seed.initialText}
		</div>
	);
}
