// viewers/pptx/packages/vue/src/viewer/components/BroadcastDialog.vue
<script setup lang="ts">
import {
	DEFAULT_BROADCAST_SERVER_URL,
	generateBroadcastRoomId,
	resolveTransportForServerUrl,
} from 'ooxml-ui/pptx';
import type { CollaborationTransport } from 'ooxml-ui/pptx';
/**
 * BroadcastDialog: start / stop a one-way live broadcast for the Vue viewer.
 *
 * A broadcast is a one-way collaboration session: the presenter drives slide
 * navigation and viewers follow along via a shareable link. This dialog only
 * owns the start/stop UI; the host (`PowerPointViewer.vue`) is responsible for
 * actually opening a collaboration session in response to the `start` event and
 * for supplying the resolved `viewerUrl` while the broadcast is `active`.
 *
 * Mirrors the React `BroadcastDialog.tsx` contract but trimmed to the one-way
 * presenter/viewer flow, built on the local {@link ModalDialog} shell.
 *
 * Props:
 *  - `open`      : whether the dialog is visible.
 *  - `defaults`  : optional `{ roomId, serverUrl }` seed for the start form.
 *  - `active`    : whether a broadcast is currently running.
 *  - `viewerUrl` : the shareable follow link (shown while `active`).
 *
 * Emits:
 *  - `start` : `{ roomId, serverUrl }`, the presenter started a broadcast.
 *  - `stop`  : the presenter stopped the active broadcast.
 *  - `close` : the dialog was dismissed.
 */
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';

import DialogFooter from './DialogFooter.vue';
import ModalDialog from './ModalDialog.vue';

interface BroadcastDefaults {
	roomId?: string;
	serverUrl?: string;
}

interface BroadcastConfig {
	roomId: string;
	serverUrl: string;
	transport?: CollaborationTransport;
}

const props = defineProps<{
	open: boolean;
	defaults?: BroadcastDefaults;
	active?: boolean;
	viewerUrl?: string;
}>();

const emit = defineEmits<{
	start: [config: BroadcastConfig];
	stop: [];
	close: [];
}>();

const { t } = useI18n();

const roomId = ref('');
const serverUrl = ref(DEFAULT_BROADCAST_SERVER_URL);
const copied = ref(false);

// Seed the form whenever the dialog opens for a fresh (non-active) broadcast.
watch(
	() => props.open,
	(open) => {
		if (open && !props.active) {
			roomId.value = props.defaults?.roomId ?? generateBroadcastRoomId();
			serverUrl.value = props.defaults?.serverUrl ?? DEFAULT_BROADCAST_SERVER_URL;
			copied.value = false;
		}
	},
	{ immediate: true },
);

// A blank server URL is valid: it selects serverless peer-to-peer (webrtc).
const canStart = computed(() => roomId.value.trim().length > 0);

// True when the current server field selects serverless peer-to-peer mode.
const isPeerToPeer = computed(() => resolveTransportForServerUrl(serverUrl.value) === 'webrtc');

const title = computed(() =>
	props.active ? t('pptx.broadcast.broadcastingTitle') : t('pptx.broadcast.startTitle'),
);

function onClose(): void {
	emit('close');
}

function onStart(): void {
	if (!canStart.value) {
		return;
	}
	const trimmedServer = serverUrl.value.trim();
	emit('start', {
		roomId: roomId.value.trim(),
		serverUrl: trimmedServer,
		transport: resolveTransportForServerUrl(trimmedServer),
	});
}

function onStop(): void {
	emit('stop');
}

const canCopy = computed(
	() =>
		typeof navigator !== 'undefined' &&
		navigator.clipboard !== undefined &&
		typeof navigator.clipboard.writeText === 'function',
);

function onCopyLink(): void {
	if (!props.viewerUrl || !canCopy.value) {
		return;
	}
	void Promise.resolve(navigator.clipboard.writeText(props.viewerUrl)).then(() => {
		copied.value = true;
		window.setTimeout(() => {
			copied.value = false;
		}, 2000);
		return undefined;
	});
}
</script>

<template>
	<ModalDialog :open="props.open" :title="title" @close="onClose">
		<!-- Active: share the follow link + stop control -->
		<div v-if="props.active" class="pptx-vue-broadcast flex flex-col gap-4">
			<p class="pptx-vue-broadcast-desc text-[13px] leading-relaxed text-muted-foreground">
				{{ t('pptx.broadcast.liveDesc') }}
			</p>

			<div class="pptx-vue-broadcast-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-broadcast-viewer-url"
					class="pptx-vue-broadcast-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.broadcast.viewerLink') }}
				</label>
				<div class="pptx-vue-broadcast-link-row flex items-center gap-2">
					<input
						id="pptx-vue-broadcast-viewer-url"
						class="pptx-vue-broadcast-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
						type="text"
						readonly
						:value="props.viewerUrl ?? ''"
						@focus="(e) => (e.target as HTMLInputElement).select()"
					/>
					<button
						type="button"
						class="pptx-vue-broadcast-btn shrink-0 whitespace-nowrap rounded border border-border bg-muted px-2.5 py-1.5 text-[12px] text-foreground transition-colors hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40"
						:disabled="!canCopy || !props.viewerUrl"
						@click="onCopyLink"
					>
						{{ copied ? t('pptx.share.copied') : t('pptx.broadcast.copyLinkBtn') }}
					</button>
				</div>
				<p class="pptx-vue-broadcast-hint text-[11px] text-muted-foreground">
					{{ t('pptx.broadcast.viewerHint') }}
				</p>
				<p
					v-if="isPeerToPeer"
					class="pptx-vue-broadcast-server-value text-[11px] text-muted-foreground"
				>
					{{ t('pptx.broadcast.p2pServerValue') }}
				</p>
			</div>

			<button
				type="button"
				class="pptx-vue-broadcast-stop w-full rounded border border-red-500/30 bg-red-500/10 px-3 py-2 text-[12px] font-medium text-red-400 transition-colors hover:bg-red-500/20"
				@click="onStop"
			>
				{{ t('pptx.broadcast.stopBroadcast') }}
			</button>
		</div>

		<!-- Idle: configure + start a broadcast -->
		<div v-else class="pptx-vue-broadcast flex flex-col gap-4">
			<p class="pptx-vue-broadcast-desc text-[13px] leading-relaxed text-muted-foreground">
				{{ t('pptx.broadcast.idleDesc') }}
			</p>

			<div class="pptx-vue-broadcast-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-broadcast-room-id"
					class="pptx-vue-broadcast-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.broadcast.roomId') }}
				</label>
				<input
					id="pptx-vue-broadcast-room-id"
					v-model="roomId"
					class="pptx-vue-broadcast-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					type="text"
					:placeholder="t('pptx.broadcast.roomIdPlaceholder')"
				/>
			</div>

			<div class="pptx-vue-broadcast-field flex flex-col gap-1.5">
				<label
					for="pptx-vue-broadcast-server-url"
					class="pptx-vue-broadcast-label text-[12px] font-medium text-foreground"
				>
					{{ t('pptx.broadcast.serverUrl') }}
				</label>
				<input
					id="pptx-vue-broadcast-server-url"
					v-model="serverUrl"
					class="pptx-vue-broadcast-input w-full rounded border border-border bg-background px-3 py-1.5 text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
					type="text"
					placeholder="ws://localhost:1234"
				/>
				<p
					v-if="isPeerToPeer"
					class="pptx-vue-broadcast-p2p-hint text-[11px] text-muted-foreground"
				>
					{{ t('pptx.broadcast.p2pHint') }}
				</p>
			</div>
		</div>

		<template #footer>
			<DialogFooter
				:actions="[
					{ id: 'close', label: t('pptx.common.close') },
					...(props.active
						? []
						: [
								{
									id: 'start',
									label: t('pptx.broadcast.startBroadcast'),
									variant: 'primary' as const,
									disabled: !canStart,
								},
							]),
				]"
				@action="(id) => (id === 'start' ? onStart() : onClose())"
			/>
		</template>
	</ModalDialog>
</template>

// viewers/pptx/packages/svelte/src/viewer/collab/components/BroadcastDialog.svelte
<script lang="ts">
	/**
	 * BroadcastDialog: start/stop a one-way live broadcast (presenter drives
	 * slide navigation, viewers follow along via a shareable link). Svelte port
	 * of the Vue `BroadcastDialog.vue`. Only owns the start/stop UI; the host
	 * (`PowerPointViewer.svelte`) opens the actual collaboration session in
	 * response to `onstart` and supplies the resolved `viewerUrl` while active.
	 * Room-id generation, validity, and config assembly reuse the shared,
	 * framework-agnostic `pptx-viewer-shared` broadcast helpers directly (no
	 * local reimplementation).
	 */
	import DialogFooter from '../../components/DialogFooter.svelte';
	import {
		canUseClipboard,
		DEFAULT_BROADCAST_SERVER_URL,
		buildBroadcastConfig,
		canStartBroadcast,
		resolveTransportForServerUrl,
		seedBroadcastFields,
	} from 'ooxml-ui/pptx';

	import { useTranslator } from '../../../i18n/context';
	import ModalDialog from './ModalDialog.svelte';
	import type { BroadcastDialogProps } from './props';

	const { open, defaults, active, viewerUrl, onstart, onstop, onclose }: BroadcastDialogProps =
		$props();

	const t = useTranslator();

	let roomId = $state('');
	let serverUrl = $state(DEFAULT_BROADCAST_SERVER_URL);
	let copied = $state(false);
	let copyTimer: ReturnType<typeof setTimeout> | null = null;

	// Seed the form whenever the dialog opens for a fresh (non-active) broadcast.
	$effect(() => {
		if (open && !active) {
			const seeded = seedBroadcastFields(defaults);
			roomId = seeded.roomId;
			serverUrl = seeded.serverUrl;
			copied = false;
		}
	});

	const canStart = $derived(canStartBroadcast({ roomId, serverUrl }));
	const isPeerToPeer = $derived(resolveTransportForServerUrl(serverUrl) === 'webrtc');
	const title = $derived(active ? t('pptx.broadcast.broadcastingTitle') : t('pptx.broadcast.startTitle'));
	const canCopy = $derived(typeof navigator !== 'undefined' && canUseClipboard(navigator));

	function handleStart(): void {
		const config = buildBroadcastConfig({ roomId, serverUrl });
		if (config) {
			onstart(config);
		}
	}

	function onCopyLink(): void {
		if (!viewerUrl || !canCopy) {
			return;
		}
		void navigator.clipboard.writeText(viewerUrl).then(() => {
			copied = true;
			if (copyTimer !== null) {
				clearTimeout(copyTimer);
			}
			copyTimer = setTimeout(() => {
				copied = false;
			}, 2000);
			return undefined;
		});
	}
</script>

<ModalDialog {open} {title} {onclose}>
	{#if active}
		<div class="pptx-svelte-broadcast">
			<p class="pptx-svelte-broadcast-desc">{t('pptx.broadcast.liveDesc')}</p>
			<div class="pptx-svelte-broadcast-field">
				<label for="pptx-svelte-broadcast-viewer-url">{t('pptx.broadcast.viewerLink')}</label>
				<div class="pptx-svelte-broadcast-link-row">
					<input
						id="pptx-svelte-broadcast-viewer-url"
						type="text"
						readonly
						value={viewerUrl ?? ''}
						onfocus={(event) => (event.target as HTMLInputElement).select()}
					/>
					<button
						type="button"
						class="pptx-svelte-broadcast-btn"
						disabled={!canCopy || !viewerUrl}
						onclick={onCopyLink}
					>
						{copied ? t('pptx.share.copied') : t('pptx.broadcast.copyLinkBtn')}
					</button>
				</div>
				<p class="pptx-svelte-broadcast-hint">{t('pptx.broadcast.viewerHint')}</p>
				{#if isPeerToPeer}
					<p class="pptx-svelte-broadcast-server-value">{t('pptx.broadcast.p2pServerValue')}</p>
				{/if}
			</div>
			<button type="button" class="pptx-svelte-broadcast-stop" onclick={onstop}>
				{t('pptx.broadcast.stopBroadcast')}
			</button>
		</div>
	{:else}
		<div class="pptx-svelte-broadcast">
			<p class="pptx-svelte-broadcast-desc">{t('pptx.broadcast.idleDesc')}</p>
			<div class="pptx-svelte-broadcast-field">
				<label for="pptx-svelte-broadcast-room-id">{t('pptx.broadcast.roomId')}</label>
				<input
					id="pptx-svelte-broadcast-room-id"
					type="text"
					bind:value={roomId}
					placeholder={t('pptx.broadcast.roomIdPlaceholder')}
				/>
			</div>
			<div class="pptx-svelte-broadcast-field">
				<label for="pptx-svelte-broadcast-server-url">{t('pptx.broadcast.serverUrl')}</label>
				<input
					id="pptx-svelte-broadcast-server-url"
					type="text"
					bind:value={serverUrl}
					placeholder={t('pptx.broadcast.serverUrlPlaceholder')}
				/>
				{#if isPeerToPeer}
					<p class="pptx-svelte-broadcast-p2p-hint">{t('pptx.broadcast.p2pHint')}</p>
				{/if}
			</div>
		</div>
	{/if}
	{#snippet footer()}
		<DialogFooter actions={[
			{ id: 'close', label: t('pptx.common.close') },
			...(active ? [] : [{ id: 'start', label: t('pptx.broadcast.startBroadcast'), variant: 'primary' as const, disabled: !canStart }]),
		]} onaction={(id) => (id === 'start' ? handleStart() : onclose())} />
	{/snippet}
</ModalDialog>

<style>
	.pptx-svelte-broadcast {
		display: flex;
		flex-direction: column;
		gap: 16px;
	}

	.pptx-svelte-broadcast-desc {
		margin: 0;
		font-size: 13px;
		line-height: 1.5;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-broadcast-field {
		display: flex;
		flex-direction: column;
		gap: 6px;
	}

	.pptx-svelte-broadcast-field label {
		font-size: 12px;
		font-weight: 500;
		color: var(--pptx-foreground, #e2e8f0);
	}

	.pptx-svelte-broadcast-field input {
		width: 100%;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-background, #11111b);
		color: var(--pptx-foreground, #e2e8f0);
		padding: 6px 10px;
		font: inherit;
		font-size: 13px;
	}

	.pptx-svelte-broadcast-field input:focus {
		outline: 1px solid var(--pptx-primary, #6366f1);
		outline-offset: -1px;
	}

	.pptx-svelte-broadcast-link-row {
		display: flex;
		align-items: center;
		gap: 8px;
	}

	.pptx-svelte-broadcast-link-row input {
		flex: 1;
		min-width: 0;
	}

	.pptx-svelte-broadcast-hint,
	.pptx-svelte-broadcast-server-value,
	.pptx-svelte-broadcast-p2p-hint {
		margin: 0;
		font-size: 11px;
		color: var(--pptx-muted-foreground, #94a3b8);
	}

	.pptx-svelte-broadcast-stop {
		width: 100%;
		border: 1px solid rgba(239, 68, 68, 0.3);
		border-radius: var(--pptx-radius, 6px);
		background: rgba(239, 68, 68, 0.1);
		color: #f87171;
		padding: 8px 12px;
		font: 500 12px/1 system-ui, sans-serif;
		cursor: pointer;
	}

	.pptx-svelte-broadcast-stop:hover {
		background: rgba(239, 68, 68, 0.2);
	}

	.pptx-svelte-broadcast-btn {
		flex-shrink: 0;
		white-space: nowrap;
		border: 1px solid var(--pptx-border, #33334d);
		border-radius: var(--pptx-radius, 6px);
		background: var(--pptx-muted, #1f2937);
		color: var(--pptx-foreground, #f3f4f6);
		padding: 6px 12px;
		font-size: 12px;
		font-family: inherit;
		cursor: pointer;
	}

	.pptx-svelte-broadcast-btn:hover:not(:disabled) {
		background: var(--pptx-accent, #33334d);
	}

	.pptx-svelte-broadcast-btn:disabled {
		cursor: not-allowed;
		opacity: 0.4;
	}
	</style>
